### ISSUE TITLE
"wiring" and "remoteupload" extensions somehow became disabled by default. Enable them please!

### ISSUE THREAD

**Issue by BoggLog** [wiremod/wire#1005]
I was using these functions, basically these were critical for my system, and now they are gone somehow, like not even existed... What happened?

**Comment by immibis** [comment]
I don't remember these ever being in Wiremod. Are you sure it wasn't an addon specific to the server you were playing on?

**Comment by arduinium** [comment]
Make sure the remoteupload extension is enabled

**Comment by bigdogmat** [comment]
What @arduinium said, they're in wiremod but disabled by default.

**Comment by BoggLog** [comment]
Oh shit, really they were disabled both with "wiring" extension by default.
So the reason I thought they are gone was that they both were enabled earlier by default, but now I can't use them on almost any server.
Another question then: Why disabling them??

**Comment by bigdogmat** [comment]
Pretty sure they've always been disabled by default. As for the servers not having them, they could've at one point but I'm pretty sure the way extensions are enabled changed a few months ago so that could've reset what they had enabled.

**Comment by BoggLog** [comment]
well... so, Do I need to create another issue for that then?
Because personally I don't see any reason for them being disabled by default, and that breaks tons of already written e2's, targeted at using these from scratch, which were already working for maybe 2 years or so...

**Comment by arduinium** [comment]
As bigdogmat said, those extensions weren't meant to be enabled, but there was a bug which allowed to use disabled extensions as if they were enabled. Now the bug has been fixed, so the server owners must manually enable the extensions (command is wire_expression2_extension_enable)

**Comment by immibis** [comment]
@BoggLog You don't see *any problem, at all* with allowing E2s to edit other E2s?

**Comment by BoggLog** [comment]
Well, so it was a bug. But who knew of that? They were still working and there were no problems with them as far as I could see... well, let's put that on discussion then, ok?

**Comment by Nebual** [comment]
Given that they were accidentally enabled for years and nobody complained much,  I'd vote for just enabling them, so servers that don't want Skynet can opt out by disabling them.

**Comment by BoggLog** [comment]
voting is now here #1007
