### ISSUE TITLE
Enable wiring and remoteupload extensions by default?

### ISSUE THREAD

**Issue by BoggLog** [wiremod/wire#1007]
I suggest to discuss this, because they were actually working for at least 2 years.
It turned out to happen because of some bug, which is now fixed.
And now they are disabled and not working, because, everybody knows, 99% of servers keep settings by default.
So that bug fix created a situation when e2's, written using functions from these extensions, became useless, until you are in single player or some rare kind of servers.
Personally I love these and used them in many e2's.
Wiring extension allows to connect things automatically, which just saves a lot of time and is very very useful. 
And remoteUpload is the only possible way to make such a thing like compiling your own language to native e2 code and running it automatically. Possibilities are endless: Auto-updating, preprocessing e2+ with macroses to use framework functionality (my case), and everything making e2-computers possible.

So, in facts:
#### Pros:
- saves time
- makes cool automation possible (auto-connecting EGP's and much more)
#### Cons:
- a little more functions overall
#### Pros:
- makes great things possible, like compiling, preprocessing, etc.
- makes self-updating e2's possible
- saves time for tasks, also possible by hand
#### Cons:
- a little more functions overall
#### Note:

somebody said in previous topic, that it is not safe. But AFAIK it's works exactly the same way like if you would generate some e2 in e2, open it in your e2 editor and remotely upload to any of your e2's, only on server's side, so there is nothing new but automation.

**Comment by AbigailBuccaneer** [comment]
From what I can see the real argument for them is "@BoggLog spent lots of time writing something that uses these, and would now like to show off their contraption on public servers". That's not a particularly compelling reason.

Given that we are consistently being complained at for things like users accidentally copying other people's E2s and then people intentionally writing malicious E2s (see #929), I think `remoteUpload` and `wiring` are really quite dangerous.

**Comment by BoggLog** [comment]
Well, I'm into that too.
It's always about Pros&cons.
Of course, I'm interested in it myself, and I don't think I'm the only guy using these.

As a case, these were already working for a long time, and I didn't get into issues like you mentioned about. About that issue, I think, it's not the problem of anything technical, it's only the matter of trust, people relations, etc.

My opinion on security, trust and such things, involving these:
You must be able to only update e2's which you own. If you want to collaborate with somebody - make e2 itself to do it - I mean write some protocol, etc. This is what makes it fun, interesting, useful.
If you are admin, and you give somebody ownership on your props, e2's - you must think yourself about your trust to that person and know possible consequences. All said. That also helps to learn this life, and that's what games are made for...

**Comment by Divran** [comment]
I use both these extensions all the time. The solution is to enable them and then you're done.

>If you are admin, and you give somebody ownership on your props, e2's - you must think yourself about your trust to that person and know possible consequences. All said. That also helps to learn this life, and that's what games are made for...

This is why people are complaining. E2 has too much power if you share prop protection, and people are fucking stupid, so they blame us when their gmod is "hacked".

**Comment by BoggLog** [comment]
> This is why people are complaining. E2 has too much power if you share prop protection, and people are fucking stupid, so they blame us when their gmod is "hacked".

Haha, as always. But it only depends on your reaction to that. I wouldn't treat other's personal problems, happening just because of their stupid actions, like mine.

Well, I think I need to start a WIP to show what exactly I'm talking about. Probably I'll do that in half a year or so.

**Comment by TomyLobo** [comment]
So essentially it's your minor personal inconvenience versus others' stuff getting stolen. Yes, I don't think we should treat them alike.

**Comment by Divran** [comment]
>So essentially it's your minor personal inconvenience versus other people's stuff getting stolen.
You are right, we shouldn't treat them alike.
there is no way to steal other people's code with E2, even with the remote functions enabled. Only way to steal code is to dupe the E2 (which requires PP) or be an admin.

**Comment by immibis** [comment]
I vote no, because even regardless of the security problems, having E2s do everything is silly and makes the whole rest of Wiremod pointless.

**Comment by oldmud0** [comment]
I vote yes. I trust that the Wire team does not deliberately make their extensions security-prone if they are supposed to be useful and available to the public, and it's the responsibility of serious server owners to lock the servers down themselves through the use of permissions systems.

**Comment by arduinium** [comment]
In my opinion every extensions should be enabled by default.

**Comment by immibis** [comment]
While we're talking about extensions, the HTTP extension seems particularly dangerous. If the server is hosted on a typical home network, imagine rebooting the router, or changing the temperature on a wireless thermostat, or something along those lines. (Many networked home devices implicitly trust the whole network)

It's also been shown to be possible to send spam mail over a HTTP POST request (by connecting to an SMTP server, and sending POST data that looks like an SMTP session), although I don't know if Garry's Mod allows that, and E2 doesn't allow POST requests anyway.

And at the very least you could get a few players together to spam API requests to Reddit and get the server IP-banned from Reddit.

**Comment by Nebual** [comment]
I completely agree with @immibis 's point on HTTP, that should definitely be disabled by default.

I vote Wiring and Remote Upload be enabled by default, since they're both restricted by prop protection anyway, so they're precisely as secure as a regular user.

**Comment by immibis** [comment]
If it was up to me, I'd probably disable all extensions except for `serialization`, `file`, and potentially `ranger`, `sound` and `find`. Players on my server should have to work for their results.

Which means this is a question of: if a server owner with little knowledge of Wiremod just installs "Wiremod", how much stuff should their server get? It's ultimately the same question as "what should we move from UWSVN to wiremod core?" and "should the CPU be moved to a separate addon?" but in disguise.

**Comment by Divran** [comment]
Side note: remoteUpload is not restricted by PP. It's forced to owner only.

**Comment by BoggLog** [comment]
> E2s do everything is silly and makes the rest of Wiremod pointless.
True. Like having github disconnects people, makes them lonely, unhealthy, unhappy and makes a lot of office's collaborative work pointless.

> If the server is hosted on a typical home network, imagine rebooting the router
Implement cookies and add POST requests, then make E2 to brute passowrds, then yes.

> changing the temperature on a wireless thermostat
Same

> It's also been shown to be possible to send spam mail over a HTTP POST
Yeah, which is impossible in e2. So?

> And at the very least you could get a few players together to constantly send API requests to Reddit and get the server IP-banned from Reddit.
The only thing which is probably practically possible.
How about, probably, adding a filter of urls? You could just add a text file with blocked url's or masks, and filter these.

**Comment by Divran** [comment]
The 256 limit sounds like umsg. gtables are all serverside, so they don't use umsg or net messages. The problem is not with gtables.

**Comment by BoggLog** [comment]
This is weird then\ It happens in a part where I'm just working with gtables, tables, and resetting 4 e2's. It used remoteSetCode, but I disabled that for testig and it stil happens\ Well, we'll see later today

**Comment by AbigailBuccaneer** [comment]
@BoggLog @Divran please take it back to #1006.

**Comment by BoggLog** [comment]
Was just messing around on a server with 450+ hrs players. Guess what. Of cause, remoteUpload is disabled. By default. Owner just never used it. This is ruining e2.

**Comment by immibis** [comment]
@BoggLog E2 is not ruined just because remoteUpload is disabled. Whatever you're trying to do can almost certainly be done without remoteUpload. That's like saying E2 is ruined because propcore is disabled.

**Comment by bigdogmat** [comment]
@BoggLog I don't see how it's ruining E2, only time I'd see this to be 100% necessary is if you were trying to dynamically write code and run it on an separate e2 which if it is, just make something else, I can think of a million things you can do without remoteUpload but maybe 5 that'd require it.

**Comment by BoggLog** [comment]
> Whatever you're trying to do can almost certainly be done without remoteUpload.

How would I compile my internal extended e2 language to native e2 then? Interpreting it? That's 1k times slower, unuseable. How would I make e2 to update self through http? Do you remember old e2's like "toybox"? (yes, disabling http is ruining e2 too and even more and for much much more cases and people, though many good server's admins know about it and will enable it, so I hope it won't be so massive)

> Do you also believe that having propcore default-disabled is ruining E2?

Almost everybody know about it, so I rarely see servers on which it's disabled. So no.

> I don't see how it's ruining E2

Imagine that you just found that extension very useful for your contraption. Such a useful that it can't exist without it. Then you wasted 1k hrs of your life writing that. And all was fine and working for years. And after that somebody tells you: "if you were trying to dynamically write code and run it on an separate e2 which if it is, just make something else", taking in consideration that there were not any problem with it for years while it was enabled.

**Comment by immibis** [comment]
> How would I compile my internal extended e2 language to native e2 then? Interpreting it? That's 1k times slower, unuseable.

You don't need remote upload to compile things. Compiling is the process of transforming one form of code to another - nothing to do with uploading. If you want an enhanced E2 language, have you considered either not making the compiler an E2 itself, or writing to the `>e2shared` directory (which is visible from the E2 editor, so you can easily upload those files yourself), or requesting a `printConsole` function and copy-pasting the resulting code from your console?

> Almost everybody know about it, so I rarely see servers on which it's disabled. So no.

What about tracesystem? Constraintcore? Effects? Camera? It doesn't take much imagination to think of contraptions where each of those would be useful, yet they're default-disabled. (Note: tracesystem and camera are from UWSVN)

> Imagine that you just found that extension very useful for your contraption. Such a useful that it can't exist without it. Then you wasted 1k hrs of your life writing that.

If you want to use it, the solution is to enable it. It's really no different from:

* You make a contraption on a server.
* You accidentally use a thing from an addon that most servers don't have.
* Now you can't use your contraption on most servers, because it requires that addon.

Default-disabled extensions are effectively addons to E2, that are included in Wiremod only for convenience of distribution (it's easier than having another 5 Git repositories and workshop items).

If you made a contraption that uses (for example) ACF, and then find out most servers don't have ACF, you wouldn't ask ACF to piggy-back on Wiremod so that most servers will get it. Server owners who want ACF are free to install it. If it does not fit in Wiremod, it should not be part of Wiremod by default.

**Comment by Divran** [comment]
>This is ruining E2 ... 500 lines of butthurt

Just ask the admin to enable them holy shit

**Comment by BoggLog** [comment]
> You don't need remote upload to compile things.

Yes, but I am currently building PC-thing, which means it must not only compile, but run compiled code on the fly by itself. I made fully functional e2+ editor in e2/egp for that, and am currently merging it's parts of functionality: advanced string editor, working with pre-made charsets, including russian and other multi-byte ones, realtime syntax highlighting with rendering engine, dynamic selection feature, etc. It's grown pretty complex now.

> What about tracesystem? Constraintcore? Effects? Camera? It doesn't take much imagination to think of contraptions where each of those would be useful, yet they're default-disabled. (Note: tracesystem and camera are from UWSVN)

I would enable them too. They have nothing such abusive or anything. I just care more of what I'm saying. Used tracesystem and it's great too. But you can replace it with just e2. What you can't do with remoteUpload and http.

> Now you can't use your contraption on most servers, because it requires that addon

You are right. The problem is that I don't just make something to show off on different servers and all. I make it to be useable by others when released. And no, it's not likeannoying drunk-combine thing, not the one wasting shitload of ops (its very optimized and runs idling on 100-200ops). And it enables users to write/use downloaded apps, connected to their contraptions, using it's API mixed with native e2 and then being compiled. It still needs a lot of work, but that's what it is about.

**Comment by BoggLog** [comment]
> Just ask the admin to enable them holy shit

Sounds easy. Turns out nearly impossible. I don't play gmod every day/week/even not every couple of months, and I don't have so much time for that. I can't admin anything including my server because of that. And with these disabled by default any time I want to work on my e2pc or something, usually on servers of my friend's choise, I would now have to find their owner first, explain him somehow what I want, why and how can he enable that... this is just impossible in most cases, and will took a lot of time in others, instead of just playing, writing e2s and having fun.

**Comment by BoggLog** [comment]
So this discussion just came somehow to http...

But. What about this topic? Wiring and remoteupload to be exact. 
_WHY_ would you even think of disabling them, after 6 yrs they were working fine, having no problems at all (and area copy doesn't count, its just adv.dupe2's problem, not how it should work. Same with owner not changed when uploading)?

**Comment by bigdogmat** [comment]
No one thought of disabling them, they were disabled to begin with and were only working because of a bug.

**Comment by BoggLog** [comment]
> No one thought of disabling them, they were disabled to begin with and were only working because of a bug.

Exactly. For six years. And nobody knew it was a bug.

**Comment by arduinium** [comment]
Yes, as a player, it's annoying to go on a server and realize that your favorite E2 extension is not enabled. But as an admin, you don't want everyone to be able to use constraintcore for example, considering how easily it can crash a server (even unintentionally). In fact I always wanted a permission system with which an extension could be enabled for a specific player (then restriction mods like URS could use this feature and manage E2 extensions per user groups), I never looked into it but I should, maybe in a few days. And "sorry" for fixing this bug, but it was needed for serious servers.

**Comment by BoggLog** [comment]
@arduinium I was not saying about constraintcore, lightcore, and some others. They at least have a reason to be disabled. What I can't say about remoteUpload and wiring in any way, unless there are some bugs involving them and still not solved. So I think the best solution will be to merge that adv.dupe 2 fix and finally solve this #929. And after that enable these two, at least, and maybe tracing, if there's no reason to have it disabled too.

"Thank you so much" for fixing that "bug", it was annoying everybody for so many years... xD

**Comment by AbigailBuccaneer** [comment]
@arduinium, genuinely, thank you for fixing that bug. That bug meant that server owners had very little control over what kind of nonsense they want to allow or disallow. Don't apologise just because of one loud entitled user.

**Comment by CaptainPRICE** [comment]
Damn. I'm voting :+1: for enabling `remoteupload` and `wiring` extensions by default.
It would make a lot of my E2s simpler to use (and yeah as already mentioned, save time).
To that end, for the love of E2, do NOT disable `http` by default (all of my upcoming E2s will rely on http as I will integrate an advanced auto-updater library I am working on). Keep http extension enabled, and instead of doing a blacklist - make a whitelist.

**Comment by suunrider** [comment]
http got disabled 2 months ago

**Comment by CaptainPRICE** [comment]
@suunrider derp

**Comment by bigdogmat** [comment]
@CaptainPRICE That's only because the workshop version of wiremod hasn't been updated in 7 months

**Comment by arduinium** [comment]
No that's only because http was only disabled **by default**. On existing servers, if this extension was enabled prior to this update, it will still be enabled unless server owner manually disable it or delete server.db.

**Comment by bigdogmat** [comment]
It would only be enabled if the server changed it once before, as the status of an extension is only saved when changed.

**Comment by arduinium** [comment]
You are wrong.

**Comment by Divran** [comment]
nope he's right

**Comment by arduinium** [comment]
Just look at the code... If there is no row in sv.db for an extension, then one is created and filled with the default value of this extension. From then, e2 will use the value from sv.db, end of story.

The only way to force the status of an extension on all servers, would be to add code to somehow delete the row of this extension in sv.db, so that it is recreated with the default value.

**Comment by bigdogmat** [comment]
Weird, last I checked extensions.save wasn't in the preload function, my mistake.

**Comment by arduinium** [comment]
So I had a look at previous code. It didn't automatically save the default value to sv.db.

When I rewrote this extension loading/saving thing, I didn't think it would be an issue to just save the default value in sv.sb. Now I realize it was maybe a mistake to do that.

What do you think? Changing the actual code so that it doesn't save the default value to sv.db should be pretty simple, something like changing E2Lib.RegisterExtension from:
```Lua
if extensions.status[ name ] == nil then
	E2Lib.SetExtensionStatus( name, default )
end
```
to:
```Lua
if extensions.status[ name ] == nil then
	extensions.save = false
	E2Lib.SetExtensionStatus( name, default )
	extensions.save = true
end
```

**Comment by bigdogmat** [comment]
It'd make it easier to change default extension status if something were to go wrong.

**Comment by Divran** [comment]
oh right, the extension loading code was rewritten/updated/whatever. I
forgot that

**Comment by TomyLobo** [comment]
@arduinium guh, thanks for breaking my code...
Did that hit the workshop yet?

**Comment by arduinium** [comment]
The reason I decided to rewrite your code is because it didn't work correctly. I don't remember why I needed to rewrite it all, but as far as I know there wasn't an easy fix. The main problem was the Error function didn't stop the extension from being loaded, but there was other small problems.

**Comment by TomyLobo** [comment]
So, did it hit the workshop yet?
i.e. is it too late to fix?

**Comment by CaptainPRICE** [comment]
@TomyLobo See comment by @bigdogmat above.
Update: 16 Jun, 2015 @ 2:11am
[Changelog](https://github.com/wiremod/wire/compare/79a87ec...1fec41c).

**Comment by bigdogmat** [comment]
@TomyLobo The last workshop update was pushed right after all the fixes were done. I'm guessing because the issue of them being disabled but not actually disabled was a major issue.

So now the question is how do we fix the new issue of changing the default state of extensions without messing up the custom config of the server.

**Comment by TomyLobo** [comment]
I'm out, this is too depressing.
I implemented that feature with a single purpose and right before it's needed, someone breaks it...

**Comment by arduinium** [comment]
Sorry, errare humanum est... It's not impossible to salvage.

One solution would be to create a new table in sv.db with a different name, and if the old table exists, fill the new one with rows from the old but discarding the "http" row, and finally delete the old table. Apply the other fix that bigdogmat described above, problem solved.

Another solution, which I think is better, would be to just create a new empty table with a different name, delete the old table if it exists, and apply the fix I posted above to not save default status... Of course that means servers owner will have to setup their extensions again... No big deal, right?

Shit happens, once again I'm sorry...
