### ISSUE TITLE
Creating convars in entity's shared file?

### ISSUE THREAD

**Issue by MStruntze** [wiremod/wire#1008]
Isn't it pretty stupid to create convars for ops quota in here: https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/shared.lua
So you as server owner can't change it within your server config?

**Comment by oldmud0** [comment]
I don't see the problem.

**Comment by MStruntze** [comment]
The convars aren't created before the first E2 entity is created. Meaning that the convar values set in your server.cfg for example isn't used.

**Comment by immibis** [comment]
@MStruntze Yes they are...

**Comment by MStruntze** [comment]
@immibis I see. I just concluded that since it wasn't applied from my config, it could be that reason.
Thanks for making that clear.

**Comment by bigdogmat** [comment]
The convars aren't created until wiremod has initialized, so they won't load from your config file.
