### ISSUE TITLE
HL-ZASM Strings

### ISSUE THREAD

**Issue by suunrider** [wiremod/wire#1011]
In HL-Zasm you can write strings like: ```"Text'```, ```'Text"``` or ```'Text'```. The character ```'``` isn't only used for characters in HL-Zasm. This behavior prevents to define a ```'``` in the string, however you can define it with ```\'```. In ANSI C you can define such strings: ```"Text: 'Text'"```.

**Comment by AbigailBuccaneer** [comment]
Other languages which accept both ensure that they're paired correctly, and allow the other delimiter inside them. For example, Python allows `"foo 'bar' baz"` and `'foo "bar" baz'`, but not the `"foo'` or `'foo"` which HLZASM does.
