### ISSUE TITLE
Add UUID generation function and per-server UUIDs

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#1013]
We should be able to generate [version 4 UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29) as strings fairly easily. Assigning each server a persistent UUID means per-server storage for E2 chips would be easy.

Originally mentioned in #1010.

**Comment by AbigailBuccaneer** [comment]
Just wrote:

```Lua
-- uuid.lua - generation of RFC-4122 UUIDs

module("uuid", package.seeall)

--- Generate a random version 4 UUID. (The random number generator
--- used is math.random so it should be seeded with math.randomseed)
function generate()
  local words = {}
  for i = 1, 2 do words[i] = math.random(0, 0xFFFF) end
  words[3] = math.random(0, 0x0FFF) + 0x4000
  words[4] = math.random(0, 0x3FFF) + 0x8000
  for i = 5, 8 do words[i] = math.random(0, 0xFFFF) end

  for i = 1, 8 do words[i] = string.format("%04x", words[i]) end

  return words[1] .. words[2] ..
         "-" .. words[3] .. "-" .. words[4] .. "-" ..
         words[5] .. words[6] .. words[7] .. words[8]
end
```

**Comment by Divran** [comment]
I'm pretty sure `math.randomseed` is already seeded by gmod when the server
starts. Also we could just put that function in wirelib instead of making
it its own module.

**Comment by AbigailBuccaneer** [comment]
@Divran it's written as a module because I haven't run Garry's Mod in months, and don't actually have my own computer at the moment - so I wrote it like I would write a standalone library so I could test it from a Lua REPL.

**Comment by immibis** [comment]
Is there any reason it has to be a UUID, as opposed to a plain random hex string?

**Comment by TomyLobo** [comment]
shits and giggles? :)

It's essentially free, because we only have to generate it once

**Comment by TomyLobo** [comment]
@AbigailBuccaneer 
looks ok, but i'm not sure about the range of math.random on windows. Did you see if it spits out every possible number in that range?

**Comment by AbigailBuccaneer** [comment]
@immibis because standards are cool!

@TomyLobo:

> math.random(lower, upper) generates integer numbers between lower and upper.

Even if there is some upper range that it'll silently fail over, we only ask for random numbers less than 2¹⁶, which is less than that limit ever seems to be in any naive random number generators. (That being said, I don't have a Windows machine at the moment - this code was only tested on `lua5.2`, not even in Garry's Mod.)

**Comment by TomyLobo** [comment]
generating this bytewise would probably be more reliable and probably easier to read as well :)

**Comment by TomyLobo** [comment]
@AbigailBuccaneer 
![standards are cool] (https://i.imgflip.com/txj2t.gif)

**Comment by immibis** [comment]
@AbigailBuccaneer what is one scenario where it's useful for these to be in UUID format?

If there are none, it's needless complexity, which is always bad.

**Comment by AbigailBuccaneer** [comment]
@immibis as I said, interoperability. Plenty of things use UUIDs for unique identifiers, and given that E2s can talk to the outside world with HTTP it's quite useful to be able to generate them. Also, standards are cool.

(Besides, if BoggLog preprocesses their E2s, I'm going to automatically generate Visual Studio project files for me from the E2 script itself, which requires UUIDs...)

**Comment by immibis** [comment]
@AbigailBuccaneer Okay... what's an external service that requires the user to supply a UUID?

If you generate VS project files, presumably you need a new E2 for each project, not just each server, so you want to generate them in E2 anyway.

**Comment by TomyLobo** [comment]
we can reduce the code complexity a bit by putting it as string.format("%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x%02x%02x", unpack(words))

also, generate words in a plain and simple loop and then create the exceptions by masking
