### ISSUE TITLE
Adv Duplicator 2 + Wiremod crash upon pasting.

### ISSUE THREAD

**Issue by dafoxx** [wiremod/wire#1014]
I have a build server running, when ever someone's build are set down (not all) it crashes the server console how ever it dosn't close, there are no console errors other then the last thing it tried to create then just locks up. we are running the latest SVN version

**Comment by AbigailBuccaneer** [comment]
@dafoxx can you make sure you're running the latest GitHub versions of both Wiremod and AdvDupe2? We [took over development of AdvDupe2](https://github.com/wiremod/advdupe2) because the original author gave up on it, but lots of people are still using the old Google Code SVN version.

**Comment by dafoxx** [comment]
thank, we are now running the latest, ill keep you posted later on when its busy.

**Comment by oldmud0** [comment]
By the way, AdvDupe1 still looks terribly ugly.

**Comment by dafoxx** [comment]
been running it, still crashed on a single dupe, could a reinstall of the server help maybe?

**Comment by thegrb93** [comment]
Give the dupe file so we can test it.

**Comment by dafoxx** [comment]
I don't have the dupe at hand as its other players, but give me a bit and ill try get hold of one.

**Comment by dafoxx** [comment]
Turns out, My friend changed the Steam collection and added the Wiremod from there, along with the latest on here in addons, no crashing now!
