### ISSUE TITLE
E2 editor "right click › save as" option works on wrong tab (previous)

### ISSUE THREAD

**Issue by BoggLog** [wiremod/wire#1015]
Basically, title says it all. It happens every time to me, so I need to add one tab to save the last one.
This is a bit of dangerous because you can easily occasionnaly overwrite something.

**Comment by brandonsturgeon** [comment]
I've lost 2 good E2's to this :(

**Comment by AbigailBuccaneer** [comment]
Is this via the *Save As* menu button, or via *right click on tab › Save As*?

**Comment by brandonsturgeon** [comment]
@AbigailBuccaneer You're right, I did consider it after the second time. But I couldn't rule out the possibility that I just did something dumb. I was going to make sure it was a problem before I said anything.

**Comment by BoggLog** [comment]
@AbigailBuccaneer Sure for right clicking, I'll check the menu later

**Comment by BoggLog** [comment]
It works from menu, so only for right clicking

**Comment by brandonsturgeon** [comment]
👍 Thanks @Nebual !
