### ISSUE TITLE
The internal workings of disabling E2 extensions are silly and over-engineered

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#1016]
- [`E2Lib.RegisterExtension`](https://github.com/wiremod/wire/blob/9847ecf5bee18184fcc32d98738422961a2e6461/lua/entities/gmod_wire_expression2/core/e2lib.lua#L464) throws an assert with a particular message if the extension is disabled
- Files are then included by calling `CompileString`, and `pcall`ing the resulting function. The error message is then [searched for the particular error message](https://github.com/wiremod/wire/blob/9847ecf5bee18184fcc32d98738422961a2e6461/lua/entities/gmod_wire_expression2/core/extloader.lua#L107).

Why not just have `E2Lib.RegisterExtension` return whether it's enabled or not, and then extensions could start with `if not E2Lib.RegisterExtension(...) then return end`? It seems this would be a much less fragile approach.

**Comment by Divran** [comment]
Sure I guess? Why not

It would also allow us to make smaller extensions inside a file, such as one for the applyForce functions, which are all inside the entity file.

**Comment by AbigailBuccaneer** [comment]
@Divran Are there E2 extensions around and in use that aren't in Wiremod or `wire-extras`?

**Comment by Divran** [comment]
I would say yes. Why

**Comment by TomyLobo** [comment]
Yeah it's all my fault.
It seemed clever at the time.
In my defense, that was before we knew that having many files is bad.

**Comment by AbigailBuccaneer** [comment]
If there are unofficial E2 extensions then they can't be updated to use a new method - and so we'd have to add a new method *alongside* the old method, which kind of defeats the point of doing this as cleanup. I'm not convinced this is worth it, thoughts?

**Comment by Divran** [comment]
Change it anyway, fuck other extensions?

**Comment by bigdogmat** [comment]
Most 3rd party extensions I've seen are still being maintained, so if this was changed I'm sure they'd get updated.

**Comment by AbigailBuccaneer** [comment]
I guess this also wouldn't be such an issue because server owners who've installed third-party extensions are unlikely to then want to *disable* the extensions.

**Comment by immibis** [comment]
There could be addons that come with bonus E2 extensions, rather than being centred around the extension.

Think UWSVN, except not maintained by Wiremod. Maybe there's some Spacebuild expansion pack that comes with E2 functions for linking RD entities together (like the `wiring` extension but for RD links).

**Comment by oldmud0** [comment]
(Is Spacebuild even in active development?)

**Comment by immibis** [comment]
@oldmud0 Not really, but it's just an example to show it's plausible.

**Comment by immibis** [comment]
Slightly related: can applyForce be moved to an extension?

There's a small problem that `bone:applyForce` should be available only if the applyForce extension is enabled *and* the bone extension is enabled. I don't know if there are any other similar functions (that rely on two extensions), and how they handle the situation.

**Comment by Nebual** [comment]
I think the current approach is fine and we're kinda stuck with it anyway.
