### ISSUE TITLE
Make a new workshop release

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#1020]
It's been 5 months since the last push to the `workshop` branch - we should start preparing for the next one.

Please add any issues or PRs you'd like to be in the next release to the 'Next Workshop release' milestone.

**Comment by AbigailBuccaneer** [comment]
This probably won't happen for a few days because there are quite a few bugs and and PRs I was planning on working on over the weekend, but I'm now busy this weekend and will be back on Monday.

**Comment by immibis** [comment]
Does the workshop branch automatically update the workshop via some build process, or do you have to find Faron again?

**Comment by AbigailBuccaneer** [comment]
@immibis *hypothetically* it happens automagically, but I'm not sure if that actually works in practice.

**Comment by TomyLobo** [comment]
I hear it usually does, but sometimes Faron needs to be poked to restart the contraption.

**Comment by AbigailBuccaneer** [comment]
Going to hold on this until we reach a resolution to #965, which I probably shouldn't have pulled.

**Comment by bigdogmat** [comment]
This can be closed as well
