### ISSUE TITLE
Wire Keyboard "synchronous" flag is unintuitive

### ISSUE THREAD

**Issue by immibis** [wiremod/wire#1024]
The Wire Keyboard tool has a "synchronous keyboard" checkbox.

When it's checked, players who are using a keyboard will have their normal keybinds blocked; they can type W/A/S/D without moving, E without leaving the pod (if applicable) and so on.

When it's not checked, this won't happen. This makes it very difficult to actually type anything.

Moreover, this flag is per-client, not per-keyboard, and defaults to off. So if you make a contraption that lets users type things with the keyboard (using a CPU or E2) you'll have to tell everyone who uses your contraption to turn on the checkbox, which isn't even easy to find.

I suggest that it should apply to the keyboard (meaning some keyboards can be synchronous and some asynchronous) and default to synchronous (since that's how you'd expect a keyboard to work - it captures all of the user's input and prevents the normal stuff happening). Any objections?

(And is asynchronous mode even useful? If not, it could be removed)

**Comment by Divran** [comment]
What, no, this should be per keyboard

**Comment by thegrb93** [comment]
Just replace "Synchronous" with the text label that's above it.

**Comment by immibis** [comment]
@thegrb93 Doesn't solve the problem of having to tell everyone who uses your contraption to check it.

**Comment by immibis** [comment]
Closing this - see #1025.
