### ISSUE TITLE
Move `table.*` to a Garry's Mod pull request

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#1033]
We currently add things like [`table.IsEmpty`](https://github.com/wiremod/wire/blob/fb2f6204f09e692908ca910193a2257d7cadee73/lua/wire/wireshared.lua#L23), that'd make more sense to be in Garry's Mod than Wiremod. Garry's Mod [already adds a bunch of `table.*` functions](https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/includes/extensions/table.lua), it'd be nice to add ours to there.

We also have similar functions like [`pairs_sortkeys`](https://github.com/wiremod/wire/blob/fb2f6204f09e692908ca910193a2257d7cadee73/lua/wire/wireshared.lua#L58) that would be nice to get rid of too. Ideally we shouldn't be defining any globals other than WireLib.

**Comment by Divran** [comment]
:+1:

**Comment by TomyLobo** [comment]
make sure you call table.Compact table.Filter, table.Select or table.Reject

**Comment by oldmud0** [comment]
Meanwhile on the pull requests currently being processed over there:
```
+ tool.leafblower.desc=This tool is the most important aspect of Garry's Mod
```

**Comment by thegrb93** [comment]
garrysmod doesn't merge PRs

**Comment by bigdogmat** [comment]
We can remove `table.IsEmpty` after the next update.
