### ISSUE TITLE
Rendering script on client-side EGP entity

### ISSUE THREAD

**Issue by matiasah** [wiremod/wire#1036]
Hello,

Sending multiple objects to be rendered on EGP costs a lot of network usage, so I had the idea of making the EGP able to load a "rendering script" which does the same EGP operations made in E2 but on client-side so sending those objects via user-messages does not become a heavy task, especially for radars which need to update all the visible objects every X time.

<b>Why don't you use GPU instead?</b>
Firstly because it's hard to learn, and secondly because most people prefers to use EGPv3 over GPU.

<b>Why don't you use Expression Advanced 2?</b>
Because it's a completely different addon, the idea I had on mind was to keep the current functionalities of EGP and integrate this lightweight "rendering script" functionality in it, so every server that has wiremod will be able to run it.

<b>Developers don't have time to do that.</b>
I can offer myself to do this, and if it works fine, it could be added to wiremod depending on what you think about the results.

<b>How do you plan to make it?</b>
1. EGP should be able to receive a Lua script from the server which has some functions available for rendering, it may be able to receive calls from it's TriggerInputs and it will update the client-side objects.
2. The rendering script will run in a protected environment.
3. The Lua functions must have the same names as the E2 functions so everyone will guess how to use it (egpText, egpBox, egpLine, etc)
4. There's no Lua-syntax for wiremod's text editor, so a E2 function must be created in order to upload the rendering script, at least until someone decides to make a Lua-syntax for the text editor.
(void entity:egpRenderScript(string script) sounds likely to be a good candidate for a function name).

Any opinions/suggestions?

**Comment by thegrb93** [comment]
You'd also need a data pipeline so the server is able to provide data to the render script. I would suggest starfall instead which is already lua and has net library support.

**Comment by Starkkz** [comment]
Yeah, but the only way that this gets available everywhere is that it's built-in wiremod, starfall is also another separate addon, it's the same as suggesting to use Expression Advanced 2.

**Comment by TomyLobo** [comment]
This would be possible using that "generic e2-to-client-lua interface" proposal i keep pitching
essentially you'd have the E2 talk to a client-side lua script, which then does whatever it wants

**Comment by Divran** [comment]
In your interface, how would you tell the client side lua what to do?

**Comment by TomyLobo** [comment]
This client code would be player-specifiable.
Yes, there would be an unchanging thunk to do marshalling between the server and client, but that's about it.
Where do you see the problem modifying client-side code?
After all we can just load something from the data folder.

**Comment by thegrb93** [comment]
>there would be an unchanging thunk to do marshalling between the server and client

wut

**Comment by TomyLobo** [comment]
I replaced the big words

**Comment by AbigailBuccaneer** [comment]
Wasn't there an almost identical proposal for something like this a long time ago?

Frankly, I'm think any E2-to-client-Lua interface would be quite horrible, given the current state of E2. I still have grand faraway plans for an E3 language - maybe it should be possible to write both serverside and clientside code?

**Comment by TomyLobo** [comment]
what would be the use case for adding a new interface between E2 and server-side lua?

**Comment by Divran** [comment]
>After all we can just load something from the data folder.

Then you would have to also send that code to every other client by bouncing the file off the server, but yeah it would work

**Comment by Starkkz** [comment]
@Divran That was the idea, a editor wouldn't be coded in a very long time but at least having the possibility to send a rendering script to all the clients would make it better than having to deal with network overhead.

**Comment by TomyLobo** [comment]
>>After all we can just load something from the data folder.

>Then you would have to also send that code to every other client by bouncing the file off the server, but yeah it would work

What? That'd be a huge security risk, to allow clients to run scripts on other clients.
Don't do that.

No, the idea is to have that script on *your own* client only and have *your own* E2 communicate with it.

**Comment by Starkkz** [comment]
@TomyLobo but you can filter the required functions in a function environment, and hook a usage limit using the debug library. That's probably the quickest solution.

**Comment by TomyLobo** [comment]
that'd make this proposal completely useless

**Comment by Vurv78** [comment]
Yeah this is not going to happen. This issue is way too broad -- EGP would need to be completely redesigned, right now it's designed to be serverside sending messages to the client. Plus you'd need to either give E2 clientside support (making this kind of useless, because you could then just call render functions like starfall) or invent another language just for EGP, when you can just use EGP/GPU. And the argument for GPU being too hard has been solved with StarfallEx now.
