### ISSUE TITLE
Spawn Menu Bug

### ISSUE THREAD

**Issue by PhantomSnipz19** [wiremod/wire#1039]
Everytime I join A server the spawn menu main tools are bugged from wire mod i know this because i uninstalled wiremod and also went on servers that dont have wiremod and my tools tab is completely Normal And i also went in to single player without wiremod installed and everything looked normal and when i have wire mod in it will show my tools like it shows for wiremod on how it displays is there a way to fix that or put out a bug fix or tell me how to fix it in my settings please help its very annoying to see

**Comment by Divran** [comment]
I refuse to answer this until you write in proper readable sentences

**Comment by bigdogmat** [comment]
From what I got is the normal tool menu looks like the wire one? Post a screen shot of what you mean or explain in readable sentences.

**Comment by PhantomSnipz19** [comment]
bigdogmat you are correct with wiremod installed my tools tab with glitch and will look like the wiremod tab and without wire mod everything is normal so i know its wiremod bugging my spawn menu

**Comment by Divran** [comment]
I was about to reply "I know the answer, but you've still not written an even remotely gramatically correct sentence, so I'm not going to help you", but then I realized I'm not that big of an asshole so I'll help you anyway

Go to the wire tab. In the search box at the top, type "options". Go to the "custom wire tab options" menu and uncheck the checkbox called "use custom tab for all tabs".

**Comment by PhantomSnipz19** [comment]
thank you so much for helping me it fixed it

**Comment by oldmud0** [comment]
:clap:
