### ISSUE TITLE
Unwired Wirelink can cause Overwriting of Default Table

### ISSUE THREAD

**Issue by Steeveeo** [wiremod/wire#1041]
## Observed Behavior:

The following E2 code, when the "Unwired" input is left, well, unwired, causes the default E2 table to become writable. This then affects any and all new persisted tables that are not overwritten with "T = table()".
#### "Infection" Code:

```
@inputs Unwired:wirelink

T = Unwired["AnyNameHere",table]
T["This Value Will Appear In All New Persisted Tables",number] = 1337
```
#### Display Code:

```
@persist Test:table

#Test = table()     #If this is uncommented, the issue does not occur.
                    #Also, this issue does not occur with non-persisted tables.
printTable(Test)
```
## Steps to Reproduce:
1. Start a new online session.
2. Open the E2 tool and paste the _"Infection" Code_ E2, then place into the world.
3. Repeat Step 2 with the _Display Code_ E2.
4. Observe that the _Display Code_ E2 outputs _"This Value Will Appear In All New Persisted Tables  =   1337"_
## Notes:
1. This issue occurred when only Wiremod was installed.
2. Any value of any name and type can be written to the default table when using the above code.
3. This issue persists even after the _"Infection Code"_ chip has been removed, and is only resolved after running "wire_expression2_reload".
4. This issue does not occur when setting the persisted table with "Table = table()", or with local Tables.

**Comment by Divran** [comment]
looks like the wirelink getter function doesn't properly copy its defaults before returning them.

**Comment by TomyLobo** [comment]
I think that (#1042) should help. @Divran what do you think?

**Comment by TomyLobo** [comment]
I have a question, btw:
Why does the input serializer for arrays count stuff and increment self.prf while the input serializer for table does not? :)

**Comment by TomyLobo** [comment]
Oh I just figured out why this bug originally happened.
I designed it with 2 categories of table-based types in mind: 
1. immutable types, like vectors and such
2. mutable types whose zero element is an empty table

Someone kinda made a 3rd category out of the E2 table type (T) which is a blend of the two categories, by putting elements in that type's default element.

But maybe that has always been there in which case I messed up in the first place :)

**Comment by Divran** [comment]
Here's what I use to solve it (this function is used when you attempt to retrieve a nonexistant value from a table) https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/table.lua#L118-L121

**Comment by TomyLobo** [comment]
Your function is inefficient. you could cache all those v[x]. Would make the code easier to read as well, provided you pick good names.

And you're cloning every single table when you dont even need to.
That's just hugely wasteful. Just use the type's associated input serializer.

**Comment by Divran** [comment]
what are you talking about "when you don't need to". You always need to, because all tables are passed by reference in Lua.

So either we define "create new zero element" functions of every single table-based data type in E2, or we run `table.Copy(zero)`, which, yes, in some cases can be `table.Copy({})`

**Comment by TomyLobo** [comment]
cache all of them

**Comment by TomyLobo** [comment]
@Divran do you understand what I mean when I say "immutable"?

**Comment by Divran** [comment]
Yes I understand what you mean when you say that all values that are passed by reference must be cloned from their default value, or else the reference to the default value will be passed. That's what my code did already. If you want to modify all of the input serializers to clone the input (I just checked, only about half of them do currently) then sure, but just know that's going to be a lot more work than simply using table.Copy (which accomplishes exactly the same thing).

But I have no idea how a "cache" relates to this issue.

**Comment by TomyLobo** [comment]
cache is an informal term I use in this case for storing frequently accessed but static values as upvalues

**Comment by TomyLobo** [comment]
And no, not everything you pass by reference has to be cloned.
rangerdata is immutable (since it has no setters), so cloning is useless, since any clone is and stays equal to the original.

oh god, if you dont understand the concept of immutable types, i shudder to see what you've done to the vector types

**Comment by Divran** [comment]
I haven't touched the vector types, like at all. And I completely forgot about the rangerdata type. You're right though, it doesn't need to be cloned. And yes I already knew that using the input serializers is the better solution, it was just more effort. So go ahead and do that then
