### ISSUE TITLE
Add wirelink:fill(start, size, content)

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#1049]
Currently when writing lots of identical data (coloring digital screen uniformly, clearing HS-Memory, etc) you have 2 options:
- for-loop over every single cell, can take multiple ticks
- backup the (size+1)th cell, write a array filled with the data (can be done with logarithic complexity) and write back the (size+1)th cell (since writeArray always adds a null to arrays, even though useless, see #879).

Both have avoidable overhead, both in E2 and to lesser effect in lua, which could be avoided by having a trivial function to fill a set amount of cells with data.

Examples:
Color Digitalscreen of size 32 all white: Screen:fill(0, 32*32, 999)
Clear the second half of a 1024-Cell Memory: Memory:fill(512,512,0)

---

Something very similar i could also see being useful to a certain degree, like for screens and certain memory structures: Memory:fillPattern(0,5,array(999,666,333,0,NaN)) which would repeat that Pattern 5 times, but leaving the Nan-ones as they are. 
Pseudocode:

```
memory:fillPattern(start,count,pattern):
for(i=1,#pattern){
    if(pattern[i]==NaN) continue
    for(j=1,count){
        memory[start+j*#pattern]=pattern[i]
    }
}
```

**Comment by TomyLobo** [comment]
If you absolutely need patterns, how about having a "step" parameter for fill instead?
That way you could interleave the pattern and wouldn't even need some NaN stuff to skip cells

But... this looks like another way to crash the server, so be careful whoever implements this.

**Comment by thegrb93** [comment]
I believe writeArray or writeString accomplishes this

**Comment by thegrb93** [comment]
Oh wait nvm you want something akin to 'memset' I see

**Comment by thegrb93** [comment]
writeString with rep() should work

**Comment by adosikas** [comment]
Doing something like this now, works well enough.
```golo
RepeatedArray = Pattern
for(I=floor(log2(Count)-1),0,-1){
  RepeatedArray=RepeatedArray:add(RepeatedArray)
  if(Count&&2^I){
    RepeatedArray = RepeatedArray:add(Pattern)
  }
}
writeArraySimple(RepeatedArray)
```
