### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by immibis** [wiremod/wire#1050]
Not a code issue, and you might already know, but http://wiremod.com/ is down (it shows that CloudFlare timed out waiting for the server to respond)

**Comment by Divran** [comment]
I've been trying to reach @FaronFox

**Comment by bigdogmat** [comment]
This happens every few months and last for about a week.

**Comment by AbigailBuccaneer** [comment]
It's up.

**Comment by immibis** [comment]
And it's down again.

@bigdogmat @Divran If the website goes down a week every few months... surely you need better hosting?!

**Comment by Divran** [comment]
The problem is the host (faron) is extremely hard to get a hold of. I've
been sending messages at faron every time it goes down. Usually it takes at
least 2 weeks to even get a response.

**Comment by bigdogmat** [comment]
^ and #1114

**Comment by immibis** [comment]
@Divran Well then someone else should be hosting the website.

**Comment by AbigailBuccaneer** [comment]
I'd be willing to take over hosting of the website, but I don't really know what sort of infrastructure it's currently hosted on. (I'd be willing to pay hosting costs for a set of VPSs for load balancing and uptime.)
