### ISSUE TITLE
(Suggestion) remoteUpload, remoteSetCode w/ PP support

### ISSUE THREAD

**Issue by ThatOneCheetah** [wiremod/wire#1052]
Currently remoteUpload and remoteSetCode only work on the owner's chips, me myself I'd like to see this work on any PP friend ( probably CPPICanTool & cvar protection, e.g. "wire_expression2_friendremote" ).  

(Off to see what I can do by myself, if I get it working 100% reliably I'll do a request)  

**EDIT**: So far a success, added entity:remoteAllowed(), testing reliability...

**Comment by TomyLobo** [comment]
Not going to happen for very obvious very large security reasons.

**Comment by ThatOneCheetah** [comment]
Ah, I thought I'd had everything thought through, but I forgot about the possibility to remoteUpload from the expression2 folder itself, dumb of me, yeah, a possibility would be to remove any instance of remoteUpload when uploading to someone else's e2 but it's a hassle, I understand this decision, hopefully this might be possible in the future.

Once again, apologies for overlooking that code-grab possibility.

**Comment by TomyLobo** [comment]
There's also the issue of inserting code that runs with your privileges.
I'd still like to make it as hard as possible for people to put code into other people's chips.
We have one "E2 virus", we don't need another :)
@Divran your opinion?

**Comment by ThatOneCheetah** [comment]
Yeah, I guess you'd need to filter stuff like file*, remote*, perhaps http* out of it when uploading.
Would be a great hassle, I understand why you want to make it as hard as possible.

**Comment by TomyLobo** [comment]
given a language with infinite possibilities, any blacklist you devise will be no match for a bored person's creativity :)

**Comment by TomyLobo** [comment]
I wanted to throw this in, too: http://thedailywtf.com/articles/Client-side_PHP

**Comment by Divran** [comment]
Nah, the remote functions used to have the ability to be used on pp friends, but I specifically removed that because "hackers" were using it to fuck with people
