### ISSUE TITLE
Add a system to eliminate the ifs in TriggerInput

### ISSUE THREAD

**Issue by TomyLobo** [wiremod/wire#1055]
I can think of 3 ways to do it, in order of decreasing preference:
1. function ENT:TriggerInputKick(value)
2. function ENT:TriggerInput_Kick(value)
3. callbacks

**Comment by TomyLobo** [comment]
pseudo-code for base_wire_entity:
````Lua
function ENT:TriggerInput(name, value)
	return self["TriggerInput"..name](self, value)
end
````

**Comment by Divran** [comment]
I like the base_wire_entity solution
All current code will still work, we have the option of using it for new code, and it's super easy to implement.

**Comment by TomyLobo** [comment]
yeah let's discourage inputs with spaces :P

**Comment by AbigailBuccaneer** [comment]
I don't like the idea of concatenating strings to form function names - it makes more sense to store a table where the keys are input names and the values are functions.

```Lua
ENT.TriggerInput = {}
setmetatable(ENT.TriggerInput, { __call = function(triggers, self, name, ...) assert(triggers[name])(self, value) end }
function ENT.TriggerInput:Kick(value) --[[ ... ]] end
```

**Comment by Divran** [comment]
@AbigailBuccaneer but then we would have to check if TriggerInput is a function or a table, to keep backwards compatibility. That's no problem of course, but is that any better than concatenating strings?

**Comment by TomyLobo** [comment]
````Lua
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
> ENT = {}
> ENT.TriggerInput = {}
> function ENT.TriggerInput:Kick(value) --[[ ... ]] end
> function ENT.TriggerInput["I am bad at naming inputs"](self, value) --[[ ... ]] end
stdin:1: '(' expected near '['
````

**Comment by thegrb93** [comment]
Should be function ENT["TriggerInputI am bad at naming inputs"](self,value) end

**Comment by AbigailBuccaneer** [comment]
@TomyLobo Whoops, minor syntactic slipup aside, it's still possible - I just updated my comment.

@Divran we wouldn't have to check if it's a function or a table - the `__call` metamethod means it can be called like a function even though it's a table. And if entities want to override `ENT.TriggerInput` with an actual function, then they could. Nothing would change in how `ENT:TriggerInput(name, value)` gets called anywhere.

**Comment by Divran** [comment]
>we wouldn't have to check if it's a function or a table - the __call metamethod means it can be called like a function even though it's a table.

oh right yeah I read your post too fast and missed that

**Comment by TomyLobo** [comment]
me too.
But is it worth the complexity?

**Comment by AbigailBuccaneer** [comment]
I think it gives the cleanest API for defining input functions. To me at least, `function ENT.TriggerInput:Kick(value)` feels a lot nicer than `function ENT:TriggerInputKick(value)`.

**Comment by thegrb93** [comment]
Using that syntax, "self" will be the TriggerInput table.

**Comment by AbigailBuccaneer** [comment]
`self` is whatever you pass in as the `self` argument - if you were to call it directly using the same syntax it's declared with, then yes it would be - but the `__call` implementation above does the right thing. That's probably an argument that it's confusing - but it's not wrong.

**Comment by thegrb93** [comment]
Definitely confusing

**Comment by TomyLobo** [comment]
unless your port names are excessive, don't argue with cost.
1. You're completely discounting the cost of a table lookup
2. You're concatenating 2 strings with less than 20 characters each. In C.

**Comment by thegrb93** [comment]
Yeah forgot the wonkey metatable stuff

```
ENT = {}
ENT.TriggerInputTest1 = function() end
ENT.TriggerInputTest2 = function() end
ENT.TriggerInputTest3 = function() end
ENT.TriggerInputTest4 = function() end
ENT.TriggerInput = setmetatable({}, {
  __call = function(triggers, self, name, ...)
    assert(triggers[name])(self, ...)
  end })
ENT.TriggerInput.Test1 = function() end
ENT.TriggerInput.Test2 = function() end
ENT.TriggerInput.Test3 = function() end
ENT.TriggerInput.Test4 = function() end

local iterations = 1000000
local key = "Test1"
local t = os.clock()
for I=1,iterations do
	ENT["TriggerInput"..key](ENT)
end
print(os.clock()-t)

t = os.clock()

for I=1,iterations do
	ENT:TriggerInput(key)
end

print(os.clock()-t)
```
outputs
0.129
0.179

**Comment by Nebual** [comment]
I slightly prefer Abigail's approach, though we should go with the more performant. Unless we would ever want to iterate over all input functions, in which case Abigail's is way easier. 

Out of curiosity, could you rerun the benchmark with Test3, and comparing against the existing approach, with a series of if(string comparison)?

**Comment by thegrb93** [comment]
```
ENT = {}
ENT.TriggerInputTest1 = function() end
ENT.TriggerInputTest2 = function() end
ENT.TriggerInputTest3 = function() end
ENT.TriggerInputTest4 = function() end
ENT.TriggerInput = setmetatable({}, {
  __call = function(triggers, self, name, ...)
    assert(triggers[name])(self, ...)
  end })
ENT.TriggerInput.Test1 = function() end
ENT.TriggerInput.Test2 = function() end
ENT.TriggerInput.Test3 = function() end
ENT.TriggerInput.Test4 = function() end

local iterations = 10000000
local key = "Test1"
local t = os.clock()
for I=1,iterations do
	ENT["TriggerInput"..key](ENT)
end
print(os.clock()-t)

t = os.clock()

for I=1,iterations do
	ENT:TriggerInput(key)
end

print(os.clock()-t)

t = os.clock()

for I=1,iterations do
	if "Test1"==key then
		ENT:TriggerInputTest1()
	elseif "Test2"==key then
		ENT:TriggerInputTest2()
	elseif "Test3"==key then
		ENT:TriggerInputTest3()
	elseif "Test4"==key then
		ENT:TriggerInputTest4()
	end
end

print(os.clock()-t)

t = os.clock()

for I=1,iterations do
	if "Test4"==key then
		ENT:TriggerInputTest1()
	elseif "Test3"==key then
		ENT:TriggerInputTest2()
	elseif "Test2"==key then
		ENT:TriggerInputTest3()
	elseif "Test1"==key then
		ENT:TriggerInputTest4()
	end
end

print(os.clock()-t)
```
1.276
1.793
0.588
0.789

**Comment by TomyLobo** [comment]
yeah but we're not trying to get rid of the ifs because they're slow but because they're cumbersome

**Comment by Divran** [comment]
gmod doesn't have jit though does it? I thought garry disabled it because it caused problems

**Comment by TomyLobo** [comment]
are you sure that isnt obsolete news?

**Comment by Divran** [comment]
idk

**Comment by thegrb93** [comment]
With JIT and 10x more iterations I get
5.753
0.026000000000001
0.026000000000001
0.026999999999999

**Comment by AbigailBuccaneer** [comment]
@Divran @TomyLobo `jit.status() == true` on both client and server (for me, at least).

@thegrb93 This test is unrealistic because it checks the same key each time, which allows the JIT compiler to optimise for one particular codepath.

Also, if we're doing performance tests, how about tables without the metatables? It'd be nice to see how this compares to the other methods:

```Lua
ENT.TriggerInput.Test1 = function() end
ENT.TriggerInput.Test2 = function() end
ENT.TriggerInput.Test3 = function() end
ENT.TriggerInput.Test4 = function() end
for i = 1, iterations do 
  assert(ENT.TriggerInput[key])(ENT)
end
```

That said, I don't think there's a huge amount of value in performance testing these things - we should use whatever's clearest and most elegant unless it causes measurable performance problems in real-world situations.

**Comment by thegrb93** [comment]
```
ENT = {}
ENT.TriggerInputTest1 = function() end
ENT.TriggerInputTest2 = function() end
ENT.TriggerInputTest3 = function() end
ENT.TriggerInputTest4 = function() end
ENT.TriggerInput = setmetatable({}, {
  __call = function(triggers, self, name, ...)
    assert(triggers[name])(self, ...)
  end })
ENT.TriggerInput.Test1 = function() end
ENT.TriggerInput.Test2 = function() end
ENT.TriggerInput.Test3 = function() end
ENT.TriggerInput.Test4 = function() end

local iterations = 100000000
local keys = {"Test1","Test2","Test3","Test4"}
local t = os.clock()
for I=1,iterations do
	assert(ENT["TriggerInput"..keys[I%4+1]])(ENT)
end
print(os.clock()-t)

t = os.clock()

for I=1,iterations do
	ENT:TriggerInput(keys[I%4+1])
end

print(os.clock()-t)

t = os.clock()

for I=1,iterations do
	ENT.TriggerInput[keys[I%4+1]](ENT)
end

print(os.clock()-t)

t = os.clock()

for I=1,iterations do
	local key = keys[I%4+1]
	if "Test1"==key then
		ENT:TriggerInputTest1()
	elseif "Test2"==key then
		ENT:TriggerInputTest2()
	elseif "Test3"==key then
		ENT:TriggerInputTest3()
	elseif "Test4"==key then
		ENT:TriggerInputTest4()
	end
end

print(os.clock()-t)

t = os.clock()

for I=1,iterations do
	local key = keys[I%4+1]
	if "Test4"==key then
		ENT:TriggerInputTest1()
	elseif "Test3"==key then
		ENT:TriggerInputTest2()
	elseif "Test2"==key then
		ENT:TriggerInputTest3()
	elseif "Test1"==key then
		ENT:TriggerInputTest4()
	end
end

print(os.clock()-t)
```
7.917
1.502
1.143
0.589
0.574

**Comment by TomyLobo** [comment]
Why don't you make the metatable like this?
````Lua
ENT.TriggerInput = setmetatable({}, {
	__call = function(triggers, self, name, value)
		return triggers[name](self, value)
	end })
````
That assert looked useless and you weren't making use of tail call optimization

**Comment by AbigailBuccaneer** [comment]
The `assert` gives a nicer error message when you call `ENT:TriggerInput("this input doesn't exist")`. (Especially when you actually write a nicer error message for it :wink:)

I was under the impression that if the last expression was a function call then it'd be tail call optimized, regardless of whether it was in a `return` or not. (Especially with LuaJIT.) It'd be interesting to know if that's the case though.

**Comment by TomyLobo** [comment]
how would that work if the caller defines the return value, not the callee?

**Comment by AbigailBuccaneer** [comment]
...You're right, it only works with `return`. Would be interesting to run these tests again.

**Comment by TomyLobo** [comment]
About those asserts:
How about making that check in Create/AdjustWireInputs?
