### ISSUE TITLE
egpOrder is not working

### ISSUE THREAD

**Issue by Illutax** [wiremod/wire#1056]
Greetings,
I noticed it years ago and still couldn't use it. It just seems not to be working. Or im doing it wrong all the time. Could you give clarity?

Edit: Tried to use it on various servers and also in SP with the newest wiremod installed.

**Comment by Divran** [comment]
Last time I tried it, it worked fine. It can be a bit tricky to use, however, so I recommend creating the objects in the correct order in the first place instead.

**Comment by TomyLobo** [comment]
@Divran does it have to do with parenting?

Otherwise maybe the API is bad.
How about having API for:
1. Bring A to top
2. Send B to bottom
3. Put A just above B
4. Put A just below B

**Comment by Illutax** [comment]
Would be great, if we could get this.

**Comment by AbigailBuccaneer** [comment]
Okay, opened another issue for a better API.
