### ISSUE TITLE
GMod December Update

### ISSUE THREAD

**Issue by oldmud0** [wiremod/wire#1058]
I've looked through the [changelog](http://www.garrysmod.com/2015/12/16/december-2015-update/) and I haven't seen anything critical that would break Wiremod, but I have seen a bunch of new API methods added. There was also a minor change made to `utf8`.

Is there anything that needs to be fixed or changed?

**Comment by AbigailBuccaneer** [comment]
I can't see anything that will break (but I'll leave this issue open so others can see this has happened).

**Comment by Nebual** [comment]
Another update [yesterday](http://www.garrysmod.com/2016/01/19/january-2016-update/), though it looks smaller than December and doesn't seem to have broken anything.

**Comment by TomyLobo** [comment]
Maybe that thing shouldnt be called Next Workshop release but *n*th Workshop release

**Comment by TomyLobo** [comment]
There we go:
````
$ git fetch && git log origin/workshop | grep -c 'Merge.*from wiremod/master'
13
````

**Comment by TomyLobo** [comment]
There, renamed it :)

**Comment by bigdogmat** [comment]
This can be closed now that the workshop has been updated.

**Comment by TomyLobo** [comment]
The milestone is still open
