### ISSUE TITLE
Improve foreach to allow key type selecting

### ISSUE THREAD

**Issue by bigdogmat** [wiremod/wire#1060]
You should be able to select which key type is used when iterating through a table. If I was to make an unordered table, the only way I'd be able to iterate through it would be to use table:keys(), I feel that shouldn't be necessary to do so. I would use arrays, but I can't store tables nor arrays within them.

As for how this should be implemented,

```
foreach(K:string, V:array = RandomTable)
```

And to keep backwards compatibility if no type is specified then it'll just use the old default (string).

**Comment by Matt1923** [comment]
The table index can only be a number or a string. Wouldn't it make sense just to implement both into the foreach so it loops through all of the keys regardless of type. I don't see a reason why you would want to loop through string and number keys individually so this would save using two foreach loops.

**Comment by bigdogmat** [comment]
Because that completely breaks type safety.

**Comment by AbigailBuccaneer** [comment]
Lots of people are persistently very confused as to why it's not possible to iterate over numeric keys, and from a syntax / grammar perspective this is clean, intuitive and consistent. :+1:
