### ISSUE TITLE
Cam controller bugs

### ISSUE THREAD

**Issue by thegrb93** [wiremod/wire#1062]
After reentering a vehicle with wire cam controller enabled, the entity the cam controller has as it's parent input becomes invisible.

**Comment by thegrb93** [comment]
Also after pasting a dupe with a cam controller that was linked to a vehicle, my view starts being controlled by the cam controller even though I'm not sitting in it.

**Comment by Divran** [comment]
what

**Comment by Divran** [comment]
first issue: there's a checkbox for that in the cam controllers context menu

**Comment by thegrb93** [comment]
Oh ok then the first issue is that the parented entity will draw when the player enters the vehicle for the first time even if that option is off. 

I think maybe it's because I created the parented entity after sitting in the chair.

The other issue seems to be a pasting issue.

**Comment by Divran** [comment]
Make sure it's linked to a vehicle after pasting it, and also make sure it isn't constantly enabled (using a pod controller's active output is a good choice)

**Comment by thegrb93** [comment]
It is constantly active. So maybe it is becoming active before the vehicle is created. I've changed my code to do that, but I still think it should wait until after pasting before becoming active.

**Comment by Divran** [comment]
The active input is a wire input and they've always worked this way when being pasted. Not saying it's the best idea, but it's the way it always has been.

**Comment by thegrb93** [comment]
Sry, what I meant is that it shouldn't start modifying the view until after everything is pasted. Or maybe after it's pasted, stop modifying the view if linked to a vehicle. Anyway I fixed that so not a big issue anymore, but the parent visibility bug might need a fix.
