### ISSUE TITLE
Entities with highspeed can be used to crash the server

### ISSUE THREAD

**Issue by suunrider** [wiremod/wire#1065]
Can be used to lag/crash a server.

**Comment by oldmud0** [comment]
Wouldn't be very practical. But maybe there should be a server side limit, just in case.

**Comment by AbigailBuccaneer** [comment]
Aren't there many other entities which can also store an unbounded amount of data?

**Comment by suunrider** [comment]
No, they have limits.

**Comment by suunrider** [comment]
Changed the title since almost every entity with highspeed has unlimited size of memory by using decimals as address.

**Comment by TomyLobo** [comment]
not quite unlimited :)

**Comment by Divran** [comment]
@tomylobo until the server crashes unlimited

**Comment by TomyLobo** [comment]
there's a finite amount of floating point numbers.

**Comment by suunrider** [comment]
Changed title before any offtopic is starting. :I

**Comment by TomyLobo** [comment]
you're right. I'll put an "almost" in front of the "unlimited" in your post and delete my two posts (and this one) as well as Divran's
