### ISSUE TITLE
fileAppend(..., "") breaks all file operations until reconnect

### ISSUE THREAD

**Issue by CaptainStumpy** [wiremod/wire#1068]
Hey there, when i use `fileAppend()` and not put anything in the data string like so:
```Lua
fileAppend("somefile", "")
```
...then you cannot write or append to a file anymore unless you reconnect to the server. `fileCanWrite()` will return 0 from that moment.

**Comment by AbigailBuccaneer** [comment]
Ah, the bug is [here](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/files.lua#L299) - the `wire_expresison2_file_download_finish` netmessage will only get sent if it can first send a non-zero-length chunk message.
