### ISSUE TITLE
Only 2 holoClips on Linux

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#1076]
As seen [here](http://imgur.com/a/CQE2P), trying to add a third clip removes the first one, while other players see it correctly.

I suspect this is a gmod/source+linux issue, as "Visual Clip"-tool also shows the same behavior.
(Reporting here anyway since this is technically a wiremod issue, not vanilla gmod)

Could anyone verify this, i am using Arch x86_64, someone with different distro/Mac OS maybe?

**Comment by TomyLobo** [comment]
I assume you are using linux as a client and you're in single-player mode?

**Comment by adosikas** [comment]
Both as client on multiplayer and in singleplayer.

**Comment by AbigailBuccaneer** [comment]
Nothing to do with us - especially if a non-Wiremod tool shows the exact same behaviour.
