### ISSUE TITLE
foreach-loop not working in E2 debug mode

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1081]
I'm not sure what's happening over there, but I have just downloaded master branch (removed old wire folder and put the new one in addons) - just to be sure I don't have outdated wiremod addon.
Turns out, a foreach-loop got broken somehow, luckily I have wrote (temporary?) workarounds using for/while loop. This only occurs after setting `wire_expression2_debug 1`.

#### An attempt at using foreach with array: ####
![Imgur](https://i.imgur.com/piVF0yf.png)
##### Array E2 code: #####
```
Array = array("string 1", "string 2", "3rd string", "more strings")

# foreach-loop does not work!
#
print("before foreach-loop")
foreach (Key, Value:string = Array)
{
    print("Key=" + Key, "Value=" + Value)
}
#]#

# Workaround using for-loop:
#[
print("before for-loop")
for (Key = 1, Array:count())
{
    local Value = Array[Key, string]
    print("Key=" + Key, "Value=" + Value)
}
#]#

# Alternative workaround using while-loop:
#[
local Key = 1
print("before while-loop")
while (Key <= Array:count())
{
    local Value = Array[Key, string]
    print("Key=" + Key, "Value=" + Value)
    Key++
}
#]#
```
##### Array output in Console: #####
```
Trace:
	1: Line 32  "Trace" lua/includes/extensions/debug.lua
	2: Line 76  "nil"   addons/wire/lua/entities/gmod_wire_expression2/core/init.lua
	3: C function
	4: Line 121 "Execute"   addons/wire/lua/entities/gmod_wire_expression2/init.lua
	5: Line 429 "Setup" addons/wire/lua/entities/gmod_wire_expression2/init.lua
	6: Line 260 "func"  addons/wire/lua/wire/stools/expression2.lua
	7: Line 32  "nil"   lua/includes/extensions/net.lua


before foreach-loop
before foreach-loop
Key=1   Value=string 1
Key=1   Value=string 1
Key=2   Value=string 2
Key=2   Value=string 2
Key=3   Value=3rd string
Key=3   Value=3rd string
Key=4   Value=more strings
Key=4   Value=more strings
sv: Expression 2 (generic): Type check for function "number=op:fea(array)" failed: Return value is not a number, but a nil!
```
<br>
#### An attempt at using foreach with table: ####
![Imgur](http://i.imgur.com/tjMRDu5.png)
##### Table E2 code: #####
```
Table = table("first id" = "the first string", "second id" = "the second string", "foo" = "'s bar")

# foreach-loop does not work!
#
print("before foreach-loop")
foreach (Key, Value:string = Table)
{
    print("Key=" + Key, "Value=" + Value)
}
#]#

# Workaround using for-loop:
#[
Keys = Table:keys()
print("before for-loop")
for (Index = 1, Keys:count())
{
    local Key = Keys[Index, string]
    local Value = Table[Key, string]
    print("Key=" + Key, "Value=" + Value)
}
#]#

# Alternative workaround using while-loop:
#[
Keys = Table:keys()
print("before while-loop")
local Index = 1
while (Index <= Keys:count())
{
    local Key = Keys[Index, string]
    local Value = Table[Key, string]
    print("Key=" + Key, "Value=" + Value)
    Index++
}
#]#
```
##### Table output in Console: #####
```
Trace:
	1: Line 32  "Trace" lua/includes/extensions/debug.lua
	2: Line 76  "nil"   addons/wire/lua/entities/gmod_wire_expression2/core/init.lua
	3: C function
	4: Line 121 "Execute"   addons/wire/lua/entities/gmod_wire_expression2/init.lua
	5: Line 429 "Setup" addons/wire/lua/entities/gmod_wire_expression2/init.lua
	6: Line 260 "func"  addons/wire/lua/wire/stools/expression2.lua
	7: Line 32  "nil"   lua/includes/extensions/net.lua


before foreach-loop
before foreach-loop
Key=second id   Value=the second string
Key=second id   Value=the second string
Key=foo Value='s bar
Key=foo Value='s bar
Key=first id    Value=the first string
Key=first id    Value=the first string
sv: Expression 2 (generic): Type check for function "string=op:fea(table)" failed: Return value is not a string, but a nil!
```

**Comment by TomyLobo** [comment]
How exactly is this an "emergency"?

**Comment by CaptainPRICE** [comment]
@TomyLobo Oh well if the current master branch gets on Workshop, then I am pretty sure it would be "emergency".

**Comment by bigdogmat** [comment]
I can't test now but as I haven't had a computer with gmod for a few weeks, but this worked fine when I played and nothing has changed with code related to that since. Can anyone else confirm this?

**Comment by CaptainPRICE** [comment]
It errors exactly after finishing iteration through an array or table.

**Comment by suunrider** [comment]
Tried both of your codes and nothing errored.

**Comment by AbigailBuccaneer** [comment]
Confirmed: this works fine with `wire_expression2_debug 0` but errors (with the given error) for `wire_expression2_debug 1`.

**Comment by AbigailBuccaneer** [comment]
Ah, I see the problem: There are multiple versions of the `fea` operator, and under each of them the key should be a different type:

```Lua
registerOperator("fea","t","s", ...) -- operator that takes a table, and so the keys should be strings
registerOperator("fea", "r", "n", ...) -- operator that takes an array, and so the keys should be numbers
registerOperator("fea","xgt","s", ...) -- operator that takes a table, and so the keys should be strings
```

As you can see, the element type is placed in the third argument of each of these. However, that third field is for the *return type* of the expression - this says to the typechecker (only active when `wire_expression2_debug 1`) that a call to the registered `foreach` operator handler on arrays should return a number. Which it doesn't, of course, a `foreach` doesn't return a value. So the typechecker complains.

**Comment by TomyLobo** [comment]
``wire_expression2_debug 1`` is meant to be used to debug problems (such as this) with the functions and operators in the library.
99% of the people have this set to the default of 0 and they should.
E2 is a statically typed language (like C) implemented on top of Lua, which is a loosely typed language (like machine code).
Like in C, there's the problem of when did a problem start. Activating this feature makes it easier to diagnose the cause of the problem while sacrificing a ton of performance (kinda like valgrind).

**Comment by TomyLobo** [comment]
Now it would be sweet if the compiler does something with these operators' return values as well.
That might make the whole thing more flexible

**Comment by AbigailBuccaneer** [comment]
I agree that end-users shouldn't use debugging, but programs should still run okay with it enabled, or it's practically useless.

**Comment by TomyLobo** [comment]
Yes, but it's not an emergency, i.e. we dont need to push this to workshop asap :)
