### ISSUE TITLE
addon.txt missing

### ISSUE THREAD

**Issue by austinv900** [wiremod/wire#1082]
This commit is missing addon.txt so it doesn't register in GMOD

**Comment by bigdogmat** [comment]
Addons in gmod haven't required an addon.txt for quite some time lmao

**Comment by austinv900** [comment]
Wire didn't work until I added a addon.txt and Carters add-on pack keeps
saying wire isn't installed correctly or not present. Any tips?

On Wed, Jan 13, 2016, 9:01 PM bigdogmat <notifications@github.com> wrote:

> Addons in gmod haven't required an addon.txt for quite some time lmao
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wiremod/wire/issues/1082#issuecomment-171530291>.
>
-- 


Austin Vandersluis

Founder of NinDroid Computer Services LLC

"From Computer Maintance to Game Server Management - Anything Could Happen"

Cell: 253-341-2025
Email: austinv900@nindroidservers.com

**Comment by bigdogmat** [comment]
Then I'm guessing you installed it incorrectly. And no idea what addon pack that is but I'm guessing it has to do with the way you installed it/the way that addon detects wire.

**Comment by austinv900** [comment]
Gmod doesn't even detect wire.

I downloaded wire from the github page with the download zip button.
Extracted the wire-master folder directly into my addons folder on both
server and client. I haven't had an issue before.

On Wed, Jan 13, 2016, 9:08 PM bigdogmat <notifications@github.com> wrote:

> Then I'm guessing you installed it incorrectly. And no idea what addon
> pack that is but I'm guessing it has to do with the way you installed
> it/the way that addon detects wire.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wiremod/wire/issues/1082#issuecomment-171531831>.
>
-- 


Austin Vandersluis

Founder of NinDroid Computer Services LLC

"From Computer Maintance to Game Server Management - Anything Could Happen"

Cell: 253-341-2025
Email: austinv900@nindroidservers.com

**Comment by bigdogmat** [comment]
Well this isn't a wiremod issue, best I can say would be try reinstalling gmod and if that doesn't then make a bug report on the gmod github or post in the help section of facepunch.

**Comment by austinv900** [comment]
Try running wire yourself "as is" from the github repo. Once I added the
addon.txt to the wire folder it worked.

On Wed, Jan 13, 2016, 9:16 PM bigdogmat <notifications@github.com> wrote:

> Well this isn't a wiremod issue, best I can say would be try reinstalling
> gmod and if that doesn't then make a bug report on the gmod github or post
> in the help section of facepunch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wiremod/wire/issues/1082#issuecomment-171533897>.
>
-- 


Austin Vandersluis

Founder of NinDroid Computer Services LLC

"From Computer Maintance to Game Server Management - Anything Could Happen"

Cell: 253-341-2025
Email: austinv900@nindroidservers.com

**Comment by bigdogmat** [comment]
If it were the case that it needed addon.txt, which hasn't been required since 2013, then I'm sure a lot more people would've made a report about this. And I have been using the github repo for wiremod for about the past 2 - 3 years, never had an issue.

**Comment by austinv900** [comment]
It's probably an issue on my side. I'll dig deeper. Thanks for the info

On Wed, Jan 13, 2016, 9:27 PM bigdogmat <notifications@github.com> wrote:

> If it were the case that it needed addon.txt, which hasn't been required
> since 2013, then I'm sure a lot more people would've made a report about
> this. And I have been using the github repo for wiremod for about the past
> 2 - 3 years, never had an issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wiremod/wire/issues/1082#issuecomment-171535426>.
>
-- 


Austin Vandersluis

Founder of NinDroid Computer Services LLC

"From Computer Maintance to Game Server Management - Anything Could Happen"

Cell: 253-341-2025
Email: austinv900@nindroidservers.com

**Comment by AbigailBuccaneer** [comment]
@austinv900 if `addon.txt` is relevant, then I'd assume you're running an outdated (and most likely pirated) version of Garry's Mod. Especially if that *is* the case, I'd think twice about posting your cellphone number and email address publicly.

**Comment by austinv900** [comment]
I've owned gmod since 2013. Don't believe me? This is my steam profile
http://steamcommunity.com/id/austinv900/

On Thu, Jan 14, 2016, 2:19 AM Abigail <notifications@github.com> wrote:

> @austinv900 <https://github.com/austinv900> if addon.txt is relevant,
> then I'd assume you're running an outdated (and most likely pirated)
> version of Garry's Mod. Especially if that *is* the case, I'd think twice
> about posting your cellphone number and email address publicly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wiremod/wire/issues/1082#issuecomment-171596091>.
>
-- 


Austin Vandersluis

Founder of NinDroid Computer Services LLC

"From Computer Maintance to Game Server Management - Anything Could Happen"

Cell: 253-341-2025
Email: austinv900@nindroidservers.com

**Comment by austinv900** [comment]
Thanks for your help guys. :) I'm gonna be trying to figure out why my server or client isn't loading wire
