### ISSUE TITLE
callable string functions allways return void

### ISSUE THREAD

**Issue by E6QODCpPZ0U** [wiremod/wire#1088]
My mistake, Close please

**Comment by bigdogmat** [comment]
That's because you need to specify the type getting returned. So for owner it'd be

```php
O = "owner"()[entity]
print(O:name())
```

**Comment by E6QODCpPZ0U** [comment]
well thanks, i feel like a bit of an idiot now :+1:

**Comment by bigdogmat** [comment]
You can close this yourself, I believe on the comment button or somewhere around that

**Comment by TomyLobo** [comment]
I can close things too

**Comment by bigdogmat** [comment]
:p
