### ISSUE TITLE
Blockly for E2

### ISSUE THREAD

**Issue by jrwr** [wiremod/wire#1089]
Google has made a very nice system called Blockly, its very simple to use and have a nice interface for making scripts, I propose that using a system similar to it in gmod would bridge the gap between the representation of gates and the raw coding power of E2

https://developers.google.com/blockly/

**Comment by TomyLobo** [comment]
Since it's basically just another editor for the same language, I don't see much value in that.
Feel free to use Blockly to make a standalone editor for E2.

**Comment by AbigailBuccaneer** [comment]
An interesting project if somebody wants to contribute it, but unlikely to happen.

Wire2 had something similar to this, but it'd require a serious rewrite of most of Wiremod's entities.

**Comment by oldmud0** [comment]
Like a gates-within-gates system? Would be nice to have, but nah
