### ISSUE TITLE
DHDD not output anything?

### ISSUE THREAD

**Issue by oninoni** [wiremod/wire#1091]
I wrote array in a dhdd and it shows to be of the size 2 but it's writing an empty array to the Memory Output? Am i doing something wrong?
![dhdd](https://cloud.githubusercontent.com/assets/4203340/12558634/eb3f8244-c390-11e5-98cc-a3b839bf094a.PNG)

**Comment by bigdogmat** [comment]
This is because the output points to self.Proxy while that itself is empty. You can still use the output, though you can't iterate through it.

**Comment by TomyLobo** [comment]
Who is passing around tables with metatables as wiremod arrays?

**Comment by oninoni** [comment]
I Want to access the DHDD with a wirelink so what do i have to do?

**Comment by bigdogmat** [comment]
If I'm thinking correctly just make sure AllowWrite has an input of 1 when you try to input something in through data.

**Comment by oninoni** [comment]
It was 1 and as you can see in the "Size" Parameter data has been stored i just dont know how to acces it via wirelink?

**Comment by oninoni** [comment]
No Idea?

**Comment by bigdogmat** [comment]
Ok so I was wrong about it should working, I was testing in Lua 5.3 where ipairs works on tables with __index fields. So the reason for it not showing on the debugger is solved.

Though when I tried to get a value from the array within E2 I got not result, as for why I have no idea. I'd attempt to look through the value handling within E2 but I'd have no idea where to start.

**Comment by oninoni** [comment]
So It's broken? Great...

**Comment by TomyLobo** [comment]
this is why you test stuff inside gmod

**Comment by bigdogmat** [comment]
Lately I've only had a shitty laptop so it was easier to just test without it, though you're right and eventually I did.

**Comment by oninoni** [comment]
Any chance this will be fixed soon?

**Comment by TomyLobo** [comment]
@bigdogmat should we just revert the PR that introduced the problem?

**Comment by TomyLobo** [comment]
That's #962 I guess

**Comment by bigdogmat** [comment]
I'd say that's fine, it's an output so nobody should be trying to change it anyway.
