### ISSUE TITLE
I know it's a bit late to the update suggestion party...

### ISSUE THREAD

**Issue by NavyCo** [wiremod/wire#1104]
I know it's a bit late to the update suggestion party... But I'd like to know at least IF there's a client-side command to retrieve the E2 [entity] owner?

**Comment by bigdogmat** [comment]
Your admin mod would handle this, at least if I understand what you're asking correctly

**Comment by NavyCo** [comment]
I just finally figured it out o-o Sorry for being douche and _not posting what I did to fix_
`_:GetNetworkedEntity("player", nil)`
