### ISSUE TITLE
E2 Clientside Crasher

### ISSUE THREAD

**Issue by suunrider** [wiremod/wire#1105]
###### Code removed

**Comment by TomyLobo** [comment]
I edited the code to prevent abuse.

**Comment by oldmud0** [comment]
So, this was confirmed?

**Comment by bigdogmat** [comment]
@oldmud0 Well the code was removed, and even if this issue itself is closed the issue made on the gmod issue tracker pretty much outlines how it's done.

**Comment by thegrb93** [comment]
Yeah, but now at least noobs can't just copy paste the server crashing code.

**Comment by bigdogmat** [comment]
yee
