### ISSUE TITLE
jsonDecode is not properly decoding nested arrays/tables

### ISSUE THREAD

**Issue by Mista-Tea** [wiremod/wire#1106]
Below is a test script I wrote that demonstrates incorrect behavior when decoding a JSON-encoded table with nested arrays/tables back to an E2 table:

```
# Table to JSON encode
local Table = table()

Table["String",string] = "Some string"
Table["Number",number] = 1
Table["Array",array]   = array( "Some", "elements" )
Table["Table",table]   = table( 1, 2 )

local JSON = jsonEncode( Table )


# JSON-decoded table
local Table2 = jsonDecode( JSON )

print( "JSON Error:",      jsonError() )
print( "String:",          Table2["String",string] )
print( "Number:",          Table2["Number",number] )
print( "Array size:",      Table2["Array",array]:count() )
print( "Array contents:",  Table2["Array",array] )
print( "Table size:",      Table2["Table",table]:count() )
print( "Table contents:" ) printTable( Table2["Table",table] )
```

There are no reported JSON errors. The String and Number fields are handled without any issues, but notice the output for the nested array and table:
```
JSON Error:		
String:	        Some string	
Number:	        1
Array size:     0
Array contents:	[
Table size:	    5	
Table contents:	
ntypes:
		1	=	n
		2	=	n
s:
n:
		1	=	1
		2	=	2
size	=	2
stypes:
```

None of the indexes remain in the array, and the table seems to expose the values from https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/serialization.lua#L508-L516 rather than just the front-end values { 1, 2 }. I looked around the E2 serialization file but I don't really have the time to go through it all.

I've switched to von in the meantime, which works. However, since I primarily use JSON everywhere else, it would be nice to get this resolved.

Let me know if there is anything more I can do to help. Thanks!

**Comment by Divran** [comment]
huh that's odd. I'm sure I tested this already

**Comment by Mista-Tea** [comment]
I should note I am using the workshop version of Wiremod. I didn't realize the workshop version hadn't been updated since June 15th, 2015, so this may been fixed between then?

**Comment by Divran** [comment]
Fixed it. The problem was I was an idiot.

**Comment by Mista-Tea** [comment]
Ah, sweet.

On a unrelated topic, how does the Wire team decide when to update the workshop version?

I used to use the GitHub version to keep up with the ongoing fixes/additions, but at one point I had updated my copy and discovered some recently-made commit nearly broke it entirely. Since then I've stuck to the more stable workshop version.

**Comment by Divran** [comment]
It would help if you told us which recently made commit broke it

**Comment by Mista-Tea** [comment]
It was years ago when I was still a fledgling developer, so I didn't have a GitHub account and didn't really feel comfortable using it.

Otherwise I would have, like I am now :)

**Comment by Divran** [comment]
Alright
