### ISSUE TITLE
E2 Clientside Crasher (2)

### ISSUE THREAD

**Issue by its-suun** [wiremod/wire#1113]
```
@persist I

if(first()) {
    runOnTick(1)
} elseif(holoCanCreate()) {
    holoCreate(I, entity():pos())
    holoModel(I, "models/dog.mdl")
    I++
}
```

Can't find any "collaborators only" feature.
Also works for starfall and expadv.

**Comment by bigdogmat** [comment]
Is it the model or the creating of them every tick?

**Comment by its-suun** [comment]
It's the model

**Comment by its-suun** [comment]
It's not an april fool btw, test it out yourself :P

**Comment by GuurgleOS** [comment]
It does not crash for me just kills my FPS.

**Comment by its-suun** [comment]
Crashes for me with engine error "too many indexes in buffer"

**Comment by oldmud0** [comment]
Probably because here, polycount * model count > engine count, assuming that model count < e2 max holo prop count

**Comment by bigdogmat** [comment]
This isn't really something that Wiremod can fix, except for maybe lower the holo limit or blacklist the model.

**Comment by Divran** [comment]
Only way to fix this would be to use a blacklist, and how do we know what to blacklist? There's probably thousands of models like this.

**Comment by thegrb93** [comment]
Citadels too.

**Comment by AbigailBuccaneer** [comment]
[`util.GetModelInfo`](http://wiki.garrysmod.com/page/util/GetModelInfo) might have useful info, but the wiki page doesn't say what info it actually gets.

**Comment by bigdogmat** [comment]
> util.GetModelInfo might have useful info

Even so it doesn't work server side(or at least that's what the wiki says), and I don't think we want deal with networking more (possibly inaccurate) info.

**Comment by AbigailBuccaneer** [comment]
As always: we don't implement the whitelist/blacklist logic ourselves, we just add the hooks for other addons to decide what can/can't be done. See #1097 - this should just be extended to E2 holograms and [anywhere else we call `ENT.SetModel`](https://github.com/wiremod/wire/search?utf8=%E2%9C%93&q=setmodel).

**Comment by its-suun** [comment]
bump

**Comment by oldmud0** [comment]
bump rejected

**Comment by Codingale** [comment]
So, is this fixed? I had a minge come on and try it today but no one crashed. I even tried it with 3 on SP then on MP, massive FPS drop but no crash to desktop.

**Comment by TomyLobo** [comment]
It's clearly Garry's fault, so I'm closing this

**Comment by its-suun** [comment]
It's more like wire's fault since garry didn't intend to sandbox/limit addons. And wire's job is to limit/sandbox expression2 so you can't access everything (otherwise everyone would just use glua).
So a gmod dev won't probably fix this issue, since it's the addon which crashes the players. You could still hide the code i have written in the issue.

**Comment by Codingale** [comment]
No though, like I said somehow my game won't crash anymore with that error in fact I had it run out of memory before it crashed.
