### ISSUE TITLE
Add horizontal scroll-bar to text editor

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1116]
I am reporting this as a potential feature request.
There is vertical, but no horizontal scroll-bar.
I have checked options (just in case) and it is not there.

(So, after so long, I don't get it why isn't it implemented?)

**Comment by bigdogmat** [comment]
There is no horizontal scroll bar by default so we'd have to create our own. That and with the current state of the editor it'd probably be a bit of a mess to put in.

**Comment by CaptainPRICE** [comment]
@bigdogmat Well it would be mess^2...

**Comment by Divran** [comment]
It's bad coding practice to make lines long enough that you have to scroll
sideways. Just write better code and you don't need it.

**Comment by bigdogmat** [comment]
While I do agree it's bad to code across the entire screen, a few other variables come into effect. What font size you use, how big your editor is, how big your screen is.

**Comment by CaptainPRICE** [comment]
Me. Well, most of the time I am running low game resolution (800x600).. And then I have to switch resolutions (back and forth).. How does longer lines make code "less better" (a.k.a. productive)!? Did you mean less readable? If so, that's completely different topic, down to coding conventions, readability, standards, user preferences/styles... Which in Expression 2, is not really.. So your point is FULL of baloney. Seriously, no offense @Divran.

Or, how about wrap-long-lines feature?

Note, I have said _potential_ feature request, it would make E2 editor a little easier/painless to use.
So, my rate for current E2 editor is 4/10. (And I am using Sublime or my own E2 editor, simple because it is more feature-rich...)

**Comment by AbigailBuccaneer** [comment]
I think it's short-sighted to say that it's good practice to limit line lengths (which it is) so we shouldn't implement a horizontal scroll bar. That said, if there is no horizontal scrollbar widget and it's not easy to make one that looks and works identically to the vertical scrollbar widget, I don't really think it's a justifiable effort. As always, this is an open-source project worked on in people's free time, and you're welcome to contribute if this is something you'd like to see.

The E2 editor will never be as good as a dedicated code editor. It lives here as an editor for one component in this quite large and varied mod, so it'll never be full-featured.

**Comment by oldmud0** [comment]
aka word wrap?

**Comment by AbigailBuccaneer** [comment]
Feel free to submit a pull request for this, but it's not something we have any intention of  doing.
