### ISSUE TITLE
User-defined function analysis verification fails (No such function)

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1117]
See the following picture (worth a thousand words):
![No such function](https://i.imgur.com/DePLgA1.png)

Code:

```
local First = first()
if (!First)
{
    print("First: " + First)
    # It is not first run. myFunc "should have a go"..?
    myFunc() # Syntax highlighting works. But, validation still says "No such function".
}
else
{
    print("First: " + First)
    # !(!first()) == first()
    # It is first run.
    function myFunc() { }
}
```

**Comment by bigdogmat** [comment]
The editor highlights all *defined* UDFs. The issue is the editor can't tell if the that branch will go through before the branch that call's in. Also you really shouldn't be creating UDFs outside of if(first()) as that's when the editor expects them to be.

**Comment by CaptainPRICE** [comment]
I know a possible workaround is to make call myFunc using quotes, like so:
`"myFunc"()`
But, this is doesn't work on user-defined functions (UDF) on types (afaik), for example:
![Picture](http://i.imgur.com/y3up1yU.png)
Now that dropped syntax highlighting, and also this workaround doesn't work on UDF on types (in pictured scenario "entity", the function entity:myFunc(void), but I mean it is regardless of type, this applies to any UDF on any type [angle, array, bone, complex, effect, entity, gtable, matrix, matrix2, matrix4, number, quaternion, ranger, string, table, vector, vector2, vector4, wirelink]).

Code:
```
local First = first()
if (!First)
{
    print("First: " + First)
    "myFunc"() # Syntax highlighting no longer works. Validation successful.
    # It is not first run. entity:myFunc "should have a go"..?
    entity():myFunc() # ... syntax highlighting works ... No such function.
}
else
{
    print("First: " + First)
    # !(!first()) == first()
    # It is first run.
    function myFunc() { }
    function entity:myFunc() { }
}
```

**Comment by CaptainPRICE** [comment]
@bigdogmat 
> Also you really shouldn't be creating UDFs outside of if(first()) as that's when the editor expects them to be.

It is defined in the code-block that is run first. Don't you see?

**Comment by bigdogmat** [comment]
I thought you were talking about a completely different issue, as for why I removed my comment. And this issues stems from the fact that the validator wants UDFs to be created before called. 

When I say that I mean created line wise before called.

Also you can still do it with callable strings,

```
function number entity:test(T:string) {return T:toNumber()}
print("test"(owner(), "1")[number])
```

**Comment by CaptainPRICE** [comment]
@bigdogmat 
> Also you can still do it with callable strings,
```
function number entity:test(T:string) {return T:toNumber()}
print("test"(owner(), "1")[number])
```

Oh right, there is a workaround for UDFs on types! Ah, but it is still an issue..
Thanks for reminding me.

**Comment by bigdogmat** [comment]
To give a little insight on how it works, or at least how I remember it working.

To give a little insight on how it works, or at least how I remember it working.

The validator goes through the script and checks to make sure everything is valid, when it comes to a UDF definition it adds it to a lookup so when it comes to a function call it can check against it. The issue comes with the definition comes after the call.

The only fix I can think of for this would be to go through the script once and take a function errors and compare them against the list of defined functions.

**Comment by Divran** [comment]
Because the syntax highlighter is much dumber than the compiler. Would be a
pain to fix.

**Comment by AbigailBuccaneer** [comment]
Yeah, verifying whether E2 functions exist is equivalent to solving the halting problem. The entire function system's a mess, they should be statically defined and you shouldn't have to fuck around with the `if (first())` shit that goes on.

Verification could mark a function as existing if a definition of it exists anywhere in the file. That would mean we'd correctly succeed on your example, correctly fail when we use a function name that's never defined, and assume the code is correct if it defines it somewhere. That's probably the best we can do for now.

**Comment by oldmud0** [comment]
Function definition is similar to the behavior in JavaScript:
```javascript
foo(); //"bar"

function foo() {
  console.log("bar");
}
```
This is a function declaration.

It will work regardless of the position in body:
```javascript
foo(); //"bar"

if(false) {
  function foo() {
    console.log("bar");
  }
}
```

However, ECMA strict typing discourages use of function declaration and instead prefers function definitions:
```javascript
foo(); //"bar"

if(false) {
   foo = function() {
    console.log("bar");
  }
}
```
This works due to hoisting. It's complicated.

However this definitely doesn't:
```javascript
foo(); //Uncaught TypeError: foo is not a function

if(false) {
   var foo = function() {
    console.log("bar");
  }
}
```

The point is that UDFs should be differentiated between those that are only defined when they pass a point in the code (as if they were variables) or are automatically defined at runtime regardless of where they are.

**Comment by Divran** [comment]
@oldmud0 E2 doesn't have function variables (which is the reason we have
callable strings at all), so doing that seems pretty pointless. But idk I'm
no expert on syntax design

**Comment by oldmud0** [comment]
That's really weird, callable strings.
So could you do
```bash
function asdf() {print("foo")}
function ghjk() {print("bar")}

local Foo:string = "asdf"
Foo()  #"foo"
Foo = "ghjk"
Foo()  #"bar"
```
?

**Comment by bigdogmat** [comment]
@oldmud0 Yeah

**Comment by oldmud0** [comment]
Wow that's almost as bad as eval.

**Comment by CaptainPRICE** [comment]
@oldmud0 That's invalid E2.
Local variable definition don't expect a type.
Corrected:
```
function asdf() {print("foo")}
function ghjk() {print("bar")}

local Foo = "asdf"
Foo()  #"foo"
Foo = "ghjk"
Foo()  #"bar"
```
Anyways, since we are talking about UDFs. I have excellent news to share, about what's coming soon for public in [Wire-Data repository](https://github.com/CaptainPRICE/Wire-Data). I am writing five (5) libraries that every Expression 2 programmer is going to love to include and work with, yeah you will wish to use them! :heart: :smile:

Very recently, I have started developing them, so I pay attention around.. This has just began an official announcement from me, in this issue page, what a day!
Would be fantastic if you ladies and gentlemen turn me on (even more) by implementing [this](https://github.com/wiremod/wire/issues/1118)!
I have already told about them to just a few friends.

**Comment by its-suun** [comment]
Hidden promotion
