### ISSUE TITLE
Array Gates missing.

### ISSUE THREAD

**Issue by JRHEofficial** [wiremod/wire#1119]
Direct issue solely with the latest few releases of Wiremod itself. Wire array gates fail to load and do not appear in the Wire-gates tool menu.

**Comment by bigdogmat** [comment]
#991

**Comment by immibis** [comment]
What were you using them for?

**Comment by JRHEofficial** [comment]
Wire Triggers - There is no way to access dynamic entity calling currently without arrays, in which the functionality has been strictly limited to expression2 now.

**Comment by immibis** [comment]
Could you *ever* extract entities from arrays with gates? I was under the impression the array gates were limited to dealing with numbers.

**Comment by JRHEofficial** [comment]
You could extract entity IDs which convert over nicely directly to entities

**Comment by oldmud0** [comment]
I remember the old gate system. It was nice for hacking quick stuff together.
If you're going to remove one "obscure" category in favor of E2, then forget it, just remove all of gates except arithmetic, because with one category missing, chances are that the whole contraption that uses gates is going to be broken.

**Comment by immibis** [comment]
@oldmud0 Feel free to write a set of array gates that are useful and don't suck.

You keep saying that there's some reason to keep them, but we just got the first complaint after ***6 months***.

**Comment by immibis** [comment]
Apparently @its-suun disagrees that the old array gates suck. Do you have anything to add?

**Comment by its-suun** [comment]
I gave my explanation months ago

**Comment by oldmud0** [comment]
Saying that the old gate arrays suck just proves my point. They weren't good for anything other than whipping something up quickly, like if you needed to clamp a value before passing it to another Wire entity.

So why are they still around?

**Comment by immibis** [comment]
@oldmud0 They *aren't* still around.
