### ISSUE TITLE
Global user defined functions file

### ISSUE THREAD

**Issue by GalaxyOfWaffles** [wiremod/wire#1120]
I like to use functions, but I don't like to copy and paste the functions from file to file if I want to make a change to them. So my idea is to make a file that automatically loads functions across all the e2 files that need them.
For example you write function isInArray(Array:array,E:entity){ect} inside your function file and you call it in another e2 it will work without you having to ever paste it.

**Comment by bigdogmat** [comment]
Use the include directive,

```
function enitty:shit()
{
    print(This:name())
}
```

^ file's name is "shit.txt"

```
if(first())
{
    #include "shit"

    owner():shit()
}
```
^ works

**Comment by oldmud0** [comment]
excellent examples
