### ISSUE TITLE
E2 Clientside Crasher (3)

### ISSUE THREAD

**Issue by its-suun** [wiremod/wire#1121]
```lua
@persist E:entity
if (first()) {
  runOnTick(1)
  E = propSpawn("models/props_c17/oildrum001_explosive.mdl",1)
} else {
  while(perf()) {
    E:propBreak()
  }
}
```
requires propcore to be installed

**Comment by thegrb93** [comment]
so propBreak can create infinite explosions

**Comment by Divran** [comment]
Seems like the cause of this might be that the IsValid check thinks the prop is valid until the end of the tick. Maybe we should block any propcore action on the same prop more than once in the same tick.

**Comment by bigdogmat** [comment]
> Maybe we should block any propcore action on the same prop more than once in the same tick. That would probably solve other similar issues as well.

Exactly what I was thinking

**Comment by titanic4** [comment]
The solution is similar to one I did while fixing the wiremod keyboard stuck bug - adding a tiny delay in propcore ent:propBreak() and the action of it with timer.Simple should fix it...
The function currently looks like this:
```lua
        e2function void entity:propBreak()
	     if not PropCore.ValidAction(self, this, "break") then return end
	     this:Fire("break",1,0)
        end
` 

By adding timer.Simple in this function it's possible to delay actions by certain amount, thus allowing the entity to fully be removed after firing the "break" entity input.

**Comment by Divran** [comment]
@titanic4 that could work, but it would probably be better to block the use
of the same function on the same entity more than once per tick, like I
mentioned in my previous post.

**Comment by immibis** [comment]
@titanic4 If you called propBreak 1000 times in a tick, wouldn't all the timers fire in the next tick, and *still* break the prop 1000 times before the prop was deleted?

**Comment by its-suun** [comment]
bump
