### ISSUE TITLE
Script Errors with Hydraulics

### ISSUE THREAD

**Issue by SpyCrabSteam** [wiremod/wire#1124]
So, when I use Wire Hydraulics and i set the length to a higher number, it doesn't extend, and when i try to pull it with the Phys Gun I get a script error. Tried reinstalling Wiremod and wiremod extras (From   Github)

> 
[ERROR] lua/includes/extensions/table.lua:94: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. HasValue - lua/includes/extensions/table.lua:94
    3. v - workshop/lua/autorun/server/pe_base.lua:630
     4. old_hook_call - lua/includes/modules/hook.lua:84
      5. unknown - workshop/lua/includes/modules/momo/compat.lua:30

**Comment by Divran** [comment]
You have a bunch of addons installed that break it. Look at the error you posted yourself. "modules/momo/compat.lua" and "pe_base.lua". Uninstall those addons and try again.
