### ISSUE TITLE
Changes to a Wire Wheel made after it was created aren't duplicated

### ISSUE THREAD

**Issue by balloonguy** [wiremod/wire#1132]
Torque, Friction.

**Comment by TomyLobo** [comment]
wire wheel or regular wheel?

**Comment by balloonguy** [comment]
Wire wheel.

**Comment by AbigailBuccaneer** [comment]
Useful links: 
* [`gmod_wire_wheel.lua`](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_wheel.lua) entity
* [`wheel.lua`](https://github.com/wiremod/wire/blob/master/lua/wire/stools/wheel.lua) tool

**Comment by AbigailBuccaneer** [comment]
`gmod_wire_wheel` uses the standard `WireLib.MakeWireEnt` and `ENT:Setup()` for duplication. But the `wheel` tool also creates a `constraint.Motor` which takes the torque and friction. (`gmod_wire_wheel` also has some nonsense around `self.BaseTorque` and `self.TorqueScale` that looks like it's there to work around issues with the motor constraint.)

If the motor constraint isn't being saved properly, that's a bug with Garry's Mod. Can manually-created motor constraints be duplicated?

**Comment by balloonguy** [comment]
Standard wheels have their properties stay while wire wheels don't. My Garry's Mod is 100% validated. If wiremod can get the values in a constant value chip to stay it must be the same for a wheel.

After doing some inquiry, I found out that the value it keeps reverting to is the value the wheel was originally spawned with. The problem is the updated values not staying when applying different torque and friction properties to the same wheel.The normal wheel in gmod can be updated with right click and the torque value will stay while friction doesn't. Updating the value of a wire wheel will result in the new wheel having the spawned version's values of the torque and friction. I'll edit the title.

**Comment by AbigailBuccaneer** [comment]
Okay, after a bit of snooping: `gmod_wire_wheel` uses the exact same same technique with `BaseTorque`/`SetTorque`/`Motor:Fire( "Scale", ...)` as `gmod_wheel`.

It looks like [Garry's Mod wheels don't update their friction when you right-click them](https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/wheel.lua#L102) either. They do update the saved torque by setting `wheelEnt.BaseTorque` - which we currently don't do as we just use the standard [`WireToolObj:LeftClick_Update`](https://github.com/wiremod/wire/blob/master/lua/wire/tool_loader.lua#L76) implementation.

I think the cleanest fix would be to continue to use the default `WireToolObj:LeftClick_Update` but to handle updating the torque and friction of the motor constraint inside `gmod_wire_wheel`'s `ENT:Setup(...)`.

**Comment by thegrb93** [comment]
Okay, so the Setup function doesn't update the motor, but what does that have to do with the duplicator not saving them?

**Comment by AbigailBuccaneer** [comment]
Because the things that are saved are the fields named on the `duplicator.RegisterEntityClass(..., WireLib.MakeWireEnt, ...)` line, which are also the arguments passed to `ENT:Setup(...)` to load an entity.

So the torque and friction are actually two slightly different issues:

1. `ENT:Setup` doesn't set `self.BaseTorque` if it's already set, so changes aren't saved
2. Friction is never updated when left-clicking on an existing wheel, because it doesn't get passed to `ENT:Setup` (and the default implementation of left-click update only does `ENT:Setup` and nothing else)

**Comment by thegrb93** [comment]
Ahh, forgot the duplicator uses Setup.

**Comment by thegrb93** [comment]
I can't find any way to set the friction of phys_hinge.
