### ISSUE TITLE
Wire EGP doesn't come with all fonts

### ISSUE THREAD

**Issue by GamesArsenal96** [wiremod/wire#1134]
Hello Divran,

I have been noticing that Wiremod doesn't have all acquired fonts for EGP. Why?
I have already coded Wiremod and added them, but it only works on client/singleplayer. Is there anyway you can add it to the official Wiremod workshop addon so it works on all servers?

Edited [Wiremod/lua/entities/gmod_wire_egp/lib/egplib/materials.lua] file

https://www.dropbox.com/s/w4ok8f67fb75vm8/materials.lua?dl=1

**Comment by bigdogmat** [comment]
I'm guessing because either those fonts did something weird, or weren't in the game when the list was made.

**Comment by GamesArsenal96** [comment]
I already coded the file and added them and they worked just fine.

**Comment by bigdogmat** [comment]
As for why I said "did"

**Comment by GamesArsenal96** [comment]
Oh xD

**Comment by GamesArsenal96** [comment]
![code](https://cloud.githubusercontent.com/assets/8171935/15529289/ea597e22-2211-11e6-9825-a143f1e21d69.png)

**Comment by GamesArsenal96** [comment]
Hopefully it wont be a bother to add it.

**Comment by Divran** [comment]
I went through all the fonts that were listed on the gmod wiki at the time
and only added the ones that actually worked. Make a pull request if you
want to add more
