### ISSUE TITLE
E2: Add "xwl=nowirelink()" function

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1139]
Add a builtin/core function which would return an invalid wirelink.

Currently this is only possible if "wiring" extension is enabled, like:
```
local NoWirelink = noentity():wirelink()
```

**Comment by TomyLobo** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/wirelink.lua#L307-L313

Duplicate that function, rename it, rip out everything and just make it return nil :)

**Comment by Divran** [comment]
I think you can already do this, like this:
```
local Array = array()
local NoWirelink = Array["InvalidKey",wirelink]
```
but that's a huge hack, so a real function would definitely be cleaner. What do you need this for, though? I've never needed a nowirelink function.

**Comment by CaptainPRICE** [comment]
@Divran For example, in user-defined function which returns a wirelink, I want to be able to return an invalid wirelink.. For example (from extended library in array_contains file (not pushed yet)):
```
function wirelink array:containsWirelink(Wirelink:wirelink)
{
    foreach (Index, Value:wirelink = This)
    {
        if (Value == Wirelink)
        {
            return Wirelink
        }
    }
    return ??? # nowirelink()
} # End of function xwl=r:containsWirelink(xwl)
```

**Comment by Divran** [comment]
you know, the reason E2 (or lua for that matter) doesn't have any "array contains" functions is because they are bad. Any time you do that, you should be using a lookup table.

**Comment by CaptainPRICE** [comment]
@Divran The problem with that is, I don't know how could I possibly track a reference to an array. I would probably have to wrap `array()` function into a library, which is sort of what I don't want to do..
So, I guess I can't do anything better than that (that I know of).. :(

**Comment by Divran** [comment]
In this case, since wirelinks can't be an index in a table, you would need to get the entity ID:

```
function wirelink array:containsWirelink( Wirelink:wirelink ) {
    local EntityID = Wirelink:entity():id()
    return This[EntityID,wirelink]
}
```

Notice that this function uses a lookup array. This is an array with non-sequential keys, whose keys are only used for lookup requests such as these. Alternatively, you can use a table, but since the key here is always a number, arrays work too.

If this was done in Lua, we could've simply used a lookup table with the wirelink itself as the key, since Lua allows you to use literally anything as table keys.

**Comment by CaptainPRICE** [comment]
#1140 
Any cookie for me?

**Comment by CaptainPRICE** [comment]
Oh, right... It is funny, how I forgot about the following being possible.

```
##ifdef entity:wirelink()
local DefaultWirelink = noentity():wirelink()  # Note, requires "wiring" extension enabled.
##endif

function wirelink nowirelink()
{
    #print("In xwl=nowirelink() function")
    # Simply, by omitting a return statement I guess it returns nil to Lua (as invalid wirelink).
}

local NoWirelink = nowirelink()
print("IsValid: " + NoWirelink:entity():isValid())  # Prints "IsValid: 0"

local AreEqual = DefaultWirelink == NoWirelink
print("AreEqual: " + AreEqual)  # Prints "AreEqual: 1"
```

No cookie..?

**Comment by bigdogmat** [comment]
If #1095 is merged then you'll have to return a value, though you could recreate the effect with

```
function wirelink nowirelink()
{
    return noentity():wirelink()
}
```

**Comment by CaptainPRICE** [comment]
@bigdogmat
>function wirelink nowirelink()
>{
>    return noentity():wirelink()
>}

Which requires a "wiring" extension enabled in the first place. *facepalm*. See my code above..

**Comment by bigdogmat** [comment]
Ah, I see. Couldn't you just create a persisted wirelink and not set it to anything?
