### ISSUE TITLE
E2: Array is not limited to 1048576 elements?

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1142]
A test E2 to fill up an array with over 1048576 number elements/values.
```
@outputs Array:array Count Done
@trigger none

if (!Done)
{
    while (perf())
    {
        if (Array:count() >= 1048576)
        {
            Done = 1
            timer("DONE", 10000)
            print("A timer will be fired in 10s")
            break
        }
        Array:pushNumber(Count + 1)
        Count = Array:count()
    }
    interval(10)
    runOnTick(1)
}
elseif (clk("DONE"))
{
    print("Numeric array has " + Count + " elements, adding one more...")
    Array:pushNumber(Count + 1)
    Count = Array:count()
    print("Numeric array now has " + Count + " elements!")
    timer(clkName(), 5000)
}
```

According to the [Expression 2 wikipedia](http://wiki.wiremod.com/wiki/Expression_2#Array), it states that any type of array is limited to only 1048576 elements by default.
> Arrays are limited to 1048576 elements by default.

Which seems to be yet another false information, or perhaps a limited has been increased?

**Comment by bigdogmat** [comment]
> Which seems to be yet another false information, or perhaps a limited has been increased?

Hope you realize the wiki is barely updated and so it's not that good of a place for new information.

Either way I'm guessing it was removed as the only limiter in the setter function is [this ](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/array.lua#L175)one, which is only active if you used insert, so it doesn't really prevent anything unless the crash was directly related to table.insert

**Comment by Divran** [comment]
It was removed because the limit doesn't make sense. There's a hundred ways to get past it, so there was no point in trying to enforce it.

**Comment by CaptainPRICE** [comment]
Okay, let me close this issue since it is answered now.
