### ISSUE TITLE
E2: Add "number=finite(n)", "number=isinf(n)" & "number=isnan(n)" functions

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1143]
See [this gist](https://gist.github.com/CaptainPRICE/342303bba104354257db0471bf996bd3), it is pure Lua implementation (includes unit tests). Just revised/updated it ([coverage results](https://i.imgur.com/1vzo2x9.png)).

I have this in my "math" E2 library already, but I think it would be nicer to have this builtin instead ;)

**Comment by CaptainPRICE** [comment]
Ah.. Now I messed that up. It is in, #1140 PR.

**Comment by Divran** [comment]
E2 already has access to math.huge I believe, so the is finite function is useless, because you can simply do `N != math.huge` inside E2 (I forgot what the constant's name is)

**Comment by bigdogmat** [comment]
@Divran [These](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/number.lua#L46-L48) are all the number enums. Adding inf enum would be nice.

**Comment by Divran** [comment]
Huh, I could've sworn there already was one for inf
