### ISSUE TITLE
Balloon Deployer

### ISSUE THREAD

**Issue by Skyhold** [wiremod/wire#1144]
I want to do a save with Balloon deployer, but everytime when im loading a save, balloon deployer just disapear and showing me error.

1.Spawn Balloon deployer
2.Save map
3.Load map
3.Balloon Deployer disapear

[Wiremod] lua/entities/sent_deployableballoons.lua:46: attempt to index local 'pl' (a nil value)
  1. CreateEntityFromTable - lua/entities/sent_deployableballoons.lua:46
   2. unknown - lua/includes/modules/duplicator.lua:720
    3. ProtectedCall - [C]:-1
     4. Paste - lua/includes/modules/duplicator.lua:720
      5. unknown - lua/includes/gmsave.lua:58

plz fix it i really need this

**Comment by CaptainPRICE** [comment]
I was able to reproduce the error.
A bit more detailed steps for repro:

1. Start new game.
2. Spawn a Wire Balloon Deployer (Using Spawn menu, assuming default key-bindings: Hold down Q key, go to `Entities` tab, choose `Wiremod` category and click on `Wire Balloon Deployer`. Or by using console command: `gm_spawnsent sent_deployableballoons`;).
3. Save current game (Using Spawn menu, assuming default key-bindings: Hold down Q key, go to `Saves` tab, click `Save Game` under `My Saves` category. Or by using console command: `save "savegame_name_here"`.)
4. Clean up everything (or undo or restart game).
5. Load the saved game (Using Spawn menu, assuming default key-bindings: Hold down Q key, go to `Saves` tab, click `Load` on the saved game under `My Saves` category. Or by using console command: `load "savegame_name_here"`.)

Causes a server-side error with stack-trace:
```
[ERROR] addons/wire/lua/entities/sent_deployableballoons.lua:46: attempt to index local 'pl' (a nil value)
  1. CreateEntityFromTable - addons/wire/lua/entities/sent_deployableballoons.lua:46
   2. unknown - lua/includes/modules/duplicator.lua:720
    3. ProtectedCall - [C]:-1
     4. Paste - lua/includes/modules/duplicator.lua:720
      5. unknown - lua/includes/gmsave.lua:58
```
