### ISSUE TITLE
Why e2function aliases/duplicates have smaller cost?

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1147]
![See this](https://cloud.githubusercontent.com/assets/9789070/16025401/7d0724bc-31c7-11e6-8f76-36e539c9bc0c.png).

For example, above we see the following [functions](https://github.com/wiremod/wire/blob/7b39a3826ccf1e1b636f1d56d2455f180c1136d5/lua/entities/gmod_wire_expression2/core/sound.lua#L125-146) in E2 helper.
Now, I wonder why the bottom four e2functions cost 5 while the first four cost 25?

**Comment by oldmud0** [comment]
I think you're looking at this wrong. `nns` and `nnsn` functions with optional entity have a higher cost due to the `isValid` and `isOwner` calls. Now, what I don't understand is where the cost changed from 25 to 5 since there was only one `__e2setcost(25)`.

**Comment by CaptainPRICE** [comment]
@oldmud0 Yeah, well that's what I mean.. Just where is the line that set the cost to 5? I though I was blind for a moment, apparently not.

**Comment by Divran** [comment]
Pretty sure all soundPlay functions are supposed to have the same cost. A
simple isvalid check isn't slow enough to warrant such a huge difference in
cost.

**Comment by CaptainPRICE** [comment]
The only reason I can think of why there is such a difference in cost for aliases, is that when alias e2function is interpreted it calls `__e2setcost(5)` before an alias function is defined.. So, I went to try out my theory (simply by checking the cost of other e2function aliases). I have found 39 e2functions that are alias/duplicate. Here are the results:

Alias Definition | Cost | Real/Should Cost
----- | ----- | -----
e2function void findExcludePlayer(entity ply) = e2function void findExcludeEntity(entity ent) | 5 | 10
e2function void findAllowPlayer(entity ply) = e2function void findAllowEntity(entity ent) | 5 | 10
e2function void findIncludePlayer(entity ply) = e2function void findIncludeEntity(entity ent) | 5 | 10
e2function void findDisallowPlayer(entity ply) = e2function void findDisallowEntity(entity ent) | 5 | 10
e2function string glonEncode(table data) = e2function string glonEncode(array data) | 5 | 15
e2function string vonEncode(table data) = e2function string vonEncode(array data) | 0 | 15
e2function void soundPlay(string index, duration, string path) = e2function void soundPlay(index, duration, string path) | 5 | 25
e2function void entity:soundPlay(string index, duration, string path) = e2function void entity:soundPlay(index, duration, string path) | 5 | 25
e2function void soundPlay(string index, duration, string path, fade) = e2function void soundPlay(index, duration, string path, fade) | 5 | 25
e2function void entity:soundPlay(string index, duration, string path, fade) = e2function void entity:soundPlay(index, duration, string path, fade) | 5 | 25

I don't want to post an entire list..
Guess what. My theory was true :D
It seems like there is a bug in e2function alias/duplicate interpreter ;)

**Comment by Divran** [comment]
vonEncode is supposed to cost 0, because it dynamically adds more ops depending on the length of the string.

**Comment by TomyLobo** [comment]
Because I messed up, apparently. Try #1148.
It might fix it or it might blow up.

**Comment by TomyLobo** [comment]
Btw, if i read this correctly, you also can't alias vararg functions.

**Comment by Divran** [comment]
>Btw, if i read this correctly, you also can't alias vararg functions.

meh who cares. We can just do this if we really need to
```
local function do_stuff(A,B,C) end

e2function void whatever(A,B,C) do_stuff(A,B,C) end
e2function void whatever(A,B:vector,C) do_stuff(A,B,C) end
```

**Comment by CaptainPRICE** [comment]
@TomyLobo Just tested it, #1148 fixes it.
![image](https://cloud.githubusercontent.com/assets/9789070/16083338/edefc51e-3314-11e6-901e-a3ed8499d797.png)
Go ahead and merge that.

**Comment by TomyLobo** [comment]
@Divran ^

**Comment by bigdogmat** [comment]
Just noticed this affected a lot more than aliased functions.

```lua
--[[---------------------------------------------------------------------------
Broadcast messages
-----------------------------------------------------------------------------]]
__e2setcost(50)

e2function void broadcastMessage(...)
  if not check_permission(self) then return end

  send_color_print_VarArgs(self, nil, typeids, ...)
end

e2function void broadcastMessage(array args)
  if not check_permission(self) then return end

  send_color_print_Array(self, nil, args)
end

--[[---------------------------------------------------------------------------
Player methods
-----------------------------------------------------------------------------]]
__e2setcost(20)

e2function void entity:printMessage(...)
  if not IsValid(this) then return end
  if not this:IsPlayer() then return end
  if not check_permission(self) then return end

  send_color_print_VarArgs(self, this, typeids, ...)
end

e2function void entity:printMessage(array args)
  if not IsValid(this) then return end
  if not this:IsPlayer() then return end
  if not check_permission(self) then return end

  send_color_print_Array(self, this, args)
end
```

The first function in the above code would be set at 50 ops, while the last 3 would be set at 20.

**Comment by TomyLobo** [comment]
yes, it also affected vararg functions
