### ISSUE TITLE
E2: Helper does not search for registered constants

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1149]
![Helper does not search for registered constants](https://cloud.githubusercontent.com/assets/9789070/16084742/24205bda-331a-11e6-8fcb-cd5596a4e7ca.png)

Perhaps add an option to search (registered) constants?

**Comment by Divran** [comment]
Well, you can type "_" and the autocomplete thingy will list them all for you, since there aren't that many. But sure I guess it could be added to the E2Helper as well.

**Comment by CaptainPRICE** [comment]
Ok. Nice.
Looks like this one were left open. Closing it manually.
NOTE: Use `fixes #N` in the title of PR next time, where N is issue's ID to auto-close referenced issue in future ;)
