### ISSUE TITLE
E2: E2Lib.registerConstant function does not work with math.huge?

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1150]
For example:
If we add the following code to [this file](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/number.lua) (near other `E2Lib.registerConstant` function calls):

```
E2Lib.registerConstant("INFINITY", math.huge)
```

And now if we try to use this new constant value in E2, like this:

```
print(_INFINITY == _INFINITY)
```

Above Expression 2 is valid, but Lua throws an error on run-time (when spawned):

> sv: Expression 2 (generic): entities/gmod_wire_expression2/core/number.lua:85: attempt to perform arithmetic on a nil value

**Comment by Divran** [comment]
huh. Well it doesn't look like [the registerConstant function](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/init.lua#L167-L172) does anything that would make this not work

**Comment by CaptainPRICE** [comment]
Then it is something else. Hm.. I have just checked if there is `_INF` in `wire_expression2_constants` table, yes it is there:

> ] lua_run_cl PrintTable(wire_expression2_constants)
> _E	=	2.718281828459
> _FILE_404	=	3
> _FILE_OK	=	1
> _FILE_TIMEOUT	=	2
> _FILE_TRANSFER_ERROR	=	4
> _FILE_UNKNOWN	=	0
> _HUD_PRINTCENTER	=	4
> _HUD_PRINTCONSOLE	=	2
> _HUD_PRINTNOTIFY	=	1
> _HUD_PRINTTALK	=	3
> _INF	=	inf
> _PHI	=	1.6180339887499
> _PI	=	3.1415926535898

How come Lua throw a nil value error then?
I am clueless at the moment.

**Comment by bigdogmat** [comment]
So I decided to look into this, found out it's caused by the way the compiler handles the `NUM` instruction.

It simply does this

```lua
function Compiler:InstrNUM(args)
	self.prfcounter = self.prfcounter + 0.5
	RunString("Compiler.native = function() return " .. args[3] .. " end")
	return { Compiler.native }, "n"
end
```

And the issue is `math.huge` when converted to a string is `inf`. Because of that you get the nil value because it's attempting to get the global `inf`.

Not sure what the correct way to fix this is as I've barely looked into the compiler to see how it handles these.

**Comment by thegrb93** [comment]
Why's it doing RunString rather than a function lambda?

**Comment by bigdogmat** [comment]
Not exactly sure, as far as I can tell it could be replaced with that and `tonumber` and it'd work fine. All of the `NUM*` instructions use that `RunString` method.

**Comment by syranide** [comment]
`RunString` here is intended as a performance optimization, it generates a function that returns a fixed number with no captured scope. How much this still matters in practice I don't know.

**Comment by bigdogmat** [comment]
Ah, I understand how that could affect performance. After some testing with this [script](https://gist.github.com/bigdogmat/cd7a1a9037ba6aed824eae5237902bf4) I've come to some input

- With jit left on, the difference is anywhere from 3 to 100 microseconds, the `RunString` method being slower.
- With jit turned off, the difference is anywhere from 5 to 7 milliseconds, the `RunString` method being slower.

Things to take away.

1. You have to manually turn off jit, afaik it will always be on by default
2. Those differences were calculated using a billion iterations.

**Comment by syranide** [comment]
@bigdogmat You're not comparing to how E2 would be doing it though, it would have to read the number through the args parameter.

**Comment by bigdogmat** [comment]
> You're not comparing to how E2 would be doing it though, it would have to read the number through the args parameter.

But I am? Currently it either directly puts the number into the function, or it creates a table for that function to return, e.g. `NUMJ`

```lua
Compiler.native = { 0, 0, tonumber(args[3]), 0 }
RunString("local value = Compiler.native Compiler.native = function() return value end")
```

This could simply be done with an upvalue, my test attempts to show what affect that would have in performance.

> PS. Also, when micro-benchmarking, it's worth running the benchmarks in reverse order as well (or preferably independently even) to make sure there isn't any VM bias.

I did them in reverse order, however good point about running independently.

**Comment by syranide** [comment]
@bigdogmat Oh wait yeah I see your point now, I was thinking of how it would look if it wasn't pre-processed by the compiler at all (which is the real optimization). But you're totally right that the argument could just be cached as a local variable which should be near identical yes. Especially if benchmarking doesn't show otherwise. Although VMs being VMs you never know what truly happens in practice, but considering how ugly of a hack RunString is then your solution seems like the neater one.

**Comment by TomyLobo** [comment]
@bigdogmat are you compiling once, running many times or are you compiling each time?

**Comment by TomyLobo** [comment]
I'd say remove the optimization and just return a regular non-RunString lambda:
```lua
function Compiler:InstrNUM(args)
	self.prfcounter = self.prfcounter + 0.5
	local value = args[3]
	return { function() return value end }, "n"
end
```

**Comment by bigdogmat** [comment]
> @bigdogmat are you compiling once, running many times or are you compiling each time?
> RunString is not used at run time, so it should not be part of your test loop.

I linked my script so you could see exactly what I was doing. I'm creating both functions once, one from `RunString`, one using a regular lambda function, then comparing how long it takes each to run.
