### ISSUE TITLE
E2 Chip getting destroyed after player teleport

### ISSUE THREAD

**Issue by dragitz** [wiremod/wire#1153]
Hello, I'm having issues with e2
The chip keeps getting destroyed or lost after teleporting the player without commands, such as:

Getting inside a car (Rarly happends)
Using a door that teleports you far away (gm_bigcity for example)
Or any other player teleportation related

I though about, ok this might be a single player problem, but it also happends in other sevrers (sadly).

Need the e2 chip code? There are no anti-dupe or any destructive type of code inside the e2 chip.

I was wondering if it happends to some of you too :) have a nice day

**Comment by Divran** [comment]
There's nothing in wiremod or E2 that would delete E2s after you move some distance away from it.

**Comment by dragitz** [comment]
Do you think it could be an addon?

**Comment by dragitz** [comment]
This is the e2 http://pastebin.com/raw/0DKHmdcx

Pretty simple: 
1) spawn a Forcer and use the e2 on it
2) Fly far away from the chip
3) Now hold the gravity gun

**Comment by bigdogmat** [comment]
It's definitely not wiremod, and that code doesn't seem to be related to it.

**Comment by dragitz** [comment]
Thank you all kind people! I'll find something in the future 
Sorry to have opened the issue :)
