### ISSUE TITLE
E2: Add inequality operator (!=) for table

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1159]
Apparently, there is `==`, but no `!=` operator for table.
[Source](https://github.com/wiremod/wire/blob/c25f642c3bec03261b2ba7354000f21fdd3bb095/lua/entities/gmod_wire_expression2/core/table.lua#L281-L283).

**Comment by TomyLobo** [comment]
Go make a PR then. copypaste that function, replace == by !=, test, there you go

**Comment by chinoto** [comment]
Bah, stop being a wuss and do `!(T1==T2)` or `function number table:(T1,T2) {return !(T1==T2)}` :stuck_out_tongue_closed_eyes:
