### ISSUE TITLE
E2 soundPlay issue

### ISSUE THREAD

**Issue by sammyt291** [wiremod/wire#1162]
Hello,
Im unsure if this is a Gmod issue or an E2 issue:

If I run the following:
`soundPlay(1,0,"finetree_sound_pack_v1/speech/misc/ft_1.mp3")
soundPlay(2,0,"finetree_sound_pack_v1/speech/misc/ft_5.mp3")`
It works fine upon spawning and plays both sounds over lapping.

Upon refreshing the e2 the sounds no longer play correctly and are cut off ~0.1 second into the sound(s).
This issue also occurs when replaying the sound(s) internally with a timer or an interval. even one that is longer than the sounds duration.
I have noticed that If I change the pitch of the sound slightly each play this issue does not occur.

Any help in fixing or avoiding this bug would be very appreciated as always,
Best regards,
Sam.

**Comment by Divran** [comment]
I believe this was kind of solved when I told him that the source engine can only play one sound at a time per entity, so I'm closing this.
