### ISSUE TITLE
Pod Controller calls PlayerGiveSWEP without table argument

### ISSUE THREAD

**Issue by roboderpy** [wiremod/wire#1163]
When i use Pod Controller, addons that is using table argiment will crack.
Addon will throw error manually or Lua parser will throw error when addon will try to use nil as table.
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_pod.lua#L532
http://wiki.garrysmod.com/page/SANDBOX/PlayerGiveSWEP
```
[Wiremod] lua/entities/gmod_wire_pod.lua:532: Argument is not a table!
  1. error - [C]:-1
   2. Assert - [VLL: dpp - dpp/sh_init.lua]:1218
    3. fn - [VLL: dpp - dpp/sv_hooks.lua]:599
     4. Run - addons/ulysses/lua/ulib/shared/hook.lua:110
      5. unknown - lua/entities/gmod_wire_pod.lua:532

[DPP] ERROR: Argument is not a table!
TO USERS: THIS IS A BUG IN lua/entities/gmod_wire_pod.lua:532

*DPP no longer assert this*
```

**Comment by GanjaFarmer** [comment]
As you are the author of dpp, do you really need to show an error if that table is nil ? If you absolutely want the model of the SWEP, you can check inside hook PlayerSpawnedSWEP. This is the hook where you should call logSpawn anyway.

**Comment by roboderpy** [comment]
PlayerSpawnedSWEP is called only if player spawns swep using toolgun. And you are right, i really shouldnt throw errors if table is nil. But still, it needs to have table argument because wiki says so. Easy way to do it: call hook with weapons.Get() function

**Comment by GanjaFarmer** [comment]
Oops sorry. Is wiremod the only concerned addon? By the way there is the same problem here:
https://github.com/wiremod/wire/blob/c25f642c3bec03261b2ba7354000f21fdd3bb095/lua/entities/gmod_wire_las_receiver.lua#L33

**Comment by Divran** [comment]
You are correct that this is a problem in wiremod,  but it has been that way for many,  many years now and no one has had any issues that we know of. Still, it's an easy fix so I'll take a look in about 2 hours

**Comment by Divran** [comment]
There. @roboderpy please try the above pull request and see if it fixes the problem. I'll merge if it works

**Comment by bigdogmat** [comment]
@Divran Also the ones [here](https://github.com/wiremod/wire/blob/c25f642c3bec03261b2ba7354000f21fdd3bb095/lua/entities/gmod_wire_pod.lua#L540) and [here](https://github.com/wiremod/wire/blob/c25f642c3bec03261b2ba7354000f21fdd3bb095/lua/entities/gmod_wire_pod.lua#L532)

**Comment by Divran** [comment]
@bigdogmat the second of those links was already done. Fixing the first now. See the PR for updates

**Comment by roboderpy** [comment]
I can say that it should work without any test. It is safe to merge that code.
