### ISSUE TITLE
drv_udh.txt fails to compile

### ISSUE THREAD

**Issue by oldmud0** [wiremod/wire#1168]
I am using the latest unmodified version of Black Phoenix's drv_udh as included in the Wire repo. However, I cannot run the UDH example also included by default, because while compiling the program, it gives me this ominous error:
```
[lib\drivers\drv_udh.txt 121:14]: Undefined label: 
```
where line 121 is `*devPtr++ = i;` which can be found [here](https://github.com/wiremod/wire/blob/master/data/cpuchip/lib/drivers/drv_udh.txt#L121).

I'm a newbie to ZCPU; unfortunately there are few people who know how to work it still around on servers. Any help is appreciated.

-----

EDIT: It seems the editor hates me, as the validation button seems to have broke on me:
![Saved as cpuchip/examples/udh_test.txt](https://cloud.githubusercontent.com/assets/5247009/16542295/8b4da3e8-4068-11e6-8a41-0d22b23704fc.png)
Clicking it does nothing.

**Comment by its-suun** [comment]
I can't replicate your issue; compiling the example and the driver works for me.

> EDIT: It seems the editor hates me, as the validation button seems to have broke on me:  

I fixed the validation button ages ago, see #978
So eh, if the button is buggy for you, you maybe have wiremod from last year and you should update it.

**Comment by oldmud0** [comment]
Wolp, looks like there was an old `wire` folder conflicting with the Workshop version. Deleted stupid workshop and updated the wire folder, now it compiles. Now onto figuring out how to wire it up... (looks inside ages-old CPU Tutorials subforum)

**Comment by TomyLobo** [comment]
how about instead deleting the old wire folder and using the workshop version, which does not need manual updating? :)

**Comment by oldmud0** [comment]
because the workshop version is grossly outdated? :)

**Comment by bigdogmat** [comment]
> because the workshop version is grossly outdated

It's only a few commits behind master...

**Comment by oldmud0** [comment]
hardly any commits these months than there were at the beginning of the year. You know you'd think it'd be the other way around because school, but no.
