### ISSUE TITLE
E2: Comment(s) after #include directive results in invalid E2

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1176]
Hello,

Just yet another day with Expression 2 scripting..
It is worth noting that this issue exists even in Workshop version, and still exist at this point (on master branch). @TomyLobo, thanks for confirming that this issue exists in Workshop version.

For example:

```
#include "path/to/lib/file"  # Include some E2 lib.
```

Screenshot:
![image](https://cloud.githubusercontent.com/assets/9789070/16647096/d95e07d0-442d-11e6-801f-f7252c45e815.png)
Output:

> Unknown character found (.) at line 1, char 51

<br>
By removing `.` from the comment:

```
#include "path/to/lib/file"  # Include some E2 lib
```

Screenshot:
![image](https://cloud.githubusercontent.com/assets/9789070/16647178/4514bd7a-442e-11e6-8742-d4f546fe7c01.png)
Output:

> Left parenthesis (() must appear after function name, variables must start with uppercase letter, at line 1, char 30

<br>
By removing the comment, like this:

```
#include "path/to/lib/file"
```

Screenshot:
![image](https://cloud.githubusercontent.com/assets/9789070/16647235/8f20a820-442e-11e6-8135-a1f0d31acd86.png)
Output:

> Validation successful

**Comment by oldmud0** [comment]
This is in fact a bug, not a feature. C allows placing comments on `#include`s

**Comment by CaptainPRICE** [comment]
@oldmud0
> This is in fact a bug, not a feature.

Of course this is a bug.

> C allows placing comments on `#include`s

You mean after include statement. Sure it does, why would not it. (< is not a question)

**Comment by AbigailBuccaneer** [comment]
C also allows things like:

```C
/* now */ # /* we */ include /* all of */ <dlfcn.h> // so we can use its functions
```
This is because comments are replaced with spaces before any other tokenization or preprocessor directive parsing.

**Comment by Divran** [comment]
@AbigailBuccaneer E2's preprocessor is supposed to get rid of comments as well, it just missed these because include starts with a `#`

**Comment by TomyLobo** [comment]
Actually a line with an include should not include anything else.
First of all we need a proper error message here and then we can sit down and look at whether it makes sense to allow anything else there.

**Comment by immibis** [comment]
Why wouldn't it make sense to allow comments everywhere? (except inside strings)

**Comment by TomyLobo** [comment]
like i said, that discussion is premature

**Comment by thegrb93** [comment]
Include is a directive and directives are designed to input the whole line. #ifdef or whatever suffers the same issue.

**Comment by thegrb93** [comment]
Will need a new issue asking to allow directives to not consume the whole line following # if this is to change.

**Comment by CaptainPRICE** [comment]
Or, just provide a correct error message and stick with the current design.
Simpler?

**Comment by thegrb93** [comment]
The error message is already correct

**Comment by CaptainPRICE** [comment]
> The error message is already correct

> Left parenthesis (() must appear after function name, variables must start with uppercase letter

How is that correct?!

**Comment by thegrb93** [comment]
Because that's what happens when you try tokenizing invalid input.

**Comment by thegrb93** [comment]
#include acts like a token so you could probably do something like #include getInclude()

**Comment by CaptainPRICE** [comment]
> #include acts like a token so you could probably do something like #include getInclude()

Nooot.

```golo
@persist Include:string
function string getInclude() { return "path/to/lib" }
Include = getInclude()
#include getInclude()
#include Include
```

The same error on line 4th and 5th:
> include path (string) expected after include

```golo
#include "path/to/" + "lib"
```

> Identity operator (+) must not be succeeded by whitespace at line 1, char 21

**Comment by thegrb93** [comment]
Guess not then. Go reverse engineer it yourself. https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/base/compiler.lua#L916

I'm done messing with it.

**Comment by thegrb93** [comment]
Probably need code from https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/base/compiler.lua#L815

if you want it to do that
