### ISSUE TITLE
UX: Icons clip through tree view border

### ISSUE THREAD

**Issue by oldmud0** [wiremod/wire#1177]
Picture explains everything:
![whyyyy](https://cloud.githubusercontent.com/assets/5247009/16670754/7af3c764-4461-11e6-8486-9a9e99c314d0.png)
Blame Garry?

**Comment by Divran** [comment]
yep blame garry

**Comment by CaptainPRICE** [comment]
Maybe customize Derma control, you can do that client-side (yourself, I am pretty sure)?

**Comment by oldmud0** [comment]
Eh, I don't think it'd be worth making a custom control. I'll take it up over at [Facepunch/garrysmod-issues](https://github.com/Facepunch/garrysmod-issues/issues)

**Comment by CaptainPRICE** [comment]
@oldmud0 Better screenshot:

**Comment by oldmud0** [comment]
Filed an issue in Facepunch/garrysmod-issues#2708
