### ISSUE TITLE
Editor: Add an option to remove/delete directory/folder

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1179]
![image](https://cloud.githubusercontent.com/assets/9789070/16687305/282e4f56-4518-11e6-9eb3-d44816014aa8.png)
<br>
To recursively remove/delete all files from selected directory (I have tried to throughout comment it):
[Moved to Gist](https://gist.github.com/CaptainPRICE/7a459de4f101a3e48e63ddff1ba0c1f4#file-file_deletedir-lua).
Please read the comments from the code. It tells you to not add Delete option on root folder (i.e. expression2), just to be sure people don't miss-click and then..
<br>
I see no reason why would not there be such an option, it is client-side :smiling_imp: 
P.S. I have **not** tested the function much.

**Comment by oldmud0** [comment]
It should require confirmation if there are files inside the target folder or subfolders. If it's empty, I see no reason to have confirmation.

**Comment by TomyLobo** [comment]
Always ask for confirmation, but the added information that the folder is not empty would certainly be helpful if available.

**Comment by oldmud0** [comment]
```
There are %n files in this directory! Are you sure you want to delete it?
```

**Comment by TomyLobo** [comment]
%d

**Comment by oldmud0** [comment]
crap, you're right

**Comment by Nebual** [comment]
You're welcome to make this into a proper PR, but otherwise I'll close this issue.

**Comment by CaptainPRICE** [comment]
This was (**and still is**) a feature proposal, PR would autoclose the issue when merged.
I missed on this because you have closed it manually for no reason...
