### ISSUE TITLE
expression2 debuger error "Type check for function "op:sfun()" failed"

### ISSUE THREAD

**Issue by AlexALX** [wiremod/wire#1180]
Ok here is small e2 code:

``` PHP
@name 
@inputs 
@outputs 
@persist 
@trigger 

function number test() {
    print("HELLO")  
    return 1 
}

local Func = "test"
local Res = Func()[number] # also can be used just "test"()[number]
print(Res)
```

When i'm do "wire_expression2_debug 1"  this code fails to execute with this error:

```
sv: Expression 2 (generic): Type check for function "op:sfun()" failed: Return value of void function is not nil.

Trace: 
    1: Line 32  "Trace" lua/includes/extensions/debug.lua
    2: Line 76  "nil"   addons/wire/lua/entities/gmod_wire_expression2/core/init.lua
    3: Line 56  "e2_op_ass" entities/gmod_wire_expression2/core/number.lua
    4: Line 3   "oldfunc"   RunString
    5: Line 69  "nil"   addons/wire/lua/entities/gmod_wire_expression2/core/init.lua
    6: C function
    7: Line 121 "Execute"   addons/wire/lua/entities/gmod_wire_expression2/init.lua
    8: Line 429 "Setup" addons/wire/lua/entities/gmod_wire_expression2/init.lua
    9: Line 260 "func"  addons/wire/lua/wire/stools/expression2.lua
    10: Line 32 "nil"   lua/includes/extensions/net.lua'
```

Whats wrong? Without debuger code works just fine.

**Comment by AbigailBuccaneer** [comment]
`wire_expression2_debug 1` has had problems with various things for a while. (I think for some time any code with a `while` loop in it would fail to compile with it turned on.)

In this case, it's a tricky problem: it properly typechecks all the E2 code, but there's no way of knowing at compile-time what the type signature of a string function is. So the `op:sfun()` operator claims that it just returns `void`, but then at runtime can return a bunch of different things.

I think maybe the debug mode just needs a special case for `op:sfun()`, or a way to declare that it can return anything.

**Comment by chinoto** [comment]
Is `Func()[number]` specifically for functions invoked from a variable?

**Comment by bigdogmat** [comment]
@chinoto Yes

**Comment by TomyLobo** [comment]
@AbigailBuccaneer actually it's things that had problems with ``wire_expression2_debug 1``, not the other way round.
``wire_expression2_debug 1`` merely checks whether the runtime types match the compile-time types. If people add stuff that doesn't match, it's on them, not on ``wire_expression2_debug 1``.

**Comment by TomyLobo** [comment]
About the actual issue: Can't we just remove sfun altogether?
Do we still need it now that we have user-defined functions?

**Comment by Divran** [comment]
We need them BECAUSE we have user-defined functions. We can only remove it once we are able to save functions in variables directly.

**Comment by TomyLobo** [comment]
oh, i thought that was possible already

**Comment by Divran** [comment]
Nah, several people have attempted (I took a look at it as well) but none of them were experienced enough to actually do it (myself included).

**Comment by Vurv78** [comment]
This exact code works fine for me right now, maybe the optimizer pr fixed it somehow

**Comment by thegrb93** [comment]
Sounds good to me
