### ISSUE TITLE
E2: Implement indexer for complex and matrix types

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1182]
Since string type already implements this sort of functionality, I think it would be nice to have "indexer" for the following types:
- angle
- complex
- matrix
- matrix2
- matrix4
- quaternion
- vector
- vector2
- vector4
- wirelink*

Here is an example of how string indexer works (source: [extended/string](https://github.com/CaptainPRICE/Wire-Data-New/blob/master/Wire-Data/expression2/e2shared/lib/extended/src/string.txt) module):

```
#ifndef string:reverse()
    function string string:reverse()
    {
        if (This:length() < 2)
        {
            return This
        }
        local Reversed = ""
        for (Index = This:length(), 1, -1)
        {
            Reversed += This[Index]
        }
        return Reversed
    } # End of function string=s:reverse()
#endif
```

Above function reverses order of characters in a given string. If you look inside the loop, you see `This[Index]`, which returns a single-character string that is positioned at given index for the specified string/text. Okay, but that is just for string type. Also, for string type, I think this is the same as using `string=This:sub(Index, Index)` function.

Now the following is what I would suggest for other types, as to what indexer getter would return and setter would assign (at least that's what get functions in [extended/indexer](https://github.com/CaptainPRICE/Wire-Data-New/blob/master/Wire-Data/expression2/e2shared/lib/extended/src/indexer.txt) module returns, while set functions assign a value at that index):

<h4>angle</h4>

```
number = angle[1] -- Get Pitch component of Angle (angle.p or angle.pitch).
number = angle[2] -- Get Yaw component of Angle (angle.y or angle.yaw).
number = angle[3] -- Get Roll component of Angle (angle.r or angle.roll).
```

<h4>complex</h4>

```
number = complex[1] -- Get Real component of Complex (complex.real).
number = complex[2] -- Get Imaginary component of Complex (complex.imag).
```

<h4>matrix</h4>

```
number = matrix[1] -- Get element at Row:1/Column:1 of Matrix.
number = matrix[2] -- Get element at Row:1/Column:2 of Matrix.
number = matrix[3] -- Get element at Row:1/Column:3 of Matrix.
number = matrix[4] -- Get element at Row:2/Column:1 of Matrix.
number = matrix[5] -- Get element at Row:2/Column:2 of Matrix.
number = matrix[6] -- Get element at Row:2/Column:3 of Matrix.
number = matrix[7] -- Get element at Row:3/Column:1 of Matrix.
number = matrix[8] -- Get element at Row:3/Column:2 of Matrix.
number = matrix[9] -- Get element at Row:3/Column:3 of Matrix.
```

<h4>matrix2</h4>

```
number = matrix2[1] -- Get element at Row:1/Column:1 of Matrix2.
number = matrix2[2] -- Get element at Row:1/Column:2 of Matrix2.
number = matrix2[3] -- Get element at Row:2/Column:1 of Matrix2.
number = matrix2[4] -- Get element at Row:2/Column:2 of Matrix2.
```

<h4>matrix4</h4>

```
number = matrix4[1]  -- Get element at Row:1/Column:1 of Matrix4.
number = matrix4[2]  -- Get element at Row:1/Column:2 of Matrix4.
number = matrix4[3]  -- Get element at Row:1/Column:3 of Matrix4.
number = matrix4[4]  -- Get element at Row:1/Column:4 of Matrix4.
number = matrix4[5]  -- Get element at Row:2/Column:1 of Matrix4.
number = matrix4[6]  -- Get element at Row:2/Column:2 of Matrix4.
number = matrix4[7]  -- Get element at Row:2/Column:3 of Matrix4.
number = matrix4[8]  -- Get element at Row:2/Column:4 of Matrix4.
number = matrix4[9]  -- Get element at Row:3/Column:1 of Matrix4.
number = matrix4[10] -- Get element at Row:3/Column:2 of Matrix4.
number = matrix4[11] -- Get element at Row:3/Column:3 of Matrix4.
number = matrix4[12] -- Get element at Row:3/Column:4 of Matrix4.
number = matrix4[13] -- Get element at Row:4/Column:1 of Matrix4.
number = matrix4[14] -- Get element at Row:4/Column:2 of Matrix4.
number = matrix4[15] -- Get element at Row:4/Column:3 of Matrix4.
number = matrix4[16] -- Get element at Row:4/Column:4 of Matrix4.
```

<h4>quaternion</h4>

```
number = quaternion[1] -- Get Real component of Quaternion (quaternion.real).
number = quaternion[2] -- Get I component of Quaternion (quaternion.i).
number = quaternion[3] -- Get J component of Quaternion (quaternion.j).
number = quaternion[4] -- Get K component of Quaternion (quaternion.k).
```

<h4>vector</h4>

```
number = vector[1] -- Get X component of Vector (vector.x).
number = vector[2] -- Get Y component of Vector (vector.y).
number = vector[3] -- Get Z component of Vector (vector.z).
```

<h4>vector2</h4>

```
number = vector[1] -- Get X component of Vector2 (vector.x).
number = vector[2] -- Get Y component of Vector2 (vector.y).
```

<h4>vector4</h4>

```
number = vector[1] -- Get X component of Vector4 (vector.x).
number = vector[2] -- Get Y component of Vector4 (vector.y).
number = vector[3] -- Get Z component of Vector4 (vector.z).
number = vector[4] -- Get W component of Vector4 (vector.w).
```

<h4>wirelink</h4>\* (a bit special)

```
number = wirelink[address]      => wirelink:readCell(address)     -- Getter. Read (number) from address.
void   = wirelink[address] = N  => wirelink:writeCell(address, N) -- Setter. Write (number) N to address.
```

**Comment by bigdogmat** [comment]
vector, vector2, vector4, quaternion, wirelink, and angle already have index operators. Both setters and getters.

Only types that don't are matrix* and complex

**Comment by CaptainPRICE** [comment]
@bigdogmat
> vector, vector2, vector4, quaternion, wirelink, and angle already have index operators. Both setters and getters.

Ah, right. https://github.com/wiremod/wire/commit/51125d1772d073eec136d5d4f61fa96d64f2a888

> Also, your reverse method for strings is [already implemented](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/string.lua#L384-L386) in the string library

Yes.. But, I remember I was on some server (that was a while ago), and when I searched for such function, it wasn't there (at that time). That's why it is (now) enclosed with `#ifndef` directive ;)
So, I kept it there to see how it is/was done.

**Comment by TomyLobo** [comment]
wouldnt it be easier to just have toArray functions?

**Comment by oldmud0** [comment]
He wants it Python-style.

**Comment by TomyLobo** [comment]
but shittons of new code for such a slim use case doesn't sound terribly efficient.
With X:toArray() you cover at least two use cases at once

**Comment by oldmud0** [comment]
Aren't they supposed to be immutable anyway?

**Comment by TomyLobo** [comment]
That's another concern... Don't add setters :)
toArray should just return table.Clone(this) or what it's called

**Comment by CaptainPRICE** [comment]
I have just run over [this](https://github.com/wiremod/wire/blob/b489718b94182a4a6c3a52cf7b7ffb5a49f8b544/lua/entities/gmod_wire_expression2/core/wirelink.lua#L403-L409).. It is wirelink indexer for setting a value at address.
Now, from what I see, that works different than the actual function ([WriteCell](https://github.com/wiremod/wire/blob/b489718b94182a4a6c3a52cf7b7ffb5a49f8b544/lua/entities/gmod_wire_expression2/core/wirelink.lua#L375-L380))..
I mean look at the first two checks:
WriteCell:
```
if not validWirelink(self, this) then return 0 end
if not this.WriteCell then return 0 end
```

Indexer:
```
if not validWirelink(self, this) then return value end
if not this.WriteCell then return value end
```

Seriously.. Then finally indexer calls into WriteCell (that again performs same checks), ignores return value from it, so indexer forces `value` while WriteCell returns either 1 or 0:
WriteCell:
```
if this:WriteCell(address, value) then return 1 else return 0 end
```

Indexer:
```
this:WriteCell(address, value)
return value
```

And just underneath that indexer setter, is the getter which is actually an alias to ReadCell:
```
e2function number wirelink:operator[](address) = e2function number wirelink:readCell(address)
```

What the F***. (That has to be cleaned-up.)

**Comment by TomyLobo** [comment]
The difference here is, the function returns whether it succeeded, whereas the operator returns the value that was assigned, in order to be chainable.

**Comment by CaptainPRICE** [comment]
So, that is valid?
Hm.. And how do you mean to chain that indexer setter?

**Comment by bigdogmat** [comment]
> Hm.. And how do you mean to chain that indexer setter?

`link[address] = link[address_2] = link[address_3] = somevalue`

**Comment by CaptainPRICE** [comment]
@bigdogmat Okay, I see, now that makes sense. I am sorry this went off-topic now.
But, I could sworn chaining like that wasn't there when I have first attempted it like this (long time ago):
```
@persist A B T:table
T["C", number] = B = A = 123
```

**Comment by TomyLobo** [comment]
https://github.com/wiremod/wire/commit/e024d79271e78938de0773844d77747468fafecb I think this introduced it, but I'm not sure.
