### ISSUE TITLE
Wiremod Textures Error

### ISSUE THREAD

**Issue by samennis1** [wiremod/wire#1183]
I have had wiremod for a while now, but today when I joined my favourite server, all the wiremod contraptions and tools were... errors? They have never been errors until now, I don't know what happened.

Please help.
Thanks,
Sam

**Comment by AbigailBuccaneer** [comment]
Are they still errors when playing in singleplayer? If not, then it's a problem with the server, and you should contact the server owner.

**Comment by AbigailBuccaneer** [comment]
Feel free to reopen this issue if you have any useful info.
