### ISSUE TITLE
E2: s:gmatch(s,[n]) is documented incorrectly

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1185]
[string:gmatch](https://github.com/wiremod/wire/blob/b489718b94182a4a6c3a52cf7b7ffb5a49f8b544/lua/entities/gmod_wire_expression2/core/string.lua#L435-L478)

s:gmatch(s) docs:
> runs string.gmatch(S, S2) and returns the captures in an array

s:gmatch(s,n) docs:
> runs string.gmatch(S, S2, N) and returns the captures in an array

Test code:
```
@outputs Str:string [Gmatch,TypeIDs]:table

Str = "Ceca"

Gmatch = Str:gmatch("[0-9A-Fa-f][0-9A-Fa-f]")
#[
1:
		1	=	Ce
2:
		1	=	ca
]#
printTable(Gmatch)

print("____________________")

TypeIDs = Gmatch:typeids()
#[
1	=	r
2	=	r
]#
printTable(TypeIDs)

# So, it is an array? Let's check.
foreach (Index, Value:array = Gmatch)
{
    print(_HUD_PRINTTALK, Index, Value)  # Nothing.
}
# Nope. Nothing happened.

# Perhaps it is a table?
foreach (Index, Value:table = Gmatch)
{
    print(_HUD_PRINTTALK, Index, Value)  # Nothing.
}
# Damn it Divran.
```

Output:
> 1:
> 		1	=	Ce
> 2:
> 		1	=	ca
> ____________________
> 1	=	r
> 2	=	r

Edit:
And here is a screenshot of what E2 Helper says, table:
![image](https://cloud.githubusercontent.com/assets/9789070/16897659/1604239a-4bb8-11e6-9ef5-1cffa281aff1.png)

**Comment by bigdogmat** [comment]
On each iteration, the results are stored in an array, and added to a table. The reason you're not getting any output is because foreach doesn't loop through numeric indexes for tables.

#1060

**Comment by Divran** [comment]
Use 
```
for(I=1,Result:count()) {
    #whatever
}
```

**Comment by CaptainPRICE** [comment]
So, there comes "inefficient" for-loop to save the party xD

**Comment by Divran** [comment]
for loops are the most efficient, what are you talking about

**Comment by bigdogmat** [comment]
They're efficient in terms of Lua, in E2 they use a lot more ops because of running the getters on the table

**Comment by CaptainPRICE** [comment]
Right. But, why it says that they return a table in E2 Helper?!

**Comment by bigdogmat** [comment]
Because they do return a table, within that table are arrays of all the matches

**Comment by oldmud0** [comment]
> So, there comes "inefficient" for-loop to save the party xD
What, you expected iterators? #PythonToTheRescue

**Comment by TomyLobo** [comment]
oh shit there's a tab instead of 4 spaces and now my program does something different

**Comment by CaptainPRICE** [comment]
Okay, now that we had some laugh in here, and figured what was wrong..
*Just* correct the docs, along with other hundred(s) with confusing/invalid docs.
So, I think I should close this issue or perhaps not?

**Comment by TomyLobo** [comment]
or rename it to "blahblah is documented wrong"

**Comment by CaptainPRICE** [comment]
Sorry about "backstroke bot", it had bugged out at some point...
-----
@Divran Lets reopen this.
#1395
