### ISSUE TITLE
Cam Controller not working on singleplayer?

### ISSUE THREAD

**Issue by Tyler13700** [wiremod/wire#1186]
I have had this issue many times, if i use a cam controller on anything, It will just prompt me with a TON of errors about the lua code. I remember seeing something about comparing a nil value and a bunch of things similar to that, I go on any casual server and its fine.

**Comment by oldmud0** [comment]
What is the error?

**Comment by TomyLobo** [comment]
It's likely a conflicting addon you have installed from workshop that doesnt get activated when you play on a server.
So we can't help you without that error message.
