### ISSUE TITLE
Validation successful for invalid E2

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1200]
```
function string ()
{
    "Hello World"
    return
}
function string ( )
{
    local "X"
}
```

![Validation successful](https://cloud.githubusercontent.com/assets/9789070/17705720/b0639496-63d9-11e6-9fb5-a2753efbc5e2.png)

**Comment by oldmud0** [comment]
and what happens when you try to run it?

**Comment by TomyLobo** [comment]
probably nil strings :)

**Comment by bigdogmat** [comment]
There's 2 "issues" here.

1. Local operator not forcing a declaration to come after it.
2. When the parser can't find any statements it starts looking for expressions, without this you wouldn't be able to use function calls as both statements and expressions. The one side effect from this is all expressions are accepted as statements. So random strings, numbers, etc are accepted as valid lines.
