### ISSUE TITLE
Enumerated type (@enum) for E2

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1205]
Here is my second attempt..
Another, probably better design for [@const directive](https://github.com/wiremod/wire/issues/1173) (#1173) in Expression 2.
Quite similar concepts. Enumerations could be accessed using a dot (**.**) notation:
    `NameOfEnum.MemberName`
They should be **read-only**, and also I would prefer it to be "per-file".
In order to use enums, you would use `#include` directive, and specify relative path (from `expression2` folder) to the enum file (without `.txt` extension).

```
# Simple example, Boolean enumeration definition:
# "@enum" line specifies the name of enumeration, it should match the variable name regex (right-hand value should be trimmed first).
@enum Bool
# Followed by "#value" directive(s), those are going to be the members of "Bool" enum:
#value False = 0
#value True  = 1
```

```
# Example usage:
#include "path/to/enums/bool"
print(Bool.False) # 0
print(Bool.True ) # 1

# Iterate through Bool enumeration (name, value) pair:
foreach (Name, Value:number = Bool)
{
    print(Name, Value)
}
#[
False   0
True    1
]#
```

Okay, that was simple. There is more, lets try Color.
Members of enum does not have to be assigned to their value explicitly! Look at enum definition below:
```
@enum Color
#value Red
#value Green
#value Blue
```

What do you think `Color.Red` would be equal to?

Speaking from my perspective, we who are familiar with real-world programming languages such as C-family (including .NET and Java), `Color.Red` would be equal to `0` (not `1`).
However, in Lua, there is no enumeration constraint, but if you look at tables, indexes start from `1`.
We could have a whole discussion just about this implementation detail (0 vs 1). But, seriously, **it is should not even matter**, that's one of the points of why enumerated type exists; Stop using hard-coded (magic) integers (all over the place). By using enums appropriately, it increases code readability which in return make it easier to maintain!
Moving on...

Now, let's take a look at enumerated type in a few programming languages:

### C++11
Definition: `enum class Color { Red, Green, Blue };`
Access: `Color::Red` returns `0` (as int).

### C / C++ / C# / Java / TypeScript
Definition: `enum Color { Red, Green, Blue };`
C/C++ access: `Color::Red` or `Red` returns `0` (as int).
Access: `Color.Red` returns `0` (as integer).

### F&#35;
Definition: `type Color = Red=0 | Green=1 | Blue=2`
Access: `Color.Red` returns `0` (as int).

### JavaScript
Definition:
```
const Color = Object.freeze({
    "Red": 0,
    "Green": 1,
    "Blue": 2
});
```

Access: `Color.Red` returns `0`.

### Python 3.4
Definition:
```
from enum import Enum
class Color(Enum):
    Red = 0
    Green = 1
    Blue = 2
```

Access: `Color.Red` returns `0` (as int).

### Visual Basic
Definition:
```
Enum Color
    Red
    Green
    Blue
End Enum
```

Access: `Color.Red` returns `0` (as integer), too.

As you can see, most of them (if not all) are zero-based.
Moving on...

Some more enum definitions in Expression 2:
*path/to/enums/dayinweek*:
```
@enum DayInWeek
#value Monday = 1  # Start from 1 (since this enum represents day-in-week, let's respect ISO-8601 standard)
#value Tuesday     # When assignment is omitted, the value of a member is implicitly computed: "previous value + 1", so Tuesday is equal to 2
#value Wednesday   # Previous member value (Tuesday) + 1 = 3
#value Thursday    # Previous member value (Wednesday) + 1 = 4
#value Friday      # You get the idea, this one is equal to 5
#value Saturday    # 6th is awesome
#value Sunday      # 7th is awesome, too
```

*path/to/extensions/dayinweek*:
```
if (first())
{
    #include "path/to/enums/dayinweek"

    function string enum:tellHowItIs()
    {
        if (!This:isEnum(DayInWeek)) # Ew..?
        {
            error("Specified enum is not DayInWeek")
        }
        switch (This)
        {
            case DayInWeek.Monday:
            case DayInWeek.Tuesday:
                return "Baad"
            case DayInWeek.Wednesday:
            case DayInWeek.Thursday:
                return "So-so"
            case DayInWeek.Friday:
                return "Good"
            case DayInWeek.Saturday:
            case DayInWeek.Sunday:
                return "Awesome"
            default:
                error("enum case (" + int(This) + ") is not handled")
        }
    }
}
```

Now a script to show the use of above:
```
if (first())
{
    #include "path/to/extensions/dayinweek"

    foreach (NameOfDay, Value:enum = DayInWeek) # Ew..?
    {
        print(Value:tellHowItIs())
    }
}

#[
Baad
Baad
So-so
So-so
Good
Awesome
Awesome
]#
```

Challenge: See if you can "catch the bugs" below, in MonthOfYear enum?
```
@enum MonthOfYear
#value January = 1 # We all know January is the first one, right.
#value February
#value March
#value April
#value May
#value July
#value June
#value August = July + 2
#value October
#value September
#value November = 11
#value December # Yes, it is the bottom one. It is 12th (previous member value "November" + 1).
```

(Hint: Two months were swapped, and one has wrong value.)

**EDIT 2**
One more thing, multiple enums can hold the same value (and the value may be computed from the existing member using math arithmetic):
*path/to/enums/directionprecedence*:
```
@enum DirectionPrecedence
#value Forward  = 1000
#value Backward = Forward
#value Left  = Forward * 2
#value Right = Left
```

`DirectionPrecedence` enum represents *the weight* of turn in which an entity will move.

*path/to/enums/direction*:
```
@enum Direction
#value Forward
#value Backward
#value Left
#value Right
```

Small example usage of above enums:
```
@input Car:entity
@outputs Mul

if (first())
{
    #include "path/to/enums/direction"
    #include "path/to/enums/directionprecedence"

    Mul = 1500

    function enum randomDirection()
    {
        switch (randint(1, 4))
        {
            case 1:
                return Direction.Forward
            case 2:
                return Direction.Backward
            case 3:
                return Direction.Left
            case 4:
                return Direction.Right
        }
    }

    function enum enum:toDirectionPrecedence()
    {
        if (!This:isEnum(Direction))
        {
            error("Specified enum is not Direction")
        }
        switch (This)
        {
            case Direction.Forward:
                return DirectionPrecedence.Forward
            case Direction.Backward:
                return DirectionPrecedence.Backward
            case Direction.Left:
                return DirectionPrecedence.Left
            case Direction.Right:
                return DirectionPrecedence.Right
        }
    }

    function enum enum:higherDirectionPrecedence(DPrecedence:enum)
    {
        if ((!This:isEnum(DirectionPrecedence)) | (!This:isEnum(DirectionPrecedence)))
        {
            error("Specified enum is not DirectionPrecedence")
        }
        if (int(This) < int(DPrecedence))
        {
            return DPrecedence
        }
        return This
    }

    function vector entity:toDirVector(Enum:enum)
    {
        if (Enum:isEnum(Direction))
        {
            switch (Enum)
            {
                case Direction.Forward:
                    return This:forward()
                case Direction.Backward:
                    return -This:forward()
                case Direction.Left:
                    return -This:right()
                case Direction.Right:
                    return This:right()
            }
        }
        if (Enum:isEnum(DirectionPrecedence))
        {
            switch (Enum)
            {
                case DirectionPrecedence.Forward:
                    return This:forward()
                case DirectionPrecedence.Backward:
                    return -This:forward()
                case DirectionPrecedence.Left:
                    return -This:right()
                case DirectionPrecedence.Right:
                    return This:right()
            }
        }
        error("Unsupported enum argument")
    }
}
elseif (->Car & Car)
{
    Car:setMass(1000)
    local Rnd1 = randomDirection():toDirectionPrecedence()
    local Rnd2 = randomDirection():toDirectionPrecedence()
    local High = Rnd1:higherDirectionPrecedence(Rnd2)
    print(Rnd1:toString(), Rnd2:toString(), High:toString())
    Car:applyForce(Car:toDirVector(High) * Mul)
}

interval(1000)
```

If you would wire `Car` input to a cube or some vehicle/entity, it would apply force based on random pick (every 1s) while respecting their precedence (`DirectionPrecedence`).

EDIT 3:
Perhaps the following is somewhat a better example?

*path/to/enums/rank*:
```
@enum Rank
#value Unknown
#value Banned
#value Fackboi
#value Bot
#value Guest
#value Player
#value Member
#value TrialRegular
#value Regular
#value Trusted
#value TrialModerator
#value Moderator
#value SuperModerator
#value Admin
#value SuperAdmin
#value Developer
#value WebDeveloper = Developer
#value Owner
#value CoOwner = Owner
#value Garry
```

```
if (first())
{
    #include "path/to/enums/rank"

    function enum entity:rankFromTeam()
    {
        if (!Entity:isPlayer())
        {
            error("Specified entity is not a player")
        }
        switch (This:team())
        {
            case 5:
                return Rank.Banned
            case 6:
                return Rank.Fackboi
            case 10:
                return Rank.Bot
            case 20:
                return Rank.Guest
            case 30:
                return Rank.Player
            case 40:
                return Rank.Member
            case 50:
                return Rank.TrialRegular
            case 60:
                return Rank.Regular
            case 70:
                return Rank.Trusted
            case 80:
                return Rank.TrialModerator
            case 90:
                return Rank.Moderator
            case 100:
                return Rank.SuperModerator
            case 110:
                return Rank.Admin
            case 120:
                return Rank.SuperAdmin
            case 130:
                return Rank.Developer
            case 140:
                return Rank.WebDeveloper
            case 150:
                return Rank.Owner
            case 160:
                return Rank.CoOwner
            case 9000:
                return Rank.Garry
            default:
                return Rank.Unknown
        }
    }

    function number enum:isValidRank()
    {
        return This:isEnum(Rank) & (This != Rank.Unknown)
    }

    print(Rank.Unknown:isValidRank())  # 0
    print(Rank.Member:isValidRank())   # 1

    foreach (Index, Player:entity = players())
    {
        print(Player:name() + "'s rank is " Player:rankFromTeam():toString())
    }
#[
CaptainPRICE's rank is SuperAdmin
foo's rank is Guest
g0at's rank is TrialRegular
garry :D's rank is Garry
totally not a bot's rank is Bot
Cake is a Lie's rank is Developer
]#
}
```

Oh yeah, this also increases code reuse :)
<br>
NOTE: This should be a part of pre-processor. Floating-point and negative numbers should be allowed.

P.S. You can take a look at how I've defined enumerated type in Expression 2, [here](https://raw.githubusercontent.com/CaptainPRICE/Wire-Data-New/master/Wire-Data/expression2/e2shared/lib/static-reflector/src/enums/preprocessor-directive.txt). `EPreprocessorDirective` simply represents all (valid) pre-processor directives within E2. `__internal` table is to be used by internally by "OO Runtime", that I am still working on.

Check out [wiki](https://en.wikipedia.org/wiki/Enumerated_type) for more information.

 **What do you think of this**?

 Raise your thumb; up - if you support this request, or down - if you don't.

<br>
EDIT: Fixed and added code examples.
EDIT 2: Fixed and added code examples, again (see above).
EDIT 3: Added more code examples, again (see above).
EDIT 4: Added F# and JavaScript (Color) enums to the show, also added a sample of how I implement enum in Expression 2 (throughout my Wire-Data).

**Comment by Divran** [comment]
This feature adds nothing to E2. We already have tables which can do everything this can do and more.

**Comment by its-suun** [comment]
Who would be ready to implement this? There are some lazy people here

**Comment by CaptainPRICE** [comment]
> We already have tables which can do everything this can do and more.

Tables are dynamic. This is meant to be a pre-processor thing (though I used `@value` instead of `#value` in above examples, let me fix that).
Also, enums can only hold a number (internally).

Which opens another door for discussion:
`NameOfEnum["MemberName", number]`
vs
`NameOfEnum.MemberName`

**Comment by Divran** [comment]
>Tables are dynamic (why would you go with table over array?).

So that you can use string indexes

>This is meant to be a pre-processor thing (though I used @value instead of #value in above examples, let me fix that).
Also, enums can only hold a number (internally).

Being a preprocessor thing means nothing if you want to limit it to numbers only. @oldmud0 brought up a great example of a way that a preprocessor directive similar to this could actually add new features to E2, although it's debatable whether or not even his idea is actually useful enough to be added.

>Which opens another door for discussion:
`NameOfEnum["MemberName", number]`
vs
`NameOfEnum.MemberName`

I already brought this up. 10 characters saved. We are not adding a feature just so you can write 10 fewer characters.

**Comment by oldmud0** [comment]
Adding enums implies that Expression 2 supports the object-oriented paradigm, which is not true.

**Comment by Divran** [comment]
As @oldmud0 said, enums are only useful in heavily object oriented languages, such as C# and Java. Languages where not using objects is impossible.

**Comment by TomyLobo** [comment]
@oldmud0 What do enums have to do with object orientation?
Fuckin C has enums!

@CaptainPRICE Your semantics are very very loose. If we add enums, they need to have way less automatic type punning than that and also have a structured way to define them, much like functions.

That said, why do you want enums?
You presented an example, but what I really read from your post is you have enums in a bunch of languages you like, so you propose them for E2 without giving the "why" much of a thought.

**Comment by oldmud0** [comment]
Yeah but C has structs too and E2 doesn't have that kind of luxury.

**Comment by TomyLobo** [comment]
structs would actually be a more useful addition than enums

**Comment by AbigailBuccaneer** [comment]
Most of your examples of other languages are subtly wrong: they say that, for example, Java's `Color::Red` returns `0`, but that's not true: `Color::Red` returns an object of type `Color`, which is distinct from all the other given colors, and which can be converted (via `Enum#ordinal()`) to the value `0`. (In your JavaScript example it does actually return `0` because JavaScript has no real enums, and in C the enum value is implicitly convertible to `0` because C grew up in a world before type safety, but the point still stands throughout the vast majority of languages.)

This is a subtle distinction but it's an important one: if we want to be principled, then `@enum` should create its own new type as well as values of that type. If not, this is just shorthand for a bunch of `@const` directives plus a `@const` enumerable container - so I'd rather see #1173 merged than this approach to enums.

I also really don't like the `#value` syntax here, it feels very fragile and an abuse of the preprocessor.

**Comment by CaptainPRICE** [comment]
> Most of your examples of other languages are subtly wrong: they say that, for example, Java's Color::Red returns 0, but that's not true: Color::Red returns an object of type Color

Not wrong... Apparently, you didn't interpret it the same as I, or you didn't read the parts where I have said:
> as int/integer

So, what I meant by that is, (in this case) when the value of `Color.Red` is casted/converted to int, you get a result of `0` (and that is not an object).
Also, doesn't Java use dot-notation `.` for enum member access (not `::`)?
(OP states that only C/C++ access uses `::`. I've just wanted to cover languages with similar syntax as one and also keep it small, since it is about Expression 2..)
Am I missing something there?!

> I also really don't like the #value syntax here, it feels very fragile and an abuse of the preprocessor.

> have a structured way to define them, much like functions

Okay... If this could be implemented, I think we could agree on (custom) Java-like syntax?

**Comment by AbigailBuccaneer** [comment]
You've missed my point - yes, those enum values can be cast to 0, but it's a very important distinction that those enum values are *not* 0 - they're values of a user-defined type, and so you can write code in a type-safe manner. Whereas in your proposal, all enum values are of the same `enum` type, so you can easily say:
```PHP
@enum DayOfWeek
#value ...
@enum Color
#value ...
@persist Today:enum
Today = Green
```

(And yes, I'm aware that not all languages that I referred to use the syntax I used. I wasn't making a point about their syntax, I was making a point about their semantics.)

How would people feel about `@directives` not necessarily being line-based? I can imagine something like this:

```PHP
@name Hello World
@inputs A B
@enum DayOfWeek {
    Monday = 0,
    Tuesday,
    # ...
    Sunday,
    MyFavoriteDay = Saturday,
}
@persist Today:DayOfWeek

Today = DayOfWeek.MyFavoriteDay
```

The rationale for doing so is that all code outside directives is executed as it's encountered (including functions, which was a really bad choice by whoever implemented functions), whereas directives should be understood by the parser and compiler but not result in any extra executable instructions being generated.

**Comment by TomyLobo** [comment]
I'm entirely against making this a directive. Directives are evaluated by the preprocessor.
They should not introduce new types.

**Comment by AbigailBuccaneer** [comment]
Unfortunately the current structure of the E2 compiler is that there's the preprocessed directives (and I think "preprocessor" is a somewhat inaccurate term - it can introduce new values and configure the chip's input and output, not just do textual substitution), and then there's code that's compiled into instructions. E2's awful function support set the precedent for that.

If you think that should be changed, then I can definitely see a rationale for doing so - but it might involve more structural changes to the E2 compiler (for example if the availability of type names affects parsing, as it does in C/C++).

**Comment by TomyLobo** [comment]
it's a preprocessor in that it preprocesses the source code that goes into the tokenizer
the difference to the tokenizer, for instance, is that the output format is still text, not abstract tokens

**Comment by TomyLobo** [comment]
Wait, are you saying E2 functions are implemented in the preprocessor?

**Comment by Divran** [comment]
They aren't

**Comment by TomyLobo** [comment]
Good.
