### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by its-suun** [wiremod/wire#1208]
[Travis CI](https://travis-ci.org/)

**Comment by oldmud0** [comment]
That's not how that works. We would need to make unit tests.

**Comment by TomyLobo** [comment]
GLua syntax is the smallest problem. We should just get rid of that anyway.

@its-suun the interesting question is: why do you want to "Add Travis CI"?

**Comment by its-suun** [comment]
Why not, shows if there are syntax errors in pull requests

**Comment by oldmud0** [comment]
Might as well make your own integration for that. Would be super simple, just for each commit run the code through [Lua Checker](https://code.google.com/archive/p/lua-checker/) or something. And forget modifying it for GLua, if there's any GLua it's a straight-up error.

**Comment by AbigailBuccaneer** [comment]
"Make your own integration" involves making your own web service, which involves more things that actively need a maintainer. I'd be in favour of having Travis lint our code (whether with a full-featured linter or just with `luac -p`). It can also be used to check other small low-level commit hooks such as code style, trailing whitespace and no-newline-at-end-of-file automatically, which means code reviewers can concentrate on more important tasks.

**Comment by Anticept** [comment]
I added travis ci

**Comment by oldmud0** [comment]
no, we needed an election

**Comment by AbigailBuccaneer** [comment]
@Anticept @TomyLobo somebody needs to flick the repository switch at https://travis-ci.org/profile/wiremod .

**Comment by TomyLobo** [comment]
can you tell me what exactly i have to do there? all i get is a page with some useless info and a loading indicator in the middle

**Comment by Anticept** [comment]
I've flipped this on for the repos, but @AbigailBuccaneer you'll need to make the .travis.yml file for each repo.

**Comment by TomyLobo** [comment]
I still dont see wiremod there, but at least I see my own repos now

**Comment by CaptainPRICE** [comment]
> do the first push

Maybe it was not intended as the first push..
![image](https://cloud.githubusercontent.com/assets/9789070/18271883/f1df5d86-7434-11e6-992d-37fa19bfa9f2.png)

**Comment by CaptainPRICE** [comment]
Maybe turn off Travis until yml and setup files are uploaded to the repository, so we don't see (invalid) failures?
Something I found on Google, there are pretty much all Lua modules on one place: [Lua Toolbox](https://lua-toolbox.com). There are only a few ones which I see are useful for wire:
[luarocks](https://luarocks.org) / [hererocks](https://github.com/mpeterv/hererocks)
[luacheck](https://github.com/mpeterv/luacheck)

**Comment by AbigailBuccaneer** [comment]
Yeah, I've done Lua + travis before, and hererocks (which is a python package that can easily install arbitrary versions of Lua and LuaRocks) is the easiest way to go about it. I've not used Luacheck before but it seems reasonable.

For now I've just enabled the "Build only if .travis.yml is present" option, which should stop any more builds being attempted and failed before a `.travis.yml` gets added.

**Comment by AbigailBuccaneer** [comment]
Fixed in #1219.

**Comment by Anticept** [comment]
@AbigailBuccaneer i've given you higher level access so you have administrative control of the repos. I hope that makes things easier.

**Comment by AbigailBuccaneer** [comment]
Thanks @Anticept. For now, the Wiremod build fails if the set of changed files contain any non-standard Lua constructs, and I've disabled the builds for advduplicator, advdupe2 and wire-extras until they have `.travis.yml` files. I'll add Wiremod's `.travis.yml` when I have time tomorrow.

There's a slight question around syntactic validation and E2 preprocessing - currently all pull requests that modify E2 extension files (which is a lot of them because E2 killed almost all interest in any parts of Wiremod except E2), but they intentionally use non-standard Lua. Hopefully it'll be possible to run the E2 preprocessing from Travis without having to duplicate the code.

**Comment by TomyLobo** [comment]
@AbigailBuccaneer tomorrow is nigh!

**Comment by CaptainPRICE** [comment]
> tomorrow is nigh!

tomorrow™
the near future.
