### ISSUE TITLE
Move the existing IRC channel to a server with a proprietary web interface

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1210]
It seems there is wiremod community [on Gitter](https://gitter.im/orgs/wiremod/rooms), but there are no rooms. :sob: 

Create some rooms!

**Comment by Divran** [comment]
wtf is gitter

**Comment by Jack37** [comment]
I don't know what happened to the room, but it was there. I stopped using it because it was pretty dead.

**Comment by CaptainPRICE** [comment]
> wtf is gitter

You can look at it like real-time chat (like Steam group chat, though Steam chat is just plain text). Gitter supports Markdown, each room can be configured (i.e. show different welcome message, only allow GitHub users to join chat, etc.). It can also display various activity for the repository. Simple, beautiful, and free!
Create a test repository, and try it :)

> I stopped using it because it was pretty dead.

Maybe because there isn't any link to it?
There is a feature on Gitter, to automatically push a pull request which will add a "badge" in readme.

**Comment by TomyLobo** [comment]
you mean it's like IRC, except I need to keep a website open all the time?

**Comment by its-suun** [comment]
You can connect to gitter with IRC too (https://irc.gitter.im/). I would define it as irc chat with fancier web interface.

**Comment by AbigailBuccaneer** [comment]
It's worth mentioning, we already have an IRC channel: `irc.gamesurge.net #wiremod`. So this issue is really "move the existing IRC channel to a server with a proprietary web interface".

**Comment by CaptainPRICE** [comment]
Never heard of that before @AbigailBuccaneer.
Seriously, update readme with those information...

**Comment by Jack37** [comment]
Alright so the room is there, but it's only for Wiremod members I guess, thatswhy you don't see it. I think it was supposed to be used for dev chats, and there are few messages from jan 2015.

> wtf is gitter

You are in the room

**Comment by oldmud0** [comment]
So if I miss something on IRC, are there any logs for me to catch up?

**Comment by TomyLobo** [comment]
if you want a record, use reddit or a github issue, whichever is appropriate

**Comment by Anticept** [comment]
I feel like discord would be a better choice.

**Comment by Nebual** [comment]
Use Discord for this purpose: https://discord.gg/cqJ45CT

**Comment by Anticept** [comment]
Note that the discord is official.
