### ISSUE TITLE
ZCPU editor's debugging buttons are not docked to right

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1215]
Relevant source lines: [here](https://github.com/wiremod/wire/blob/88cd413c8717133af4bf8e400b773096475d6707/lua/wire/client/text_editor/wire_expression2_editor.lua#L1904-L1938).

Short media (it also includes #1214 issue, at the end):
![demo](https://i.imgur.com/n8Ini1z.gif)

(edit; add) Expression 2 editor:
![demo 2](https://cloud.githubusercontent.com/assets/9789070/18386151/424929ca-7695-11e6-9946-f07b43e3905c.gif)

NOTE: This issue has been found on GMod dev branch (version: 160905).

**Comment by TomyLobo** [comment]
So they aren't... what's your point?

**Comment by oldmud0** [comment]
They should be.

**Comment by TomyLobo** [comment]
...and why?

**Comment by its-suun** [comment]
It can hide the other buttons (save, new file) below it.

**Comment by TomyLobo** [comment]
And that doesn't happen if we dock the buttons to the right?

**Comment by its-suun** [comment]
It doesn't happen cause they get moved then too when you move the editor

**Comment by TomyLobo** [comment]
But they'd disappear at the same point as before, just in the opposite order.
So how does this make a difference?

**Comment by Divran** [comment]
The only difference it makes is that it would look nicer

**Comment by CaptainPRICE** [comment]
Actually, there is no point for this to be labeled with "Gmod dev branch". It was always like this, and it still is. This was meant to be a suggestion..
