### ISSUE TITLE
Editor: Add undo and redo history buttons

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1216]
We know about `CTRL/CMD`+`Z` (undo), `CTRL/CMD`+`Y` (redo). Those actions can also be performed from right-click context menu on text editor.

How about adding undo and redo buttons (next to "Refresh file" button)?

There are already icons for those in (famfamfam) [Silk icons pack](http://www.famfamfam.com/lab/icons/silk/previews/index_abc.png) (which is imported into Garry's Mod).
"arrow_redo" and "arrow_undo".

**Comment by oldmud0** [comment]
Ctrl+Shift+Z anyone?
