### ISSUE TITLE
Pushing the latest to workshop

### ISSUE THREAD

**Issue by Anticept** [wiremod/wire#1223]
@wiremod/developers 

We've regained control of the wireteam account. I'd like to get the ball rolling and get the latest pushed to workshop, unless there's a reason not to.

The wiremod core team members will be entrusted with the most important account and password information from here on out. This will make it much easier to maintain services.

I believe it was jenkins that was used to automatically update the workshop as well. I have a VPS and the wiremod core members will have access. It's on the todo list.

If there's any readmes, credits, etc that needs to be updated, that should be done in preparation for this push.

Finally, any links and such should be updated to point to JUST [wiremod.com](url), [reddit.com/r/wiremod](url), or [reddit.com/r/wiremod/wiki/](url) wiki pages. In addition, we now have a discord server set up (https://discord.gg/cqJ45CT) that should be put in the wire menu :-)

**Comment by Anticept** [comment]
In addition: https://github.com/wiremod/advdupe2/issues/19

**Comment by Anticept** [comment]
see
https://github.com/wiremod/wire/pull/1224
https://github.com/wiremod/advduplicator/issues/74
https://github.com/wiremod/advdupe2/pull/102

**Comment by Divran** [comment]
Any reason we're using the reddit wiki over the github wiki? The github wiki can be edited by anyone via pull requests.

**Comment by Anticept** [comment]
That sounds even better. Forgot github has a wiki.

**Comment by Anticept** [comment]
Wire, AdvDupe, and AdvDupe2 pushed or updated to workshop!
