### ISSUE TITLE
nil value in digital screen memory causes script error

### ISSUE THREAD

**Issue by Darwood37** [wiremod/wire#1226]
constantly getting this error: 

22:17:09 [Error] Lua Error: [Wiremod] lua/entities/gmod_wire_digitalscreen/init.lua:80: attempt to perform arithmetic on local 'number' (a nil value)
1. numberToString - [lua/entities/gmod_wire_digitalscreen/init.lua:80](https://github.com/wiremod/wire/blob/98ae4f1eb66fd91a60c06358103b6c9e43258a63/lua/entities/gmod_wire_digitalscreen/init.lua#L80)
2. buildData - [lua/entities/gmod_wire_digitalscreen/init.lua:120](https://github.com/wiremod/wire/blob/98ae4f1eb66fd91a60c06358103b6c9e43258a63/lua/entities/gmod_wire_digitalscreen/init.lua#L120)
3. FlushCache - [lua/entities/gmod_wire_digitalscreen/init.lua:143](https://github.com/wiremod/wire/blob/98ae4f1eb66fd91a60c06358103b6c9e43258a63/lua/entities/gmod_wire_digitalscreen/init.lua#L143)
4. Retransmit - [lua/entities/gmod_wire_digitalscreen/init.lua:166](https://github.com/wiremod/wire/blob/98ae4f1eb66fd91a60c06358103b6c9e43258a63/lua/entities/gmod_wire_digitalscreen/init.lua#L166)
5. func - lua/wire/wireshared.lua:448
6. unknown - lua/includes/extensions/net.lua:32

**Comment by TomyLobo** [comment]
So there's a nil in your memory...

Can you share the code you're using to operate that screen?

**Comment by Anticept** [comment]
Can we catch these exceptions and make them more descriptive in the contest of the wire device?

**Comment by Darwood37** [comment]
I am currently trying to pinpoint exactly what i am doing when this error happens, atm it seems random. I also want to add that i am using the Steam workshop download. When i get more information for you i will reply. Thanks for getting back to me so quickly.

**Comment by TomyLobo** [comment]
are you using any other addons?

**Comment by Darwood37** [comment]
I am using a lot of addons, are there any known issues with any in particular?

**Comment by oldmud0** [comment]
All of them. Show us the full complete list.

**Comment by CaptainPRICE** [comment]
> All of them. Show us the full complete list.

You don't have to do this, it is useless action, really.
Instead be smart:

> i am using the Steam workshop download

Ok, first extract wiremod addon (from gma file), you can do that simply by creating a shortcut in `addons` folder of `gmad` executable which you can find in `bin` folder (up the hierarchy tree; it is in `common/GarrysMod/bin` folder). Once you have a shortcut of `gmad` in `addons` folder, simply left click and drag-and-drop wiremod gma file on gmad shortcut. This will create a new folder (in addons folder) with all of the wiremod addon files in it. Inside that folder, go to `lua/entities/gmod_wire_digitalscreen` folder, and then open `init.lua` file in your favorite text editor.
Scroll to line 77, or search for this: `local function numberToString(t, number, bytes)`. You should end up at something like this:
```
local function numberToString(t, number, bytes)
	local str = {}
	for j=1,bytes do
		str[#str+1] = string.char(number % 256)
		number = math.floor(number / 256)
    end
	t[#t+1] = table.concat(str)
end
```

Insert `debug.Trace()` after `local function numberToString(t, number, bytes)`, so the body of the function should look like this:
```
local function numberToString(t, number, bytes)
	debug.Trace()
	local str = {}
	for j=1,bytes do
		str[#str+1] = string.char(number % 256)
		number = math.floor(number / 256)
    end
	t[#t+1] = table.concat(str)
end
```

That's it. Save the file, and (re)start your server. Try to run into the script error again.
Once you do, post console output here as it will contain useful information (full stack trace to the function call). Then we will (probably) easily tell where `nil` have come from...

**Comment by Divran** [comment]
@CaptainPRICE that won't do shit because the function you told him to put the trace in is the same function that he already has a trace from, due to the error. It's also not the function that causes the error, because the error is caused by a number being deleted for some reason. This trace doesn't tell us when or where that number was deleted.

**Comment by Darwood37** [comment]
Any other suggestions.

**Comment by AbigailBuccaneer** [comment]
Try with just Wiremod and no other addons. If the error disappears, then it's an interaction between Wiremod and some other addon that's causing the issue (and in these cases it's usually not Wiremod that's at fault).

**Comment by CaptainPRICE** [comment]
Very interesting! I have just run into the same error:
```
[ERROR] addons/wire/lua/entities/gmod_wire_digitalscreen/init.lua:80: attempt to perform arithmetic on local 'number' (a nil value)
  1. numberToString - addons/wire/lua/entities/gmod_wire_digitalscreen/init.lua:80
   2. buildData - addons/wire/lua/entities/gmod_wire_digitalscreen/init.lua:122
    3. FlushCache - addons/wire/lua/entities/gmod_wire_digitalscreen/init.lua:143
     4. unknown - addons/wire/lua/entities/gmod_wire_digitalscreen/init.lua:255
```

For me, it only happens when I **hold down spawn menu key** (which by default is Q).
I have only one digital screen spawned (and E2 attached to it), and it has **resolution 100×100**, it is also worth mentioning that it is updating the entire memory **every 100ms**.
There is something wrong with that function, you know, like race issues with multi-threading (or something along those lines, that's the only thing I can think of right now). I can invite someone on my server to help debug it (if interested) as I am now able to reproduce it every time. Oh, you will also get to see my actual desktop on digital screen.. hah.

**Comment by Darwood37** [comment]
I have noticed I can cause the error when using the escape menu as well. Sorry not had much time to really diagnose when it happens.

**Comment by thegrb93** [comment]
Need steps to trigger the error or it can't be fixed
