### ISSUE TITLE
Preparing for "GMod 14" (October update)

### ISSUE THREAD

**Issue by oldmud0** [wiremod/wire#1228]
Full list of changes: ~~http://wiki.garrysmod.com/changelist/prerelease/~~ http://www.garrysmod.com/updates/

I don't think the update will break anything for Wiremod, but can somebody go and test everything beforehand on the prerelease branch?

**Comment by bigdogmat** [comment]
It plays fine, also Gmod 14 will never be a thing

**Comment by TomyLobo** [comment]
Garry will release it just to spite you

**Comment by CaptainPRICE** [comment]
#1214...

**Comment by shadowscion** [comment]
I've only played for a short amount of time since the update, but I did notice that the collapsible file browser in the e2 editor can't be collapsed anymore.

**Comment by oldmud0** [comment]
Closing as the issue has aged away.
