### ISSUE TITLE
Normalize indentation of all Lua files to follow coding style

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1230]
There are still Lua files which mix both spaces and tabs...

~~[!] Note: **Document on Google's docs for Wire's coding style seems to be gone!**~~

So, how about someone fix that?

**Comment by oldmud0** [comment]
I'm working on the cleanup, including getting luacheck to pass.

**Comment by TomyLobo** [comment]
Make sure that cleanup is a process, not a one-time change.
Otherwise you will conflict with new changes that came in since you pulled.

**Comment by oldmud0** [comment]
Yes, I understand. I know how to merge against those changes if that happens, but I know it's better to do it sparingly.

**Comment by TomyLobo** [comment]
what i was saying is that you should make it a script that formats our code properly

**Comment by oldmud0** [comment]
regex is such a pain in the butt, but fine.

**Comment by CaptainPRICE** [comment]
I can do quick Regex program to do full cleanup, the problem is, merging I guess.
It would also replace all Garry's custom operators with Lua's (including C comments), etc.

**Comment by TomyLobo** [comment]
why regex? use astyle or something

**Comment by oldmud0** [comment]
Consider this:
```lua
if (!(one && two) || !(three)) then
  return;
end
```

Yes, this is an example of an if-block found in the source.
But this needs to be stripped to
```lua
if not (one and two) or not three then return end

**Comment by TomyLobo** [comment]
Well, converting gmod lua syntax to standard lua syntax is nothing a code formatter will do. I guess you can do that with a regex. Make sure you don't catch strings :)
Btw did you take a look at astyle yet?

**Comment by oldmud0** [comment]
Yes, but astyle doesn't do lua.

**Comment by AbigailBuccaneer** [comment]
The contents of the Google doc is now [on the existing code style wiki page](https://github.com/wiremod/wire/wiki/Coding-style)

**Comment by TomyLobo** [comment]
cool, thanks @AbigailBuccaneer
