### ISSUE TITLE
Editor: Prompt a user to confirm "Close tab" action

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1233]
To Wire devs:
Are you fking kidding me, this is still NOT implemented!??

---

A lot of people have lost their work because this is not present (i.e. misclicks)... Then they hope they will recover it from autosaved copy, but they don't (failclicks)...

However, I see no reason to ask to confirm if there is no code, or if it is that generic code (when new file is created from within the editor).

---

_If nobody will do this, I will, even though I don't use the editor much.._

**Comment by TomyLobo** [comment]
Hey your first meaningful issue.
More of these please and less of those:
https://github.com/wiremod/wire/issues?utf8=%E2%9C%93&q=author%3ACaptainPrice%20label%3A%22Not%20a%20bug%22%20

On the issue: I suggest a prompt where ctrl-w confirms.
Maybe put "press ctrl-w again to confirm" in the status bar or something.

**Comment by CaptainPRICE** [comment]
> Maybe put "press ctrl-w again to confirm" in the status bar or something.

I have an idea for that too, but first, all of the keyboard shortcuts will have to be present on some new frame in order to inform a user about them. Then, maybe I'll also add custom/user key-binding feature, later on...

**Comment by oldmud0** [comment]
This is like the Alt+Left debate, where the Chrome devs basically said "eliminate the backspace-to-back feature" that has been around since IE 5, and reteach people's muscle memory to use Alt+Left, which has also been around since IE 5.

The easiest solution to this is not to modify the Ctrl+W behavior, but to modify the close tab behavior so that it raises a modal dialog when it detects that a file has been modified (like a regular text editor), and make "Save" the default selection on Enter.

**Comment by TomyLobo** [comment]
yeah but don't make me reach for the mouse if i want to close something with the keyboard

**Comment by its-suun** [comment]
there should be only dialog if the file is unsaved

**Comment by CaptainPRICE** [comment]
Also, another thing worth noting is that, the current mechanism doesn't seem to automatically detect for changes from outside (i.e. possibly by external process), and prompt a user whether or not to automatically reload those file(s).
Maybe I will also implement this as a feature (with toggle option) as well... :)

**Comment by AbigailBuccaneer** [comment]
@CaptainPRICE try and keep a civil tone. If you want to yell at the developer team, you should donate enough that we can work on Wiremod full time.
