### ISSUE TITLE
Localize the whole Wire user interface to support multiple languages

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1234]
@TomyLobo So, how about my 2nd "meaningful issue"?

---

[![Wire needs YOU](https://i.imgur.com/irsRdA7.png)](http://captainprice.tk/images/wire-needs-you.png)
(_click on the image for some quick-art_ 🎨)

Wire is only available in English (menus, CPU/E2/GPU/SPU text editor, toolgun, text on HUD, etc.), and not everyone speaks/understands English.
To make Wire more popular and easier to use, We should localize it!

![garrysmod wiki](http://wiki.garrysmod.com/favicon.ico) For developers: See [language library](https://wiki.garrysmod.com/page/Category:language), it allows to add/get translations through the use of string placeholders (see examples on the wiki, there are only 2 functions in that library).

---

But, this is not a one-man job  -  To accomplish this task, **We need You**!

**Comment by AbigailBuccaneer** [comment]
This has been brought up before. `language.Add` doesn't actually let you add phrases in a specific language - does Garry's Mod support multiple interface languages, and if so, how can we use the same interface language selection for our language?

From the garrysmod repository it looks like there are multiple schemes for doing this:

https://github.com/garrynewman/garrysmod/blob/master/garrysmod/resource/language/sandbox-settings_english.txt
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/resource/localization/en/tool.properties

**Comment by oldmud0** [comment]
First, we need to round up all the strings. All of them.

**Comment by TomyLobo** [comment]
And then string them all up!

**Comment by Info-Screen** [comment]
Guys I made a fork where I implemented translation. I just need some testing before I make the Pull Request

Current Status: [![Translation status](https://weblate.info-screen.me/widgets/wiremod/-/multi-blue.svg)](https://weblate.info-screen.me/engage/wiremod/?utm_source=widget)
Translate: https://weblate.info-screen.me/engage/wiremod/
Code: https://github.com/Info-Screen/wire-translation

**Comment by CaptainPRICE** [comment]
@AbigailBuccaneer @Info-Screen 
> `language.Add` doesn't actually let you add phrases in a specific language...

Check out [localify](https://github.com/Mista-Tea/localify)!

@Mista-Tea Let me bring some attention of this for you. :)

**Comment by Mista-Tea** [comment]
Hey, that's me!

If you guys actually are interested in localizing Wiremod, Localify might be an option. There is also Nutscript's localization stuff, but there was a particular reason why I wrote my own (can't remember why).

I use Localify for my tools, like Improved Weight and (recently) Improved Stacker. Here is an example of what it looks like with a bunch of localizations: https://github.com/Mista-Tea/improved-weight/blob/master/lua/improvedweight/localization.lua

And in use within the tool: 
https://github.com/Mista-Tea/improved-weight/blob/master/lua/weapons/gmod_tool/stools/weight_improved.lua#L115-L119
https://github.com/Mista-Tea/improved-weight/blob/master/lua/weapons/gmod_tool/stools/weight_improved.lua#L593-L615

A client's ```gmod_language``` isn't accessible to the server, which means providing serverside translations was a problem. Localify uses its own cvar that mimics gmod_language but lets the server retrieve it, thus allowing translations to be made before sending phrases to clients (warning/error messages, etc). That might have been one of the things lacking in Nutscript's, I can't remember.

But yeah, let me know if it's a serious possibility and I'll gladly help where I can.

**Comment by Info-Screen** [comment]
I'm currently using the language of the game, or English as fallback language and include the resource files myself with `language.Add()`. As far as I see it currently works. I just have to clean up the code.

**Comment by Divran** [comment]
>language.Add doesn't actually let you add phrases in a specific language

I thought you'd just create a new file which runs `language.Add` for every language string in wiremod, and then you'd have one such file for every language and just `include` the one you wanted. At least I assumed that was how it worked.

**Comment by Info-Screen** [comment]
I have the resource files (wire.properties) and a lua script, which gets the language from the `gmod_language` cvar and then includes the `resource/localization/<lang/wire.properties` file be going through every line and splitting the string at the `=`
