### ISSUE TITLE
Get a hologram's size [E2]

### ISSUE THREAD

**Issue by oOLinusOo** [wiremod/wire#1237]
Is there a way to get the size of a hologram in E2 ? Example:
When i create a hologram 
`
holoCreate(1)
holoScaleUnits(1,vec(50))
`
Is there a way to get these scale values from the entity (vec(50)) ?
I want to create a chip that copies holos but when someone uses random sizes i can´t get the real size.

```
findIncludeClass("wire_hologram")
findInSphere(owner():pos(),200)
Finds=findToArray()

foreach(K,V:entity=Finds) {
holoCreate(1)
print(V:id())
holoScaleUnits(1,V:boxSize())
}
```
i tried some things like boxSize/Max/Min / aabbBox... but nothing seems to work correctly.

**Comment by Divran** [comment]
`holoScale(Index)` or `holoScaleUnits(Index)`

In the future, if you have questions, go to https://discord.gg/cqJ45CT where you'll get answers much quicker. The github is more for bug reports, not questions.
