### ISSUE TITLE
Replace e2quota timer with cvar callback

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#1238]
[`gmod_wire_expression2/init.lua`](https://github.com/wiremod/wire/blob/98ae4f1eb66fd91a60c06358103b6c9e43258a63/lua/entities/gmod_wire_expression2/init.lua#L18) contains a repeating timer named `"e2quota"` that could be implemented in terms of a call to [`cvars.AddChangeCallback`](http://wiki.garrysmod.com/page/cvars/AddChangeCallback) instead.

**Comment by CaptainPRICE** [comment]
Suggestion:
Also, make `wire_expression2_unlimited` ConVar default to 1 for single-player game (see [game.SinglePlayer](https://wiki.garrysmod.com/page/game/SinglePlayer) function).

**Comment by AbigailBuccaneer** [comment]
@CaptainPRICE please open another issue if you have a suggestion.

**Comment by immibis** [comment]
@CaptainPRICE Wouldn't that make it way too easy to accidentally freeze your game client?

**Comment by CaptainPRICE** [comment]
@immibis Freezes are fine, if done accidentally they can be fixed by turning unlimited mode off, the only difference is: a "bad" E2 will stop before when running with disabled unlimited mode.
Unlimited mode just increases the default quota ConVar values to higher values.

-----

_Sorry about the bot, it had messed up somehow here..._

**Comment by immibis** [comment]
@CaptainPRICE As far as I'm aware, if your E2 gets stuck in an infinite loop (with unlimited mode) there is no way to stop it besides completely exiting the game. Mind you, I haven't tried it in years.

**Comment by Divran** [comment]
@immibis E2's infinite mode isn't actually infinite for this reason. It just adds a lot of zeroes to the limits.
