### ISSUE TITLE
Make Editor to be fully dockable and resizable

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1243]
Check out the quick [demo](http://captainprice.tk/garrysmod/demos/dockable-gcompute).
It is very practical when working with multiple files :)

@notcake Cheers. Are you planing to add this to wire Editor?

**Comment by notcake** [comment]
GCompute is legacy code that I don't want to touch and would not recommend importing into other projects, sorry.
Also I'm not a wiremod developer.
