### ISSUE TITLE
Redirect of "wiki.wiremod.com/wiki/Expression_2" is not correct

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1244]
If you go [here](http://wiki.wiremod.com/wiki/Expression_2), it redirects to [here](https://github.com/wiremod/wire/wikiwiki/Expression_2).
Apparently, URL rewriting (or forwarding) is setup incorrectly.
This is [the page](https://github.com/wiremod/wire/wiki/Expression-2) it should redirect to.

**Comment by Anticept** [comment]
I need to know where that link is showing up.

**Comment by Divran** [comment]
>I need to know where that link is showing up.

lolwut, It's in the title of this thread. It's also linked in the first post in the form of the word "here" being a link to it

Click this -> http://wiki.wiremod.com/wiki/Expression_2

**Comment by CaptainPRICE** [comment]
It is also in E2 editor...

**Comment by oldmud0** [comment]
nope, links to https://github.com/wiremod/wire/wikiwiki/Expression_2

**Comment by CaptainPRICE** [comment]
> nope, links to https://github.com/wiremod/wire/wikiwiki/Expression_2

... yeah. What's your point?
It can not be found, because like I already said:
> Apparently, URL rewriting (or forwarding) is setup incorrectly.

**Comment by Anticept** [comment]
OH NOW I SEE. You mean the URL redirect from the website. I thought you were saying it was in E2 somewhere.

It actually isn't supposed to be redirecting like this at all, it was supposed to route all links from wiki.wiremod.com to https://github.com/wiremod/wire/wiki.

**Comment by AbigailBuccaneer** [comment]
There's no longer any redirection so this is now solved.
