### ISSUE TITLE
Gmod scripted error

### ISSUE THREAD

**Issue by ares111111** [wiremod/wire#1248]
Hello im not sure if this is a common problem but im using the WireMod and holoCreating things but when i try to duplicate and save it i get this  error-

```
[ERROR] gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator/transport.lua:25: attempt to serialize structure with cyclic reference
  1. TableToJSON - [C]:-1
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator/transport.lua:25
    3. unknown - lua/includes/modules/concommand.lua:54
```

plz help im totally lost

**Comment by CaptainPRICE** [comment]
> holoCreating things but when i try to duplicate and save it i get this error

Normally, you can't duplicate holograms.
Also, the error points at sandbox gamemode, nothing to do with wire, perhaps post issue [here](https://github.com/Facepunch/garrysmod-issues/issues).

**Comment by ares111111** [comment]
So is it not possible to duplicate the cpu that has the script for the holograms?

**Comment by bigdogmat** [comment]
> So is it not possible to duplicate the cpu that has the script for the holograms?

Guessing you mean E2 to which the answer is yes and no. E2 can't be duplicated by the default duplicator, although it can be by Advdupe1 or Advdupe2.

However, it shouldn't create this error either, I'd report it as a bug over on the gmod issues repo.

**Comment by Divran** [comment]
what? E2 can't be duplicated with the default duplicator? since when?

**Comment by bigdogmat** [comment]
Strange, I remember it not being able to. Works fine

**Comment by Nebual** [comment]
Garrydupe is pretty bad - a quick test of
```
holoCreate(1, entity():pos())
```
seems to save/paste fine, so I'm closing. Reopen if you have an example E2 that causes this.
