### ISSUE TITLE
E2 preprocessor: Add dynamic/variant return type to e2function syntax

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1250]
For example, I have a function which returns either a string or a number, what would do I specify as a return type?
<pre>
e2function <b>???</b> foo(x)
    if x == 1 then return 1 end
    return 'not 1'
end
</pre>

So, I am wondering if there is something such as dynamic/variant type.
I could use an array/table, but then users will need to write more code.

**Comment by bigdogmat** [comment]
No, there isn't. I also don't believe this is really _possible_ in a strict type environment, it'd break type safety.

**Comment by CaptainPRICE** [comment]
> No, there isn't.

There should be.

> I also don't believe this is really possible in a strict type environment

It is possible...

> it'd break type safety

Not quite, it would basically have to perform checks/validations at runtime rather than when it is compiling the code. So, if any of these checks fail during runtime, just throw an error.

**Comment by bigdogmat** [comment]
> Not quite, it would basically have to perform checks/validations at runtime rather than when it is compiling the code. So, if any of these checks fail during runtime, just throw an error.

That in my opinion beats the point of type safety.

Although, I guess if a dynamic type was created it could work out, although I imagine it'd be very similar on the user end for writing extra code to handle it.

**Comment by Divran** [comment]
Not happening.
