### ISSUE TITLE
Allow adding complete egp objects as table

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#1251]
While the current way of adding egp objects works and is simple to understand, it is cumbersome and fairly inefficent when adding complex objects.

```
EGP:egpTextLayout(Index, Text, Pos, Size)
EGP:egpFont(Index, Font, FontSize)
EGP:egpColor(Index, Color)
EGP:egpAlign(Index,1,1)
EGP:egpParent(Index, OtherIndex)
#55 ops, lots of avoidable (internal) calls
```
compared to something like
```
Object=table("type"="TextLayout", "pos"=Pos, "size"=Size, "font"=Font,
    "fontSize"=FontSize, "rgba"=Color, "alignment"=vec2(1,1), "parent"=OtherIndex)
EGP:egpAddObject(Index, Object)
```
(using different keys such as rgb/rgba to handle functions with multiple possible parameter choices, incase it should be neccessary at all)

If no type is set, it would merge the new data with the existing object, instead of overwriting it as a whole.

Other functions that would make sense in this context:
```
Object=EGP:egpGetObject(Index)

#Multiple Objects
EGP:egpAddObjects(table(Index1=Object1, Index2=Object2))

Objects=EGP:egpGetObjects(array(Index1,Index2))
AllObjects=EGP:egpGetObjects()
```

The function to add multiple objects would make sense as EGPs don't usually contain just a few objects, but dozends, with most of them created in bulk.  
It would also add a more general way to do batch operations compared to #967.

Reading back objects would be nice too, while only useful for a few purposes such as serialisation, it should be comparatively easy to just output a copy of the internal table.

**Comment by Divran** [comment]
just saying, you can easily do this yourself inside E2 using user defined functions and callable strings

**Comment by adosikas** [comment]
I did, but the ops went through the roof, since creating each object this way would cost over 100 ops (2*20 ops for just the function calls + whatever internal logic needs to be done inside them+ 55 ops for egp functions as seen above).  
And creating hundreds of objects isn't exactly a rarity.

And while the ops cost is "fair" when doing all these operations individually, when done in bulk lots of overhead (both cpu time and ops) could be reduced.

**Comment by Divran** [comment]
It's definitely possible to add this feature to E2 itself, but first why don't I take a look at your code and see if I can optimize it so that it doesn't use so much ops.

Also, make sure you're making good use of EGPs frame feature, so you only ever need to create the objects once per server session.

**Comment by adosikas** [comment]
If you want to have a shot at it, [here](https://gist.github.com/adosikas/064f28ad5cd6b99f819f7f9beba7fe11) is a part of a library i started.  
When i went to test it on larger scale with lots of objects it reached it limits (mostly due to drawing being recursive and such stacking the 20 ops udf call penalty), so when i went to test alternative methods.  
Then i came to the result that optimizing my code wouldn't effect much when the egp functions would use a large part of the ops anyway.

**Comment by CaptainPRICE** [comment]
"_Object_"? +1, I like where this is going.
This would really help with complex EGP work. But, consider:

- "type" and "alignment" (and probably "font", too) should have their constants (this would save a lot, since it should be using numbers internally for indexing of their table in Lua instead of allocating strings/vector2s on the heap every time!), for example:

        ```
        -- Lua:
        -- Alignment constants:
        local Alignments = { TopLeft = { 0, 0 }, TopMiddle = { 0.5, 0 }, TopRight = { 1, 0 }, ... } -- Create that 9 vectors once and for all. Not sure what the values of the alignments actually are.
        -- Register them as E2 constants...
        -- Font constants:
        local SupportedFonts = { Tahoma = "Tahoma", Default = "Default", ... }
        for fontId, fontName in next, SupportedFonts do E2Lib.registerConstant('FONT_' .. fontName:upper(), fontId) end -- Not sure if it is all in this order, but you get the idea. fontId will be a number. Probably there should be 2 tables for this, another one being number indexed..
        -- ....
        -- In e2function, make sure to check if the value of "font" is a number (constant) or a string (user defined), if it is a number, then validate it by indexing SupportedFonts (or use table.HasValue), but if it is a string, then just use that. Perhaps also lowercase all keys for e2function which takes a table argument? So, that way if would have typed "Font", it would still work just as fine as "font".
        -- E2:
        EGP:egpAddObject(1, table("alignment" = _ALIGNMENT_TOP_MIDDLE, "font" = _FONT_TAHOMA, other params...)) # That should actually be faster than creating an alignment vector or using "Tahoma" every time, but there's a bit extra typing. I would damn type a few more characters if it would help the performance.
        ```

- Adding an overloaded function which takes all of the parameters (so it could save the time of table creation), for example (E2):

        ```
        # Index, Type, Pos, Size, Font, FontSize, Color, Alignment, ParentIndex
        EGP:egpAddObject(2, _TYPE_, vec2(X, Y), vec2(Width, Height), _FONT_TAHOMA, 12, vec(255), _ALIGNMENT_TOP_LEFT, 1) # No table creation. Can it be faster? Speeed it up, moooore!
        ```

**Comment by Divran** [comment]
>The batch insert feature would allow to edit/fill in templates on the fly before sending it to the egp (instead of using egp functions after the fact), insert only what you need instead of replacing the whole screen, as well as allowing easy serialization, making them superior to frames in almost any case, except having to validate the input before adding to the egp (since frames cannot be changed there is no need for that, but tables could be changed).

No, this feature would not compete with frames at all. They are two completely different things. Frames save all their data on the client, which means that to load a frame, you only need to send the name of the frame to the client, which is a very, very small amount of data. Then all the data is loaded instantly when the frame name arrives.

This feature of using tables would behave in the exact same way as creating objects currently works. It would only be a different syntax for literally the same behavior.

**Comment by adosikas** [comment]
I was going for a highly hierarcial menu design (think of HTML or Java JFrame) with dynamic popups, overlays, and draggable objects. It was a ops problem due to the recursion adding lots of overhead to the drawing, but thats not the point i was trying to make. 
My main point was that it is inefficent, in both ops and lua to first create a object and then change each setting individually after the fact, when one could have a objects complete as a table and load it on the egp in one step.

And the reason i chose tables over spamming functions and overloading is that is works without being intrusive - if you want to do it normally you can just ignore the 4 functions and being flexing in allowing to both create and update using the same function, and only specifying what is needed.

I wasn't aware that frames were clientside, but my other points still stand: 
They are limited since they cannot selectivly change the screen, only save static snapshots and later load them.  
After loading they would have to be updated with new information, unneeded objects removed and others added back. That works if you don't have to change much, but if you do they are not very useful.

With tables one could easily make a "template" system to fit whatever usage.  
Here is a quick example on what i mean, PlayerObjects has 3 objects, a background box, colored team name and player name, correctly setup with local coordinates, fonts, etc. And templates for header and footer are static.

```
local Objects=HeaderObjects:clone()
foreach(N,P:entity=players()){
  local PlayerObjects=PlayerTemplate:clone()
  for(I=1,3){PlayerObjects[I,table]["pos",vector2]=PlayerObjects[I,table]["pos",vector2]+vec2(0,50+20*N)}
  PlayerObjects[2,table]["rgb",vector]=teamColor(P:team())
  PlayerObjects[2,table]["text",string]=teamName(P:team())
  PlayerObjects[3,table]["text",string]=P:name()
  Objects=Objects:add(PlayerObjects)
}
EGP:egpAddObjects(Objects:add(FooterObjects))
```

If i wanted to do the same thing with current functions i would have to do everything after the other, create objects, set color, set fonts, set size, set alignment in addition to the dynamic parts.  
Or if i used frames, create a dummy with maximum number of entries every time in advance, then load that, and then make every entry i don't need invisible and update the information, all in individual egp calls.

**Comment by Divran** [comment]
>I wasn't aware that frames were clientside, but my other points still stand: 
They are limited since they cannot selectivly change the screen, only save static snapshots and later load them, as a whole, overwriting everything. 
After loading they would have to be updated with new information, unneeded objects removed and others added back. That works if you don't have to change much, but if you do they are not very useful.
With tables one could easily make a "template" system to fit whatever usage.

A point still stands, not sure if it's the one you mean. It is correct that after loading a frame you need to add additional egp objects on top of it, but just to be clear, having a function with table arguments like we are discussing would not replace frames in any way. You should still use frames to load any elements that will always appear on that specific page (static elements) (assuming the background consists of more than a single box), and then use the suggested table arg functions to load additional elements on top of that.

>Or if i used frames, create a dummy with maximum number of entries every time in advance, then load that, and then make every entry i don't need invisible and update the information, all in individual egp calls.

nah, you'd create a frame with the background elements in place, and leave the entry list area empty, and then load the list after the frame. 


EGP screens are pretty small, so you can't fit very many list elements on a screen at one time before they become too small to see. It's definitely a small enough number for E2 to handle.

I can't say I'm against adding this table arg function, though. While it does seem to be useful, I think you may have given up on optimizing your code a bit early

**Comment by adosikas** [comment]
I was not talking about replace frames, or any other functions for that sake. Infact such a template system would work best *with* frames, since you could do the "adding things after loading and editiing elements" with a single filled in "template" as well. 
And you have to create the frames in the first place, which are static by nature so a great place to use a single table to insert everything for the frame at once and save it (or have a "save table as frame" function even, but that might be going to far).

Although at one point it doesn't make much of a difference if 5 "simple" backgrounds objects are loaded from a frame or not, when you have 100+ elements with material or text being sent to the client.  

And Yes, Egp screens are small, Emitters however are a bit more flexible. Also they can display pngs, like the [full library of silkicons](http://www.famfamfam.com/lab/icons/silk/previews/index_abc.png), which are great to make stuff like file browsers and you can fit enough of 16x16 icons to fill the egp object cap.

And i got it working, ops were not a deciding factor for this request, it was more of a "hey this works, but is harder than it could be, why not find a way to make it better overall"-type idea.
