### ISSUE TITLE
findClipTo/FromPlayerProps missing

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#1252]
It makes it really annoying to find stuff owned by a specific player in a single query, such as "find all e2 and egp emitters by owner", one has to add all other players to the blacklist, i could not find other ways that work.

            findIncludeClass("gmod_wire_egp_emitter")
            findIncludeClass("gmod_wire_expression2")
            foreach(N,P:entity=players()){
                if(P!=owner()){findExcludePlayerProps(P)}
            }
            findInSphere(vec(),100000)

`findByOwner(Entity)` and `findAllEntities()` would be nice to have as well.

**Comment by CaptainPRICE** [comment]
Indeed `getAllEntities()`, not `findAllEntities()`. You don't find all, you get all.
Side note: findInBox/findInSphere and such functions has a limit of 512/1024 entities (by engine). So, you don't get them "all", if there's too many of them.
[This](https://gist.github.com/CaptainPRICE/da190e6b78c0863ce133b55ce08cf670/raw), I will implement later a bit :)

**Comment by Divran** [comment]
`findAllEntities()` would be pretty pointless for E2 since there's going to be thousands of entities on the map at pretty much all times (even when there's not a single prop on the map, there's still hundreds of entities). E2s aren't powerful enough to loop through that entire table in a single tick, so you'd need to spread it out over multiple ticks, which is, relatively speaking, a lot of work. It's much easier to filter down the results in Lua.

**Comment by adosikas** [comment]
`findAllEntities` would be useful together with the find white/blacklist and filtering, so the e2 would only get what it needs. It would be the equivalent of findInSphere(vec(),100000), without the limits. 
And what is bad about giving the e2 all the entities? If the player explicitly requests it he probably understands the consequences. 
You wouldn't don't block while(1) just because it might cause tick qouta if the player is unaware.

Anyway the find quota is a good change, was not aware of that.  
But it only works if you have just a few things you are looking for. If you want more the number of finds scales with it. With a working clipTo/FromPlayerProps one could have lua do the filtering (which ironically you suggested in response to the findAll).

However the root problem here is that the whitelist is OR, findIn/findBy adds a AND, and you can add further ANDs with ClipTo/From. And the PlayerProps filter is only availible in the whitelist, and as such cannot be added as AND. findByOwner would add one way to AND, with ClipTo/FromPlayerProps the other. Currently there is no way (apart from inverse blacklist).

**Comment by Divran** [comment]
>findAllEntities would be useful together with the find white/blacklist and filtering, so the e2 would only get what it needs. And what is bad about giving the e2 all the entities? If the player explicitly requests it he probably understands the consequences. 

I meant it would not be useful because of the sheer number of entities. Like you said, it would only be useful if you filtered it down first.
