### ISSUE TITLE
Editor does not list files/folders when name begins with a dot (.)

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1255]
This is a feature and bug at the same time. 😆

**Comment by oldmud0** [comment]
It's a fug.

**Comment by CaptainPRICE** [comment]
Closin' this one too.
If anybody is going to fix that pattern, please add an option to preserve the current behavior, it is a handy feature (I use it to "hide" non-E2 codes, and to stop certain files from showing in the file browser such as `.gitignore`).
