### ISSUE TITLE
WireLib.CalcElasticConsts doesn't check if Ent1 and Ent2 are valid

### ISSUE THREAD

**Issue by Mista-Tea** [wiremod/wire#1258]
Sorry if this is posted somewhere already, I couldn't find anything related.
```
Wire error (Entity [379][gmod_wire_hydraulic]):
lua/wire/server/wirelib.lua:1220: Tried to use a NULL entity!
stack traceback:
        [C]: in function 'GetPhysicsObject'
        lua/wire/server/wirelib.lua:1220: in function 'CalcElasticConsts'
        lua/entities/gmod_wire_hydraulic.lua:107: in function <lua/entities/gmod_wire_hydraulic.lua:97>
        [C]: in function 'xpcall'
        lua/wire/server/wirelib.lua:62: in function 'TriggerInput'
        lua/wire/server/wirelib.lua:567: in function 'Wire_Unlink'
        lua/wire/server/wirelib.lua:715: in function 'Link_Clear'
        lua/wire/server/wirelib.lua:405: in function 'ClearPorts'
        lua/wire/server/wirelib.lua:429: in function 'Remove'
        lua/entities/base_wire_entity.lua:356: in function <lua/entities/base_wire_entity.lua:355>
```
[Line 1220](https://github.com/wiremod/wire/blob/32126fec78b10cb4769c0a58a6c877201847409c/lua/wire/server/wirelib.lua#L1220) of wirelib:
```if not IsValid(Ent1:GetPhysicsObject()) or not IsValid(Ent2:GetPhysicsObject()) then return 100, 20 end```

[Line 107](https://github.com/wiremod/wire/blob/fdcecff8e3282e25728c2e8aa6feb8eef80c0457/lua/entities/gmod_wire_hydraulic.lua#L107) of hydraulic:
```self.current_constant, _ = WireLib.CalcElasticConsts(self.constraint.Ent1, self.constraint.Ent2)```

Either ```self.constraint.Ent1``` or ```self.constraint.Ent2``` are ```NULL``` when being passed to WireLib.CalcElasticConsts. Since WireLib.CalcElasticConsts doesn't check if the entities themselves are valid before trying to access their physics objects, the error occurs.

You can't just add an IsValid() check on Ent1 and Ent2 at the beginning either, because the world entity returns ```false``` in :IsValid().

I tried to write a clean and readable example (untested) of what you might be able to do:

```lua
 WireLib.CalcElasticConsts(Ent1, Ent2)
	-- return default values for nil or non-entities
	if not (IsEntity(Ent1) and IsEntity(Ent2)) then return 100, 20 end
	
	-- guaranteed to have an entity now
	local massEnt1 = (Ent1:IsWorld() and 99999) or (Ent1:IsValid() and IsValid(Ent1:GetPhysicsObject()) and Ent1:GetPhysicsObject():GetMass())
	local massEnt2 = (Ent2:IsWorld() and 99999) or (Ent2:IsValid() and IsValid(Ent2:GetPhysicsObject()) and Ent2:GetPhysicsObject():GetMass())
	
	-- one or both of the entities was either not the world, or didn't have a valid physics object
	if not (massEnt1 and massEnt2) then return 100, 20 end
	
	local minMass = math.min(massEnt1,massEnt2)
	local const = minMass * 100
	local damp = minMass * 20

	return const, damp
end
```

This ensures both Ent1 and Ent2 are entities before trying anything on them.
After that, we're guaranteed to have entities, and even if Ent1 or Ent2 aren't valid we can still safely run :IsWorld() on them without an error.
If neither are the world, it then checks if the entity AND its physics object are valid before trying to get its mass.
If either of the masses are false (was not the world, or wasn't a valid obj/phys obj), then the default is returned. Otherwise, continue on.

**Comment by CaptainPRICE** [comment]
Some quick code tips:
Use `isentity` instead of `IsEntity`.
Use `IsValid` instead of `Entity.IsValid`.
Localize `math.min` function (or even better: simply write it out: `local minMass = massEnt1 < massEnt2 and massEnt1 or massEnt2`).
Return values directly instead of storing them into variables, `const` and `damp`.
Move numbers `100` and `20` (and possibly `99999`) to constant literals.

**Comment by Mista-Tea** [comment]
```Use IsValid instead of Entity.IsValid.```
IsValid checks if the passed value has an .IsValid function before calling it. That is unnecessary if you already know the parameter is going to be an entity, which is what the IsEntity checks are for.

The other comments (other than isentity) go against what Wiremod is already doing nearly everywhere else, including the original WireLib.CalcElasticConsts function.

**Comment by bigdogmat** [comment]
> Use IsValid instead of Entity.IsValid.
`isentity` already checks this, there's no point

> Localize math.min function (or even better: simply write it out: local minMass = massEnt1 < massEnt2 and massEnt1 or massEnt2).
Using `math.min` is many times faster than that conditional in LuaJIT because of
