### ISSUE TITLE
Error when attempting to set the color of an entity with the type 'bodyque'

### ISSUE THREAD

**Issue by CSGKCJDBCPQ2K8** [wiremod/wire#1264]
When trying to change anything to do with the visibility of a bodyque i get this error:
`Expression 2 (Test): lua/entities/gmod_wire_expression2/core/e2lib.lua:707: attempted to call method 'CPPIGetFriends' (a nil value)`
So far this happens when i try use setAlpha, setMaterial or setColor. I wasn't sure about submitting due to that it could be a problem with CPPI but Abigail suggested i did.

EDIT: also affects parentTo and if you try do propSpawn(BodyQueEntity,1) then you get this`Expression 2 (Test): entities/gmod_wire_expression2/core/custom/prop.lua:53: bad argument #1 to 'IsValidModel' (string expected, got nil)`

**Comment by sammyt291** [comment]
Would you be able to post an e2 example of what you were setting where and when?

**Comment by bigdogmat** [comment]
You might want to try updating wiremod, as your line numbers compared to the errored functions do not match.

**Comment by CSGKCJDBCPQ2K8** [comment]
Sorry for the late reply, so ive checked ive got the latest workshop version. The colour issue doesnt seem to happen anymore but the prop one still does, ill post what you need to recreate it.

if there is no bodyque then type `ent_create bodyque` into console.

Heres the E2:
`@persist I
interval(5)
E = entity(I)
if(E:type() == "bodyque"){
    print(E:type())
    E:setColor(vec(0),255)
    propSpawn(E,1)
    
}
I++`

**Comment by TomyLobo** [comment]
dafuque is a bodyque?

**Comment by oldmud0** [comment]
body-¿que?

**Comment by CaptainPRICE** [comment]
> dafuque is a bodyque?

It is on Valve docs as Portal 2 entity, [here](https://developer.valvesoftware.com/wiki/List_of_Portal_2_Entities).

**Comment by CSGKCJDBCPQ2K8** [comment]
Doesnt seem to be much info on what it is, i saw some talk about it on a quake forum (maybe something from goldsource originally?) but it does seem to be in servers that dont have portal 2 mounted.

**Comment by AbigailBuccaneer** [comment]
This also works with `base_brush`. It seems that some entities return `nil` as a model.

**Comment by thegrb93** [comment]
I think gmod fixed this at some point. Say so if not
