### ISSUE TITLE
Keypad calls GetNetworkedInt instead of GetNWString

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1265]
See [this](https://github.com/wiremod/wire/blob/637ba50d6762a2a1e7db57744778f09f5b1c4585/lua/entities/gmod_wire_keypad.lua#L106).
Fix please; I guess this is right:
```
local Display = self:SetNWString("keypad_display", "")
```

**Comment by its-suun** [comment]
Why not fix yourself?

**Comment by CaptainPRICE** [comment]
> Why not fix yourself?

Because I am busy. Also, yet another issue is coming up in a moment..

**Comment by Jelman21** [comment]
> Because I am busy. Also, yet another issue is coming up in a moment..

Busy like every other wiremod dev who are doing this as a hobby and not a fulltime paid job.
