### ISSUE TITLE
EGP font Marlett-

### ISSUE THREAD

**Issue by klapek11970** [wiremod/wire#1267]
Hello cant get to work Marlett font in EGP,any tips how to use those fonts?

**Comment by Divran** [comment]
It's possible that font no longer works. Or maybe your computer doesn't have the font (not sure if all fonts are included in gmod/source). The fonts that EGP has were the fonts that worked years ago, back when they were enabled for egp.

**Comment by AbigailBuccaneer** [comment]
Marlett is a font used for rendering window button icons and other UI widgets. The available characters seem to be: `0123456789abcdefghijklmnopqrstuvxy`. It works fine for me on Ubuntu. If those characters don't work for you, you'll have to be more specific about the symptoms.

![image](https://cloud.githubusercontent.com/assets/908758/20545275/38e2bc56-b106-11e6-9e25-ee696645ba4e.png)

**Comment by klapek11970** [comment]
tested at mp and sp , switched from workshop to github version and still not working
![20161126155045_1](https://cloud.githubusercontent.com/assets/12882557/20641079/39cdc768-b3f0-11e6-8d3d-657e545060ad.jpg)
