### ISSUE TITLE
Create a series of 'testcase dupes'

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#1271]
Testing your code to make sure you haven't broken anything would be a lot easier if we had a set of dupes which test lots of functionality of different entities.

**Comment by CaptainPRICE** [comment]
aka unit tests for wire? I like. 👍
Someone post an automatic GLua script to spawn all wire components/gates, and link everything up and validating all outputs test-by-test.. Then others would just need to add more tests, get me?

**Comment by oldmud0** [comment]
hmm, hook up Travis CI to SteamCMD, download GMod, run a lua script on game start, spawn a bunch of dupes, and verify good output?

**Comment by AbigailBuccaneer** [comment]
I don't think Travis would enjoy that (it has fairly tight time and resource limits), but it's something I'd love to see happening in the future. Maybe if Wiremod went back to having (semi-)official build servers, we could use their infrastructure for the good of Wiremod?

Either way, this would still be a productivity boost without continuous integration.
