### ISSUE TITLE
Using exit() inside switch statement breaks foreach

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#1275]
```
if(first()){
    switch(1){
        default,
            timer("test",1)
            exit()
    }
}
if(clk("test")){
    foreach(N,K:number=array(1,2)){print(K+1)}
}
```

For whatever reason using exit inside a switch statement causes foreach in all following E2 executions to have nil as Key and Value, which causes a variety of errors depending on what those are used in.

Tested with 4acbfe2d95b9b9f27d83be26091c3136136f639d

**Comment by TomyLobo** [comment]
huh? i cant even begin to imagine how effed up the implementation of switch/foreach must be to even make that possible

**Comment by adosikas** [comment]
From a look at the code it looks like exit and break both use error() to leave the current block and switch doesn't popScope incase a unexpected error comes along [Link](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/core.lua#L523), while other functions do, like other environments. Examples: [for](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/core.lua#L102) [foreach](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/core.lua#L145).

So using exit() (or causing any other error) would mess up the scope stack. This is not a issue for other errors, as they kill the E2 anyway.

**Comment by TomyLobo** [comment]
well i guess one of the scopes is empty or missing, so it cannot write the local vars.
