### ISSUE TITLE
Editor does not update in singleplayer

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1285]
## Steps for reproducing issue
1. Start a new singleplayer game.
2. Open Wire Text Editor (e.g. right-click with Expression 2 tool).
3. Press `Esc` (Escape) key.
4. Click `Update` button in lower-left corner.

File structure/tree does not update, example list of folders:
```
expression2
expression2\level1
expression2\level1\level2
```

Folder `level1` shows up, but any children (level 2) does not.
Do not panic, your files are there (unless you have deleted the folder).
Press `Esc` (Escape) key, and then click `Update` again and then it'll work again.

**Comment by CaptainPRICE** [comment]
@TomyLobo What's downvote for?
... This bug is still relevant and is not fixed.

**Comment by bigdogmat** [comment]
This is caused by the fact the `DTree_Node` uses a timer to populate the list. There's no easy way to fix this on Wiremods end.
