### ISSUE TITLE
Editor: Automatically insert closing parentheses/bracket/brace/quotes

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1286]
I think most of us find this feature somewhat helpful, it can be found in popular text editors today.
For example:
Once you type `(`, it would insert its closing pair `)`, and set the caret position after the beginning `(`.
Here are they in pair:

| Open | Close |
|:----:|:-----:|
|   **(**  |   **)**   |
|   **[**  |   **]**   |
|   **{**  |   **}**   |
|   **"**  |   **"**   |

- [ ] Implement it in Wire Text Editor
- [ ] Allow user to turn it on/off in options (I suggest to enable it by default)

**Comment by oldmud0** [comment]
Implementation is hard to do correctly, and lazy implementations are annoying as heck (like in Notepad++). For example, you can automatically insert opening/closing braces in many editors, but there is no way to automatically delete matching braces in any editor except Vim and maybe Sublime.

I'm not sure anyone is inclined to do this; if any advances editor features are needed, we just run to our favorite text editor.

**Comment by shadowscion** [comment]
Only if I can disable it, I find autocompletion annoying as hell.

**Comment by MulleDK19** [comment]
Brace auto completion is the devil's work. It's an absolute garbage feature.

**Comment by Divran** [comment]
yeah nah

**Comment by TomyLobo** [comment]
I 100% agree with @Divran
