### ISSUE TITLE
camcontroller error

### ISSUE THREAD

**Issue by PeltGun** [wiremod/wire#1290]
[Wiremod] lua/entities/gmod_wire_cameracontroller.lua:327: bad argument #1 to 'WriteFloat' (number expected, got function)
  1. WriteFloat - [C]:-1
   2. SendPositions - lua/entities/gmod_wire_cameracontroller.lua:327
    3. SyncPositions - lua/entities/gmod_wire_cameracontroller.lua:358
     4. unknown - lua/entities/gmod_wire_cameracontroller.lua:500
what is this? 
I used the tank hud e2 chip
and It did not work, and this error appears on the console.
So I used camcontroll and again this error appears on the console.
Please let me know how to fix it.
I can not speak English very well. so i used Google translation

**Comment by Divran** [comment]
This issue has already been reported and solved. You even replied in one of the other issues, where the solution is listed.

I'll say again to be clear: **Uninstall slvbase**
