### ISSUE TITLE
The last rocker switch skin is an error?

### ISSUE THREAD

**Issue by PlNG** [wiremod/wire#1291]
According to entity inspector:
in models/bull/buttons/rocker_switch.mdl:
[1] bull/buttons/rocker_switch
[2] bull/buttons/rocker_switch_red
[3] bull/buttons/rocker_switch_blue
[4] bull/buttons/rocker_switch_green
[5] bull/buttons/rocker_switch_orange
[6] ___error

Selecting "Skin 5" ingame produces the missing texture graphic.

**Comment by thegrb93** [comment]
Where are the model sources?

**Comment by PlNG** [comment]
I'm not sure that I fully understand the question?
I've downloaded the game and am loading up addons and getting back on meta construct #1.

**Comment by PlNG** [comment]
Button input output?

**Comment by thegrb93** [comment]
No, the files used to compile the model

**Comment by CaptainPRICE** [comment]
Hm, perhaps [here](https://github.com/wiremod/wire/tree/master/materials/bull/buttons) ?

**Comment by thegrb93** [comment]
No, has to be decompiled

**Comment by CaptainPRICE** [comment]
Could try out [Crowbar](https://steamcommunity.com/groups/CrowbarTool) (or [Hooch's decompiler](https://gamebanana.com/tools/5083)), I can't be bothered going over decompiling atm :/

**Comment by thegrb93** [comment]
Yeah, I know how to decompile. I've just been busy with my own modelling project

**Comment by thegrb93** [comment]
Looked in the mdl file and the missing material is rocker_switch_dark. I can just change the number of skins to 5 instead of 6.
