### ISSUE TITLE
Cam Controller Not working

### ISSUE THREAD

**Issue by Tyler13700** [wiremod/wire#1294]
I have tried downloading wiremod via SVN, ive downloaded wire extras via svn, And no luck on making camera controllers work. If you want the exact error it spams me about 10 times a second, here it is:

```
[Wiremod] lua/entities/gmod_wire_cameracontroller.lua:482: bad argument #2 to '__mul' (number expected, got function)
  1. __mul - [C]:-1
   2. UpdateOutputs - lua/entities/gmod_wire_cameracontroller.lua:482
    3. unknown - lua/entities/gmod_wire_cameracontroller.lua:573
```

And upon leaving while in a cam controller linked seat, I get this message:

```
[Wiremod] lua/entities/gmod_wire_cameracontroller.lua:385: bad argument #1 to 'WriteFloat' (number expected, got function)
  1. WriteFloat - [C]:-1
   2. SendPositions - lua/entities/gmod_wire_cameracontroller.lua:385
    3. SyncSettings - lua/entities/gmod_wire_cameracontroller.lua:407
     4. DisableCam - lua/entities/gmod_wire_cameracontroller.lua:616
      5. ClearEntities - lua/entities/gmod_wire_cameracontroller.lua:846
       6. unknown - lua/entities/gmod_wire_cameracontroller.lua:601

Wire error (Entity [84][gmod_wire_cameracontroller]):
lua/entities/gmod_wire_cameracontroller.lua:385: bad argument #1 to 'WriteFloat' (number expected, got function)
stack traceback:
	[C]: in function 'WriteFloat'
	lua/entities/gmod_wire_cameracontroller.lua:385: in function 'SendPositions'
	lua/entities/gmod_wire_cameracontroller.lua:407: in function 'SyncSettings'
	lua/entities/gmod_wire_cameracontroller.lua:616: in function 'DisableCam'
	lua/entities/gmod_wire_cameracontroller.lua:771: in function <lua/entities/gmod_wire_cameracontroller.lua:768>
	[C]: in function 'xpcall'
	lua/wire/server/wirelib.lua:62: in function 'TriggerInput'
	lua/wire/server/wirelib.lua:567: in function 'Wire_Unlink'
	lua/wire/server/wirelib.lua:715: in function 'Link_Clear'
	lua/wire/server/wirelib.lua:405: in function 'ClearPorts'
	lua/wire/server/wirelib.lua:441: in function 'Remove'
	lua/entities/base_wire_entity.lua:356: in function <lua/entities/base_wire_entity.lua:355>

```

**Comment by Divran** [comment]
This error gets reported to us about once a month. It's caused by having a shit addon installed that breaks every other addon that uses a variable called "Distance".

Write this in your console to find out which addon it is:
`lua_run PrintTable(debug.getinfo(Player(1):GetEyeTraceNoCursor().Entity.Distance))`
This will give you lots of information about the function that this shit addon creates, including exactly where the function is created. This will give you the file path to the addon. Once you have it, simply uninstall the addon, and also go tell the addon author to fix his bad code.

**Comment by Tyler13700** [comment]
I did it while looking at a cam controller, I got this message

`
[ERROR] lua_run:1: attempt to call method 'GetEyeTraceNoCursor' (a nil value)
  1. unknown - lua_run:1
`
Then about 10 seconds later, I got this message:

`
[TFA Base] lua/tfa/modules/tfa_backend.lua:19: attempt to perform arithmetic on a nil value
  1. XML_GetMembers - lua/tfa/modules/tfa_backend.lua:19
   2. onsuccess - lua/tfa/modules/tfa_backend.lua:51
    3. unknown - lua/includes/modules/http.lua:34
`

I'm not sure if this means TFA has something to do with it, But I'm gonna try uninstalling anything TFA in my addons.

**Comment by bigdogmat** [comment]
You probably tried to run it on a NULL entity then. Type `status` into console, see what number is in the `userid` column next to your next, plug that number into that `Player` function, e.g. `Player(2)`

**Comment by Tyler13700** [comment]
Thanks, Heres what I got...

```
> PrintTable(debug.getinfo(Player(3):GetEyeTraceNoCursor().Entity.Distance))...
currentline	=	-1
func	=	function: 0x42c19090
isvararg	=	false
lastlinedefined	=	161
linedefined	=	156
namewhat	=	
nparams	=	2
nups	=	0
short_src	=	lua/autorun/slvbase/shared/slvbase_sh_meta.lua
source	=	@lua/autorun/slvbase/shared/slvbase_sh_meta.lua
what	=	Lua

```

**Comment by Tyler13700** [comment]
I cant find anything to do with `slvbase`

**Comment by Divran** [comment]
That FTA error looks completely unrelated. I'd forgotten what the name of the offending addon was, but now that you got the correct file path, I remember that "slvbase" is the one. Just get rid of that and problem solved.

**Comment by Pharap** [comment]
In case anyone else ever runs into this problem again (as I have), one of the known offending mods is Skyrim SNPCs.
