### ISSUE TITLE
holoParentAttachment() displaces holos when used

### ISSUE THREAD

**Issue by unknao** [wiremod/wire#1295]
I have made a few e2 weapons only to find them being misplaced when i play singleplayer or on my own server, the issue doesnt occur when the holo is being setposed to the attachment position, only when parenting.

**Comment by Divran** [comment]
Pretty sure this is source engine's fault, I don't think we can fix this.

**Comment by UnKnao** [comment]
it does work on other servers tho

**Comment by Divran** [comment]
To be clear, the issue I think you mean is this: Parenting to player attachments used to work flawlessly, but then it suddenly broke. Now it'll just randomly sit like 40 units away from where it's supposed to be, and if you aim up/down it'll orbit you in an arc, etc. Is this the same issue?

If someone has any idea how to fix this, go ahead and post a pull request.

**Comment by UnKnao** [comment]
Yep thats exactly the issue im having.

**Comment by thegrb93** [comment]
Addon conflict issue most likely.
