### ISSUE TITLE
How to simulate holo's having a limited lifetime?

### ISSUE THREAD

**Issue by Tyler13700** [wiremod/wire#1296]
I have a smoke machine e2 that spawns absurd amounts of holos, (Its on an interval(50)) And I was wondering if I could make these holos disappear after X amount of seconds?

**Comment by bigdogmat** [comment]
1. This isn't a place for help, I'd suggesting using wiremod's [reddit page](https://www.reddit.com/r/wiremod) or the wiremod [discord](https://discord.gg/cqJ45CT).

2. There aren't any built in functions to do this, however that doesn't stop you from creating a system that will do it. Easiest way I can think of would be to make a timer with the id of the hologram appended to the name, then to check `clkName()` and get the holograms id out of it.

**Comment by Tyler13700** [comment]
Oh, ill make sure to use the reddit page next time, but my code is something like this:

```
@name smoke weed every day machine
@persist Smoke
@inputs Active

if (first()) {
Smoke = 1
}

interval(50)

if (Active == 1) {
holoCreate(Smoke)
(all the stuff to change its model n size blah blah blah)
Smoke++
}
```

How would I use clkName() and timers and stuff on that?

**Comment by bigdogmat** [comment]
```
# This is where your holoCreate code is
timer("DeleteHolo" + Smoke, 10 * 1000) # 10,000 milliseconds = 10 seconds

# This is somewhere else in the code
if(clkName():sub(1, 10) == "DeleteHolo")
{
    holoDelete(clkName():sub(11):toNumber())
}
```

**Comment by TomyLobo** [comment]
As mentioned, this place is for when something with wiremod is not working or you have a suggestion for improvement, not for help.
You'll get a much better answer on reddit, where the people who actually play the game are :)
