### ISSUE TITLE
Broken with player

### ISSUE THREAD

**Issue by TwistieFresh** [wiremod/wire#1301]
owner():isPLayerHolding()
owner():isFrozen()

Both of these don't work if the admin of a server does it to you. The admin of a server can pick you up with their Physics Gun and it does not work with "isPlayerHolding()", the admin of a server can also put "!freeze <playername>" into the chat, and "isFrozen()" does not work.

**Comment by bigdogmat** [comment]
`isPlayerHolding` is using the default method made for gmod, the fact it doesn't return a player if a player is holding another player would be a bug on their side.

`isFrozen` is checking if the physics object is move able, iirc players have a different type of physics and as such this probably wouldn't work.

**Comment by TomyLobo** [comment]
That's the fault of the server's plugin, not ours. Closing.
