### ISSUE TITLE
JSON is broken (at least with decoding arrays)

### ISSUE THREAD

**Issue by ghost** [wiremod/wire#1302]
Hey guys!
Problem:
`Data = table("data" = array(0,0,0,123))
DecodedData = jsonDecode(jsonEncode(Data))
print(DecodedData["data",array]:count())
printTable(DecodedData["data",array])`
=>
`0`

Checked with simple numbers and vectors, it was ok, but fails with arrays somehow (doesn't matter where they are exactly)
Encoding looks fine, only decoding.

**Comment by TomyLobo** [comment]
@Divran another case of nesting being disabled for security reasons?

**Comment by Divran** [comment]
nah it's probably a bug. I haven't had the time to look at it and I'm about to step onto a 12 hour flight so yeah, will do later

**Comment by Divran** [comment]
Alright I did some testing on the plane, and it turns out this was intended behavior. I had forgotten that I had made the JSON decode function convert all tables and arrays into tables. So this means you simply need to use `T["derp",table]` to retrieve the array, instead.

**Comment by BoggLog** [comment]
Wow, that works... alright, but would be good to atleast mention it somewhere. Not much obvious.

**Comment by UAVXP** [comment]
Also jsonDecode can't normally decode angles:

Original: 	
`Ang	=	[0,90,0]`

Encoded: 
`{"Ang":"{0 90 0}"}`

Decoded:
```
Ang:
		1	=	0
		2	=	0
		3	=	0
```

**Comment by Divran** [comment]
@UAVXP that is correct. I've been considering changing the way arrays in E2 store values internally, so when I get around to that, that might fix it, we'll see.

**Comment by Vurv78** [comment]
The Angle example by @UAVXP works for me. Pretty sure this is a side effect from `vector` and `angle` being changed to store userdata, and gmod has special cases for json with angles and vectors.
