### ISSUE TITLE
Make limits more adequate for indexing arrays/strings

### ISSUE THREAD

**Issue by ghost** [wiremod/wire#1303]
I was trying to make simple image loader, failed with json, but okay, I used string for image data, expecting `512*512` numbers as strings to be okay as it was, but suddenly found that max values I can explode to array is `128*128`, some more and I get tick quota just for that one op... seriously?
I believe limits were much greater last time I checked (were where any limits at all?) and they really should be. 
Let's vote! 
_(I'll base on exploding a string for N strings 7 chars each, because it's typical case I think)_
1. Same 128^2
2. at least 512^2
3. at least 2048^2 (me)
4. no limits (or like they were before, if any)

**Comment by Divran** [comment]
You're going to have to parse the string more slowly, over multiple ticks.

You can't expect E2 to do unlimited amounts of computationally heavy operations in a single tick, when it must leave enough time left for the game engine itself to run smoothly afterwards.

**Comment by BoggLog** [comment]
Sure, I don't expect anything unlimited. The main reason for this is consistency, because It worked with much larger strings back then (year ago for sure), and that never caused server to lag or any problems.

Do I have to always expect my E2s to be broken just for no reason then?

**Comment by bigdogmat** [comment]
> Do I have to always expect my E2s to be broken just for no reason then?

How old is your E2 specifically? I only ask because the last change to explode was done back in 2011 (9f1b9542eac70d913d62f171600fcdc1b0f6f400). I wouldn't normally expect 2010, 2011 E2s to work considering the amount of updates since then, and also the update to Gmod 13.

Unless you aren't talking about the function explode, in which case I'd like to know the code you were running.

**Comment by Nebual** [comment]
Wow, I tried benching s:explode(s) with a large string of `"b,":repeat(450^2)` which I then `LargeString:explode(",")` - it takes 10x longer than 1000 E:setPos() calls! If anything that means we should _raise_ the cost of explode hah. Lua just has crap string handling, apparently!
```
@name 
@persist E:entity P:vector S:string
if(first()) {
    E=entity()
    P=E:pos()
    #S = "b,":repeat(450^2)
    interval(1)
} else {
    for(I=0,100,1) { # unroll these setPos's to reduce the impact the for loop has on ops
        E:setPos(P)
        E:setPos(P)
        E:setPos(P)
        E:setPos(P)
        E:setPos(P)
        E:setPos(P)
        E:setPos(P)
        E:setPos(P)
        E:setPos(P)
        E:setPos(P)
    }
    #S:explode(",")
    interval(1)
} else {
    print(ops(), cpuUsage() * 1000)
}
```

**Comment by Divran** [comment]
that doesn't sound right.. try benchmarking the different versions of string.Explode that gmod has had and see which one handles `"b,":repeat(450^2)` the best?

**Comment by bigdogmat** [comment]
This is probably correct, `setPos` is rather simple compared to a high amount of string multiplication, something that Lua isn't the best at handling.

**Comment by Divran** [comment]
yeah string.explode in gmod used to use gmatch but it was replaced with string.find to improve performance even more.

The very FIRST version in gmod used to literally step through every character in the whole string
