### ISSUE TITLE
E2: @name directive ignores everything after the first "#"

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1305]
For example:
```
@name Test#Hello World
```

If you spawn above E2, and aim on it, you should see the overlay text telling you that E2 is named "Test" (which it is not).
This is clearly a bug.

However, if you use `setName(s)` function, like so:
```
setName("Test#Hello World")
```

Then you should actually see it just fine: "Test#Hello World".

**Comment by thegrb93** [comment]
Obviously comments are discarded first. C++ does the same thing. Also filenames don't support \# so using it in the name is a bad idea in general.

**Comment by Damianu** [comment]
"This is clearly a bug.". 
Just remove comment feature, noone uses it anyway.

That was a joke.

**Comment by oldmud0** [comment]
This is clearly intended behavior.

**Comment by shadowscion** [comment]
Frankly I use this as a feature all the time to prevent people from constantly commenting about what I name my scripts.

**Comment by CaptainPRICE** [comment]
Okay closin' it. I like this feature too.

**Comment by CaptainPRICE** [comment]
@thegrb93
> Also filenames don't support # so using it in the name is a bad idea in general.

I just wanted to tell you, you are very wrong. I don't know what makes you think `#` is disallowed in filenames... Bad idea or not (that's a personal preference), `#` **is allowed**:
![image](https://user-images.githubusercontent.com/9789070/27431074-6c8ec5c2-574b-11e7-9003-a68f9b4ad0b9.png)


@oldmud0
> This is clearly intended behavior.

I was talking about E2 editor syntax highlighting here... Everything after `#` in `@name` is not highlighted as a comment...
