### ISSUE TITLE
A new way to check for official distribution.

### ISSUE THREAD

**Issue by Anticept** [wiremod/wire#1308]
Since reuploading is still occurring, and technically it's allowed under our licensing, I've come up with a new idea of how we can handle it.

Using https://wiki.garrysmod.com/page/steamworks/IsSubscribed, we could check if the user is subscribed to an official source of our tools. If not, display a message: "Wiremod has an official distribution for our tools at "url". If the version you are using is not working properly, consider using the official source." It's polite but still makes a point.

In addition, if someone is using the git version, we could check for the presence of git files is possible. If not possible, then we could create a new init file that sets the var IsGitDownload, and exclude this init file in addon.json so that when the workshop build is created so that it's not included with the build.

This is easily circumvented, but could curb some of the low effort abuse, and raise awareness to the official source.

Consider the following psudocode:

```
If ((wire-official-subscribed || IsGitDownload)  == 0);
   print "Wiremod has an official distribution for our tools at <url>. If the version you are using is not working properly, consider using the official source."
return
```

**Comment by Divran** [comment]
Question is where to display this message. Could do in chat, but that might get ignored. Another place is in a popup that doesn't activate the mouse, and then we place this popup on the left or right of the screen. Then the user can use C to open the context menu or whatever to activate the mouse and close it.

**Comment by CaptainPRICE** [comment]
> Then the user can use C to open the context menu or whatever to activate the mouse and close it.

Note: Not all gamemodes implement a context menu.

**Comment by Divran** [comment]
Wiremod is only intended to work in sandbox. If someone wants to use it in a different game mode, it's their problem

**Comment by CaptainPRICE** [comment]
So... Here you go, [gist](https://gist.github.com/CaptainPRICE/d4efc816d40edc3acbae5a663187ee5a/raw). Untested.

**Comment by AbigailBuccaneer** [comment]
I can't find any reuploads on the workshop. I think regular releases stop people wanting to reupload. As for other sites, they're most likely not being updated, and so our message wouldn't reach anybody using them.
