### ISSUE TITLE
String:replace("","") always returns an empty string

### ISSUE THREAD

**Issue by CSGKCJDBCPQ2K8** [wiremod/wire#1312]
Title says it all really, heres some sample code anyway.
```
@name Rep Test
print(">"+"Hi":replace("",""))
```

**Comment by thegrb93** [comment]
Empty string matches any character. Try string.find("hello","")

**Comment by bigdogmat** [comment]
> Empty string matches any character. Try string.find("hello","")

Why is this relevant? Only reason this returns an empty string is because [here](https://github.com/wiremod/wire/blob/bb9aee73f0948de7d27807588f81e315d84d0a82/lua/entities/gmod_wire_expression2/core/string.lua#L315), we return an empty string if given an empty needle.

**Comment by CSGKCJDBCPQ2K8** [comment]
Strange that "" matches anything, do you think we could get it to just return the input as techically replacing any char with itself should't change anything.

**Comment by TomyLobo** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/string.lua#L313-L317
This is an anti-crash feature.

**Comment by bigdogmat** [comment]
@TomyLobo Do you not agree that it still should return itself and not an empty string? Also I've already said that it won't crash anymore,

> That check can be removed as it won't crash anymore. Or it could be changed to just return the string itself, would do the same as calling string.Replace except skips that step.

**Comment by dvdvideo1234** [comment]
@TomyLobo 

Can you tell what exactly can crash if this is removed, because I see only а value assign. Moreover. Just a return statement. The interpreted will not even go trough the "this:Replace( needle, new)" statement.

**Comment by TomyLobo** [comment]
@bigdogmat i was just stating a fact, not implying an opinion.
