### ISSUE TITLE
Why doesn't my CarE2 Work?

### ISSUE THREAD

**Issue by iNoPeRaTiVe** [wiremod/wire#1314]
I really have no clue why this E2 won't work. Basically, what I'm trying to do is when I press W, the wheels on the car go forward. When I press S, they need to go backwards, but they don't. Is there something I'm missing?
From here:
@name CarE2
@inputs W S
@outputs LeftWheels RightWheels

if(S == 0)
{
    LeftWheels = 0
    RightWheels = 0
}

if(S == 1)
{
    LeftWheels = -1
    RightWheels = -1
}

if(W == 1)
{
    LeftWheels = 1
    RightWheels = 1
}

if(W == 0)
{
    LeftWheels = 0
    RightWheels = 0
}
To here.

**Comment by CaptainPRICE** [comment]
Just checking, have you wired the inputs `W` and `S` to pod controller and then linked that to vehicle?
Also, use Discord, you will get much better help there.

**Comment by iNoPeRaTiVe** [comment]
Yes. Yes I have. Also, there's a discord for wiremod?

**Comment by CaptainPRICE** [comment]
Yep, there is Discord for wire, [here](https://discord.gg/cqJ45CT).
Anyways, here, take mine [gist](https://gist.github.com/CaptainPRICE/bf3d23d6d7235351fcc1333ea74946ca/raw).
So, if you have linked Pod Controller to some vehicle, wired it all up, once you enter it, press `+forward` (by default `W` key), it will set `LeftWheels`, `RightWheels` and `LeftAndRightWheels` to 1. If you stop holding forward key `W`, they will be set back to 0. If you hold down `+back` (S) and `+forward` (W) keys together, they will be set to 0, and if you only hold `+back` (S) key down, they will be set to -1.
Simple. Also, they will be always 0 as long as you don't wire things up.
Tip: Use Debugger tool to help you see values of inputs/outputs of wire gates.

@Divran How about to close this issue?

**Comment by Divran** [comment]
Here's a much better way of doing it
```
@name CarE2
@inputs W A S D
@outputs LeftWheels RightWheels

local ForwardSpeed = 1 #Change this to your liking
local TurningSpeed = 1 #Change this

LeftWheels = (W-S) * ForwardSpeed + (D-A) * TurningSpeed
RightWheels = (W-S) * ForwardSpeed + (A-D) * TurningSpeed
```

**Comment by iNoPeRaTiVe** [comment]
@Divran Thanks!
