### ISSUE TITLE
Inverting T:typeids() dumps numerical indexes

### ISSUE THREAD

**Issue by Matt1923** [wiremod/wire#1317]
Inverting T:typeids() dumps numerical indexes:
Code Example:
```
T = table(1="Test", "A"="Test2")
printTable(invert(T:typeids()))
```
Prints to chat:
```
s	=	A
```

Weirdly invert works fine on a normal table; just not typeids:
Code Example:
```
T = table(1="Test", "A"="Test2")
printTable(invert(T))
```
Prints to chat:
```
Test2	=	A
Test	=	1
```

**Comment by Divran** [comment]
What's the problem? I see nothing wrong here

**Comment by Divran** [comment]
I think i see what's confusing you. try printing the typeids of your first table without inverting it. You will see it says both are equal to "s". Since a table can't have more than one identical keys, all but one is deleted when this table is inverted.

**Comment by Matt1923** [comment]
They're not identical keys. The keys are 1 and "A"

**Comment by Divran** [comment]
No. Try printing T:typeids()

**Comment by Matt1923** [comment]
Yea sorry me and my friend got a bit confused. We assumed typeids() meant the type of the table indexes(keys) as the word id was in the function.

Maybe these names would make more sense?
```
T:keyTypes()
T:valueTypes()
```

**Comment by AbigailBuccaneer** [comment]
What would `keyTypes` tell you that you can't already tell from the key itself? Wouldn't you get a table that looks like `{ [1] = "n", ["A"] = "s" }`
