### ISSUE TITLE
E2 Protection (runstring)

### ISSUE THREAD

**Issue by splashlucas** [wiremod/wire#1329]
So something like runstring would be pretty cool like loading another e2 and running the code from it.
This could be abused so add it like concmd where you have to enable it also add it so the server could disable it.
This would make me feel a lot better that not some admin could just go up and copy my e2 that I used a long time coding.
Http request with this would be awesome :3

**Comment by adosikas** [comment]
You can already do something like that with remoteupload (`entity():remoteSetCode("@name ...")`).

And i don't think your idea (which includes *uploading the code open for anyone on the internet*) makes it harder to copy code at all, if not easier. (After all, what prevents someone downloading the code)

If you want to not get your E2 "stolen", play singleplayer only (or play on serves with trustworthy admins).

**Comment by Divran** [comment]
Like adosikas said, this is already possible with remoteUpload or remoteSetCode.

And the only way to prevent admins from stealing your code is to play single player or on servers with good admins.
