### ISSUE TITLE
E2: moneyRequest() not working with array as value.

### ISSUE THREAD

**Issue by Luka2477** [wiremod/wire#1331]
The addon for expression2 called moneyRequests, does not work if i use an array value as money amount. For example i have this array:
`WeapPrices = array(100, 200, 300, 400, 500)`
And i have this command:
`moneyRequest(owner(), WeapPrices[1, number], 30)`
The first argument is the entity/player to send the request to. The second is the amount of money to ask for, and the third is the amount of seconds. This does not give the player any request, and no error either. But if i do this instead:
`moneyRequest(owner(), 100, 30)`
Which is exactly the same output, it works. **Does anyone have an explanation for why this happens, and how i can fix it?**

**Comment by bigdogmat** [comment]
Considering this is more of a question and not a bug/request, I'd suggest using either the Wiremod Discord or Wiremod Reddit page, you can get to both [here](http://wiremod.com/).

To just give a quick answer though, the code you've provided looks fine, and should work fine as well. If I had to guess it's probably a problem somewhere else in your code.

**Comment by Luka2477** [comment]
Thanks, i have made a post on reddit now. The thing is, even if i make a new E2 and add this into 2 lines, it still doesn't work. There must be some way to work your way around it... @bigdogmat

**Comment by Divran** [comment]
Post an example E2 that isn't working

**Comment by adosikas** [comment]
This is a user error, see the [reddit post](https://www.reddit.com/r/wiremod/comments/5rovpq/e2_moneyrequest_not_working_with_array_as_value/). He defined that array only in the first run but didn't add it to persist.

@Luka2477 Good practice to reporting suspected bugs is to make a [Minimal Working Example](https://en.wikipedia.org/wiki/Minimal_Working_Example) to reproduce the bug, which will usually make user errors obvious and incase it is a actual bug helps developers to pinpoint it. Example MWE:

    @name Test
    if(first()){
      A=array(1,2,3)
      interval(15)
    }
    print(A[1,number])

Given that "not adding X variable to @persist" is a relatively common beginner error, is it not possible to throw an error/warning when a undeclared variable is encountered at runtime? I can see how it would be difficult to detect when validating.
