### ISSUE TITLE
wire teleporter

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#1337]
ok, so I have love the wire teleporter for some time now but my issue is when I parent it to ANYTHING it will then teleport and disappear! so how can i parent it and still use it like normal? or is there a way in e2 that can work like the teleporter? i must know! thanks!

**Comment by Divran** [comment]
congratulations on issue nr 1337

**Comment by deathking61** [comment]
i have told it to "weld parent" yet this still happens............

**Comment by dvdvideo1234** [comment]
@deathking61 Are you sure that this option of this scrip actually creates a weld ?

**Comment by DatAmazingCheese** [comment]
Ticking weld doesn't weld parent right sometimes.

Try welding first, then parenting to a gate with remove constraints unticked.

**Comment by deathking61** [comment]
@DatAmazingCheese  what you recommended doesn't work, its either because it doesn't like to be inside the contraption OR it simply doesn't like to "parent" at all and that's bogus! if that's the case this shouldn't matter but i guess why will have to fix it.

**Comment by Divran** [comment]
Whether or not it's parented shouldn't matter. I'll try to remember to try this issue when I get the time.

**Comment by deathking61** [comment]
@Divran ok cool let me know if there is a possible fix for this issue?

**Comment by Divran** [comment]
The issue was this error message would appear in the console
```
Crazy origin on entity [93][gmod_wire_teleporter]
	Origin:           [6.759730, 111.745193, -36807.808594]
	Angles:           [-0.007970, 0.000001, 0.002042]
	Velocity:         [0.000000, 0.000000, -0.000000]
	Angular Velocity: [0.000000, 0.000000, -0.000000]
Defusing!
Removing!
Crazy origin on entity [97][prop_physics]
	Origin:           [3.123589, 161.288589, -24613.744141]
	Angles:           [-0.008524, -165.630249, 359.999908]
	Velocity:         [-1.786665, -4.462221, -3959.997070]
	Angular Velocity: [-0.008306, -0.004371, 0.004839]
Defusing!
Removing!
```
and then the entire contraption would be deleted.

I fixed it by making the teleporter automatically unparent itself just before teleporting, and reparent itself just after teleporting.

**Comment by deathking61** [comment]
so does this mean i can now do the teliporter with parenting? cause doing the welds is not fun

**Comment by Divran** [comment]
Yes, assuming the server you play on uses the latest version of wiremod downloaded directly from here (workshop is always a bit behind, so that doesn't have this fix yet)

**Comment by deathking61** [comment]
ok cool so would it have to be weld parent? or does that matter?

**Comment by deathking61** [comment]
ok cool so would it have to be weld parent? or does that matter?

**Comment by Divran** [comment]
After this update you no longer need to weld the teleporter, just parent is enough, as long as its parented to the same entity that every other entity is parented to (the "core" so to speak)

**Comment by Divran** [comment]
yes

**Comment by deathking61** [comment]
ok also you might wanna look into the other issue and that is you cannot
put it inside a contraption if you do it will not work at all

**Comment by Divran** [comment]
what

**Comment by deathking61** [comment]
ok so if you parent the teleporter inside the contraption (like making a
cage and parenting the teleporter on the inside) the teleporter will not go
to the target

**Comment by AbigailBuccaneer** [comment]
Off the top of my head that sounds like it might be some sort of anti-prop-noclip prop protection issue. Can you confirm that this is happening in single player without any addons other than Wiremod? If it is, please open a new issue about it, because it is a separate issue.

**Comment by Divran** [comment]
The teleporter has some checks built in that attempts to detect if any of the props would be placed inside a world brush. Make sure you're not trying to put it halfway inside a wall.

**Comment by deathking61** [comment]
its not its dead centure in side the cage so it shouldn't be that way
