### ISSUE TITLE
Expression 2 egpParent(number,entity) broken

### ISSUE THREAD

**Issue by HungarianPatriot** [wiremod/wire#1344]
The function egpParent(number,entity), which is supposed to parent an EGP 3d tracer object to the specified entity according to its description, ignores the entity input, and parents the 3d tracer to the owner instead.

**Comment by adosikas** [comment]
You must be doing something wrong, it works perfectly fine for me on both Emitter and HUD with the following code:

    EGP:egp3dTracker(1,vec())
    EGP:egpParent(1,Entity)

Of course you need to parent something to the 3d tracker, as it is invisible (same when just tracking a vector) and make sure the entity actually exists.

**Comment by HungarianPatriot** [comment]
Here is my code:
`if(first())
{
...entity acquisition here
    EGP:egp3DTracker(0,Entity:pos())
    EGP:egpParent(0,Entity)
    EGP:egpCircleOutline(4,vec2(0,0),vec2(10,10))
    EGP:egpColor(4,vec(255,0,0))
    EGP:egpSize(4,3)
    EGP:egpParent(4,0)
    print(EGP:egpTrackerParent(0))
}`
The E2 prints out the entity, so it's valid for certain. However, the circle is parented to me. I also tried creating the 3d tracker with an empty vector and a 0,0,0 vector instead of the Entity's pos, but no improvement.
