### ISSUE TITLE
Expression 2 holoParent(number,bone) fails to parent the hologram

### ISSUE THREAD

**Issue by ghost** [wiremod/wire#1345]
The function holoParent(number,bone) which is supposed to parent the hologram with the given ID to the given bone, fails to parent the hologram at all.

**Comment by thegrb93** [comment]
iirc, ACF overrided SetParent incorrectly causing this.

**Comment by thegrb93** [comment]
Actually it's because https://wiki.garrysmod.com/page/Entity/SetParentPhysNum only works clientside.
