### ISSUE TITLE
Spawn and break...

### ISSUE THREAD

**Issue by MrPlatypusGames** [wiremod/wire#1346]
I am current developing a rather simple code that has had me on the fritz for awhile now....
I'm attempting to code it to basically where I can spawn a barrel where i'm looking using mouse 1, then propbreak kinda thing with mouse 2.

I have used concmd ("gm_spawn " + Model) and Model is the code for the barrel.
The issue with this is I successfully got it to spawn barrels where I was looking, but I couldn't use propBreak obviously, and know no other way to make it explode with code.

I then went to a longer code of "propSpawn("models/props_c17/oildrum001_explosive.mdl", E:toWorld(vec(0,0,0)), E:angles(), 1)"
It wouldn't allow me to make it where it spawns where i'm looking, but it still didn't let me propBreak, but I think that's due to me coding it wrong

Is there anyway to break it with another command than propBreak...Thanks for the help!

**Comment by Divran** [comment]
This site is used to report issues/bugs in the code in wiremod, not to ask for help. Either go to https://www.reddit.com/r/wiremod/ to get help (eventually), or go to https://discord.gg/cqJ45CT to get help almost instantly (the discord channel is more active).

That being said, you can definitely spawn props where you are looking using propSpawn, and propBreak works just fine.

First do this
```
@persist Ent:entity
```

then, somewhere in your code (like when you press a key on your keyboard or whatever) do this
```
Ent = propSpawn(Model,owner():aimPos(),owner():eyeAngles():setPitch(0)+ang(0,180,0),1)
```

and lastly, somewhere else in your code, do this
```
Ent:propBreak()
```

But yeah if you have any more questions about this then go ahead and go to the discord channel instead. You can copy paste a link in there that leads to here if you don't want to repeat yourself.
