### ISSUE TITLE
The wire motor tool behaves very strange ( Workshop version )

### ISSUE THREAD

**Issue by dvdvideo1234** [wiremod/wire#1347]
The first thing that I noticed is when the angular velocity of the wheel is set too high it flips around on its axis and continues to spin. When it slows down returns to the normal position it was constrained in the first place.

The second thing is that when you try to make a car and you use a negative torque it works as expected to behave, however if you dupe it. The motors with negative torques do not spin anymore does not matter if you putting a signal in the ("Mul":NORMAL) input

For further details note the screenshot below:

https://drive.google.com/file/d/0B6vgydhudtoAMGlNdUFOdjkxTGs/view?usp=sharing

**Comment by AbigailBuccaneer** [comment]
Can you reproduce the flipping issue with the same kind of angular velocity with the regular (non-Wire) motor tool?

**Comment by AbigailBuccaneer** [comment]
The negative torque duplication issue also looks like it's caused by an underlying Garry's Mod bug, it uses an underlying `phys_torque` entity created via `constraint.Motor`, and I can't see anywhere we clamp the torque values ourself.

**Comment by dvdvideo1234** [comment]
Yes both directions are reproducable. It behaves similarly. I am more concerned about the duping problem.
