### ISSUE TITLE
WireLib.GetVersion returns wrong result when subscribed+legacy

### ISSUE THREAD

**Issue by X-Coder** [wiremod/wire#1351]
Is it on purpose WireLib.GetVersion() returns "Workshop" if wiremod is installed as legacy addon (git) and subscribed to workshop at the same time? At least this happens on dedicated server which uses a workshop collection including wiremod and a additional (temporary) local legacy install.

I think this is wrong as it should respect garrysmod load order.

https://github.com/wiremod/wire/blob/master/lua/wire/server/wirelib.lua#L1186
This could be solved by moving the workshop check to the bottom of the function.

**Comment by Divran** [comment]
Are you sure gmod loads normal addons before workshop addons? If so, it'd be great if you could post a PR that fixes this issue.

**Comment by bigdogmat** [comment]
Legacy has priority

**Comment by X-Coder** [comment]
@Divran, legacy addons have priority over workshop addons with garrysmod, or did this change?
With wiremod's WireLib.GetVersion() its the other way around, with it the workshop-test has priority over legacy-test.

**Comment by X-Coder** [comment]
Did a PR, I tested it on my dedicated server. But I don't know if it would have any side effects, so you should it test carefully before merging.

**Comment by Divran** [comment]
nah this couldn't have any side effects
