### ISSUE TITLE
E2: Add runOnPlayerSpawn, runOnPlayerDeath

### ISSUE THREAD

**Issue by Extra-Mental** [wiremod/wire#1356]
I made my own version of spawn and connection functions just before they were added to e2, i yet only just realised there were some added.

However theres only connect and disconnect, how about adding init spawn, spawn and death events? They are more useful rather than continously checking if players are dead or spawned

**Comment by bigdogmat** [comment]
Init spawn and connect are the same thing?

**Comment by Extra-Mental** [comment]
oh i assumed it was connect as in connect to the server

**Comment by bigdogmat** [comment]
Well `PlayerInitialSpawn` is called once they're completely in the server, so it's pretty much the same thing as connect.

**Comment by Divran** [comment]
In lua they aren't the same thing, but in E2, the player connected event doesn't exist and instead the initiap spawn event is called player connect. It does make sense though, because the actual player connected event wouldn't be useful in E2.

**Comment by CaptainPRICE** [comment]
If you look up Workshop, there is already an extension for those events: on player connect/disconnect/death/spawn, on entity damage/break/spawn/remove.. And more. But, E2 doesn't implement all those for whatever reason, and they we have to write our own "hooks".

**Comment by andreblue** [comment]
https://github.com/wiremod/wire/commit/9db3f6a6b816ad6396d8849fe97fb024278d84ba already exists which gives join(PlayerInitialSpawn) and leaving(PlayerDisconnected). Don't see why you are talking about re-adding them.

**Comment by thegrb93** [comment]
I guess a few more hooks won't hurt, but will this conflict with a 3rd party mod that does the same? Might be better to let them pr their code.

**Comment by CaptainPRICE** [comment]
> It does make sense though, because the actual player connected event wouldn't be useful in E2

Nothing of that makes sense for an EGP scoreboard which would like to show "player STEAM_X:Y:Z is connecting", however.



> but will this conflict with a 3rd party mod that does the same

Seriously considering that? In most of the cases, when E2 officially supports a new event, 3rd-party addon for the given event functionality is removed afterwards, so there are no conflicts.

**Comment by Vurv78** [comment]
Well this is done now.

**Comment by thegrb93** [comment]
Where?

**Comment by Vurv78** [comment]
https://github.com/wiremod/wire/pull/2003

**Comment by thegrb93** [comment]
All right. Thanks.
