### ISSUE TITLE
Files could maybe be saved in addons/wire dir after SVN checkout

### ISSUE THREAD

**Issue by revosw** [wiremod/wire#1362]
If you subscribe to the Wiremod addon, files get saved directly into common/garrysmod/garrysmod. However, if you SVN checkout wiremod on the addons folder, I think all wire-related files should be saved into addons/wiremod. It feels redundant having some directories duplicate, like the data folder where expression 2 code gets saved. It defaults to garrysmod/data instead of garrysmod/addons/wire/data. Just semantics, it's not a problem at all that I have some folders outside of addons.

**Comment by CaptainPRICE** [comment]
What?!?

**Comment by revosw** [comment]
Is it that this sounds completely idiotic or that you don't quite catch my drift?

**Comment by Divran** [comment]
What are you talking about

**Comment by revosw** [comment]
Okay this issue can be thrown in the trash right away because I have misunderstood completely the SVN checkout of this repo, the folders should of course be merged with the ones in the root garrysmod/garrysmod folder

**Comment by Divran** [comment]
The data folder that it creates & uses will be merged, yes, but when you install the addon via github, you should place the addon under garrysmod/addons. If you place the addon outside the garrysmod folder, then uninstalling the addon (if you ever want to do that) will be a huge pain.
