### ISSUE TITLE
Wiki page for Expression-2 is a mess

### ISSUE THREAD

**Issue by TruePikachu** [wiremod/wire#1363]
I set out to make [a very small change in the formatting of the section for `#include`](https://github.com/wiremod/wire/wiki/Expression-2/_compare/6717c72fce059d823820fe31f5c6ac11b2e5e3c8...3decec000f0210aafbcd7fe278ed123fac2eb438) (since it wasn't clear that the `#` is part of it), which led to the page taking too long to render "in production" (despite having rendered in the preview) and my account being flagged (I _think_ this has been cleared up with staff, but I _do_ know it was a result of editing the page).

Given that the servers can't render the page now, despite the change both being small and only utilizing source elements that were already present (`&#35;` and `<code></code>` tags), and being valid Wiki markup (as evidenced by the local preview, albeit the preview has render issues of its own), I believe there's probably some greater issue in the page itself.

**Comment by TruePikachu** [comment]
Servers caught up, and I've concluded that MediaWiki makes little to no sense here on Github, looking at the page render of the examples. I might try a recode of the current page in Markdown, but I'd want other opinions on it first.

**Comment by Divran** [comment]
We've been talking about splitting it up into multiple smaller pages, but no one has taken the time to do it

**Comment by CaptainPRICE** [comment]
Might this be helpful; [mediawiki-to-markdown](https://github.com/philipashlock/mediawiki-to-markdown).

**Comment by AbigailBuccaneer** [comment]
Can we pretty please use reStructuredText instead of Markdown? (The tool @CaptainPRICE links does support it.)

http://zverovich.net/2016/06/16/rst-vs-markdown.html
http://ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/
http://eli.thegreenplace.net/2017/restructuredtext-vs-markdown-for-technical-documentation/

**Comment by TruePikachu** [comment]
Keep in mind that the more "exotic" the language used, the less likely someone is to edit the page.

**Comment by andreblue** [comment]
Markdown works just fine.  It does not really have to do any really complicated stuff. I have been touching it a bit on the wiki to make it better.

**Comment by shadowscion** [comment]
For expression2 we at least have the e2helper, could we not do what expadv has done and have a function that outputs formatted markdown automatically from the helper data?

**Comment by oldmud0** [comment]
The problems start when you want things that GitHub Markdown does not support, such as sortable tables and color. But for the most part, I think the new page is all right.

**Comment by TomyLobo** [comment]
There is e2doc, maybe that could be updated to output github markup instead of what it did before

**Comment by Divran** [comment]
I think e2doc is broken.. or maybe it wasn't. Maybe it's just that it tries to get the descriptions from comments, but very few of the functions in E2 actually have comments above them. Either way, I don't think it works properly.

**Comment by Vurv78** [comment]
This can be closed since E2 Docs are autogenerated and stuff is in separate pages
