### ISSUE TITLE
Fix Namer tool

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1367]
Currently, the Namer tool seems to work even on non-Wire entities, which relatively can screw things up on 3rd-party entities!
The same fix is needed for #1366. So, perhaps introduce a new function in wirelib we can then make use of?
How does 3rd-party entity integrate with Wire?
How does one figure it is Wire-based (derived) entity?

**Comment by CaptainPRICE** [comment]
Since @TomyLobo didn't came up with the function for me...
One silly solution would be to have a list of entity class names of all known wire entities.
Another silly solution would be to check entity names if they start with `gmod_wire_*` or `wire_*`.
The third, kinda a "good" solution I could think of would be to use `scripted_ents` library and then figure out the base entity through the class name.

**Comment by Divran** [comment]
How can this break on 3rd party entities? It stores the name in a variable called `WireName` (in `SetNWString`). There's basically no chance of this interfering with other more normal variables, like `Name`

**Comment by CaptainPRICE** [comment]
Exactly I said to @TomyLobo. Maybe `WireName` will not cause problems, but `name` definitely will interfere. That's why we need such function.

**Comment by Divran** [comment]
What are you talking about? I literally just said the wire namer stores its value in `WireName`, not `name`. I say again: The wire namer doesn't use the variable called `name` anywhere, except in the data object given to EntityModifier, but that can't interfere because that's also stored in `WireName`, see:
```
duplicator.StoreEntityModifier( Entity, ---> "WireName" <--- , Data )
```

**Comment by CaptainPRICE** [comment]
I get it Divran, but it was just an example.. We need this function in a way.
