### ISSUE TITLE
Travis seems to be blocking certain pull requests [potentially not an issue]

### ISSUE THREAD

**Issue by RevoluPowered** [wiremod/wire#1376]
I just noticed a large backlog of Pull Requests.

Various errors from LuaCheck, but it's in a high number of pull requests.
```
Checking lua/entities/gmod_wire_expression2/core/debug.lua 1 error
    lua/entities/gmod_wire_expression2/core/debug.lua:7:2: expected expression near '*'

Checking lua/wire/client/text_editor/wire_expression2_editor.lua 354 warnings
```

Can someone merge this pull request, just to get other pull requests closed/rejected, as necessary?
https://github.com/wiremod/wire/pull/1369

**Comment by AbigailBuccaneer** [comment]
#1369 needs reviewing before it can be merged.
