### ISSUE TITLE
e2doc console command does not work

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1377]
<code><a href="https://github.com/wiremod/wire/blob/930023863d0000801c90b6612c10c966b94acc23/lua/entities/gmod_wire_expression2/core/e2doc.lua#L125-L150">e2doc</a></code> console command does not work.

Also, auto-complete function throws the following errors:
<pre>
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/e2doc.lua:140: bad argument #1 to 'ipairs' (table expected, got nil)
  1. ipairs - [C]:-1
   2. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/e2doc.lua:140
</pre>

<pre>
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/e2doc.lua:72: bad argument #1 to 'gmatch' (string expected, got nil)
  1. gmatch - [C]:-1
   2. e2doc - addons/wire/lua/entities/gmod_wire_expression2/core/e2doc.lua:72
    3. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/e2doc.lua:133
     4. unknown - lua/includes/modules/concommand.lua:54
</pre>

**Comment by thegrb93** [comment]
Bumping this up to higher priority
