### ISSUE TITLE
Rewrite holoBoneScale E2 functions to use no for-loop

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1382]
This is what I have found while traversing through every e2function:
`vector=holoBoneScale(number, number)`: [Go to source](https://github.com/wiremod/wire/blob/0b065a0ba5b9e664d72d4d285e37a9952c4c8a86/lua/entities/gmod_wire_expression2/core/hologram.lua#L816-L826).
`vector=holoBoneScale(number, string)`: [Go to source](https://github.com/wiremod/wire/blob/0b065a0ba5b9e664d72d4d285e37a9952c4c8a86/lua/entities/gmod_wire_expression2/core/hologram.lua#L828-L840).

Above E2 functions can be rewritten in such way so they don't use for-loop at all, which will increase performance :)
Also, somebody have mixed tabs/spaces in the first E2 function I have mentioned above!

**I will work on this a bit later**.

**Comment by Divran** [comment]
wow thats some bad code. Checking history to see who wrote it

**Comment by bigdogmat** [comment]
Should also remove those `table.Count` calls.
