### ISSUE TITLE
E2: Add type checker functions for non-truthiness, allowing for T[1,entity] = noentity()

### ISSUE THREAD

**Issue by bigdogmat** [wiremod/wire#1388]
Currently the type checker fails if the entity is invalid, though it shouldn't because an invalid entity is still an entity. This caused #1350.

Another example of what this breaks is assigning values to arrays. Currently arrays use the type checker on the value being assigned, if it fails it isn't put into the array. This is bad because it can mess up the sequentiality of an array. It's also a bit inconsistent because the construct for arrays doesn't use the type checker.

So
```
T = array(noentity()) # The NULL entity is in the first index
```
and
```
T[1, entity] = noentity() # Fails because the NULL entity doesn't pass the type checker
```
don't have the same outcome.

**Comment by Nebual** [comment]
Generally speaking, when one writes in E2
```
if(Ply) {
  # Do stuff with Ply
}
```
the expectation is that Ply is valid. I don't think we can break backwards compatibility that far to change this, though perhaps a hack is possible for specifically inserting null entities (or arbitrary falsey types) into arrays? Perhaps a set of type validity functions that checks for minimal compatibility with the type (`isentity`, `istable`, etc) which would be used in cases like this but **not** for truthiness.

**Comment by bigdogmat** [comment]
That would still work fine as that's controlled by the `is` operator, not the type checker.

**Comment by Divran** [comment]
`foreach will loop over NULL entities in arrays instead of ignoring them.`
I wouldn't want this behavior in my E2s though since it would add more ops for no gain

**Comment by Nebual** [comment]
@Divran avoid putting nulls in your arrays then

**Comment by Nebual** [comment]
If I understand correctly, it was previously possible to end up with invalid entities in an E2 array (ie. Spawn prop, put in array, remove prop, nothing automatically removes it from the array), but you could not intentionally add them, which was an inconsistency.

**Comment by bigdogmat** [comment]
You could intentionally add them in the constructor.

**Comment by AbigailBuccaneer** [comment]
If E2 is a statically typed language, then values need to not suddenly stop being members of a certain type because of external changes.

**Comment by Divran** [comment]
@AbigailBuccaneer null entities are still entities

**Comment by AbigailBuccaneer** [comment]
@Divran yep, we're in agreement (#1538). You're the one who said that you didn't want `foreach(K, V:entity = T)` to iterate over null entities

**Comment by Divran** [comment]
nah it's fine
