### ISSUE TITLE
E2 doesn't work correctly with prop protection

### ISSUE THREAD

**Issue by Fasteroid** [wiremod/wire#1394]
So I posted this on falco's github page and he said this:

> FPP has a thing called CPPI. It allows addons to query whether the prop protection allows a player to do something with a prop. All major pro protections have this. Wiremod uses it, I believe, but I don't know how it deals with expression 2 functions. Whatever they do is their decision, though. CPPI should make it possible for them to make what you want. Once they do so, it will work with any major prop protection.

In more basic terms, admins seem to not be able to run propcore functions on other people's props... the other person HAS to have buddied the admin. Admins should be able to run e2 on other people's props regardless of the buddied status... but that currently is not how it works. For instance, even as admin, I can't propDelete() a player's things until they buddy me.

Certain functions such as applyforce don't even check the buddied status at all, they simply fail to run entirely on anything that isn't your props...

I'd love to see this fixed, but if it at all requires completely re-doing E2 i'd rather it be left as-is for now.

Catch you dudes later, stay awesome! -Fast

**Comment by bigdogmat** [comment]
Referring to `propDelete`, and everything else in propcore, it checks if the player is buddies with the entities owner. I assume when Falco said 

`It allows addons to query whether the prop protection allows a player to do something with a prop.`

he's talking about the `CPPICan*` functions, however none of them would fit the use case of deleting a prop (for example) as far as I can tell.

**Comment by CaptainPRICE** [comment]
@Fasteroid
There is a setting in FPP, which disallows even admins to touch your props unless you buddy an admin first. So if I am not wrong, I guess that your FPP installation is being configured incorrectly. Check your FPP server settings.

**Comment by AbigailBuccaneer** [comment]
Where possible I'd like for us to avoid CPPI and use hooks like [CanProperty](http://wiki.garrysmod.com/page/SANDBOX/CanProperty), [CanTool](http://wiki.garrysmod.com/page/SANDBOX/CanTool), [PhysgunPickup](http://wiki.garrysmod.com/page/GM/PhysgunPickup) and others - that should cover the vast majority of cases.

For the other things, we can either use CPPI or invent our own hooks (and maybe provide an implementation that uses CPPI if available). In general I don't like CPPI, the hook system is much more extensible and flexible, but I do acknowledge that it's what's become a standard.

**Comment by Fasteroid** [comment]
@CaptainPRICE Do you know where this setting can be found?

**Comment by thegrb93** [comment]
I prefer either CPPI or hooks specific to prop protection since those hooks can clash with other addons.

**Comment by thegrb93** [comment]
Iirc E2 uses it's own prop protection because they are not standardized well.

**Comment by thegrb93** [comment]
Nevermind, the issue is some functions aren't using E2's own prop protection it seems.

**Comment by Divran** [comment]
which functions

**Comment by thegrb93** [comment]
He mentioned prop core

**Comment by thegrb93** [comment]
Looks like it uses e2's built in 'isOwner' function.
