### ISSUE TITLE
Add "entity:use()" function and "runOnUse" hook

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1399]
A function that would be implemented as a new E2-core extension, that would basically mimic [`Wire User entity`](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_user.lua) functionality.

Also, this should introduce two new ConVars:
- `wire_expression2_use_maxdistance`: A maximum distance between `Entity` and `E2` in order for `entity:use()` function to work on `Entity`. I am thinking of using `1000` units as the default value.
- `wire_expression2_use_level`:
    - `0` (default): E2 owner can only use his/her own entities.
    - `1`: E2 owner can use world/map entities.
    - `2`: E2 owner can use entities owned by another player.

Additionally I would also like to introduce a new hook/event, `runOnUse(number)` and `useClk()`, that would allow E2 to do something when a player `+use`'s an entity, etc.

### Support
React to this issue with 👍 if you support it, and would like to have this feature in E2.
Remember to post a reasonable comment, otherwise your vote won't count.

**Comment by shadowscion** [comment]
Not keen on the runOnUse hook, but I've wanted entity:use() for years now.

**Comment by CaptainPRICE** [comment]
@shadowscion I have added "voting" to OP, go ahead and upvote it :)

**Comment by Pajro4** [comment]
+1 for the entity:use()

**Comment by oldmud0** [comment]
`runOnUse()` is if a player does the use command on the E2 chip, right? I can't see anything inherently wrong with these, and it looks like a good idea to save on ops, so I support the use hooks.

**Comment by CaptainPRICE** [comment]
> `runOnUse()` is if a player does the use command on the E2 chip, right?

Not just for the E2 chip. It is for all players & any `USE`-able entity.
[`PlayerUse`](https://wiki.garrysmod.com/page/GM/PlayerUse)

**Comment by oldmud0** [comment]
Well.... that ignore the use range, doesn't it?

**Comment by CaptainPRICE** [comment]
@oldmud0 The hook would obviously ignore the limits, that's nothing to do with ConVars. It is a hook/event. However, `entity:use()` function is the one that's affected by ConVars.

**Comment by AbigailBuccaneer** [comment]
Please stop encouraging 'voting' via reactions and ad-hoc rules about whose votes count and whose don't. Wire Team already has a structured development process.

**Comment by Codingale** [comment]
Just adding a comment in that `runOnUse` would be helpful because trying to hold a tiny prop sometimes and checking `aimEntity` returns null.

**Comment by Codingale** [comment]
Would, `runOnUse` work for props? I've been working on a system recently and I ended up setting the weight of tiny props to `251` in order to prevent player pickup.

**Comment by Nebual** [comment]
#1523 Adds a runOnUse() for the E2 itself, which is probably safer than allowing it for any arbitrary entity. 

On the meta discussion of voting on issues - I'd say please do! Seeing 6 upvotes on this FR encouraged me to make a PR for my private extension. Github shows you who exactly voted, and while I'd weigh Abigail and Divran's opinion above random players, its still useful to see. I believe Wireteam's structured development process is "let issues and PR's pile up for months until someone with push access feels like playing Gmod long enough to test them", and "work on whatever you happen to feel interested in"

**Comment by CaptainPRICE** [comment]
Ok. Cool.
Looks like this one were left open. Closing it manually.
NOTE: Use `fixes #N` in the title of PR next time, where N is issue's ID to auto-close referenced issue in future ;)
