### ISSUE TITLE
E2 is downloaded and I have put txt files into "Expression2" folder.

### ISSUE THREAD

**Issue by Devlonation** [wiremod/wire#1401]
E2 is downloaded and I have put .txt files into "Expression2" folder, But the files are not showing up into my Garry's mod. Please help with my problem

**Comment by Divran** [comment]
The github issues page is for bugs with wiremod itself, not with problems during installation or use. The correct place to ask this would be here https://discord.gg/cqJ45CT

However, I would've helped you here anyway, except I need to leave now and I don't have the time. I'll leave this issue open for now in case someone else sees it.

Also, you need to give us some extra information like a screenshot of your addons folder structure (if you didn't use the workshop) and your gmod's data folder structure.

**Comment by CaptainPRICE** [comment]
@devlonation 
First, make sure you have your E2 (a `.txt` file) in `./Steam/steamapps/common/GarrysMod/garrysmod/data/expression2` folder. Make sure it is called exactly `expression2`, case-sensitivity matters if you are running non-Windows OS!
If you have it called as `Expression2` on non-Windows OS, then it will NOT find your E2s.

I hope I have helped you :)

**Comment by CornerPin** [comment]
Just press **Update** button in the file tree.
![image](https://user-images.githubusercontent.com/7669876/28126636-b5d97320-6732-11e7-8394-7849697cb17c.png)
