### ISSUE TITLE
Wiremod Console Commands Are Non-Existent

### ISSUE THREAD

**Issue by HeyLookItsBlu** [wiremod/wire#1402]
Hello. My name is Blu and I am a server owner. I've recently encountered a issue with Wiremod. Certain commands such as "wire_holograms_modelany 1" is not being read as an actual command. I have Wiremod and Wiremod Extras installed and alot of the Wiremod cores (I think all the cores)

**Comment by oldmud0** [comment]
What extensions do you have enabled?

**Comment by HeyLookItsBlu** [comment]
DamageCore, PlyCore, SentCore, and Holo Phys Core.

**Comment by deathking61** [comment]
if you have ULX installed try tunning those though the RCON that helps a lot of the time.

**Comment by deathking61** [comment]
and besides that DamageCore is actually broken right now as when you try to target a player it gives out errors and then kills the e2.

**Comment by Nebual** [comment]
Duplicate of #1470, also need more reproduction steps
