### ISSUE TITLE
E2 Holos not working on server

### ISSUE THREAD

**Issue by NathanInnes** [wiremod/wire#1403]
Hello all,

I have been looking through many forums about wiremod holos are not working anymore on my server, everything console wise has been enabled but when I attempt to use anything to do with holos it does not give me errors but they simply just don't spawn in.

I have tried to reinstall wiremod onto the server but that did not work either.

If any help is possible this would be much appreciated.

Thanks.

**Comment by AbigailBuccaneer** [comment]
Have you tried running with no addons except for the Git master version of wiremod?
