### ISSUE TITLE
internal error 

### ISSUE THREAD

**Issue by unsafeknave** [wiremod/wire#1408]
https://gyazo.com/a10316fdb093f82003e3daf3bd6df746
please help idk what to do

**Comment by bigdogmat** [comment]
The error is coming from something inside the `gmc_fuckup` addon.

**Comment by Divran** [comment]
Yep this is caused by a very badly made plugin to E2 like bigdogmat said. Seems like this plugin wasn't even tested at all before it was released.

**Comment by unsafeknave** [comment]
so how do i fix it @Divran @bigdogmat

**Comment by bigdogmat** [comment]
Report the error to whoever made the `gmc_fuckup` addon.

**Comment by Divran** [comment]
sounds like a trash addon, uninstall it

**Comment by unsafeknave** [comment]
@Divran how do i uninstall it's not a steam addon from the workshop

**Comment by bigdogmat** [comment]
If you're in single player, or running this on your own server, then delete it from the addons folder. If it isn't your server, report it to whomever runs it.
