### ISSUE TITLE
Motor and hydraulic should be updateable

### ISSUE THREAD

**Issue by MulleDK19** [wiremod/wire#1410]
Using especially motors takes forever since finding the right forces takes many tries, which is especially tedious since you have to remove the entire motor, move the prop up in the air, then make a new motor with updated values instead of just being able to right click on the controller like every other tool to just update it.

**Comment by oldmud0** [comment]
That was a pretty fast fix for an annoyance that's been around since the very beginning.

**Comment by Divran** [comment]
eh I was bored and this was a small fix
