### ISSUE TITLE
E2 Extensions that are disabled by default don't update even as the console says it's reloading extensions.

### ISSUE THREAD

**Issue by PhantomEnderium** [wiremod/wire#1412]
For some reason, the default extensions that are disabled (propcore, html, remoteupload, etc.) can't be enabled. I've ticked the boxes under the E2 Extensions tab in Utilities, I've run console commands to enable them (wire_expression2_extension_enable [extension]), and have even run the command to reload the extensions. for some reason, it never does reload. according to the console, the extensions are even shown to be disabled even after trying to enable them.

this is using the workshop version of wiremod.

**Comment by Divran** [comment]
I tried it (using the latest github version) and everything worked fine.

**Comment by EnderScout** [comment]
@Divran like I've said, I have the workshop version. should I switch to the GitHub one?

_Sent from my LGE LGLS992 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Divran** [comment]
Yes

**Comment by EnderScout** [comment]
@Divran I've gone and uninstalled wiremod from the workshop, and went through to install the GitHub one. doesn't seem to be working still, however the game seems like the workshop version is still there (nothing reset). any way to get the GitHub working and not the workshop one?

_Sent from my LGE LGLS992 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Divran** [comment]
Unsubscribe from workshop, then delete the workshop file in the addons
folder, then to be safe also delete the download cache folder. I'm not at
my PC right now so I can't give you the exact file path to the cache
folder.

**Comment by EnderScout** [comment]
@Divran could you let me know where the cache is when you get a chance? I tried deleting the one from the garrysmod folder but nothing seemed to happen.

_Sent from my LGE LGLS992 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
