### ISSUE TITLE
E2: Callable Strings issue or design limitation?

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1415]
I will just let the code speak for itself this time:

```golo
@persist [Array,GTable,Print,Table]:string
@outputs OutR:array OutGT:gtable OutT:table

Array = "array"
GTable = "gTable"
Print = "print"
Table = "table"

(Print)("hello", 1234.5, entity()) # Works.

Print("steamID"(owner())[string]) # Print works.

OutGT = GTable()[gtable] # Works.

OutR = (Array)()[array] # Works too.
OutR = (Array)((1) = "1st", "2nd")[array] # Does NOT work.

OutT = Table()[table] # Works as well.
OutT = Table("key" = "value")[table] # Does NOT work too.
```

-----

@Divran You are the one in-charge for this concept.
What do you think, is it an issue to be fixed or a design limitation/failure?
(In my opinion it is an issue. Undocumented too!)

**Comment by Divran** [comment]
the `key = value` syntax is specific to table definitions.

**Comment by CaptainPRICE** [comment]
> the key = value syntax is specific to table definitions.

Yeah it is? But callable strings exist to allow you us to call functions, so "table definitions" should be supported for it (but it is really just these 3 functions/exceptions); otherwise, you can't have array/gtable/table initialized with values.. :(

**Comment by bigdogmat** [comment]
The parser does a special case when it comes into those function names and no longer treats them as normal function calls.

**Comment by AbigailBuccaneer** [comment]
`table("foo" = "bar")` isn't a function call. If anything, it's a design failure that it looks like a function call and misleads people into creating GitHub issues like this.

**Comment by Divran** [comment]
@AbigailBuccaneer Nope, it is an actual function call, and then we added the special case `key=val` on top of it https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/base/parser.lua#L1273-L1274

**Comment by AbigailBuccaneer** [comment]
@Divran as you show yourself, these end up as [`kvtable` and `kvarray` instructions](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/base/parser.lua#L1314), not a `fun` instruction. You're right that the parsing of them starts off in the same way (because, after all, it looks like a function call), but semantically it's not.

`table(Foo, Bar)` and `array(Foo, Bar)` *are* parsed as `fun` instructions.

**Comment by Divran** [comment]
yes, so?
