### ISSUE TITLE
E2 function toChar(0) not returing null byte

### ISSUE THREAD

**Issue by AlexALX** [wiremod/wire#1419]
Ok, what title says - E2 function toChar(0) not returing null byte. 

https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/string.lua#L131

this line should be less zero and not one, because in lua string.char(0) returns null byte just fine, and idk why you limited that in e2.

**Comment by CaptainPRICE** [comment]
Common and known issue... And still not fixed, WTF?!
