### ISSUE TITLE
E2: #include can be used to bypass functiondef-inside-functiondef restriction

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#1421]
This works (but shouldn't)
```
@name Main
function func(){
    #include "inc"
}
```
```
@name inc
function inc(){}
```

This doesn't (because of [this restriction](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/base/parser.lua#L562) )
```
@name Main
function func(){
    function inc(){}
}
```

This issue causes the problems the restriction was put in place to prevent, which is inconsistent behavior.

Example of such an issue:
```
@name Main
function number func(){
    #include "inc"
    return 1
}
```
```
@name inc
function number inc(){return 2}
```
Error during validation: `Return type mismatch: void expected, got number at line 4, char 5`

Credit to @CaptainPRICE for finding this case.

Possible solutions would be:

* send along `in_func` when parsing included file
* block #include inside UDF completely (are the legitemate usecases that this would break?)
* fix functiondef-inside-functiondef not working, and remove restriction

**Comment by AlexALX** [comment]
Idk if this is bug or feature, because actually i used includes inside functions for include file only when needed, and of course it have functions inside, without it it will break all my work.

For example this file https://github.com/AlexALX/wiremod_e2_os/blob/master/expression2/alx_pc/gpu/alxos/_prog_.txt

`

ALXOS_PROGS["alxos_bmp_reader",number] = 1
--

`

**Comment by CaptainPRICE** [comment]
@AlexALX Yeah, we are aware of that there is a (lazy) solution that would break the existing E2s and fix the bug as well... I am against such solution too.
Join the discussion at Wiremod Discord (`#help` channel).

**Comment by adosikas** [comment]
I guess the restriction is there for a reason, maybe @Rusketh can tell us why.

It does not seem to cause issues when the outer function returns void (like in @AlexALX code).
Perhaps the restriction can be made more permissive (to allow udf inside void-return-udf).
