### ISSUE TITLE
E2: Why do we have both, "normal" and "number" types?

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1423]
```golo
@name normal...number?!
@outputs Implicit Normal:normal Number:number
Implicit = 123.45
Normal = 123.45
Number = 123.45
```

Please answer the question in details (is this to do with E1/E2 history?).

To me, they are literally all the same. And all of them can handle decimals too:
![image](https://user-images.githubusercontent.com/9789070/28238798-b8e5996a-695b-11e7-8444-1b95f3a05ff3.png)

And they can also be used interchangeably with callable strings, function arguments, etc:
```golo
@outputs X Y:normal Z:number
local Pos = entity():pos()
X = "x"(Pos)[number]
Y = "y"(Pos)[normal]
Z = "z"(Pos)[number]
print("x"(Pos)[normal], "y"(Pos)[number], "z"(Pos)[normal])
# We can even assign them to each other:
Z = Y = X
```

I see no real differences between them nor E2 wiki points it out, thus why I ask such a question.
There are only two differences I know:
- I have seen a couple of replacements in the source code, in E2Helper for example a `normal` is replaced with `number`.
- Wire Gates (oldschool) uses a `NORMAL` type.

And then I have also found some inconsistencies around this, for example:
In `wire_expression_types` and/or `wire_expression_types2` table, there is `NORMAL` (`n`), but there is no `NUMBER`.

I only see one reasonable answer to this so far, either a `number` type is supposed to be an alias of `normal` type, or it is something to do with history/WireLib?

**Comment by Divran** [comment]
Pretty sure they're aliases. I'm not sure where it started. Maybe @TomyLobo knows?

**Comment by CaptainPRICE** [comment]
So, since there are practically no differences, I see no point in having such an alias.
But, even if we were to remove one of those, it would break E2s... Yet another one of those cases... 😠

**Comment by immibis** [comment]
@CaptainPRICE Originally there were no types and every wire was a number.  
Then someone decided to add more types (though I don't know what type was first or how many were added at once).  
Then there were normal wires and string wires and vector2 wires and vector3 wires and entity wires and ....  
Then someone realised that calling them "normal" wires was stupid because numbers are just another type, so they changed them to "number" wires. But "normal" had to be kept around for compatibility.

**Comment by AbigailBuccaneer** [comment]
Historical raisins!

**Comment by TomyLobo** [comment]
gee, another pointless "issue" by @CaptainPRICE 
When do we ban him?

**Comment by shadowscion** [comment]
I mean, his antics lead to some seriously hilarious discussions on discord. To me that seems like motivation enough to keep him around.
