### ISSUE TITLE
E2: Add "number=wirelink:egpDrawTopLeft()" function

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1424]
So, there is a setter E2 function: `wirelink:egpDrawTopLeft(number)`.
But, there is no getter E2 function `number=wirelink:egpDrawTopLeft()`?!

**Comment by Divran** [comment]
This function is trash anyway. A better suggestion would be to remove it.

**Comment by CaptainPRICE** [comment]
> This function is trash anyway. A better suggestion would be to remove it.
> EDIT: But we probably can't do that cos we'll break everyone's E2s.

Yep. Should not remove it... I can tell 99% of mine EGP UIs are drawn using top-left, because the default (opt-out) "center-based" positioning is reta**** (only helpful when drawing circles in some cases).

Anyways, as a temporary workaround, keep the track of this manually.
