### ISSUE TITLE
E2: Wirelink() function not checking prop protection properly

### ISSUE THREAD

**Issue by ghost** [wiremod/wire#1425]
The entity:wirelink() function doesn't check prop protection properly (Such as if the player is admin+ or if they are prop protection buddies) meaning you aren't able to wirelink to world or player entities even if you have permissions to interact with their props such as being an admin, superadmin.

Update: Im not sure about the buddies thing, I have been told by someone that buddies are taken into account but i know for a fact admins that are able to target player props are not able to wirelink to it

**Comment by Nebual** [comment]
I believe wirelink uses the same permission checks most of E2 (including PropCore and Wiring and E:setMass(n)) uses. If a Prop Protection added is detected, we defer to their entity:CPPIGetFriends() lua method. I use my own https://steamcommunity.com/sharedfiles/filedetails/?id=159298542 NPP, and it works with this. If you're still having issues, its probably your prop protection, but if you believe its something Wire should fix please reopen this with more information, including a quick example E2, and a list of any admin or PP related addons you have installed.
