### ISSUE TITLE
Holo E2 Chip not working properly

### ISSUE THREAD

**Issue by TenCents01** [wiremod/wire#1428]
Hi all, sorry if this is a problem which has already been rectified before, but I haven't found a solution to it. I have two particular Holo E2 chips I'm currently working on; "CB&Q SD7" and "Boxcar" (both are provided so if anyone wants to test them to see what I mean, they require this prop pack to see though: https://steamcommunity.com/sharedfiles/filedetails/?id=260954002). Both are supposed to not project the holo until it is wired to its respective Entity. However, when "CB&Q SD7" is spawned, it works as intended, while "Boxcar" projects the holo from the chip and does not attach to the Entity properly when wired to it. Any possible reasons this could be. I've written both of them from scratch and they're almost exactly identical, except for a few things unrelated to the actual holo. All of the E2 extensions are enabled. Thanks in advance!
[CB&Q_SD7.txt](https://github.com/wiremod/wire/files/1151118/CB.Q_SD7.txt)
[Boxcar_.txt](https://github.com/wiremod/wire/files/1151119/Boxcar_.txt)

**Comment by Divran** [comment]
This github is for bugs and issues with the Lua code of Wiremod, not for asking for help on how to use it. The correct place to ask those questions would be on the reddit or on discord. The discord channel is far more active than the reddit page however.

I suggest you go to the Discord channel where there are many experienced E2 coders available to help you. https://discord.gg/cqJ45CT
