### ISSUE TITLE
E2 lastSaid() function unresponsive on my server. 

### ISSUE THREAD

**Issue by VXGGOVORTEXGaming** [wiremod/wire#1429]
An example of code that didn't work would be this
`
interval(100)

A = owner():lastSaid():explode(" ")

if(A[1,string]:lower()=="/test" & chatClk(owner())) {
    hideChat(chatClk(owner()))
print("ur a feggit")
}
`

There are no hint errors, there are no errors in server console, it just doesn't work. I've reinstalled wire numerous times but I have no idea as to what is causing this.

**Comment by Divran** [comment]
This github is for bugs and issues with the Lua code of Wiremod, not for asking for help on how to use it. The correct place to ask those questions would be on the reddit or on discord. The discord channel is far more active than the reddit page however.

I suggest you go to the Discord channel where there are many experienced E2 coders available to help you. https://discord.gg/cqJ45CT

**Comment by VXGGOVORTEXGaming** [comment]
I'm pretty sure this counts as a bug, because I'm complaining about a server specific issue.

**Comment by bigdogmat** [comment]
It's not a bug. `chatClk` does not work without `runOnChat(1)`, it uses it's own events, you don't need to use `interval`.

**Comment by VXGGOVORTEXGaming** [comment]
Sorry, didn't copy the whole thing and missed the statement. It is actually there.

**Comment by Divran** [comment]
In that case, maybe another addon is using "/" as a chat command prefix and isn't allowing the chat message to be passed to E2?

**Comment by VXGGOVORTEXGaming** [comment]
I tried it with other punctuation like periods and I also tried it without any punctuation but it still doesn't respond. This is happening to all players on my server.

**Comment by Divran** [comment]
```
runOnChat(1)
if (chatClk()) {print("someone said something")}
```
so this simplest possible script doesn't work?

**Comment by VXGGOVORTEXGaming** [comment]
Nope

**Comment by VXGGOVORTEXGaming** [comment]
I had other players try it too. Works fine on other servers.

**Comment by Divran** [comment]
There must be a conflict somewhere with another addon on your server since we can't reproduce it and it works fine on other servers.

**Comment by VXGGOVORTEXGaming** [comment]
Do you wanna check the server collection?

**Comment by VXGGOVORTEXGaming** [comment]
Can this be re-opened?

**Comment by CaptainPRICE** [comment]
@VXGGOVORTEXGaming It is your server issue, nothing to do with wiremod development. So, I think it can't be re-opened.
I can go further and help you to fix the server issue, but it is definitely not going to be discussed here, join Wiremod Discord instead.

**Comment by VXGGOVORTEXGaming** [comment]
Alright
