### ISSUE TITLE
E2: Restrict "engine/writez" material

### ISSUE THREAD

**Issue by EgrOnWire** [wiremod/wire#1431]
"engine/writez" could be used to partially disable rendering of objects in the world.
This acts similar to "pp/copy" effect, allowing user to blind other players.

**Comment by shadowscion** [comment]
a good idea to block this any any other known bad materials, but before anyone gets overzealous and makes materializing within wiremod based on a whitelist like garry did with the material tool, please don't

**Comment by Divran** [comment]
@shadowscion nah, a blacklist would be better

**Comment by EgrOnWire** [comment]
So this is not to be implemented in a near future?

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/pull/1245

**Comment by ajloveslily14** [comment]
This material doesn't even show for me, what is it?

**Comment by thegrb93** [comment]
That's what it is.

**Comment by Divran** [comment]
Yeah apparently it's an invisible material that makes everything behind it invisible as well.

**Comment by CaptainPRICE** [comment]
@Divran 
... except for shadows.

**Comment by AbigailBuccaneer** [comment]
> This material doesn't even show for me, what is it?

The clue is in the name `writez` - it doesn't write anything to the colour buffer but does write to the depth buffer (aka z-buffer), which means it'll stop other objects from rendering behind it. Opaque objects are drawn in closest-to-farthest order, so putting a `writez` object very close to a player's face would block most things from rendering. (I think the world might be rendered before any objects in Source, I can't remember, but either way it's bad.)

**Comment by ajloveslily14** [comment]
Sounds abuseable, but sadly also kinda cool, useful for like one way mirrors.

**Comment by Damianu** [comment]
Everyone is focusing on blocking those in E2, meanwhile I may remind you that most of minges use those by creating other wire entities with pp/copy.(wire_dynamic_button_material pp/copy)

**Comment by Divran** [comment]
@Damianu in that case we should have a `WireLib.setMaterial` function or something that everything in wire uses, and block it in there
