### ISSUE TITLE
E2: Add adjusting ragdoll-hologram bones.

### ISSUE THREAD

**Issue by fludd12** [wiremod/wire#1432]
If possible, being able to move/manipulate bones of a hologram of a ragdoll would allow for nonstandard animations, and the capability of getting ragdoll holograms to not be in T-pose when holoAnim is not enabled. I apologize if this has been suggested before, or is not possible.

**Comment by shadowscion** [comment]
It's been suggested (by me), PRed (by me) and denied iirc. 

https://github.com/wiremod/wire/pull/453
