### ISSUE TITLE
GPU flickering when onscreen

### ISSUE THREAD

**Issue by hawk0484** [wiremod/wire#1434]
most things in the scene flicker whilst it is onscreen idk why

**Comment by its-suun** [comment]
that should happen when a lua error happens while rendering. if thats the case you could give the gpu code and the lua errors from the console?

**Comment by hawk0484** [comment]
There is no error in the console whilst the flickering is happening, everything that isnt props or map such as the held weapon flickers in and out of existance see:
![hl2_2017-07-25_19-49-43](https://user-images.githubusercontent.com/10554383/28588480-a385909c-7172-11e7-9500-18779c0526f6.jpg)
![hl2_2017-07-25_19-50-00](https://user-images.githubusercontent.com/10554383/28588481-a38bcda4-7172-11e7-8d7e-f8b47c595311.jpg)

**Comment by hawk0484** [comment]
my mistake the latest version of the git works, i was using workshop version forgot to delete the workshop file, will probably want to update that when possible
