### ISSUE TITLE
How can I turn odd tick quota or detect touched object

### ISSUE THREAD

**Issue by Mateu15** [wiremod/wire#1437]
Hi, I writed detecting touched object on EGP.
```PHP
function number getTouch(App)
{
IsTrue=0
Currs = Egp:egpCursor(Usr)
Obb = Egp:egpNumObjects()
Iri=0
while(Iri<Obb){
Sptt=StOnt[App,string]:explode(",")
local MinX=Sptt[1,string]:toNumber()
local MinY=Sptt[2,string]:toNumber()
local MaxX=Sptt[3,string]:toNumber()
local MaxY=Sptt[4,string]:toNumber()
if(inrange(Currs,vec2(MinX,MinY),vec2(MaxX,MaxY))){local IsTrue=Iri}
}
if(IsTrue!=0){
return Iri
}
}
```
StOnt is array with objects. Sptt is max and min pos and size.
This generates tick quota error. Please help. Can this optimize or turn off tick quota? Or set higher tick quota limit???
Regrads

**Comment by AbigailBuccaneer** [comment]
This generates a tick quota error because it's an infinite loop: `Iri` is never modified in the `while` loop, so it never terminates until it uses up the tick quota and gets terminated.

**Comment by Divran** [comment]
This github is for bugs and issues with the Lua code of Wiremod, not for asking for help on how to use it. The correct place to ask those questions would be on the reddit or on discord. The discord channel is far more active than the reddit page however.

I suggest you go to the Discord channel where there are many experienced E2 coders available to help you. https://discord.gg/cqJ45CT
