### ISSUE TITLE
E2: Cannot set materials

### ISSUE THREAD

**Issue by hawk0484** [wiremod/wire#1441]
Cannot set materials on holograms using holoMaterial
Cannot set materials on props using setMaterial
Extends to materials even those specific to gmod like shadertests and the debug materials
![image](https://user-images.githubusercontent.com/10554383/28742665-e4c5f96c-742d-11e7-8f35-61f0795009ce.png)

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/pull/1439

**Comment by Divran** [comment]
Fixed by #1439
