### ISSUE TITLE
multiple names in SteamID Filter / Name Filter for target finder

### ISSUE THREAD

**Issue by alex65j** [wiremod/wire#1456]
When using the target finder with loads of people. I've had to find a way around it but people whole are using wiremod and are not experienced, find it hard to work with it also the way around it can sometimes cause lag on big servers. #suggestion #fix #easier

**Comment by Divran** [comment]
It's true that the target finder could benefit from a complete rewrite to add some more useful features. Unfortunately, most of the wire devs have more important irl things to do, so mostly it's just me merging some PRs now. Also I fix bugs when they are found. This is a case of "when I have the time and am bored, I'll do it", which could be tomorrow, or never, who knows

**Comment by alex65j** [comment]
sorry i have not replied just side it and forgot to reply. ok and thankyou for responding
