### ISSUE TITLE
Timers breaks after recreating

### ISSUE THREAD

**Issue by CornerPin** [wiremod/wire#1459]
E2 timer does not run if it was created, stopped and recreated in one execution clk. The code below should print 1 every second, but it only prints it two times.
```
timer( "second", 1000 )
stoptimer( "second" )
timer( "second", 1000 )

print( 1 )
```
After executing, the timer still is in the E2 timers table
![image](https://user-images.githubusercontent.com/7669876/29346250-9adb7606-824c-11e7-9f5c-af797d1c6e86.png)

**Comment by Divran** [comment]
E2 timers directly use gmod's timer library so if they don't work then that means gmod's timers don't work either.

**Comment by CornerPin** [comment]
I am writing E2 library that makes timers more Lua-like. When i'm trying to adjust the timer in it's callback, bug occurs.
```
@name Timer library test

if( first() ){
    #include "lib/timers"
    
    function void myTimer(){
        timerAdjust( "test", 1000, 5, "myTimer" )
        print( 1 )
    }
    
    timerCreate( "test", 1000, 5, "myTimer" )
}

checkTimers()
```
**checkTimers** checks if the chip was triggered by timer, repeats this timer if it should be repeated again (runs timer( name, delay )) and runs timer callback. **timerAdjust** uses **timerCreate** to reconfigure the timer, and in it's body it uses stoptimer( name ) and timer( name, delay ) to reset timer, if it exists, and create new one. This sequence leads to this bug and that's how i found it.

**Comment by Divran** [comment]
Yes well as I said, if you were to actually use the real `timer.Remove` and `timer.Create` to remove a timer and create a new one in plain gmod lua, you would have the exact same issue. Also, E2's `timer` function already does the adjusting for you - see the code I linked above. So you don't have to remove the timer first. Just restart it.
