### ISSUE TITLE
Wire Ranger Breaks when you disable the Ranger E2 extension.

### ISSUE THREAD

**Issue by SlipwayServers** [wiremod/wire#1461]
Disable the Ranger E2 Extension (I'm doing this in the Q admin menu) and restart (I'm doing this on a dedi if it matters) and this is what happens.

```
attempted to use tool "wire_ranger"
used the tool wire_ranger on maps/rp_world_kdg.bsp

[ERROR] addons/____________wire-master/lua/wire/server/wirelib.lua:257: attempt to index a nil value
  1. AdjustSpecialOutputs - addons/____________wire-master/lua/wire/server/wirelib.lua:257
   2. Setup - addons/____________wire-master/lua/entities/gmod_wire_ranger.lua:101
    3. MakeWireEnt - addons/____________wire-master/lua/wire/server/wirelib.lua:1047
     4. MakeEnt - addons/____________wire-master/lua/wire/tool_loader.lua:65
      5. LeftClick_Make - addons/____________wire-master/lua/wire/tool_loader.lua:56
       6. LeftClick - addons/____________wire-master/lua/wire/tool_loader.lua:37
        7. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:227
```

I then turn the ranger extension back on and wait a few seconds for it to reload, then Rangers work again. 

```
> Calling destructors for all Expression 2 chips.
> Reloading Expression 2 extensions.
> Calling constructors for all Expression 2 chips.
> Done reloading Expression 2 extensions.
> attempted to use tool "wire_ranger"
> used the tool wire_ranger on maps/rp_world_kdg.bsp
> attempted to use tool "wire_ranger"
> used the tool wire_ranger on maps/rp_world_kdg.bsp
```

When they "dont" work, they appear, but you cannot press Z to remove them, and walking into them makes them fall to the ground regardless of settings. Every other ent that we allow on the server works fine with all E2 extensions turned off, except for the Ranger.

I'm not sure if this is intended behaviour, as I would expect a Ranger to work without E2 extensions turned on.

**Comment by Divran** [comment]
I checked the code and there's nothing in it that makes it rely on E2 at all. You could delete E2 completely and it would still work.

**Comment by bigdogmat** [comment]
> I checked the code and there's nothing in it that makes it rely on E2 at all. You could delete E2 completely and it would still work.

It relies on the ranger data type which is created by E2. By default there're only these data types,
https://github.com/wiremod/wire/blob/b534c97637ebb1c2445cdff9ab47e7793703ca3b/lua/wire/server/wirelib.lua#L72-L108

The ranger one is added when the type is registered in E2 here,
https://github.com/wiremod/wire/blob/f374d5bbcef78667aaf4a985f50a9553e3c98112/lua/entities/gmod_wire_expression2/core/init.lua#L110-L116

**Comment by Divran** [comment]
yep, I already edited my post
