### ISSUE TITLE
PNG's don't work with particle()

### ISSUE THREAD

**Issue by 343N** [wiremod/wire#1462]
You can't use a png file with Particles unlike other textures. 
Not sure if a bug with particle() or something greater.

Specs incase it matters:
- Windows 10 b1703 64-bit
- i5 3570k
- GTX 1060

**Comment by Divran** [comment]
what

**Comment by Divran** [comment]
You realize there is nothing in wiremod that allows you to create particles right

**Comment by thegrb93** [comment]
e2 extension I think

**Comment by 343N** [comment]
I was told it was apart of core wiremod, nevermind
