### ISSUE TITLE
lua/entities/gmod_wire_expression2/base/compiler.lua:185: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by maksview** [wiremod/wire#1463]
Internal error - please report to https://github.com/wiremod/wire/issues
lua/entities/gmod_wire_expression2/base/compiler.lua:185: attempt to concatenate a nil value

Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 308	"__concat"		lua/entities/gmod_wire_expression2/core/e2lib.lua
	3: Line 185	"GetOperator"		lua/entities/gmod_wire_expression2/base/compiler.lua
	4: Line 582	"nil"		lua/entities/gmod_wire_expression2/base/compiler.lua
	5: Line 153	"EvaluateStatement"		lua/entities/gmod_wire_expression2/base/compiler.lua
	6: Line 160	"Evaluate"		lua/entities/gmod_wire_expression2/base/compiler.lua
	7: Line 403	"nil"		lua/entities/gmod_wire_expression2/base/compiler.lua
	8: Line 153	"EvaluateStatement"		lua/entities/gmod_wire_expression2/base/compiler.lua
	9: Line 160	"Evaluate"		lua/entities/gmod_wire_expression2/base/compiler.lua
	10: Line 443	"nil"		lua/entities/gmod_wire_expression2/base/compiler.lua
	11: Line 153	"EvaluateStatement"		lua/entities/gmod_wire_expression2/base/compiler.lua
	12: Line 160	"Evaluate"		lua/entities/gmod_wire_expression2/base/compiler.lua
	13: Line 443	"nil"		lua/entities/gmod_wire_expression2/base/compiler.lua
	14: Line 153	"EvaluateStatement"		lua/entities/gmod_wire_expression2/base/compiler.lua
	15: Line 160	"Evaluate"		lua/entities/gmod_wire_expression2/base/compiler.lua
	16: Line 403	"nil"		lua/entities/gmod_wire_expression2/base/compiler.lua
	17: Line 153	"EvaluateStatement"		lua/entities/gmod_wire_expression2/base/compiler.lua
	18: Line 287	"nil"		lua/entities/gmod_wire_expression2/base/compiler.lua
	19: Line 57	"nil"		lua/entities/gmod_wire_expression2/base/compiler.lua
	20: C function	"Execute"
	21: Line 74	"wire_expression2_validate"		lua/entities/gmod_wire_expression2/cl_init.lua
	22: Line 1589	"Validate"		lua/wire/client/text_editor/wire_expression2_editor.lua
	23: Line 1837	"Close"		lua/wire/client/text_editor/wire_expression2_editor.lua
	24: Line 827	"DoClick"		lua/wire/client/text_editor/wire_expression2_editor.lua
	25: Line 232	"nil"		lua/vgui/dlabel.lua

**Comment by Divran** [comment]
Please post the E2 code you were using when you received this error. If you don't want to share it publicly, then write a small snippet that also reproduces the error and post that instead.
