### ISSUE TITLE
EGP v3 stucked on its logo after game restart

### ISSUE THREAD

**Issue by NaveNO** [wiremod/wire#1465]
Hello. I have a basic connection between E2 chip and EGP v3 screen. It works okey always(I mean E2 chip is showing text, boxes, color correctly), until I save the world and restart a game. When I load the game from save, EGP screen shows its logotype. When I go to my E2 chip and press "Upload & save", it does nothing. I have to remove old screen and place new one, then connect E2 chip again to screen. How can I prevent it? 
Code: no code, course it happend even with basic code.

**Comment by Divran** [comment]
None of the entities in wiremod are made to handle being saved. They are
meant to be used with advanced duplicator. We've never taken the time and
effort required to support saves because very few people use them. Just use
advdupe instead and it'll work

**Comment by NaveNO** [comment]
Thanks for info.
