### ISSUE TITLE
E2 Ops Settings

### ISSUE THREAD

**Issue by Minisoft321** [wiremod/wire#1469]
Hello

Am i the only one that can't apply OPS settings in the server console
i try to apply these 
```
wire_expression2_quotahard 6000
wire_expression2_quotasoft 5000
wire_expression2_quotatick 8000
```
but they dont register this will make the E2 crash at 500 ops but when i place it in 
server.cfg and autoexec.cfg

i know they dont apply cuz the highest ops before it crashes is 10000 atm
Any other way i can change it?

**Comment by AbigailBuccaneer** [comment]
Can you update other wire server settings from the same place? (Can you give an example of one that works okay?)

**Comment by Nebual** [comment]
Can't reproduce
