### ISSUE TITLE
the wire thruster effects

### ISSUE THREAD

**Issue by Comradevadim** [wiremod/wire#1492]
the jet flame effect and others that use the same effect looks like this when its on : http://steamcommunity.com/sharedfiles/filedetails/?id=1168057294

**Comment by AbigailBuccaneer** [comment]
![image](https://user-images.githubusercontent.com/908758/35778630-c6a0b56e-09b8-11e8-9c18-82b22ac4367f.png)

They all work for me - this is likely a graphics card issue. Are you definitely on the latest version of Wiremod and Garry's Mod and your graphics drivers? What graphics card are you using?

**Comment by AbigailBuccaneer** [comment]
I'll reopen when you respond.
