### ISSUE TITLE
Add static function support for E2

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#1496]
E2 functions are *dynamic* - they can be defined at and redefined at runtime based on arbitrary conditions:

```PHP
if (Verbose) {
    function log(Message: string) { print(Message); }
} else {
    function log(Message: string) {}
}
```

Because of this, defining functions at top level scope has a performance penalty, so functions which should be effectively top-level functions are often written as such:

```PHP
if (first() | duped()) {
    function log(Message: string) { print(Message); }
}
```

It would be convenient if functions could be marked *static* - that is, globally available and unchanging. This would aid the compiler and type checker, the syntax highlighter, and would make for cleaner code.

Two suggestions for the syntax for this are as follows:

## `@function`

```PHP
@function log(Message: string) { print(Message); }
```

`@function` could be a new compiler directive, intended as a drop-in replacement for the `function` keyword to mark a function static. This would be fully backwards compatible, and using the syntax for compiler directives makes it clear that it can only appear at the top level and doesn't do anything at runtime. It's a little bit opaque and confusing, and would break the convention that compiler directives are expected only at the top of files.

## `static function`

```PHP
static function log(Message: string) { print(Message); }
```

`static` could be a new keyword that must be followed by a function definition. This isn't fully backwards compatible (as `static` could be the name of a function at the moment), but should involve fairly minimal extension to the parser, and is more googleable.

**Comment by AbigailBuccaneer** [comment]
Other things we could look at:

* Reducing the overhead of redefining a function (so nobody writes `if (first() | duped()) { ... }`)
* Adding special case handling for a function which is defined at the top level and whose name is never redefined anywhere else
* Throwing E2 in the bin and starting on E3

**Comment by oldmud0** [comment]
I'd be in support for the `@function` keyword, as `static function` gives the impression that E2 is more similar to Java or ECMAScript than it really is.

However, this new syntax does not fix the root problem: performance issues from top-level redefinition. Could it be determined at runtime whether or not a function is intentionally being redefined (never seen any E2 that does this) or if it is unintentionally being redefined as a result of some kind of top-level trigger?

**Comment by AbigailBuccaneer** [comment]
> I'd be in support for the `@function` keyword, as `static function` gives the impression that E2 is more similar to Java or ECMAScript than it really is.

You're right that 'static' is a heavily-loaded term in lots of different languages. For what it's worth, as a primarily C++ developer, I read `static function ...` as being about linkage rather than OOP, which is just a different thing to get it confused with.

You're also right about this being a band-aid over a bigger issue, and the more I think about it the more I'm inclined to go with one of my previous bullet points. Complicating the language for performance's sake is probably not a good idea.

**Comment by AbigailBuccaneer** [comment]
> I'd be in support for the `@function` keyword, as `static function` gives the impression that E2 is more similar to Java or ECMAScript than it really is.

You're right that 'static' is a heavily-loaded term in lots of different languages. For what it's worth, as a primarily C++ developer, I read `static function ...` as being about linkage rather than OOP, which is just a different thing to get it confused with.

You're also right about this being a band-aid over a bigger issue, and the more I think about it the more I'm inclined to go with one of my previous bullet points. Complicating the language for performance's sake is probably not a good idea.

**Comment by AbigailBuccaneer** [comment]
One approach that could be taken based on #1497 is that we could rewrite top-level functions to be surrounded by an `if (first() | duped())` block if they're never redefined anywhere. I can't tell if that's a terrible idea or not.

**Comment by Divran** [comment]
Nah in that case it would be better to just delete delete the function definitions from the compiled code (if possible, or something similar) so that that part of the code is never ran again.

**Comment by AbigailBuccaneer** [comment]
Static functions make sense as an implementation detail, but exposing that to the user isn't necessary.

**Comment by Vurv78** [comment]
Worth posting here that this is now default behavior for functions on `@strict`.
