### ISSUE TITLE
I don't know what's wrong but it pisses me off

### ISSUE THREAD

**Issue by Gaaraofthesand** [wiremod/wire#1501]
This keeps happening

http://www.mediafire.com/file/lq65tj787t6dm0w/wow.gif

Couldn't post it, so I put it on mediafire

plus these are my addons

![20171222135133_1](https://user-images.githubusercontent.com/15252459/34309304-430114ee-e71f-11e7-9950-5a2b30898c57.jpg)

**Comment by AbigailBuccaneer** [comment]
First off: the `wow.gif` file is actually an an MPEG-4 file, which explains why you can't post it here. (Did you rename it from `wow.mp4` to `wow.gif` to try and bypass GitHub's file upload restrictions?)

Secondly, it's totally unclear what you're trying to accomplish. I think you've misunderstood the purpose of the Wire User. The user has an input and the turret has an input, and you can't wire an input to an input. To do what I think you're trying to do, you'd probably want a Wire Ranger (with the "Output UniqueID" option enabled, which should output a value that's not 0 whenever the beam is hitting a player), and then you can wire the turret's input to the ranger's output.

**Comment by Divran** [comment]
Also the github is for issues/bugs with wire, not for help using it. For
quicker help in the future, go to our discord server instead. The link is
available on http://wiremod.com
