### ISSUE TITLE
Camcontroller net.Send usage

### ISSUE THREAD

**Issue by roboderpy** [wiremod/wire#1510]
![not good](https://dbot.serealia.ca/public/mugek/screens/hl2_2018-01-11_20-17-02.png)

**Comment by CornerPin** [comment]
Are you on dev branch? Might be https://github.com/Facepunch/garrysmod-issues/issues/3361#issuecomment-356250815.

**Comment by roboderpy** [comment]
It is my own implantation on network library (on lua level) 

You pass NULL to net.Send

**Comment by Divran** [comment]
Then fix your code

**Comment by roboderpy** [comment]
How can i fix passing NULL Entity by Wiremod to net.Send

**Comment by Divran** [comment]
How should I know it's your code

**Comment by roboderpy** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_cameracontroller.lua#L411

ply is NULL

**Comment by roboderpy** [comment]
And this is another gmod design mistake. net.Send throws `Tried to use a NULL Entity! ` if no arguments were passed at all, or it got an empty table. It is supposted to error on `net.Send(NULL)` but it just fails silently. This is not exactly an issue but in future your code could break.

**Comment by Divran** [comment]
How do I reproduce this? I just tried sitting in a chair that I had duped and then pressing undo, but it did send valid values into net.Send.

**Comment by roboderpy** [comment]
Just add a check, it looks like heisenbug
```lua
function ENT:SyncSettings( ply, active )
	if active == nil then active = self.Active end
	if not IsValid(ply) and #self.Players == 0 then return end
	net.Start( "wire_camera_controller_toggle" )
	net.WriteBit( active )
	net.WriteEntity( self )
	if self.Active then
		net.WriteBit( self.ParentLocal )
		net.WriteBit( self.AutoMove )
		net.WriteBit( self.LocalMove )
		net.WriteBit( self.AllowZoom )
		net.WriteBit( self.AutoUnclip )
		net.WriteBit( self.AutoUnclip_IgnoreWater )
		net.WriteBit( self.DrawPlayer )
		net.WriteBit( self.DrawParent )
		SendPositions( self.Position, self.Angle, self.Distance, self.Parent )
	end
	net.Send(ply or self.Players )
end
```

**Comment by roboderpy** [comment]
@Divran **all** functions called has checks whatever `ply` is valid but `SyncSettings`
![checks](https://i.dbot.serealia.ca/2018/01/aee12bf261_Code%20-%20Insiders_2018-01-13_09-47-26.png)
![checks](https://i.dbot.serealia.ca/2018/01/31874ca504_Code%20-%20Insiders_2018-01-13_09-48-11.png)
![checks](https://i.dbot.serealia.ca/2018/01/d961ad4bab_Code%20-%20Insiders_2018-01-13_09-48-31.png)

and SyncSettings without checks
![problem](https://i.dbot.serealia.ca/2018/01/9de061aa70_Code%20-%20Insiders_2018-01-13_09-49-08.png)

With check is code in post above

**Comment by Divran** [comment]
Ok I think this error might happen if the person who spawned the cam controller has left the server, and then someone else sits in the chair, and then the cam controller is deleted.
