### ISSUE TITLE
E2 editor copy/paste not working with keyboard commands

### ISSUE THREAD

**Issue by Anonymous1157** [wiremod/wire#1512]
**How to reproduce:**
1. Open the E2 editor.
2. Select text using shift+arrows/home/end. Ctrl+C.
3. Move the cursor somewhere else. Ctrl+V.

What's supposed to happen is that the text I selected and copied is pasted in the new location. What happens instead is that a short string of random garbage characters ("??D?" or "?q" or invalid character squares) is pasted.

Using the mouse to select text, using Ctrl+C to copy it, then using Ctrl+V to paste it works fine. Using the keyboard to select text, using Ctrl+C to copy it, then pasting with the right-click menu also works fine. Entirely using the mouse is fine as well. **The only combination of steps to copy and paste text that's NOT working is purely using the keyboard.**

I'm playing on Linux with up-to-date Wiremod from git. I've heard of this issue happening for at least one other Linux user in Wiremod and happening in the exact same way in at least one other mod (GCompute) but I don't know (and don't think this implies) whether it's an upstream problem in GMod or if both this and that mod have a bug.

**Comment by adosikas** [comment]
Rightclick->Paste doesn't use the clipboard (instead on internal self.clipboard variable), so it working here is kinda a bug in it self.

**Comment by Nebual** [comment]
Resolved by #1513 (I hope)

**Comment by Anonymous1157** [comment]
Confirmed working now! Thanks!
