### ISSUE TITLE
Prevent the setting of malicious materials on Holograms

### ISSUE THREAD

**Issue by brandonsturgeon** [wiremod/wire#1543]
Recently there has been a bout of malicious E2 activity on my server and I'd like to submit a report for it.

Holograms can be set to materials which will crash all clients that see it. I only know of one of these materials right now, but I know that there are others.

Malicious users will use `holoVisible` to only allow their targeted player to see the hologram, which will lag, and subsequently crash the client's game. 

I'm happy to disclose the material I know of with any of the wiremod team that would like to discuss in private.

steamcommunity.com/id/Phatso727

Thanks!

**Comment by Divran** [comment]
we've got this blacklist here https://github.com/wiremod/wire/blob/master/lua/wire/server/wirelib.lua#L1192 and we could easily add more to it

**Comment by brandonsturgeon** [comment]
I'll message you on steam with the material. Thanks!

**Comment by oldmud0** [comment]
I mean it doesn't matter, everyone can see what the material is when it's added.

**Comment by brandonsturgeon** [comment]
@oldmud0 I suppose, but there's still time between a PR, a Merge, push to workshop, and servers updating. Still a good amount of time for someone to abuse it.
