### ISSUE TITLE
Improve runOnKeys by adding key filters

### ISSUE THREAD

**Issue by Divran** [wiremod/wire#1549]
Proposal to add a new function called `runOnKeys(Ply:entity,OnOff:number,Filter:array)` where the filter is a sequential array of letters. This filter would be applied to that player only. If the old function `runOnKeys(Ply,N)` is ran later, the filter is unchanged (this is to allow toggling on/off without modifying the filter). To remove the filter and set it back to the "every key" default, you'd call it with an empty array.

I've been telling myself that I'd add this for several weeks but never seem to find the time. I'll try again this weekend but we'll see.

As a side note, it has been suggested to allow `runOnKeys` to work even after a player disconnects and reconnects.

**Comment by AbigailBuccaneer** [comment]
Is it possible to check bindable keys like `IN_USE` with `runOnKeys`, or only keys like `KEY_F`?

**Comment by Divran** [comment]
It uses this hook http://wiki.garrysmod.com/page/GM/PlayerButtonDown which uses http://wiki.garrysmod.com/page/Enums/BUTTON_CODE these buttons

**Comment by AbigailBuccaneer** [comment]
Okay, so it's not possible to use `runOnKeys` to implement `runOnUse`.

**Comment by Divran** [comment]
True, if the user has changed the bind. But if they haven't then it is.

**Comment by Divran** [comment]
Actually you can probably check E:keyUse() inside the runOnKeys event but then you can't use filters if you want to catch rebinds

**Comment by Divran** [comment]
Unfortunately there appears to be no way to get which key a bind is bound to on the server, which means it's very hard to make both hooks trigger the same E2 execution, and have the keys line up. For example, without any additional checks, if I press W and D at the same time, it'll be reported inside the E2 as being `W=moveright` and `D=forward` pretty much half the time. This must be because the key/bind pressed hooks are only triggered once per X amount of miliseconds, so if you press two keys at the same time during this period, then there's no way to tell which one was pressed first.

I've written some code which tries to "learn" which key corresponds to which bind, so that it can later filter out those misfires, but this is more of a hack than a solution really.

In any case, we're ditching `runOnUse`. Then, the question is: do we want to add `runOnBind`? We can already sort of do this by not using any filter on `runOnKeys` and then checking `E:keyUse(), E:keyAttack(), etc` to see if the user pressed those binds. But 95% of the time, people are gonna have use bound to E, so most people will probably check that.

**Comment by CaptainPRICE** [comment]
Inconsistency the way it be?
p.s. I don't like this idea. Just to be clear, it just stinks. I prefer a separate hook/function set for "use" (#1523).

**Comment by Divran** [comment]
@CaptainPRICE that use hook is pointless because it only works on the e2 entity itself. The stuff I've written in this issue is a bit out of date. All of the issues have already been solved and the way it works is seamless now.
