### ISSUE TITLE
HTTP executing every owned E2

### ISSUE THREAD

**Issue by bigdogmat** [wiremod/wire#1554]
Whenever an HTTP request is finished every E2 you own that has `runOnHTTP` will be executed with the results. Looking at the code it looks like this was intended, 

https://github.com/wiremod/wire/blob/088d7cddfbfe6fa20043f4fe2f77fec0e4003e4e/lua/entities/gmod_wire_expression2/core/http.lua#L49-L53

Should it work like this?

**Comment by Divran** [comment]
yeah I've noticed this as well. idk if changing it will break someone's E2 but I doubt it. Obviously only the E2 that requested the data should run. I'd be alright with changing it

**Comment by Anticept** [comment]
Is any of this http data being cached anywhere for all of them to access? If so, I am curious if that was done to prevent E2s from slamming a resource.

**Comment by bigdogmat** [comment]
I doubt it, the alternate to this _feature_ would be to pass the data yourself (e.g. datasignals), or to request it on the other E2(s). Requests are limited to 1 every 3 seconds per player.

**Comment by Divran** [comment]
Datasignals are the correct way imo
