### ISSUE TITLE
Thruster "Force Minimum" setting misleading

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#1556]
It actually acts as "Input Minimum" (like a deadzone on a joystick), the input needs to be *greater* than this value to trigger the thruster.
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_thruster.lua#L204

This affects the vector thruster as well.

Possible fixes:

* Change code to value*force>force_min to match name (although Threshold would fit better than minimum)
* Change it to act as bound for reverse thrust (if bidirectional is enabled), better matches current name
* Rename it to match the code (Input Minimum/Deadzone), and allow decimals (currently none, see https://github.com/wiremod/wire/blob/master/lua/wire/stools/thruster.lua#L148)

**Comment by AbigailBuccaneer** [comment]
I think renaming it (to something involving the word Deadzone or Threshold) is the way forward - changing what it does just because it's misleadingly named doesn't make a lot of sense to me.

**Comment by adosikas** [comment]
"Force Threshold" or "Input force" isn't really much clearer either, because force isn't used in the calculation, just the input (which acts as additional multiplier).

"Input threshold" would be best in this case.

**Comment by georgeravenholm** [comment]
is there really a point to having a limit like this in the first place? i think if people needed to limit the thrust they could put it in their e2 or use a range gate

i think just having a multiplier and no limits in the tool is the way to go

**Comment by AbigailBuccaneer** [comment]
@georgeravenholm if somebody proposed this today then I'd probably tell them that there's no point in having a limit like this in the first place, because it's easy to implement yourself with gates or E2. But it already exists, and Wiremod has over a million and a half subscribers, so backwards compatibility's not something we can easily break.
