### ISSUE TITLE
Calculate string

### ISSUE THREAD

**Issue by Mateu15** [wiremod/wire#1560]
Hi,
How can I make calculate number from string. Number = some_function("(3+2)*2") and returns 10. Must I use loop and calculate string by parts? Or what function I must use.
Regrads

**Comment by bigdogmat** [comment]
These kind of questions should be asked on the wiremod discord or reddit, you can find a link to them at http://wiremod.com/.

As a short answer, you can't. You could try to use the remote upload extension to upload that string to an E2 and have it send back the answer. Another possible way would be to create a full on calculator within E2. To go further in detail go to either of the places I listed above.
