### ISSUE TITLE
Can't open up my E2 Menu

### ISSUE THREAD

**Issue by Homelessmanwithasword** [wiremod/wire#1563]
So I am playing offline for now and everytime I open up my E2 and only E2 section it shows nothing below the e2 models and gives a script error saying attempt to index field Preprocessor (a nil value)

**Comment by AbigailBuccaneer** [comment]
Are there any errors printed to the console?

**Comment by Homelessmanwithasword** [comment]
Yeah there is I have a picture of it and I left what it said in the issue but I don't know how to insert photos on these pages

**Comment by Divran** [comment]
`but I don't know how to insert photos on these pages` drag and drop the picture into the text box

**Comment by Homelessmanwithasword** [comment]
Well I'm on mobile but I could try and give an in depth description of what it says

**Comment by Homelessmanwithasword** [comment]
![img_20180210_111332](https://user-images.githubusercontent.com/36338075/36075185-c6032cba-0f10-11e8-8608-f108c717efc9.jpg)
I fixed it my switching to desktop mode but here it is.  I think it might be because I'm offline.  Idk

**Comment by Divran** [comment]
There's another error above it which we can't see because you didn't send the whole screen

**Comment by Homelessmanwithasword** [comment]
![img_20180211_095959](https://user-images.githubusercontent.com/36338075/36075284-5e26a49e-0f12-11e8-8247-e88abeb64f68.jpg)
I hope this helps

**Comment by Homelessmanwithasword** [comment]
Well I guess there hasn't been any solves yet

**Comment by bigdogmat** [comment]
Are there any errors in console from when the server started up? If not have you tried a reinstall?

**Comment by Homelessmanwithasword** [comment]
I can't reinstall because I've been using steam offline mode for the past week. But here's something
![img_20180211_164212](https://user-images.githubusercontent.com/36338075/36079616-b0222a7e-0f4a-11e8-8b4e-b9932ec7203f.jpg)

**Comment by oldmud0** [comment]
Sorry, that's unreadable. Can you try to take a screenshot again?

**Comment by Homelessmanwithasword** [comment]
I'm gonna wait until tomorrow because I get internet tomorrow.  I will post the status

**Comment by Homelessmanwithasword** [comment]
![img_20180211_202650](https://user-images.githubusercontent.com/36338075/36081906-f97273a4-0f69-11e8-9135-80bfcc9a31ce.jpg)

**Comment by oldmud0** [comment]
Partially transcribed to save your eyes:
```
Couldn't include file 'include\modules\glon.lua' (File not found) (<nowhere>)
Making workshop map available for client download
Unknown command 'sv_tags'
Using map cycle cfg_mapcycle.txt.
KeyValues Errors RecursiveLoadFromBuffer:  got } in key in file scripts/soundscapes_gm_?????.txt
???.crickets,  ambient\levels\saves\cave_crickets_loop1.wav, ("playlooping"), ("????"), ("???????"),
Unable to load sprite material materials/cable/cable_m????.???
Nav file is missing or something (1)
?ClientSteamContext OnSteamServerConnectFailure logged on = 0
```
There's nothing important on this part, it's just map load errors.

**Comment by AbigailBuccaneer** [comment]
@Homelessmanwithasword disable everything except Wiremod, and make sure the version of Wiremod you're using is recent (either the latest Git `master` version, or the Workshop version). There are errors from unrelated addons and it's hard to tell what's causing the error because of it.

**Comment by Homelessmanwithasword** [comment]
It might not be updated to the recent version because I have had no internet and playing offline for 12 days but today I get internet.  So I'm gonna try it out

**Comment by Homelessmanwithasword** [comment]
God dangit I'm sick of this I have gone 3 weeks without internet I'm tired of not being able to do anything. This isn't gonna work out for me.  Thanks for the help

**Comment by Divran** [comment]
If you still don't have internet you can try just moving all addons except wiremod out of the addons folder. Put them in a folder on your desktop or something. Also make sure you do this to the workshop addons as well. Then open gmod with only wiremod and see if the error still happens. If not, then that means one of your addons broke it.

**Comment by Homelessmanwithasword** [comment]
If I move them out of my folder and start gmod they won't be there right? And if I move them back they would get back onto gmod?

**Comment by Divran** [comment]
yes, only things in the addons folder are loaded

**Comment by Homelessmanwithasword** [comment]
Well I disabled  wiremod and re-enabled  it.  This is what I got
![img_20180213_163522](https://user-images.githubusercontent.com/36338075/36177706-2cb07586-10dc-11e8-9880-416693413456.jpg)

**Comment by Homelessmanwithasword** [comment]
I GOT IT TOO WORK but only with no add-ons and only wiremod...

**Comment by Homelessmanwithasword** [comment]
Guys thank you s<ooooo much for all of your help.  I've gotten it to work by minimizingbsome of the add-ons I use

**Comment by Divran** [comment]
>I GOT IT TOO WORK but only with no add-ons and only wiremod...

yes this is what we said, one of your addons is breaking it
only way to find out which one it is, is to add them back one by one until it breaks again
