### ISSUE TITLE
Holos using dangerous models

### ISSUE THREAD

**Issue by brandonsturgeon** [wiremod/wire#1566]
Hi,

I submitted a PR which restricted a known dangerous model from E2 Holo's.

However, there are many others. This is why I'm making an issue today - to talk about how we can handle this.

I currently know of two more props which will cause client crashes if set as holograms, but they're both part of a popular 3rd party addon.
As a programmer, it doesn't make sense to add restrictions in Wiremod for props outside of the vanilla Gmod scope.
On the other hand, as a server owner, there's no way for me to prevent troublemakers from crashing clients without restricting E2 from them.

Does anyone have any ideas?

**Comment by Divran** [comment]
if you want you could do this
```lua
hook.Add("InitPostEntity","block holo models",function()
	local holo = scripted_ents.Get( "gmod_wire_hologram" )
	local old = holo.SetModel -- get existing setmodel function
	local blacklist = { -- create blacklist
		["path/to/model.mdl"] = true,
		["path/to/other/model.mdl"] = true,
		-- ... and so on
	}
	function holo.SetModel(self,path) -- override normal setmodel function
		if blacklist[path] then return end -- if blacklisted, don't allow it
		old(self,path) -- allow it
	end
end)
```

**Comment by AbigailBuccaneer** [comment]
[`WireLib.CanModel(player, model, skin)`](https://github.com/wiremod/wire/blob/63b4b10e867ba16b1383f70d05ac83a710213126/lua/wire/server/wirelib.lua#L1026) already exists. It calls the [`PlayerSpawnObject(player, model, skin)`](http://wiki.garrysmod.com/page/SANDBOX/PlayerSpawnObject) hook, so servers can blacklist spawning those objects. Assuming the holo library does properly call this function, then your server can add a custom hook to prevent those materials:

```Lua
local blacklist = { -- create blacklist
	["path/to/model.mdl"] = false,
	["path/to/other/model.mdl"] = false,
	-- ... and so on
}
hook.Add("PlayerSpawnObject", "block holo models", function(_, model) return blacklist[model] end)
```

**Comment by AbigailBuccaneer** [comment]
It looks like `hologram.lua` does correctly use `WireLib.CanModel` (via the `GetModel` wrapper), unless `wire_holograms_modelany == 2` in which case all bets are off anyway (ie. you allow an infinite set of potentially client-crashing models).

**Comment by Divran** [comment]
ah yeah true that's a better way
