### ISSUE TITLE
Enter Key Not Recognized

### ISSUE THREAD

**Issue by CryptAlchemy** [wiremod/wire#1569]
The keyboard's enter key is not recognized. I double-checked this by wiring a text screen to the key output; all other keys worked while the enter key just froze/unfroze when I had my physgun out. Please fix this :)

**Comment by AbigailBuccaneer** [comment]
What layout is your physical keyboard, what keyboard layout setting have you are you using (in the Wire Keyboard c-menu), and which enter key do you mean (the one to the right of the letter keys, or the one to the right of the numpad)? It works fine for me.

**Comment by CryptAlchemy** [comment]
My keyboard layout is US.
I'm using the American C-menu setting.
I'm using the main Enter key, and not the numpad enter key.

**Comment by AbigailBuccaneer** [comment]
Hmm. Does this setting affect anything?
![image](https://user-images.githubusercontent.com/908758/36401110-2353c09c-15cd-11e8-86ea-65b381f986b7.png)
If not, somebody with a US keyboard will have to investigate, as I suspect this is layout-specific.

**Comment by CryptAlchemy** [comment]
I attempted to toggle the button with no success. I'll try a few other things to see if they work.

**Comment by CryptAlchemy** [comment]
Okay, I've tried it on singleplayer and on servers; I get the same result.
A friend of mine has the same issue as I do.

**Comment by Divran** [comment]
Make an E2 with only this in it `@inputs A
print(A); ` then wire it to the memory output of the keyboard then press
enter and tell us what it says

**Comment by CryptAlchemy** [comment]
I've tried this and it says the following in console.

10	
0

**Comment by Divran** [comment]
Check the checkbox shown in the image in a previous post. There is also another checkbox which I can't remember the title of which locks input. Enable that too. Then left click the keyboard to update it with these new settings and you're done

**Comment by CryptAlchemy** [comment]
I reinstalled Gmod and it started working.

Thanks for the help guys!
