### ISSUE TITLE
Timer not executed if stop and call it twice in its run

### ISSUE THREAD

**Issue by AlexALX** [wiremod/wire#1578]
Ok so basically timer won't execute second time if use this code:

```lua
@name Timer bug?

if (first()) {
    timer("test",1)    
}

if (clk("test")) {
    print("test timer")
    stoptimer("test")
    timer("test",1)
    stoptimer("test")
    timer("test",1)
}
```

It will only run once but should run all time. Is this purpose or bug?

**Comment by Divran** [comment]
E2 timers are just gmod timers so if this doesn't work then that means gmod timers are broken. Solution: don't do that

**Comment by Divran** [comment]
nevermind discussion on discord revealed the cause
