### ISSUE TITLE
lua errors

### ISSUE THREAD

**Issue by atomic26** [wiremod/wire#1583]
so when i spawn in acf and right click it like you would with a prop instead of a box showing up it gives me this error

[ERROR] addons/wire/lua/weapons/gmod_tool/stools/wire_debugger.lua:62: attempt to call field 'dummytrace' (a nil value)
  1. Filter - addons/wire/lua/weapons/gmod_tool/stools/wire_debugger.lua:62
   2. OpenEntityMenu - lua/includes/modules/properties.lua:81
    3. OnScreenClick - lua/includes/modules/properties.lua:125
     4. fn - lua/includes/modules/properties.lua:179
      5. Run - addons/ulib/lua/ulib/shared/hook.lua:109
       6. unknown - gamemodes/sandbox/gamemode/spawnmenu/contextmenu.lua:151

i need to fix it i run a gmod server but cant figure out how to fix it any help?

**Comment by bigdogmat** [comment]
`WireLib.dummytrace` should probably be made shared.

**Comment by AbigailBuccaneer** [comment]
This was my fault! I broke things again. Cause is #1565, I think I only tested in singleplayer (where many hooks aren't called clientside) and not in multiplayer. I'll fix this right now.

**Comment by atomic26** [comment]
ok thx so much X3
