### ISSUE TITLE
Wiremod code editors have broken font widths

### ISSUE THREAD

**Issue by lilggamegenius** [wiremod/wire#1597]
Currently I'm having the same issue as #309. Removing all e2 cvars from client.vdf didn't fix the issue. Changing the font setting doesn't change the font also not fixing the problem. This shows up in both the E2 editor and the CPU editor (I'm assuming they share code). I'm not really sure how to reproduce this since I can't make it go away to test. I've been trying to fix this issue for about 6 months now.

![20180310005308_1](https://user-images.githubusercontent.com/6175821/37239418-224064f2-2401-11e8-80cd-2b2f81a19741.jpg)
![20180310005205_1](https://user-images.githubusercontent.com/6175821/37239419-224e40ae-2401-11e8-84c8-a7bfc890f033.jpg)

**Comment by Divran** [comment]
Which OS are you using

**Comment by lilggamegenius** [comment]
The OS I was using when I took the screenshot was Windows 10 however I also get this issue in Kubuntu and another Windows 10 machine.

**Comment by bigdogmat** [comment]
Does this happen in a default single player game with zero addons enabled besides wiremod? That DFrame is not default.

**Comment by lilggamegenius** [comment]
I'll test it right now. I'll try the addon that changes the DFrame first since that might be the cause, otherwise I'll disable everything

**Comment by lilggamegenius** [comment]
...Ok so I found out from one of the admins on the server that the server has its own version of `surface.CreateFont` which is causing the issue.
