### ISSUE TITLE
Renaming folders for editors

### ISSUE THREAD

**Issue by revosw** [wiremod/wire#1598]
I see that folder renaming is not a thing. It's sad when you notice a typing error after having created the folder, which forces you to navigate to `\garrysmod\data\expression2` to rename it.

[Picture](https://cdn.discordapp.com/attachments/237764217736921089/422699337013788673/unknown.png)

**Comment by oldmud0** [comment]
As discussed on the Discord server, GMod's [file library](http://wiki.garrysmod.com/page/Category:file) does not have a rename or move function, so it cannot be done (easily).

**Comment by Divran** [comment]
But I asked a dev to add it so it's already in the dev branch of gmod

**Comment by oldmud0** [comment]
Great, so I guess we didn't need to start a revolt

**Comment by AbigailBuccaneer** [comment]
`file.Rename` exists now so this shouldn't be too hard.

**Comment by revosw** [comment]
Since folder renaming works, I'm closing this issue
