### ISSUE TITLE
The first tab in Expression 2 editor after joining server has border

### ISSUE THREAD

**Issue by revosw** [wiremod/wire#1599]
I am running Wiremod from SVN, revision 4026 (newest as of today at this time of posting)

The first time opening Expression 2, the first tab you see has a border. All other tabs opened afterwards will not have a border, you have to rejoin to experience it again.

To recreate:
- Join a server, or rejoin if you are already in a server
- Open the Expression 2 editor

https://i.imgur.com/u0T2RHs.gifv

**Comment by Divran** [comment]
yeah I've noticed this too but it doesn't seem to break anything so I haven't bothered to look at it

**Comment by CaptainPRICE** [comment]
I too noticed this a long ago. Sure you have a habbit of deleting the first tab and opening a new one every time...
