### ISSUE TITLE
Server hang with rangerOffsetHull(start,end,size)

### ISSUE THREAD

**Issue by Just-Boog** [wiremod/wire#1603]
Supplying a negative vector like -vec(100) will cause the server to hang for a few minutes.
rangerOffsetHull(vec(), vec(), -vec(100)) as an example.

**Comment by bigdogmat** [comment]
Ordering the min and max vectors given to `util.TraceHull` seems to fix the issue. Don't think it'll cause any traces to result in different behavior.
