### ISSUE TITLE
String function cache system breaks redefining UDFs

### ISSUE THREAD

**Issue by bigdogmat** [wiremod/wire#1612]
```
function string t()
{
    return "a"
}

print("t"()[string])

function string t()
{
    return "b"
}

print("t"()[string])
```

This will result in `a` being printed twice because the older version of the function is still in cache.

We could clear the cache for said signature when we define a UDF. This isn't as simple as clearing the signature however because string functions don't know the difference between methods and plain functions.

With the current cache system it'd look something like this (assuming we add another index to the cached function to store whether it was a method or not). This is consistent with how the functions would be cached.
```lua
local method = string.find(sig, ':', 1, true) ~= nil
local plainSig = method and sig or string.gsub(sig, ':', '')

for i = 1, #self.strfunc_cache do
	local val = self.strfunc_cache[i]
	if val[1] == plainSig and not method or val[5] then
		val[2] = body
		val[5] = method
	end
end
```

We add the above here https://github.com/wiremod/wire/blob/941df1b8b16f2361c1894903eb790b9d1bcfb237/lua/entities/gmod_wire_expression2/core/functions.lua#L9-L12

We could also just clear the `plainSig` instead and have it do a lookup again. This still requires the `plainSig` logic so eh. Either way we do it could be simplified a bit more if we made the cache a lookup table instead.

I can't think of a cleaner way to do this without changing behavior.

**Comment by AbigailBuccaneer** [comment]
Has this always been the case or did I recently break this?

**Comment by bigdogmat** [comment]
Been the case since cf19ffc (so about 6 years), only noticed it when I was working on #1600.
