### ISSUE TITLE
E2 broken user made functions

### ISSUE THREAD

**Issue by clonbon** [wiremod/wire#1616]
when I create an empty function in E2 such as-

function void test()
{
    return
}

I get the error "Return type mismatch: void expected, got void at line 4, char 5"
This seems to break any function that needs to return but type is set to void or left blank.

**Comment by CornerPin** [comment]
```perl
function void test()
{
return void
}
```

**Comment by bigdogmat** [comment]
That would've still errored, `return` is the same as `return void`.
