### ISSUE TITLE
Run string on the E2

### ISSUE THREAD

**Issue by lRoberth** [wiremod/wire#1617]
Is there any function that allows running a string?, i want to get a string from a URL (httpFetch) and run this string as code, to do a "anti-leak / stole" script, that checks who is trying to spawn the chip, and if the steamid is whitelisted, then get the string from the url and run it

**Comment by bigdogmat** [comment]
You might be able to use `remoteSetCode`. This won't really help with an anti steal script considering they can just copy the E2 you set the code on but eh. A run string type function wouldn't really help you either as they could just copy the link out of the E2.

Only solution I could give you that might work is to have major parts of your code obfuscated and based on strings from local files. This'll work but it'll be a lot of work for little bits of code and will hit performance a fair amount.
