### ISSUE TITLE
Wire socket/plug stay plugged when removing duped plug/socket

### ISSUE THREAD

**Issue by AlexALX** [wiremod/wire#1618]
Here is step to reproduce:

1. Spawn socket and plug separately. 
2. Dupe plug (or socket).
3. Spawn duped plug.
4. Connect duped plug to socket.
5. Press crtl+z.
6. Socket will be still attached to plug, but plug does not exists anymore.
7. Same goes with socked->plug connection (vice versa).

I'm not sure why this happens, but this breaks plug or socket. 

ps There is also another bug with duped sockets with big contraptions (with a lot of socket/plugs) - they errors "Weld error" and some socket/plugs become always plugged and cannot be unplugged anymore, i'll try to make steps to reproduce, but still can't figure when this exactly happens. I'll create new issue later for this. UPD: #1620

**Comment by Divran** [comment]
Most of this should be fixed now. Create a new issue if you find any bugs that I missed. https://github.com/wiremod/wire/commit/3e9aa235baba866b779cbb8afbdfcf81561724a5
