### ISSUE TITLE
entity=remoteSetCode() creating LUA errors when using chat commands on the code.

### ISSUE THREAD

**Issue by lRoberth** [wiremod/wire#1619]
when i download a string code from a VPS, and use remoteSetCode to the chip itself, when I use any chat commands that are created on the chip, I just get the next LUA error: 

> Expression 2 (Radio Listener v2.0): entities/gmod_wire_expression2/core/array.lua:94: attempt to index local 'Scope' (a nil value)

I figured out that if i remove the next line of code, the E2 works just fine, but will make it unuseful, you would need to dig into the code to manually use the E2.

`local A = owner():lastSaid():explode(" ")`

I also used fileLoad() instead of httpRequest(), and gave me the exact result, looks like everything is on the remoteSetCode() function.

Chip that downloads the string from the VPS and replaces the code: [Click here](https://ghostbin.com/paste/6tdjc)

Code that is downloaded and replaced with: [Click here](https://ghostbin.com/paste/kybd5) (lastsaid array at line 53)

**Comment by AbigailBuccaneer** [comment]
Your example code uses custom extensions. Please paste a minimal example that developers can actually run.

**Comment by lRoberth** [comment]
Here is the downloaded code without custom extensions: [Click here](https://ghostbin.com/paste/jammt)

**Comment by AbigailBuccaneer** [comment]
I'm unable to reproduce this, in singleplayer, using the latest `master` version of Wiremod (ba5a37684199fa83780be5ef54feb766822343d3), with the following code:

```PHP
@name Radio Listener v2.0
runOnHTTP(1)
httpRequest("https://ghostbin.com/paste/jammt/raw")
if(httpClk()){
 runOnHTTP(0)
 entity():remoteSetCode(httpData())
}
```

...and by saying "!play https://www.youtube.com/watch?v=dQw4w9WgXcQ" and "!pause".

Can you reproduce this without any addons installed other than Wiremod?

**Comment by lRoberth** [comment]
I can only get the chip commands work on DarkRP. However, the chip seems to perfectly work, no more LUA errors when typing any commands (Im using the Workshop Wiremod version), what was the command to see the current Wiremod version running on the server?

**Comment by AbigailBuccaneer** [comment]
The only reliable way is to ask the server owner. This is because Wiremod can be downloaded either from Git or the Workshop (there's even people who still update Wiremod via GitHub's SVN mirror), and Wiremod isn't able to inspect what workshop version it's on or inspect its own internal `.git` files.

**Comment by CaptainPRICE** [comment]
> what was the command to see the current Wiremod version running on the server?

IIRC, `wireversion` (it does not popup in client console's autocomplete list because the command is created on serverside).

**Comment by thegrb93** [comment]
Ill try tomorow

**Comment by thegrb93** [comment]
Works fine for me too
