### ISSUE TITLE
Some wire plug/sockets become always plugged after dupe in large contraptions

### ISSUE THREAD

**Issue by AlexALX** [wiremod/wire#1620]
Here is small video of demonstrating this bug: https://youtu.be/mMZHHIdqfgs

Basically this happens when you copy/paste big contraption with a lot of socket/plugs and also it creates weld errors as you can see on video. I have no idea why this happens, but this broke ability to copy and paste my whole E2 PC when it is assembled. 

Also this looks pretty random but repeatable, i mean that in this exact PC assemble is only broken 2 network ports, and if i repeat action - it will give same result. But if i'll create new assemble and dupe it - other ports may be affected.

I'm not sure, but it also might be somehow connected with #1618.

**Comment by Divran** [comment]
Most of this should be fixed now. Create a new issue if you find any bugs that I missed. https://github.com/wiremod/wire/commit/3e9aa235baba866b779cbb8afbdfcf81561724a5
