### ISSUE TITLE
High-speed writes to keyboard trigger memory fault

### ISSUE THREAD

**Issue by immibis** [wiremod/wire#1627]
The keyboard's WriteCell function always returns false (indicating an invalid address) - so whenever you write to it, it always triggers a memory fault, even if the write was actually successful.
(This is easily worked around by disabling interrupts when accessing a keyboard)

**Comment by AbigailBuccaneer** [comment]
Looking at the code:
* Writing anything to location 0 removes the first key in the buffer
* Writing a value to _any other_ location removes the first occurrence of that value from the buffer

Would it suffice to allow locations 0 and 1 as valid locations?
