### ISSUE TITLE
Errors upon server load.

### ISSUE THREAD

**Issue by Toxic10101** [wiremod/wire#1630]
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/angle.lua:26: '=' expected near 'angle'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/angle.lua:0
//  
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/array.lua:56: '=' expected near 'array'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/array.lua:0
//  
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/bitwise.lua:6: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/bitwise.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/bone.lua:87: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/bone.lua:0 
//  
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/chat.lua:52: '=' expected near 'void'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/chat.lua:0
//  
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/color.lua:24: '=' expected near 'vector'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/color.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/compat.lua:3: '=' expected near 'string'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/compat.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/complex.lua:101: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/complex.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/console.lua:34: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/console.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/constraint.lua:48: '=' expected near 'array'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/constraint.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/core.lua:244: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/core.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/custom/constraintcore.lua:8: '=' expected near 'void'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/custom/constraintcore.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/custom/effects.lua:60: '=' expected near 'effect'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/custom/effects.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/custom/prop.lua:156: '=' expected near 'entity'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/custom/prop.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/custom/remoteupload.lua:17: '=' expected near 'void'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/custom/remoteupload.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/custom/sv_moneyrequest_tylerb.lua:183: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/custom/sv_moneyrequest_tylerb.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/custom/sv_shipments_tylerb.lua:47: '=' expected near 'string'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/custom/sv_shipments_tylerb.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/custom/wiring.lua:7: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/custom/wiring.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/datasignal.lua:314: '=' expected near 'void'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/datasignal.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/debug.lua:88: '=' expected near 'void'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/debug.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/egpfunctions.lua:14: '=' expected near 'void'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/egpfunctions.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/entity.lua:67: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/entity.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/files.lua:135: '=' expected near 'void'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/files.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/find.lua:344: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/find.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/gametick.lua:15: '=' expected near 'void'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/gametick.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/globalvars.lua:54: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/globalvars.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/hologram.lua:628: '=' expected near 'entity'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/hologram.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/http.lua:27: '=' expected near 'void'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/http.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/matrix.lua:57: '=' expected near 'matrix2'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/matrix.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/npc.lua:13: '=' expected near 'void'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/npc.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/number.lua:232: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/number.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/player.lua:29: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/player.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/quaternion.lua:113: '=' expected near 'quaternion'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/quaternion.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/ranger.lua:167: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/ranger.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/selfaware.lua:7: '=' expected near 'entity'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/selfaware.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/serialization.lua:237: '=' expected near 'string'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/serialization.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/serverinfo.lua:7: '=' expected near 'string'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/serverinfo.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/signal.lua:108: '=' expected near 'void'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/signal.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/sound.lua:125: '=' expected near 'void'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/sound.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/steamidconv.lua:8: '=' expected near 'string'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/steamidconv.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/string.lua:110: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/string.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/table.lua:278: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/table.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/timer.lua:69: '=' expected near 'void'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/timer.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/unitconv.lua:96: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/unitconv.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/vector.lua:41: '=' expected near 'vector'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/vector.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/vector2.lua:158: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/vector2.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/weapon.lua:7: '=' expected near 'entity'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/weapon.lua:0
//
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/wirelink.lua:150: '=' expected near 'number'

  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/wirelink.lua:0

**Comment by bigdogmat** [comment]
Have you edited Wiremod in anyway? These errors indicate that these files weren't run through the extension preprocessor, which can't happen.

Try reinstalling.

**Comment by AbigailBuccaneer** [comment]
It might be caused by a third-party addon - but I don't know what reason a third-party addon would have to just blindly parser all these files. (Maybe it's some horrible broken 'security' addon that parses every Lua file to try and look for suspicious bytecode?)

**Comment by Toxic10101** [comment]
It's CAC - https://www.gmodstore.com/scripts/view/460
