### ISSUE TITLE
Http returning table would be nice

### ISSUE THREAD

**Issue by Consoli0** [wiremod/wire#1631]
If HTTP get would return a table I would be able to do lots more with it.
Just a small question.

**Comment by Consoli0** [comment]
How would I label this?

**Comment by AbigailBuccaneer** [comment]
Only developers can label issues.

What exactly are you asking for here? Do you want to be able to fetch the HTTP headers and status code, as well as the response body? Or are you asking for a function that parses the response body as if it's a table?

**Comment by AbigailBuccaneer** [comment]
Closing due to no response.
