### ISSUE TITLE
Starfall processor declining to work

### ISSUE THREAD

**Issue by saint345** [wiremod/wire#1633]
Guys im new to starfall and i just finished the code, this appeared : "attempt to call global "loadlibrary" (a nil value)"
If you could provide some help, please do.

**Comment by thegrb93** [comment]
Try these examples instead https://github.com/thegrb93/StarfallEx/tree/master/lua/starfall/examples

**Comment by AbigailBuccaneer** [comment]
Starfall isn't part of Wiremod.
