### ISSUE TITLE
Recent Update causes E2 to create Internal Error

### ISSUE THREAD

**Issue by Mrannoyus** [wiremod/wire#1636]
After taking a break from writing a bunch of E2's a few months ago I come back and attempt to add onto them but now the master E2 is causing an internal error. See attached Expression 2 and Error.

Internal error - please report to https://github.com/wiremod/wire/issues
lua/entities/gmod_wire_expression2/base/optimizer.lua:59: attempt to concatenate a nil value

Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 296	"__concat"		lua/entities/gmod_wire_expression2/core/e2lib.lua
	3: Line 59	"evaluateUnary"		lua/entities/gmod_wire_expression2/base/optimizer.lua
	4: Line 90	"action"		lua/entities/gmod_wire_expression2/base/optimizer.lua
	5: Line 38	"Process"		lua/entities/gmod_wire_expression2/base/optimizer.lua
	6: Line 32	"Process"		lua/entities/gmod_wire_expression2/base/optimizer.lua
	7: Line 32	"nil"		lua/entities/gmod_wire_expression2/base/optimizer.lua
	8: C function	"xpcall"
	9: Line 19	"Execute"		lua/entities/gmod_wire_expression2/base/optimizer.lua
	10: Line 260	"CompileCode"		lua/entities/gmod_wire_expression2/init.lua
	11: Line 424	"Setup"		lua/entities/gmod_wire_expression2/init.lua
	12: Line 264	"func"		lua/wire/stools/expression2.lua
	13: Line 32	"nil"		lua/includes/extensions/net.lua

sv: Internal error, see console for more details

[PMD_MasterServer.txt](https://github.com/wiremod/wire/files/1892871/PMD_MasterServer.txt)

**Comment by bigdogmat** [comment]
This is caused by the fact our `and` and `or` optimizations didn't check the second argument for being literals.

If you want a quick fix change line 268 to `if (!dsClk())`, for reference it used to be `if (1&!dsClk())`.
