### ISSUE TITLE
Dynamically load custom E2 extensions

### ISSUE THREAD

**Issue by Mista-Tea** [wiremod/wire#1639]
Hello,

I hate to ask this via opening an issue, but is it currently possible to **dynamically load custom E2 extensions** without having to restart the server on every change? It's a bit of a pain when trying to writing E2 functions.

I'm looking at lua/entities/gmod_wire_expression2/core (init, extloader, etc) to see if there is a hook or function we can call to reload extensions, but everything seems to be done only on server startup.

If not, would this be a potential feature that could be added?

**Comment by Divran** [comment]
`wire_expression2_reload` will reload all extensions, just type that after every change

**Comment by Mista-Tea** [comment]
Ah, my apologies for missing that. Thanks for the quick response.
