### ISSUE TITLE
Wiremod Lights brightness and size doesn't seem to change anything.

### ISSUE THREAD

**Issue by steampunko** [wiremod/wire#1641]
![20180415190554_1](https://user-images.githubusercontent.com/16859299/38786980-305265b2-40e0-11e8-8a45-511f000b8fe0.jpg)
![20180415190600_1](https://user-images.githubusercontent.com/16859299/38786981-306aa262-40e0-11e8-85e3-8d0db2ada416.jpg)

Left light has brightness and size set to 0.
Right light has brightness set to 1 and size to 256

**Comment by AbigailBuccaneer** [comment]
The 'Glow brightness' and 'Glow size' options only affect the glow component, which you have disabled in the C-menu. We should offer control over the size of the radiant component (which is what's casting the light in the screenshot) and the directional component.

**Comment by steampunko** [comment]
That would be really helpful

**Comment by Divran** [comment]
Some of these might already have inputs to configure them, instead of C-menu options.

**Comment by thegrb93** [comment]
So these should depending on the size and brightness as well

https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_light.lua#L183-L184
