### ISSUE TITLE
Digital Screen image loading too slow (regression)

### ISSUE THREAD

**Issue by AlexALX** [wiremod/wire#1642]
Hello, in past we already discuss that and even was made fix in https://github.com/wiremod/wire/commit/ff70ce2a03b7f3cb783ec11f6e76d90a9d9a447d#diff-12683ca34a0694775f94ca1b1a6830c5

But right now its again happens. I'm not sure why but this image loading extremely slow in both sp/mp. It is opening in my script for 7 seconds but DS draw it itself ~5 minutes.

Here is that image in png format: https://i.imgur.com/1lUafxj.png

**Comment by Divran** [comment]
yeah I'll try to find the time to take a look at this

**Comment by Divran** [comment]
Ok I've taken a look at this and it looks like that image is just straight up broken. My PHP script (which converts the image into a format which is easier for E2 to use) thinks every single pixel in the entire image is black.

**Comment by Divran** [comment]
should be fixed now
