### ISSUE TITLE
propPhysicalMaterial() on invalid entity

### ISSUE THREAD

**Issue by MagnumMacKivler** [wiremod/wire#1648]
The E2 function `propPhysicalMaterial()` when given an invalid entity as a parameter returns a null string, which causes errors if you try to do anything with it.

Example
```
@name 
@inputs 
@outputs 
@persist 
@trigger 

local PhysProp = noentity():propPhysicalMaterial()
print(":" + PhysProp + ":")
```

Plop it down and it returns this error:
```
sv: Expression 2 (generic): entities/gmod_wire_expression2/core/string.lua:63: attempt to concatenate a nil value
```

Granted this is probably super easy to fix by just checking if the entity you're passing propPhysicalMaterial() to is actually valid. Perhaps instead of returning a null string it just returns an empty one ("")? Concatenating an empty string doesn't return the error.

Edit: Apparently the same thing happens with ragdolls.

**Comment by bigdogmat** [comment]
It seems a lot of propcore functions have this issue, I'll make a pr to fix them.
