### ISSUE TITLE
Vector operator[]= doesn't trigger vector output

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#1660]
#411 added mutability to these types, which were never supposed to be mutable. This mutability causes bugs: in the following code snippet, `Array` and `Table` (which are intentionally mutable types) will update when `In` does, but `Vector` won't.

```Perl
@inputs In
@outputs Array:array Table:table Vector:vector
Array[1, number] = Table[1, number] = Vector[1] = In
```

It also means that [table cloning is less efficient](https://github.com/wiremod/wire/pull/1659#discussion_r189656123) and the optimizer will have a harder time optimizing code blocks that manipulate vectors.

@Divran @bigdogmat @TomyLobo thoughts? What if the E2 compiler issued a warning on those setters for a few months before we removed them?

This is also the case for ang/quat/vec2/vec4 types.

**Comment by AbigailBuccaneer** [comment]
This has been complained about before in #1348.

**Comment by thegrb93** [comment]
I think the operator is good, but it does need to trigger ouput vectors.

**Comment by thegrb93** [comment]
I believe this was fixed already. Need to check

**Comment by thegrb93** [comment]
Fixed by https://github.com/wiremod/wire/pull/2315
