### ISSUE TITLE
Issue with pod controller

### ISSUE THREAD

**Issue by jullegulle2000** [wiremod/wire#1664]
This issue started to appear a month ago or so in an update.
When you are in a vehicle with multiple seats and look in thirdperson, It will randomly switch seat. Aka putting you in another seat thats linked to the base prop. And if you get out you will still be able to control the pod controller and you are not able to enter the main seat linked to the pod controller. No idea what started to cause this but its hella annoying

**Comment by AbigailBuccaneer** [comment]
@jullegulle2000 can you no longer reproduce this issue?

**Comment by jullegulle2000** [comment]
Found what caused it. A wire update must have broken the "Switchable Seats" addon. I didnt think of it until now so i removed the addon and the issue seems to be gone.

**Comment by jullegulle2000** [comment]
Re-opening the issue, I thought it was that addon that caused it but after removing it from my server the issue remains.

**Comment by thegrb93** [comment]
Perhaps it's another addon then

**Comment by jullegulle2000** [comment]
I guess, I was gonna do a server reset next week so hopefully it will get fixed.
