### ISSUE TITLE
Paren highlighting is broken next to strings

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#1667]
The following cases highlight correctly:
```
f( ( 1 ) , 1 )
f( ( 1 ) , 1)
f( ( 1 ) , " " )
```
But things break if you remove the final space from the third case. When the cursor is to the left of the final paren, there's no paren highlighting:
![image](https://user-images.githubusercontent.com/908758/41044555-7166bd14-699e-11e8-9fb0-8d3784c15d53.png)
And when it's to the right, the wrong paren is highlighted:
![image](https://user-images.githubusercontent.com/908758/41044466-412b4dae-699e-11e8-9ff4-1e2fcb2578d9.png)

cc @bigdogmat

**Comment by bigdogmat** [comment]
This is due to the fact `GetTokenAtPosition` returns the token to the left side of the cursor. I didn't even think to test this due to the fact `self.Rows[pos[1]]:sub(pos[2], pos[2])` returns the character right of the cursor.

Just need to add an offset.
