### ISSUE TITLE
Wire beacon sensor velocity non functional

### ISSUE THREAD

**Issue by FallenRecruit** [wiremod/wire#1668]
With beacon sensor if I try to output targets velocity nothing will work and you get this error

This is when using it with an XYZ beacon from wire extras

[ERROR] addons/wire-master/lua/entities/gmod_wire_sensor.lua:101: attempt to call method 'GetBeaconVelocity' (a nil value)
  1. unknown - addons/wire-master/lua/entities/gmod_wire_sensor.lua:101

**Comment by thegrb93** [comment]
The xyz beacon was only designed to work with position it seems. Turn off velocity to prevent the error for now.
