### ISSUE TITLE
[E2] Need help with soundPlay and soundStop

### ISSUE THREAD

**Issue by Gyarik** [wiremod/wire#1669]
So basically I'm trying to build a sound library for Stalker RolePlaying, but the sounds keep looping whenever I use them; this is what I wrote for each one of them (obviously with different sounds and chat commands):

if(owner():lastSaid() == ".scream1")
{
    owner():soundPlay(1, 0, "npc/stalker/stalker_scream1.wav")
    soundStop(1, 0)
}

I've put "runOnTick(1)" at the start of the E2, removing it doesn't even work as it doesn't even play a sound.

So is there any way to fix it? Thanks.

**Comment by AbigailBuccaneer** [comment]
If the code has `runOnTick(1)` then the code will repeatedly run. When you say ".scream1" then the if condition will be true every time, and so it repeatedly calls `owner():soundPlay()`, which starts it playing again.

What you want to do is run the chip only on a chat message, and only play the sound when it was the owner who triggered it:

```PHP
if (first()) {
    runOnChat(1)
}

if (chatClk(owner()) & owner():lastSaid() == ".scream1") {
    owner():soundPlay(1, 0, "npc/stalker/stalker_scream1.wav")
}
```

**Comment by Gyarik** [comment]
I tried what you suggested, but this time the sound won't even start.
Is it because many servers blacklists `chatClk(owner)`?
