### ISSUE TITLE
Wire POD gives error when removed

### ISSUE THREAD

**Issue by dvdvideo1234** [wiremod/wire#1672]
While My contraption was working, I linked the POD to another vehicle then removed the whole thing via UNDO:

[Wiremod] lua/entities/gmod_wire_pod.lua:186: attempt to call method 'UnlinkEnt' (a nil value)
  1. Function - lua/entities/gmod_wire_pod.lua:186
   2. v - lua/includes/extensions/entity.lua:134
    3. unknown - lua/includes/modules/hook.lua:84

**Comment by dvdvideo1234** [comment]
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/extensions/entity.lua#L134

Seems to be:
```
	pod:CallOnRemove("wire_pod_remove",function()
		self:UnlinkEnt(pod)
	end)
```
Maybe t's better to be named `RemovePod` instead of `UnlinkEnt`

**Comment by AbigailBuccaneer** [comment]
I tried the following steps in a singleplayer game:

1. Spawn a pod controller
2. Spawn an airboat seat
3. Link the pod controller to the airboat seat
4. Press Z to undo spawning the airboat seat

...and could not reproduce this. I'll reopen if you have more detailled reproduction steps.
