### ISSUE TITLE
Pod controller does not respond to key presses

### ISSUE THREAD

**Issue by RedFoxIV** [wiremod/wire#1674]
Ignores my keypresses while in a linked vehicle or if i'm using a remote controller, exept the light key.
No lua errors from wiremod whatsoever.

Not present in a multiplayer game.

![20180625174456_1](https://user-images.githubusercontent.com/38788538/41857684-c19ee246-78a0-11e8-8fc0-251fe18672a9.png)

**Comment by AbigailBuccaneer** [comment]
I tried the following steps in both singleplayer and multiplayer:

1. Spawn a pod controller
2. Spawn an airboat seat
3. Link the pod controller to the airboat seat
4. Select the Wire Debugger tool
5. Click on the pod controller to debug it
6. Sit in the seat
7. Mash all the keys listed

...and couldn't reproduce the issue. This works fine for me. Do you have more detailed repro steps? Have you tried with no other addons installed?

**Comment by GamesArsenal96** [comment]
I know this old as hell but do we know the fix to this issue?
