### ISSUE TITLE
E2 API always makes the `this` pointer return nil

### ISSUE THREAD

**Issue by dvdvideo1234** [wiremod/wire#1676]
I was coding logging controls for my [Wire extras addon](https://github.com/dvdvideo1234/BridgesExpression2/commit/2dacf5a198cdc0346826c6ff101598a8bc066f6b) the other day, just to notice that the `this` pointer always returns `nil` for the code "A:[setState](https://github.com/dvdvideo1234/BridgesExpression2/compare/error_logging#diff-71dc9785719dee708140160d01e18a07R730)(3,4):[getControl](https://github.com/dvdvideo1234/BridgesExpression2/compare/error_logging#diff-71dc9785719dee708140160d01e18a07R689)()" I have the following in the logs
```
setState(nn): Invalid instance
getControl(): Invalid instance
```
I am on a dedicated branch for the logging control:
https://github.com/dvdvideo1234/BridgesExpression2/compare/error_logging

My wild guess is that I cant return a function [vararg values](https://github.com/dvdvideo1234/BridgesExpression2/compare/error_logging#diff-71dc9785719dee708140160d01e18a07R46).

**Comment by bigdogmat** [comment]
What's `A` in this case?

**Comment by dvdvideo1234** [comment]
@bigdogmat A state controller object defined [here](https://github.com/dvdvideo1234/BridgesExpression2/blob/2dacf5a198cdc0346826c6ff101598a8bc066f6b/lua/entities/gmod_wire_expression2/core/custom/stcontroller.lua#L148).

**Comment by bigdogmat** [comment]
I did a pull from your `error_logging` branch and ran this `print(newStController():setState(3,4):getControl())`. I don't see any prints to console aside from the one I made manually.

**Comment by dvdvideo1234** [comment]
This is addon intended for E2. Try the E2 script in the pull request.

**Comment by dvdvideo1234** [comment]
```
if(first() || dupefinished())
{
    V2 = vec2(1.1,0.5)   
    E = entity()
    T = E:setFSensor(E:massCenterL(),vec(0,0,1), -225):addClassHit("prop_physics")
    C = newStController():setGain(1700, 6800, 7800):setWindup(-9000,9000):setPowerPI(V2):dumpConsole("TEST")
    E:setMass(250)
}
```

**Comment by bigdogmat** [comment]
I get no print outs when running that.

**Comment by dvdvideo1234** [comment]
Are you using the workshop version of wiremod or the GIT version ? I am running the workshop version.

**Comment by bigdogmat** [comment]
It wasn't printing out because you're logger only works if I change the convar state to `LOG` while it's set to something else, and don't reload E2. Your logger code should be a lot simpler, but I digress.

The reason both of your codes above give the invalid instance output is because `makeStController` with no argument gives the `mnTo` field 0. As such it follows the path of `logError("makeStController: Instance sampling time mismatch #"..tostring(oStCon.mnTo), nil)`, and as you can see the last argument is `nil`, so `logError` returns nothing.

**Comment by dvdvideo1234** [comment]
I guess this logging is not needed as IFF the controller is defined properly, the method calls wil not fail

I updated the PR and removed the `or 0` addition:

https://github.com/wiremod/wire-extras/pull/59
