### ISSUE TITLE
DarkRP Interfacing

### ISSUE THREAD

**Issue by benfoster04** [wiremod/wire#1679]
So, I was wondering, would there be any way for Wiremod to be able to interface with the DarkRP gamemode in ways such as activating an output when there's a lockdown in progress? Or taking in an input to activate a lockdown.

**Comment by CornerPin** [comment]
This should be implemented by the gamemode developer IMO.

**Comment by shadowscion** [comment]
Support for things like this are definitely the thirdparty's problem and responsibility.

**Comment by AbigailBuccaneer** [comment]
As the other comments have said, this is something that any gamemode can do - someone could even make an addon separate to Wiremod and DarkRP that adds entities that interface them via the public interfaces they provide.

If you're interested in developing such an addon, the Wiremod developer team would probably be happy to review your code to make sure that it uses the Wiremod interface directly. But all of the wire entities are examples of how to write entities that use Wiremod, and any addon could use Wiremod in just the same way.

**Comment by benfoster04** [comment]
@AbigailBuccaneer That is something that I could be interested in doing. If anyone would be happy to help me out then hit me up
