### ISSUE TITLE
Support E2 compiler warnings

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#1680]
Currently, the E2 compiler can either succeed, or fail with a message and a source location (or die from an internal compiler error). It would be nice if it could output a list of warnings. The E2 text editor could then show them on validation (maybe even with yellow squiggly underlines?)

**Comment by AbigailBuccaneer** [comment]
Some things to warn on:

* Duplicate `@inputs`/`@outputs`
* Not all code paths in a function return a value
* Global variable used earlier in the source than it's defined
* Expression statement has no effect (eg. `function f() { 1 + 2 }`)

**Comment by CaptainPRICE** [comment]
> * Duplicate `@inputs`/`@outputs`

It is currently treated as an error, for example:
`Directive (@input) contains multiple definitions of the same variable`
See also https://github.com/wiremod/wire/issues/1494

> * Not all code paths in a function return a value
> * Expression statement has no effect (eg. `function f() { 1 + 2 }`)

( Currently, this is a small feature in mine E2 obfuscator for increasing a level of confusion. Junk code, unused random expressions [string, number, and other values, garbage not being assigned nor used]. Fixing this would break it, no big deal for me. )
Just be aware of what you're doing. Focus on more important parser issues...
I thought the no returns were fixed, @bigdogmat you talked about this being fixed?

> * Global variable used earlier in the source than it's defined

It is like "method hiding", but for variables; variable hiding. IIRC, I have talked about this, also I remember I had an issue about it. Just I can't seem to find it now. So, I'll just bring up some code up:
```golo
@persist N C
@outputs A
@inputs A

if (0 & N)
{
    B = 1 # Heuristically unreachable "dead" code. Required to keep compiler happy! Otherwise validation errors.
}
elseif (first())
{
    print("Running...")
    local B = inf()
    local C = -B
    #local N = 0
    function f()
    {
        print("f()")
        function f(A)
        {
            print(format("f(%g)", A))
            ioSetOutput("A", A * _PI) # Thanks to io we can still tell it to change the output value in this scope.
            # At this point, how would you get "@outputs A" value?
        }
        C = B - _PI
    }
    f()
    N++ 0 N
    # If "local N" line were uncommented, at this point, how would you set "@persist N" to some other number?
}
elseif (N)
{
    N = 0
    f(_E)
}
```

You want to improve E2, bring in warnings? Then here is your candidate:
#1181 Make `array` and `table` a language construct.

**Comment by bigdogmat** [comment]
> I thought the no returns were fixed, @bigdogmat you talked about this being fixed?

Originally the fix was to check all code paths but was switched out for a runtime error.
