### ISSUE TITLE
Add inputs to camera controller for all of the settings?

### ISSUE THREAD

**Issue by shadowscion** [wiremod/wire#1686]
Currently you have to check or uncheck boxes before spawning the entity, which can get annoying if you frequently switch between using clientside and serverside cams. 

Also the ability to link them to vehicles (this could be added to pod controllers as well) in the same way would be nice.

**Comment by thegrb93** [comment]
This is probably because entering the camera controller and then changing the settings could lead to issues. Idk though

**Comment by shadowscion** [comment]
This can be closed if https://github.com/wiremod/wire/pull/1706 is merged.
