### ISSUE TITLE
Wires disappear after duplicating or connecting to the server

### ISSUE THREAD

**Issue by MulleDK19** [wiremod/wire#1687]
At first I thought it was a bug in Advanced Duplicator 2, as wires it pasted were invisible.
But it also happened with Advanced Duplicator 1.

Then I tried reconnecting to the server, and all wires on all existing contraptions on the map were gone too.

This happens on both my cleanly installed dedicated server, and cleanly installed game, with these workshop addons: https://steamcommunity.com/sharedfiles/filedetails/?id=136821175

I have tried in singleplayer with no addons except Wiremod. The issue persists.

When dupping with adv. dup 2, only the last wire is restored. And if you do a wire with say 20 waypoints, then redo the wire with 3 waypoints; in the dup those 20 waypoints will still be there, and the 3 first were just changed. (Happens whether you delete the existing wire first or not).
Behavior is identical with adv. dup 1, so I'm pretty sure it's a bug with the wire itself.

https://youtu.be/8AyUEMzLx6c

**Comment by thegrb93** [comment]
Looks like the problem is in the networking. I can check it out.

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/pull/1688

**Comment by MulleDK19** [comment]
Thanks. I'm using the workshop, so I just took your changes and dumped the entire thing into my server's lua folder. This fixes dupes, but not connects. Don't know if that's a different bug, or just due to how I'm just dumping the script in my lua. That's good enough until this gets approved, I guess.

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/pull/1691
