### ISSUE TITLE
Wire Motor: placement problem

### ISSUE THREAD

**Issue by Rami4274** [wiremod/wire#1689]
so when i'm placing a motor on the ground and when i undo, it falls a little bit meaning that it is a little offground
![half life source screenshot 2018 07 30 - 11 08 19 97](https://user-images.githubusercontent.com/6593593/43385268-efbe40dc-93e8-11e8-8309-5137661675f4.png)

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/blob/master/lua/wire/stools/motor.lua#L145
