### ISSUE TITLE
lua/entities/gmod_wire_expression2/base/compiler.lua:49: attempt to index a nil value

### ISSUE THREAD

**Issue by rush93** [wiremod/wire#1694]
e2 code:
```
@persist A B

B = A + A
```
this error append:
```
lua/entities/gmod_wire_expression2/base/compiler.lua:49: attempt to index a nil value
Trace:
    1: Line 32    "Trace"        lua/includes/extensions/debug.lua
    2: Line 319    "__index"        lua/entities/gmod_wire_expression2/core/e2lib.lua
    3: Line 49    "nil"        lua/entities/gmod_wire_expression2/base/compiler.lua
    4: C function    "Execute"
    5: Line 74    "wire_expression2_validate"        lua/entities/gmod_wire_expression2/cl_init.lua
    6: Line 1588    "Validate"        lua/wire/client/text_editor/wire_expression2_editor.lua
    7: Line 1836    "Close"        lua/wire/client/text_editor/wire_expression2_editor.lua
    8: Line 826    "DoClick"        lua/wire/client/text_editor/wire_expression2_editor.lua
    9: Line 232    "nil"        lua/vgui/dlabel.lua
```
e2 code:
```
A = 2 + 2 
```
Error: `No such operator: +(number, number)`

for all players on my server, and yesterday all works perfectly. i have added nothing on my server.

**Comment by bigdogmat** [comment]
I can't reproduce either of these with the latest workshop/github versions. Make sure you're up to date in whatever method you're using.

**Comment by AbigailBuccaneer** [comment]
>     3: Line 49    "nil"        lua/entities/gmod_wire_expression2/base/compiler.lua
>     4: C function    "Execute"
>     5: Line 74    "wire_expression2_validate"        lua/entities/gmod_wire_expression2/cl_init.lua

I don't know what happened here but something is broken with your server (or Garry's Mod or LuaJIT) if it thinks wire_expression2_validate calls a C function called `Execute`. (The only functions called `Execute` we call in there are Lua functions, as they're from Wiremod itself, which contains no C code.)

**Comment by bigdogmat** [comment]
> I don't know what happened here but something is broken with your server (or Garry's Mod or LuaJIT) if it thinks wire_expression2_validate calls a C function called `Execute`. (The only functions called `Execute` we call in there are Lua functions, as they're from Wiremod itself, which contains no C code.)

There's nothing wrong. We're directly returning `xpcall` which turns into a tail call and thus it thinks we're calling a C function (`xpcall`).

Though this issue is still with the clients install, not wiremod.
