### ISSUE TITLE
Wirelinks disappear after duping

### ISSUE THREAD

**Issue by TehRayinator** [wiremod/wire#1708]
I'm pretty new to E2 and Wiremod itself so excuse me if I miss anything or use the wrong terms.

I created a basic contraption using an E2 Chip and linked it all up using the wire tool. Upon duping it and pasting it however, the wirelinks all unlinked themselves. When I try relinking them after pasting them, nothing works. None of the inputs respond and the E2 chip seems to be dead. If I unlink them all and relink them the same occurs. I've also tried replacing the E2 chip itself which still leads to the same result. It will only work if I remove and replace every single wiremod object.

I've tried using the regular Duplicator, Advanced Duplicator and Advanced Duplicator 2 to no avail.

Is there any step I'm missing or an issue with how I'm duping it?

**Comment by thegrb93** [comment]
I can't reproduce this issue. Are you using the latest version? Does it work if you use a clean gmod with just wire and advdupe installed?

**Comment by TehRayinator** [comment]
I'm using the steam workshop versions of the addons so I'm assuming they're up to date. Just in case, I reinstalled them and I also disabled all the other mods and tried again. The same result occurs. Would it help if I linked the Advdupe file?

**Comment by thegrb93** [comment]
Sadly workshop isn't up to date, try updating.
