### ISSUE TITLE
Pod controller is stuck active after exiting vehicle

### ISSUE THREAD

**Issue by atomic26** [wiremod/wire#1710]
so im an acf builder with ISA and I run an svn thru this but when I drive a tank and exit it the egp is still on my screen the pod controller is still taking controls as well

**Comment by thegrb93** [comment]
Does this happen with every tank or a specific one?

**Comment by atomic26** [comment]
this happens with anyvehichle useing a pod controller cam controller and egp they all stay stuck on

**Comment by thegrb93** [comment]
Try updating to this version of wire, or try on another server. If it still happens, we'll probably need the dupe in order to figure out what's wrong.

**Comment by atomic26** [comment]
it's not a specific dupe and it doesn't only happen to me on the server it's literally anything that uses a pod controller egp or cam controller no matter what player it is or what vehicle it is, it can be just a chair with a pod controller connected and it will do the same the problem is the pod controllers once you get out the chair stay active and keep on taking inputs

**Comment by thegrb93** [comment]
Try another server. If it doesn't happen then the problem is with the server. They'll need to remove addons to isolate which one is causing the issue.

**Comment by thegrb93** [comment]
If it's still a problem, we'll probably need a dupe file containing the issue.
