### ISSUE TITLE
Two Way Radios show a lot of "hint" lua errors when duplicated apart

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/wire#1711]
It seems that duplicating two way radios which are linked and then pasting one of the radios apart triggers a lot of "hint" lua errors until the radio is "unlinked" or removed.

**Comment by thegrb93** [comment]
What's the error? I can't reproduce this issue.

**Comment by Andrew-Eathan** [comment]
i'll get on garry's mod in a few hours and re-create the problem myself.

**Comment by thegrb93** [comment]
Also is it regular duplicator, adv duplicator, or adv duplicator 2?

**Comment by Andrew-Eathan** [comment]
seems to be advdupe2 related.
https://videobin.org/+utl/zv5.html
there's the video. the quality may be crappy but if there's any need, i can send a screenshot of the console errors.

**Comment by thegrb93** [comment]
Seems to be a lot more than two-way radios there. Would explain why I couldn't reproduce it. Going to need more info on how to make it error
