### ISSUE TITLE
Pasting a wire entity that is wired to another will wire it to the original entity if it is missing from the dupe

### ISSUE THREAD

**Issue by thegrb93** [wiremod/wire#1712]

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/base_wire_entity.lua#L393

This is the cause. Should it be changed?

**Comment by thegrb93** [comment]
@AbigailBuccaneer @Divran

**Comment by AbigailBuccaneer** [comment]
It's been like this [forever](https://www.youtube.com/watch?v=ADxp6-as1OU) (but that doesn't mean we shouldn't consider it a bug).

Ideally, if you dupe an entity then any entities it's wired to would also be duped - similar to how constraints are handled. (That's what #339 is about.)

I think it's better to fix this than to leave it as is, you're right.

**Comment by thegrb93** [comment]
Forgot that this was the cause. https://github.com/wiremod/wire/blob/master/lua/entities/base_wire_entity.lua#L394
