### ISSUE TITLE
Arguments of type complex/normal/number are unrecognized by syntax highlighter

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1714]
Running off `Wiremod's version: 'Git fbbc01e'`.

```golo
function normal op_eq(L, R:complex) { return L == R }
function normal op_neq(L, R:complex) { return L != R }
function normal op_eq(L:number, R) { return L == R }
function normal op_neq(L, R) { return L != R }
function normal op_lt(L:normal, R) { return L < R }
function normal op_gt(L, R:normal) { return L > R }
function number op_le(L, R:number) { return L <= R }
function number op_ge(L, R, X:number, Y:normal, Z:complex) { return L >= R }
print(_PI)
```

Reports "Validation successful", and it runs fine too.
But, there seems to be a bug in Wire text editor syntax highligher:
![Screenshot](https://user-images.githubusercontent.com/9789070/44956908-4a1feb00-aecb-11e8-9840-ae723e93e47b.png)

**Comment by shadowscion** [comment]
Oddly, it somehow depends on the order of the arguments
![wut](https://user-images.githubusercontent.com/2807409/44959350-6d8a6c00-aeb2-11e8-9551-d7bed11ecbe1.png)
