### ISSUE TITLE
Digital screen pixel "warp" bug

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/wire#1718]
While messing around with digital screens (some info's below), i found a bug. Apparently i had left the garry's mod tab, and 3 minutes later, when i come back, i see this: 
![image](https://user-images.githubusercontent.com/42521608/45221116-225cc880-b2b9-11e8-95f7-10c602388018.png)

I was coding a expression2 chip that had multiple code lines creating B-W dots on a 512x512 screen. 
(
image:
![image](https://user-images.githubusercontent.com/42521608/45221064-fa6d6500-b2b8-11e8-84b4-2959d33b36e6.png)
)

Updating the screen with the tool seemed to fix that back to the original image above, but idling 5 minutes outside the garry's mod tab brought it again:

![image](https://user-images.githubusercontent.com/42521608/45221178-50daa380-b2b9-11e8-85eb-37835ced505c.png)

If it's neccesary, i can upload the code of the chip itself for testing.

**Comment by thegrb93** [comment]
Was the e2 drawing to the screen while you were tabbed out or was it just idling?

**Comment by PhoenixBlack** [comment]
It's possible it's not a bug, but you just overwrote the value in memory that indicates screen resolution?

**Comment by Andrew-Eathan** [comment]
hmm. maybe it did overwrite the values. though, it did it a second time and the longer i'm tabbed out the more "stretched" the y axis gets. the value which was incrementing and was currently writing to the screen, which was also way out of bounds to overwrite any important values. not sure what's the actual issue here

**Comment by thegrb93** [comment]
You still didn't answer my question.

**Comment by Andrew-Eathan** [comment]
yes, it was drawing while tabbed out

**Comment by thegrb93** [comment]
My guess is the viewport size is affected by tabbing out of the game, but it needs testing to be sure.

**Comment by thegrb93** [comment]
What OS are you using?

**Comment by Andrew-Eathan** [comment]
windows 7 (professional edition)

**Comment by Andrew-Eathan** [comment]
anything new?

**Comment by thegrb93** [comment]
I'll try it, but I'm on a machine with integrated graphics right now and won't have my rig until next month.

**Comment by thegrb93** [comment]
If I can get the code you're using, that would make reproducing it a lot easier too.

**Comment by thegrb93** [comment]
Yeah, couldn't reproduce it. Probably need your code or a different machine.

```
--@name DigitalScreenTest
--@server

local wl = chip():isWeldedTo():getWirelink()
wl[1048569]=2
wl[1048572]=512
wl[1048573]=512
for i=0, 512*512-1 do
    local col = Color((((i%512)+math.floor(i/512))/1024*360+180)%360-180,1,1):hsvToRGB()
    wl[i]=bit.bor(bit.lshift(col.r, 16), bit.lshift(col.g, 8), col.b)
end
wl[1048575]=1
wl[1048575]=0
```
![screenshot from 2018-09-16 14-55-14](https://user-images.githubusercontent.com/6713261/45599824-8ae62c80-b9c0-11e8-9c42-770bd8541313.png)

**Comment by thegrb93** [comment]
I did notice that digital screen still overflows reliable channel.

**Comment by Andrew-Eathan** [comment]
alright hang on gonna find the code

**Comment by Andrew-Eathan** [comment]
damnit, i must have forgotten to save the code, but i'll see if i can recreate the bug later. After all it was a 30-40 lines of code chip which will be easy to re-code.

**Comment by Andrew-Eathan** [comment]
nevermind, i've found the code, currently re-testing to see if it still can be reproduced

**Comment by Andrew-Eathan** [comment]
alright it still works, here's the code and a screenshot


https://pastebin.com/GdiF7BSA

**Comment by Andrew-Eathan** [comment]
anything new?

**Comment by TomyLobo** [comment]
@thegrb93 seriously? didn't someone port that over to net a long time ago?

**Comment by thegrb93** [comment]
There's been recent changes to speed it up that probably reintroduced that issue.

**Comment by Andrew-Eathan** [comment]
anything on the digital screen warp issue yet?

**Comment by thegrb93** [comment]
Won't have my windows computer until after Oct 6.

**Comment by Andrew-Eathan** [comment]
i'm using Windows 7 Ultimate 64-bit + GeForce 7300 GT. probably could be driver specific but i seem to be able to reproduce the same bug on my other computer with more buffed up specs

**Comment by thegrb93** [comment]
I'm willing to bet Windows 7 does handle alt+tabbed windows differently. In my experience it also crashes a lot more which is why I prefer 10, but I think this can be summed up as an OS issue unless you can reproduce it on windows 10.

**Comment by bigdogmat** [comment]
This is caused by what @PhoenixBlack said above.

The screen width and height locations are at `1048572` and `1048573`. You'll eventually hit those numbers above and overwrite their values with random data.

Given a 66 tick server here's when you'll overwrite those values

Height:

| Seconds Passed | 
| --- |
| 588 |
| 1134 |
| 1323 |
| 1323 |
| 1765 |
| 2269 |
| 3971 |
| 5295 |
| 5295 |
| 5295 |
| 7943 |
| 15887 |

Width:

| Seconds Passed |
| --- |
| 15887 |

The reason there's multiple for height is because many of the numbers you're multiplying by are factors of its address. This is why you see it change over longer periods of time.

**Comment by oldmud0** [comment]
Wow, I can't read.
