### ISSUE TITLE
Digital screen still overflows reliable channel

### ISSUE THREAD

**Issue by thegrb93** [wiremod/wire#1723]
Splitting net messages into 65536 byte chunks isn't enough. If too much gets queued in source's internal buffer, it disconnects the player with Reliable channel overflow.

What's the limit? idk, but in my experience, a ping/pong method works best. Server sends data to client, client sends message back when completed, server sends next chunk of data. Right now it just stuffs everything into the reliable channel buffer and overflows it.

**Comment by thegrb93** [comment]
I'm adding crash label since that's practically the effect it has.

**Comment by thegrb93** [comment]
Maybe I can finally employ the net library I wrote for this.

**Comment by TAbdiukov** [comment]
Although the mods marked this as a big, this is actually a feature preventing from spamming. You can try this simple example - make an e2 chip/gate that spans a very large string (fror example of size 2^20) and then wire it to some other wire device that uses Strings (for example, Text Screen - Font) and you'll get the same thing.

**Comment by TAbdiukov** [comment]
Here is the example code,
`
@name TTest
@inputs 
@outputs T:string
@persist 
@trigger 

interval(1)

while(perf())
{
    T = toChar(random(255)):repeat(2^19)
}
`

**Comment by CaptainPRICE** [comment]
PVS is a b*tch.

**Comment by thegrb93** [comment]
I'll do this tonight
