### ISSUE TITLE
Cannot wire anything

### ISSUE THREAD

**Issue by Rukia1727** [wiremod/wire#1726]
Everything works, I can go through the tools list, spawn in a button, etc, but when I try and wire a contraption I go and left click using the wire tool to the set variable or whatever in the button and it doesn't do a thing. Nothing, doesn't select it, doesn't register it at all. I've cleaned out my GMAs, I've gone through settings, everything and cannot get wiremod to work at all. I can spawn in things, but I just cannot wire them. I cannot find anyone else with this issue and have been trying to figure out what is going on and still cannot find out what is going on. I've gone through literally all of my addons and still nothing has fixed this issue. Unless wiremod has changed how to wire things with the wire tool I don't know what is wrong and it is getting frustrating trying to figure out what is wrong. If anyone knows what is causing this issue I'd love to know about how to fix it.

**Comment by thegrb93** [comment]
I don't think anyone knows what's wrong. Probably a bad install or conflicting addon.
