### ISSUE TITLE
E2 spawned props limit bug

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/wire#1727]
Let's say the prop limit is 200 props.
When spawning a lot of props with E2, it hits the limit, but when i spawn a regular prop, it spawns it in, even though technically the limit has been hit. It goes on until there are 200 regular props. That way i could have 400 props spawned at once, even though the limit is 200. Is this a bug or is it just me and there is a feature for that?

**Comment by thegrb93** [comment]
Looks like it's because it doesn't call the PlayerSpawnedProp hook so the prop doesn't get added to the props counter.

**Comment by thegrb93** [comment]
Nevermind, MakeProp takes care of that. Can't reproduce, must be 3rd party addons.
