### ISSUE TITLE
Holograms are white cubes

### ISSUE THREAD

**Issue by NinjasInMyBasement** [wiremod/wire#1728]
Hello! Any expression2 holograms turn out to be cubes, usually white but not always. All the solutions point toward wire_holograms_modelany 1 being a command that I need to type, but it is a nonexistant command for whatever reason. I have a workshop install of wiremod

**Comment by shadowscion** [comment]
The command [certainly does exist](https://github.com/wiremod/wire/blob/a421bc388293448bafb823dd03c0ee3ec03a6143/lua/entities/gmod_wire_expression2/core/hologram.lua#L16), and must be passed through the server console or placed in the server cfg.
