### ISSUE TITLE
Issue with the new functionality of Pod Controller's Hide HUD input

### ISSUE THREAD

**Issue by ghost** [wiremod/wire#1730]
Finally, Hide HUD no longer hides EGP HUD's... except in the following case:
A vehicle has an EGP HUD linked to it as well as a Pod Controller. Pod Controller's "Hide HUD" input is set to constant one via a wirelink connection right after the contraption is spawned.

For me, it works as intended, the HL2 HUD is hidden, but chat and EGP remain visible. If someone else sits in my vehicle however, they don't see any HUD. The EGP is set up in a way that it is independent of screen resolution, and it works just fine for the other player if I comment out the line in the E2 that sets Hide HUD to 1.

**Comment by thegrb93** [comment]
@c9787af03d0b3cd90f06 can you look at this. I've almost got my windows machine so I will as well soon.

**Comment by c9787af03d0b3cd90f06** [comment]
I tried to test this but I am unable to replicate the bug. Hooked up a pod controller and simple EGP HUD to a seat, and an E2 to set "Hide HUD" to 1 via wirelink after dupefinished. Everything works as expected for all players.
