### ISSUE TITLE
E2 reset() function seems to ignore @autoupdate directive

### ISSUE THREAD

**Issue by HungarianPatriot** [wiremod/wire#1731]
Expression 2's reset() function, which is supposed to reset the E2 "as if it was newly spawned" seems to ignore the @autoupdate directive -changes I made and saved to the E2 file did not appear on an already palced chip after it ran the reset() function.

**Comment by Divran** [comment]
The autoupdate directive only runs after pasting the e2 from a dupe. https://github.com/wiremod/wire/wiki/Expression-2#autoupdate_directive
