### ISSUE TITLE
Wire entities don't change transparency no matter the alpha set

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/wire#1732]
The wiremod entities don't seem to be affected by alpha unless it's 0 or 255. That means it can only be transparent or visible which would be a bit annoying sometimes if, say, i wanted to make a wire entity partially visible so it wouldn't be covering the surface it is placed on, but still a bit visible for changes to be done.

**Comment by thegrb93** [comment]
Nevermind, it's the rendergroup that needs to be set.

**Comment by thegrb93** [comment]
RENDERGROUP_TRANSLUCENT and RENDERGROUP_BOTH allow the alpha to work. That's why it works when you hover the cursor over it since it gets set to RENDERGROUP_TRANSLUCENT when that happens
