### ISSUE TITLE
EGP delayed

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#1736]
ok so i have a simple screen e2 (for a door lock e2) and when i use it the EGP randomly gets delayed why?

**Comment by thegrb93** [comment]
EGP uses a queue for its networking which can be slow

**Comment by deathking61** [comment]
they should find a way to actually make it a little faster and it also seems there is a delay in using an EGP hud for a speedometer why?

**Comment by thegrb93** [comment]
It's an over 8 year old system sending rendering logic from server to client. It is slow and I don't think that can be improved.

https://github.com/wiremod/wire/blob/976f6ed9d2226367e842e95394c2079f7bcb395e/lua/entities/gmod_wire_egp/lib/egplib/queuesystem.lua

Starfall would give you better results.

**Comment by deathking61** [comment]
i understand that but i cant use Starfall as it doesn't have functions i need and its (to me ) a pain to code with

**Comment by thegrb93** [comment]
You can report that to the github there, or the discord server will be happy to help too.

**Comment by deathking61** [comment]
well, I'm mainly stating this as Starfall has no delay but egp does? I believe EGP should have some "work done" so it to has less of a delay. cause I know if plenty of people who have told me that egp would be better if not for the delay. now i know why it does, but don't you think we should have it lag less behind?

**Comment by Divran** [comment]
The delay in egp is intentional to prevent people from lagging servers and players with it. You can disable the delay with a convar but that will absolutely completely destroy your FPS, so I wouldn't recommend it.

EGP is made for static content or menus, nothing more. If you need lots of FPS for games and the like, your only two options are GPU and Starfall.
