### ISSUE TITLE
EGP huds turn off after a huge lag spike

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/wire#1737]
when a huge lag spike happens usually after it my EGP huds spawned and enabled get "disabled" even though they're still enabled, by that i mean it's like all objects on the egp hud dissapear and i have to go to the egp hud and disable and re-enable it again

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/blob/ae50a27881d4568f6366fed4d3940cb20be25e5c/lua/entities/gmod_wire_egp_hud/cl_init.lua#L99

There's the problem. OnRemove will get called on large lagspike.

**Comment by thegrb93** [comment]
```lua
function ENT:OnRemove()
	timer.Simple(0,function()
		if not self:IsValid() then
			EGP:RemoveHUDEGP( self )
		end
	end)
end
```
Should fix it

**Comment by thegrb93** [comment]
There's https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_egp_hud/huddraw.lua#L65 anyway too, so could just get rid of the OnRemove
