### ISSUE TITLE
freshly created plug and sockets connect to ports even though the data type is different

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/wire#1739]
it seems that duping a plug or spawning it will connect to a nearby port even though their data type is different. by this i mean i create a socket with, say, the data type being number, and a plug with data type array, and they seem to connect with each other, including with their own data types. this didn't happen before, and i noticed it a few days ago.

**Comment by thegrb93** [comment]
I don't see any logic in the data port code that would stop it from connecting if data type is different, nor any changes in the history. I can test it when I get home, otherwise I don't think it's an issue.

**Comment by thegrb93** [comment]
How do you get plug/port with another data type? The ones I see are number only.

**Comment by Andrew-Eathan** [comment]
https://puu.sh/BZps3/8bd41b7c9b.mp4

**Comment by Divran** [comment]
if I remember correctly that's intended behavior. If the type is different
it'll read the first four entries of the array (only if they are numbers)
and pass that to the other end. Same when writing.

**Comment by TomyLobo** [comment]
@Divran that doesn't sound right...

**Comment by Divran** [comment]
@TomyLobo yes
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_plug.lua#L85-L112

**Comment by thegrb93** [comment]
I still have no idea what the problem is.
