### ISSUE TITLE
Ignore World and Hit Water ranger flags incompatible

### ISSUE THREAD

**Issue by MagnumMacKivler** [wiremod/wire#1740]
I found this issue after my server updated with one of the more recent SVN updates.

Previously, using an E2 ranger with Ignore World set to 1 and Hit Water set to 1 meant the ranger would hit water, but not any other world geometry like brushes, displacements, etc. 

Now, it seems, E2 rangers treat water identically to other world geometry as far as Ignore World goes. They will not hit water at all if IW is set to 1, and if IW is 0 and HW is 1, they will hit water and solid world geometry indiscriminately.

I realize this is probably intentional as water in source is technically world geometry. However there's no simple way to detect now if a ranger is positively hitting a water brush. I've been experimenting with fixes such as searching the hit texture for the string "water" but that seems a little clunky for something that used to be so efficient and straightforward.

My suggestion is to either revert E2 rangers back to their old behavior or to include a new function that shows whether or not a ranger is hitting water specifically.

Normal Wire Rangers do this as well, as I determined by experimentation.

**Comment by thegrb93** [comment]
Set ignoreworld to 0 and then check for hitWorld() in your trace. If it hits water I think hitWorld will return 0.

**Comment by thegrb93** [comment]
It actually was hitting world geometry before, but it was reporting that it wasn't.

**Comment by thegrb93** [comment]
If that doesn't work. Lemme know if that doesn't work

**Comment by MagnumMacKivler** [comment]
You mean like this?
```
@outputs Hit HitWorld
@model models/props_junk/TrafficCone001a.mdl

interval(100)
rangerIgnoreWorld(0)
rangerHitWater(1)

R = ranger(64)
Hit = R:hit()
HitWorld = R:hitWorld()
```

When HitWater is set to 1, the hitWorld() ends up giving a 1 regardless of whether the ranger is pointing at water or land.  If it's set to 0, it behaves as expected, and only returns 1 when it hits solid geometry.

The more I think about it the more adding a function like, for example, XRD:hittingWater() makes sense. If my understanding is correct the whole thing that sparked this issue was a fix involving rangers in the world, so it's probably not a good idea to simply revert the code.

**Comment by thegrb93** [comment]
Let me see how the code previously checked for water

**Comment by thegrb93** [comment]
Ok, I think the masks need to be reworked

**Comment by thegrb93** [comment]
I have a script that will hopefully brute force the correct mask values since the wikis are so vague on how they work. Will try tomorrow.

**Comment by thegrb93** [comment]
I can't find any way to make a trace hit water but not world. The problem was there before as well, but it just pretended it wasn't. I don't think I can fix this.

**Comment by thegrb93** [comment]
I tried brute forcing masks and didn't find a working combo. Might need collision groups or other flags, but I'm tired of looking.

**Comment by thegrb93** [comment]
Nvm found it. Just need to find one that hits entities and water but not world now.

**Comment by MagnumMacKivler** [comment]
If it helps, in my specific application where I found the error I had Hit Entities set to 0. The example E2 I threw together didn't have it but I didn't think it was relevant at the time.

**Comment by thegrb93** [comment]
Yeah, your use case is solved, but there's one more in that logic tree that needs to be solved.
