### ISSUE TITLE
a lot of plug and socket errors appear when a E2 processes certain port inputs

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/wire#1751]
basically for some reason every time my complex E2 processes a wire keyboard's input, like enter or other stuff, it returns an error in console. sometimes it does it alot and lowers my fps down to a crisp. here's a recording:
https://puu.sh/BZpGZ/cc3d90c183.mp4

mostly the errors happen when im trying to read the array output of the socket
i know this issue has something to do with plug and sockets because if i disconnect the keyboard the errors stop
is this really a bug or is it my e2 that causes these errors?

**Comment by Andrew-Eathan** [comment]
nevermind the errors continue to persist even after the keyboard is disconnected i'll do more tests

**Comment by Andrew-Eathan** [comment]
heres the console error log that keeps persisting:

] by Player [3][AndrewEathan]):
lua/entities/gmod_wire_socket.lua:142: attempt to call method 'SetValue' (a nil value)
stack traceback:
	lua/entities/gmod_wire_socket.lua:142: in function <lua/entities/gmod_wire_socket.lua:140>
	[C]: in function 'xpcall'
	lua/wire/server/wirelib.lua:57: in function 'TriggerInput'
	lua/wire/server/wirelib.lua:529: in function 'TriggerOutput'
	lua/entities/gmod_wire_expression2/init.lua:492: in function 'TriggerOutputs'
	lua/entities/gmod_wire_expression2/init.lua:152: in function 'Execute'
	entities/gmod_wire_expression2/core/timer.lua:13: in function 'Execute'
	entities/gmod_wire_expression2/core/timer.lua:28: in function <entities/gmod_wire_expression2/core/timer.lua:27>

**Comment by TomyLobo** [comment]
Remove all your other mods, spare change, belt buckles, key chains and other metallic objects and try again.

**Comment by thegrb93** [comment]
@Andrew-Eathan Need a way to reproduce the error or we can't help

**Comment by Andrew-Eathan** [comment]
the E2 itself needs some other chips and the entire PCB including the other components like keyboard and wireless screen tech to work so should i send them all?

**Comment by thegrb93** [comment]
A advdupe file would work yeah

**Comment by Andrew-Eathan** [comment]
the problem is i'd need to send the entire 700 lines of code computer because i couldn't recreate it with a test E2, but i'll take the code that manages the plug/socket stuff and put it in one chip

**Comment by thegrb93** [comment]
good grief

**Comment by thegrb93** [comment]
Can't do anything without more info.
