### ISSUE TITLE
PropSpawn does not work entirely

### ISSUE THREAD

**Issue by e2sallad** [wiremod/wire#1752]
Whenever I try to use PropSpawn I receive the following error:
`sv: Expression 2 (generic): lua/includes/modules/duplicator.lua:270: bad argument #1 to 'SetPos' (Vector expected, got number)`
I did not use any extensions when I was testing it. To reproduce this error, I've used the following script:
```
@name 
@inputs Button
@trigger all
if(Button) {
propSpawn("models/props_c17/oildrum001.mdl",entity():pos(),0)
}
```
I've disabled everything except Wiremod, and I still receive this error.
(P.S: Second time writing an issue on GitHub, pardon my incompetence if I haven't specified some detail.)

**Comment by CaptainPRICE** [comment]
@e2sallad 
Please declare which wire version you are having. (Submit `wireversion` into the console, and post back the response here.)
Also, you should be using the most recent git version when reporting such issues.
And only have wire addon loaded (which you stated you have).
With that said, I have tried to reproduce the error in singleplayer, and failed.
You haven't stated that you have to wire the input `Button` from E2 to the Wire button's output `Out`, and use/trigger the button. I've tried it again, and failed. A prop is spawned successfully after I use the button.

/cant-reproduce
/need-more-information

**Comment by thegrb93** [comment]
Worked for me

**Comment by e2sallad** [comment]
The version I'm currently using is 'Workshop'. I think I should also state the fact that I'm using Garry's Mod chromium branch, since this might play some role in this case.

**Comment by e2sallad** [comment]
Still waiting for a reply.

**Comment by thegrb93** [comment]
Related to https://github.com/wiremod/advdupe2/issues/157

**Comment by e2sallad** [comment]
So, case closed, I guess?

**Comment by robotboy655** [comment]
It doesn't work because MakeProp global's arguments were changed ( since some of them were unused ), but I didn't expect addons to directly call it. I will change it back.

**Comment by e2sallad** [comment]
Well, it seems that's about it for this bug. Thank you, gentlemen. I'll close the issue once the bug's fixed.

**Comment by thegrb93** [comment]
Strange that advdupe2 is erroring. It should be using its own MakeProp function. I'll look into that.
