### ISSUE TITLE
E2: #endif token is not checked?!

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1753]
Running off [`Wiremod's version: 'Git 84dcff6'`](https://github.com/wiremod/wire/commit/84dcff60b377d214b4af4ddce43dc57405312bfc).
(Garry's Mod version: `2018.10.10` - current public branch)

1. Spawn E2 chip using the following code:
    ```golo
    @model models/props_junk/cardboard_box004a.mdl
    #ifdef effect()
        print("'effects' extension is available.")
        local XEF = effect()
        print(XEF)
        #ifdef propSpawn(string, number)
            print("'propcore' extension is available too.")
            local Prop = propSpawn(entity():model(), 1)
            print(Prop)
        #else
            print("'propcore' extension is not available!")
    #else
        print("'effects' extension is not available!")
        print("Bail. Legacy stuff...")
        #ifdef propSpawn(string, number)
            print("'propcore' extension is available.")
            print(propSpawn(entity():model(), 1))
        #else
            error("'propcore' extension is not available neither!")
    ```
2. Fap.

(Above is only just a sample mini-code in order to reproduce the bug.)
Notice there are no `#endif` tokens to end their starting `#ifdef`.
Parser seems to be happy and reports: "Validation successful".
Even worse, E2 runs fine!

Sample output:
By running above E2 with `effects` extension,
- Disabled:
It runs the code below the first `#else`.
- Enabled:
It runs the code between the first `#ifdef` and `#else`.

**Comment by CaptainPRICE** [comment]
No replies still.
Is this a feature, or, a bug?

**Comment by Divran** [comment]
I don't know who the original author of `#ifdef` is so can't ask them. But regardless, since obviously as you yourself proved, it works flawlessly either way, I'm just gonna consider this to be a feature.

**Comment by TomyLobo** [comment]
That would be me.
I think he's right, it's not checked.
Does it matter, though?
You can even put multiple `#else`s and it'll flip back and forth, the implementation is rather primitive :)

**Comment by Divran** [comment]
feature™️

**Comment by CaptainPRICE** [comment]
Cool. Discovering unknown parts of E2 erry'day! 🙌
