### ISSUE TITLE
Syntax highlighting for #ifdef seems borked

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1755]
Running off [`Wiremod's version: 'Git 84dcff6'`](https://github.com/wiremod/wire/commit/84dcff60b377d214b4af4ddce43dc57405312bfc).
(Garry's Mod version: `2018.10.10` - current public branch)

Here is a screenshot of how it looks like (given that, all of the builtin extensions are disabled/off):
![Screenshot](https://user-images.githubusercontent.com/9789070/48513413-0565e800-e85c-11e8-902f-4a38d3f6a358.png)

See, `effect()` is highlighted red as there is no such function, but what's up with `ranger(number)`?!
There is no `ranger(n)` function in E2Helper, of course because `ranger` extension is disabled. But, why is it colored differently then?

Also, you can observe how it picks up the color of UDF. It just makes confusion. `#ifdef` doesn't even work for UDFs, because it is not even intended to. So, why does it color them?

Syntax highlighter seems borked, and should be cleaned up.

**Comment by TomyLobo** [comment]
Yeah, `#ifdef` is part of the preprocessor, so it cannot catch UDFs, which are only available at parsing time (or was it run time?)
Anyway, since it doesn't make sense to ifdef a UDF anyway, the tiny mis-highlight doesn't really affect anyone.
If you can fix it and guarantee there are no side-effects, go for it.
Otherwise, better to leave the mis-highlight in.

**Comment by bigdogmat** [comment]
Fixing the highlighting just would just a matter of changing how the highlighter works.

**Comment by TomyLobo** [comment]
And that is precisely why I worry :)
yeah, probably you need to split udf highlighting from regular function highlighting and only allow regular function highlighting after an #ifdef

**Comment by CaptainPRICE** [comment]
Note, this is not just about UDF mishighlighting. See how `ranger(number)` function is highlighted like it exists, but it doesn't because `ranger` extension is disabled. It should be red, just like it is for `effect`; which is the only one correctly highlighted in this case.

**Comment by TomyLobo** [comment]
Did it myself. Needs testing.

**Comment by bigdogmat** [comment]
They should all be highlighted like they exist, at least that's how I think it should be.

**Comment by TomyLobo** [comment]
yeah the last thing you described is actually correct behaviour

**Comment by CaptainPRICE** [comment]
> They should all be highlighted like they exist, at least that's how I think it should be.

Not a good idea.

**Comment by TomyLobo** [comment]
This is how Visual Studio highlights undefined symbols after after an `#ifdef`:
![image](https://user-images.githubusercontent.com/963797/48612242-b669a100-e988-11e8-935d-312cfba6c1e0.png)
I suggest we follow that well-established example.
