### ISSUE TITLE
inGodMode() is no working

### ISSUE THREAD

**Issue by bujtasadam** [wiremod/wire#1758]
E:inGodMode() function is not working. The editor is marking it whith red caracters.

**Comment by thegrb93** [comment]
Works for me

**Comment by bujtasadam** [comment]
how can i check my wiremod version?it may be helpful

**Comment by thegrb93** [comment]
I don't think it ships with the revision number. Just try updating to this one and see if it works.

**Comment by bujtasadam** [comment]
here is a screen shot
http://www.kepfeltoltes.eu/images/2018/11/385e2error.png

**Comment by thegrb93** [comment]
That doesn't help unfortunately.

**Comment by bujtasadam** [comment]
i use this version:
https://steamcommunity.com/sharedfiles/filedetails/?id=160250458&searchtext=wiremod
and gmod:
chromium 2018.11.01 (Year.month.day)

**Comment by bigdogmat** [comment]
Our workshop was last updated July 7th, `inGodMode` just was added to the repo in August 30th. It's not on the workshop version yet.

**Comment by bigdogmat** [comment]
We usually plan them at the beginning of months, however we haven't done one in quite a while. We might do one next month.
