### ISSUE TITLE
Digital Screen's data is not being duped

### ISSUE THREAD

**Issue by TAbdiukov** [wiremod/wire#1765]
Digital Screen's data is not being duped.

Try writing something to it and then duping it. The data will then get lost

**Comment by Andrew-Eathan** [comment]
that could be intended behavior or something but assume you're saving a 512x512 screen, which would be an extra 262144 bytes to the dupe file which would be a lot of bytes for just one dupe file
you could create a device that uses fileWrite and fileLoad based saving so you will be able to save any stuff you make in screens

**Comment by CaptainPRICE** [comment]
As much as it would be cool, this is most likely going to be rejected for a couple of reasons. I can say them if you want.
Also, wire has nothing to do with this - shouldn't this be over [advdupe2](https://github.com/wiremod/advdupe2) repository?

**Comment by thegrb93** [comment]
@CaptainPRICE no, duplicator functionality is the entity's responsibility.

Like he said though, it would blow up the dupe file size pretty quickly. Advdupe2's default max file size is 200kb so you wouldn't have enough space for it.
