### ISSUE TITLE
E2's fileWrite() terminates on "\0" character prematurely (like C's strcpy)

### ISSUE THREAD

**Issue by TAbdiukov** [wiremod/wire#1766]
Suppose you have the following String

**Index**|1|2|3|4|5|6|7|8|9|10|11|12
--|--|--|--|--|--|--|--|--|--|--|--|--
**HEX**|48|65|6C|6C|6F|00|57|6F|72|6C|64|21
**Char**|H|e|l|l|o|\0|W|o|r|l|d|!|

If you plug it into *fileWrite()* function, it will only write up until \0, i.e. in this example, it will write "Hello", instead of the whole thing; sort of in the same style C's *strcpy()* does the job

**Comment by TAbdiukov** [comment]
As a side note, one of the possible solutions could be to implement something like *file**n**Write()*, which, similarly to C's *strncpy()* would require the string length along with the string to be passed

**Comment by bigdogmat** [comment]
Was fairly certain `net.WriteString` respected null characters, guess not. Will need to change it to use `net.WriteData` alongside writing length.

**Comment by CaptainPRICE** [comment]
This is a known bug, since old days.
Old wiki had a warning of this.
