### ISSUE TITLE
7-segment display - lack of patters needed for automation

### ISSUE THREAD

**Issue by TAbdiukov** [wiremod/wire#1767]
The issue is very simple but very frustrating

The Wire 7-segment displays are great - they are super fancy and simple. HOWEVER, their biggest issue is that when spawned, they lack any sort of pattern required to automate the wiring process. 

This is not big of an issue for just one just display, but suppose you want to create a 100-characters long billdoard fill of characters, then wiring one will be a nightmare (100 characters * 7 segments * 2 wires (1 wires on one side, one on the other) = **1400 wirings!**, SO and good luck not messing up the order.

I tried to find some sort of the pattern along the segments of the display, and they seem to have pretty much unpatterned entityIds (likely dependent on the currently-free ids) and their constraints are messy.

There is a 'kind of' workaround to the problem, which is to use the Gate - 7-segment encoder/decoder, but it's not present on all the servers, and it also adds some extra computations, which is not good in bulk

I can think of the following solutions to the problem,
* Force the segments of 7-segment display to spawn with the specific order of IDs
* Spawn (or encode into the central segment) some sort of the 'constant value' carrying entity IDs of the 7-segment display

**Comment by CaptainPRICE** [comment]
There is always E2 solution to do it quickly.
Link it up using `entity:createWire`, but iirc that function is in `wiring` core (extension), yep:

https://github.com/wiremod/wire/blob/9ae1f5504f2f1c31bfbd31c51ab4e0bdff5c1ae4/lua/entities/gmod_wire_expression2/core/custom/wiring.lua#L7-L59

**Comment by thegrb93** [comment]
That's the point. Old school wire is about doing really complex shit. Automate everything and it loses its charm.

**Comment by TAbdiukov** [comment]
@CaptainPRICE @thegrb93 

I'm afraid you both misunderstood the issue. Yes, I know about createWire() and I totally agree about the charm statement. 
 
The issue is this

![7](https://upload.wikimedia.org/wikipedia/commons/e/ed/7_Segment_Display_with_Labeled_Segments.svg "7")

In Wiremod, each of the 7 segments of the indicator have their unique entId's. And there seemingly is no pattern among the segments helping to determine is some entity is a part of an indicator.

> That's the point. Old school wire is about doing really complex shit

Funny there is a workaround to this issue without "complex shit", which is to use 7-segment encoder/decoder gate, which allegedly does work around this issue somehow, how it obviously adds extra computations and isn't so good for complete automation

P.S. As I'm writing this comment, I think I may have found a way to tell. Be right back

**Comment by thegrb93** [comment]
You can localize their positions relative to some reference point and sort them based on their coordinates. I recommend looking at the toLocal function for that.

**Comment by CaptainPRICE** [comment]
> In Wiremod, each of the 7 segments of the indicator have their unique entId

Are you referring to the `entity:id()`?
If so, that is an entity index or "identifier" (just a *random* number), which is given to an entity while engine is at constructing a new entity. Not much of a use for what you need it.

If you were only able to create those using an E2... See #1770

**Comment by TAbdiukov** [comment]
> You can localize their positions relative to some reference point and sort them based on their coordinates. I recommend looking at the toLocal function for that.

I know this issue is closed, but figuring out coordinates of the entities (as a side note, different sizes of the 7-segment displays obviously use different offsets) and then localising them to the entities seems a bit like overkill. 

For the future reference, I found a much easier and simplistic solution. In the latest versions of wiremod the segments of the display are properly constrained (unlike some time ago), and so you can just use the following code to figure out the patterns the segments are constained

```
@name LookAtTest
@inputs 
@outputs AE:entity ConTo:array
@persist [E O AE]:entity 
@persist I TE1:entity
@trigger 

interval(1)

if(first())
{
    E = entity()
    O = owner()
}

AE = O:aimEntity()
ConTo = array()
I = 0
while(I <= 10)
{
    TE1 = AE:isConstrainedTo(I)
    if(TE1:id() > 0)
    {
        ConTo = ConTo:add(array(TE1))
    }
    I++
}
```

As for we, the segments are constrained in A...G order, skipping the segment you are checking, followed by the external constraints (i.e. the entity to which the display is it 'glued to'  and so on)

**Comment by thegrb93** [comment]
I don't think the constraint order will be the same after duplicating the entity.
