### ISSUE TITLE
[Suggestion] Add basic music instrument sounds as a mainstream to wiremod

### ISSUE THREAD

**Issue by TAbdiukov** [wiremod/wire#1769]
Perhaps this should've went to the GMod github, but since they don't have a repo i'll post that here.

I suggest addihng basic instrument sounds as a mainstream to wiremod. Unfortunately, GMod seriously lacks them, and lacking them prevents from writing the comphisticated music synthesister systems using any other sounds other than the sounds in the /synth/ directory

**Comment by Divran** [comment]
https://github.com/wiremod/wire/tree/master/sound/instruments

https://github.com/wiremod/wire/tree/master/sound/synth

already exists

**Comment by TAbdiukov** [comment]
Oh good to see there's been this improvement since the time I was fristrated with that! :+1:
