### ISSUE TITLE
Weird Behavior with #include

### ISSUE THREAD

**Issue by kbarber1998** [wiremod/wire#1776]
So with the newest update to wiremod that is released to the workshop, I noticed some weird behavior with "#include "
I narrowed it down to when you include another file that has some kind of a "print()" in the "if(first())", it causes all following "print()'s, printColor()'s, hint()'s" to not show up at all on the hud/chat/console. And the only way to fix the bug is to reconnect to the server, the server is running AtlasChat, so that may have an effect on it, but I doubt as hints and prints to console wouldn't show up either.

Here's My Code.
Main:
```
interval(1000)

if(first()){
    #include "testBug"
}
customFunc()
```

Include File "testBug.txt":
```
if(first()){
    print("testBug.txt included")
    
    function void customFunc(){
        print("called function")
    }
}
```
If you were to remove the "print("testBug.txt included")" the e2 would work as intended. Just some strange behavior that I found

**Comment by thegrb93** [comment]
Latest version of wire doesn't have this issue.

**Comment by thegrb93** [comment]
I'm referring to the github version, not the workshop one.

**Comment by CaptainPRICE** [comment]
@kbarber1998 Before reporting issues, please, make sure that server is running on the 'latest' version of Wire from GitHub. You can check your Wire version by using `wireversion` console command.

/external compatibility
/unable-to-reproduce
