### ISSUE TITLE
Enhance use of direct memory accessing among the wire-entities

### ISSUE THREAD

**Issue by TAbdiukov** [wiremod/wire#1777]
[Suggestion][Epic] Enhance use of direct memory accessing among the wire-entities

For example, for digital screen D, the direct memory accessing would be D[5] = 5000

Why? Multiple reasons
1. It's super exciting! Some wire-entities support undocumented functionality accessible only via direct memory accessing
2. Wouldn't that be 'wiremody' to set things up in such a hacky way, instead of figuring out the names of inputs & outputs?
3. In issue #1770 , @bigdogmat says
> Every entity has a different set of parameters required to set it up. Unless we hard code every entity there's not really a safe way to do this.

The use of direct memory set up could be a relatively easy solution to this problem

**Comment by thegrb93** [comment]
You're forgetting that everything the user sets has to be sanitized. You can't trust outside data.

**Comment by TAbdiukov** [comment]
> You're forgetting that everything the user sets has to be sanitized. You can't trust outside data.

@thegrb93 Yes. thats right. However, I believe the entity class/type, colour, position, angles and the primitive inputs are easily sanitised, am i not right?

**Comment by thegrb93** [comment]
Those don't have anything to do with the 'direct memory' you're referring to.

**Comment by TAbdiukov** [comment]
Oops, my apologies. Yes, that's right, sorry for this. Thanks for helping me sort this out in my head

I know it looks as if I push for this, but whatever way we do that, can't we inherit the functions sanitizing the user input user for the normal entity-spawning ?

**Comment by thegrb93** [comment]
The toolgun functions can be used for setting up most entities. A table of strings can be used for the options which is how the toolgun currently works. The other issue would cover all that.
