### ISSUE TITLE
Add Switch Statements and Enums to Wiki

### ISSUE THREAD

**Issue by MagnumMacKivler** [wiremod/wire#1786]
I've been coding in E2 for the better part of seven years (E2 was my first programming language and it's the only one I'm fluent in), and I consider myself to be halfway decent at it. I'm always finding new things I didn't know about. Like, for example, when I discovered Switch statements _by accident_ when I forgot to capitalize a variable. Thankfully I was able to figure out the syntax by trial and error!

Switch statements aren't covered on the Expression 2 Wiki page, and I feel like they really should be, because they're a really handy base-level feature like loops and if statements. And the wiki, even as out-of-date as it is in some regards, is still the number 1 resource I use when trying to figure something out in E2, and it's where I point people to when they come to me with questions that I can turn into learning opportunities.

Of course, it's one thing to identify a problem and another to actually propose a solution, so here's my idea for what the section should look like.

[start wiki section suggestion]

### Switch Statements

Switch Statements  are a multi-part, expandable code structure that examines an argument and executes code depending on specific cases of that argument's value. They can be a powerful alternative to if-elseif-elseif-[…]-else statements in certain applications.

Syntax:
```
switch(arg){
    case case_1,
    
        break
    case case_2,
    
        break
    default,
    
        break
}
```

A Switch Statement works by examining the value of a single argument (arg). Arg can be any datatype. The cases (case_1 and case_2) represent specific, expected possible values of the argument. If the value of the argument matches one of the cases, E2 will execute any code between the appropriate "case" line and the "break" line. The "default" line and its associated "break" line are **optional**, and will execute when the value of the argument _doesn't match any_ of the specified cases.

Example:

Suppose you have a string variable called "Vegetable". You can only think of three possibilities for Vegetable to be: "carrot", "potato", or "tomato".
For example, `Vegetable = "potato"`
Suppose you then want Expression 2 to tell the user what kind of vegetable the variable represents.
```
switch(Vegetable){
    case "carrot",
        print("You have a Carrot.")
        break
    case "potato",
        print("You have a Potato.")
        break
    case "tomato",
        print("A tomato is not a vegetable.")
        break
    default,
        print("I don't know what that is.")
        break
}
```
What this example will do is examine the value of the string variable "Vegetable". If the Vegetable is "carrot", Expression 2 will print "You have a Carrot." to the chat. If the Vegetable is "potato", Expression 2 will print "You have a Potato." to the chat, and so on. If Vegetable doesn't match any of the predefined cases (as in, it's something other than "carrot" or "potato" or "tomato"), Expression 2 will print "I don't know what that is." to the chat.

You can also do the above example using chained if-elseif-else statements, and the following code will behave identically to the switch statement above:

```
if(Vegetable=="carrot"){
    print("You have a Carrot.")
}elseif(Vegetable=="potato"){
    print("You have a Potato.")
}elseif(Vegetable=="tomato"){
    print("A tomato is not a vegetable.")
}else{
    print("I don't know what that is.")
}
```
Ultimately, it is up to the coder to decide whether to use a Switch Statement or a chain of if statements to accomplish the task.

[end wiki section suggestion]

Please let me know if I'm missing any important syntax features here... I figured it out mostly by experimentation so I might not have all the facts. I'll also be more than happy to take suggestions on the wiki section, since, you know, it's not my wiki in the first place.

On the topic of Enums, I didn't even know they _existed_ until I saw them starting to appear in the E2 Helper, and even now they are so infrequently used that ~~I have absolutely no idea how they work and think they are stupid and pointless and~~ my understanding of them is very limited and I feel they might be potentially very useful if I could figure them out. I am aware many languages make use of enumerations but remember, E2 is my first (and for all intents and purposes, ONLY) programming language. So unfortunately, no suggested section for Enums from me. I'll leave that to the people who actually know what they are and how to use them.

**Comment by CornerPin** [comment]
Switch statement is already briefly described in the *Syntax* section of the *Expression 2* Wiki page and has been there for a long time as I remember.

**Comment by MagnumMacKivler** [comment]
Well I'll be a son of a gun, it is. I don't remember seeing it there for a long time though... maybe it's a recent addition?

I still think the description is a little minimal (and confusing) considering how complicated switch statements can be though. Something that complex really deserves its own section in my own humble opinion.

And of course there's still the issue of Enums.

**Comment by Vurv78** [comment]
Added constants here to close this https://github.com/wiremod/wire/wiki/Expression-2-Features#Example-2

**Comment by thegrb93** [comment]
Thanks
