### ISSUE TITLE
fileWrite appends in end "NUL" simbol

### ISSUE THREAD

**Issue by SomeUselessGuy** [wiremod/wire#1790]
![image](https://user-images.githubusercontent.com/40398890/49327795-8a087400-f587-11e8-97c2-20e9d188706c.png)
fileWrite appends in end "NUL" simbol
code:
`fileWrite("test.txt","test")`

**Comment by CaptainPRICE** [comment]
I'm unable to reproduce this (running on the latest [`master`](becd300f355d857e28ba7c07cbbfdaff9aa58a66) version) using a simple E2:
```golo
fileWrite("test.txt", "Hello World")
```

Inspecting the bytes of the written `data/e2files/test.txt`:

| Hex ASCII | 48 | 65 | 6C | 6C | 6F | 20 | 57 | 6F | 72 | 6C | 64 |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| Char | H  | e  | l  | l  | o  |    | W  | o  | r  | l  | d  |

All good, there is no null terminator at the end.

/unable-to-reproduce

**Comment by CaptainPRICE** [comment]
@OriaOriginal Before reporting issues, please, make sure that server is running on the 'latest' version of Wire from GitHub. You can check your Wire version by using `wireversion` console command.

**Comment by thegrb93** [comment]
Maybe there could be a miscalculation or rounding issue in the ReadData

**Comment by thegrb93** [comment]
I'll try
