### ISSUE TITLE
Github version of Woremod pod controller mouse scroll not working.

### ISSUE THREAD

**Issue by dvdvideo1234** [wiremod/wire#1792]
Hello, 

Mouse scroll does not work when it is wired via wirelink, though it works when wired directly ( without wirelink )

Consider this E2 code which does not work:
```
@inputs On [Pod EntityMaker]:wirelink 
ScrollU = Pod["PrevWeapon",number] > 0
ScrollD = Pod["NextWeapon",number] > 0
```

Now one that works when wirelink is used with no scroll realted buttons:
```
@inputs On [Pod EntityMaker]:wirelink 
ScrollU = Pod["Space",number] > 0
ScrollD = Pod["R",number] > 0
```
Or when the inputs are wored direcly to internal variable inpus
```
@inputs [Wfl Wfr Wbl Wbr]:entity W S A D NextWeapon PrevWeapon
    if(NextWeapon){ GearStep = GearStep - GearVel}
    if(PrevWeapon){ GearStep = GearStep + GearVel}
```

**Comment by Divran** [comment]
Wirelinks don't trigger the e2. The scroll buttons only stay as 1 for one single tick. To make your e2 fast enough to catch that, you need to use `runOnTick`.

Use normal wires or `runOnKeys` instead.
