### ISSUE TITLE
concmd no longer working with empty whitelist

### ISSUE THREAD

**Issue by hobnob11** [wiremod/wire#1794]
Previously, leaving the whitelist empty would allow the user to run any concmd, but a recent update has broken this.

**Comment by thegrb93** [comment]
You're saying the latest one isn't working?

**Comment by CaptainPRICE** [comment]
Yeah, whitelist is broken (running on the current latest version; 8fefeacdb27399376300314e69d1ef3c6cef324e).

My test case:
> wire_expression2_concmd 1
> wire_expression2_concmd_whitelist "say,+duck"

```golo
concmd("kill;say hello;+zoom;+duck")
```

Expected a chat message and duck commands to work, but it seems all of the commands got ignored.

**Comment by thegrb93** [comment]
Glancing at the code, I don't see the problem, but I'll debug later today.

**Comment by Divran** [comment]
@CaptainPRICE no, according to the code, if any of the commands you attempt to run are not in the whitelist, all of the commands are ignored. That's intended behavior.

The problem the OP is having is somehow his whitelist is empty and therefore it should allow all commands, but no commands are being allowed. Which should be impossible.

**Comment by Divran** [comment]
@hobnob11 please try typing `wire_expression2_concmd_whitelist` without arguments so that it prints its current value and check what it's set to

**Comment by CaptainPRICE** [comment]
> intended behavior

Really.
I propose this to be changed then. Leverage the parser.

@thegrb93 Also, I broke out of your barebone parser (`tokenizeAndGetCommands`) due it doesn't match engine implementation. I have successfully executed `kill` (can execute any other command too) while only having `say` in the whitelist.

**Comment by thegrb93** [comment]
So what's the hole?

**Comment by hobnob11** [comment]
wire_expression2_concmd_whitelist returns "", so does the new system allow wildcards or something? can i put say, a `*` symbol to allow all?

**Comment by thegrb93** [comment]
No it doesn't. Try updating, I can't reproduce it.

**Comment by hobnob11** [comment]
It appears the update to wiremod on our server happened right as the pull request was merged, this issue existed on 28358614 but is now gone on 8fefeacd
