### ISSUE TITLE
Allow control of EGP transparency

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#1799]
ok so when i change the EGP screen to any of the PCB models they turn out this way: https://steamuserimages-a.akamaihd.net/ugc/941713065221062269/639BF103DE89CB322C224C232315669FFB3BC546/ 

WHY?

**Comment by Andrew-Eathan** [comment]
same issue here. dunno why it happens

**Comment by thegrb93** [comment]
@Rusketh

**Comment by Rusketh** [comment]
Some reason the monitor for those entities are requesting a transparent rt, or at least that is what would cause that.

**Comment by Rusketh** [comment]
Found the issue:
https://github.com/wiremod/wire/blob/faa9464a2559c2549b86129400c9e3d98b300db8/lua/wire/wiremonitors.lua#L229
The true on the end needs to be false, by default a model not registered on WireGPU_Monitors will be transparent by default.

**Comment by deathking61** [comment]
so if i change it to false it will fix it?

**Comment by deathking61** [comment]
I fell as they should make them so if we wanted to we could make them update in realtime lol to me that would be far better but that's just me (and again give us that option like a console command lol or something)

**Comment by Hazeofdream** [comment]
fixed awhile ago, this can be closed @thegrb93 

https://github.com/wiremod/wire/blob/635b89b82d5773744c7733272ce139d5ab7ed8e5/lua/wire/wiremonitors.lua#L225
