### ISSUE TITLE
Gimbals angle input roll mimicking yaw

### ISSUE THREAD

**Issue by EnragedKoala** [wiremod/wire#1803]
![20181215203217_1](https://user-images.githubusercontent.com/45907361/50049039-3d558a80-00a9-11e9-8b9c-0be30bafaf9b.jpg)
The photo shows 3 gimbals each linked to their corresponding gyroscope. As you can see, one of these things is not like the other! Pitch, Roll, and Yaw, from left to right, are all set to -45, 45, and -45 respectively. Yet Roll (middle) seems a wee bit tipsy, in the wrong axis! I did a full roll rotation of the middle gimbal on the roll axis, and it acted as if I had yaw'd it instead. This is a bit problematic, and it took forever for me to realize that it was the gimbal's fault, and not my e2 code. It should be reproducible, as it seems consistent. Ask me if you need any more info, I will try my best to help.

**Comment by TomyLobo** [comment]
A dupe would probably help.

**Comment by EnragedKoala** [comment]
It should be easy enough to set up, a gimbal, gyroscope, and a button. Plus I don't know how to share dupes, sorry.

**Comment by thegrb93** [comment]
Ya looks like gimble issue.

**Comment by thegrb93** [comment]
Line 60, adding a euler angle is bad math.

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_gimbal.lua#L60

**Comment by thegrb93** [comment]
Instead, an offset angle input that gets saved as a matrix and rotates the target angle would be better.
