### ISSUE TITLE
pod controller isn't taking my mouse1 and mouse2 inputs

### ISSUE THREAD

**Issue by Wheatleyw** [wiremod/wire#1805]
A week or so ago, when I tried to make an ACF car and wire the gear up and down to the mouse buttons, switching gears didn't work at all. Two days ago, I reinstalled GMod and let all my addons install and I moved my data back and it magically worked.

I went to restart as I forgot to install ACF-Custom and it stopped working again. Just now, I disabled all my addons, and it still doesn't work. I used the debugger tool on the pod and it isn't taking input period. Everything else works fine.

This happens in both Singleplayer and Multiplayer, and on Multiplayer, everyone' else buttons work just fine.

Before someone asks, for some reason "wire_PrintVersion" isn't a command. I am only able to get the UWSWN version which is 322. Neither is "condump". Just know that at the time I re-installed, I downloaded a fresh new copy of the master branch.

**Comment by thegrb93** [comment]
Addon conflict probably

**Comment by Wheatleyw** [comment]
Just tested with literally no addons including ACF, Wire Extras, and PAC3. It still doesn't work.

**Comment by Wheatleyw** [comment]
Never mind, you can close the issue. For some reason, even though they were bound to attack and attack2, rebinding them fixed it. It's just a question of "Will it unbind somehow and break again?"

**Comment by thegrb93** [comment]
Should be +attack and +attack2
