### ISSUE TITLE
E2 Compiler Broke

### ISSUE THREAD

**Issue by Ameno-Sagiri** [wiremod/wire#1806]
Was out of Garry's Mod for about a year or two, came back to it. All my expression 2's are broken, even simple ones that just play a sound while being toggled on.

This is using today's wire from github.

```
Internal error - please report to https://github.com/wiremod/wire/issues
addons/wire-master/lua/entities/gmod_wire_expression2/base/compiler.lua:42: attempt to index a nil value

Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 301	"__index"		addons/wire-master/lua/entities/gmod_wire_expression2/core/e2lib.lua
	3: Line 42	"nil"		addons/wire-master/lua/entities/gmod_wire_expression2/base/compiler.lua
	4: C function	"Execute"
	5: Line 74	"wire_expression2_validate"		addons/wire-master/lua/entities/gmod_wire_expression2/cl_init.lua
	6: Line 1595	"Validate"		addons/wire-master/lua/wire/client/text_editor/wire_expression2_editor.lua
	7: Line 1845	"Close"		addons/wire-master/lua/wire/client/text_editor/wire_expression2_editor.lua
	8: Line 1749	"SaveFile"		addons/wire-master/lua/wire/client/text_editor/wire_expression2_editor.lua
	9: Line 859	"DoClick"		addons/wire-master/lua/wire/client/text_editor/wire_expression2_editor.lua
	10: Line 232	"nil"		lua/vgui/dlabel.lua


```

**Comment by bigdogmat** [comment]
Could you post the code used to get this error?

**Comment by Ameno-Sagiri** [comment]
Any E2 I have, but here's a simple one from 2009 that worked up until sometime last year when I last played:
`@name Sound Emitter
@inputs Button
@outputs 
@persist 
@trigger 

if (Button) {
    soundPlay( 1 , 0 , "ambient/music/country_rock_am_radio_loop.wav")
}
else {
    soundStop(1)
}


`

**Comment by bigdogmat** [comment]
That code works just fine, this issue is similar to #1694. I'd suggest reinstalling wiremod and making sure you uninstall any old versions of wiremod. If that doesn't work disable all addons and try again with just wiremod. Last resort is reinstalling Gmod.

**Comment by thegrb93** [comment]
Probably a module or something installed adding the execute function to entities. Weird. It's definitely some kind of conflict though

**Comment by thegrb93** [comment]
Oh nevermind then.
