### ISSUE TITLE
Wire Tool Not Working

### ISSUE THREAD

**Issue by GameFace218** [wiremod/wire#1808]
So Here's my problem: Last month (November 20-24th, 2018) I was home playing Gmod and using Carter's Addon Pack (CAP) and Spacebuild 3. I have had no problems with Wiremod not cooperating with this mod before. From November to now, however, Wiremod isn't working. (Actually, halfway through my session it quit on me so if I might've somehow unbound something let me know) To clarify: I can spawn a wire object and when I look at the object with the basic wire tool the menu comes up like it should (I'm using "explosive" to troubleshoot) but when I click on the object to wire it, nothing happens. I tried uninstalling CAP, as well as any mod that involved the Wire tool and tried again. Same problem. I tried all the ideas on the guide; I cleared my cache and, verified integrity (I downloaded from the Steam workshop so I'm no pirate). Still not working. Now a month later (December 18th, 2018) I tried again and still nothing!

**Comment by thegrb93** [comment]
Nothing happens as in you don't get a toolgun animation or anything? Definitely another mod causing it or your gmod is broke.

**Comment by GameFace218** [comment]
Just spent a few hours troubleshooting. turns out the mod causing the problem is the mod "Weapon Loadouts" by Gorea (https://steamcommunity.com/sharedfiles/filedetails/id=199226357&searchtext=loadout)
