### ISSUE TITLE
[E2] increase holo limits

### ISSUE THREAD

**Issue by EvaneosKOWAR** [wiremod/wire#1813]
I know that Shadowcion asked to increase the limits from 128 to 250 in 2013, but with times knowledge comes, and nowadays i find out that 250 holograms is veryyy short for advanced contraptions, and a small increase such as wire_holograms_max 250 --> 300 would be very useful and would not create a big difference in players experiences !

**Comment by thegrb93** [comment]
>not create a big difference in players experiences !
not if your gpu isn't good

**Comment by EvaneosKOWAR** [comment]
Not really, because a small percent of the players use a lot of holos, and add that the chance that the players has a "bad gpu" (even if i think it has no influence) the chance that small increase of holos limits bother someone is under 2%

**Comment by shadowscion** [comment]
Build more efficiently.

**Comment by thegrb93** [comment]
This is a convar right? Just ask the server owner to increase it.

**Comment by EvaneosKOWAR** [comment]
> Build more efficiently. 250 is plenty. Speaking as someone who has pretty much exclusively used wiremod for holograms for the better part of 8 years.

Well, i'am using only standart props (hq_tube, cube, prism) and if i want to add more details on my creations it quickly increase over 250, so i'll probably try with different props i guess^^
