### ISSUE TITLE
E2 propCanCreate() causes Lua error

### ISSUE THREAD

**Issue by Pollitto** [wiremod/wire#1817]
**Code example:**
`if(propCanCreate()){propSpawn("models/props_c17/oildrum001.mdl", 0)}`
**causes this error**
`sv: Expression 2 (generic): entities/gmod_wire_expression2/core/custom/prop.lua:493: attempt to call field 'WithinPropcoreLimits' (a nil value)
`

**Comment by thegrb93** [comment]
No idea how that error is even possible. The e2 works fine for me. I'd try reinstalling wire or something.

**Comment by JustMrPhoenix** [comment]
Can confirm, running latest version from git(installed using git clone)
![2019-01-07_02-14-24](https://user-images.githubusercontent.com/14361083/50742264-2591a200-1222-11e9-9ae0-02d9841cb718.png)

**Comment by JustMrPhoenix** [comment]
Found the source, E2Power addon was overriding global `PropCore` table
