### ISSUE TITLE
Duplicating an E2 causes tick quota error

### ISSUE THREAD

**Issue by Ruuttu** [wiremod/wire#1827]
This E2 runs fine when spawned normally and doesn't come very close to shutting down. 
However, when it's copied and pasted with the duplicator, it shuts down immediately. The "tick quota exceeded" error is displayed. Same happens with the Advanced Duplicator 2. 

My first suspicion was that the initialization work got done twice when duplicating, but that didn't seem to be the case.

```
@name DuplicationTest 

runOnTick(1)

if (first() | duped()) {
    print("Doing some initialization")
    for (I = 0, 5000) {}
    print("Init done")
}

for (I = 0, 1000) {}
```

**Comment by Andrew-Eathan** [comment]
that for loop at the end looks ops consuming, not to forget the one in the initialization and the runOnTick altogether is probably the cause

**Comment by Ruuttu** [comment]
The purpose of the sample code is to demonstrate the issue. You should observe two things:
1. The code runs on E2 without issue. The ops usage is well below limits, and the E2 does not shutdown even after a period of time.
2. When the E2 is duplicated, the duplicate immediately shuts down.

The E2 limits are 25,000 ops max in a single tick, or 10,000 ops per tick continuously. The sample code should use about 18,000 ops during the first tick, then 3,000 ops per tick continuously.

**Comment by thegrb93** [comment]
I'll test it when I get home

**Comment by thegrb93** [comment]
My guess is the dupe saves it's current ops usage and then when the Init happens, it goes over.

**Comment by thegrb93** [comment]
I see why.

Whenever it's not duped, it executes

**Comment by thegrb93** [comment]
I see why.

Whenever it's not duped, it executes here,
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/init.lua#L465

Then clears its perf in this Think()
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/init.lua#L469


However when it is duped, it skips that first execute, does that Think() that clears perf, then executes here,
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/init.lua#L521


So first() gets its ops cleared right after executing, but duped() does not.

**Comment by thegrb93** [comment]
@Ruuttu see if https://github.com/wiremod/wire/pull/1828 fixes it.

**Comment by Ruuttu** [comment]
Yup, works like a charm. Thanks!
