### ISSUE TITLE
attempting to link EGP hud to vehicle gives lua errors

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/wire#1831]
trying to link a EGP hud to an airboat seat gave this error in console: 

[ERROR] addons/wiremod_160250458/lua/entities/gmod_wire_egp_hud/init.lua:66: attempt to call method 'LinkHUDToVehicle' (a nil value)
  1. LinkEnt - addons/wiremod_160250458/lua/entities/gmod_wire_egp_hud/init.lua:66
   2. RightClick - addons/wiremod_160250458/lua/wire/tool_loader.lua:598
    3. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:250

here's a video:
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/42521608/51611884-f8830600-1f28-11e9-94b4-0170a7a83915.gif)

**Comment by Divran** [comment]
That function is created here https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_egp_hud/huddraw.lua#L93

The error says this function doesn't exist. If the function doesn't exist, then that must mean the file it's in isn't running. Are there any errors in console while the server loads, which could prevent it from running?

**Comment by Andrew-Eathan** [comment]
no errors seem to appear in console

**Comment by Andrew-Eathan** [comment]
removing a contraption with an egp hud or an egp hud itself shows this error in console

[ERROR] addons/wiremod_160250458/lua/entities/gmod_wire_egp_hud/init.lua:74: attempt to call method 'UnlinkHUDFromVehicle' (a nil value)
  1. unknown - addons/wiremod_160250458/lua/entities/gmod_wire_egp_hud/init.lua:74

**Comment by thegrb93** [comment]
The only thing I can think of causing it is one of your initialize hooks returned something.

**Comment by thegrb93** [comment]
I don't see why we're using an initialize hook here in the first place.

**Comment by Divran** [comment]
I believe it's to make certain that the egp table has been initialized first.

**Comment by thegrb93** [comment]
Yeah it works.

**Comment by Andrew-Eathan** [comment]
okay then

**Comment by thegrb93** [comment]
@Andrew-Eathan run this if you want to find what all has initialize hooks.

`lua_run for k, v in pairs(hook.GetTable().Initialize) do print(debug.getinfo(v,"S").short_src) end`

**Comment by Andrew-Eathan** [comment]
this is what it prints in console:

lua/autorun/textscreens_util.lua
lua/ulib/server/player.lua
lua/ulx/modules/uteam.lua
lua/ulx/end.lua
addons/wiremod_160250458/lua/entities/gmod_wire_egp_hud/huddraw.lua
addons/wiremod_160250458/lua/entities/gmod_wire_egp/lib/egplib/usefulfunctions.lua
addons/the_aperture_862644776/lua/aperture/main.lua
addons/the_aperture_862644776/lua/aperture/paint_lib.lua
lua/autorun/server/advdupe2_sv_init.lua
lua/mediaplayer/shared.lua
addons/wiremod_160250458/lua/entities/gmod_wire_target_finder.lua
lua/ulx/modules/xgui_server.lua
lua/includes/modules/hookextras.lua

**Comment by Divran** [comment]
This *might* break your game, but can be fixed with a simple map change. Try this
`lua_run for k,v in pairs(hook.GetTable().Initialize) do if v()~=nil then print("this hook returned a value when it shouldn't:",debug.getinfo(v,"S").short_src) end end)`

**Comment by Andrew-Eathan** [comment]
this hook returned a value when it shouldn't:	addons/the_aperture_862644776/lua/aperture/paint_lib.lua

okay i'll remove that addon and see if it causes any issues
