### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by TheLightBringer1991** [wiremod/wire#1832]
Waited to test this with the latest dupe2 version that let's you use the old constraint system. After the change with the latches spawning last, many of my dupe's constraints feel loose yet again. For example this tank's gun before the whole change was solid, not it is floppy. I removed the github version of wire and installed the workshop one to make sure it is not some weird bug or dupe2 causing this, and it works with the older version, everything goes solid again if you spawn it with the old constraint mode. So it really is the new version of wire causing this, for some reason.

[15t WSP 75.txt](https://github.com/wiremod/wire/files/2793670/15t.WSP.75.txt)

**Comment by TheLightBringer1991** [comment]
Welding it last doesn't add anymore stability to the rest of the constraints but kills only itself. I don't know how useful that is. Also, latches are activated and deactivated all the time, so they are always last by design in the constraint table, no?

**Comment by thegrb93** [comment]
Even with toggling the latch, it would get added to the same constraint-system as the props connected to it. Now it won't, but that issue mentioned would fix that.

**Comment by thegrb93** [comment]
Idk, if it's still not fixed after that then we can reopen this one.

**Comment by TheLightBringer1991** [comment]
Ok. But why would a change in how a latch behave bring floppyness to other constraints too?

**Comment by thegrb93** [comment]
Idk

**Comment by thegrb93** [comment]
It could have just as easily broken something else. Before, it would apply its weld before anything else.

**Comment by thegrb93** [comment]
I'll revert it just because it's going to get replaced again anyway
