### ISSUE TITLE
FPP Error, Settings not saving

### ISSUE THREAD

**Issue by LiamFarley** [wiremod/wire#1835]
So i'm having this error show up:

[ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:431: table index is nil
1. callback - gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:431
2. query - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:305
3. RetrieveBlockedModels - gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:429
4. onFinished - gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:953
5. commit - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:194
6. Init - gamemodes/darkrp/gamemode/modules/fpp/pp/server/settings.lua:950
7. fn - gamemodes/darkrp/gamemode/modules/fpp/sv_fpp.lua:41
8. Call - addons/ulib/lua/ulib/shared/hook.lua:109
9. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:126
10. onFinished - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:140
11. commit - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:194
12. callback - gamemodes/darkrp/gamemoTimer Failed! [Simple][@gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua (line 161)]

My FPP settings such as blocked models list are not being read from my sv.db. All the blocked models are shown in the table but on the gameserver it is empty.

Any Ideas?

**Comment by thegrb93** [comment]
Wrong place
