### ISSUE TITLE
Wiremod Inputs randomly defunct

### ISSUE THREAD

**Issue by MelonChickens** [wiremod/wire#1839]
This is a very strange issue which I've had for a bit.
The only way I can summarise it is that one moment, Wiremod inputs such as pod controllers were working fine, and the next, they weren't.
I've tried verifying my game cache, reinstalling Wiremod and even reinstalling Garry's Mod, but the issue persists. They just don't work.
Button inputs and such are fine, but anything requiring keyboard or possibly mouse inputs do not work.
On further investigation, E2 does appear to register inputs, but doesn't do anything about it, if that makes any sense. It'll recognise a key is pressed, but it just does nothing. No output, nothing.
Very strange.

**Comment by thegrb93** [comment]
Post a dupe of the contraption that has the issue pls

**Comment by MelonChickens** [comment]
[qTestRig_2.txt](https://github.com/wiremod/wire/files/2846611/qTestRig_2.txt)

I have confirmed that the dupe is fine, since when spawned in other people can use it just fine. It just doesn't work for me.
Would me using the x64 beta be an issue? Because all of a sudden this has happened to all of my computers running Garry's Mod. I'll try using x86 to see if that solves it, actually.

**Comment by MelonChickens** [comment]
Using the x86 build did not solve the issue. The issue is now happening on all of my computers that have Garry's Mod installed, so perhaps there's an addon conflict or something like that?

**Comment by thegrb93** [comment]
People have reported problems with the x64 beta so yes that is the problem.

**Comment by thegrb93** [comment]
Try a fresh re-install. Switching back to x86 probably set back some things.

**Comment by MelonChickens** [comment]
Completely unsubscribing from the x86-64 beta solved the issue.
