### ISSUE TITLE
Radios have high cpu usage

### ISSUE THREAD

**Issue by Etothepowerof26** [wiremod/wire#1840]
If you have a bunch of radios (one way) with the max amount of inputs, and wire it to a button (any value, tried with 899999995002880) and start spamming it, the server will start to slow down.

A person came onto the server that I was playing on, and we've experience some server crashes. Looking at logs we saw this:
`LUA
| 0 lua/entities/gmod_wire_radio.lua:122: ShowOutput
| 1 lua/wire/server/radiolib.lua:49: Radio_SendData
| 2 lua/entities/gmod_wire_radio.lua:81: ?
| 3 [C]:-1: xpcall
| 4 lua/wire/server/wirelib.lua:58: TriggerInput
| 5 lua/wire/server/wirelib.lua:530: Wire_TriggerOutput
END:maxdepth
STACK:29: <UserData>, '(Channel 0) Transmit 1:9.8596108894622e+30 2:9.8596108894622e+30 3:9.8596108894622e+30 4:9.8596108894622e+30 5:9.8596108894622e+30 6:9.8596108894622e+30 7:9.8596108894622e+30 8:9.8596108894622e+30 9:9.8596108894622e+30 10:9.8596108894622e+30 11:9.8596108894622e+30 12:9.8596108894622e+30 13:9.8596108894622e+30 14:9.8596108894622e+30 15:9.8596108894622e+30 16:9.8596108894622e+30 17:9.8596108894622e+30 18:9.8596108894622e+30 19:9.8596108894622e+30 20:9.8596108894622e+30 21:9.8596108894622e+30 22:9.8596108894622e+30 23:9.8596108894622e+30 24:9.8596108894622e+30 25:9.8596108894622e+30 26:9.8596108894622e+30 27:9.8596108894622e+30 28:9.8596108894622e+30 29:9.8596108894622e+30 30:9.8596108894622e+30 31:9.8596108894622e+30 32:9.8596108894622e+30
Receive 1:9.5708088510014e+30 2:9.5708088510014e+30 3:9.5708088510014e+30 4:9.5708088510014e+30 5:9.5708088510014e+30 6:9.5708088510014e+30 7:9.5708088510014e+30 8:9.5708088510014e+30 9:9.5708088510014e+30 10:9.5708088510014e+30 11:9.5708088510014e+30 12:9.5708088510014e+30 13:9.5708088510014e+30 14:9.5708088510014e+30 15:9.5708088510014e+30 16:9.5708088510014e+30', LN17, LN32, LN1, LN17, '(Channel 0) Transmit 1:9.8596108894622e+30 2:9.8596108894622e+30 3:9.8596108894622e+30 4:9.8596108894622e+30 5:9.8596108894622e+30 6:9.8596108894622e+30 7:9.8596108894622e+30 8:9.8596108894622e+30 9:9.8596108894622e+30 10:9.8596108894622e+30 11:9.8596108894622e+30 12:9.8596108894622e+30 13:9.8596108894622e+30 14:9.8596108894622e+30 15:9.8596108894622e+30 16:9.8596108894622e+30 17:9.8596108894622e+30 18:9.8596108894622e+30 19:9.8596108894622e+30 20:9.8596108894622e+30 21:9.8596108894622e+30 22:9.8596108894622e+30 23:9.8596108894622e+30 24:9.8596108894622e+30 25:9.8596108894622e+30 26:9.8596108894622e+30 27:9.8596108894622e+30 28:9.8596108894622e+30 29:9.8596108894622e+30 30:9.8596108894622e+30 31:9.8596108894622e+30 32:9.8596108894622e+30`
9.8596108894622e+30 mustve been the value they selected to use. Maybe clamp it to 2^31-1 or limit amount of radios people can spawn? This is also the contraption they used:
![contraption](https://steamuserimages-a.akamaihd.net/ugc/939467109943569933/B42435AB641C089B77642D84E327ED23C76580A1/)

**Comment by thegrb93** [comment]
I solved it on my server by just lower sbox_maxradios or whatever it is. Basically it's just TriggerInput spam.

**Comment by Divran** [comment]
Why would any amount of trigger input spam cause the server to lag, unless it's wired into an infinite loop? I checked the code and while the radio is one of the oldest untouched pieces of code in all of wire, it doesn't seem to be *that* bad

**Comment by thegrb93** [comment]
Inputs can be triggered about 10 times per frame and with 100 inputs connected sequentially (so it builds a big stack) it adds up I guess. That code needs refactoring though, for sure.

**Comment by thegrb93** [comment]
I never understood the point of radio. It's not like wires have a range limit. Maybe it could just act as a proxy between two entities instead of the overcomplicated mess it is.

**Comment by CaptainPRICE** [comment]
recon. needs refactoring.

**Comment by thegrb93** [comment]
Looks like the problem is they can have 32 inputs/ouputs running through an inefficient radio library ~7 times per radio per frame.

**Comment by thegrb93** [comment]
I really don't see any point in these entities, but the best solution is to limit them imo.

**Comment by thegrb93** [comment]
Here's a new library. Should be lightning fast. Just requires a few changes to the entity. (reminder: ent.Channel needs to be changed to a string)

```lua
local Channel = {
	__index = {
		register = function(self, ent)
			table.insert(self.subscribers, ent)
			ent.ChannelData = self
			ent:NotifyReceivedData()
		end,
		unregister = function(self, ent)
			table.removeByValue(self.subscribers, ent)
		end,
		isEmpty = function(self)
			return #subscribers == 0
		end,
		send = function(self, ent, subch, x)
			self.data[subch] = x
			for k, v in ipairs(self.subscribers) do
				v:NotifyReceivedData(subch)
			end
		end
	},
	__call = function(meta)
		return setmetatable({
			data = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
			subscribers = {}
		}, meta)
	end
}
setmetatable(Channel, Channel)

local Channels = setmetatable({},{__index = function(t,k) local r=Channel() t[k]=r return r end})
local Secure_Channels = setmetatable({},{__index = function(t,k) local r=setmetatable({},{__index = function(t,k) local r=Channel() t[k]=r return r end}) t[k]=r return r end})

function Radio_Register(ent)
	Channels[ent.Channel]:register(ent)
end

function Radio_RegisterSecure(ent)
	Secure_Channels[ent.Steamid][ent.Channel]:register(ent)
end

function Radio_Unregister(ent)
	local chan = Channels[ent.Channel]
	chan:unregister(ent)
	if chan:isEmpty() then
		Channels[ent.Channel] = nil
	end
end

function Radio_UnregisterSecure(ent)
	local chan = Secure_Channels[ent.Steamid][ent.Channel]
	chan:unregister(ent)
	if chan:isEmpty() then
		Secure_Channels[ent.Steamid][ent.Channel] = nil
		if next(Secure_Channels[ent.Steamid])==nil then
			Secure_Channels[ent.Steamid] = nil
		end
	end
end

function Radio_SendData(ent, subch, data)
	Channels[ent.Channel]:send(ent, subch, data)
end

function Radio_SendDataSecure(ent, subch, data)
	Secure_Channels[ent.Steamid][ent.Channel]:send(ent, subch, data)
end

function Radio_ChangeChannel(ent)
	Radio_Unregister(ent)
	Radio_Register(ent)
end

function Radio_ChangeChannelSecure(ent)
	Radio_UnregisterSecure(ent)
	Radio_RegisterSecure(ent)
end

local radio_twowaycounter = 0
function Radio_GetTwoWayID()
	radio_twowaycounter = radio_twowaycounter + 1
	return radio_twowaycounter
end
```

**Comment by thegrb93** [comment]
Just realized the ChangeChannel function won't work, but that can be fixed while integrating.
