### ISSUE TITLE
Radio inputs disconnected after loading save

### ISSUE THREAD

**Issue by rster2002** [wiremod/wire#1841]
When I create a simple circuit where I pass an input into a radio and then retrieve it from an other radio it works fine. Untill you save your world and then load it again. The input to radio wires are gone. Outputs from radio's to other entities don't show this behavior.

Envoirment: 
* Windows 10
* Gmod: Update: December 2018 Hotfix #2 (released: 15 dec 2018)
* Wiremod: Update released on: jan 18 2019

**Comment by rster2002** [comment]
Feel free to ask me any questions for further information.

**Comment by TAbdiukov** [comment]
if I may ask, when you "load" (I suppose, when you duplicate your radios), is the pair of radios constrasined (i.e. welded, for example) to one another?

**Comment by rster2002** [comment]
No, sorry, I should have been more precise. When you save and load a world. Not a duplication, that works fine.

**Comment by thegrb93** [comment]
I think OnRestore might be happening too soon.

**Comment by Divran** [comment]
Wire has never really supported saved games. You're likely going to have a lot more issues than this

**Comment by thegrb93** [comment]
It actually does. I was surprised when I saw it too.

**Comment by Divran** [comment]
I know there was an attempt at fixing it at some point.

**Comment by rster2002** [comment]
> You're likely going to have a lot more issues than this

Actually, this is the only issue I have with wiremod and saving/loading.

**Comment by thegrb93** [comment]
I think I'll just refactor radio and knock out issues with one pr.

**Comment by rster2002** [comment]
I did some extra testing and found out that the input for the channel doesn't get disconnected.

**Comment by rster2002** [comment]
Only the data input seem to be affected
