### ISSUE TITLE
Generic limit/quota system for prop/holo/...

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#1843]
Currently there are 5 vastly different system used for limits in E2 alone.
Not only that, but they also work slightly different, and some of them are not transparent to the user (ie print).

It would be helpful to use one generic system that is consistent across wiremod and add some quality of life features while at it (warnings).  
Exposing this via E2Lib would make sense so other addons can use it as well instead of trying to come up with their own or copy/paste one of the existing systems.

## Features:
* Concurrent maximum (ie max holo limit)
* Maximum quota "storage" (ie holo burst limit)
* Maximum "refill" over time (ie 4/second)
* Quota scope
	* global per owner
	* each E2 individually
	* global per server (maybe)
	* Maybe implement via "target" parameter, ie `quota.state[target]`, that would also allow quota per target entities or whatever else people might want
* Query current limit (ie for holoNumSpawns)
* Warning message if exceeded
* (Triggers like `runOnQuota("propSpawn",1)` )

## Covered extensions:
* find
* holo
* print
* prop
* remoteUpload
* camera/light from `wire-extras`

## API-Draft:
* `quota = registerQuota(name, concurrentMax, storageMax, refill, warningMessage, warningPeriod)`
	Register quota, leaving parameters nil will disable that feature. warningPeriod ensures the player only gets one warning every X seconds, nil=only once
* `quota:check(target, num)`
	Will check if num operations can be done, returns number of operations left or false (ie `if not quota:check(self) then return end`).
	target would be `self` for e2-specific, `self.player` for player-specific or some static value for global.
	num=-1 just gets number of operations left.
* `quota:use(target, num, warnPly)` self explainatory, returns true on success, otherwise warns warnPly and returns false. warnPly is used for warnings only, can be left out when warnings are disabled
* `quota:free(target, num)` used to free up stuff from the concurrent maximum (ie when removing a prop/holo)
	num=-1 would clean up the quota entry for that target, ie on player disconnect or e2 removal
* Internally there would be a helper function to refill the affected quota (stored as float) based on time passed since last refill or create the entry on first use, instead of timers and initializing potentially unused quotas
---

I don't have much time right now to implement it, so this is for feedback at the moment, unless someone else wants to adopt it.

**Comment by Divran** [comment]
the reason there is one for each extension that needs it is because each extension needs a very different set of features. it's not impossible to do this, just saying

**Comment by adosikas** [comment]
Yeah that is why I was looking for feedback, to see if I missed a requirement.  
And while it won't be able to be 100% the same, i hope it will be better overall.

Taking holo burst spawn for example: I assume the burst system was implemented because 15/sec is to low to spawn larger contraptions at once, and there was no "quota storage" like I'm proposing here, which is not only much easier to communicate but also more flexible.
