### ISSUE TITLE
signalSetOnRemove not working at all

### ISSUE THREAD

**Issue by andrewgorpenko** [wiremod/wire#1845]
## Description
The title says pretty much everything. When I remove the chip with Remover/Ctrl+Z, I am expecting it to send a signal X before/after the destruction, but this never happens. 

## Code
Chip 1:
```lua
@name Node

if (first() | dupefinished()) {
    signalSetGroup("base")
    signalSetOnRemove("delete", 0)
}
```

Chip 2:
```lua
@name Base

if (signalClk("base", "delete", 0)) {
    print("Node " + signalSenderId() + " was destructed.")
}
```

## Expected
`> Node X was destructed.`

## Result
`> `

_P.S. Other signal* commands are working fine(like signalSend, etc.)_

**Comment by CaptainPRICE** [comment]
It works all fine for me. Also, your code has missing pieces.
This is not a place to get help, [join Discord](https://wiremod.com/) for help with wire.
But, here you go. Spawn the following E2s.
**1st chip**:
```golo
if (first() | dupefinished())
{
    signalSetGroup("Group")
    runOnSignal("Destroyed", 0, 1)
}
elseif (signalClk(signalGetGroup(), "Destroyed", 0))
{
    print("Node was destroyed: #" + signalSenderId())
}
```

**2nd chip**:
```golo
if (first() | dupefinished())
{
    signalSetGroup("Group")
    signalSetOnRemove("Destroyed", 0)
}
```

Then, remove your 2nd chip, and you will see it will print (as expected):
> Node was destroyed: #ID

/request-to-close
