### ISSUE TITLE
[Workshop]Wire breaks other addons clientside on 64 bit gmod branch

### ISSUE THREAD

**Issue by storm37000** [wiremod/wire#1848]
Wire breaks other addons such as GAS and vcmod clientside on 64 bit gmod branch.
it produces an assertion failed error in client side console.

Also various wire things dont work like pod controllers.

this is with 64 bit branch on client, not server.

**Comment by TomyLobo** [comment]
That'd be a first!
Usually it's other addons that break wire, not the other way round :)

Can you explain what exactly you mean by "breaks"?
I assume the error is absent once you remove the other addons?

**Comment by storm37000** [comment]
the other addons start working clientside when wire is removed.

**Comment by bigdogmat** [comment]
Is this the same assertion people on discord were talking about breaking x64 branch?

https://github.com/wiremod/wire/blob/b9bbbbf81273e5ba5b6a188fa2409ecfb1ddf9bf/lua/wire/wireshared.lua#L1157

This one?

If so I don't think there's anything we can do about it. I'll take a look into it if I have the time.

**Comment by storm37000** [comment]
that could be whats breaking the other addons, it causes vcmod to say that it failed loading when you try to open the vcmod menu and the repairmen have to gui or tags above them.

**Comment by bigdogmat** [comment]
Are by chance on the workshop version? The workshop version has a different assert at that location that **does** fail on the x64 version. It has since been removed on the github version.

**Comment by storm37000** [comment]
im on workshop version yea.

**Comment by TomyLobo** [comment]
It's good that you already knew what he was talking about, because he didn't really answer my questions.

Anyway, we need to increase the number of bits from 8 to at least 11, in order to support up to 2048 button codes.
Or we play it safe and go for 16 bits and support up to 65536 button codes.

Although 11 bits for the button code + 5 bits for the binding index would make a neat 16 bits in total :)

@Divran @Nebual @AbigailBuccaneer opinions?

**Comment by TomyLobo** [comment]
Oh someone already set this to 12, but removed the assert.
That's bad.

**Comment by thegrb93** [comment]
@Anticept workshop needs update.

**Comment by Divran** [comment]
Why was the assert removed
