### ISSUE TITLE
Digital Screen - nil value error

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1857]
```
[ERROR] addons/wire/lua/entities/gmod_wire_digitalscreen/cl_init.lua:51: attempt to perform arithmetic on a nil value
  1. stringToNumber - addons/wire/lua/entities/gmod_wire_digitalscreen/cl_init.lua:51
   2. ProcessBuffer - addons/wire/lua/entities/gmod_wire_digitalscreen/cl_init.lua:81
    3. unknown - addons/wire/lua/entities/gmod_wire_digitalscreen/cl_init.lua:108
```

**Comment by thegrb93** [comment]
Need reproduction steps

**Comment by CaptainPRICE** [comment]
> Need reproduction steps

Ok. I give you exact E2 code in a zip. (Note: The code inside is completely automatically generated via external program, you're not supposed to change anything.)

Download [captainprice-001.zip](https://github.com/wiremod/wire/files/3027438/captainprice-001.zip)

1. Extract `captainprice-001` folder from the zip into `garrysmod/data/expression2` folder.
2. Make sure `wiring` E2 extension is enabled.
3. Spawn digital screen, and then spawn `expression2/captainprice-001/captainprice-001.txt` script onto the digital screen entity.
4. Wait for the upload to finish.
5. ???
6. Enjoy the script error spam.

**Comment by thegrb93** [comment]
Jeez, it lags my game so bad.

Adding this to cl_init.lua:65 fixes the error spam
```lua
if #datastr>0 then
	ent:AddBuffer(datastr,pixelbit)
end
```

but the root of the issue is the decompression fails. I'd have to look at it later.

**Comment by thegrb93** [comment]
The data metering is all wrong. That's the problem.

**Comment by CaptainPRICE** [comment]
> Jeez, it lags my game so bad.

Sort of expected with how wire works currently, everything is just called immediately, it would be much better if certain things used coroutines. Did I say everything? I am pretty sure wire doesn't utilize threads at all. Which results in such a bad performance when dealing with "bigger stuff".

> The data metering is all wrong

That's just another sub-issue, yes...

**Comment by thegrb93** [comment]
No, coroutines will not make shitty code better - it would just take even longer to load, and no, that was the issue. Check the fix in the PR, I'll test it later.

**Comment by Divran** [comment]
@CaptainPRICE gmod lua is single threaded. coroutines are not threads.

**Comment by CaptainPRICE** [comment]
@Divran 
> gmod lua is single threaded.

Well, true, and I knew that (it is Lua itself, GLua is nothing more special).

> coroutines are not threads.

However, that's a false statement. Lua coroutines are *threads* (not the same as [process thread](https://en.wikipedia.org/wiki/Thread_(computing)) tho). Read a [tutorial](http://lua-users.org/wiki/CoroutinesTutorial) to begin with.
Bad performance (and experience) is mostly caused by the Wire editor, not being multi-threaded, GMod freezing up while it is performing code validation on a large `buffer` (`wire_expression2_validate` function, parser/compiler being invoked in a sequence). This part of code could really use coroutines, which would make it responsive, and also allow to bring a better user experience, by showing validation progress to the user, while it is doing the *hard* work in the background.
That was my point. Hopefully you understand it now.
