### ISSUE TITLE
Upload buffer is overflowing reliable channel

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1858]
For example, when uploading a bigger E2 code to the server, an overflow of the reliable channel occurs, forcing client to disconnect from the server.

Spew from console (spam):
> IP: send reliable stream overflow

**Comment by Adorable-Catgirl** [comment]
Can we get this closed?

**Comment by thegrb93** [comment]
Seems like a common issue with wire's networking. Devs assumed that staying below the 65k limit won't have any issues, but that's not the case. I have a library that I use for starfall's file transferring that avoids this and I can port to wire. It would just be a bunch of work to integrate it. https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/netstream.lua if anyone is interested

**Comment by CaptainPRICE** [comment]
> Can we get this closed?

Once it is fixed, yes.

**Comment by Adorable-Catgirl** [comment]
Ah, didn't realize it was a legit issue or this was an April Fools joke. I guess I never had a 65k E2.
