### ISSUE TITLE
E2/EGP: Add Arc (to draw pie/ring/circle/arc)

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1862]
With a single Arc function it is possible to draw a couple of shapes (i.e. a pie, ring, circle, and arc), just by altering an input values.

Creation `wirelink:egpArc(arcID:number, thickness:number, startAngle:number, endAngle:number)`
Thickness getter `number=wirelink:egpArcThickness(arcID:number)`
Thickness setter `wirelink:egpArcThickness(arcID:number, thickness:number)`
Angle setter `wirelink:egpArcAng(arcID:number, startAngle:number, endAngle:number)`
Start Angle getter `number=wirelink:egpArcStartAng(arcID:number)`
Start Angle setter `wirelink:egpArcStartAng(arcID:number, startAngle:number)`
End Angle getter `number=wirelink:egpArcEndAng(arcID:number)`
End Angle setter `wirelink:egpArcEndAng(arcID:number, endAngle:number)`

Practically:
![egp-arc](https://user-images.githubusercontent.com/9789070/55689617-dd9c2b80-5986-11e9-8adb-7f78bc5c0b27.gif)

(Some things I see coming: charts, pacman, more fancy user interfaces...)

P.S. I am working on the "EGP Designer" (see [my comment on the forum](https://forum.facepunch.com/gmodgd/btace/Post-Your-Current-WIP-V6-1/13/#postcwvrkx)). 😃

**Comment by adosikas** [comment]
Are you aware of `egpWedge`? That takes care of of the non-arcs.

The arcs could be done with `egpPolyStrip` once #895 is fixed.
