### ISSUE TITLE
EGP: Object size networking uses signed instead of unsigned integer

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1868]
Mathematically, the "size" can not be negative, it is always represented with positive numbers (width & height).

Why on earth does EGP network the object size using signed integer?
Example snip (there may be other places too):
https://github.com/wiremod/wire/blob/44ed9f26ca813b80490126429865d46315164e0e/lua/entities/gmod_wire_egp/lib/egplib/usefulfunctions.lua#L180-L181

https://github.com/wiremod/wire/blob/44ed9f26ca813b80490126429865d46315164e0e/lua/entities/gmod_wire_egp/lib/egplib/usefulfunctions.lua#L194-L195

Should be changed to `net.WriteUInt` (unsigned integer).

**Comment by thegrb93** [comment]
Maybe some object types utilize negative w/h.

**Comment by Divran** [comment]
it also doesn't matter since a 16 bit signed int is aprox 32k. Unless you've got eight 4k monitors placed horizontally and you're using an egp hud.

**Comment by CaptainPRICE** [comment]
> it also doesn't matter since a 16 bit signed int is aprox 32k. Unless you've got eight 4k monitors placed horizontally and you're using an egp hud.

That is exactly my problem -_-
