### ISSUE TITLE
Editor: Implement code formatting engine

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1871]
I think it is about the time to do this feature.

An editor would provide formatting options to the user, so, the formatter would be able to format the code in editor according to the user's code formatting options with a single button (could add keyboard shortcut too).
There're many formatting options for E2, I will try to keep it minimalistic while providing enough of options for common coding styles.

There should also be a feature to temporarily turn off code formatting using 'special' comment, for example in E2:
```golo
#FORMATTING=OFF

#[FORMATTING=ON]#
```

When formatting engine is run over your code, it would understand that you have a comment which it would internally interpret as a switch, formatter will be turned off until you turn it back on using `#FORMATTING=ON`, so you can use custom code style while formatter is turned off.
Make the code look pretty and exactly as you want it to :)

I am not sure if it should take case-sensitivity into an account. But, multiline comment (`#[]#`) should be interpreted by formatting engine as well.

**Comment by thegrb93** [comment]
No. If someone wants to PR it then maybe, but this isn't enough to be an issue.
