### ISSUE TITLE
E2/EGP: Make egpLineStrip support 4D vectors

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1875]
Currently, [`wirelink:egpLineStrip(number, ...)`](https://github.com/wiremod/wire/blob/6c21328f2774ebc358e19ce41eb0686b9f0f5d3e/lua/entities/gmod_wire_expression2/core/egpfunctions.lua#L411) and [`wirelink:egpLineStrip(number, array)`](https://github.com/wiremod/wire/blob/6c21328f2774ebc358e19ce41eb0686b9f0f5d3e/lua/entities/gmod_wire_expression2/core/egpfunctions.lua#L437) functions only works for 2D vectors.
I proposing to expand them, in order to also support 4D vector usage.

For example (assuming `W` is a `wirelink` to the EGP screen, and `ID` being index of object):
```golo
# Old way
W:egpLineStrip(ID,   #######################
                     # Start  |       End  #
                     # X | Y  |      X | Y #
                 vec2(256,128),vec2(320,256),
                 vec2(192,256),vec2(256,128)
              )

# New way
W:egpLineStrip(ID,   ##################
                     # Start |   End  #
                     # X | Y |  X | Y #
                 vec4(256,128, 320,256),
                 vec4(192,256, 256,128)
              )
```

Why?
Well it is obvious. A simple reason: Performance.
It would decrease the amount of `vec2` function calls by **twice**.

**Comment by bigdogmat** [comment]
Performance would be _better_, however your ops are gonna be the same. Neither of the functions dynamically add to perf and `vec4` has twice the cost of `vec2`.

**Comment by CaptainPRICE** [comment]
@bigdogmat 
Yeah, as you said yourself, ops would remain the same. Performance improvement lies down in Lua code, it would have twice as less loop iterations when using 4D vectors.
4D vectors also make E2 code smaller.
And, finally because it groups Start and End points together (forming one line) - making E2 code more easier to read.

**Comment by CaptainPRICE** [comment]
Besides, I have one more thing to note:
`egpPoly` supports 2D and 4D vectors.
`egpLineStrip` only supports 2D vectors.

Seems like code inconsistency.

**Comment by thegrb93** [comment]
Don't think E2 var-arg overloads are possible without typechecking and then all proposed performance goes down the toilet.

**Comment by thegrb93** [comment]
Oh that's exactly what egpPoly does... https://github.com/wiremod/wire/blob/6c21328f2774ebc358e19ce41eb0686b9f0f5d3e/lua/entities/gmod_wire_expression2/core/egpfunctions.lua#L281

**Comment by thegrb93** [comment]
I don't think adding to the garbage pile is a good coding practice anyway though. Would be better to remove that.

**Comment by bigdogmat** [comment]
I think if it has good reason it's fine, like in `egpPoly` where it's used for the u,v coords.

**Comment by thegrb93** [comment]
Wait did you not read the code? egpLineStrip does it too. https://github.com/wiremod/wire/blob/6c21328f2774ebc358e19ce41eb0686b9f0f5d3e/lua/entities/gmod_wire_expression2/core/egpfunctions.lua#L411

**Comment by thegrb93** [comment]
They are uv's though

**Comment by CaptainPRICE** [comment]
> Wait did you not read the code? egpLineStrip does it too.

huh ok this is strange... 3rd and 4th used for UV tho. alright...
But, something is just wrong. Must be description.

Yes, that's it... Description is to be fixed for these 2 functions.

**Comment by CaptainPRICE** [comment]
@thegrb93 I guess you can fix these 2 descriptions?

https://github.com/wiremod/wire/blob/6c21328f2774ebc358e19ce41eb0686b9f0f5d3e/lua/wire/client/e2descriptions.lua#L1415-L1416
