### ISSUE TITLE
E2: Entity search/find is broken

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1877]
Running on the latest wire (as of the date of this post):
> Wiremod's version: 'Git c77e70c'

Having only wire addon installed, something is weird about entity search/find in E2.
For example:
1. Start a new singleplayer Sandbox game (there are no wire entities spawned).
2. Spawn the following E2 chip/code:
    ```golo
    if (!findCanQuery()) {
        reset()
        exit()
    }
    
    findByClass(entity():type()) # Find all E2 (gmod_wire_expression2) entities.
    
    local E2s = findToArray()
    print("#Array = " + E2s:count()) # Print out status (first is: "#Array = 0")
    print(findResult(1):isValid() ? "Ok." : "NOT OK!") # Prints "NOT OK!", even without calling isValid.
    ```
3. Notice `#Array` started to increment from 0. But, it should have printed `1`.
4. Spawn more of those E2s, and it will start to increment `#Array`, but always missing that 1.

Something is just quite wrong... I have also tried to iterate the found entities:
```golo
foreach (K, V:entity = E2s) { print(format("E2 (#%d) found: %s", V:id(), V:getName())) }
```
I have noticed that nothing is being printed with only 1 chip, so, as before after spawning in an another chip, then it started to run the print inside foreach-loop.

**Comment by CaptainPRICE** [comment]
Interestingly, doing a quick trial&error, I have went the whole history back, changed `find.lua` to its [initial version from 2009](https://github.com/wiremod/wire/blob/d8f0b9ca8d6fbee3950340897abfb4d73e18d635/lua/entities/gmod_wire_expression2/core/find.lua). Wiremod runs fine (no script errors). Except, there're still issues with it (length of `findToArray()` is always equal to actual amount minus 1).
That said, since it was brought to GitHub, it was already broken - since ever. Nobody's to blame.
I think it would be best to rewrite it.

**Comment by CaptainPRICE** [comment]
@Divran You seem to be the one who wrote `findCount` ("Bull's idea").
https://github.com/wiremod/wire/commit/a97cfca341022a9b70bb56adf1d424a833f3e9b8
So, you take the blame for that part.

**Comment by thegrb93** [comment]
Don't point fingers. Also I don't think that commit has anything to do with it.

**Comment by CaptainPRICE** [comment]
Yeah, that was my bad. It is not Divran's fault. Sorry, I am quickly skimming over git...
`findCount()` returns the count for how many available find calls you can do.
So, it returning `9` is fine (for above E2).
However, still the problem are these two E2 functions:
- `findToArray()` (and possibly `findToTable()` too)
- `findResult(n)`

**Comment by CaptainPRICE** [comment]
More E2 test-code:
```golo
print(findByClass(entity():type())) # Prints 0
F = findToArray()
print(F[1, entity] == entity()) # Prints 0
print(find() == noentity()) # Prints 0
print(find() == findResult(1)) # Prints 1
```

The first value out (0), suggests a problem comes from the returned value from the `applyFindList` function, which uses local `filterList` which resolves to [`E2Lib.filterList`](https://github.com/wiremod/wire/blob/c77e70ccd16e4fa7e405430a48044f779d6f9162/lua/entities/gmod_wire_expression2/core/e2lib.lua#L271-L288) function.
And that's where the 10+ year bunny lies.

Whoops. I meant bug. 😄'

**Comment by CaptainPRICE** [comment]
🐰
🐛 
😆

**Comment by Divran** [comment]
Not broken.
The cause is this line
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/find.lua#L68
which specifically filters out the E2 that ran the find query.
The E2 which ran the query is always ignored in all results. So technically it's a feature.

Not one I agree with. I would've included the E2 in the result, but still.

**Comment by Divran** [comment]
You can easily prove this to yourself by doing this
```
print("Number of E2s: "+findByClass("gmod_wire_expression2"))
print("Number of props: "+findByClass("prop_physics"))
```
then simply spawn 1 prop and it will say 
```	
Number of E2s: 0	
Number of props: 1
```
which means the 1st result is not ignored. The only entity that is ignored, is the E2 that runs the query.

**Comment by CaptainPRICE** [comment]
@Divran Yeah, now everything makes sense. Well, thanks for that.
I was just about to look at the filtering functions after trying out PR. Ok, no need for that PR.

**Comment by Divran** [comment]
Theoretically we could simply erase that one line and everything would work fine, but since it's been this way literally forever and no one has even noticed, we can safely say that the amount of times people need the e2 to be able to find itself is slim to none. So changing this would basically do nothing.

**Comment by CaptainPRICE** [comment]
What a bunny issue... What's with the "Bunny label. rofl xD

**Comment by CaptainPRICE** [comment]
@Divran However, I think that it should say that somewhere.
I suggest something like:
"By default, the E2 chip itself is ignored from found entities."
It would make the whole thing crystal clear for everyone. I think that's the least thing to do over all this. If there were such docs, this issue wouldn't exist.

Please do,
https://github.com/wiremod/wire/blob/c77e70ccd16e4fa7e405430a48044f779d6f9162/lua/wire/client/e2descriptions.lua#L976-L981
And wiki too.

**Comment by Divran** [comment]
Putting it on the wiki would be great, but the wiki can't be edited because it bans you from github every time you try. Someone needs to take the time to split up the E2 wiki into multiple pages first.

**Comment by thegrb93** [comment]
wat lol

**Comment by thegrb93** [comment]
It bans you? That's a problem

**Comment by CaptainPRICE** [comment]
"ban" how?!

**Comment by Divran** [comment]
yeah cos the E2 wiki is so huge, if you edit it, github thinks you're ddosing them or something idk. They might have fixed it now, but it used to do that.

**Comment by CaptainPRICE** [comment]
> yeah cos the E2 wiki is so huge, if you edit it, github thinks you're ddosing them or something idk. They might have fixed it now, but it used to do that.

Ah, must be their 'robust' anti-spam detection system...
I know what you're talking about now. What's the matter, I have experienced it:
https://github.com/CaptainPRICE/curly-octo-journey
