### ISSUE TITLE
Profile and improve editor performance

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1879]
I have initially started to talk about this in another issue, see my comment:
https://github.com/wiremod/wire/issues/1857#issuecomment-482310936

**Comment by thegrb93** [comment]
While I agree the editor could use some performance improvements, I don't think it's an issue worth leaving open. If anyone wants to refactor it or write their own, a pr is welcome.

**Comment by CaptainPRICE** [comment]
@thegrb93 I think we should have a label for such *issues* tho.
Also applies to #1871.

**Comment by thegrb93** [comment]
It technically is an enhancement, but it's so outlandish and difficult to implement that it is pointless to keep open.

**Comment by thegrb93** [comment]
It's like if someone opened an issue 'Add 2D physics engine to E2'. That's not going to happen.

**Comment by thegrb93** [comment]
That said, if the community disagrees with closing an issue, then we can reopen it.

**Comment by thegrb93** [comment]
I'll rename it to 'Profile and improve editor performance'

**Comment by CaptainPRICE** [comment]
Fair enough.
