### ISSUE TITLE
E2: Add basic Unicode (UTF-8) functionality

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1887]
Being unable to paste (and even work) with Unicode characters in E2 code/editor...
I'd like to introduce a couple of new E2 functions to fight this limitation.
Added 3 new E2 functions based on GLua's [utf8](https://wiki.garrysmod.com/page/Category:utf8) library.
This should be a *must-have minimum*, to make UTF-8 support, at least barebone working for E2 users.

**Comment by AbigailBuccaneer** [comment]
@CaptainPRICE it sounds like this is two separate issues - Unicode handling in the E2 editor itself, and allowing E2 scripts to correctly handle Unicode strings. This issue starts with describing the first issue, and #1888 is addressed at the second issue. Is that a reasonable summary of the situation here?

**Comment by CaptainPRICE** [comment]
Yeah, I started with such a speak, because its just to describe the situation. Despite it could be interpreted as 2 separate issues. This one is for enhancing E2 unicode functionality (not the editor), both labels and title are tagged to keep it clear.
At first I didn't know there were already 3 functions for this in E2 (follow up the PR), so it turned into enhancing/improving this particular functionality (API).
Anyways, it is easier to combat this issue using E2 functions than making Editor support unicode...

**Comment by AbigailBuccaneer** [comment]
> Anyways, it is easier to combat this issue using E2 functions than making Editor support unicode...

As I said, these are two entirely separate issues.
