### ISSUE TITLE
Fix e2doc

### ISSUE THREAD

**Issue by thegrb93** [wiremod/wire#1889]

**Comment by adosikas** [comment]
For reference, last year i took a stab at it, https://github.com/adosikas/wire/tree/e2doc-comments

I wasn't really happy with the result though, mainly because github wiki is fairly limited in layout options: https://github.com/adosikas/wire/wiki/Test:-E2Doc:-Entity

**Comment by Divran** [comment]
doesn't github support everything the old wiki supports? the current E2 wiki is just a copy paste of the old one I think
