### ISSUE TITLE
E2: number=keyClk(entity) function has been broken

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1890]
https://github.com/wiremod/wire/blob/bbb1f50cdeb2d93e926a225c9b0c7fbfa1aa71a2/lua/entities/gmod_wire_expression2/core/player.lua#L395-L401

Something is just broken with this particular function (`number=keyClk(entity)`), other `key*` functions are working fine.
It is supposed to return `1` on key down, and `-1` on key release. But, it is always returning `-1`, never a `1`.
Presentation, made because I thought I was going crazy as a member with ID `243249050449739787` claimed it works just fine (see Discord, `dev-wiremod` channel), proof of it not working:
https://streamable.com/eh4ly

Well, I know, it had worked fine previously, so something must have happened to it since the last time I used it. As of this moment, it is NOT working.

**Comment by adosikas** [comment]
That should be caused by the recent rewrite of the runOnX functions https://github.com/wiremod/wire/commit/f8ab5ad565a488a7b800b01bb4684e3c038e1d1b#diff-1cb37c52262c75dacbd77119d99e08d3

This is how `KeyWasReleased = state and 0 or 1` is set, so either 0 or 1, both of which will trigger the "true" portion of that the ternary `self.data.runOnKeys.KeyWasReleased and -1 or 1 `.

**Comment by Plootie** [comment]
Looks like thegrb93 beat me to it

**Comment by thegrb93** [comment]
Isn't it supposed to return 0 or 1?

**Comment by CaptainPRICE** [comment]
> Isn't it supposed to return 0 or 1?

Not.... Read what I said, it even states it in E2 description.
> It is supposed to return 1 on key down, and -1 on key release.

**Comment by Plootie** [comment]
https://github.com/wiremod/wire/blob/bbb1f50cdeb2d93e926a225c9b0c7fbfa1aa71a2/lua/entities/gmod_wire_expression2/core/player.lua#L393

**Comment by thegrb93** [comment]
@CaptainPRICE asking takes less time

**Comment by CaptainPRICE** [comment]
@thegrb93 `runOnKeys` is actually a wisdom on its own...
2 `keyClk` functions to retrieve 2 different values, it is also trying to solve 2 *problems* in a single way (recall of `runOnUse` discussion, and #1399).. so, it is to be treated specially.. *cough*
