### ISSUE TITLE
E2: Add entity:stripWeapons() function

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1894]
A function which is available via Pod Controller, but is missing in E2.
It allows to strip weapons from the driver of your vehicle.

By implementing this function, E2 would become a bit more independent (saving on time and entity count as well).
(It can come in useful when doing vehicle-controlled minigame using E2.)

**Comment by thegrb93** [comment]
You can already call remove() on your weapons.

**Comment by thegrb93** [comment]
Oh you want it to be able to strip others' weapons.

**Comment by thegrb93** [comment]
Use a pod controller, I don't think starfall should be able to do this.

**Comment by CaptainPRICE** [comment]
Perhaps a better name would be `podStripWeapons`.

**Comment by thegrb93** [comment]
That'd probably be good ya

**Comment by thegrb93** [comment]
Deleted all my comments. for some reason thought this was in the starfall repo
