### ISSUE TITLE
E2: Not able to open Expression 2 console

### ISSUE THREAD

**Issue by Lutevail** [wiremod/wire#1895]
So im playing normal wiremod but for some odd reason after installing addons of vehicles,playermodels and weapons the e2 stops working and reports this error:

[Wiremod] lua/entities/gmod_wire_expression2/cl_init.lua:48: attempt to index field 'PreProcessor' (a nil value)
  1. wire_expression2_validate - lua/entities/gmod_wire_expression2/cl_init.lua:48
   2. Validate - lua/wire/client/text_editor/wire_expression2_editor.lua:1595
    3. SetCode - lua/wire/client/text_editor/wire_expression2_editor.lua:1685
     4. NewScript - lua/wire/client/text_editor/wire_expression2_editor.lua:1512
      5. Setup - lua/wire/client/text_editor/wire_expression2_editor.lua:1951
       6. initE2Editor - lua/wire/stools/expression2.lua:822
        7. func - lua/wire/stools/expression2.lua:794
         8. FillViaFunction - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:100
          9. FillViaTable - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:89
           10. ActivateTool - lua/includes/modules/spawnmenu.lua:287
            11. DoClick - lua/wire/client/customspawnmenu.lua:577
             12. InternalDoClick - lua/vgui/dtree_node.lua:62
              13. DoClick - lua/vgui/dtree_node.lua:32
               14. unknown - lua/vgui/dlabel.lua:234

Thank you for your attention

**Comment by thegrb93** [comment]
This is unfixable without knowing which addon caused the break.

**Comment by Lutevail** [comment]
i can give the link from where i got the addons im refering

**Comment by Lutevail** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=679799074

**Comment by Plootie** [comment]
I would imagine the culprit would be [this](https://steamcommunity.com/sharedfiles/filedetails/?id=518664786) or [this](https://steamcommunity.com/sharedfiles/filedetails/?id=145061455) but I'm unable to test that right now

**Comment by Lutevail** [comment]
Hi again,found the addon causing the problema,a very sneaky addon…
https://steamcommunity.com/sharedfiles/filedetails/?id=518664786

**Comment by Plootie** [comment]
Can we get this closed? The offending addon is way in the wrong

**Comment by thegrb93** [comment]
Ya
