### ISSUE TITLE
Cam controller bugs

### ISSUE THREAD

**Issue by thegrb93** [wiremod/wire#1898]
>Looks like there's some bugs regarding cam controllers. Spawning one makes your view snap to whatever angle, and if youre using one and delete another it screws with the one you're using.

**Comment by Plootie** [comment]
Tested this on the latest master branch and encountered aim angle snap on remove instead of spawn, The snap seems to only be on the X axis. I wasn't able to reproduce the second issue

**Comment by CaptainPRICE** [comment]
Same here, the pitch angle snaps to `0` after removing Cam Controller entity.
And unable to reproduce the second part tho.

**Comment by Plootie** [comment]
The angle snap comes from https://github.com/wiremod/wire/blob/a06f4c5514273a07ec42e5f37882704e8493d677/lua/entities/gmod_wire_cameracontroller.lua#L210
introduced by #1709. I still cannot replicate the second issue after more trying

**Comment by CaptainPRICE** [comment]
I found it prevents Vehicle Exit Point from modifying pitch angle on exit as well.

**Comment by thegrb93** [comment]
I think @Divran or someone fixed cam controller stuff recently

**Comment by Divran** [comment]
yeah I think at least this specifc issue may have been fixed already
