### ISSUE TITLE
Discord link invalid. (Wiki)

### ISSUE THREAD

**Issue by TechnichalDoge** [wiremod/wire#1901]
The various Discord invite links throughout the git hub wiki and so on are invalid, and as such, people can not join from here.

**Comment by Plootie** [comment]
I would edit it myself but i dont know if github still temp bans first time editors for spam and i dont fancy finding out today. They should probably all be updated to https://discord.gg/H8UKY3Y which is the link on the wiremod landing page

**Comment by CaptainPRICE** [comment]
Yeah, just use the link from wiremod website.

**Comment by thegrb93** [comment]
I updated it. @Anticept maybe it could be added to the repository description as well next to the wiremod.com link.

**Comment by TechnichalDoge** [comment]
yeah i got flagged like 3 times for editing the wiki 3 times

**Comment by CaptainPRICE** [comment]
> yeah i got flagged like 3 times for editing the wiki 3 times

This is just unacceptable, somebody has to bug GitHub about it.

**Comment by Anticept** [comment]
All of this should be updated.

If need be, I can create a wiremod wiki editors group, for nothing but the purpose of hopefully keeping github from flagging wiki editors.
