### ISSUE TITLE
E2: \r is not treated as a carriage return (escape sequence)

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1905]
The title says it all, pretty much, but here's some code:
```golo
CarriageReturn_Faulty = "\r"
print(CarriageReturn_Faulty) # prints "r" (should have printed an empty line)
print(CarriageReturn_Faulty == toChar(13)) # prints 0 (should have printed 1 instead)
print(toByte(CarriageReturn_Faulty) == 13) # prints 0 (should have printed 1 instead)
```

`\r` doesn't seem to be a part of string escape sequence.
Note: If `\r` is going to be added, there is a possibility of breaking E2s.

**Comment by CaptainPRICE** [comment]
It is worth mentioning, that E2 string escaping is not strictly checked as it should (_have_) be(_en_).
For example, it just skips character ahead, not performing a check of whether it is a valid escape sequence:
```golo
print("\k\. fail")
print("#\\\ o
h\r")
```

Output:
> k. fail	
> #\ o
> hr

Once again to note: Adding `\r` and/or fixing string escaping may break E2s.

**Comment by TomyLobo** [comment]
@thegrb93 the original title was fine. you made it sound like a PR fixing the issue :)
I was actually surprised to see price actually fixing the trivial stuff he keeps reporting.

**Comment by TomyLobo** [comment]
@CaptainPRICE Can you open another issue for the checking thing please?
Let's keep this separate.

**Comment by thegrb93** [comment]
The phrasing makes it sound like the feature is broken when in-fact it just isn't there. That's why I changed it.
