### ISSUE TITLE
E2: hideChat for the pod/vehicle driver

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1906]
Allow E2 to `hideChat` of the driver who is in your vehicle/seat.
It would be pretty useful to have this functionality.
For example (usecase):
When doing minigames, where player must interact with the game using commands while being in your vehicle/seat. Wire Keyboard is practically unusable, because not every layout is supported, however using in-game chat (`runOnChat`) solves the problem, but now we need a way to hide that chat (so it doesn't annoy everyone else).

**Comment by CaptainPRICE** [comment]
I suggest a new function (signature): `void entity:podHideChat(number)`
Some quick example code would look like (a bit overcomplicated it, but you get the idea):
```golo
runOnChat(1)
if (!chatClk()) { exit() } # May not even need the if-statement. But, whatever.
# Just hide chat from all drivers/players from all of your vehicles.
local Player = lastSpoke()
local Vehicle = Player:inVehicle() ? Player:vehicle() : noentity()
if (!(Vehicle & Vehicle:isVehicle())) { exit() } # Blame Garry. Workaround for Player:GetVehicle() returning non-vehicle entity, make sure IT IS a Vehicle; otherwise, Lua may start go crazy and error. Take prop_vehicle_crane for example.
Vehicle:podHideChat(1) # It shouldn't work on a vehicle you don't own (prop-protection)
```

**Comment by thegrb93** [comment]
You want a way to hide other players' chat who sit in your vehicles? I don't like this.

**Comment by CaptainPRICE** [comment]
> You want to hide other players' chat who sit in your vehicles?

Yep that. Hence if it is a vehicle of my ownership, I would like a way to hide the chat from a driver inside.
There are 2 main problems which this would *solve* (more like workaround), by using `runOnChat` (as explained above):
- Wire Keyboard is not supporting every layout
- `runOnKeys` doesn't trigger for the `>` (`<`) key (the key next to `Left Shift` key, at least on my keyboard, yet another Garry's fault), and you would need to implement keyboard layouts manually in E2 *library*, *cough*, I did this for my country layout, but it is serious pain)

**Comment by thegrb93** [comment]
I'd say improving those other entities would be better than using chat.

**Comment by CaptainPRICE** [comment]
> I'd say improving those other entities would be better than using chat.

But, that is just insane task and would make code fairly grow...
Now, generally speaking, notice how `LAlt` is being the default 'leave key', also `AltGr` is not correctly recognized (`Ctrl`+`Alt` sequence). For example: I can't type `@` into Wire Keyboard because of this, it goes `AltGr`+`V`, literally a *blocking issue*. (Garry... Garry...)
Anyways, relying on chat (input) works for all, right out of box. It just becomes minor annoyance for others to read the chat, such function would solve all of those problems. And also it would help even more, as there won't be any need for Wire Keyboard per seat/player, less entities, better performance! :)

**Comment by thegrb93** [comment]
As long as the player sees '[Message hidden by vehicle]' when they say something.

**Comment by CaptainPRICE** [comment]
> As long as the player sees '[Message hidden by vehicle]' when they say something.

Hm. I don't really see a point in that. But, ok, sure. Hint (notification) message may be better (to keep chat clear as possible)?

**Comment by thegrb93** [comment]
Those are even more annoying

**Comment by Divran** [comment]
Alt Gr is broken? it worked back when I made the swedish keyboard layout <https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_keyboard/remap.lua#L279>
only thing is for some reason, Alt Gr triggers LCONTROL instead of RALT but whatever

**Comment by CaptainPRICE** [comment]
> Alt Gr is broken?

Garry.
