### ISSUE TITLE
Propcore needlessly unfreezing stuff and creating lag with setPos setAng

### ISSUE THREAD

**Issue by Areappa** [wiremod/wire#1907]
I think PhysObj:IsMoveable() is causing massive lag in propcore, this occurs when manipulating props that occupy the same spot ie, spawn 5 props in the same position and use setAng on them.
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/custom/prop.lua#L152. It uses more cpu if the prop has a more complex hitbox.. If you use a prop like models/mechanics/wheels/wheel_spike_48.mdl you'll see the issue.

@persist Props:array Go
if(first()){
    runOnTick(1)
    
    propSpawnUndo(0)
    function run() {
        if(!propCanCreate() | Props:count() == 5){timer("go",10),return}
        local Prop = propSpawn("models/mechanics/wheels/wheel_spike_24.mdl",1)
        Props:pushEntity(Prop)
        timer("run",500)
    }
    run()
    
}
if(clk("run")){
    run()
}
elseif(clk("go")){
    Go = 1
}

if(Go){
    foreach(K:number,Prop:entity=Props){
        Prop:setAng(randvec():toAngle()*360)
    }
}

**Comment by Areappa** [comment]
They don't even have to be in the same spot, if their hitboxes coincide with eachother then it will lag.

**Comment by thegrb93** [comment]
You're saying that IsMovable is the culprit, but it seems more likely that the EnableMotion right below it is the culprit.

**Comment by Areappa** [comment]
I thought the IsMoveable may have been checking around for other objects. Would EnableMotion use more depending on other objects near it?

**Comment by Areappa** [comment]
After some more testing it appears that it may be an issue with the WireLib.setPos and WireLib.setAng.

**Comment by thegrb93** [comment]
Yeah, that makes sense. Nothing really that can be done to stop it except for blocking laggy models.

**Comment by Areappa** [comment]
So this should probably be reported to Garry? Seems it's an issue with SetAngles and SetPos?

**Comment by Areappa** [comment]
After some more testing this only happens with E2, I spawned some props and used Lua to SetAng, it didn't cause any lag under the same conditions.

**Comment by Areappa** [comment]
Found out what the problem was, Calling EnableMotion(true) then false after setting the position will cause the lag.

**Comment by Areappa** [comment]
So why is this in here? If it's not movable then enable motion then disable motion in the same tick?
`if !phys:IsMoveable() then
			phys:EnableMotion( true )
			phys:EnableMotion( false )
end`

**Comment by thegrb93** [comment]
It's not needed for the setAng or setPos so I think that can be fixed.

**Comment by Areappa** [comment]
I'll do all this testing before I report a bug next time, sorry about that. I was a bit hasty.

**Comment by thegrb93** [comment]
Np, I'm not even sure what the unfreeze/refreeze is for. Removing it should hopefully fix the lag. You can try it yourself too and see.

**Comment by thegrb93** [comment]
Maybe it's to wake the constraints on the prop.

**Comment by thegrb93** [comment]
I imagine the phys:Wake() before it would suffice, but not sure.

**Comment by CaptainPRICE** [comment]
Ok, here's my log, I can't seem to produce a so-called "Massive CPU spike" here, I spent 20 minutes running around with this E2:
```golo
interval(251) # adjust this per 1000/sbox_E2_maxPropsPerSecond+1 (which is 4 by default, so 1000/4+1=251)
propSpawnUndo(0)
E = propSpawn("models/mechanics/wheels/wheel_spike_24.mdl", 0)
if (!E) { exit() }
E:setPos(owner():aimPos() + vec(random(-100, 100), random(-100, 100), random(100, 200)))
E:setAng(ang(random(-90, 90), random(-180, 180), 0))
E:propFreeze(1)
E:propFreeze(0)
E:propFreeze(1)
```

I have ended up spawning tons of those ([3k+](https://user-images.githubusercontent.com/9789070/56926790-d32b0880-6ad2-11e9-853e-ada35d8d1b55.png)), and I only noticed usermessages started to grow and a slight ~20 FPS decrease (but that's reasonable due to amount of entities), however nothing about "Massive CPU spike" (I even run monitoring programs to track it, basically a flat line the whole time), GPU usage does seem to have a couple spikes at times.
Perhaps 3rd-party addon is causing your problems, make sure to isolate issue before reporting (check it by only having wire addon installed, always advised to use git version in such case).
I will investigate more with some profiling in that function, later a bit.

Note, keep in mind: E2's propcore has antispam, and also `entity:setAng(angle)` and `entity:setPos(vector)` operations are postponed (queued) until next tick I believe (and there's more to prevent mingery/abuse).

-----

> I imagine the phys:Wake() before it would suffice, but not sure.

Yeah, that may be the cause, but I am not sure either, do some profiling.

**Comment by Areappa** [comment]
Why is captainPrice even still around, just copy the code I put in the top.

**Comment by Plootie** [comment]
Looking at the commit history for propcore that code has been there since its creation in UWSVN and has stayed since. I couldn't find any side affects from removing it from a short test but that needs further testing

**Comment by Divran** [comment]
>When you spawn a prop such as ragdoll

If this is the only thing it fixes, then why not just move that code to the `propSpawn` function instead, where it should've been to begin with

**Comment by CaptainPRICE** [comment]
> If this is the only thing it fixes, then why not just move that code to the `propSpawn` function instead, where it should've been to begin with

Well, if you move it to `propSpawn` only, then it wouldn't fix the edgecase still.
So, leave it as is, or, remove it.
I prefer to remove it since it causes more trouble rather than being helpful (*attempting to fix vphysics*).
