### ISSUE TITLE
E2: entity:parentTo() function is just upsidedown

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1909]
I had noticed this issue a while ago, and it is still there... So here it goes.

It is alias of deparenting function:
https://github.com/wiremod/wire/blob/e24296b6cfd738acb06b9112700012869d0c4f54/lua/entities/gmod_wire_expression2/core/custom/prop.lua#L480

But, is documented with the description of 'parenting' function:
https://github.com/wiremod/wire/blob/e24296b6cfd738acb06b9112700012869d0c4f54/lua/entities/gmod_wire_expression2/core/custom/cl_prop.lua#L29

**Comment by CaptainPRICE** [comment]
The best solution I can think of, is to basically remove this function.
So, even if any E2 is using it, they will notice the function would be gone, and search E2 helper again, and hopefully find that it was just completely wrong, and switch to `entity:deparent()`.

**Comment by thegrb93** [comment]
It's just the documentation that needs update. It should be,
```
E2Helper.Descriptions["parentTo(e:)"] = E2Helper.Descriptions["deparent(e:)"]
```

**Comment by CaptainPRICE** [comment]
> It's just the documentation that needs update. It should be,

Why is it called `parentTo` then?

**Comment by thegrb93** [comment]
Because parentTo with empty arguments implies setting parent to nothing.
