### ISSUE TITLE
E2: Add missing propcore getter functions

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1910]
There are several functions in E2 propcore, which only has setter, but no getter.
It would make sense to add the missing getter functions.
Here just to name some without getter (all are `entity` methods, taking a number as an argument):
`propDrag`
`propDraw`
`propFreeze`
`propGravity`
`propMakePersistent`
`propNotSolid`
`propSetBuoyancy`
`propShadow`
`propStatic`

**Comment by Divran** [comment]
It's possible some of these already have getters outside of propcore, in the normal entity extension. I haven't checked though.

And for the ones that don't, adding them to the normal entity extension would probably make more sense.

**Comment by Plootie** [comment]
quite a few of these seem to not have getters due to gmod, Looking through the wiki i cant find a getter for drag, buoyancy and shadow so you would probably have to modify the existing functions to store the set value somewhere for a getter to retrieve.

`propFreeze` has `n = e:isFrozen()`
`v = propGravity()` exists to return the gravity all props are affected by which might confuse things if `n = e:propGravity()`
The rest could be added

**Comment by CaptainPRICE** [comment]
> quite a few of these seem to not have getters due to gmod, Looking through the wiki i cant find a getter for drag, buoyancy and shadow so you would probably have to modify the existing functions to store the set value somewhere for a getter to retrieve (which also wouldn't catch edits made by anything other than E2).

Air friction/drag has direct getter function (`PhysObj.IsDragEnabled`).
Buoyancy is actually missing, but could be worked around.
Shadow can be retrieved using bittest function (`Entity.IsEffectActive(EF_NOSHADOW)`).

> `v = propGravity()` exists to return the gravity all props are affected by which might confuse things if `n = e:propGravity()` is added

There's nothing to be confused with, if you read descriptions, which is something people should always do beforehand. (Yes, it can be a bit cumbersome when looking at the signatures at first, but that's because E2 doesn't have `boolean` datatype, instead it uses `1` and `0` as a number to represent `true` and `false` respectively.)
`vector=propGravity()` ; get the direction and strength of gravity.
`entity:propGravity(number)` ; set per-entity zero gravity (boolean).
`number=entity:propGravity()` ; get per-entity zero gravity (boolean). < is missing.
`number=gravity()` ; get the value of `sv_gravity` ConVar; world gravity.

Oh, yeah, the 1st function above isn't even documented.

**Comment by Plootie** [comment]
My bad on the drag, not sure how i missed that tbh. I didn't know about the `Entity.IsEffectActive(EF_NOSHADOW)` :P. I agree that people should look at the descriptions but not many people do (unfortunately) and i dont like to add confusion, when unnecessary. If nobody else has done it when get time i'll make a pr adding these but unless you can point me to a way to get buoyancy that'll be skipped out
