### ISSUE TITLE
E2: Make noCollide work for players

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1912]
This is crucial for making cool doors/gate work per-player, and more.

Since this can't be done using a `constraint.NoCollide`, then `ShouldCollide` + `Entity.SetCustomCollisionCheck` (with proper validation/cleanup) should do the job.
The functionality could be integrated into `noCollide(entity, entity)` E2 function (which is a part of disabled-by-default `constraintcore` extension), to avoid creation of new E2 function of the *same* purpose. But, it doesn't have to be integrated into the existing function, I could make it a new function.

@Divran @bigdogmat @thegrb93 Whatever you choose, goes in PR.

**Comment by thegrb93** [comment]
Custom collisions and shouldcollide are 100% no-go. No matter what, the quicksand effect occurs and not even gmod devs can fix it.
