### ISSUE TITLE
E2: Unused rawinputs table in preprocessor

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1913]
https://github.com/wiremod/wire/blob/ec2326ea289d6c9966d18c1485f2105714f16815/lua/entities/gmod_wire_expression2/base/preprocessor.lua#L266

I couldn't find any references to it, for what does it exist for?

**Comment by CaptainPRICE** [comment]
#965 ???

**Comment by Plootie** [comment]
rawinputs seems to have been added in 5050dfe and that table was added as a fix in 02b6d3a. i cant be bothered to go through the git blame on phone rn but it seems its since been removed and that slipped past

**Comment by bigdogmat** [comment]
https://github.com/wiremod/wire/commit/080195aa30da5ca2e944a96dd691b982dd136ccc reverted it, the table was kept cause it was added as a fix between adding and removing.
