### ISSUE TITLE
Add function to get a players weapons

### ISSUE THREAD

**Issue by Plootie** [wiremod/wire#1919]
Currently the only way get a players weapons is with find functions, It seems sensible to add something like `e:weapons()` or `e:getWeapons()`. As far as i'm aware there's no risk of abuse from this so it seems weird for it to be missing

**Comment by CaptainPRICE** [comment]
Easy to add. Attention is required.
`Player.GetWeapons` returns uncontinuous/nonsequential table, so the # operator, ipairs, and a numeric-for loop shouldn't be used with it.

This is how it should be implemented for E2:
```lua
e2function array entity:weapons()
    -- todo: check 'this' is a player...
    local ret = {}
    for _, w in pairs(this:GetWeapons()) do ret[#ret + 1] = w end
    return ret
end
```
