### ISSUE TITLE
applyforce lags the server when used on a certain contraption

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/wire#1921]
if i use applyforce on a certain contraption it causes the E2 chip's cpu usage to rise to this:
![image](https://user-images.githubusercontent.com/42521608/57228155-cf8c0a00-701b-11e9-88c9-ccedb068f72e.png)

but when it doesn't apply force it idles around this:
![image](https://user-images.githubusercontent.com/42521608/57228220-f21e2300-701b-11e9-999f-e9006124e333.png)

the actual contraption:
![image](https://user-images.githubusercontent.com/42521608/57228260-06fab680-701c-11e9-86c7-1ff70b134259.png)

it's a tardis i made that's in flight. it only uses 57 props, and it hovers via using propGravity to turn the gravity for all props off. but if i try to apply force to one of the props, the server lags. i tried welding a regular cube with regular gravity to one of the props and applying the force on that, but it still lags.
i applied force to a fridge prop that wasn't connected to the tardis and it didn't lag at all, so what is causing this issue?

also, the applyforce doesn't move the tardis at all.
the time interval at which the force is being applied is 150 ticks (it was originally 50, but i made the interval bigger due to the lag which caused around 32000 cpu time)

**Comment by Plootie** [comment]
Is the server running the latest wire version and if so did this happen on previous versions? #1908 should have made this situation better

**Comment by Andrew-Eathan** [comment]
wireversion says it's running the workshop version

**Comment by Divran** [comment]
You're probably using falco's prop protection mod, it's known to cause huge issues with apply force. You'll need to disable the setting that interferes with it. Unfortunately I don't remember what it was called. 

@plootie that update has nothing to do with apply force

**Comment by Plootie** [comment]
>@Plootie that update has nothing to do with apply force

yeah derp :P. The setting is "Anti E2 mingery", They set the collision group for every constrained ent on every call

**Comment by Andrew-Eathan** [comment]
apparently even if i play on a server without FPP it still lags

**Comment by thegrb93** [comment]
There's a number of addons it could be.

**Comment by thegrb93** [comment]
Otherwise, I'll need a way to reproduce the issue.
