### ISSUE TITLE
E2: Add file deletion & renaming

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1924]
So, an E2 can read, write, and list files.
But, what about deleting a file? What about renaming a file?
In case of deleting a file, what if you want to delete an empty folder?
Well, there are no builtin E2 functions to complete these basic file tasks.

**Comment by thegrb93** [comment]
This is for safety

**Comment by bigdogmat** [comment]
There isn't really any safety we gain, if people can't delete files they'll just write empty data to them.

**Comment by TomyLobo** [comment]
Except for deleting folders. this is not currently possible and probably shouldn't be.

**Comment by bigdogmat** [comment]
Someone could just write empty data to all the files within a folder? The only difference between what's possible now and what would be possible is it'd just delete the existence of the files/folders instead of emptying them.

I agree with that last bit though, there's not really a reason to do this.

**Comment by thegrb93** [comment]
bigdogmat is right, I didn't think of that. I'm guessing the author didn't either.

**Comment by CaptainPRICE** [comment]
Why was this closed and then reopened.

> This is for safety

> bigdogmat is right, I didn't think of that. I'm guessing the author didn't either. Should be fine to be added then.

W.h.a.t.
I don't know what were you thinking.
`data/e2files/` and `>` (shared) are the only paths where E2 file API will operate; You can't read/write/list files from outside (i.e. `data/`), and thus you shouldn't be able to delete nor rename an outside file.

> Except for deleting folders. this is not currently possible and probably shouldn't be.
At least I don't see a compelling reason to allow it.

Imagine your operating system doesn't allow you to delete a folder. It'd quickly turn into a ever growing painful box of empty folders. omg.
A folder is basically just a special type of file, that you can 'enter' into. So, if you remove all children files recursively, then you should be able to remove the folder itself too. That's actually how it works, and thus it is possible.

**Comment by thegrb93** [comment]
The original author probably didn't want a user to be tricked into using an E2 that deleted all their e2files.

Stop the snide attitude. Seriously, it's annoying.

**Comment by TomyLobo** [comment]
E2 isn't an operating system.
I suppose you're writing one in it, but that doesn't mean we have to treat it like one.

Find a better argument.
