### ISSUE TITLE
E2: Move findToTable to find library

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1925]
https://github.com/wiremod/wire/blob/8ae53270ee708b6b9f504c19936dfd91a06943e0/lua/entities/gmod_wire_expression2/core/table.lua#L840-L849

Why does [`table=findToTable()`](https://github.com/wiremod/wire/blob/8ae53270ee708b6b9f504c19936dfd91a06943e0/lua/entities/gmod_wire_expression2/core/table.lua#L840-L849) E2 function exist outside of the [`Find`](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/find.lua) extension/core?!

**Comment by TomyLobo** [comment]
That is a very good question!
Also, why do we even have that in addition to findToArray?

**Comment by TomyLobo** [comment]
oh i see, this was introduced as part of the mtables extension, then that extension replaced the old tables without moving the findTo[M]Table function over to the find extension
