### ISSUE TITLE
E2: Weak tables

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1929]
[Reference page](http://lua-users.org/wiki/WeakTablesTutorial).

I suggest to implement...
E2 function signature:
`number=table:getWeakMode()`
`void=table:setWeakMode(number)`
E2 constants (to be used as a number argument for the `setWeakMode` E2 function):
`WEAK_TABLE_K`, `WEAK_TABLE_V`, `WEAK_TABLE_KV` (tip: could store strings into those, if E2 constants support string data-type)

Example E2 code would look like:
```golo
@persist Weak:table

if (first()) {
    Weak:setWeakMode(_WEAK_TABLE_K) # Weak-key table.
    print(Weak:getWeakMode() == _WEAK_TABLE_K)
}
```

Implementing this feature into E2 should not be hard really.
Here goes my quick write-down (in browser, lol, I have no idea if I got it right):
```lua
local getmetatable, setmetatable = getmetatable, setmetatable

-- I assume E2 constants doesn't support string data-type. So, using two lookup tables:
E2Lib.registerConstant("WEAK_TABLE_K", 1)
E2Lib.registerConstant("WEAK_TABLE_V", 2)
E2Lib.registerConstant("WEAK_TABLE_KV", 3)
local WeakTableMode = { [1] = "k", [2] = "v", [3] = "kv" }
local InvWeakTableMode = { ["k"] = 1, ["v"] = 2, ["kv"] = 3 }

--- Gets the mode of the given table.
e2function number table:getWeakMode()
    local mt = getmetatable(this)
    return mt and InvWeakTableMode[mt.__mode] or 0 -- Using zero to indicate that mode is not set
end

--- Sets the mode of the given table.
e2function void table:setWeakMode(mode)
    mode = WeakTableMode[mode]
    if not mode then return end
    local mt = getmetatable(this) or {} -- Tip: Could drop 'or {}' if E2 table value has metatable builtin
    if mt.__mode then return end -- Used to prevent mode changing, it is builtin to Lua, but just to be safe
    mt.__mode = mode
    setmetatable(this, mt)
end
```

Please.

**Comment by Plootie** [comment]
but why. i dont see any real reason to add this

**Comment by bigdogmat** [comment]
Doing this would cause a lot of issues for our current table implementation. There's no way we could delete the type information we store alongside a value, unless we changed the current table implementation. It'd at least be possible to implement this for our current array implementation, but that'd be a bit inconsistent.

Aside from the issues above what reason would there be to add this?

**Comment by CaptainPRICE** [comment]
> but why. i dont see any real reason to add this

> Aside from the issues above what reason would there be to add this?

For the same reason it exists in Lua...
The only difference in E2 is that, you can't force-call GC. But, Lua can, thus weak-tables stored in E2s would be *GCed*. Aside from Lua force-call, GC is actually automatic, so it could happen at runtime while E2s are running, and then weak-tables would be *GCed* as well...

**Comment by CaptainPRICE** [comment]
> Doing this would cause a lot of issues for our current table implementation. There's no way we could delete the type information we store alongside a value, unless we changed the current table implementation. It'd at least be possible to implement this for our current array implementation, but that'd be a bit inconsistent.

In E2 there's also `gtable`.
This makes me think, well if this would be that hard to implement into E2 `table` data-type.
How about a new data-type `wtable` along with special constructor `wtable(mode, ...)`?

**Comment by thegrb93** [comment]
Fyi, there's no guarantee lua's garbage collector will clean the weak table just by invoking it like you seem to imply.

**Comment by thegrb93** [comment]
If there's a use case for this then maybe, but looks like bloat to me.

**Comment by CaptainPRICE** [comment]
> Fyi, there's no guarantee lua's garbage collector will clean the weak table just by invoking it like you seem to imply.

I didn't said "it will definitely clean the weak-tables" tho, I just said it could happen. And according to the Lua example code (on the reference page), it does, read it.

> If there's a use case for this then maybe, but looks like bloat to me.

Sure there are..
There's no bloat, think completely minimal, is simply sufficient.

**Comment by CaptainPRICE** [comment]
-----

Let me describe a new version..

A new E2 data-type `wtable` (`xwt`) would be introduced, `table` data-type basically, but **redesigned**:
```golo
@persist Weak:wtable

# Create a weak-value table (new functionality). And it'd no longer be limited to only number/string keys, a key could be of any data-type.
Weak = wtable(_WEAK_TABLE_V, (entity()) = "foo")

function table fooAsTable() {
    return Weak["foo"] # True indexer unlocked! Explicit-type-specification is optional.
    # table implementation is limited due being overly bloated, and redundantly redundant.
    # wtable would use static analysis techniques to beat it.
    # Type of expression would be determined at compile-time.
    # In this case, since expression is used as a return value (expecting a table),
    # it will look for a table value at index "foo" in the Weak-wtable,
    # in case of non-existence of "foo" key it would create an expression
    # of default return value, an empty table. Taa-daa.
}

function angle fooAsAngle() {
    local Index = Weak[entity(), string] # Just an example of using (optional) explicit-type-specification still, this read operation would indeed return "foo".
    local A = Weak[Index] # This is indexing by string, because Index is a string value. And it would be looking for an angle value, because A is used as a return value of this function (expecting an angle return value).
    return A # Just to demonstrate the case of non-existent value.
}

if (1) { # Truthful condition for sure. The point is, we want a new (local) scope, emulating GC.
    # Create a table with strong references (existing functionality); table implementation is limited to only number and string keys tho.
    local Bar = table(("Hello") = "World", (1) = "The first")
    Weak["foo"] = Bar # Bar is a local table value, assigning a local table Bar by string index "foo".
    printTable(fooAsTable())
    # Prints the following:
    #   Entity [10][gmod_wire_expression2] = foo
    #   foo:
    #       1       = The first
    #       Hello   = World
}

#[ Moment later... (Let's pretend GC has executed at this point.) ]#
# Bar is no longer visible, and has been disposed of. GC took care of cleaning up weak-tables.

# Thus, now it would not print out Bar table at index "foo".
printTable(Weak)
# Prints the following:
#   Entity [10][gmod_wire_expression2] = foo

print(fooAsAngle() == ang()) # Prints 1. A default value of angle data-type is returned from fooAsAngle call, because the underlying index is not a part of the Weak-wtable.
print(format("%q", Weak[entity()])) # Prints "foo". In this case, for vararg case, since explicit-type-specification is omitted, it would read whatever the value is stored at [entity()] index (and leave formatting to the format function).
```

Ough. Long.

**Comment by thegrb93** [comment]
I'm talking about an actual thing you would use it for gameplaywise

**Comment by TomyLobo** [comment]
Weak tables/hashmaps/etc are usually used for caches in a memory-constrained situation.
Please describe how you would encounter such a situation in gmod.

**Comment by AbigailBuccaneer** [comment]
I don't think it's a good idea to implement ideas in E2 just because the underlying implementation (a Lua interpreter) makes them easy. E2 is its own language, which could have multiple implementations (an implementation in S&box, a standalone interpreter, it could even be compiled to native machine code!). Sure, this is mostly a hypothetical point as nobody's rushing to create an alternative implementation right now, but more theoretically, E2 is its own language with its own personality and abstractions and we shouldn't be bound by Lua. E2 doesn't even have a concept of garbage collection.

I like that you're thinking about type inference though, it's something I'd like E2 to be able to do. But it's not something that's tied to tables at all. As you say, this would require extensive new static analysis, and I do think that it's worth doing but it's not a selling point of this proposal for weakly keyed/valued tables.
