### ISSUE TITLE
E2/Editor: Highlight of "return" keyword is borken

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1931]
*The picture is worth a thousand words*
![image](https://user-images.githubusercontent.com/9789070/58297575-7ae8dd00-7dd8-11e9-8353-7326f9783917.png)
This is not a *blocking* issue tho; the E2 also runs fine when spawned.
It's just a small syntax highlighter (E2 Editor) bug.
Temporary workaround is to insert a whitespace between `return` and `(`, like so:
![image](https://user-images.githubusercontent.com/9789070/58297712-ffd3f680-7dd8-11e9-84f3-f5e82818c937.png)

*bork-bork*.

**Comment by AbigailBuccaneer** [comment]
Good spot. Likely caused by [this](https://github.com/wiremod/wire/blob/master/lua/wire/client/text_editor/modes/e2.lua#L29).
