### ISSUE TITLE
Forcers can push moving world doors

### ISSUE THREAD

**Issue by scriptis** [wiremod/wire#1934]
Any Forcer with a set `Velocity` can push world doors, allowing players to break parts of the map.

Steps to reproduce:
- Spawn a Forcer.
-  Enable `Force` and set a high `Velocity`, say, `10000`.
- Point the Forcer at a door.
- Open the door.

The velocity applied to the door will never decay and will act whenever the door is in movement. Even after removing the forcer, the velocity will continue to act. Nobody wants the map torn apart like this--maps are people too!

**Comment by thegrb93** [comment]
I'd say a restriction should be put in place

**Comment by TomyLobo** [comment]
https://github.com/wiremod/wire/commit/228b6f99dc12170e5d22fbff9e2cc02655dfb4c7?w=1
Funny, in the last 10 years, no one complained about this :)

**Comment by TomyLobo** [comment]
Currently, the setvelocity parts are on the same prop protection hook as the applyforce parts (GravGunPunt).
Maybe we need to add a hook that is checked in addition to GravGunPunt, specifically for the setvelocity parts?
Then, prop protection could be configured to allow or disallow this

**Comment by storm37000** [comment]
simple fix would be to have an option to have forcers check CPPI.

**Comment by Aws0mee** [comment]
> simple fix would be to have an option to have forcers check CPPI.

It already calls GravGunPunt which every prop protection should return something for. As far as I'm concerned if you can use a forcer on an entity, it's intended. A possible "solution" could be to change the hook call to either PhysgunPickup or GravGunPickupAllowed as those will likely be more restrictive by the prop protection. Additionally, you could save all entities to a table on server startup and prevent those entities from being forced as they must be map entities. I can write up a fix for this, but I'm not sure what the best solution would be. @thegrb93 what do you think?

**Comment by thegrb93** [comment]
I think forcers should only affect things with the player or vphysics movetype. Map entities like doors have a different movetype that forcers shouldn't affect.

**Comment by thegrb93** [comment]
MOVETYPE_WALK and MOVETYPE_VPHYSICS I think are what it should push and MOVETYPE_PUSH are things like doors and map entities that it shouldn't push.

**Comment by Aws0mee** [comment]
> MOVETYPE_WALK/MOVETYPE_STEP and MOVETYPE_VPHYSICS I think are what it should push and MOVETYPE_PUSH are things like doors and map entities that it shouldn't push.
@thegrb93

Just tested, it appears map props including doors do indeed have MOVETYPE_PUSH. Do you want me to make a PR preventing forcers on entities with MOVETYPE_PUSH completely?

**Comment by thegrb93** [comment]
Sure
