### ISSUE TITLE
Error with WireMod

### ISSUE THREAD

**Issue by Potatosayno** [wiremod/wire#1935]
Hello, I don't quite remember how I managed to do this, but I got the following error:
`[ERROR] addons/wire-master/lua/wire/tool_loader.lua:66: attempt to index local 'ent' (a boolean value)`
Sadly, this is most of the information I can provide.

**Comment by bigdogmat** [comment]
Either the model was invalid or the player hit their spawn limit or the entity failed to create. To know which one we'd need a stack trace of the error.

**Comment by Potatosayno** [comment]
Even if I hit the entity limit, shouldn't it already be in wiremod to detect that?

**Comment by bigdogmat** [comment]
Entity limit as in the server entity limit. Generally addons don't handle that condition cause meeting it can cause a lot of issues and is indicative of another issue. As I said though I can't say it was that without seeing the full stack trace.

**Comment by thegrb93** [comment]
Paste the full error next time.
