### ISSUE TITLE
E2: Low time-quota (1ms) breaks 'destruct' callback (cleanup is never executed)

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1938]
Running on the most recent version of Wiremod (475f06faec6aa7a9949ceb1f1c1767c659969c35).

**Details**
A user could possibly abuse this bug, because it prevents `destruct` callback from being executed, so things aren't cleaned-up as they should be.

**Steps to reproduce**
1. Start a new singleplayer game.
2. Open Console, and enter the following command: `wire_expression2_quotatime 1`
3. Spawn the following E2 chip/code:
    ```golo
    @persist A:string
    if (first()) {
        propSpawnUndo(0)
        propSpawn(entity():model(), 1)
        holoCreate(1)
        runOnTick(1)
    }
    while (perf(90)) {
        A = A + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    }
    ```
4. Script error will occur: `time quota exceeded`.
5. Finally, remove/undo the spawned E2, to observe that `destruct` is not being called.

Note: Such *ghost-owned* holo can still be deleted afterwards using `holoDeleteAll(1)`. While a prop can NOT be removed via `propDeleteAll()` (as this is the only overload and can only clean up props spawned by their *owner* E2). You'd need to use a Remover tool, or obtain an entity index to remove it via E2: `entity(ID):propDelete()`.

**Credit**
This bug was originally found by `Charles#1111` (UID: `175226117215617024`, on Discord).

**Comment by Divran** [comment]
@thegrb93 I believe you added the time quota functionality
this can be fixed simply by calling the destruct hook below this line
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/init.lua#L193
I'd do it but I need to leave for today. I can throw that in there tomorrow if you haven't already by then
