### ISSUE TITLE
#ifdef not working for user-functions

### ISSUE THREAD

**Issue by Manonox** [wiremod/wire#1946]
```
function f(){}
#ifdef f()
    print(1)
#else
    print(0)
#endif
```
This bit of code returns 0 and i don't understand why is it like this.
Any alternatives or maybe a fix?
I need this for my #include madness:

```
-- Heroes.txt --
@persist [Heroes]:table
function addHero(Table:table){
Heroes:pushTable(Table)
}
#include %heroname%.txt


-- %heroname%.txt --
#include BaseHero.txt
init("Shit")


-- BaseHero.txt --
function init(string){
#ifdef addHero(table(...))
addHero(table(...)) #here i want to automatically add the hero[table] to Heroes in Heroes.txt
#endif
}
```

I want to do this so i can easily make new hero txts and just include them once and forget about it.

**Comment by bigdogmat** [comment]
You should know what you're including and if it exists if it's user defined. If not store it in a table and string call it, or prototype it with an empty udf that never actually gets ran.

The preprocessor will probably never have access to the knowledge of udfs.

**Comment by TomyLobo** [comment]
correct. the preprocessor cannot access compile-time state and you haven't made a compelling case for such a fundamental breach of good compiler design

**Comment by bigdogmat** [comment]
Aside from my other suggestions we could expand the `#ifdef` system to allow custom defs, e.g. `#define custommodule`
