### ISSUE TITLE
E2 @persists over dupes?

### ISSUE THREAD

**Issue by gmodplayer423** [wiremod/wire#1947]
Why is this even a thing?

`@persist Global

if (dupefinished()) {
    print(Global) # Global is still 10, even after duping it and placing again
}

if (first()) { # Doesnt run when dupefinished
    Global = 10
}`

**Comment by thegrb93** [comment]
Yeah E2 includes its persists with the duplication, that's intended. dunno why first() doesn't work after duping, but most ppl work around it with `if (first() | dupefinished())`
