### ISSUE TITLE
Error with E2

### ISSUE THREAD

**Issue by MrBallistic101** [wiremod/wire#1952]
[ERROR] lua/entities/gmod_wire_expression2/cl_init.lua:48: attempt to index field 'PreProcessor' (a nil value)
  1. wire_expression2_validate - lua/entities/gmod_wire_expression2/cl_init.lua:48
   2. Validate - lua/wire/client/text_editor/wire_expression2_editor.lua:1595
    3. SetCode - lua/wire/client/text_editor/wire_expression2_editor.lua:1685
     4. NewScript - lua/wire/client/text_editor/wire_expression2_editor.lua:1512
      5. Setup - lua/wire/client/text_editor/wire_expression2_editor.lua:1951
       6. initE2Editor - lua/wire/stools/expression2.lua:822
        7. func - lua/wire/stools/expression2.lua:794
         8. FillViaFunction - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:100
          9. FillViaTable - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:89
           10. ActivateTool - lua/includes/modules/spawnmenu.lua:287
            11. DoClick - lua/wire/client/customspawnmenu.lua:577
             12. InternalDoClick - lua/vgui/dtree_node.lua:62
              13. DoClick - lua/vgui/dtree_node.lua:32
               14. unknown - lua/vgui/dlabel.lua:234

[ERROR] lua/entities/gmod_wire_expression2/cl_init.lua:48: attempt to index field 'PreProcessor' (a nil value)
  1. wire_expression2_validate - lua/entities/gmod_wire_expression2/cl_init.lua:48
   2. Expression2Upload - lua/wire/stools/expression2.lua:526
    3. func - lua/wire/stools/expression2.lua:576
     4. unknown - lua/includes/extensions/net.lua:32

**Comment by thegrb93** [comment]
When did the error happen

**Comment by bigdogmat** [comment]
It looks like another error occurred earlier on in the server start up. If not try reinstalling

**Comment by pudsmoker** [comment]
i get the same nil value error trying to use switch cases or breaks. was this fixed in the patch yesterday/today?

**Comment by bigdogmat** [comment]
No, this is an issue with your install or something other related to your server

**Comment by MrBallistic101** [comment]
> What caused the error?

spawning the e2's or trying to open the editor

**Comment by thegrb93** [comment]
Your server has a conflicting addon
