### ISSUE TITLE
Text screen reliable channel overflow

### ISSUE THREAD

**Issue by Lutevail** [wiremod/wire#1957]
So,i found out that the e2,with the use of http functions could make the players disconnect and this was the code:
######################################################
@name Streaming Chat
@inputs 
@outputs String:string
@persist Y
@trigger
runOnTick(1)
Y++
httpRequest("https://www.twitch.tv/ninja%22")
String = httpData():sub(Y)
##########################################################
I was trying to stream into gmod Twitch chats…(Didnt test in singleplayer but tested in different servers and it made users leave)
To Replicate the problem:
-Spawn the E2 (obviously)
-A text Screen
-Connect Both
-Make sure u use a url from a live twitch

When it happens every player or at least almost everyone gets an error like "Client 6 overflowed…" something like that

**Comment by thegrb93** [comment]
Looks like a bug with text screen
