### ISSUE TITLE
Advanced inputs are seemingly global for anyone regardless of owner

### ISSUE THREAD

**Issue by TheWizardLizard** [wiremod/wire#1960]
Situation: Tank has hydro sus that is adjustable UP with num 7 and 8, DOWN with 4 and 5, i asked random people to hit those keys and it did infact adjust the values on the advanced input, even though I was the owner.

**Comment by Divran** [comment]
Looks like it's been broken since 2013 <https://github.com/wiremod/wire/commit/0c82cf6d2353b5b6a9b620af5df86c98aafef292#diff-a99f2aad57e7810ef9f4017737eba500>

@Nebual pls

**Comment by Nebual** [comment]
Whoops. In my defence _it worked_ haha.
