### ISSUE TITLE
Wiremod won't work

### ISSUE THREAD

**Issue by dieselraptorCS** [wiremod/wire#1964]
Wiremod won't show up in the spawnmenu (or anywhere else). I've uninstalled and re-installed wiremod multiple times and I've deleted the cache folder. Whenever i start a game it creates a LOT of script errors. Please help!!

**Comment by thegrb93** [comment]
You have an incompatible addon.

**Comment by dieselraptorCS** [comment]
> You have an incompatible or broken addon installed.

how do i fix this?

**Comment by thegrb93** [comment]
Remove addons until it stops breaking
