### ISSUE TITLE
EGP HUD Issue.

### ISSUE THREAD

**Issue by Flappy229** [wiremod/wire#1965]
I have a HUD a long time ago (for aircraft) and recently a update to wiremod messed up a hud object that was working in the previous update. The error exactly is if you have a a resized EGP poly it will mess it up quite noticeably.

HUD Pre-issue:
https://steamuserimages-a.akamaihd.net/ugc/834765698267321494/3D0CF307BE80C10522151F758BDC027AC17826AC/

After issue:
https://steamuserimages-a.akamaihd.net/ugc/791991374972316143/98FFBF39BC60A9AFCB45A16B9F41FE25646CCC94/

Code (Works fine with second line commented out):
        EGP:egpPolyOutline(7,Res+vec2(8,8),Res+vec2(0,0),Res+vec2(-8,8),Res+vec2(0,0))
        EGP:egpSize(7,2)

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/pull/1869 may be the cause.

**Comment by adosikas** [comment]
Not sure why you aren't using a lineStrip for that chevron (which would only draw 2 lines instead of 4 for the polyOutline), but I tracked down and fixed the issue, see #1968.
