### ISSUE TITLE
Wire Thruster Server Crash

### ISSUE THREAD

**Issue by ghost** [wiremod/wire#1970]
After using an extremely high number (9e99) as an input for wire thrusters, the server crashed instantly.

Thruster settings:

Model: models/dav0r/thruster.mdl

Physical Properties: Super Ice
Gravity: Off
Weight: 1,000

Underwater Effects: None
Abovewater Effects: None
Sound: None

Force Multiplier: 10,000
Input Threshold: -9,999,999
Force Maximum: 9,999,998

Bi-directional: Yes
Works out of water: Yes
Works underwater: Yes

**Comment by thegrb93** [comment]
Forgot to test this, but something tells me this will only induce a crash if the crazy physics checks are disabled.

**Comment by thegrb93** [comment]
It's a crazy physics crash, pretty sure devs addressed this at some point
