### ISSUE TITLE
Pod controller constantly disconnects itself when pasted with duplicator

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/wire#1976]
The pod controller keeps disconnecting from its seat every time i paste the dupe with the Duplicator.

**Comment by TaylorRatliff** [comment]
Hi Andrew,
I started looking at this today, but I have been unable to replicate the issue. Would you be able to share the dupe with me?

**Comment by thegrb93** [comment]
Addon conflict probably, but yes a dupe file would help.

**Comment by Andrew-Eathan** [comment]
I'll provide an example dupe file tomorrow
