### ISSUE TITLE
Adv. Dpulicator wont laod 

### ISSUE THREAD

**Issue by olivery3107** [wiremod/wire#1982]
Hello
I'm normally playing on a danish DarpRP server and i wanted to make something i singleplayer from that server.

The tool-thing just lokds like this:
https://i.imgur.com/XPzYxHr.jpg

[sdasd.txt](https://github.com/wiremod/wire/files/3694875/sdasd.txt)
trying to open that one ^^

And console says:
https://i.imgur.com/GEzIbEB.png

Can someone please help

**Comment by thegrb93** [comment]
I'll give it a look. Thanks for providing the error and file.

**Comment by thegrb93** [comment]
The file is corrupted. Something caused it to save incorrectly.

**Comment by thegrb93** [comment]
If you can try making the contraption again with the latest version and the error happens again then I'd like to investigate what's causing the saving issue.

**Comment by olivery3107** [comment]
The file is not corrupt.
The file works 100% fine in-game, its because the server im playing on has some kind of "dupe-protection" for some dupes.

**Comment by thegrb93** [comment]
I see, so their 'protection' shifted some tables around and made the file unusable anywhere except their server.
