### ISSUE TITLE
Expression 2 rangerFilter() is annoying to use

### ISSUE THREAD

**Issue by Fasteroid** [wiremod/wire#1984]
Right now, all we can do is blacklist certain entities from being hit.
Would it be possible to add the ability to whitelist entities to be hit by a trace?  Right now my workaround is to continually trace and ignore entities until I hit the one I want, but that's quite expensive in terms of processing.

An easy way to do this while keeping backwards-compatibility?  Make a new e2 function for setting the filter mode:

`rangerFilterWhitelist(1)   ## enables whitelist mode`
`rangerFilterWhitelist(0)   ## disables whitelist mode`

Hope this isn't too much to ask!  Thanks :) 

![20191018032215_1](https://user-images.githubusercontent.com/29342750/67074338-e69c5f80-f156-11e9-8345-444fa7577a32.jpg)

**Comment by thegrb93** [comment]
Can use trace filter function. Those typically use a lot of cpu though.

**Comment by bigdogmat** [comment]
> Can use trace filter function. Those typically use a lot of cpu though.

Assuming it's linear we could just count calls, not a great solution however.

**Comment by Fasteroid** [comment]
> Is it possible to do this with lua? I'm not entirely sure it is.
> 
> Regardless, you can do this to easily make a whitelist with the current functions
> 
> ```
> findExcludeEntities(ArrayOfWhitelist)
> findInSphere(Pos,Radius)
> rangerFilter(findToArray())
> ```

I was hoping to whitelist what the trace _can_ hit, rather than what it can't hit.  I know the current system lets you ignore entities, but I don't think it lets you specify "don't ignore" entities.

My issue in the above image is that when I try to get the thickness of the prop (by pinching it between two rangers),  I have to re-fire a trace and filter every time I hit something I wasn't looking for.  I feel like this might use more CPU?

**Comment by Fasteroid** [comment]
https://www.youtube.com/watch?v=EzWNBmjyv7Y
Added it myself, gonna make a pull request :D
