### ISSUE TITLE
Holograms can't be created in the first second with extreme hologram limit values (GetInt bug)

### ISSUE THREAD

**Issue by shadow7483147** [wiremod/wire#1988]
Because an E2's code on a local server or singleplayer game is already immediately available when the E2 is created, the code immediately starts running as soon as the expression exists in the world. However, the function holoCreate waits until the minimum amount of time has passed (after Uploading has disappared from the toolgun screen) before doing anything.

This can lead to cases where if you have an E2 that uses an iterator on an interval/tick to create holos, any holograms created in the first second are never created.

To reproduce: After starting either a singleplayer game or a local server, use this expression 2 code: (edited)
```golo
if(clk()){ #second execution
    holoCreate(2)
    print(holoEntity(2),holoEntity(2):pos())
}else{ #first execution
    interval(1000)
    holoCreate(1)
    print(holoEntity(1),holoEntity(1):pos())
    entity():setPos(entity():toWorld(vec(0,0,30))) # set pos upward after the first hologram tries to create. Visibly leaves the hologram behind on multiplayer.
}
```
It should print the first holo's pos [0,0,0] immediately as the toolgun fires (a null entity), and then the second holo's pos after 1 second. (correctly created)
Lowering the interval below one second, puts the second hologram below the minimum time threshold for code uploading, and then you'll have both holograms print pos [0,0,0].

Trying this on a multiplayer server works correctly, as the first hologram is created when the e2 is finished uploading and runs, as does the second hologram after 1 second.

**Comment by bigdogmat** [comment]
> Because an E2's code on a local server or singleplayer game is already immediately available when the E2 is created, the code immediately starts running as soon as the expression exists in the world.

How exactly is this different from what happens on a server?

I can't reproduce you behavior in single player, local server, or on a dedi. In the past I remember the holo position not updating immediately, however I can't reproduce that now and can't think of a reason it would occur.

**Comment by shadow7483147** [comment]
It's different because when an E2 is created by the toolgun, the server will wait until your client finishes uploading the code to the server before running. In singleplayer the E2 runs immediately after being created with the toolgun.

Updated code: print(holoEntity(1)) instead of using the interger to prove that the holo entity simply doesn't exist.

https://youtu.be/IdeNAnW5nkc

Alternatively, try the code I used in finding the bug in the first place: (using the navmesh extension and a high hologram burst amount & delay)
```golo
@persist N:array I
if(first()){
    runOnTick(1)
    N=navmeshes()
    printTable(N)
}else{
    I++
    holoCreate(I,N[I,navmesh]:navCenter(),vec(5))
}
```
It'll skip creating holograms for the first second's worth of ticks, then create size 5 holograms at the center of the nav areas normally.

**Comment by bigdogmat** [comment]
Both of these work just fine for me on both single player, local server, and dedi

![hl2_2019-10-21_21-14-23](https://user-images.githubusercontent.com/7156309/67253847-e0a0ca00-f447-11e9-88f9-c7740d7c5a8c.png)
![hl2_2019-10-21_21-09-09](https://user-images.githubusercontent.com/7156309/67253853-e72f4180-f447-11e9-8dde-93e928067263.png)



> It's different because when an E2 is created by the toolgun, the server will wait until your client finishes uploading the code to the server before running. In singleplayer the E2 runs immediately after being created with the toolgun.

This still doesn't make sense cause it still doesn't start running until after the code is received and compiled. The conditions are all the same.

**Comment by shadow7483147** [comment]
Bigdog does your E2 turn red when you put it down, before coloring itself normal? Mine doesn't. Only on multiplayer

**Comment by bigdogmat** [comment]
No it doesn't, it's the same as yours. And as I explained it doesn't matter when the code runs, it doesn't affect the holograms in any way. Could you try reinstalling and turning off/disabling workshop/legacy addons.

**Comment by shadow7483147** [comment]
In progress:
Disable all workshop addons except for Wiremod
Delete /lua from garrysmod folder, verify game integrity.
Launch with -noaddons, leave off -noworkshop as I'm intending to use the workshop version of Wiremod.

**Comment by shadow7483147** [comment]
Yep, it's still happening

**Comment by shadow7483147** [comment]
Ok so holoCanCreate returns 0 until the e2 finishes uploading, gonna look at that

**Comment by shadow7483147** [comment]
Found it
I had wire_holograms_burst_amount set to an absurd value (999999999999)
Bringing it down to 1000 fixes it

**Comment by thegrb93** [comment]
So it was just a bad convar?
