### ISSUE TITLE
Holograms inherit the expression's angles when created

### ISSUE THREAD

**Issue by shadow7483147** [wiremod/wire#1989]
In case of setting a hologram at an arbitrary position using `holoCreate(Index,Position)`,
if you place the expression 2 on a sloped surface such as a ramp, it will create the hologram with the same angles as the parent E2 instead of being created with an empty angle (0,0,0).

Not sure if this is intentional or not, so I'm marking it as an issue. It seemed like an oversight from being able to create a hologram at the expression's position, or maybe if holograms were supposed to be bound locally from the E2 when the extension was first made.

**Comment by shadow7483147** [comment]
https://steamuserimages-a.akamaihd.net/ugc/762723985820352681/9AEE2166032D3A02E43C10F64BF742608EE1E327/

**Comment by marchkarcz** [comment]
I'm pretty sure it was intended, plus you can use holoAng(Index,ang(0,0,0)) to get around that iirc

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua#L518
