### ISSUE TITLE
GPULib Screen Switcher has broken ownership when duped. (FPP)

### ISSUE THREAD

**Issue by ShadowzOfTheDark** [wiremod/wire#1992]
Whenever pasting a dupe that has a GPULib controller, the ownership of everything constrained becomes owned by the world. (FPP)

**Comment by thegrb93** [comment]
The GPULib switcher is filled with lua errors when duping in general.

**Comment by thegrb93** [comment]
[ERROR] addons/wire/lua/entities/gmod_wire_gpulib_controller.lua:24: attempt to index field 'screen' (a boolean value)
  1. unknown - addons/wire/lua/entities/gmod_wire_gpulib_controller.lua:24

**Comment by TomyLobo** [comment]
"screen" doesn't strike me as the boolean kind of variable. how'd that get in there?

**Comment by TomyLobo** [comment]
#710 related issue?

**Comment by thegrb93** [comment]
Yeah

**Comment by TomyLobo** [comment]
I don't get it. This should be working unless someone is actively sabotaging us.
E2's Make routine works the same way and that thing works, right?
Maybe "screen" is used by some other addon as we suspected in #710.
Changing it to something less generic could help, but I'd like to see a list of addons @ShadowzOfTheDark has installed, first.

**Comment by thegrb93** [comment]
Obviously the dupe setup function is buggy

**Comment by thegrb93** [comment]
Glancing at the code, it actually doesn't make much sense to me either.

**Comment by thegrb93** [comment]
I'll try debug.trace and __newindex to find the culprit

**Comment by ShadowzOfTheDark** [comment]
Okay, so I disabled all addons other than FPP, AdvDupe1, and AdvDupe2. The issue only seems to occur with AdvDupe2 in my testing, however the server I play on any duplicator will result in the ownership transferring to the world.

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sv_clipboard.lua#L885

**Comment by thegrb93** [comment]
Entities are not allowed in setup arguments, https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sv_clipboard.lua#L75

**Comment by thegrb93** [comment]
duplicator does the same thing as advdupe2.

**Comment by thegrb93** [comment]
It needs its linking mechanism switched to however other wire entities do their linking.

**Comment by TomyLobo** [comment]
Now that is a dumb workaround...
The obvious workaround to that workaround would be an "or nil" on our side :)

**Comment by TomyLobo** [comment]
I guess that wouldn't help either, though.
We'd need to add a validity check for the screen entity instead.

I checked and advdupe1 does it the same way, btw:
https://github.com/wiremod/advduplicator/blob/master/lua/autorun/server/advdupe.lua#L2567

**Comment by TomyLobo** [comment]
Btw, a better workaround would have been to put a marker object into those gaps and then remove it before passing it to unpack:
```lua
> x = { 1, "marker", 3 } x[2] = nil print(unpack(x))
1       nil     3
```

**Comment by thegrb93** [comment]
The point of it is to make whatever is putting an entity into the classargs error rather than having the duplicator error.

**Comment by thegrb93** [comment]
Also, that wouldn't always work.

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/pull/258 will add a warning for invalid types in the classargs.

**Comment by thegrb93** [comment]
This is how linked entities are supposed to be done https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_keyboard/init.lua#L432

**Comment by TomyLobo** [comment]
@bigdogmat and the lua reference manual convinced me that this kind of nil hole punching is indeed not reliable.
This should be done instead:
https://ideone.com/vVPIVz

**Comment by TomyLobo** [comment]
I agree. We don't control all the duplicators so we'd need to do both anyway.

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/pull/259
