### ISSUE TITLE
E2 remoteSetCode() function unwires all entity and wirelink inputs

### ISSUE THREAD

**Issue by marchkarcz** [wiremod/wire#1997]
I have E2 1, and E2 2. 1 would upload code to 2. But every time I do this, both 1 and 2 lose their connections to each other. 1 will show that it isn't connected to an entity anymore, 2 won't, but both would lose their wires completely.

Example video: https://www.youtube.com/watch?v=NOU2J-zFlIs&feature=youtu.be

**Comment by marchkarcz** [comment]
Sidenote: heres the code I'm doing specifically, for the E2 loader, that is. Ignore my shit coding lol

E2 2:
`@name E2_LOADER
@inputs [BIOS Disk_Controller Keyboard]:entity Code:string REUPLOAD
@outputs [Rendertable]:table 
@outputs Upload Sector:string Import:table
@persist FileBeggining:string Divline:string 
@trigger REUPLOAD

if(first() || duped() || dupefinished()){
    function upload(Cd:string){
        local CurrentCode = getCode()
        local ExplodedValue = CurrentCode:explode(Divline)
        #print(ExplodedValue:count())
        local CodeToUploadToOurselves = ExplodedValue[1,string] + Divline + "\n" + Cd
        entity():remoteSetCode(CodeToUploadToOurselves)
    }
}
if(changed(REUPLOAD) && REUPLOAD && !first() && Code != ""){
    upload(Code)
}
if(first() || dupefinished()){
    Divline = "#DI"+"V"
}

#DIV
`

And E2 1's primary function is just
`function upload(CUp:string){
        Code = CUp 
        REUPLOAD = 1 
        timer("changeupload",250)
    }`

**Comment by Vurv78** [comment]
Going to work on this, I'll see if its possible to add a second function with an optional number that keeps inputs/outputs for the changed chip

**Comment by Vurv78** [comment]
After a year of downtime, I looked into it again and like I said, it loses all of its inputs and outputs, so if you create an output from that chip in another, it will be overwritten. So it basically becomes a new entity in terms of wiring, therefore this isn't a bug

The only way to 'fix' this would be to keep the current outputs (and inputs?). Either way, It'd be hacky and I'm not sure if it'd be worth it. Maybe remoteSetCode could return the new entity which you could use in the chip??

It'd be nice if wiring an input entity didn't actually depend on the entity targeted storing the info... but that also isn't really what wiring is for.

Here's code that basically makes keeping inputs and outputs irrelevant by making its own output of itself.
```golo
@name Chip Code Setter
@inputs TargetChip:entity

if(first()){
    TargetChip:remoteSetCode("
@name Cool E2 Chip
@outputs Self:entity
Self = entity()
print(Self)
")
    print("Set code!")
}
```
Code Getter
```golo
@name Cool E2 Chip
@outputs Self:entity
Self=entity()
```

**Comment by marchkarcz** [comment]
Should I close this issue, then? I think I've found a better way to do what I was intending without using remoteUpload(), and it's been almost a year since I posted this
