### ISSUE TITLE
GPU Visual bug

### ISSUE THREAD

**Issue by SolidSlav** [wiremod/wire#1998]
mov #regVertexMode,1; is breaking GPU. 
![image](https://user-images.githubusercontent.com/57808381/68961687-22c9eb00-07fd-11ea-86f6-d5ece3ba7409.png)

**Comment by thegrb93** [comment]
Anything printing in console?

**Comment by JenyaRostov** [comment]
Nothing in the console,sadly

**Comment by nicothegoat** [comment]
The offset [(calculated here)](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_gpu/cl_init.lua#L389) is wrong, but less off for some models. The monitor bounds [(defined here)](https://github.com/wiremod/wire/blob/master/lua/wire/wiremonitors.lua#L163) might be wrong.
![gm_construct0003](https://user-images.githubusercontent.com/48368848/99151657-07f2b680-269d-11eb-81ee-84e0be020073.jpg)
( every display in this screenshot is offset, though some are close enough to where it's barely noticable )
