### ISSUE TITLE
A problem with 64-bit version of Garry's Mod and Pod Controlers

### ISSUE THREAD

**Issue by Polskimops** [wiremod/wire#1999]
On this version of Garry's Mod you can't use any Pod Controlers. Also all Wire Keyboards can only read alpha-numeric characters (they can't read buttons like F1, Delete, Home etc.) This thing seems 
 to apply only to players with 64-bit version of Garry's Mod turned on.

**Comment by thegrb93** [comment]
I haven't had these issues. Maybe OS dependent.

**Comment by TomyLobo** [comment]
either way, without further details, this sounds like a garry problem

**Comment by Fenteale** [comment]
My friend and I are having the exact same issue.  We are both on the x64 version on Linux.  Ill see if there is an issue for Gmod as well and post there.
