### ISSUE TITLE
Wrong font usage.

### ISSUE THREAD

**Issue by GitSparTV** [wiremod/wire#2000]
Some wiremod files use surface.CreateFont incorrectly.

File: `addons/wire-master/lua/entities/gmod_wire_keypad.lua`
fontName: `Trebuchet34`
fontData.font: `Trebuchet`

File: `addons/wire-master/lua/entities/gmod_wire_keypad.lua`
fontName: `Trebuchet24`
fontData.font: `Trebuchet`

File: `addons/wire-master/lua/weapons/gmod_tool/stools/wire_adv.lua`
fontName: `Trebuchet22`
fontData.font: `Trebuchet24`

File: `addons/wire-master/lua/weapons/gmod_tool/stools/wire_adv.lua`
fontName: `Trebuchet20`
fontData.font: `Trebuchet24`

File: `addons/wire-master/lua/weapons/gmod_tool/stools/wire_adv.lua`
fontName: `Trebuchet16`
fontData.font: `Trebuchet24`

File: `addons/wire-master/lua/weapons/gmod_tool/stools/wire_adv.lua`
fontName: `Trebuchet14`
fontData.font: `Trebuchet24`

File: `addons/wire-master/lua/wire/client/text_editor/wire_expression2_editor.lua`
fontName: `DefaultBold`
fontData.font: `defaultbold`

`Trebuchet` and `Trebuchet24` in fontData.font should be changed to `Trebuchet MS`.
`defaultbold` should be changed to `Tahoma`.

Otherwise this will be in the console:
> Failed creating font 'Trebuchet'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'defaultbold'!

**Comment by CornerPin** [comment]
Why is this not a pull request?

**Comment by thegrb93** [comment]
I'm on vacation.

**Comment by GitSparTV** [comment]
@CornerPin If you really want me to do a PR -- ok. I just have a reason no to clone the repo

**Comment by thegrb93** [comment]
Fork it, don't clone it.

**Comment by GitSparTV** [comment]
@thegrb93 Fork is the same no? Or you mean to fork and edit the file in GitHub instead of local cloning?

**Comment by thegrb93** [comment]
You can't push branches here, so you have to push to your fork instead. Then you pull request from your fork to this repo.

**Comment by GitSparTV** [comment]
@thegrb93 I know, I mean to edit files I have to use GitHub site or clone it, edit and push to work.

**Comment by GitSparTV** [comment]
So should I PR?

**Comment by thegrb93** [comment]
Ye

**Comment by GitSparTV** [comment]
Closed. Moved to https://github.com/wiremod/wire/pull/2002

**Comment by CornerPin** [comment]
In case you don't want to keep the fork on your GitHub profile, you can delete it after the changes are merged.
