### ISSUE TITLE
Wire keyboard input languages

### ISSUE THREAD

**Issue by Supertos** [wiremod/wire#2001]
[Suggestion] Please add ability to show images at EGP Screen. Also please add Russian and Ukraine languages to keyboard. It would be also great to allow users to write Cyrillic symbols at E2 Editor.

P. S. Sorry for my bad english.

**Comment by thegrb93** [comment]
The E2 editor request already exists. Custom images is a heavy request. Starfall has it though.

**Comment by thegrb93** [comment]
Looks like this was fixed in https://github.com/wiremod/wire/commit/697654ac4e56e291d2c6bf44a4aab6526157c825
