### ISSUE TITLE
Vector rotation gate modifies input value

### ISSUE THREAD

**Issue by OmaMitStaubsauger** [wiremod/wire#2004]
Steps to reproduce:
- Create a `Vector`->`Rotate` gate and connect it to a `Constant Value` with a value of `1,0,0`
- Spawn a random prop, use an `Entity Marker` and an `Entity`->`Angles` gate to get its angle
- Connect the `Angles` gate to the `Rotate` gate
- Monitor everything with the debugger

The `Rotate` gate's and `Constant Value`'s output will randomly change directions with every change in the prop's angle.

**Comment by TomyLobo** [comment]
This has been that way for literally all of Git history.
Nice spot!
