### ISSUE TITLE
Debugging tool breaks for all players on a server if an output type changes on an entity being debugged

### ISSUE THREAD

**Issue by CheezusChrust** [wiremod/wire#2010]
To reproduce:
- Spawn an E2 with various types of outputs
- Begin debugging the E2
- Open the E2 and change one of the output types without modifying its name
- Debugger is now broken for all players on the server until it restarts

**Comment by 12121095** [comment]
Please fix it

**Comment by Vurv78** [comment]
I can't reproduce this, does this still happen?  Is it only for all **other** players?
