### ISSUE TITLE
When presented with a nil number, number.lua seems to exception when performing arithmetic

### ISSUE THREAD

**Issue by marchkarcz** [wiremod/wire#2014]
sv: Expression 2 (LC2): entities/gmod_wire_expression2/core/number.lua:84: attempt to perform arithmetic on a nil value

I was attempting to do this: return (This:volume() == 0) in a function

**Comment by bigdogmat** [comment]
The only way for this to happen is either `volume(e:)` was modified or `physics:GetStress()` is returning nil. I couldn't get it to return nil for any entity so if you know what `This` was that'd be helpful. Also if you have access to the server could you run `PrintTable(debug.getinfo(wire_expression2_funcs["volume(e:)"][3]))` and get the output.

**Comment by marchkarcz** [comment]
Using the Make Spherical tool, volume will return nil on any entity that is spherical. I was thinking that the number would just default to 0 but it errored instead.

**Comment by bigdogmat** [comment]
Seems it also effects `GetSurfaceArea`, might be more so a Gmod issue than a wiremod one considering it isn't documented on the wiki.

**Comment by thegrb93** [comment]
E2 should default it to 0.

**Comment by thegrb93** [comment]
I updated the wiki.

**Comment by thegrb93** [comment]
Btw this bug is also why ACF stuff would glitch out when made spherical because it created lua errors.

**Comment by marchkarcz** [comment]
Made a PR in #2015

**Comment by TomyLobo** [comment]
Is there any gmod issue for this yet?

**Comment by marchkarcz** [comment]
I don't think it's a gmod issue itself, although I'm glad it does this for spherical entities as its easy to detect
