### ISSUE TITLE
problem with e2

### ISSUE THREAD

**Issue by SSsulaiman** [wiremod/wire#2016]
so when i try to even CLICK on e2 in the wire tab it shows the wiremod is creating script errors and i cant use e2 at all when this error pops up its said check the console for details, and this is what the console wrote.

[Wiremod] lua/entities/gmod_wire_expression2/cl_init.lua:48: attempt to index field 'PreProcessor' (a nil value)
  1. wire_expression2_validate - lua/entities/gmod_wire_expression2/cl_init.lua:48
   2. Validate - lua/wire/client/text_editor/wire_expression2_editor.lua:1595
    3. SetCode - lua/wire/client/text_editor/wire_expression2_editor.lua:1685
     4. NewScript - lua/wire/client/text_editor/wire_expression2_editor.lua:1512
      5. Setup - lua/wire/client/text_editor/wire_expression2_editor.lua:1951
       6. initE2Editor - lua/wire/stools/expression2.lua:822
        7. func - lua/wire/stools/expression2.lua:794
         8. FillViaFunction - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:100
          9. FillViaTable - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:89
           10. ActivateTool - lua/includes/modules/spawnmenu.lua:287
            11. DoClick - lua/wire/client/customspawnmenu.lua:577
             12. InternalDoClick - lua/vgui/dtree_node.lua:62
              13. DoClick - lua/vgui/dtree_node.lua:32
               14. unknown - lua/vgui/dlabel.lua:234

[Wiremod] lua/entities/gmod_wire_expression2/cl_init.lua:48: attempt to index field 'PreProcessor' (a nil value)
  1. wire_expression2_validate - lua/entities/gmod_wire_expression2/cl_init.lua:48
   2. Expression2Upload - lua/wire/stools/expression2.lua:526
    3. func - lua/wire/stools/expression2.lua:576
     4. unknown - lua/includes/extensions/net.lua:32

Requesting texture value from var "$basetexture" which is not a texture value (material: pp/copy)
] [Wiremod] lua/entities/gmod_wire_expression2/cl_init.lua:48: attempt to index field 'PreProcessor' (a nil value)  1. wire_expression2_validate - lua/entities/gmod_wire_expression2/cl_init.lua:48   2. Expression2Upload - lua/wire/stools/expression2.lua:526
Unknown command: [Wiremod]
] [Wiremod] lua/entities/gmod_wire_expression2/cl_init.lua:48: attempt to index field 'PreProcessor' (a nil value)  1. wire_expression2_validate - lua/entities/gmod_wire_expression2/cl_init.lua:48   2. Expression2Upload - lua/wire/stools/expression2.lua:526
Unknown command: [Wiremod]

[Wiremod] lua/entities/gmod_wire_expression2/cl_init.lua:48: attempt to index field 'PreProcessor' (a nil value)
  1. wire_expression2_validate - lua/entities/gmod_wire_expression2/cl_init.lua:48
   2. Expression2Upload - lua/wire/stools/expression2.lua:526
    3. func - lua/wire/stools/expression2.lua:576
     4. unknown - lua/includes/extensions/net.lua:32

[Wiremod] lua/entities/gmod_wire_expression2/cl_init.lua:48: attempt to index field 'PreProcessor' (a nil value)
  1. wire_expression2_validate - lua/entities/gmod_wire_expression2/cl_init.lua:48
   2. Validate - lua/wire/client/text_editor/wire_expression2_editor.lua:1595
    3. SetV - lua/wire/client/text_editor/wire_expression2_editor.lua:1634
     4. Open - lua/wire/client/text_editor/wire_expression2_editor.lua:1706
      5. func - lua/wire/stools/expression2.lua:628
       6. unknown - lua/includes/extensions/net.lua:32

**Comment by SSsulaiman** [comment]
Please Help!

**Comment by bigdogmat** [comment]
That table should exist, are there any earlier errors in your console? If not can you try reinstalling wiremod

**Comment by SSsulaiman** [comment]
no bigdogmat there was no earlier errors and just a few hours ago e2 worked fine

**Comment by SSsulaiman** [comment]
whoever put those labels they are wrong the BUG is reproducible it is a bug and this bug only works with Garry's Mod 13!

**Comment by bigdogmat** [comment]
I can't reproduce it, and it doesn't seem like anyone else is having this problem. Try validating your Gmod install and uninstall/disabling all other addons.

**Comment by SSsulaiman** [comment]
oh yeah actually the console only said this [Wiremod] lua/entities/gmod_wire_expression2/cl_init.lua:48: attempt to index field 'PreProcessor' (a nil value)
  1. wire_expression2_validate - lua/entities/gmod_wire_expression2/cl_init.lua:48
   2. Validate - lua/wire/client/text_editor/wire_expression2_editor.lua:1595
    3. SetCode - lua/wire/client/text_editor/wire_expression2_editor.lua:1685
     4. NewScript - lua/wire/client/text_editor/wire_expression2_editor.lua:1512
      5. Setup - lua/wire/client/text_editor/wire_expression2_editor.lua:1951
       6. initE2Editor - lua/wire/stools/expression2.lua:822
        7. func - lua/wire/stools/expression2.lua:794
         8. FillViaFunction - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:100
          9. FillViaTable - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:89
           10. ActivateTool - lua/includes/modules/spawnmenu.lua:287
            11. DoClick - lua/wire/client/customspawnmenu.lua:577
             12. InternalDoClick - lua/vgui/dtree_node.lua:62
              13. DoClick - lua/vgui/dtree_node.lua:32
               14. unknown - lua/vgui/dlabel.lua:234
