### ISSUE TITLE
Instant server HCF with NaNs from user input

### ISSUE THREAD

**Issue by TiberiumFusion** [wiremod/wire#2017]
Wiremod is possibly totaling servers when NaN inputs are introduced by players. I've had a server I support hang twice in a halt and catch fire manner, with wire at the very end of the log each time.

**Crash 1:**
<snip>
models/cheeze/wires/speaker.mdl (2) at -nan -nan -nan in contact with world (2) at -234.5 -4.2 241.7, crash. dist = -1, minq = 99999999999999997704951326524533662844684271992415000612999597473199345218078991130326129448151154688.000000
models/cheeze/wires/speaker.mdl (2) at -nan -nan -nan in contact with world (2) at -234.5 -4.2 241.7, crash. dist = -1, minq = 99999999999999997704951326524533662844684271992415000612999597473199345218078991130326129448151154688.000000

**Crash 2:**
<snip>
Crazy origin, angles, angular velocity on entity [1210][gmod_wire_gate]
	Origin:           [-nan, -nan, nan]
	Angles:           [-nan, nan, 180.000000]
	Velocity:         [0.000000, 0.000000, -0.000000]
	Angular Velocity: [-nan, -nan, nan]
Defusing!
Removing!

It seems that wire is the culprit or at least a starting factor in these crashes.
Is wire lacking NaN checks before user inputs reach vulnerable code?

**Comment by thegrb93** [comment]
There are NaN checks. Will probably need more information. If you have crash dump, you can report to garrysmod-issues.

**Comment by Divran** [comment]
Both of the errors are essentially the same thing. They are saying that an entity is at position -nan. Whatever moved the entity to that position however, isn't shown in the error message. It could be any mod on the server, and the fact that the entities in question happened to have a wiremod model or be a wiremod entity doesn't really matter.

Like thegrb93 said, as far as I know, all applyForce related code in wiremod already has checks for this. I guess it's possible we missed one, but I doubt it.

The chance that checks are missing is larger when talking about wire extras, though. Maybe you have that installed?

**Comment by TiberiumFusion** [comment]
@thegrb93 @Divran Thanks for the feedback. After extended consultation with the players relevant to the crashes, it's shaping up to be a problem with vphysics that may take many hours to reproduce. I couldn't determine any wiremod forcers/thrusters/etc to be part of the events relating to the entities with nans. The server does not have the wire extras addon, either. The implications against wiremod look pretty nil now.
Thank you for your patience with me. I jumped the gun on this one.

**Comment by Divran** [comment]
Alright I'll close it, but let us know if it turns out to be wiremod after all
