### ISSUE TITLE
[E2] holoColor() bug crashing almost any server

### ISSUE THREAD

**Issue by BadCod3r** [wiremod/wire#2022]
found its bug randomly ( just playing with color )
* Creating a hologram 
* Set its color to vec(inf()) 
* Server freezes forever
`holoCreate(1),holoColor(1,vec(inf()))`

**Comment by bigdogmat** [comment]
I can't reproduce this, and the color is clamped when set anyway. Make sure your wiremod is up to date and without any other addons enabled.

**Comment by BadCod3r** [comment]
> found its bug randomly ( just playing with color )
> 
> * Creating a hologram
> * Set its color to vec(inf())
> * Server freezes forever
>   `holoCreate(1),holoColor(1,vec(inf()))`

**Comment by thegrb93** [comment]
Maybe related https://github.com/thegrb93/StarfallEx/issues/816

**Comment by thegrb93** [comment]
Need to test hsvToRGB and rgbToHSV
