### ISSUE TITLE
Tick quota exceeded

### ISSUE THREAD

**Issue by zackadiax24** [wiremod/wire#2023]
Im making an E2 that makes being in water dangerous, for various reasons i cant use explosive props so i had to work around it. when i paste my E2 it gives me a tick quota exceeded error.

heres my code, i dont care if it gets out because you cant use it on most servers anyways.
https://pastebin.com/e0Fdy7CN

**Comment by bigdogmat** [comment]
What exactly is the issue?

**Comment by CornerPin** [comment]
Ask for help in the Wiremod Discord. You have a giant `foreach` loop, causing your chip to crash.
