### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by iquirno** [wiremod/wire#2024]
Hello, im a moderator in a server and recently we had a wiremod internal error. This error began when we switched maps to gm_fork. Ill post some screenshots and the console text below.
Any help would be appreaciated as we don't know what originated the issue or how to fix it. Thanks!

Console showed this:

"Internal error - please report to https://github.com/wiremod/wire/issues
lua/entities/gmod_wire_expression2/base/compiler.lua:46: attempt to index a nil value

Trace:
    1: Line 32    "Trace"        lua/includes/extensions/debug.lua
    2: Line 301    "__index"        lua/entities/gmod_wire_expression2/core/e2lib.lua
    3: Line 46    "nil"        lua/entities/gmod_wire_expression2/base/compiler.lua
    4: C function    "Execute"
    5: Line 74    "wire_expression2_validate"        lua/entities/gmod_wire_expression2/cl_init.lua
    6: Line 1595    "Validate"        lua/wire/client/text_editor/wire_expression2_editor.lua
    7: Line 1845    "Close"        lua/wire/client/text_editor/wire_expression2_editor.lua
    8: Line 826    "DoClick"        lua/wire/client/text_editor/wire_expression2_editor.lua
    9: Line 234    "nil"        lua/vgui/dlabel.lua"

![unknown-61](https://user-images.githubusercontent.com/61035688/74495704-5a593980-4eb7-11ea-941c-609ee81411e9.png)
![unknown-57](https://user-images.githubusercontent.com/61035688/74495720-5fb68400-4eb7-11ea-8796-c5a7e426db11.png)
![unknown-53](https://user-images.githubusercontent.com/61035688/74495728-634a0b00-4eb7-11ea-91b3-9bd8907ddfc4.png)
![unknown-144](https://user-images.githubusercontent.com/61035688/74495737-6a711900-4eb7-11ea-90f3-ced2b84d920b.png)

**Comment by bigdogmat** [comment]
It seems like none of the E2 extensions are loading. Are there any early errors in server/client console (doesn't even have to be from wiremod)? If there aren't try reinstalling wiremod.

**Comment by iquirno** [comment]
I don't see any errors apart from "tried to look up thirdperson as if it were a variable" whenever i enable the thirdperson camera. Ill try to have wiremod reinstalled, thanks. Ill hit you up when its fixed.

**Comment by bigdogmat** [comment]
It's possible that your install is just corrupt. The default extension loader won't error but just fail to load.

**Comment by iquirno** [comment]
the server has been up for over a year though. this is the first time it happened to us

**Comment by thegrb93** [comment]
If you guys installed a new addon, that could be it.

**Comment by iquirno** [comment]
We haven't installed anything recently. We're going to try to do a full reinstall of the adddon

**Comment by iquirno** [comment]
We fixed it. Thanks for the help!

**Comment by oldmud0** [comment]
How did you fix it?

**Comment by thegrb93** [comment]
Lol you're welcome
