### ISSUE TITLE
Cannot create extension with more than 200 local variables

### ISSUE THREAD

**Issue by dvdvideo1234** [wiremod/wire#2025]
Simply what it says:
```lua
[ERROR] entities/gmod_wire_expression2/core/custom/ftrace.lua:271: main function has more than 200 local variables
  1. unknown - addons/wiremod_git/lua/entities/gmod_wire_expression2/core/extloader.lua:86
   2. pcall - [C]:-1
    3. e2_include_finalize - addons/wiremod_git/lua/entities/gmod_wire_expression2/core/extloader.lua:101
     4. unknown - addons/wiremod_git/lua/entities/gmod_wire_expression2/core/extloader.lua:172
      5. include - [C]:-1
       6. unknown - addons/wiremod_git/lua/entities/gmod_wire_expression2/core/init.lua:194
        7. include - [C]:-1
         8. unknown - addons/wiremod_git/lua/entities/gmod_wire_expression2/shared.lua:26
          9. include - [C]:-1
           10. unknown - addons/wiremod_git/lua/entities/gmod_wire_expression2/init.lua:3
```
Thugh, I sure I am way below the maximum number of locals (searching for `local`):
![image](https://user-images.githubusercontent.com/9112662/74594472-8a334900-503f-11ea-90fe-18d7a48c4a2a.png)

I am also sure that this limit is set per file, as I removed a local helper function function from my other file and the result is the same.
> ![image](https://user-images.githubusercontent.com/9112662/74592644-dd9b9c00-502b-11ea-96e8-9720f1586e18.png)

I had the error then I

**Comment by thegrb93** [comment]
Lua has a limit on number of locals. This is what over-localizing causes.

**Comment by thegrb93** [comment]
Also the reason it is erroring despite you being under the limit is the preprocessor probably adds some locals into the mix as well.

**Comment by bigdogmat** [comment]
> Also the reason it is erroring despite you being under the limit is the preprocessor probably adds some locals into the mix as well.

^, each function you create adds a new local variable. Considering how many functions are in your file it's not surprising you're hitting the limit

**Comment by thegrb93** [comment]
Perhaps the preprocessor needs to scope them inside a `do end` so that the main file doesn't get filled up with them; I don't know how it works though.

**Comment by bigdogmat** [comment]
It took me a while to figure out if that'd be possible, the one problem I came across was function aliases. Functions are stored in local variables and then registered at the end of the file, this way aliases can just refer to their aliased function.

Simplest way without rewriting a lot of the preprocessor would be to store the functions in a table

**Comment by dvdvideo1234** [comment]
The 148 are in fact all the local variables in the file. Including the ones that are defined inside a function and are local to the function itself. So that means the actual number of the local variables is even under 148, because I just searched for the string `local`.

**Comment by dvdvideo1234** [comment]
> Simplest way without rewriting a lot of the preprocessor would be to store the functions in a table

This is how I reduced the locals in TA. by calling `(Get/Set)OpVar(#HASH, VALUE)` maybe it will help

https://github.com/dvdvideo1234/TrackAssemblyTool/blob/master/lua/trackassembly/trackasmlib.lua#L521

**Comment by bigdogmat** [comment]
@dvdvideo1234 If you look at #2026 I've already modified the extension preprocessor to not use locals for every function. If you could test it and check that you're not hitting the limit.

**Comment by dvdvideo1234** [comment]
@bigdogmat  @thegrb93 

Hello, The testing methodology

1. I switched Wiremod to [your branch](https://github.com/wiremod/wire/tree/extpp-less-locals)
2. Confirmed having `"\nlocal tempcosts,registeredfunctions={},{}"` in [extpp.lua](https://github.com/wiremod/wire/commit/2c6978200a031cb8825617c50b9851bdc60278b9)
3. I switched my [E2 Control theory addon](https://github.com/dvdvideo1234/ControlSystemsE2) back to [the problematic commit](https://github.com/dvdvideo1234/ControlSystemsE2/commit/c0d72f18a1345b7c88b54927a6a2b50ac354457f)
4. Confirmed I have overhead locals like `local tonumber = tonumber`
5. loaded Gmod and confirmed it is working and both classes are registered correctly.
![image](https://user-images.githubusercontent.com/9112662/74779033-725cfe80-52a5-11ea-9143-69a8592d3065.png)

Thank you!
