### ISSUE TITLE
What hashing algorithm is used for hash(s) ?

### ISSUE THREAD

**Issue by TAbdiukov** [wiremod/wire#2027]
I searched far and wide, and couldn't find any info. I want for both client and server to be able to verify the integrity of some transmission (to an extent, nothing is perfect) and to keep things easier (and faster) on E2-side, I want to use the stock hashing algorithm. Can anyone advise on what hashing algorithm is used for `hash(s)` ? Is it, for example, a CRC32, BLAKE, or Adler, or something else? Cheers

**Comment by bigdogmat** [comment]
CRC-32
