### ISSUE TITLE
Expression 2 Core is not allowing my E2s that I had forever to work

### ISSUE THREAD

**Issue by TheGNinja** [wiremod/wire#2030]
So I have some E2s that I use frequently and recently bought a new server for my friends and I to play on. I'm not sure if that has some relivence but E2 Core is causing my chips to "Script Error" I went ahead and looked for the source and found it in the Core.Lua file of Expression 2 on the server.

`__e2setcost(0) -- cascaded

registerOperator("is", "n", "n", function(self, args)
	local op1 = args[2]
	local rv1 = op1[1](self, op1)
	return rv1 ~= 0 and 1 or 0
end)
`
This part of the code is giving a nil value for some reason, I have no idea how to fix this any suggestions?

**Comment by thegrb93** [comment]
Try this version https://github.com/wiremod/wire/archive/e5e90ce1e2187bef6f6334cd16fd25505e144481.zip

If it works in that, then I think @bigdogmat needs to take a look.

**Comment by bigdogmat** [comment]
I'm gonna assume this is the `changed` issue considering this is erroring inside of an if statement. Update to latest version and see if it's still broken. Luckily #2026 didn't make it onto workshop release.

**Comment by Divran** [comment]
yep. this was the error someone else reported to me when I found the changed issue. so it should be fixed with https://github.com/wiremod/wire/commit/328e6748f78ea9f58884bd3429e2c4eb6012912a this update
