### ISSUE TITLE
A bug reporting

### ISSUE THREAD

**Issue by ddubaa99** [wiremod/wire#2033]
1. Not working the E:propDrag(N) function in e2(still affected to some props).

2. i finded a another wiremod bug about wire hydraulic unit.
If you use ADV Duple2 several times, the hydraulic unit self destructed.

**Comment by thegrb93** [comment]
1. Do you have examples of props? The only ones I can think of this not working are ragdolls.

**Comment by ddubaa99** [comment]
> 1. Do you have examples of props? The only ones I can think of this not working are ragdolls.

EX) Sprop superthin 12x192 ect ect...

**Comment by thegrb93** [comment]
Can't reproduce either of those.
