### ISSUE TITLE
Wire components refusing to spawn/Defaulting to default model.

### ISSUE THREAD

**Issue by NinjasInMyBasement** [wiremod/wire#2034]
(Workshop version)
Issue: After running wiremod on a dedicated server with only wiremod installed, no players playing (with 1 daily restart) for several days, many components refuse to spawn, and some components such as buttons, dynamic buttons, and many others will instead spawn their default model (in the case for buttons, this would be clock model), or with gates they turn into a barrel.

As for components that refuse to spawn, some examples of these are: Rangers, Expression 2, cam controllers.

How to reproduce: 
1)Put the wiremod workshop addon in a server addon collection.
2)Run a dedicated server for 2-14 days
3)Try to use the ranger, or dynamic buttons, or other problematic wire components.
![WireBugReport1](https://user-images.githubusercontent.com/19523856/76153056-82355a80-607b-11ea-8ea0-2cd14042eab9.png)
![WireBugReport2](https://user-images.githubusercontent.com/19523856/76153064-a5600a00-607b-11ea-8965-1d85a687ec0c.png)

I should also note there is no console errors in either client, or server console.

**Comment by bigdogmat** [comment]
The reason this happens is because the models become invalid to `util.IsValidModel`, and the models don't exist to `Model` either. I haven't found the cause, I only know the above because it happened to a server I admin. After a restart it fixes itself.

I'll try looking into it more this weekend

**Comment by NinjasInMyBasement** [comment]
> 
> 
> The reason this happens is because the models become invalid to `util.IsValidModel`, and the models don't exist to `Model` either. I haven't found the cause, I only know the above because it happened to a server I admin. After a restart it fixes itself.
> 
> I'll try looking into it more this weekend

Thank you, however sometimes a restart does not seem to fix it. Sometimes this lasts ages. I do appreciate you looking into this, as this issue has been plaguing my community causing lots of disruptions and angry folk. In the meantime, do you think there is a script I can make that can check if util.IsValidModel is valid, and if not, to restart the server?

**Comment by bigdogmat** [comment]
You could, however if a restart sometimes doesn't fix it then that may be a bad idea.

**Comment by thegrb93** [comment]
It's a gmod bug. The filesystem gets screwed up or something.

**Comment by thegrb93** [comment]
Only useful advice is to reinstall stuff and verify there's no corruption.

**Comment by NinjasInMyBasement** [comment]
> 
> 
> Only useful advice is to reinstall stuff and verify there's no corruption.

Have reinstalled SEVERAL times running into this issue

**Comment by thegrb93** [comment]
An installed addon triggering the bug maybe?
