### ISSUE TITLE
Digital screen draws pixels darker the further away you are

### ISSUE THREAD

**Issue by JaCoB123456798** [wiremod/wire#2037]
This used to happen on only one server and as of today, it happens in single player and every server I go on. It's really bad when something is drawing and you are moving around doing other stuff. I have the workshop version of wiremod but I don't know about the server I'm on. It's entirely client side. Sometimes if you wait a long time it fixes itself.
![image](https://user-images.githubusercontent.com/46092227/76456928-dacf6500-63a5-11ea-8e16-cb7b409707b7.png)

**Comment by thegrb93** [comment]
A bug with drawing the pixel it seems. The reason it fixes itself is because it will redraw the whole screen during a refresh.

**Comment by JaCoB123456798** [comment]
Is there a way to manually trigger a refresh?

**Comment by thegrb93** [comment]
I remember there was a 'fix wire screens' button somewhere but I think its been deleted or something.

**Comment by thegrb93** [comment]
My guess is there's something intrinsic about the ENT:Draw hook causing the lighting changes. Best solution would be to do the rendering in a non-entity hook.

**Comment by thegrb93** [comment]
Another option may be to disable engine shading.

**Comment by thegrb93** [comment]
Can you see if this fixes it? https://github.com/thegrb93/wire/archive/fix-gpulib-lighting-issue.zip

**Comment by JaCoB123456798** [comment]
Sorry I completely forgot about this. The issue hasn't happened for a very long time outside of the server and I'm not sure I can get them to try this solution.
