### ISSUE TITLE
No such function print(void) and E2 Extension load bug

### ISSUE THREAD

**Issue by diefromsuicide** [wiremod/wire#2043]
E2 Extensions do not load completely, and in expression2 writes that there is no such print () function

**Comment by thegrb93** [comment]
You have a bad addon causing some other errors. Try uninstalling other things until it's fixed.

**Comment by diefromsuicide** [comment]
When I turn off all add-ons and leave only Wiremod, everything works correctly!

**Comment by diefromsuicide** [comment]
But, what is this addon that prevents e2 extensions from loading?

**Comment by thegrb93** [comment]
You'll have to find it yourself.
