### ISSUE TITLE
Wiremod Wire tool keeps connecting wires into one

### ISSUE THREAD

**Issue by NewbieHookTheWebhook** [wiremod/wire#2045]
I'm not sure if this is a BUG, or a FEATURE, but, it is annoying.
![image](https://user-images.githubusercontent.com/38844918/80064535-eb730f00-84fd-11ea-8a79-b00b6d4d78a7.png)

**Comment by thegrb93** [comment]
You gotta explain with more detail

**Comment by NewbieHookTheWebhook** [comment]
Basically, the wires connect and won't connect with wireable objects.

**Comment by thegrb93** [comment]
Still no idea what you mean.

**Comment by thegrb93** [comment]
That'd be better

**Comment by NewbieHookTheWebhook** [comment]
Ok.

**Comment by NewbieHookTheWebhook** [comment]
https://www.youtube.com/watch?v=O-ufpDKAQb8

**Comment by Divran** [comment]
you're holding shift, the standard "select more" button in most applications

**Comment by NewbieHookTheWebhook** [comment]
I wasn't holding shift though.

**Comment by thegrb93** [comment]
Looks like you're stuck sprinting or something which is what counts as shift. Or you have an addon causing it.

**Comment by NewbieHookTheWebhook** [comment]
Nevermind, I had shift binded to +duck (I play minecraft alot, so i get confused.) I unbinded and it worked.
