### ISSUE TITLE
The switch statement evaluates its expression multiple times

### ISSUE THREAD

**Issue by CornerPin** [wiremod/wire#2049]
The switch statement expression is evaluated for every comparison.

```golo
Calls = 0

if (first()) {
    function number rand3() {
        Calls++
        return randint(3)
    }
}

switch (rand3()) {
    case 1,  print("Case 1") break
    case 2,  print("Case 2") break
    case 3,  print("Case 3") break
    default, print("Default") # Should never print
}

print("Calls: " + Calls + "\n")

interval(1000)
```
Outputs:
```
Default
Calls: 3

Default
Calls: 3

Case 3
Calls: 3

Case 2
Calls: 2

Default
Calls: 3

Case 1
Calls: 1

Case 3
Calls: 3
```

**Comment by Divran** [comment]
Hmm, I'm not sure how to go about fixing that. @thegrb93 , any ideas?

**Comment by thegrb93** [comment]
I'm guessing this is getting the rand3 function, https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/base/compiler.lua#L881

and then this is evaluating it? https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/base/compiler.lua#L902

We need to move its evaluation to before checking each case, and check each case with that result. I have no idea how E2 stack works though.

**Comment by thegrb93** [comment]
In other words, we just need https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/base/compiler.lua#L881 to fully evaluate the expression inside of it.

**Comment by Divran** [comment]
I think I may have fixed it. I don't know if this is the 'proper' way to do it though
```
function Compiler:InstrSWITCH(args)
	-- args = { "switch", trace, value expression, { { case expression or nil, body }... } }
	-- up to one case can have a nil case expression, this is the default case
	self:PushPrfCounter()
	local val, type = self:EvaluateStatement(args,1) -- This is the value we are passing though the switch statement
	local prf_cond = self:PopPrfCounter()

	-- build table which ensures the value is only evaluated one time
	local value = {
		function(self, args)
			if not args.evaluated then
				args.evaluated = val[1]( self, val )
			end

			return args.evaluated
		end
	}

	[...]
```

**Comment by bigdogmat** [comment]
I don't think there is a proper way to do this.  A_less_ hacky way might involve assigning the value to a hidden global then accessing it (e.g. delta), not to say that would be better.

**Comment by Divran** [comment]
that seems like more hacky to me. keep in mind that the "args" table I'm saving it to right there is the "value" table.
```
local value = { <-- value table here and
		function(self, args) <-- args table here, are both the same exact table
```

**Comment by Divran** [comment]
I also dunno if it properly resets itself through executions. Will this code evaluate one time and then never again for the whole lifetime of the e2? it might.

**Comment by bigdogmat** [comment]
> Will this code evaluate one time and then never again for the whole lifetime of the e2?

Yes, it'll have to be reset inside the `switch` operator function. I proposed mine cause it doesn't require fakey statements
