### ISSUE TITLE
& doesn't work

### ISSUE THREAD

**Issue by TheLightBringer1991** [wiremod/wire#2057]
& doesn't work at all.

If I try to do something like this:

Value=(A*30||(A&B)*10)

if I press only A value should be 30, if I press A and B togheter, value should be 10. Instead it still says 30, no matter what I do, tried to use && too, but with no success.

Funny thing is, it works fine in old E2s that don't get edited.

**Comment by TheLightBringer1991** [comment]
After more testing, the problem seems to be when it is used with the | function. It used to work with only | now it needs to be || and messes up when used with &.

**Comment by thegrb93** [comment]
Can you find the version where it stops working?

**Comment by CornerPin** [comment]
Nothing's wrong with the operators here, you are performing bitwise OR of `30` and `10`, which is `30`. `&` and `|` are logical operators, `&&` and `||` are bitwise operators.
|30 \|\| 0|30 \|\| 10|
|---------|---------|
|`11110` [30]<br>`00000` [0]<br>`=====`<br>`11110` [30]|`11110` [30]<br>`01010` [10]<br>`=====`<br>`11110` [30]|

Instead, you should be using `if else` statements or ternary operators.

**Comment by TheLightBringer1991** [comment]
If I use | instead of || , output is 1.

And I don't know when it stopped working right, it just did some time ago, couple of months probably.

**Comment by CornerPin** [comment]
> If I use | instead of || , output is 1.

Because it's a logical operator, it's supposed to either return `0` or `1`, not its operands. You can look at the git history of https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/core.lua, it always worked that way.

**Comment by bigdogmat** [comment]
As said before it has always worked this way. A solution to your problem would be `A * 30 + (A & B) * 10`.

Any further questions can be brought up on the discord.
