### ISSUE TITLE
E2 string crash

### ISSUE THREAD

**Issue by Nexeonenn** [wiremod/wire#2063]
*deleted*

**Comment by viral32111** [comment]
bruh learn how to use [collapsable content](https://github.com/dear-github/dear-github/issues/166#issuecomment-236342209) & [code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) in comments lmao, this took ages to scroll through :/

**Comment by Divran** [comment]
We already know about this crash. Unfortunately, gmod doesn't support sandboxing lua code to the level required to fix this. The only way to "fix" it would be to delete all those functions from E2 entirely.

**Comment by thegrb93** [comment]
This actually doesn't crash. It just lags really badly. It doesn't lag starfall though so E2's gmatch is doing something weird.

**Comment by thegrb93** [comment]
Maybe it would be possible to count the number of 'or more' operators in the regex and set a limit to the input string, since those are O(N^2). 1=2048, 2=1024,

Limit = 16384/(2^(n-1)) where n is number of 'or more' operators.
