### ISSUE TITLE
E2 Lines aren't accurate

### ISSUE THREAD

**Issue by schnitzelgithub** [wiremod/wire#2066]
Hello,

I play on a gmod server that used wiremod and E2 first wenn i joied it was fine but now the Lines are not accurate.i dont new what to do but wiremod sayed to me that i have a older version of it so i downloaded (with SVN) the update, But it didn't work to. The thing is on the server everyone see it normal and i dont now why i didn't see is so.

it look like so 
![4000_screenshots_20200705174930_1](https://user-images.githubusercontent.com/68058300/87029690-c5960600-c1e0-11ea-8a7d-579e1bab74c3.png)

**Comment by TomyLobo** [comment]
This bug tracker is for bug reports, not support.
Ask on Discord.
See https://www.wiremod.com/ for the invite link.
