### ISSUE TITLE
how do i disable the halo around wiremod's item

### ISSUE THREAD

**Issue by Oaklizard-2047** [wiremod/wire#2070]
not because its ugly, its laggy. everytime i point at a button it, my fps drops to 20-15. so thats why i want to disable it.

**Comment by viral32111** [comment]
I don't think there's a convar available for this. However, a dirty workaround would be to remove the various hooks that create the halos around the entities, after a quick search I found these three (there could be more, I'm not 100% sure):
* [Wiremod_overlay_halos](https://github.com/wiremod/wire/blob/b5460f8795340e52e5fff8c243ca3cf0417cb1ab/lua/entities/base_wire_entity.lua#L246-L251).
* [Wiremod_dynbutton_overlay_halos](https://github.com/wiremod/wire/blob/ea9f63ec7eb52ae8809a1e4e744c5eea546c6e1e/lua/entities/gmod_wire_dynamic_button.lua#L27-L32).
* [Wiremod_button_overlay_halos](https://github.com/wiremod/wire/blob/ea9f63ec7eb52ae8809a1e4e744c5eea546c6e1e/lua/entities/gmod_wire_button.lua#L34-L39).

Hooks can be removed on the client by running `lua_run_cl hook.Remove( "Name", "Identifier" )` (replacing `Name` & `Identifier` with the appropriate values, host/server must also have `sv_allowcslua` set to `1`).

If there is indeed no convar for this, I could create a simple PR to add one, if the repo maintainers agree on having the convar.

**Comment by thegrb93** [comment]
Hold c, open the option in the top left of the screen, then uncheck the halo options.

**Comment by TheLightBringer1991** [comment]
Try wire_drawoutline 0.
