### ISSUE TITLE
'createSound outside PVS/PAS' update caused sound pitch update rate to lower drastically

### ISSUE THREAD

**Issue by CheezusChrust** [wiremod/wire#2073]
After update https://github.com/wiremod/wire/commit/833cb6bb89daa7a0ef32a150084c28f23b5d5627, creating sounds in E2 and attempting to set the pitch rapidly/smoothly (for example, an engine sound E2) has a very noticeable "stepping" effect to it. Using the fade argument in soundPitch doesn't help, in some cases making the effect worse.

Example code, spawn this and listen. Before https://github.com/wiremod/wire/commit/833cb6bb89daa7a0ef32a150084c28f23b5d5627 it's very smooth, and after it has the stepping effect.
```golo
@name Sound Pitch Test

runOnTick(1)

if(first()) {
    entity():soundPlay(1, 0, "synth/sine.wav")
}

soundPitch(1, 100 + sin(curtime()*200) * 50)
```

**Comment by thegrb93** [comment]
Sounds like a facepunch/garrysmod-issue then

**Comment by nonstopjoker** [comment]
I'm having the same issue. It's also happening with ACF addon.

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/4606

**Comment by sammyt291** [comment]
Seems to be the same with and without the filter for me:
[https://streamable.com/mcvxm3](url)

**Comment by thegrb93** [comment]
Might depend on your ping

**Comment by thegrb93** [comment]
Its hard to notice, but its quite a bit choppier with the filter.

**Comment by sammyt291** [comment]
> Might depend on your ping

Yeah i was using a dedicated server on my Lan so, yeah that could be amsking the issue for me :)

**Comment by thegrb93** [comment]
We will need to set the sound to be unreliable when gmod is updated.
