### ISSUE TITLE
E2 add roping to bones

### ISSUE THREAD

**Issue by DapperNurd** [wiremod/wire#2085]
Roping is kind of limited already, but you can only rope to entities. I think it would be really cool if you could rope to bones specifically instead of the entity itself. When roping to the entity of a ragdoll, it attaches to it's mid section, and that is okay but it would be so much nicer if you could specify where the rope should attach, just as if you were using the rope tool on a ragdoll.

**Comment by thegrb93** [comment]
Isn't there a bone number option?

**Comment by Bencraft8** [comment]
![image](https://user-images.githubusercontent.com/26912300/91781986-b021d480-ebb0-11ea-9470-d0ff9eca64a1.png)
no

**Comment by thegrb93** [comment]
Yeah. Looks like all the constraint functions have 0,0 for the bone number. Guess new overloads are needed.

**Comment by Denneisk** [comment]
This can be closed now.
