### ISSUE TITLE
how to disable ring effect?

### ISSUE THREAD

**Issue by Oaklizard-2047** [wiremod/wire#2087]
ive used wire_drawoutline 0, but buttons and some other elements still have effect rings. is there anyway to disable this?

**Comment by thegrb93** [comment]
Which elements?

**Comment by Oaklizard-2047** [comment]
nevermind, apparently only buttons are unaffected by wire_drawoutline. so how do i disable ring effects on buttons?

**Comment by thegrb93** [comment]
Looks like a bug
