### ISSUE TITLE
Hud Indicator vehicle detection inconsistent with Pod Controller

### ISSUE THREAD

**Issue by copperwarrior** [wiremod/wire#2091]
The Hud Indicator entity does not use the same fake vehicle detection as the Pod Controller. This results in pod controllers working with my lua based seats with a warning message, but hud indicators not working at all.

I believe this is specifically due to this line:
https://github.com/wiremod/wire/blob/ea9f63ec7eb52ae8809a1e4e744c5eea546c6e1e/lua/wire/stools/hudindicator.lua#L127

Also, this issue is present in the WireExtras Advanced Hud Indicator. I'm not sure if I should duplicate this issue there as well.

**Comment by Divran** [comment]
The hud indicator is just a really, really, REALLY old entity that hasn't been touched in forever.

For reference, every other entity (most other entities) that can be linked to vehicles all use the same general way:
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_pod.lua#L204-L207
and
https://github.com/wiremod/wire/blob/master/lua/wire/wireshared.lua#L1033-L1108

I might get around to looking at the indicator later, but if anyone else wants to update it to use the above before me that'd be great
