### ISSUE TITLE
EGP Emitter text disappears

### ISSUE THREAD

**Issue by nokoto6** [wiremod/wire#2092]
**On EGP Emitter, When you set the angle of the text, it disappears. 
Code example:**

    if(first()) {
        EGP = entity():isWeldedTo():wirelink()
        EGP:egpClear()
        EGP:egpText(1, "KaKTyC", vec2(256))
        EGP:egpFont(1, "consolas", 20)
        EGP:egpAngle(1, 45)
    }

**Comment by CornerPin** [comment]
Works perfectly fine for me, make sure your Wiremod is up-to-date.
![image](https://user-images.githubusercontent.com/7669876/95658310-112eb780-0b22-11eb-97f8-4d151c88c23f.png)

**Comment by 0x00000ED** [comment]
EGP Emitter not EGP Screen...

**Comment by CornerPin** [comment]
Oh right, I'm blind.

**Comment by CornerPin** [comment]
Apparently duplicate of #776.
