### ISSUE TITLE
Setting the E2 name to a null char causes it to download infinitely

### ISSUE THREAD

**Issue by evilfactory** [wiremod/wire#2095]
```
@name 
@inputs 
@outputs 
@persist 
@trigger 

setName(toChar(0))
```

[short video](https://cdn.discordapp.com/attachments/764237100203638795/770287344409641022/wiremod.mp4)

**Comment by Fasteroid** [comment]
I've used this before as a form of DRM for E2s >->
If this gets patched I have no way to fully protect my stuff from badmins.

**Comment by RealNoooooo** [comment]
you could put credits in the e2 or hint the credits but just like fasteroid said it's a good way to prevent downloading and copying e2's

**Comment by thegrb93** [comment]
There's an addon to download player's data folders. I don't think this makes you safe.

**Comment by thegrb93** [comment]
I guess it does make you safe against the lower-tier admins though.
