### ISSUE TITLE
Memory to String is broken?

### ISSUE THREAD

**Issue by VigilanteHobo** [wiremod/wire#2096]
I have been trying to convert the characters in a 64 store to a string but can't find any way to do it through this gate. Am I doing things wrong or is this broken?
https://github.com/wiremod/wire/blob/410ab96ed35e0713c380d1bf720ee655d9b4aeba/lua/wire/gates/string.lua#L363

**Comment by thegrb93** [comment]
You need to set the length of the string in address 1, then your string in address 2-end. Then set address 0 to 1 and it will output the desired string.

**Comment by VigilanteHobo** [comment]
I'm having problems with wiring it up to ram since its memory is in the output.

**Comment by thegrb93** [comment]
you'll need to wire it to a memory bus, not ram. I suggest discussing this in the discord #help channel.
