### ISSUE TITLE
E2 functions to set bodygroups but not get bodygroups

### ISSUE THREAD

**Issue by JaCoB123456798** [wiremod/wire#2102]
E2 has a way to set bodygroups (entity:setBodygroup(number bgrp_id,number bgrp_subid)) but not get the state of them. The most you can do is get the amount of bodygroups in a group id.

**Comment by nicothegoat** [comment]
It does have that though? [`number entity:getBodygroup( number bgrp_id )`](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/entity.lua#L518)

**Comment by JaCoB123456798** [comment]
I just realized I was thinking about bodygroups wrong. I was thinking you'd need to check each sub id.
