### ISSUE TITLE
Transferring to another chair when i sit based on chair while.

### ISSUE THREAD

**Issue by tjrtk95** [wiremod/wire#2104]
I'm from Korea. Sorry to my bad english ability.
Recently, while using the advanced duplicator2, I noticed a strange phenomenon based on me.
For example, if I install 4 chairs in my car creation, I stay where I sit, but it is transferred to another chair, and it can only be controlled from that chair. Anyone can help me? Help!
There is no right place to ask a question, so here is a question.

**Comment by thegrb93** [comment]
I think you have a problem with another addon. I can't understand without a video or pictures.
