### ISSUE TITLE
Whitelist/Blacklist for Wire Users

### ISSUE THREAD

**Issue by bellum128** [wiremod/wire#2109]
I had a suggestion that I wanted to get opinions on, regarding the Wire User. 
Currently, the Wire User allows "using" on essentially any object, including certain weapons, weapon ammo crates, health chargers, and so on. Players have discovered that they can essentially use this to achieve unlimited ammo/health by constantly having a User use health chargers and ammo crates for them.

What are your thoughts on implementing an entity blacklist and/or whitelist for the Wire User tool, to disallow certain weapon/entities from being picked up/used by the user?

**Comment by Divran** [comment]
the user already checks this hook
<https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_user.lua#L38>
before it uses the entity. You can simply add a distance check to this hook on your server to block the majority of these things.

If anything like what you ask is going to be implemented, then it should be as a fourth parameter to the hook, specifying that it was called from a wire user

**Comment by bellum128** [comment]
> distance check

Good point, I didn't even think of a simple distance check. That should solve these issues...
