### ISSUE TITLE
von.lua erroring in recent update

### ISSUE THREAD

**Issue by Bryantdl7** [wiremod/wire#2113]
Hello! 

As of the recent update two days ago to wire, E2s are not working properly, with a vague tooltip error saying von.lua is the culprit. Unfortunately, this error does not even make a console log entry, it just give a little tip with red x in it giving a very vague message. 
![photo_2020-12-08_13-19-39](https://user-images.githubusercontent.com/5564661/101524543-0fce0f80-3958-11eb-897b-f6e41eec925d.jpg)

In doing some digging, my initial thought was this was a conflicting addon, however, I have gone through all addons which have updated since November 30th, making me come to the conclusion that something which was adjusted in the recent Wire update has caused it to start conflicting with other addons, and break E2. 

Happy to debug as necessary, currently our server's E2 is completely dead! :-1:

**Comment by thegrb93** [comment]
Can you put a picture where the error is actually readable? I didn't get any errors while testing.

**Comment by Bryantdl7** [comment]
Sorry compression loves github it seems. Try this one: https://steamcommunity.com/sharedfiles/filedetails/?id=2313230627

**Comment by thegrb93** [comment]
Pretty sure the cause is this. https://github.com/wiremod/wire/pull/2103 but the question is why. I'll test more later, but my first thought is you have an addon that changes the e2 netcode.

**Comment by thegrb93** [comment]
Just tested on my server some more and didn't run into that error so it must be an addon.

**Comment by Bryantdl7** [comment]
I just went through and removed every e2-related addon and still the issue persists. 

I was able to get a better error message, however. 

Expression 2 upload failed! Error message:
lua/wire/von.lua:180: vON: Malformed data... Can't find a proper type definition. Char#1:�

**Comment by thegrb93** [comment]
Probably some other addon then. We'd most likely be getting a lot more complaints if it was a widespread issue.

**Comment by Bryantdl7** [comment]
For future reference, I have attached the culprit addon, e2logger. 

[e2logger.tar.gz](https://github.com/wiremod/wire/files/5718570/e2logger.tar.gz)

This addon was indeed messed up by the latest update, as this was a legacy addon and had not been modified since roughly 2019. Not a deal breaker, just letting you guys know.

**Comment by thegrb93** [comment]
They made a terrible mistake overloading the net functions. Should've just detoured one of the entity's functions.
