### ISSUE TITLE
Expanding the prop spawner

### ISSUE THREAD

**Issue by Shidoengie** [wiremod/wire#2119]
The prop spawner is extremely limited because of the limitation of only being able to spawn props and because of this things like spawning a explosive , a entity, a vehicle etc.. become extremely difficult or impossible

**Comment by TheMerkyShadow** [comment]
This was probably done on purpose to prevent minging. 
If you would like to spawn an entity might I suggest an Doragon's AdminCore addon which allows you to do this.

**Comment by Divran** [comment]
adv dupe 1 has a dupe spawner, and I believe adv dupe 2 does as well. there's really no need to also add this functionality to the prop spawner.
