### ISSUE TITLE
R:remove() - Moves index'es while looping.

### ISSUE THREAD

**Issue by EpicGamerMic** [wiremod/wire#2120]
I don't think it's an actual bug, but I don't know where else to post it.

the removeNumber, string, whatever moves the indexes 1 down while in a loop, witch can fuck up ur loop alot.

Example.
Lets say I have an array that looks like (1,2,3,4,5).
I want to remove 2 and 3.
```
for(I = 1, Array:count())
{
  A = Array[I, number]
  if(A == 2 | A == 3)
  {
    Array:remove(I)
  }
}
```

Here comes my problem, when it removes index 2 the remove() function moves all other indexes down 1 and therefore it skips index 3 (witch is now index 2)

I hope this makes sense, and I'm currently just using tables.

**Comment by bigdogmat** [comment]
This is intended behavior, loop backwards `for(I = Array:count(), 1, -1)`

**Comment by CornerPin** [comment]
This is not a bug, you have to iterate backwards. Generally, you shouldn't be adding/removing fields to arrays/tables you are iterating over.

>  I don't know where else to post it.

You can ask your questions on the [official Wiremod Discord server](https://discord.gg/H8UKY3Y).
