### ISSUE TITLE
A bug with wire clutch on Gmod Chromium x64 branch

### ISSUE THREAD

**Issue by dvdvideo1234** [wiremod/wire#2123]
Wiremod version is this ( Git head 787e66321871ee28e0f473f10fef80197b5211fd )

I am leaving this here. Maybe I will debug it later
```
[wiremod_git] addons/wiremod_git/lua/entities/gmod_wire_clutch.lua:149: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. unknown - addons/wiremod_git/lua/entities/gmod_wire_clutch.lua:149
    3. CleanUpMap - [C]:-1
     4. unknown - gamemodes/sandbox/gamemode/persistence.lua:57 (x2)
```

**Comment by dvdvideo1234** [comment]
Hello,

Utilized [`istable()`](https://wiki.facepunch.com/gmod/Global.istable)  in [here](https://github.com/wiremod/wire/pull/2126).

**Comment by bigdogmat** [comment]
@dvdvideo1234 
> Sure. If you say so ;)

I can't reproduce this issue, and if this is actually an issue it'll error everywhere that table is used. If you can constantly reproduce this I'd suggest debugging it instead of throwing random checks everywhere it errors.

**Comment by thegrb93** [comment]
Probably a gmod bug with cleanupMap and OnRemove

**Comment by bigdogmat** [comment]
Don't think it's `OnRemove` considering it doesn't remove the table. My guess would be other addon, or maybe Gmod is doing something in the persistence system that messes with ents.

**Comment by dvdvideo1234** [comment]
I made the server and a friend connected. He was using the workshop version of wiremod so maybe that's why.
