### ISSUE TITLE
E2 print(int, str, ...) fails silently

### ISSUE THREAD

**Issue by texruska** [wiremod/wire#2124]
`print(int, str, ...)` fails to print anything (unexpected)
`print(str, int, ...)` works

Example:
```
print(5)
print("test", 5)
print(5, "test")
```

Output:
```
5
test    5
```

Expected output:
```
5
test    5
5    test
```

**Comment by texruska** [comment]
Ah it's intended, the first int is changing where the print is going to. Should've dug a bit more into the docs

**Comment by Divran** [comment]
yeah this is a relic of the past. Previously, E2 did not support varargs, and print had only `print(N,S)`. Then, `print(...)` was added later, but an exception was made to it, in order to preserve backwards compatibility with the old `N,S` arguments.
