### ISSUE TITLE
Suggestion: E2 Callable Strings act as a Method

### ISSUE THREAD

**Issue by texruska** [wiremod/wire#2125]
The following works as expected:
```
function table:example() {
    print(This)
}
table():example()
```

It would be nice if this would work:
```
function table:example() {
    print(This)
}
table():"example"()
```

At the moment this produces the error:
```
Method operator (:) must be followed by method name
```

I can get around this by doing the following, but I don't prefer it:
```
function example(Table:table) {
    print(Table)
}
"example"(table())
```

Is the current design a limitation of how the preprocessor works?

**Comment by thegrb93** [comment]
Callable strings just don't have type support. Probably a lot of work to make it happen so don't expect anyone to prioritize it.

**Comment by Divran** [comment]
if I remember correctly, it already works, just slightly differently
`"example"(table()))`
it already checks for methods of the first parameter and prioritizes them if it finds any

**Comment by bigdogmat** [comment]
Your first example works with your last just fine.

```
function table:example() {
    print(This)
}

"example"(table())
```

**Comment by thegrb93** [comment]
Yeah, I don't see any need for that syntax.

**Comment by thegrb93** [comment]
MyTbl:MyStr() would look pretty weird

**Comment by bigdogmat** [comment]
To be honest string functions as a whole look weird. The _plan_ is for functions to become first class values, contain up values, etc and get rid of all the weirdness it currently is.
