### ISSUE TITLE
Sound Emitters Sometimes Stop Working

### ISSUE THREAD

**Issue by Peekofwar** [wiremod/wire#2128]
I don't know why it happens, but sometimes Wiremod sound emitters stop working, or don't work... My alarms in a tunnel consistently don't play sounds, and my doorbell and bad code door alarm have both just failed on me despite previously working fine. Some of my alarm speakers have stopped working. They are receiving input to start and stop. I've even tried giving it a volume and pitch input and they won't work.

I'm in a peer-to-peer session as host with one other friend connected.

**Comment by Peekofwar** [comment]
Today, after loading my map save, some of the sound emitters have started working again such as the doorbell with no modifications or fixes made... One of my gate alarms (an alarm that warns you that the gate is about to move) has failed though...

**Comment by thegrb93** [comment]
Sounds more like a problem with your gmod or conflicting addons. I don't think I've ever experienced this.

**Comment by Peekofwar** [comment]
> Sounds more like a problem with your gmod or conflicting addons. I don't think I've ever experienced this.

I could probably send you the save...

**Comment by thegrb93** [comment]
zip it and drag to the chat window to upload it here.

**Comment by Peekofwar** [comment]
Or I could uploaded it as an unlisted workshop item https://steamcommunity.com/sharedfiles/filedetails/?id=2369274005

**Comment by Peekofwar** [comment]
Is it just some sort of limitation? I'm getting a similar issue with lights now, where some lights aren't illuminating the world.

**Comment by thegrb93** [comment]
Where's the base in the save? I don't know that map well.

**Comment by Ek-Videogames** [comment]
There is known engine limitations issues with too many sound-buffer or continuous looping sounds no longer being audible if you go far away and then come back. However I do not know if this is related to that at all.

**Comment by Peekofwar** [comment]
> Where's the base in the save? I don't know that map well.

Door Six.. I believe there should be a "locked" door in the spawn covering this door.

**Comment by Peekofwar** [comment]
> There is known engine limitations issues with too many sound-buffer or continuous looping sounds no longer being audible if you go far away and then come back. However I do not know if this is related to that at all.
> 
> Edit: ( User error is always possible too, in some cases it may be more beneficial to use Input A rather than SoundStart )

I did replace most of the connections to input A after figuring out what that input was for, but it didn't fix the problem.

**Comment by Alidonis** [comment]
i got the same issue. to reproduce , i either had let the game in background while the Sound emitter was playing or it randomly stop working after turning it off
