### ISSUE TITLE
Game crashes when code is invalid 

### ISSUE THREAD

**Issue by TRY0NIGHT** [wiremod/wire#2135]
Just starting a few days ago, Whenever I tried to use the expression 2 editor and get some code wrong, it won't point out any problems with the code and instead it would just say that there is an internal error, and if I try to exit the editor with any code issues the game would just crash. I have no idea what is going on and I would love some help.

**Comment by TomyLobo** [comment]
See if you can reproduce it with all other addons deactivated (advupe/advdupe2/wire-extras are fine)
