### ISSUE TITLE
Prevweapon input trigger to cam FOV no longer working(?)

### ISSUE THREAD

**Issue by Flappy229** [wiremod/wire#2143]
Hello.

I believe a recent issue saw the change to the wiremod E2 controller or pod controller not receive an input.
The issue goes something as the following:

I have a (terrible given but foolproof) code that has stopped working and i assume due to a wiremod update as it worked for the past few years. The code is suppose to toggle zoom in by scrolling up (Prevweapon on Pod Controller, going to a E2 with the @trigger PrevWeapon and further down if(~PrevWeapon&PrevWeapon){*toggle zoom code*}) this fraction of the code is used on almost all my dupes.

I have checked with a firend and he has verified that this isnt on my client side and he has difficulty having the zoom respond on scrolling up aswell.
I am very tired right now and wish to sleep so i cant provide any further details or debug for myself. All i know is the code was (in my opinion) written correctly so it shouldnt be unresponsive and i think its either a problem from pod or cam controllers and not actually the E2

the Code; a ACF tank aimming and cam control E2 is provided. Once again I am tired and so sorry i cant be of more help to figuring out whats and where its going on.

[!!!gg5_as_holoturret_(cdumod).txt](https://github.com/wiremod/wire/files/5943552/gg5_as_holoturret_.cdumod.txt)

I dont know if this is the best place to submit this issue in hindsight but thanks for any responses i get
-CDU

**Comment by thegrb93** [comment]
I put print("hi") in the `if(~PrevWeapon&PrevWeapon){toggle zoom code})` and it worked fine.

**Comment by Flappy229** [comment]
Hi. 
Sorry for leaving this open and not being able to respond for so long. I was preoccupied in other subjects :(..
I had a better look at it and made a debug code (shown below)
The result was that the Prev and Next weapon where double-triggering meaning a toggle would turn on and off in a single tick (im guessing). I was told by others that this is due to 'windows 10 settings' guessing it works fine for people for win10? since this is out of my control im happy to close off on this issue but wondering if theres chance it could be changed to suit all windows?

Once again thank you for your help!

@name Debug
@inputs PrevWeapon
@outputs Zoom
@trigger PrevWeapon


    if ( ~PrevWeapon&PrevWeapon ) {Zoom=!Zoom,print(Zoom)}

**Comment by thegrb93** [comment]
Yea, that's your mouse wheel sensitivity.

**Comment by Flappy229** [comment]
Thank you for fiquring out the problem, One last question; is there a way or console command to adjust the scroll sensitivity back to the the old setting? If not that is all. 
-CDU

**Comment by thegrb93** [comment]
Its a windows setting i think or whatever mouse driver you use.

**Comment by Flappy229** [comment]
Doesnt do anything. Assuming wiremod has its own settings for mouse which cant be altered. Should i put in an issue to asking to fix it for older windows or just leave it considering its not overly important.

**Comment by thegrb93** [comment]
There's no gmod or wire setting imo, its your own OS/mouse causing the issue.
