### ISSUE TITLE
egpOrder not working

### ISSUE THREAD

**Issue by nirahiel** [wiremod/wire#2145]
When I set a new order with egpOrder, it's not set, the old value is kept instead.

**Comment by Divran** [comment]
The implementation of egporder is very shit. To use it, you need to know which order all of your objects were created in. as in, the 2nd number you give it isn't an object ID.
Try using egpOrderAbove/Below instead. Those are much easier to use because you give it two object IDs.

**Comment by nirahiel** [comment]
They didn't work either xD

**Comment by Divran** [comment]
post a small sample code snippet of them not working. also if you want faster help, go to the discord instead https://discord.gg/H8UKY3Y

**Comment by nirahiel** [comment]
Well it used to not work with my code (on a server) but now it works again .. so until I can reproduce it, i'll mark this as solved.
