### ISSUE TITLE
Vector Compose gate has troubles when wired to wire Radio(one-way)

### ISSUE THREAD

**Issue by JosephiGSZ** [wiremod/wire#2148]
I found that when you connect a Vector Compose gate to a Wire Radio that the gate ignores the Y&Z values when creating the vector. This doesn't seem to be a problem for other wire gates that take multiple values, and the Radio.

It only seems to be from an interaction with the radio. 
I've tested with plugs, and selectors thinking that it was the Compose gate itself not playing nicely with multiple possible values, but they worked just fine.

How to reproduce (on 64bit):
1. Take a GPS, or 3 random non-zero values, and send the values through a radio
2. Repeat on at least one other radio on a separate channel
3. Set up a receiving radio that has a compose gate connected to all 3 values, and the ability to change channels to the radios set before it
4. Change the channel to one with a non-(0,0,0) vector
5. Change the channel to another one with another non-(0,0,0) vector
6. Observe the two different vectors either with debugger, or a decompose gate connected to screens.

Keep in mind I'm on linux, and am using the 64 bit version of Gmod; this may be a non-issue if the focus of Wiremod is only on 32 bit Gmod, or 64 bit Windows.

Thanks in advance
(Edited for grammar, and detail)

**Comment by thegrb93** [comment]
Does indeed sound like a radio bug.
