### ISSUE TITLE
E2 Editor Doesn't Error When Saving E2 File With a Invalid Character (such as "/") in the Filename

### ISSUE THREAD

**Issue by bellum128** [wiremod/wire#2153]
The Expression 2 editor appears to allow saving a script even if it includes an invalid character, such as a forward slash ("/"). This results in the editor saying it successfully saved the file, however it is not actually saving. This is very dangerous from a data loss standpoint, as one may think they have saved a file, when they have not.

It should either give an error, or automatically replace invalid characters with something on save.

![e2_file_issue](https://user-images.githubusercontent.com/2830605/113484334-c446f080-9475-11eb-9159-5ed8049adb76.png)

**Comment by TheMerkyShadow** [comment]
I know this is issue is closed. But the reason why this happening is because windows doesn't allow those symbols as filenames. Technically someone could put an error warning if you wanted

**Comment by thegrb93** [comment]
Windows does allow / in order to save it to a folder, but giving a folder that doesn't exist was what was causing it not to save.

**Comment by TheMerkyShadow** [comment]
> Windows does allow / in order to save it to a folder, but giving a folder that doesn't exist was what was causing

> Windows does allow / in order to save it to a folder, but giving a folder that doesn't exist was what was causing it not to save.

You are mistaken. You cannot name files with a illegal character such as a /.

Read further here. https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

**Comment by thegrb93** [comment]
`file.Write("myFolder/myFile.txt","Hello")` try it yourself

**Comment by TheMerkyShadow** [comment]
> `file.Write("myFolder/myFile.txt","Hello")` try it yourself. myFolder has to exist first though.

Thats allowed because the / represents a directory ... thats not the name of the file. 

Try this. Go into a folder and try to make or rename any file with the / symbol you cant.

**Comment by thegrb93** [comment]
It can, but not if the folder doesn't exist.

**Comment by TheMerkyShadow** [comment]
> It can, but not if the folder doesn't exist.

Prove it....show me any file in windows with a / in the name

**Comment by thegrb93** [comment]
It's specifying a path, not a filename. That's why / is allowed.

**Comment by TheMerkyShadow** [comment]
Yes? Thats obvious. I dont understand your point.

**Comment by thegrb93** [comment]
You seem to think that the / is an invalid input. It's not.

**Comment by TheMerkyShadow** [comment]
> You seem to think that the / is an invalid input. It's not.

Yes. It is invalid for FILES. Thats why wiremod cannot save them.

**Comment by thegrb93** [comment]
Try reading over this thread a few times and maybe it'll click for you. I'm done discussing.

**Comment by TheMerkyShadow** [comment]
Theres nothing to discuss. E2 cant name files with those illegal characters cause Windows does not allow them in the operating system. Sorry for trying to help you brain dead idiot

**Comment by thegrb93** [comment]
It can, try it. Create a folder 'myFolder' in your expression2 folder, then save a file as 'myFolder/myfile.txt" and it'll work. And I saw what you said and the irony is incredible

**Comment by TheMerkyShadow** [comment]
> It can, try it. Create a folder 'myFolder' in your expression2 folder, then save a file as 'myFolder/myfile.txt" and it'll work. And I saw what you said and the irony is incredible

The / represents a directory. The filename is still "myfile.txt" Thats what your not understanding.

**Comment by thegrb93** [comment]
Please tell me a case that will fail to write then.

**Comment by TheMerkyShadow** [comment]
Go anywhere within windows try to make or rename a file with a / in the name. You cant.

**Comment by thegrb93** [comment]
We're talking about e2 here.

**Comment by TheMerkyShadow** [comment]
Were talking about windows here because E2 saves the file into windows....

**Comment by thegrb93** [comment]
Yet you've failed to give a case where a '/' will make E2 fail to save.

**Comment by TheMerkyShadow** [comment]
You demonstrated it yourself when you did in your screenshot.

@name Test/Chip

**Comment by thegrb93** [comment]
That's not the file name

**Comment by thegrb93** [comment]
When you save things, the '/' gets interpreted as a folder. It's not part of the file name. Please open up your thick brain a bit and try to understand before going off and calling ppl idiots.

**Comment by TheMerkyShadow** [comment]
> When you save things, the '/' gets interpreted as a folder. It's not part of the file name. Please open up your thick brain a bit and try to understand before going off and calling ppl idiots.

Thats because the problem is happening behind the scenes in LUA. You cant see what its doing but thats whats happening in the back end

**Comment by thegrb93** [comment]
Windows does it, not lua. But now at least you get an error if the folder doesn't exist so there's no problem now.

**Comment by TheMerkyShadow** [comment]
> Windows does it, not lua. But now at least you get an error if the folder doesn't exist so there's no problem now.

Lua is trying to do it. Windows is not allowing it

**Comment by thegrb93** [comment]
Because the folder doesn't exist.

**Comment by TheMerkyShadow** [comment]
@name determines the actual filename. Thats why it doesn't work. End of story.

**Comment by nicothegoat** [comment]
A path containing forward slashes is a valid input for the `@name` directive. Whether the resulting file name is the same as the specified path does not matter - it's still a valid input.

**Comment by TheMerkyShadow** [comment]
> A path containing forward slashes is a valid input for the `@name` directive. Whether the resulting file name is the same as the specified path does not matter - it's still a valid input.

It may be valid for E2. But it wont save cause windows wont allow it.

**Comment by thegrb93** [comment]
It will if a folder with the name before the '/' exists 🤣

**Comment by TheMerkyShadow** [comment]
> It will if a folder with the name before the '/' exists 🤣

Your such as idiot. Thats because its not the filename.

**Comment by nicothegoat** [comment]
I would like to reiterate what grb said above - `file.Write` takes a file *path*, not a file *name* - `file.Write('dir/file.txt', ' ')` will attempt to write to a file named `file.txt` in the directory `dir`, and not a file named `dir/file.txt`.

**Comment by thegrb93** [comment]
He understands that, but there's some kind of gap between his understanding of path and filename. He doesn't realize that there's no distinction between path and filename.

**Comment by thegrb93** [comment]
Or maybe you just closed the gap. Anywho, please hammer your brain a few times for me when you do figure it out.

**Comment by name** [comment]
Hi guys I was tagged due to the @name reference, looking through the thread I'd have to agree with GRB here but I understand what you're trying to say.

Well have a good day all!

**Comment by Divran** [comment]
> @name determines the actual filename. Thats why it doesn't work. End of story.

No it doesn't. When you press save you get a pop-up window where you enter the file name. This may be auto filled with the value from the name directive but you can always change it independently of the directive.
