### ISSUE TITLE
Buttons while in seats has a funky issue

### ISSUE THREAD

**Issue by TRY0NIGHT** [wiremod/wire#2154]
There is a problem where whenever we use pod controllers for allowing to be able to push buttons while in seats, if the seat is tilted in a pitched or rolled direction, It will offset the hitbox of where you would need to hit to activate the button. For example if you had a seat facing upward 45 degrees, it would offset the hitbox for the button by 45 degrees and you would have to hover your mouse around until you were able to find it.

**Comment by thegrb93** [comment]
Probably related to shooting while sitting in a chair, the shots are tilted when the chair is tilted. It is a garrysmod bug. Not sure its fixable.

**Comment by thegrb93** [comment]
This is the trace that'd need to be updated. https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_pod.lua#L440

**Comment by thegrb93** [comment]
This'll be fixed in the next gmod update.
