### ISSUE TITLE
Interact with entities?

### ISSUE THREAD

**Issue by TRY0NIGHT** [wiremod/wire#2159]
Is there any way one can give an output for when a player interacts with a specific entity? The closest thing I found to this was `runOnUse()` which gives an output for when a player interacts with the actual expression 2 chip. It would be cool if you were able to give an output like if the player was interacting with the entity and what player was interacting with the entity.

**Comment by shadowscion** [comment]
You should be able to do this well enough from within e2 itself

**Comment by thegrb93** [comment]
> You should be able to do this adequately enough from within e2 itself

How?

**Comment by TRY0NIGHT** [comment]
> > You should be able to do this adequately enough from within e2 itself
> 
> How?

That is what I came here for

**Comment by shadowscion** [comment]
> 
> 
> > You should be able to do this adequately enough from within e2 itself
> 
> How?

**His question:** 
> give an output for when a player interacts with a specific entity?

'Specific entity' implies the e2 is already aware of it... there's nothing difficult about detecting nearby players and what they are doing to it.

**Comment by thegrb93** [comment]
You still didn't give an answer. I don't see any issue with extending the runOnUse to any entity.

**Comment by shadowscion** [comment]
Oh... I thought it did work that way

Ignore me

**Comment by thegrb93** [comment]
lol np

**Comment by m-doescode** [comment]
> if the player was interacting with the entity and what player was interacting with the entity.
Do you mean like, for example, when a player clicks a button, get the player who clicked it? In the Wired Button tool, you can select "Output Entity". The button will now have a second output called "Entity" (Not to be confused with "Create Entity)

**Comment by 4naki** [comment]
foreach(I,E:entity=players()){
if((E:aimEntity()==Prop)&(E:pos():distance(Prop:pos())<50)&changed(E:keyUse())&E:keyUse()){
print("hey "+E:name()+" pressed E on the prop!")
}
}
that should work
