### ISSUE TITLE
E2 Name Bug

### ISSUE THREAD

**Issue by KyleNaCl** [wiremod/wire#2160]
passing `toChar(0)` into `setName()` causes the e2's hoverUI to break

https://i.gyazo.com/a2d45f9c159770ae3ee9423499eb21b0.png

**Comment by Fasteroid** [comment]
This has actually already been fixed as of  #2095

**Comment by thegrb93** [comment]
No, the UI collapses still. It's because the w/h it likely returning 0.

**Comment by Fasteroid** [comment]
So far I have been unable to get toChar(0) to successfully pass into setName since #2095.  I know what KyleNaCl is talking about, I used it in an old glitch e2, but it doesn't give me the cursed nameplate anymore

**Comment by KyleNaCl** [comment]
I was using the workshop version when I initially reported this, I have since changed over the workshop version on my server and it still works.

**Comment by Fasteroid** [comment]
That’s odd, I’ll try again tomorrow
________________________________
