### ISSUE TITLE
Aiming with ACF guns or other entities is broken 

### ISSUE THREAD

**Issue by TheLight91** [wiremod/wire#2168]
After I updated wire, all acf guns now aim wrong, most of the guns now aim super low compared to where I'm trying to aim.

On further inspection, it affects all entities, not just acf guns.

**Comment by M-dot-Core** [comment]
https://www.youtube.com/watch?v=KpIH-F5k9as&t=38s Affects all of my vehicles as well. This example relies on comparing my camera angles to that of a parented hologram.

**Comment by Divran** [comment]
It doesn't seem to be a coincidence that this issue here was recently updated: 
https://github.com/Facepunch/garrysmod-issues/issues/1150
it may be related

**Comment by TheLight91** [comment]
I noticed that the problem changed with the angle of the vehicle, so could be it, but it's a very recent change.

**Comment by robotboy655** [comment]
If I had to guess it is likely either client/server mismatch (i.e. client is on a beta branch and server is not, or server is simply not up to date) or something that mods you use do to compensate for the bug that was fixed.

**Comment by TheLight91** [comment]
The problem appears on singleplayer, so could it be wiremod's fault?

**Comment by robotboy655** [comment]
I cannot say anything else without some actual info. I don't even know what ACF has to do with wiremod at all.

**Comment by thegrb93** [comment]
@robotboy655 's fixes are working fine. I just tested in singleplayer. We need to see if any hacks are put in the cam controller that were mitigating the engine issues that were fixed.

**Comment by thegrb93** [comment]
Here's a test in starfall I used

```lua
--@shared

local h = holograms.create(Vector(),Angle(),"models/starfall/holograms/sphere.mdl")
if SERVER then
    h:setColor(Color(200, 100, 50))
else
    h:setColor(Color(50, 100, 200))
end

hook.add("think","",function()
    h:setPos(owner():getEyeTrace().HitPos)
end)
```

**Comment by Divran** [comment]
I'm about to do some tests as well

**Comment by thegrb93** [comment]
Yeah I'll need to try the actual cam controller later.

**Comment by thegrb93** [comment]
@TheLight91 what version of gmod are you on?

**Comment by Divran** [comment]
I can't reproduce this.

With a cam controller hooked up and enabled, the outputs from the cam controller always align perfectly to the crosshairs as expected. When the cam controller is set to *CL movement on* and *CL movement local to parent off*, `ply:EyeAngles()` doesn't align to the crosshairs, but that's also as expected.

With cam controller disabled (or just not hooked up at all), then `ply:EyeAngles()` aligns perfectly with the crosshairs, as expected.

Tested in both the "none" branch on gmod, and on the x86-64 branch in 64 bit mode. 

@TheLight91 @M-dot-Core 
Which version of gmod are you using? 
I assume you are using E2? Both of you need to create a new E2 with the smallest possible code that reproduces the error. See my example code below. My example code has three separate tests in one. Ideally you'd simply take my code, erase hologram 2+3, then replace the angle calculations for hologram 1 with your code in a way which reproduces the problem.

This is the code I used to test
```
@inputs CamAng:angle Parent:entity
@persist Seat:entity
if (first()) {
    holoCreate(1)
    holoScale(1,vec(2)/12)
    holoColor(1,vec(255,0,0),200)
    holoAng(1,ang())
    holoCreate(2)
    holoScale(2,vec(2)/12)
    holoColor(2,vec(0,255,0),200)
    holoAng(2,ang(45,0,0))
    holoCreate(3)
    holoScale(3,vec(2)/12)
    holoColor(3,vec(0,0,255),200)
    holoAng(3,ang(0,45,0))

    Seat = entity():isWeldedTo()
}

interval(10)

# RED HOLOGRAM = just regular normal Ply:EyeAngles()
local Pos = rangerOffset(60000,Seat:driver():shootPos(),Seat:driver():eye()):position()
holoPos(1,Pos)

# BLUE HOLOGRAM = input from wiremod camera controller
local Pos2 = rangerOffset(60000,Seat:driver():shootPos(),CamAng:forward()):position()
holoPos(2,Pos2)

# GREEN HOLOGRAM = code that works the same way as the camera controller (when set to CL Movement=on, CL Movement Local To Parent=off)
# when set to CL Movement=on, CL Movement Local To Parent=off
#local CamAng2 = Seat:toLocal(Seat:driver():eyeAngles())
# or, when set to CL Movement=on, CL Movement Local To Parent=on (use this mode when testing with cam controller disabled)
local CamAng2 = Parent:toWorld(Seat:toLocal(Seat:driver():eyeAngles()))
#this is equivalent to just Ply:EyeAngles() if Parent is the same as Seat

local Pos3 = rangerOffset(Seat:driver():shootPos(),Seat:driver():shootPos()+CamAng2:forward()*999999999):position()
holoPos(3,Pos3)
```

**Comment by TheLight91** [comment]
> @TheLight91 what version of gmod are you on?

On the latest vesion of 64bit.

**Comment by TheLight91** [comment]
@thegrb93 on the latest version of 64bit

**Comment by TheLight91** [comment]
[15t WSP 75.txt](https://github.com/wiremod/wire/files/6423437/15t.WSP.75.txt)

This is an example of a tank that shows the problem clearly. 

This is the aiming chip it uses:

@name Aiming E2
@inputs Gun:entity [Active]:number Aimpos:vector Base:entity Cam:wirelink A Ctrl
@persist Rotation CamOffset:vector Inertia:angle Elevation Depression Yaw RotateSpeed [Angle GunAng]:angle 
@outputs CamDist FOV GunAng:angle Lock

interval(50)
if (first()|dupefinished()) {
    Elevation = 45 #Gun Elevation 
    Depression = 15 #Gun Depression
    Yaw = 20 #Turret ability to rotate around

    Rotation = 100 #Turret rotation speed, be reasonable please  

    #Unless you know what your doing dont edit below here



    
    Elevation*=-1
    Inertia = shiftL(ang(Gun:inertia()))
    
    CamOffset=vec(76,14,55)
    CamDist=0
      
    RotateSpeed = clamp(11.5 - (Gun:mass()/Rotation),0,10)
} 
   
if( Active ) {
    
    if(A){
               
        FOV=10
        
    }else{
            
        FOV=90
    }


    
    Cam["FOV",number]=FOV
    Cam["Activated",number]=1
    Cam["Distance",number]=CamDist
    Cam["Parent",entity]=Base
      
    GunAng =(Aimpos - Gun:pos()):toAngle()

if( Active ) {
    
    if (Ctrl == 1)

{   
   Lock = 1
}

    else

{   
    Gun:applyAngForce((Gun:toLocal(entity():toWorld(clamp(entity():toLocal(Gun:toWorld(clamp(Gun:toLocal(GunAng),ang(-RotateSpeed),ang(RotateSpeed)))),ang(Elevation,-Yaw,-1),ang(Depression,Yaw,1)))) * 400 - Gun:angVel() * 30) * Inertia)
    Lock = 0 
}

}

   Cam["Position",vector]=CamOffset
}

else {Lock = 1}


if (changed(Gun:acfReady())& !Gun:acfReady()) {Gun:soundPlay(1,0,"acf_extra/tankfx/gnomefather/reload3.wav")}

if (changed(Gun:acfReady()) & Gun:acfReady()) {Gun:soundPlay(2,0,"acf_extra/tankfx/gnomefather/rack.wav")}  

if(Gun:acfReady()) {soundStop(1)}

if(!Gun:acfReady()) {soundStop(2)}

**Comment by Divran** [comment]
In the above E2, what is Aimpos wired to?

**Comment by TheLight91** [comment]
To the cam controller's HitPos. To test that you don't need actual acf parts, you can use any prop for "Gun".

**Comment by Divran** [comment]
ok gmod just updated for me, and now it's fucked

```
] lua_run print(Entity(93):WorldToLocalAngles(Entity(1):EyeAngles()))
> print(Entity(93):WorldToLocalAngles(Entity(1):EyeAngles()))...
-0.012 90.000 -0.011
] lua_run_cl print(Entity(93):WorldToLocalAngles(Entity(1):EyeAngles()))
0.012 -135.017 -0.004
] lua_run print(Entity(1):EyeAngles())
> print(Entity(1):EyeAngles())...
-0.000 -44.986 -0.000
] lua_run_cl print(Entity(1):EyeAngles())
0.000 90.000 -0.000
```

**Comment by TheLight91** [comment]
So it's a gmod issue? BTW this is the hud for the aiming, it's EGP and holo based

@name Aiming Hud E2
@inputs  EGP:wirelink Gun:entity Lock Active      
@persist Rangefinder:ranger LocalVel
@outputs User:entity
@persist Active   

interval(50)
if(first()||dupefinished())

{     
holoCreate(1)
holoModel(1,"models/sprops/geometry/sphere_3.mdl")
holoMaterial(1,"Models/effects/vol_light001")
holoColor(1,vec4(255,255,255,0))
}
    
if (Active)
{   
if (~Active)
{       
Gun:soundPlay(1,0,"acf_extra/tankfx/turret5.wav")
soundPitch(1,0) 
         
EGP:egp3DTracker(2,vec(0,0,0))
EGP:egpParent(2,holoEntity(1)) 
         
EGP:egpCircleOutline(3,vec2(0,0),vec2(10,10))
EGP:egpParent(3,2)
         
EGP:egpCircle(5,vec2(960,540),vec2(3,3))
     
rangerFilter(Gun)
rangerFilter(entity():getConstraints())
rangerPersist(1)       
}      
EGP:egpColor(5,vec(255*Lock,255*!Lock,0))
EGP:egpColor(3,vec(255*!Gun:acfReady(),255*Gun:acfReady(),0))
holoPos(1,rangerOffset(9999999999,Gun:pos()+Gun:forward()*100,Gun:forward()):position())      
LocalVel=entity():toLocal(Gun:angles()):yaw()+ entity():toLocal(Gun:angles()):pitch()
soundPitch(1,(abs($LocalVel)>0.1)*45)
soundVolume(1,1)

**Comment by Divran** [comment]
@TheLight91 please use code tags when posting code, <https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks>

but yeah it seems to be a gmod issue

**Comment by TheLight91** [comment]
Ah thanks for the tip. 

So the problem came from the latest gmod changes in how aiming works from vehicles? That sucks since it's probably gonna take a long time to get fixed...

**Comment by robotboy655** [comment]
@Divran Are you sure you are testing the same client/server? What vehicle are you using specifically?

**Comment by Divran** [comment]
@robotboy655 
would you like to join my local server right now and test?

what do you mean "same client/server"
I'm using a regular default "airboat_seat" style chair
![image](https://user-images.githubusercontent.com/1485728/117063163-bc07fc80-ad24-11eb-90c1-b486b3097f7f.png)

**Comment by thegrb93** [comment]
I don't think Gmod has updated for me yet, will check again later.

**Comment by TheLight91** [comment]
Just tested since I was curious. The problem doesn't happen in "vanilla" gmod, as in the gmod out of all betas. The problem still appears on the x86-64 build as of now.

**Comment by thegrb93** [comment]
The GetEyeTrace HitPos is working fine, but the angles from getEyeAngles() are definitely mismatched between server and client. The yaw on server and client are like `serverYaw = 180 - clientYaw`. Either one of the transformations is backwards or there's a bad rotation somewhere.

![image](https://user-images.githubusercontent.com/6713261/117116968-fbead600-ad5c-11eb-8a28-886110f578cd.png)

**Comment by thegrb93** [comment]
@robotboy655

**Comment by thegrb93** [comment]
Hmm actually I just tested it in the non-dev branch and the behavior is also weird, however it's `serverYaw = 90 - clientYaw` instead

![image](https://user-images.githubusercontent.com/6713261/117119084-921ffb80-ad5f-11eb-8524-9850ed9989f5.png)

**Comment by thegrb93** [comment]
Nevermind, I'm dumb. The serverside and clientside are different for both the beta and non-beta. I don't see any clear difference between the beta and non-beta gmod. I'll have to test more tomorrow.

**Comment by robotboy655** [comment]
Apparently `EyeAngles()` has a hack for localplayer to return the local eye angles. Don't know why it was there, but I removed it and added `Player.LocalEyeAngles()` for that instead. So it should now all work. Kinda weird that you'd use `EyeAngles` for this, `GetAimVector` is normally used, but whatever.

It's currently on Dev, please test and let me know if anything else breaks due to this change.

**Comment by Divran** [comment]
> Kinda weird that you'd use `EyeAngles` for this, `GetAimVector` is normally used, but whatever.

Of course I can always change this if it's an improvement. Not sure what the difference is between these two, though.

Plus, unless I'm mistaken, `GetAimVector` doesn't include roll information, so if we were to update the cam controller to use that instead then we'd also need to retrieve the roll angle from somewhere else. Probably from the roll angle of the selected parent entity.

Will test it as soon as I have time.

**Comment by TheLight91** [comment]
Just tested it, still broken. Nothing changed.

https://user-images.githubusercontent.com/40478437/117135975-02eb0600-ada8-11eb-89ac-1a7f50188c7c.mp4

**Comment by robotboy655** [comment]
The behavior of the camera has not changed. The view in second video will behave identically on the NONE beta.

I can't really debug your ACF gun without having it myself. In my tests EyeAngles() and GetAimVector() both match on client/server now as long as the client and server versions are identical (or you test in singleplayer). Not sure what else I can do.

**Comment by TheLight91** [comment]
It's not a problem about acf, it shows the same problem with any entity aimed with an e2 and a cam controller.

**Comment by TheLight91** [comment]
'''
@name Aiming E2
@inputs Gun:entity [Active]:number Aimpos:vector Base:entity Cam:wirelink A Ctrl
@persist Rotation CamOffset:vector Inertia:angle Elevation Depression Yaw RotateSpeed [Angle GunAng]:angle 
@outputs CamDist FOV GunAng:angle Lock

interval(50)
if (first()|dupefinished()) {
    Elevation = 45 #Gun Elevation 
    Depression = 15 #Gun Depression
    Yaw = 20 #Turret ability to rotate around

    Rotation = 100 #Turret rotation speed, be reasonable please  

    #Unless you know what your doing dont edit below here



    
    Elevation*=-1
    Inertia = shiftL(ang(Gun:inertia()))
    
    CamOffset=vec(76,14,55)
    CamDist=0
      
    RotateSpeed = clamp(11.5 - (Gun:mass()/Rotation),0,10)
} 
   
if( Active ) {
    
    if(A){
               
        FOV=10
        
    }else{
            
        FOV=90
    }


    
    Cam["FOV",number]=FOV
    Cam["Activated",number]=1
    Cam["Distance",number]=CamDist
    Cam["Parent",entity]=Base
      
    GunAng =(Aimpos - Gun:pos()):toAngle()

if( Active ) {
    
    if (Ctrl == 1)

{   
   Lock = 1
}

    else

{   
    Gun:applyAngForce((Gun:toLocal(entity():toWorld(clamp(entity():toLocal(Gun:toWorld(clamp(Gun:toLocal(GunAng),ang(-RotateSpeed),ang(RotateSpeed)))),ang(Elevation,-Yaw,-1),ang(Depression,Yaw,1)))) * 400 - Gun:angVel() * 30) * Inertia)
    Lock = 0 
}

}

   Cam["Position",vector]=CamOffset
}

else {Lock = 1}


if (changed(Gun:acfReady())& !Gun:acfReady()) {Gun:soundPlay(1,0,"acf_extra/tankfx/gnomefather/reload3.wav")}

if (changed(Gun:acfReady()) & Gun:acfReady()) {Gun:soundPlay(2,0,"acf_extra/tankfx/gnomefather/rack.wav")}  

if(Gun:acfReady()) {soundStop(1)}

if(!Gun:acfReady()) {soundStop(2)}
'''

This is the code used to aim it, "Gun" can be any prop. "Aimpos" is wired to the cam controller's HitPos.

**Comment by TheLight91** [comment]
Going back to the "None" beta, it shows the proper behaviour.

https://user-images.githubusercontent.com/40478437/117142873-7f81e280-adb0-11eb-85ff-c82bf69e149a.mp4

**Comment by robotboy655** [comment]
I don't know how to setup your script properly, but just placing a hologram to hitpos (connected to a POD controller) places it directly on the crosshair, which is the entire point of the update.

```
@name Aiming E2
@inputs Gun:entity [Active]:number Aimpos:vector Base:entity Cam:wirelink
@persist Rotation CamOffset:vector Inertia:angle Elevation Depression Yaw RotateSpeed [Angle GunAng]:angle 
@outputs CamDist FOV GunAng:angle

interval(50)
if (first()|dupefinished()) {
    Elevation = 45 #Gun Elevation 
    Depression = 15 #Gun Depression
    Yaw = 20 #Turret ability to rotate around

    Rotation = 100 #Turret rotation speed, be reasonable please  

    #Unless you know what your doing dont edit below here

    Elevation*=-1
    Inertia = shiftL(ang(Gun:inertia()))
    
    CamOffset=vec(76,14,55)
    CamDist=0
      
    RotateSpeed = clamp(11.5 - (Gun:mass()/Rotation),0,10)
    holoCreate(0)
    holoModel(0, "box")
} 
   
if( Active ) {
    Cam["FOV",number]=FOV
    Cam["Activated",number]=1
    Cam["Distance",number]=CamDist
    Cam["Parent",entity]=Base
      
    GunAng =(Aimpos - Gun:pos()):toAngle()

    holoPos(0, Aimpos)

    if( Active ) {
     
           Gun:applyAngForce((Gun:toLocal(entity():toWorld(clamp(entity():toLocal(Gun:toWorld(clamp(Gun:toLocal(GunAng),ang(-RotateSpeed),ang(RotateSpeed)))),ang(Elevation,-Yaw,-1),ang(Depression,Yaw,1)))) * 400 - Gun:angVel() * 30) * Inertia)
    
    
    }

   Cam["Position",vector]=CamOffset
}
```
(Also can I just say how bad the E2 autocomplete hotkeys are)

**Comment by TheLight91** [comment]
I am going to build a small test rig with vanilla props so you can test that.

**Comment by Divran** [comment]
Guys you don't need to build physical test rigs with moving props. I've already provided test code with holograms, three times.

**Comment by Divran** [comment]
I've tested the recent changes and can confirm the function now returns the same value both client and serverside. However it's still broken, so this means there's now something wrong with the cam controller code, most likely. Currently looking for the problem.

**Comment by Divran** [comment]
I've got it fixed.

Just adding some version checks so that it'll work on both the current stable version and also on the latest dev version. This means it'll still be broken on the intermediate version, ie current x64, until @robotboy655 updates that to match the dev branch.

in other words,
```
-- TODO: remove "SERVER or VERSION >= 210505" after stable branch reaches this version or later
if (SERVER or VERSION >= 210505) and IsValid( veh ) then curang = veh:WorldToLocalAngles( curang ) end
```

**Comment by TheLight91** [comment]
![Untitled](https://user-images.githubusercontent.com/40478437/117201897-795e2700-aded-11eb-9e82-25e0303475a7.png)

Not really fixed. Now it's tilted one way looking right anf tilted the opposite looking left other than having a weird jelly feeling of the cam while moving.

**Comment by TheLight91** [comment]
https://user-images.githubusercontent.com/40478437/117202543-39e40a80-adee-11eb-9223-7924d7cbd299.mp4

**Comment by Divran** [comment]
Which gmod version @TheLight91

**Comment by TheLight91** [comment]
Dev version with the up to date wire.  @Divran

**Comment by Divran** [comment]
@TheLight91 alright add me and then join the local server I've hosted so I can test your tank. I don't have acf but whatever
<https://steamcommunity.com/id/Divran/>

**Comment by Divran** [comment]
@robotboy655 did some tests and there is a pronounced wobble effect in the latest dev version of gmod. No idea what causes it, and it isn't present in the normal version of gmod (I double checked).
I'll try for a bit now to see if I can fix it but I need to go very soon.

I'd be happy to show it to you ingame, just let me know when you have time. If you can think of a way for me to fix it in the camera controller I'll implement it there.

**Comment by robotboy655** [comment]
> the only issue is that vehicle:WorldToLocalAngles(ply:EyeAngles()) is in fact not the same as ply:LocalEyeAngles()

Because the vehicle camera view is not as simple as `VehiclePos+LocalAngles` like the old `EyeAngles()` reported.

**Comment by thegrb93** [comment]
Yeah, the world transform for eye angles is vehcleMatrix*someAnimationStuff*playerEyeMatrix. The inverse transform vehicle:WorldToLocalAngles(ply:EyeAngles()) will bypass the animation stuff and be incorrect.

**Comment by Divran** [comment]
After a little discussion and several ideas, we came up with the name `eyeAnglesVehicle` in the wiremod discord. 
I'll probably be adding the function to E2 under the name `eyeAnglesVehicle` rather than `eyeAnglesLocal`. I feel it helps separate it from `E:toLocal(E:eyeAngles())`, since it has different behavior. 
The lua-ized name would be `Ply:VehicleEyeAngles()` or `Ply:EyeAnglesVehicle()`. 
Ofc, entirely up to you if you feel like that's a better name. Just let me know if you do decide update it and I'll update it in wire

**Comment by TheLight91** [comment]
Just tested the same tank on the dev version with the latest wire update. Everything seem to be working fine now, no weird camera angles, jelly cam or weird aim offset.

**Comment by thegrb93** [comment]
@Anticept workshop will need these fixes

**Comment by shadowscion** [comment]
ty for the quick fix
