### ISSUE TITLE
Issue detected by Garry's mod "problem" menu

### ISSUE THREAD

**Issue by Jonahgay** [wiremod/wire#2170]
I found this issue yesterday and i thought why not report it.
Gmod has detected a Problem in the Wiremod addon and gave the follow messages.
![issue](https://steamuserimages-a.akamaihd.net/ugc/1786218536251402991/71C7395C72AD765B0075431ED3BDECCE4E3F631C/)

**Comment by TomyLobo** [comment]
From looking at the source, I'd be surprised if you could reproduce that issue reliably.
It's probably just a race condition between client and server.
Shouldn't create any persistent problems.

However, if you can write up repro steps, that'd be great.

**Comment by Jonahgay** [comment]
i was playing on single player on gm_construct, testing around different wiremod tools like the teleporter, radio , expression 2 chip, gate chip, holograms.
i disconnected from the session then the error popped up. After, I was looking to play another gamemode.

"you should also report the error to the addon author" and report it i did.

this is the full story of what happened in this issue.

**Comment by thegrb93** [comment]
So disconnecting from singleplayer is the culprit

**Comment by Jonahgay** [comment]
I suppose its best to close the issue because there isn't much information.

I'll make sure to pull more info next time.

**Comment by thegrb93** [comment]
Its something to do with `wire_singleplayer_tool_wtfgarry`. Idk why that's needed, but that's the cause.

**Comment by thegrb93** [comment]
Any idea why disconnecting would trigger it? I'm guessing maybe a toolgun function was called which then called one of these. I haven't tried reproducing it myself though.

**Comment by Divran** [comment]
nnnnnnope

**Comment by thegrb93** [comment]
I think it happened and they only noticed it after disconnecting. Probably won't be able to reproduce.
