### ISSUE TITLE
Wire turret lag improvement

### ISSUE THREAD

**Issue by kbsmilk** [wiremod/wire#2171]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_turret.lua
Currently, wire turrets' bullet origin lags behind the turret entity's position. When triggered to fire, it appears to queue a bullet to launch in the next tick, but only after physics motion is calculated. Because of this turrets on a contraption tend to shoot the contraption when it's moving fast enough. I've made seemingly better fix than the previous one:

```
-- this is the original 2 lines
-- Get the shot angles and stuff.
--local shootOrigin = Attachment.Pos + self:GetVelocity() * engine.TickInterval()
--local shootAngles = self:GetAngles()

local shootAngles = self:GetAngles()
local selfPos = Attachment.Pos
local selfVel = self:GetVelocity()
local selfVelL = self:WorldToLocal(selfVel + selfPos) -- didn't find a native local velocity function, so copied this from e2 lua
local shootOrigin = Vector()
if selfVelL[1] > 0 then shootOrigin = selfPos + selfVel * engine.TickInterval() * 4 else shootOrigin = selfPos end
```
Also, here is a video of before and after. Before 26 seconds is the original, after is my fix.
https://www.youtube.com/watch?v=WrL-sop4bTc

some problems: selfVelL can probably be done better, and fast rotating contraptions still shoot themselves just as much as the original fix.

**Comment by TomyLobo** [comment]
I assume the entities in this contraption in your video are all parented to one entity?

**Comment by thegrb93** [comment]
I can test the firebullets delay with the EntityTakeDamage hook and see how it varies with physics.

**Comment by thegrb93** [comment]
Maybe the FireBullets hook too.

**Comment by thegrb93** [comment]
All the hooks are called at the same CurTime so I'm guessing its doing
Think -> FireBullets -> Physics -> EntityTakeDamage all on the same tick.

**Comment by thegrb93** [comment]
Or the problem is that traces during the current frame are still querying the old physics state, when the new positions are being used for the bullet positions.

**Comment by kbsmilk** [comment]
> 
> 
> I assume the entities in this contraption in your video are all parented to one entity?

Yes, the turret and numpad should be - I directly targeted the fridge prop with both tools.

**Comment by thegrb93** [comment]
Starting to think it's something wrong with `GetAttachment` going to try with the physobject position.

**Comment by thegrb93** [comment]
The note here is worrying https://wiki.facepunch.com/gmod/Entity:GetAttachment

**Comment by thegrb93** [comment]
Yeah that's what it was

**Comment by kbsmilk** [comment]
Wow, yea. I changed the bullet origin to just "self:GetPos()" and it works perfectly. Thank you

**Comment by kbsmilk** [comment]
The muzzle position would be fine to keep for the tracer and muzzle flash effects.

**Comment by thegrb93** [comment]
No, the fix here will work https://github.com/wiremod/wire/pull/2172

**Comment by Divran** [comment]
yeah saving a localized reference point is definitely the correct approach to fix that update rate issue, good catch
