### ISSUE TITLE
entity:drawHud...() functions don't work

### ISSUE THREAD

**Issue by maksimp04** [wiremod/wire#2173]
drawHud...() funcs works well, but when thing goes to entity:drawHud() funcs then nothing draw to screen

reproduced bug:
code:
![image](https://user-images.githubusercontent.com/19390500/118759745-68a0bd00-b893-11eb-82ec-2b55c2f05f7e.png)

bug showcase:
![image](https://user-images.githubusercontent.com/19390500/118759693-53c42980-b893-11eb-95bf-08d2a7b219ae.png)

*I've shown only hudDrawText, but it relative to other types of hudDraws

**Comment by CornerPin** [comment]
These aren't standard functions, you should report this to the creator of the extension.

**Comment by TomyLobo** [comment]
That extension is also not necessary. EGP can already render to the HUD without an extension.

**Comment by maksimp04** [comment]
> That extension is also not necessary. EGP can already render to the HUD without an extension.

so that's a problem. I dislike EGP for HUD things.

**Comment by TomyLobo** [comment]
well, I guess have fun with your extension that no one uses because EGP exists :)
