### ISSUE TITLE
Make gimbal angle offset not default to +90 degrees pitch

### ISSUE THREAD

**Issue by solomondog50** [wiremod/wire#2175]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_gimbal.lua#L18

**Comment by solomondog50** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_gimbal.lua#L71
(2013)

**Comment by Divran** [comment]
How does this entity handle being duped? Does it restore the angle offset? If yes, we can fix this no problem. If no, fixing this would break all dupes that use this entity without wiring the angle offset input to anything.

**Comment by thegrb93** [comment]
The target ang offset is to make the 'up' of entities be the forward shoot direction. There's a wire input for setting your own if you want.
