### ISSUE TITLE
egp broken

### ISSUE THREAD

**Issue by Ratakis** [wiremod/wire#2179]
[Wiremod] lua/entities/gmod_wire_egp_hud/cl_init.lua:79: attempt to call method 'AddHUDEGP' (a nil value)
    1. unknown - lua/entities/gmod_wire_egp_hud/cl_init.lua:79
how do I fix this I cant use egp huds bc of this and it has been going on for quite a while

**Comment by sammyt291** [comment]
- What are you doing specifically when it occurs?
- Do you use workshop or latest github version?
- Tried without other addons installed? 
you can launch without workshop addons by adding "-noworkshop" to your startup parameters to test.
or "-noaddons" to start the game without folder addons loading

**Comment by Divran** [comment]
You'll notice this is where that function is defined
<https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_egp_hud/huddraw.lua#L51>

The most likely way this error happens, is if that line I just linked does not run for some reason.

Like the user above me mentioned, try running wiremod without any other addons installed. If that fixes it, then that means one of your other addons is breaking wiremod.

### You can stop reading here if you want. For more technical info see below

If you look at the top of the file you'll see it uses an initialize hook <https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_egp_hud/huddraw.lua#L1>

It's possible for a different addon to be returning a value in this hook, thus blocking the hook from running in this file. If this is the case, that's an incorrect implementation of the hook by that other addon (Initialize should never be blocked), and you'd need to uninstall that addon to fix it (and report the issue to that addon's creator).

The following code should print all file paths for all addons that use this hook (code was written outside gmod without testing it, let me know if it doesn't work)
(Make sure the allow clientside lua convar is enabled on the server before running)
`lua_run_cl for k,v in pairs(hook.GetAll()["Initialize"]) do print(debug.getinfo(v).src) end`
you can use this to check for other addons that may be breaking it.

**Comment by Ratakis** [comment]
> Hi 👋
> 
> * What are you doing specifically when it occurs?
> * Do you use workshop or latest github version?
> * Tried without other addons installed?
>   you can launch without workshop addons by adding "-noworkshop" to your startup parameters to test.
>   or "-noaddons" to start the game without folder addons loading

Basically every time i spawn an egp v3 or anything with an egp v3 i get this lua error  [Wiremod] lua/entities/gmod_wire_egp_hud/cl_init.lua:79: attempt to call method 'AddHUDEGP' (a nil value)
    1. unknown - lua/entities/gmod_wire_egp_hud/cl_init.lua:79

**Comment by Ratakis** [comment]
> You'll notice this is where that function is defined
> https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_egp_hud/huddraw.lua#L51
> 
> The most likely way this error happens, is if that line I just linked does not run for some reason.
> 
> Like the user above me mentioned, try running wiremod without any other addons installed. If that fixes it, then that means one of your other addons is breaking wiremod.
> 
> ### You can stop reading here if you want. For more technical info see below
> If you look at the top of the file you'll see it uses an initialize hook https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_egp_hud/huddraw.lua#L1
> 
> It's possible for a different addon to be returning a value in this hook, thus blocking the hook from running in this file. If this is the case, that's an incorrect implementation of the hook by that other addon (Initialize should never be blocked), and you'd need to uninstall that addon to fix it (and report the issue to that addon's creator).
> 
> The following code should print all file paths for all addons that use this hook (code was written outside gmod without testing it, let me know if it doesn't work)
> (Make sure the allow clientside lua convar is enabled on the server before running)
> `lua_run_cl for k,v in pairs(hook.GetAll()["Initialize"]) do print(debug.getinfo(v).src) end`
> you can use this to check for other addons that may be breaking it.

the code didn't do anything

**Comment by Divran** [comment]
> the code didn't do anything

Make sure you read the whole instruction
> (Make sure the allow clientside lua convar is enabled on the server before running)
at the time I wrote that, I didn't know what the convar was. it's called `sv_allowcslua 1`. You need to have admin access to the server, run that, then run the code below. also the code was slightly incorrect. here's the fixed version
`lua_run_cl for k,v in pairs(hook.GetTable()["Initialize"]) do print(debug.getinfo(v).short_src) end`
this will give you a list of every addon that could potentially be breaking wiremod in this particular way.

It's also possible it's breaking for some other reason. This is just the most likely way I can think of with no other information.

However you don't need to do any of that if you just uninstall every other addon and try it with only wiremod installed. If that fixes the issue, then it confirms another addon was breaking it.
