### ISSUE TITLE
Holoclip broken after latest optimization

### ISSUE THREAD

**Issue by TwistedTail** [wiremod/wire#2180]
As of d8cdc76, holograms cannot be clipped via holoclip E2 functions. I narrowed down the problem to the following line:

https://github.com/wiremod/wire/blob/d8cdc76bcbc26706ab0edc4fd55ab7f4d3385b29/lua/entities/gmod_wire_expression2/core/hologram.lua#L186

Reverting this to what it used to be before d8cdc76 fixes the issue entirely.

**Comment by Divran** [comment]
Will take a look at this in a few hours

**Comment by Divran** [comment]
@TwistedTail I'm about to start fixing this issue now. If you would like to join my local server to test the fix, let me know on discord https://discord.gg/H8UKY3Y

**Comment by Divran** [comment]
Fixed
