### ISSUE TITLE
Derma error when opening the sound browser

### ISSUE THREAD

**Issue by shadow7483147** [wiremod/wire#2189]
To reproduce:
Load a singleplayer map
Open the console
Enter the command `wire_sound_browser_open`
The browser opens.
Unpause the game by exiting the console with ~
Error occurs.

```
 [ERROR] lua/vgui/dtree_node.lua:519: attempt to index field 'ChildNodes' (a nil value)
  1. PopulateChildren - lua/vgui/dtree_node.lua:519
   2. PopulateChildrenAndSelf - lua/vgui/dtree_node.lua:536
    3. unknown - lua/vgui/dtree_node.lua:432

Timer Failed! [Simple][@lua/vgui/dtree_node.lua (line 430)]
```

**Comment by thegrb93** [comment]
Might be because the spawnmenu wasn't opened yet and I think some things get created in the spawn menu.

**Comment by shadowscion** [comment]
this has been happening since the march update of gmod i think

**Comment by thegrb93** [comment]
Should be fixed after gmod update
