### ISSUE TITLE
E2 - broken core function(s) (string functions, ...)

### ISSUE THREAD

**Issue by RainbowWings** [wiremod/wire#2192]
* Actual behaviour - String functions such as finding, matching and replacing, including regex variants doesn't work at all (returning always 0 or empty string).
* Expected behaviour - String functions such as finding, matching and replacing, including regex variants should return expted results.

I believe that some of the string functions doesn't work at all. For exmaple a simple match

`print("123546789":matchFirst("(123)"))`

doesn't print anything at all as it returns empty string, while it should return "123".

I suspect this might have something to do with the most recent garrysmod update. When trying to reload the E2 extensions, there is a lua error that pops up:

`] wire_expression2_reload 
bad argument #3 to hook.Add (function expected, got nil)
stack traceback:
	entities/gmod_wire_expression2/core/globalvars.lua:10: in main chunk
	[C]: in function 'pcall'
	lua/entities/gmod_wire_expression2/core/extloader.lua:88: in function <lua/entities/gmod_wire_expression2/core/extloader.lua:81>
	[C]: in function 'pcall'
	lua/entities/gmod_wire_expression2/core/extloader.lua:101: in function 'e2_include_finalize'
	lua/entities/gmod_wire_expression2/core/extloader.lua:172: in main chunk
	[C]: in function 'include'
	lua/entities/gmod_wire_expression2/core/extloader.lua:37: in function <lua/entities/gmod_wire_expression2/core/extloader.lua:12>
	lua/includes/modules/concommand.lua:54: in function <lua/includes/modules/concommand.lua:49>
Calling destructors for all Expression 2 chips.
Reloading Expression 2 extensions.
Calling constructors for all Expression 2 chips.
Done reloading Expression 2 extensions.
`

Also another thing as a side note, is that parenting wire turrets to holograms makes the turrets work incorrectly. More specifically, the turret functional fire position and direction seems to remain at original position. The model moves along correctly, however when the turret shoots, the muzzle effect appears at the last original pos and dir before it parented, as well the shoot tracing will only hit anything as if the turret wouldn't move/rotate at all. The bullet projectiles however, actually comes form the model muzzle attachment position (which moves along with the parent) and heads towards the trace hit position, which is again starts from the turret's original position before parenting.

As a summary, there might be more functions that are broken, maybe even stuff outside of E2, but I am not aware of those.

**Comment by thegrb93** [comment]
Those issues were fixed. Try updating

**Comment by thegrb93** [comment]
@Anticept might need to update workshop
