### ISSUE TITLE
Wire turrets when parented in x64 singleplayer don't work correctly

### ISSUE THREAD

**Issue by StrawWagen** [wiremod/wire#2194]
Parented turrets don't fire in the direction they're "facing"
Video demonstration; https://youtu.be/QcYkqBQM6WE

Replicated by multi parenting a turret to a prop, then firing the turret

**Comment by thegrb93** [comment]
Yes they do, @Anticept just needs to update workshop

**Comment by StrawWagen** [comment]
ty!
