### ISSUE TITLE
e2 bug

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#2195]
UDFunction: doneSpawned() undefined at runtime!
no idea why this happens. can somone care to explain? this only happened when they decided to update wiremod.

**Comment by bigdogmat** [comment]
Nothing relating to UDFs was changed. It's possible something else changed that changed a condition you rely on for defining UDFs. We can't do anything without reproducible code

**Comment by deathking61** [comment]
soo what can i do? show you a snippet of said code?

**Comment by bigdogmat** [comment]
Yes

**Comment by shadowscion** [comment]
I don't know how to reproduce it, but this bug, or at least the error message, is not new.
