### ISSUE TITLE
E2 - regex functions are broken/inconsistent

### ISSUE THREAD

**Issue by RainbowWings** [wiremod/wire#2203]
Some Expression 2 regex functions seem to be broken and/or behave in a strange manner, namely explodeRE() and replaceRE().

- Actual behaviour: replaceRE() doesn't work in certain cases and explodeRE() doesn't work at all
- Expected behaviour: replaceRE() and explodeRE() should be always working without throwing any lua errors

* explodeRE() - Seems to be completely broken and doesn't work at all, regardless of provided input/params. It always throws lua exception: `entities/gmod_wire_expression2/core/string.lua:343: bad argument #1 to 'gsub' (string expected, got nil)`
* replaceRE() - Throws lua warning and doesn't perform requested operation, in certain combinations of input and 1. parameter. In these cases, it outputs `entities/gmod_wire_expression2/core/string.lua:356: Regex is too complex! 2 ext search length too long (500 max)` or `entities/gmod_wire_expression2/core/string.lua:356: Regex is too complex! 3 ext search length too long (150 max)`. Strangely it seems to be always either 500 or 150. Problem example: `"abcdeabcd ========= abcdeabcd abcdeabcd abcdeabcd abcdeabcd abcdeabcd abcdeabcd ====":replaceRE("[ ]*(([+%-/*]?)([=]))[ ]*","%1")`. The input string length is 84 and removing just a single character from the input string or removing a single part from the pattern, makes the issue no longer occur.

None of this was ever happening before. If some some regex complexity limitation is really going to take place, than I would suggest to not use it if possible or set the limits, much, much higher than this, because this is a bit ridiculous its going to make string processing a lot more difficult and painful. If I am not mistaken, this has been happening since the latest workshop version update.

gmod branch: chromium x86/64
wiremod version: workshop
tested in: singleplayer, multiplayer (dedicated)

**Comment by Divran** [comment]
explodeRE seems to have an incorrect variable name. It uses `pattern` here which doesn't exist. I believe it should be `delim` instead. https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/string.lua#L423

The other issues you mentioned are related to @thegrb93 's new complexity checks so I'll leave that to him to reply to.

**Comment by hounddogie** [comment]
entities/gmod_wire_expression2/core/string.lua:356: Regex is too complex! 4 ext search length too long (70 max)

Happens on my single player game and a multiplayer server, however it works on a different server. currently we ran a server bare bones and it still happens.
