### ISSUE TITLE
holos appear green despite the vec() being 255,255,255

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#2207]
so sometimes in gmod i have noticed that if there a good ammount of holos that the color isnt what the vec() is coded to be like lets say you have it like vec(+255,255,255) and there are a lot of holos some of the holos just go to green or another color...........why?

**Comment by thegrb93** [comment]
How many

**Comment by thegrb93** [comment]
I've seen it happen before with regular props so I think it's a source engine networking thing. Maybe try setting their color gradually rather than all at once.
