### ISSUE TITLE
WireLib.MakeWireEnt does not call PlayerSpawnedSENT

### ISSUE THREAD

**Issue by kerbalcadet** [wiremod/wire#2208]
Really easy fix here. While it does call playerspawnobject, there is no hook run once the entity is actually spawned, unlike nearly every other entity in GMod (crucially including a reference to said entity). Just adding hook.Run("PlayerSpawnedSENT", pl, ent) ought to do it.

**Comment by thegrb93** [comment]
If this is fixed, it'll need to decrement the 'max sents' counter as well since PlayerSpawnedSENT increments that counter.

**Comment by Divran** [comment]
I'm relatively sure that all three duplicators run PlayerSpawnedSENT themselves, so if this behavior is added to MakeWireEnt, then that function would be called twice on dupe.

**Comment by kerbalcadet** [comment]
For what it's worth, I ran into this problem while spawning wire ENTs, with and without a duplicator. To test it i just put print(ent) into the PlayerSpawnedSENT hook, which would only print the entity after I added the hook.run to the makewireent function

**Comment by kerbalcadet** [comment]
My knowledge of wire code is somewhat limited, so if there's a better place to call this function from then that also works! I just needed some way to reference wire ENTs on spawn.

**Comment by thegrb93** [comment]
Yeah I anything calling WireLib.MakeWireEnt should call the hooks. What specifically is failing to do this?

**Comment by thegrb93** [comment]
Actually, I think the problem here is there's confusion about PlayerSpawnedSENT, this hook is specifically for things spawned in the 'Entities' tab of the spawn menu. PlayerSpawnObject is for things spawned with the toolgun.
