### ISSUE TITLE
spawn basic wire tools (gates, explosives, buttons, etc)

### ISSUE THREAD

**Issue by personguybutsmart** [wiremod/wire#2209]
[wire-master] addons/wire-master/lua/entities/gmod_wire_explosive.lua:173: attempt to call field 'Think' (a nil value)
  1. unknown - addons/wire-master/lua/entities/gmod_wire_explosive.lua:173
 yeah i have no idea about lua soooo help

**Comment by personguybutsmart** [comment]
the tools still work just errors that lag my game a ton

**Comment by thegrb93** [comment]
Something else broke your gmod. Try removing other addons to fix.
