### ISSUE TITLE
I improved the FLIR camera mode as a personal project, how can I get it considered for addition?

### ISSUE THREAD

**Issue by kerbalcadet** [wiremod/wire#2212]
Of course I couldn't just create a new branch for a pull request (unless I just don't understand something obvious). It's probably best that I don't just paste everything here, but maybe a pastebin link?

Anyway, what I changed:

*Highlighted entities are separate from other opaque renderables, meaning that trees and map geometry do not render with ugly polygons and retain their textures
*Fixed infrared emitters becoming darker or invisible in low-light areas, FLIR image is consistent across maps and lightings
*Fixed visible color affecting IR signature, making black props invisible (ish)
*Fixed sky becoming white and distracting in IR
*Added Bokeh DOF to soften image, adjusted bloom
*Set environment and entities to different DrawColor passes, so their brightness and contrast can be altered independently (needed to keep white map geometry from being as bright as entities)

**Comment by thegrb93** [comment]
Create a fork and push your changes to it. Then you can pull request them here.

**Comment by kerbalcadet** [comment]
@thegrb93 Figured it out, thanks.
