### ISSUE TITLE
With the newest version of wire cloned from github, pasting any dupe with E2s causes lua errors

### ISSUE THREAD

**Issue by kerbalcadet** [wiremod/wire#2214]
I.E. [wire-master] entities/gmod_wire_expression2/core/angle.lua:7: attempt to index local 'output' (a number value)
  1. unknown - entities/gmod_wire_expression2/core/angle.lua:7
   2. TriggerOutputs - addons/wire-master/lua/entities/gmod_wire_expression2/init.lua:518
    3. Execute - addons/wire-master/lua/entities/gmod_wire_expression2/init.lua:161
     4. Setup - addons/wire-master/lua/entities/gmod_wire_expression2/init.lua:481
      5. func - addons/wire-master/lua/wire/stools/expression2.lua:433
       6. unknown - lua/includes/extensions/net.lua:32

This does not happen with the workshop version.

**Comment by thegrb93** [comment]
Can you show a snippet of E2 code that triggers it?

**Comment by kerbalcadet** [comment]
@name Avia Control
@inputs [R F Shift Alt W A S D Mouse1 Mouse2] [Crank1 Crank2 Base]:entity [FBlades BBlades]:array
@outputs Throt Hov On RPM1 RPM2 ALT [T1 T2 VEL]:vector Ang:angle
@persist [Spool] [HT HI HX HY HZ] [AM FM Bias] [B1 B2 D1 D2 FB BB] [AngF1 AngF2] [Ang]:angle
@trigger F R



if(first() || dupefinished()) {
    AM = 4000
    FM = 60
    Bias = 1.06
    Hov = 0

    timer("blades", 500)
    timer("sound", 1000)
}

    interval(100)

### Flight Vars ###


VEL = Base:velL()
HX = VEL:x()/cos(Ang:pitch())                       #hover x,y,z vel 
HY = VEL:y()/cos(Ang:roll())
HZ = Base:vel():z()

      rangerHitEntities(0)
      rangerHitWater(1)
ALT = round(toUnit("m", rangerOffset(10000, Base:pos() - vec(0,0,50), vec(0,0,-1)):distance()))

RPM1 = abs(Crank1:angVel():pitch()/6)
RPM2 = abs(Crank2:angVel():pitch()/6)

Ang = Base:angles()
Angv = Base:angVel()


### Control Vars ###


if(~R && R) {           # On / Off 
    On = !On
    exit()
}

if(~F && F) {
    Hov = !Hov
    Throt = Hov ? 0 : round(Throt/5)*5
    HT = 50
    exit()
}


if(!Hov) {Throt += (Shift-Alt)*5}
else{
    HT += -(HZ - (Shift-Alt)*75)/10 -$HZ/2
    HI = clamp(HI - HZ/200, -3, 3)
    Throt = HT + HI
}

Throt = clamp(round(Throt), 0, 100)

Spool += clamp(On - Spool, -0.05, 0.05)

###


### Hover ###

HVec = clamp(vec(0,
           HY*15 - Ang:roll()*300,
           HX*30 + (Ang:pitch() - 2.03)*1000),
            -vec(0, 7500, 20000),
            vec(0, 7500, 20000))

### Engine // Turning ###

T2 = vec(0,RPM1*10,0)

TV = (abs(VEL:x()) + abs(VEL:y()))*0.0006

Height = FM*((Throt/100)*(1 + TV)                               #Collective + Transverse
              - VEL:z()*0.001*(Throt/100 + 1.5)                 #up/down Drag
              + 1.95)                                           #Constant
Roll = -Ang:roll()*100 - Angv:roll()*300 + (D-A)*RPM1*20
Yaw = Angv:yaw()*250 - (Mouse1-Mouse2)*RPM2*35

if(!B1) {
    
    local AngF1 = Spool*(AM*(RPM1<500) + VEL:z()*7) - VEL:z()*8    
    Crank1:applyAngForce(ang(-1, 0, 0)*(AngF1 - $RPM1*150))                  #Torque/RPM
       
    local Y1 = Yaw - RPM2*10*B2 + Roll                                        #Yaw/Roll    
    local Z1 = RPM1*(Height*Bias - (W-S)*60 + Angv:pitch()*3)                 #Height/Pitch
    
    T1 = (vec(0, Y1, Z1) + Hov*HVec)*FB + vec(0,-RPM2*10,0)*(1 - FB)          #Thrust
}
else{T1 = vec(0,-RPM2*10,0)}                                                  #default if broken

if(!B2) {

    local AngF2 = Spool*(AM*(RPM2<500) + VEL:z()*7) - VEL:z()*8    
    Crank2:applyAngForce(ang(1, 0, 0)*(AngF2 - $RPM2*150))                   #Torque/RPM
 
    local Y2 = -Yaw + RPM2*10*B1 + Roll                                     #Yaw/Roll    
    local Z2 = RPM2*(Height + (W-S)*60 - Angv:pitch()*3)                     #Height/Ptich
    
    T2 = (vec(0, Y2, Z2) + Hov*(HVec)*vec(0,1,-1))*BB + vec(0,RPM1*10,0)*(1-BB)
}
else{T2 = vec(0,RPM1*10,0)}

if(Crank1:isUnderWater()) {T1 = vec(0,0,0)}
if(Crank2:isUnderWater()) {T2 = vec(0,0,0)}

### Blade Striking ###


if(clk("blades")) {
    local D1 = (Crank1:pos():distance(Base:toWorld(vec(42,-7,53)))) < 50
    local D2 = (Crank2:pos():distance(Base:toWorld(vec(-300,-6,59)))) < 50

    rangerHitEntities(0)
    local R1 = rangerOffsetHull(Base:toWorld(vec(42,0,58)), Base:toWorld(vec(42,0,58)), Base:right()*420 + Base:forward()*420)
    
    if(R1:hit() && RPM1 > 200) {
        Crank1:soundPlay(7, 0.8, "physics/metal/canister_scrape_smooth_loop1.wav")
        Crank1:constraintBreak()
        B1 = 1
    }
    
    rangerHitEntities(0)
    local R2 = rangerOffsetHull(Base:toWorld(vec(-300,0,64)), Base:toWorld(vec(-300,0,64)), Base:right()*420 + Base:forward()*420)
    
    if(R2:hit() && RPM2 > 200) {
        Crank2:soundPlay(8, 0.8, "physics/metal/canister_scrape_smooth_loop1.wav")
        Crank2:constraintBreak()
        B2 = 1
    }

    B1 = (B1 || !D1)
    B2 = (B2 || !D2)


    FB = FBlades:count()/3                              #percentage of blades remaining
    BB = BBlades:count()/3
    
    timer("blades", 500)
}


### Sound ###

if(clk("sound")) {
    Crank1:soundPlay(1, 0, "npc/attack_helicopter/aheli_rotor_loop1.wav")
    Crank2:soundPlay(2, 0, "npc/attack_helicopter/aheli_rotor_loop1.wav")
}

soundPitch(1, RPM1/3.25)
soundPitch(2, RPM2/3.3)


This is one, from a vehicle of mine. It causes enough errors that AdvDupe removes the dupe lol

**Comment by kerbalcadet** [comment]
It works just fine for me with the workshop version, but it's possible another addon somehow conflicts with the github one.

**Comment by thegrb93** [comment]
Which of those triggers the error?

**Comment by kerbalcadet** [comment]
It doesn't say - the errors occur as the dupe is finishing pasting, and all seem to have some kind of null reference going on. It doesn't refer to any lines of E2 code, but to the lua source code.

**Comment by llysdal** [comment]
I've encountered this with a few chips as well - here's an example of one such error
`Expression 2 (Bike Lean): entities/gmod_wire_expression2/core/angle.lua:184: attempt to index local 'this' (a number value)`

and the code that produces this (removed all the code that's irrelevant to the error - this code still errors with the same error)

```golo
@inputs E:entity

E:angles():pitch()
```

It seems there's some issue with entities not being initialized right, and null values being passed around?

The error disappears when removing the `pitch()` call.

**Comment by kerbalcadet** [comment]
+1 for angle call, that was one of the errors (maybe the source)? Have the angle functions changed since the workshop release?

**Comment by thegrb93** [comment]
Looks like the workshop was updated Jul 6.

Can you see if these versions have the issue? If not, then I think @Vurv78 's PR caused it.

https://github.com/wiremod/wire/tree/02d5dfd0ae28a0a1e4e01952857c982abd68f636
https://github.com/wiremod/wire/tree/73b4dbf20818f65f7a183521527da451f7f1db1b

**Comment by thegrb93** [comment]
If one has the issue an not the other, then @stepa2 's do-while thing must've caused it. If both have the issue, then I'll have to investigate further.

**Comment by kerbalcadet** [comment]
Will check out in a few minutes

**Comment by Vurv78** [comment]
It's my pr. Just https://github.com/wiremod/wire/blob/384809700d1cd250cf0f3f5b98d1e642e5131cd3/lua/entities/gmod_wire_expression2/core/entity.lua#L453

Easy fix if you want to do it right now @thegrb93 but I'm gonna sift through and see if there's more incorrect ones

**Comment by kerbalcadet** [comment]
Vurv is right - I just tested and ended up with the commit being 5fc05d58f9ed808bf4d9bfae622175e78380ac1c

I don't know exactly which part, but it seems like he understands.

**Comment by kerbalcadet** [comment]
Thanks for the quick responses, guys. This seems fixed, so I'll close this thread and move on to other issues :)

**Comment by kerbalcadet** [comment]
Vurv - I had the same problem with angVelVector(). I didn't look into how your error throwing mechanism works, but I replaced every instance in exp2/entity.lua of throw("...", 0) with throw("...", {0, 0, 0}) and that's worked. If there's a reason for some of them to be just the number, you can work it out from there.

**Comment by Vurv78** [comment]
Well it's not fixed until someone pushes a commit

**Comment by Vurv78** [comment]
Also that last parameter is the value you're gonna return, most of them are correct but ofc if you return nil when e2 expects a vector or something it will break. Since I added so many of these I ended up copy pasting and getting some wrong. At least it's only when your code is null unsafe

**Comment by kerbalcadet** [comment]
Yeah that makes sense. Thanks!
