### ISSUE TITLE
Refactor E2 to use Vector() & Angle() constructors/userdata

### ISSUE THREAD

**Issue by Vurv78** [wiremod/wire#2218]
Vectors/Angles are already returned by a lot of functions so there's no real security concerns there.  

It would be a massive boost to performance since we construct a vector/angle every single time for many functions like ``setAng``, ``applyForce``, etc, which many E2s call these functions every tick at least once if not multiple times.

**Comment by thegrb93** [comment]
I think it's using tables because lua userdata and ccalls are actually slower

**Comment by thegrb93** [comment]
Yeah you're right that constructing them for every glua function that uses them is pretty slow though. Starfall suffers from this too unfortunately.

**Comment by thegrb93** [comment]
I think we investigated the performance and found this to be better overall though since far more math is done on the vectors than using them in glua.

**Comment by bigdogmat** [comment]
I doubt there'd be much of a performance hit in either direction, at this point it's a matter of the amount of code that assumes it being a table. Extensions will still assume tables are used, and return them.

There's also the issue of vectors and angles being limited by their respective datatypes. I know personally I've used vectors as cheap number arrays in the past and have gone past the precision limitation of a float.

**Comment by Vurv78** [comment]
Why close this?

Even for the addon issue we can always just check if it's already a vector through indexing or ``isvector``, would be better than indexing three times into the table + constructing the vector every time.

And I see people wanting to use vectors as cheap number arrays as a concern in itself

**Comment by thegrb93** [comment]
If you want to try that, then sure. I don't think we should clutter the issues here any further though.

**Comment by TomyLobo** [comment]
seeing how isvector performs would actually be interesting. Though I have a suspicion the overhead of calling that is going to be similar to calling Vector()

**Comment by thegrb93** [comment]
especially since jit craps itself with isvector in x64

**Comment by bigdogmat** [comment]
> Even for the addon issue we can always just check if it's already a vector through indexing or `isvector`, would be better than indexing three times into the table + constructing the vector every time.

This still doesn't fix the issue other addons will assume it's just a table, granted it's less likely to cause issues in that direction. And if we still have to do checks everywhere a vector function is used then this is already not looking great.

> And I see people wanting to use vectors as cheap number arrays as a concern in itself

While that's true it was just an example of the precision issue, losing integer precision above `16777216` isn't exactly great.
