### ISSUE TITLE
e2 error on server load

### ISSUE THREAD

**Issue by RedNarwhal59** [wiremod/wire#2229]
When loading into singleplayer or a server with wiremod, a file appears to be missing and causes an error. Nothing insane

[Wiremod] Couldn't include file 'e2doc.lua' - File not found (@lua/entities/gmod_wire_expression2/core/init.lua (line 338))
    1. unknown - lua/entities/gmod_wire_expression2/core/init.lua:338
        2. include - [C]:-1
            3. unknown - lua/entities/gmod_wire_expression2/shared.lua:26
                4. include - [C]:-1
                    5. unknown - lua/entities/gmod_wire_expression2/cl_init.lua:1

not sure if this is something I did but I did try resubbing and still noticed it.

**Comment by Divran** [comment]
well the file is right here <https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/e2doc.lua> so it looks like you didn't upload that specific to your server for some reason?

**Comment by RedNarwhal59** [comment]
figured as much, sorry lmao. I'll try deleting the gma and remounting it to the server as well.

**Comment by Divran** [comment]
Wait a sec, does this error happen on the client side? It's actually possible that the file isn't sent to the client. I'm no longer on my PC so I can't double check right now though. 

Regardless, this error won't cause any issues because the docs file doesn't actually do anything. It's only used to generate the wiki. So even if you are unable to fix it you can just ignore it. And then I or someone can look at it closer later

**Comment by RedNarwhal59** [comment]
I believe its clientside yeah. happens whenever I load into my server (and probably any other)

and yeah I knew it wasn't anything that would break it, I just happened to notice it out of the blue.

**Comment by wrefgtzweve** [comment]
Having the same issue, can confirm it's clientside and only once. Happens in my local server too.

```
[wire] Couldn't include file 'e2doc.lua' - File not found (@addons/wire/lua/entities/gmod_wire_expression2/core/init.lua (line 339))
    1. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/init.lua:339
        2. include - [C]:-1
            3. unknown - addons/wire/lua/entities/gmod_wire_expression2/shared.lua:26
                4. include - [C]:-1
                    5. unknown - addons/wire/lua/entities/gmod_wire_expression2/cl_init.lua:1
```
