### ISSUE TITLE
e2 sound seems a bit choppy 

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#2238]
ok, so idk if its me or its the server addons or what but when i use my e2 engine the sound that normally plays isnt smooth at all its so choppy ike its cutting in and out while chainging pitch does anyone know why?

**Comment by deathking61** [comment]
thats odd cause they just changed the addon to the recent github and reset the addons soo its still doing it so sounds like e2 is bugged out or something ill keep looking

**Comment by deathking61** [comment]
sooo seems like soundpitch in e2 is broken it causes odd noises as this is part of an e2 





soundPitch(1,RPM/6.46)
soundPitch(2,RPM/19.96)
soundPitch(3,RPM/24.98)
soundPitch(4,RPM/30.03)
soundPitch(5,RPM/35.03)
soundPitch(6,RPM/40)
soundPitch(7,RPM/45.02)
soundPitch(8,RPM/50.02)
soundPitch(9,RPM/55.01)

Num = sin(clamp((RPM-8050)/5,0,180))
Tr = 0.7 + Thro

soundVolume(1,sin(clamp((RPM+20)/15,0,160))*Tr)
soundVolume(2,sin(clamp((RPM-1080)/10,0,160))*Tr)
soundVolume(3,sin(clamp((RPM-2040)/5,0,160))*Tr)
soundVolume(4,sin(clamp((RPM-2550)/5,0,160))*Tr)
soundVolume(5,sin(clamp((RPM-3050)/5,0,160))*Tr)
soundVolume(6,sin(clamp((RPM-3550)/5,0,160))*Tr)
soundVolume(7,sin(clamp((RPM-4050)/5,0,160))*Tr)
soundVolume(8,sin(clamp((RPM-4550)/5,0,160))*Tr)
soundVolume(9,sin(clamp((RPM-5050)/5,0,90))*Tr)





mind you this wasnt broken untill sothing happened with gmod updates or wire mod not sure what one but it broke the pitch in e2

**Comment by thegrb93** [comment]
My only guess would be to try without the filter: https://github.com/wiremod/wire/blob/d0a84b700fff18098bd3c6ee1b3c53b708f8a15a/lua/entities/gmod_wire_expression2/core/sound.lua#L88-L90

Seems like a garrysmod-issue if it works without that.

**Comment by deathking61** [comment]
I have confirmed with Gmod dev team it's your addon that needs to be updated

**Comment by thegrb93** [comment]
> I have confirmed with Gmod dev team it's your addon that needs to be updated

Please tell us what to update

**Comment by Vurv78** [comment]
Couldn't reproduce this BUT: Shouldn't the recipient filter be set to use the unreliable channel as was being tracked in https://github.com/wiremod/wire/issues/2073?

Btw: In the future please provide an example that is easily usable or at least with instructions, plus default sound files..

**Comment by thegrb93** [comment]
You're right. Good find. I think I misread his update and thought that reliable was false by default. Should be an easy fix then.
