### ISSUE TITLE
Buttons arent working 

### ISSUE THREAD

**Issue by AlexanderB2109** [wiremod/wire#2239]
Hi. I've been using wiremod for a while, and recently I've been having a problem where when I press a button, it stays pressed and I cannot turn it off. Even when toggle is off this happens.

**Comment by AlexanderB2109** [comment]
In the console it says it "attempted to call "Think" (a nil value)". I don't have any other wiremod related addons. I've downloaded the latest github release. If it helps, I have the github version of PAC3, Half-Life: Source Content, and CSS Content. I have bought GMod legitimately.

**Comment by TomyLobo** [comment]
It always is :)
