### ISSUE TITLE
Wire Expression2 is using alot of cpu time.

### ISSUE THREAD

**Issue by GoldenEG** [wiremod/wire#2243]
I don't know why this even occurs but when I put a e2 from a dupe on my server (those kind of e2 have many lines of code and are well work), my game starts to lag as hell and when I delete the e2, everything goes back at normal.
Since my beginning of GMOD I always did have Wiremod as mod, i do not know why today it happens and i have no clue how to fix it.
I did uninstall it from the workshop then install it back, still the same. I downloaded wiremod from github and did put it to addons, still the same.
I will send you guys a scene of me spawning an e2 then the lua errors that i found :

1) addons_wire-master_lua_entities_gmod_wire_expression2_base_optimizer.lua
local ok, result = xpcall(Optimizer.Process, E2Lib.errorHandler, root) - severe

2) addons_wire-master_lua_entities_gmod_wire_expression2_core_extloader.lua
	local ok, message = pcall(e2_include_pass2, unpack(info)) - severe
	local ok, err = pcall(func) - severe

3) addons_wire-master_lua_entities_gmod_wire_expression2_core_extpp.lua
local ok, msg = pcall(handle_function) - severe

4) addons_wire-master_lua_entities_gmod_wire_expression2_core_init.lua
ok, ret = pcall(callback, ...) - severe

5) addons_wire-master_lua_entities_gmod_wire_expression2_init.lua
local ok, msg = pcall(self.script[1], self.context, self.script) - severe
	local ok, ret = pcall(self.CallHook, self, ...) - severe
	local ok, ret = pcall(self.CallHook, self, ...) - severe

Those are all lua errors with their lua name file and code.
Here is the video :
https://user-images.githubusercontent.com/93436284/139536300-d537066d-9e5a-4092-8965-66d95edb4f6c.mp4

**Comment by thegrb93** [comment]
There's probably something wrong with your install
