### ISSUE TITLE
crossbow_bolt entity isn't affected by applyForce 

### ISSUE THREAD

**Issue by dragitz** [wiremod/wire#2244]
Hi I believe this is a bug. 

I'm trying to cancel the gravity of the bolt. I went straight up with a powerful forward force, but I've noticed that nothing gets applied to my entity.

The code does work when applied to a ``prop_combine_ball`` but not to the bolt

Minimal code for reproduction:
```lua

runOnTick(1)
findByClass("crossbow_bolt")
Ents = findToArray()

for(I=0,Ents:count()){

   Ent = Ents[I,entity]
   Ent:applyForce(vec(Ent:velL():x(),Ent:velL():y(),Ent:velL():z())*5000)

}
```

I've looked at the sdk for the crossbow and the speed of the bolt doesn't seem to be affected much.

sdk link: link https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/server/hl2/weapon_crossbow.cpp#L317

In another issue I've read that the workshop version is outdated, is this still true? Because it might be fixed in the github version.

Best wishes

**Comment by thegrb93** [comment]
They aren't physical entities. You might be able to setAngle on them to control their trajectory but applyForce for sure wont work
