### ISSUE TITLE
Internal Error attempt to index local 'rt' (a nil value)

### ISSUE THREAD

**Issue by 22hideki22** [wiremod/wire#2255]
I was building a tank with Armoured Combat Extended, and I was on a server, I went to save the tank with the advanced duplicator 2, and when I created a server and went to spawn the tank appeared an error in E2 saying ''internal error, see console for more details'' I tried to search the folders of gmod and found nothing,   this part that says ''rt'', is equal to the name of an RT camera addon.

Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 304	"__index"		lua/entities/gmod_wire_expression2/core/e2lib.lua
	3: Line 475	"CallInstruction"		lua/entities/gmod_wire_expression2/base/compiler.lua
	4: Line 163	"EvaluateStatement"		lua/entities/gmod_wire_expression2/base/compiler.lua
	5: Line 293	"CallInstruction"		lua/entities/gmod_wire_expression2/base/compiler.lua
	6: Line 163	"EvaluateStatement"		lua/entities/gmod_wire_expression2/base/compiler.lua
	7: Line 361	"CallInstruction"		lua/entities/gmod_wire_expression2/base/compiler.lua
	8: Line 163	"EvaluateStatement"		lua/entities/gmod_wire_expression2/base/compiler.lua
	9: Line 293	"CallInstruction"		lua/entities/gmod_wire_expression2/base/compiler.lua
	10: Line 65	"nil"		lua/entities/gmod_wire_expression2/base/compiler.lua
	11: C function	"Execute"
	12: Line 74	"wire_expression2_validate"		lua/entities/gmod_wire_expression2/cl_init.lua
	13: Line 1596	"Validate"		lua/wire/client/text_editor/wire_expression2_editor.lua
	14: Line 447	"SetActiveTab"		lua/wire/client/text_editor/wire_expression2_editor.lua
	15: Line 1721	"Open"		lua/wire/client/text_editor/wire_expression2_editor.lua
	16: Line 816	"func"		lua/wire/stools/expression2.lua
	17: Line 32	"nil"		lua/includes/extensions/net.lua

Internal error - please report to https://github.com/wiremod/wire/issues
lua/entities/gmod_wire_expression2/base/compiler.lua:475: attempt to index local 'rt' (a nil value)

Another thing Appeared too:

Erroring opening file: genericInternal error - please report to https://github.com/wiremod/wire/issues
lua/entities/gmod_wire_expression2/base/compiler.lua:589: attempt to index local 'rt' (a nil value)

**Comment by Vurv78** [comment]
There must be an addon breaking E2 really badly because the only way that can happen is if this error is completely avoided
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/base/compiler.lua#L263. Afaik nothing has changed at all here recently either

``rt`` is completely unrelated to RT Cameras, it's just the name of a lua variable
