### ISSUE TITLE
[BUG] Constraints Core's Hydraulic doesn't work well.

### ISSUE THREAD

**Issue by Opener974** [wiremod/wire#2256]
```
@name E2 can change neither Constant nor Damping on the Wire Constraints Core's hydraulic.

# Entities
@inputs [E1 E2]:entity

# Change Button
@inputs On


# Create hydraulic
if(E1 & E2)
{
    hydraulic(1, E1, vec(), E2, vec(), 2500, 150, 0, "cable/cable2", 1, 0)
}



# Restrain Constant and Damping
if(On)
{
    E1:setConstant(1, 0)
    E1:setDamping(1, 0)
}



# Reset Constant and Damping to original constant, damping
else
{
    E1:setConstant(1, 2500)
    E1:setDamping(1, 150)
}
```

**Comment by thegrb93** [comment]
What doesn't work well about it?

**Comment by thegrb93** [comment]
Nvm just saw the name. Looking at the code, it should work fine. Will have to test it myself.

**Comment by Fasteroid** [comment]
@Opener974 Just tested this.  It's working just fine—but I'll admit catching the problem with your code took me a minute.
```
# Create hydraulic
if(E1 & E2)
{
    hydraulic(1, E1, vec(), E2, vec(), 2500, 150, 0, "cable/cable2", 1, 0)
}
```
This block will actually run every time `On` changes, which re-creates the hydraulic and will reset its target length to whatever the current distance between `E1` and `E2` is.  This results in it not behaving as expected.

**Comment by thegrb93** [comment]
Good catch, seems to be a bug with your E2
