### ISSUE TITLE
E2 chips crashing at high quota cant be reset

### ISSUE THREAD

**Issue by NovaAstral** [wiremod/wire#2257]
I've noticed that if an e2 chip crashes from high quota, it cannot be reset, and I believe the reason for this is that when you reset a chip, it starts at the quota'd value (not the one you can see when looking at the chip, but the actual value it crashed from) and goes back down to the chips idling time.

As seen in this video you can see that using `wire_expression2_quotahard` I've forced the chip to crash, and then set the quota to be really high to see this happen.
The video does not show that if you try to reset the chip, it will instantly crash, you have to replace the entire entity if you don't have access to that console command and this ends up happening.

https://user-images.githubusercontent.com/38473327/146658048-75ea76eb-31fb-4681-9de9-d9181f547d0e.mp4

**Comment by Divran** [comment]
yep you're correct. this was caused by my earlier fix here <https://github.com/wiremod/wire/commit/d8cdc76bcbc26706ab0edc4fd55ab7f4d3385b29#diff-9665b2962bd8ff09856e58384eff6add446f2bf01cfa50d69921fec3fda64f6b>

I'm fixing it now right (see link below)

**Comment by Divran** [comment]
The fix should be pretty foolproof but please test it and let me know if you find any other issues

**Comment by garryspins** [comment]
I think thats intentional
