### ISSUE TITLE
[E2] Timer don't work when included.

### ISSUE THREAD

**Issue by Meowlan** [wiremod/wire#2260]
I have 2 files, the first file is an API wich has timers to make the filesystem work properly. The second file includes the first one and runs a function to load a file. If i try to use the function in the first file it works fine and prints the result. But if try to run it in the second file the `clk("load_timer")` wont fire . 

First file:
```lua
function load(File:string){
    if(fileCanLoad()){
        fileLoad(File)
        timer("load_timer",1000)
    }
}
if(clk("load_timer")){
    if(!fileLoading()) {
        Str = fileRead()    
        Split = Str:explode("\n")
        for(I=1,Split:count()){
            print(Split[I,string])    
        }
    }else{timer("load_timer",1000)}
} 
```

Second file:
```lua
if(first()|duped()){
    #include "meowlans_apis/bank_api"
    load("bank_accounts.txt")
}
```

**Comment by Aws0mee** [comment]
Hi meowlan

**Comment by Divran** [comment]
The included file only runs when you are including it. If you want code in the included file to run again at a later time, you need to wrap it in a function and call that function from the main file.
```
function load(File:string){
    if(fileCanLoad()){
        fileLoad(File)
        timer("load_timer",1000)
    }
}
function onLoaded() {
    if(!fileLoading()) {
        Str = fileRead()    
        Split = Str:explode("\n")
        for(I=1,Split:count()){
            print(Split[I,string])    
        }
    }else{timer("load_timer",1000)}
}
```

```
if(first()|duped()){
    #include "meowlans_apis/bank_api"
    load("bank_accounts.txt")
} elseif(clk("load_timer")){
    onLoaded()
}
```

**Comment by TomyLobo** [comment]
That's because you only ever include that file once, so the `if(clk("load_timer"))` is only ever evaluated once.

Come to the discord and ask there if you have questions like these or if you want to bounce your potential bug reports off of someone else.
This is a bug tracker.

**Comment by Divran** [comment]
and also yes, this github is a bug tracker, so ideally the best place to ask questions that aren't bug reports is on the discord channel. And if you are unsure if it's a bug or not, it's always best to come to the discord to ask first.

**Comment by Meowlan** [comment]
Ok i am sorry thanks alot
