### ISSUE TITLE
Couldn't include file 'e2doc.lua' - File not found (@addons/wire-master/lua/entities/gmod_wire_expression2/core/init.lua (line 338))

### ISSUE THREAD

**Issue by MickaelOliveira25** [wiremod/wire#2267]
reinstalled gmod, deleted the whole folder and installed again. still this error always happens after reinstallation.

[wire-master] Couldn't include file 'e2doc.lua' - File not found (@addons/wire-master/lua/entities/gmod_wire_expression2/core/init.lua (line 338))
    1. unknown - addons/wire-master/lua/entities/gmod_wire_expression2/core/init.lua:338
        2. include - [C]:-1
            3. unknown - addons/wire-master/lua/entities/gmod_wire_expression2/shared.lua:26
                4. include - [C]:-1
                    5. unknown - addons/wire-master/lua/entities/gmod_wire_expression2/cl_init.lua:1

**Comment by Divran** [comment]
This was fixed here https://github.com/wiremod/wire/commit/0c873d39f3b9443d5d76be5f9a2aaa48e9c62241
