### ISSUE TITLE
New Hologram display limits update completely broke text display.

### ISSUE THREAD

**Issue by Hazeofdream** [wiremod/wire#2273]
This means it is impossible to grab ANYONE's holograms, kinda a yikes!

[wire] addons/wire/lua/entities/gmod_wire_expression2/core/cl_hologram.lua:14: attempt to index upvalue 'holoDisplayCVar' (a nil value)
  1. fn - addons/wire/lua/entities/gmod_wire_expression2/core/cl_hologram.lua:14
   2. unknown - addons/ulib-master/lua/ulib/shared/hook.lua:109

**Comment by thegrb93** [comment]
This line should be `CreateConVar` https://github.com/wiremod/wire/pull/2271/files#diff-2548e3cbe473fd5a19032bc7cd8f66b5944d9868305d63f6206f957a94db0623R2

**Comment by thegrb93** [comment]
@LiddulBOFH mind doing a patch?

**Comment by LiddulBOFH** [comment]
Ah, sorry, didn't get this notification till a couple hours later; also figured since the server-side version of that cvar was replicated, wouldn't need to recreate it, just need that particular cvar not able to be changed by clients

**Comment by Divran** [comment]
to be clear, I did test this before merging and did not get this issue. it seems the host of a local server isn't affected by this issue.

**Comment by thegrb93** [comment]
Yeah it would've only affected dedicated servers
