### ISSUE TITLE
Wire pod causing lua errors

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/wire#2277]
Serverside error:
```
addons/wire/lua/entities/gmod_wire_pod.lua:252: attempt to call method 'UnlinkEnt' (a nil value)
   0.  UnlinkEnt - [C]:-1
    1.  Function - addons/wire/lua/entities/gmod_wire_pod.lua:252
     2.  fn - lua/includes/extensions/entity.lua:146
      3.  unkown - addons/ulib/lua/ulib/shared/hook.lua:109
```

Not sure how to replicate it, only got the error from the server console.

**Comment by thegrb93** [comment]
Workshop version or git version? Looks outdated.

**Comment by Divran** [comment]
errored line: <https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_pod.lua#L252>
yeah this shouldn't happen because this CallOnRemove is cleared when the pod controller is removed, as seen here: <https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_pod.lua#L221>

**Comment by wrefgtzweve** [comment]
Using wire master, latest change 13th for February
![image](https://user-images.githubusercontent.com/69946827/155784703-0d356237-f1f6-4390-ba45-539a7622841a.png)

**Comment by thegrb93** [comment]
Oh I think I was in the cam_controller file

**Comment by thegrb93** [comment]
Well, it's all server-side code so it can't be client gmod bugs causing it. EntityRemoved hook is being called after the pod loses its SENT lua table somehow.

**Comment by thegrb93** [comment]
I'm guessing this fixes it. I think maybe it had to do with the pod and pod controller being deleted on the same frame.
