### ISSUE TITLE
Just updated wire now can't wire e2s anymore

### ISSUE THREAD

**Issue by TheLight91** [wiremod/wire#2283]
Mouse clicks don't link stuff anymore, nor r unlinks

**Comment by LiddulBOFH** [comment]
Also seem to have this issue but only in singleplayer (local server works fine); reverting to before https://github.com/wiremod/wire/commit/c45fe1367095365984c8adbb8afbaa23ad5e750e seems to fix it, maybe an issue with IsFirstTimePredicted in singleplayer?

**Comment by Divran** [comment]
The above update should fix it. Let me know if you still have issues @TheLight91

**Comment by Divran** [comment]
To be specific, the fix for this bug in particular is this part here
https://github.com/wiremod/wire/blob/master/lua/weapons/gmod_tool/stools/wire_adv.lua#L502
where I added an "is not single player" check in addition to the "is not first time predicted" check, since it seems single player doesn't need the predicted check.

**Comment by TheLight91** [comment]
I'll test it as soon as possible, now having dinner.

**Comment by TheLight91** [comment]
@Divran Seems like it's fixed in single player too now.

**Comment by TheLight91** [comment]
BTW, it seems that wire works differently from multiplayer and singleplayer in other things too. Like clutches work decently in multiplayer, while they don't always work in single player.

**Comment by Divran** [comment]
yeah most devs focus on multiplayer, so single player barely gets any testing. Feel free to report any bugs you find either here or on the discord <https://discord.com/invite/H8UKY3Y> (if you are unsure if it's a bug or not, use the discord). There are a few bugs that we probably won't fix in single player (like save games). But you can also always just host a local server instead and avoid all issues that way.

**Comment by TheLight91** [comment]
@Divran How do you host a local server though? because if it's done from Gmod itself with the options in single player, I already tried that and the issues remain, like the tickrate following fps and all weirdness of sp wire.

**Comment by Divran** [comment]
> @Divran How do you host a local server though? because if it's done from Gmod itself with the options in single player, I already tried that and the issues remain, like the tickrate following fps and all weirdness of sp wire.

Click start game and then there is a drop-down menu in the top right corner of the screen where you can choose between single player or various player limits. Pick any option other than single player and it'll host a local server that other people will be able to join assuming you have your ports opened. Can always set a password to prevent that.

**Comment by TheLight91** [comment]
I tried that, doesn't change anything for me.

**Comment by Divran** [comment]
Well that's what I do every time. That's also what I did when I tested the update to the wire tool that made it break in single player, and since it worked fine during testing, I definitely couldn't have been in single player.

**Comment by TheLight91** [comment]
Well, I get the same wire clutch inconsistency that I get in sp while using the local server and the tickrate was still tied to fps.

**Comment by Divran** [comment]
You can try putting this in console `lua_run print(game.SinglePlayer())`, check if it prints true or false

**Comment by TheLight91** [comment]
I know it is multiplayer, says it in steam too, but it doesn't solve any of the problems I have with my sp wire, weird stuff.

**Comment by Divran** [comment]
it's possible the clutch has the same issue regardless

**Comment by TheLight91** [comment]
It does not. On an actual server it works perfectly, consinstently activates like it should. I opened an issue on it already, it's a bug.
