### ISSUE TITLE
Vehicle Exit Controllers aren't saving linked seats when duped

### ISSUE THREAD

**Issue by Amplar** [wiremod/wire#2284]
What it says on the tin, dupes aren't saving the linked seats and require relinking every paste. Curiously, older vehicles I have with exit controllers still retain their links.

**Comment by thegrb93** [comment]
Might be caused by https://github.com/wiremod/wire/commit/b457bc15c95471e9cc842644ceba4184c9bed3a6 will have to test

**Comment by thegrb93** [comment]
@Divran

**Comment by Divran** [comment]
I can look tomorrow

**Comment by thegrb93** [comment]
Got it

**Comment by Amplar** [comment]
sweet
