### ISSUE TITLE
Wire Clutch inconsistency in single player.

### ISSUE THREAD

**Issue by TheLight91** [wiremod/wire#2286]
Wire Clutches don't work the same on single player as they do in multiplayer. They work some times, some times are not working at all with no clear pattern or reason.

**Comment by thegrb93** [comment]
By not work, wdym. It fails to weld? Fails to unweld?

**Comment by TheLight91** [comment]
It fails to apply any friction to the selected props, like at all like it isn't even active. Checked with debugged if it was a problem with imputs, but it's not, its the clutch itself.

**Comment by thegrb93** [comment]
Probably something to do with this awful code https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_clutch.lua#L222-L242

**Comment by thegrb93** [comment]
@TheLight91 see if https://github.com/wiremod/wire/pull/2305 fixes it

**Comment by TheLight91** [comment]
Just saw this, gonna test it right now.

**Comment by TheLight91** [comment]
Nope, doesn't fix it, it's still inconstistent, plus it feels like it "sticks" the clutch feels like it doesn't fully release all friction when deactivated.

**Comment by thegrb93** [comment]
The problem seems to be the constraint itself. Imo this should just be simulated in lua rather than using the constraint.

**Comment by thegrb93** [comment]
@TheLight91 try again? I took a guess on how to emulate the static friction. Might need some tuning.

**Comment by TheLight91** [comment]
Just tested the latest commit. Didn't fix the problem. Now no matter how high you set the friction, the wheels won't lock. Under a certain limit of friction nothing happens, over a certain limit the wheels make a noise like when they have some forces applied to them. This is the behavior for already existing clutches in a dupe. New clutches can't link any entity. It says "Entities registered with clutch controller" but on clutch says "unlinked".

**Comment by thegrb93** [comment]
Around what friction value does it lock?

**Comment by TheLight91** [comment]
Never locks, tried 100k too.

**Comment by thegrb93** [comment]
I mean originally

**Comment by thegrb93** [comment]
I think I just need to make a plot of the original friction force vs. velocity and try to get mine to match that.

**Comment by TheLight91** [comment]
Well, at 1000 with 250kg wheels, they are locked even when going down hills. I can run some tests on that to know the full curve of how friction works.

**Comment by thegrb93** [comment]
Seems like the friction in source is only static friction. Its force decreases with angular velocity. I'll have to plot the unlock force with friction value.

**Comment by thegrb93** [comment]
The breaking force is linear as well as the force after breaking so its very simple. The problem is that it doesn't look feasible to emulate the locking even with a PhysicsSimulate hook.

**Comment by thegrb93** [comment]
I don't know why the advballsocket behaves weird in singleplayer, but that's the issue. Maybe it's a garrysmod-issue.

**Comment by thegrb93** [comment]
Seems to work if I get rid of the SetMass functions

**Comment by thegrb93** [comment]
@TheLight91 can you try now?

**Comment by TheLight91** [comment]
If I link the wheels to the setangs (like I usually do and it works perfect in multiplayer with the current wire) the wheels never lock no matter what. If I link them to the base plate, it fucks everything up in a way I can't even describe why. Also, the clutch never fully unlocks, keeping some friction.

Here is a video of it. 

https://user-images.githubusercontent.com/40478437/159659016-e9284882-ffaa-409d-8d16-04ea14d6fa93.mp4

**Comment by thegrb93** [comment]
What friction values are you using?

**Comment by TheLight91** [comment]
> What friction values are you using?

1000

**Comment by thegrb93** [comment]
I think the SetMass probably is needed since the friction values are that high.

**Comment by TheLight91** [comment]
> And what's the weight of the things being clutched?

Wheels are 250, base is 800. Setangs are 1.

**Comment by thegrb93** [comment]
Try replicating the weirdness with the advanced ballsocket tool. A clutch is just an advballsocket. If you find out what's weird then maybe report it to gmod devs?

**Comment by thegrb93** [comment]
Specifically, the clutch sets the prop's mass to 1, advballsockets, then returns the mass to original value.

**Comment by TheLight91** [comment]
I have never experience that behaviour with ballsockets, like ever in all the years af building. Maybe it's just the friction part.

**Comment by TheLight91** [comment]
Is there a way in E2 to create an advancedballsocket with friction and remove it?

**Comment by thegrb93** [comment]
Perhaps it has something to do with setting the mass of the prop, ballsocketting, then setting mass again all in the same frame. Might try to do those on seperate frames to see if that helps.

**Comment by thegrb93** [comment]
@TheLight91 I tried singleplayer and local multiplayer and saw that if you:

set two props mass to 1
advballsocket with 1000 friction using advballsocket tool
return props mass to original

You get a pretty crappy clutch, probably what you're seeing. Mind confirming? I haven't tried in a dedicated server yet, but if it works fine there, then it is probably something to do with the setmass.

**Comment by thegrb93** [comment]
I'm thinking about trying the lua driven clutch again, but locking the clutch with a force limited weld whenever their velocity is low enough.

**Comment by thegrb93** [comment]
Nvm, a weld won't work because it doesn't have free movement.

**Comment by TheLight91** [comment]
Just tested the latest fix on this and it didn't work. Still feels like the clutch doesn't release and still throws the whole vehicle around while not locking the wheels.
