### ISSUE TITLE
Error related to missing StartPos field when using Wire_Render

### ISSUE THREAD

**Issue by TwistedTail** [wiremod/wire#2296]
Since 726419d, I'm getting clientside errors on entities using the `Wire_Render` function on entities using the wire base. I can't find a single place where `StartPos` is defined, however it seems to be required now.

```
[wire] addons/wire/lua/wire/client/cl_wirelib.lua:72: bad argument #1 to 'LocalToWorld' (Vector expected, got nil)
  1. LocalToWorld - [C]:-1
   2. Wire_Render - addons/wire/lua/wire/client/cl_wirelib.lua:72
    3. unknown - addons/acf-3/lua/entities/acf_base_scalable/cl_init.lua:20 
```

**Comment by thegrb93** [comment]
Was already fixed. StartPos is defined in wire_paths.lua
