### ISSUE TITLE
[BUG] Serverside lua errors

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/wire#2298]
Not sure if these errors are related but they're happening roughly at the same time
```
addons/wire/lua/entities/gmod_wire_expression2/init.lua:234: attempt to concatenate field 'name' (a nil value)
   0.  __concat - [C]:-1
    1.  Error - addons/wire/lua/entities/gmod_wire_expression2/init.lua:234
     2.  CompileCode - addons/wire/lua/entities/gmod_wire_expression2/init.lua:250
      3.  Setup - addons/wire/lua/entities/gmod_wire_expression2/init.lua:463
       4.  _ApplyDupeInfo - addons/wire/lua/entities/gmod_wire_expression2/init.lua:538
```

```
addons/wire/lua/entities/gmod_wire_expression2/init.lua:365: attempt to index field 'directives' (a nil value)
   0.  __index - [C]:-1
    1.  ResetContext - addons/wire/lua/entities/gmod_wire_expression2/init.lua:365
     2.  fn - addons/gm_anticrash/lua/z_anticrash/server/sv_wire_halte2s.lua:18
      3.  Run - addons/ulib/lua/ulib/shared/hook.lua:109
```

**Comment by TomyLobo** [comment]
Do you have E2 code to reproduce this error?
Do you have any addons other than wiremod installed, especially ones that provide extra E2 functions?

**Comment by TomyLobo** [comment]
Error #2 is a consequence of error #1, btw, so we can focus on error #1.

**Comment by wrefgtzweve** [comment]
I sadly don't

**Comment by thegrb93** [comment]
The preprocessor threw an error and since that's what sets the name, the name never got set.

**Comment by TomyLobo** [comment]
I'm wondering, this code has been in there [forever](https://github.com/wiremod/wire/blame/820a1bb2a379cae3bd3f8e314a84e811cbb8ba7a/lua/entities/gmod_wire_expression2/init.lua#L204).
What changed to make this error pop up now and not earlier?
Did we just not have any preprocessor errors before?
