### ISSUE TITLE
E2 doesn't keep values set with dupefinished() after refreshing it.

### ISSUE THREAD

**Issue by TheLight91** [wiremod/wire#2303]
I usually set some values with dupefinished(). Everytime I reset the E2 when I changed something in it, all those settings are reset and those values are set to 0, instead of being kept like before.

I guess a quick fix would be to use if(first()|dupefinished()) to have values both when duping and when resetting the E2.

Before, the values set with dupefinished() would be unchangeable unless you redupe the e2, but remained what you set before, not going to be reset to 0 like it happens now.

**Comment by thegrb93** [comment]
What was happening before was a bug. The E2's vars should reset when the E2 resets.

**Comment by TheLight91** [comment]
Ah, so the solution to it is adding first() as I thought. Thanks for explanation.
