### ISSUE TITLE
Serverside error: bad argument #2 to 'max' (number expected, got nil)

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/wire#2306]
Serverside error:
```
lua/includes/extensions/math.lua:52: bad argument #2 to 'max' (number expected, got nil)
   0.  unkown - [C]:-1
    1.  max - [C]:-1
     2.  Clamp - lua/includes/extensions/math.lua:52
      3.  clampForce - addons/wire/lua/wire/wireshared.lua:998
       4.  CalcForce - addons/wire/lua/entities/gmod_wire_thruster.lua:142
        5.  unkown - addons/wire/lua/entities/gmod_wire_thruster.lua:242
```
Not sure how to replicate it sadly, but it's been happening in large volume
![image](https://user-images.githubusercontent.com/69946827/159208139-61f32b91-3131-491c-8591-82fa863381e3.png)

**Comment by thegrb93** [comment]
I think that means you had another addon's InitPostEntity hook error so wire's didn't run and thus the errors.

**Comment by wrefgtzweve** [comment]
Something was breaking the hookchain, external issue indeed. Thanks for checking out anyway!
