### ISSUE TITLE
[BUG] Serverside lua error: gmod_wire_expression2/init.lua:366: attempt to index field 'directives' (a nil value)

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/wire#2313]
Had the bug happen again, this time the game actually returned a proper stacktrace:
```
addons/wire/lua/entities/gmod_wire_expression2/init.lua:366: attempt to index field 'directives' (a nil value)
   0.  __index - [C]:-1
    1.  ResetContext - addons/wire/lua/entities/gmod_wire_expression2/init.lua:366
     2.  fn - addons/wire/lua/entities/gmod_wire_expression2/init.lua:693
      3.  unkown - addons/ulib/lua/ulib/shared/hook.lua:109
```

Happened twice within a minute, not sure how to reproduce as it's from server console.
Original issue: https://github.com/wiremod/wire/issues/2311

**Comment by thegrb93** [comment]
Had a hunch it might've been this, https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/init.lua#L693
