### ISSUE TITLE
FLIR broken rendering.

### ISSUE THREAD

**Issue by Hazeofdream** [wiremod/wire#2317]
Happened with the update #2308 

Causes holograms to be invisible, player's aren't rendered (Lights like the physgun glow are, however) Some vehicles/entities aren't rendered, either and is overall is extremely dark and ugly.

![image](https://user-images.githubusercontent.com/74027566/163667693-f1c364c9-b33a-44b0-a868-b50acbdd8f25.png)

**Comment by thegrb93** [comment]
It didn't look like that when I tested it. perhaps an addon is conflicting

**Comment by Hazeofdream** [comment]
> It didn't look like that when I tested it. perhaps an addon is conflicting

I haven't changed my addons since the last update for FLIR. This should not be the case.

**Comment by thegrb93** [comment]
It's probably conflicting with one since the last update

**Comment by Hazeofdream** [comment]
> It's probably conflicting with one since the last update

Do you mean that this flir is conflicting with the last flir? Just to confirm I joined my regular server in which this was taken with all my addons disabled and the result was the same.

**Comment by thegrb93** [comment]
It would be a problem of the server's addons, not your own.

**Comment by thegrb93** [comment]
@kerbalcadet any idea what it could be?

**Comment by kerbalcadet** [comment]
huh, I don't actually quite know. @Hazeofdream, just to make sure make a preset without any other addons. If you know any lua, the FLIR file is pretty simple. Feel free to DM me or what have you.

**Comment by thegrb93** [comment]
It's probably another addon conflicting with entity's RenderOverride

**Comment by thegrb93** [comment]
If it was working before, then something in https://github.com/wiremod/wire/commit/ce8531220f97bd171f58f6523d8ccb56be9bfda1 introduced the conflict

**Comment by Hazeofdream** [comment]
> It would be a problem of the server's addons, not your own.

Interestingly enough, I confirmed that other people of said server do not have that problem.


I did find this error however whenever FLIR was triggered.

`Requesting texture value from var "$basetexture" which is not a texture value (material: pp/bokehblur)
Requesting texture value from var "$depthtexture" which is not a texture value (material: pp/bokehblur)
Requesting texture value from var "$basetexture" which is not a texture value (material: pp/copy)
`

**Comment by Hazeofdream** [comment]
Even more odd, The FLIR actually works properly when I'm clipped inside the map!

![image](https://user-images.githubusercontent.com/74027566/164994033-ebf4dedf-61c7-400c-ba24-316505ba36ef.png)

**Comment by thegrb93** [comment]
Try verifying your gmod files

**Comment by Hazeofdream** [comment]
> Try verifying your gmod files

Found the problem, [https://github.com/wiremod/wire/commit/ce8531220f97bd171f58f6523d8ccb56be9bfda1]ce85312(url) causes flir to be broken if you disable the skybox with r_3dsky 0

**Comment by thegrb93** [comment]
Looking at the gmod wiki https://wiki.facepunch.com/gmod/GM:PostDrawOpaqueRenderables "In case of 2D skyboxes it is possible for this hook to always be called with this parameter set to true."

Then this line would be causing the issue https://github.com/wiremod/wire/blob/master/lua/wire/flir.lua#L103

**Comment by thegrb93** [comment]
@Hazeofdream @kerbalcadet could you guys see if its fixed now
