### ISSUE TITLE
how do i change text screen limit?

### ISSUE THREAD

**Issue by olej12** [wiremod/wire#2320]
so my friend and i are making a map and we have lots of text screens,we wanted to add more but i get error called "You've hit the WIre Text Screens Limit!" and its super annoying,so does anyone know how to change the limit of it?

**Comment by Divran** [comment]
The same way you change the limit of anything at all in gmod: with the `sbox_max` commands. You type `sbox_maxwire_` and it will autocomplete the rest.

Also note that this github repository is primarily a bug tracker, not a support forum. To get help with things that aren't bugs, the recommended way is to go to the discord <https://discord.gg/H8UKY3Y>
