### ISSUE TITLE
hydraulics issues

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#2322]
so using hydraulics in wiremod and saving a dupe 2 file with them the length of them is not persisted im using a consistent value for them right now and i have to un-wire length then re-wire them for the length  to change to what i originally had it set to. why is this an issue? there any plans for a fix?

**Comment by thegrb93** [comment]
This issue has indeed been around since the hydraulic was made. Should be an easy fix

**Comment by deathking61** [comment]
When will it be fixed?

**Comment by thegrb93** [comment]
Whenever https://github.com/wiremod/wire/pull/2325 gets merged

**Comment by deathking61** [comment]
well that doesnt help man this needs to be a fix sooner then later cause its getting tiresome to keep re doing them on dupe spawn
