### ISSUE TITLE
trying to make an e2 run runOnPlayerDisconnect(Number Activate) only when i leave server

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#2331]
so trying this: runOnPlayerDisconnect(Number Activate) and i wire it to a prop the prop just breaks i wanna know how to make this only work when i leave server thanks!

**Comment by deathking61** [comment]
im just trying to figure how to use this first i have the code its a simple
light code

**Comment by Divran** [comment]
This github is for bug reports. If you have questions that aren't about bugs, go to the discord at https://discord.gg/H8UKY3Y

**Comment by Divran** [comment]
Sorry, was a bit quick to close this. If this isn't a bug please go to the discord at <https://discord.gg/H8UKY3Y>, however we haven't been given enough information to do anything, much less know if what we have is a bug or not.
