### ISSUE TITLE
null entity

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#2336]
so when trying to wire up anything im getting 

[ERROR] lua/weapons/gmod_tool/stools/wire_adv.lua:268: attempt to index a nil value
  1. CachePorts - lua/weapons/gmod_tool/stools/wire_adv.lua:268
   2. GetPorts - lua/weapons/gmod_tool/stools/wire_adv.lua:291
    3. LoadMemorizedIndex - lua/weapons/gmod_tool/stools/wire_adv.lua:817
     4. Think - lua/weapons/gmod_tool/stools/wire_adv.lua:839
      5. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:161 (x6)

yet its when im trying to go from an input to an output and its making it hard to even use it.

**Comment by thegrb93** [comment]
You have a broken addon installed
