### ISSUE TITLE
[Error] Wire thruster causing lua errors

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/wire#2338]
Not sure how to replicate, server lua error

```
lua/includes/extensions/math.lua:52: bad argument #2 to 'max' (number expected, got nil)
   0.  unkown - [C]:-1
    1.  max - [C]:-1
     2.  Clamp - lua/includes/extensions/math.lua:52
      3.  clampForce - addons/wire/lua/wire/wireshared.lua:998
       4.  CalcForce - addons/wire/lua/entities/gmod_wire_thruster.lua:142
        5.  unkown - addons/wire/lua/entities/gmod_wire_thruster.lua:242
```

Happened quite frequently
![image](https://user-images.githubusercontent.com/69946827/172459859-5cb14df4-7bb8-49de-ad59-74c841d21f89.png)
![image](https://user-images.githubusercontent.com/69946827/172460978-ba4f4c71-01e8-4995-ab2b-688488e9994a.png)

**Comment by thegrb93** [comment]
You have another addon that errored InitPostEntity when the server started

**Comment by GamesArsenal96** [comment]
What was the addon?

**Comment by wrefgtzweve** [comment]
Not sure anymore, not that it matters as any addon that errors in the `InitPostEntity` can cause the same error. If you're getting this error check for startup errors on your server.
