### ISSUE TITLE
CPUs/OPS do not update after hitting limits

### ISSUE THREAD

**Issue by StrawWagen** [wiremod/wire#2339]
**Describe the bug**
When my e2 quotas, it shows the CPUs from the tick before the crash.
When I'm trying to diagnose a problem, it doesn't help when my e2 shows CPUs that can be half, or even a quarter of what they actually were.

**To Reproduce**
1. Make code that will crash the e2 in 1 tick.
2. Hover over e2.
3. E2 will be crashed, and have a CPU time / OPS of 0

**Expected behavior**
I expect that the e2 will show me actionable numbers.

**Screenshots**
![image](https://user-images.githubusercontent.com/64710817/172695753-3d9902e2-1010-47ef-8791-b2ec523bcc18.png)

![image](https://user-images.githubusercontent.com/64710817/172695777-3eae1726-4fdd-4a4a-bc06-6f3ea2d19173.png)

**Comment by thegrb93** [comment]
Need to break this code into its own function and have it also called with the "perf" error occurs https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/init.lua#L193-L207

**Comment by StrawWagen** [comment]
Still an issue! awaiting that fix!
