### ISSUE TITLE
gmod_wire_pod serverside error spam

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/wire#2341]
We've been getting this serverside error, im not sure how to replicate it. It's spamming a lot.
![image](https://user-images.githubusercontent.com/69946827/174391279-904db5d4-1ec4-4447-a08c-967c9c75534e.png)

```
addons/wire/lua/entities/gmod_wire_pod.lua:511: attempt to call method 'GetThirdPersonMode' (a nil value)
   0.  GetThirdPersonMode - [C]:-1
    1.  unkown - addons/wire/lua/entities/gmod_wire_pod.lua:511
```

**Comment by Divran** [comment]
That's a function added by gmod itself <https://wiki.facepunch.com/gmod/Vehicle:GetThirdPersonMode>.
The error message is saying this function doesn't exist. The only way that can happen is either
A) you have an old version of gmod installed, or
B) a different addon is breaking this in some way, either by preventing the function from being created or by deleting the function afterwards.

**Comment by wrefgtzweve** [comment]
It's being called on "pod" so if pod isn't valid or some form of other entity it will error like this.
https://github.com/wiremod/wire/blob/5fdeb01a1f3aa029bb6612ba12b19356773b14c4/lua/entities/gmod_wire_pod.lua#L511

We're using wire master and the latest version of gmod.

**Comment by Divran** [comment]
pod can't be invalid because of the HasPod check on the same line. It would probably error like this if you managed to link it to an entity that isn't a vehicle, since that function only exists on vehicles. However, that's not possible because the link function checks to make sure the entity is a vehicle before allowing you to link it.

**Comment by thegrb93** [comment]
It might be possible an addon overloaded IsVehicle for custom vehicles or something, and someone is trying to use a pod on them.

**Comment by Divran** [comment]
> It might be possible an addon overloaded IsVehicle for custom vehicles or something, and someone is trying to use a pod on them.

wouldn't that break like, everything
not just wiremod

**Comment by thegrb93** [comment]
Probably yeah lol

**Comment by thegrb93** [comment]
We'll need more info to fix this one I think
