### ISSUE TITLE
E2: `convar` raises false positives for "blocked commands", like "name"

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#2346]
`convar` uses the same validation function as `concmd`, which checks `IsConCommandBlocked`. For some convars, ie `name` (which is actually the example in the E2Helper description), **changing** it is blocked, but lua should be able to **get** the value.

Code references:
`convar` e2 function: https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/console.lua#L72

`IsConCommandBlocked` call: https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/console.lua#L45

Thanks to `@Nimeji` on Discord for finding this and verifying that you can actually get the value with lua.

**Comment by Vurv78** [comment]
Regression caused by https://github.com/wiremod/wire/pull/2281,
Need to split the validConCmd into separate ones for convar and concmd, can do it right now
