### ISSUE TITLE
POD Controller failing to capture user inputs and wire thrusters not functioning

### ISSUE THREAD

**Issue by ArsiTheFox** [wiremod/wire#2350]
I am having an issue where the POD controller is failing to capture any user-input while in seat

No Lua errors at all.
I have it linked to the seat and using the debugger to see all inputs and outputs but I get no interaction when in the seat or using the remote control tool

This is a weird issue because it is intermittent it works 1 tine then dies the next...

I bet it is a mod doing it but I can't find out what it can be

https://steamcommunity.com/sharedfiles/filedetails/?id=2822867933

These are all of my addons ^^^
Plus some manual addons like ACF-3 and ACF-3 Missiles.
Idk if anyone had this issue before and knows the addon it would be

Same issue as: https://github.com/wiremod/wire/issues/1674
From 2018

**Comment by thegrb93** [comment]
Disable half your addons and see if it fixes. If not, try the other half. You'll have to narrow it down yourself to find the broken addon.

**Comment by ArsiTheFox** [comment]
@thegrb93 Issue with that is.... this is a intermittent issue.... So it randomly happens from time to time I will see what I can find out

**Comment by Vurv78** [comment]
That is a lot of addons.. if you could reproduce this with <10 addons (or preferably none) can re-open this.
