### ISSUE TITLE
wirevalue crash

### ISSUE THREAD

**Issue by bewflast** [wiremod/wire#2351]
just check that dupe\
[pippiska.txt](https://github.com/wiremod/wire/files/9032995/pippiska.txt)

**Comment by bewflast** [comment]
freezes server till undo/cleanup

**Comment by thegrb93** [comment]
The problem is concat gates feeding back into each other

**Comment by thegrb93** [comment]
It's still very laggy but won't freeze it now. Can't do anything about laggy gates.

**Comment by thegrb93** [comment]
Other than lowering sbox_maxwire_gates

**Comment by bewflast** [comment]
ty 🦜
