### ISSUE TITLE
Multiple Issues within E2 Editor's Highlighting and Autocomplete

### ISSUE THREAD

**Issue by bellum128** [wiremod/wire#2353]
**Describe the bug**
Multiple major issues are occurring with the E2 editor, presumably as a result of #2237.

1. Autocomplete is no longer working, as no menu appears after typing say entity():s...
2. Syntax highlighting related to block comments appears to also no longer be working, particularly after editing the text within a block comment.

**To Reproduce**
1. Typing entity():s should result in autocomplete list
2. Block comments should function properly

There may be other unforeseen issues present from these changes as well.

**Comment by ghostserver10** [comment]
Agreed. Also
![First](https://user-images.githubusercontent.com/22061441/177060443-5ca99e26-aee0-45fb-905b-0bf21957a650.jpg)
![Second](https://user-images.githubusercontent.com/22061441/177060445-774239a2-17f0-4470-b217-c7d180bcfb9a.jpg)
d

**Comment by thegrb93** [comment]
@stepa2 could you investigate?

I'll revert after a week or two if it is still broken

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/issues/2354 needs to be solved too

**Comment by bellum128** [comment]
With the severity of these issues, it may be prudent to revert now and move the development of these enhancements to a separate branch for through testing since they affect so many pieces of the E2 editor, and I don't think that's something that can be fully resolved quickly. I have reverted my prod server to 2f5cf685b1dce80cd6d692c7aaf4e91cbe0294d6 in the meantime.

**Comment by bellum128** [comment]
@ghostserver10 I'd suggest reverting to commit  2f5cf685b1dce80cd6d692c7aaf4e91cbe0294d6 if it's urgent until the HEAD is fixed/reverted.

**Comment by thegrb93** [comment]
If it's getting this much attention then I'll revert it

**Comment by Fasteroid** [comment]
strings are broken for me too, pls revert until this is resolved

**Comment by ghostserver10** [comment]
But how? I downloaded wiremod through workshop. I'm not sure how to downgrade it

**Comment by Vurv78** [comment]
"Resolved" by revert
