### ISSUE TITLE
Error spam when trying to find the other end of ( or ), unsure if it affects [] or {}, needs more testing

### ISSUE THREAD

**Issue by 4naki** [wiremod/wire#2354]
Basicly this started happening out of nowhere, i was playing on a server and this weird error started spamming in "problems" tab
When trying to locate the other end of ( symbol, ")" it can't find it, it doesn't even mark the one i click in front of and spams an error message which causes lots of fps lag

Basicly to get get this error message i just clicked in front of ( symbol that does not have the other end

Clicking ( should mark it's other end if it exists, ")"

![clip](https://user-images.githubusercontent.com/50541143/177054845-99818d0c-9157-4764-bf42-ba0ae0137ed6.png)

In text:

[github_wire] addons/github_wire/lua/wire/client/text_editor/texteditor.lua:194: bad argument #1 to 'ipairs' (table expected, got boolean)
    1. ipairs - [C]:-1
        2. GetCharIndexByPos - addons/github_wire/lua/wire/client/text_editor/texteditor.lua:194
            3. CursorToCaret - addons/github_wire/lua/wire/client/text_editor/texteditor.lua:266
                4. unknown - addons/github_wire/lua/wire/client/text_editor/texteditor.lua:915

**Comment by Fasteroid** [comment]
Reproduced the lag, but I don't see the errors.

**Comment by Fasteroid** [comment]
This can probably be closed since #2357 "fixed" it.
