### ISSUE TITLE
Client Error on first EGP render

### ISSUE THREAD

**Issue by Duck375** [wiremod/wire#2359]
**Describe the bug**
Upon entering on map, when egp is rendered for the first time console throws a client error
Bug ocurs only on fresh start of Gmod, if server is restarted or changed level there will be no error
```
[Wiremod] render.PopFilterMin underflow!
  1. unknown - lua/entities/gmod_wire_egp/cl_init.lua:45
   2. xpcall - [C]:-1
    3. RenderToGPU - lua/wire/gpulib.lua:300
     4. _EGP_Update - lua/entities/gmod_wire_egp/cl_init.lua:25
      5. unknown - lua/entities/gmod_wire_egp/cl_init.lua:68


[Wiremod] render.PopFilterMag underflow!
  1. unknown - lua/entities/gmod_wire_egp/cl_init.lua:46
   2. xpcall - [C]:-1
    3. RenderToGPU - lua/wire/gpulib.lua:300
     4. _EGP_Update - lua/entities/gmod_wire_egp/cl_init.lua:25
      5. unknown - lua/entities/gmod_wire_egp/cl_init.lua:68

```

**To Reproduce**

0. Start Gmod
1. Load into any map
2. Place EGP Screen
3. Connect E2 to EGP
4. Refresh chip, to create objects
5. See error

**Video**
https://user-images.githubusercontent.com/58744956/177534666-843fc83a-396c-4f28-b537-6ec2c174d534.mp4

**E2 Chip**
[speedometer.txt](https://github.com/wiremod/wire/files/9054129/speedometer.txt)

**Comment by thegrb93** [comment]
The texture_filtering var is being changed but isn't pushing a filter so that's why.
