### ISSUE TITLE
Line 194 not exists or not cached

### ISSUE THREAD

**Issue by Opener974** [wiremod/wire#2365]
Since updating wiremod(July3), this bug emerged when i double click on the function at the first screenshot as you know.
i have no idea. help..

Line 194 not exists or not cached
[Wiremod] lua/wire/client/text_editor/texteditor.lua:153: bad argument #1 to 'ipairs' (table expected, got nil)
  1. ipairs - [C]:-1
   2. GetCharPosInLine - lua/wire/client/text_editor/texteditor.lua:153
    3. PaintHighlightedAreas - lua/wire/client/text_editor/texteditor.lua:812
     4. unknown - lua/wire/client/text_editor/texteditor.lua:932

![20220710105108_1](https://user-images.githubusercontent.com/96227852/178128327-dadaaafd-1f6a-4f04-8949-219c7bd45651.jpg)
![20220710105211_1](https://user-images.githubusercontent.com/96227852/178128332-88f4457e-4a2c-4fa3-8cd4-8d69aeab60e3.jpg)
![20220710105827_1](https://user-images.githubusercontent.com/96227852/178128356-4dbbe7c3-998e-45cb-9f77-08328b0379e1.jpg)

**Comment by thegrb93** [comment]
Try updating again, if that still doesn't resolve the issue then it might be due to @Vurv78 's https://github.com/wiremod/wire/pull/2344

**Comment by Vurv78** [comment]
GetCharPosInLine was added by the pr, they need to update.
https://github.com/wiremod/wire/blob/016b5f59a1d40fcf003b1c70d9f8b74ca59f7dfd/lua/wire/client/text_editor/texteditor.lua#L153

Plus my pr only changed 3 lines in a different file
https://github.com/wiremod/wire/blob/016b5f59a1d40fcf003b1c70d9f8b74ca59f7dfd/lua/wire/client/text_editor/modes/e2.lua#L345-L347
 
 which already mimic the above lines https://github.com/wiremod/wire/blob/016b5f59a1d40fcf003b1c70d9f8b74ca59f7dfd/lua/wire/client/text_editor/modes/e2.lua#L342-L343

**Comment by Vurv78** [comment]
Closing with the other issues since the changes that caused this were reverted.
