### ISSUE TITLE
"Allow Buttons" function in Pod Controller has bugs/glitches/problems

### ISSUE THREAD

**Issue by ShinexWipex** [wiremod/wire#2366]
Here's an example from my experience:

Let's say I simply wanted to build more realistic vehicle with my own buttons that I can press by using Left-Mouse-Button while using a chair/vehicle that is connected to that particular Pod Controller that has "Allow Buttons" activated. Be it a train, a plane, a car, or what have you.

So I wired "Allow Buttons" to "Activate" to the very same Pod Controller, and it all works great, and it seems to be working only with Left-Mouse Button (programmed like that?), but that's not an in itself of course.

Here's a problem - when I click my Left-Mouse button on a smaller prop that has an ability to be picked with E (use) button (while on foot) then then my First Person view gets broken and I can suddenly see my equipped weapon (phys gun for eg.), but with no player's hands for some reason, although I can still keep using these buttons.

Same happens if there's any Wheels in my reach, the Wheels just change their direction if Left-Mouse clicked (I don't think this should be happening).

Sometimes it could take bit more of Left-Mouse clicks for these bugs to happen, but it sure does happen every time. 

Keep in mind this is all happening when using a chair/vehicle (obviously).

From what I understand is that "Allow Button" acts as "E" (use) button.

I don't know if this is just me, or if I did some wiring mistakes, but I really like this feature, but there's no way I can enjoy it accordingly. For your information I'm using the lowest graphical settings too (laptop).

**Comment by thegrb93** [comment]
Sound like a mod conflict.

**Comment by ShinexWipex** [comment]
> Sound like a mod conflict.

Well, try it out by yourself and see how it goes. I can't guarantee anything though. But generally speaking I've never had any excessive or extravagant addons/mods.

**Comment by thegrb93** [comment]
`Same happens if there's any Wheels in my reach, the Wheels just change their direction if Left-Mouse clicked (I don't think this should be happening).`

This should happen because left click makes the player 'use' whatever they are aiming at.

**Comment by thegrb93** [comment]
The picking up props and breaking first person view though sounds like a mod issue. Might try it soon and see.

**Comment by Vurv78** [comment]
Yeah I can't reproduce anything with breaking first person view.

But for everything else I can since it is intended behavior. Not sure what you want us to do here, it is working as intended.
