### ISSUE TITLE
Cam Controller FOV doesn't work

### ISSUE THREAD

**Issue by Hazeofdream** [wiremod/wire#2369]
Happened in one of the recent commits, mainly after the ASCII support iirc, Many of my vehicles that utilize zooming within cam controllers (aka fov) do not seem to work any longer?

**Comment by thegrb93** [comment]
Hasn't been changed since last year. More likely it's a addon conflict.

**Comment by thegrb93** [comment]
Try it in singleplayer or something and make sure.

**Comment by thegrb93** [comment]
Works for me
