### ISSUE TITLE
typeid issue

### ISSUE THREAD

**Issue by Hazeofdream** [wiremod/wire#2375]
![image](https://user-images.githubusercontent.com/74027566/181877147-3ad51d2c-bef6-4562-bda1-a63b19828d5e.png)

This function causes the following error:

sv: Expression 2 (AH-1Z Viper): entities/gmod_wire_expression2/core/table.lua:333: attempt to index local 'typeids' (a nil value)

Not sure why this is happening and becoming an issue now? Had no previous issue with this

**Comment by StrawWagen** [comment]
Same here

**Comment by TheVayt** [comment]
It now breaks when you put table/array/gtable inside table() call, `table(table())`

**Comment by Vurv78** [comment]
Should be fixed.
Also fyi gtable is already not allowed inside of tables (Would error with ``@strict`` on)
