### ISSUE TITLE
Arrays cannot be filtered into rangerFilter arrays.

### ISSUE THREAD

**Issue by Hazeofdream** [wiremod/wire#2381]
![image](https://user-images.githubusercontent.com/74027566/182040797-1906eb89-ca9b-478b-9214-82909901047f.png)

I know arrays cannot be put into arrays but using it in such a way in something like rangerFilter worked previously as I assumed it separated them, Doesn't work anymore though.

**Comment by Vurv78** [comment]
It didn't. Creating an array/table with invalid types inside would just remove the type from it, as you can see in the old source:
```lua
e2function array array(...)
	local ret = {...}
	if (#ret == 0) then return {} end -- This is in place of the old "array()" function (now deleted because array(...) overwrote it)
	for k,v in pairs( ret ) do
		self.prf = self.prf + 1/3
		if (blocked_types[typeids[k]]) then ret[k] = nil end
	end
	return ret
end
```

You want to use ``r:add(r)`` (or whatever the function is called)


You can test this right now with tables with gtables inside them as I haven't made that a compile time error yet. (It is an error on ``@strict`` though)

**Comment by Divran** [comment]
You don't need to use `R:add(R)` for this case since ranger filters stack, you can just call it multiple times
```
rangerFilter(players())
rangerFilter(Hitbox)
rangerFilter(TopCover)
...
```
or, like you were doing before, but just separate the players
```
rangerFilter(array(HitBox,TopCover,...))
rangerFilter(players())
```
