### ISSUE TITLE
Holo's sticking around after player leaves and e2 is gone

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/wire#2384]
**Describe the bug**
Bit of a vague one.
Holos sometimes stick around after the player and e2 that owned them left.
Investigating it makes it hard as it rarely happens and the people that have done it did it unintentionally.
I haven't been able to reproduce this but it's quite annoying as people with larger holo's can clog up the map.

**To Reproduce**
None, i haven't been able to

**Expected behavior**
Holos should disappear, when the owner leaves.

**Comment by thegrb93** [comment]
There would probably be a lua error associated with it

**Comment by wrefgtzweve** [comment]
We log sv lua errors and i see no errors from wire around that timespan

**Comment by MorlandMoran** [comment]
Nothing of a bug, that's default behavior of negative index.

**Comment by thegrb93** [comment]
Holograms with negative index are supposed to be deleted when their chip is deleted.

One idea I have is https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua#L543 should be changed to math.floor

**Comment by thegrb93** [comment]
index should also be limited in size because huge index values will cause ipairs to not work.

**Comment by InfHorus** [comment]
> Holograms with negative index are supposed to be deleted when their chip is deleted.
> 
> One idea I have is https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua#L543 should be changed to math.floor

Literally never been the case and even Divran said in 2013 it is its default behaviour

**Comment by InfHorus** [comment]
> index should also be limited in size because huge index values will cause ipairs to not work.

Since when ipairs is limited by the size of the table? As long as the table is numeric and has no gap it will work

**Comment by thegrb93** [comment]
When chip is destroyed: https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua#L1271

https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua#L637-L642

**Comment by thegrb93** [comment]
> Since when ipairs is limited by the size of the table? As long as the table is numeric and has no gap it will work

No, try it for yourself

**Comment by thegrb93** [comment]
Gaps might also be the issue. This loop should be 'pairs' instead of 'ipairs' https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua#L640

**Comment by InfHorus** [comment]
> > Since when ipairs is limited by the size of the table? As long as the table is numeric and has no gap it will work
> 
> No, try it for yourself

Already did, my anti-cheat table has over 30k keys and it been working for years

**Comment by InfHorus** [comment]
> When chip is destroyed: https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua#L1271
> 
> https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua#L637-L642

https://github.com/wiremod/wire/issues/346#issuecomment-249372113

**Comment by thegrb93** [comment]
The code says otherwise

**Comment by thegrb93** [comment]
> Already did, my anti-cheat table has over 30k keys

I'm taking about index values of over 1e32..

**Comment by InfHorus** [comment]
> > Already did, my anti-cheat table has over 30k keys
> 
> I'm talking about index values of over 1e32..

From my phone I can't see where ipairs is used in a situation where it could receive a table that huge, I only see it used for the amt of holo and you're not going to spawn 1e32 homos afaik

**Comment by thegrb93** [comment]
It's whatever number the user wants to use for their holo index.

**Comment by Divran** [comment]
> Gaps might also be the issue. This loop should be 'pairs' instead of 'ipairs' https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua#L640

no, that line should be ipairs because negative indexes should not be deleted when the e2 is removed. they are shared holograms and should only be deleted when the user runs `holoDeleteAll`

of course this means it's possible for players to create holograms that never get cleared maliciously, but all I'm saying is that's the way it's intended to work

**Comment by Divran** [comment]
> The global holo's indices aren't stored in the table as negative so I think they were intended to be cleared.
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua#L545-L546

yeah I saw that and edited my previous message because of it

> How else do you remove them once the chip and player are gone? Does seem like an old bug.

with `holoDeleteAll`

**Comment by wrefgtzweve** [comment]
> of course this means it's possible for players to create holograms that never get cleared maliciously

Yeah that's kind of an issue and the reason i replaced it in the first place, eg. if someone clogs up the entire map in huge black holos and then just left you'd basically be fucked

**Comment by Divran** [comment]
> > of course this means it's possible for players to create holograms that never get cleared maliciously
> 
> Yeah that's kind of an issue and the reason i replaced it in the first place, eg. if someone clogs up the entire map in huge black holos and then just left you'd basically be fucked

if you're admin you can always do `wire_holograms_remove_all`

**Comment by wrefgtzweve** [comment]
You'd have to be online, possibly ruin other peoples dupes / stuff they're working on and would have to know that command exists in the first place.

**Comment by Divran** [comment]
anyway if this is a bug it's like over 15 years old at this point

**Comment by brandonsturgeon** [comment]
I think the best compromise here is just adding a convar to disable the global holo feature.

I'd be happy to add it, but I need help deciding what the functionality should be.

If the feature is disabled, what should happen when a player tries to create a global holo? An error message?

**Comment by thegrb93** [comment]
No, global holos are designed to be accessible from any E2, but still be deleted when the E2 is removed. The behavior of my PR is preferred.

**Comment by brandonsturgeon** [comment]
Great, I'm on board with that.
