### ISSUE TITLE
Cam Controller camera distance (zooming) not working properly while client side movement is ON

### ISSUE THREAD

**Issue by dobriyprop** [wiremod/wire#2402]
When client side movement is ON in Cam Controller changing camera distance (zooming) stop working properly. If client side zooming is enabled - scrolling with mouse wheel does nothing. If disabled - camera distance is not refreshing upon changing Distance input, only when disabling and enabling Cam Controller.

Steps to replicate:
1. Spawn Cam Controller with client side movement ON (optionally client side zooming ON)
2.
   a. If client side zooming is enabled - try to scroll while Cam Controller is activated
   b. If client side zooming is disabled - try to change Distance input while Cam Controller is activated

[2022-09-04_11-2.webm](https://user-images.githubusercontent.com/18686703/188305639-5184d1f9-e645-45d9-b480-f4296579fd7f.webm)

**Comment by thegrb93** [comment]
It does work, it's just barely noticeable until you scroll down for a while. I think whatever zoom math is being done needs to be reworked though.

**Comment by thegrb93** [comment]
What you really want is FOV. The clientside 'zoom' is actually just pushing/pulling the camera back/forward.

**Comment by dobriyprop** [comment]
I think i found the culprit. For some reason unknown number of wiremod updates ago "Smooth speed" value in Cam Controller settings reset itself to 0 and i didn't notice that. I never set it to 0. After i returned it to recommended range everything started to work again.

![изображение](https://user-images.githubusercontent.com/18686703/188372131-395ee063-f3ee-4f22-8d2c-ebc322d0f101.png)

> What you really want is FOV. The clientside 'zoom' is actually just pushing/pulling the camera back/forward.

Moving camera back/forward from specified position is exactly what i wanted.

> It does work, it's just barely noticeable until you scroll down for a while.

With client side zooming "ON" mode nothing worked until i fixed "Smooth speed" value. With client side zooming "OFF" change in distance was noticeable and correct only when i re-entered attached vehicle (seat), which was also fixed when i set a proper "Smooth speed" value.

> Or maybe it works in singleplayer and not multiplayer? I only tried in singleplayer.

Checked both in singleplayer and multiplayer on newly built contraptions and my previously built things which used those features.

**Comment by Divran** [comment]
seems like the only change that could be done in wiremod to help against this is to check if the smooth speed value is 0, and if it is, reset it to the default again
