### ISSUE TITLE
Weird bug with some of the e2s

### ISSUE THREAD

**Issue by 12121095** [wiremod/wire#2403]
### **Issue:**
 After switching to latest git branch and spawning an e2 (link is down below) started getting this issue. I've never had that problem before on workshop branch. There is no errors in e2, it errors after I spawn/refresh it.
sv: Expression 2 (Aviation instruments ver15): entities/gmod_wire_expression2/core/number.lua:99: attempt to perform arithmetic on a nil value

_**E2:**_
[aviation_instruments_ver15.txt](https://github.com/wiremod/wire/files/9484863/aviation_instruments_ver15.txt)

**Comment by Vurv78** [comment]
Would really appreciate if example chips for bugs could be narrowed down so we could actually try and reproduce it, I will try and do it myself, just saying for the future / anyone else seeing this.

**Comment by thegrb93** [comment]
I bisected the tree and found cbc01711 to be the cause

**Comment by Vurv78** [comment]
Thought so, I found other people were reporting weird behavior but also giving E2s with thousands of lines which don't help me much..

**Comment by Vurv78** [comment]
I've reproduced it:
```golo
for(I = 1, 2) { # Needs to iterate at least twice?
    switch (I) {
        default,
        break
    }
}

for(Other = 1, 1) {
    print("repro", Other) # Other is nil
}
```

Need to figure out a fix now, probably just unbalanced push/pop of scopes with switch :p

**Comment by Vurv78** [comment]
Probably gonna merge #2400 after this fix so this stuff doesn't happen again..
