### ISSUE TITLE
Replace luacheck with gluafixer/glualint

### ISSUE THREAD

**Issue by Vurv78** [wiremod/wire#2410]
Gluafixer is a linter for glua projects that I've used in a number of my projects, it's pretty neat and relatively easy to setup, see https://github.com/Vurv78/Expressive/blob/master/.github/workflows/linter.yml. There's also a [playground here](https://fptje.github.io/glualint-web/) and a [VSCode Extension here](https://github.com/Goz3rr/vscode-glualint)

### Benefits
* Easy setup to run on github actions (free CI, unlike travis)
* Made for the glua environment, so comes with globals/deprecated function lints
* Actively maintained

### Potential Downsides
* There's probably a buildup of hundreds of lints with the codebase being so huge
* (...)

I personally don't think we should be depending on native lua modules as they're much harder to setup and make use of, and not really supported in the gmod environment. I haven't even used luacheck myself at all, because setting up not just lua but luarocks on windows would actually drive me insane :p

I've opened this issue to invite discussion on whether this should be done, what styling should be enforced, etc. I feel like this would be a great first step to modernize the codebase

**Comment by brandonsturgeon** [comment]
FYI, GluaLint has a reusable workflow that other projects can use for this exact purpose https://github.com/FPtje/GLuaFixer/#reusable-workflow
