### ISSUE TITLE
No e2function to check if the effect:play(string) will exceed the burst limit

### ISSUE THREAD

**Issue by StrawWagen** [wiremod/wire#2411]
**Describe the bug**
No e2function to check if the effect:play(string) will exceed the burst limit

**To Reproduce**
Create e2 that :plays() multiple effects in one tick
Realize there is no convenient function to stop your e2 from erroring.
Cry

**Expected behavior**
I expected there to be an e2function that returns 0 when a new effect would exceed the burst limit

**Comment by Vurv78** [comment]
That is what [try catch](https://github.com/wiremod/wire/wiki/Expression-2-Syntax#exception-handling-new) is for, although yeah there really should be a function to see how many plays you have left

**Comment by StrawWagen** [comment]
Aah, alright. Thanks for the workaround.
