### ISSUE TITLE
Angle * Angle mishandling variables

### ISSUE THREAD

**Issue by StrawWagen** [wiremod/wire#2420]
**Describe the bug**
When multiplied an angle by another angle it returned this error
![image](https://user-images.githubusercontent.com/64710817/189470693-b4027dd8-ac29-43c0-a6ca-dddd3a7a1587.png)

https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/angle.lua#L143

**To Reproduce**
Create a Vector axis
Use :toAngle() on it
Multiply the product of that by an angle created with ang()

**Screenshots**
![image](https://user-images.githubusercontent.com/64710817/189470719-2834e71e-6e0e-4a57-911b-6181506841d8.png)

**Comment by InfHorus** [comment]
Same issue, can't spawn anything right now e2 is literally fully broken.

**Comment by Vurv78** [comment]
I don't think multiplication/division breaking for vector and angle qualifies as "literally fully broken", but it should be fixed now. Couldn't get on my pc for a while

**Comment by InfHorus** [comment]
Kinda does when all your creations are advanced stuff that uses those methods, anyway good that it is fixed.
