### ISSUE TITLE
Function exists in base gmod right now

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/wire#2440]
https://github.com/wiremod/wire/blob/962a94edd63a6da17323ff725834eee1f4abcc3d/lua/wire/wireshared.lua#L24
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/extensions/table.lua#L55-L61

`table.IsEmpty` in base gmod, is there any reason to keep this in wiremod?
I assume it was from before it existed in gmod, seems to be so as this function is 9 years old and gmods version is 4 years old

**Comment by thegrb93** [comment]
It can be removed

**Comment by Aws0mee** [comment]
> https://github.com/wiremod/wire/blob/962a94edd63a6da17323ff725834eee1f4abcc3d/lua/wire/wireshared.lua#L24
> 
> https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/extensions/table.lua#L55-L61
> 
> `table.IsEmpty` in base gmod, is there any reason to keep this in wiremod? I assume it was from before it existed in gmod, seems to be so as this function is 9 years old and gmods version is 4 years old

I'm not sure what you're talking about with the 9 year old/4 year old function stuff. However, if you look at the code for table.IsEmpty you will see it's the same thing. I personally don't see any need to change it since it's the same thing. Additionally, the way it is currently is likely faster by a tiny amount too.

**Comment by thegrb93** [comment]
He means table.IsEmpty used to not exist in gmod, but it does now, so wire doesn't need to define it anymore.

**Comment by Aws0mee** [comment]
> He means table.IsEmpty used to not exist in gmod, but it does now, so wire doesn't need to define it anymore.

Oh, I see now. I thought he was asking in the context that another function was using not next() == nil instead of table.IsEmpty, but I see now wire redefines it here.
