### ISSUE TITLE
[Suggestion] Allow more text in prints (chat/console)

### ISSUE THREAD

**Issue by KemGus** [wiremod/wire#2445]
Suggestion:
Add an ability to print more infinite amount of text into chat or console

Currently it does this amount of information only
![image](https://user-images.githubusercontent.com/42640259/194728487-fa3eac5e-e9f2-4c9e-8296-7ea223278465.png)

**Comment by thegrb93** [comment]
The gmod net library is limited so not possible. You have break up the message and send each piece yourself.

**Comment by KemGus** [comment]
So what about starfall? It has done it flawlessly

**Comment by KemGus** [comment]
It looks way better than e2 editor currently
