### ISSUE TITLE
[Suggestion] Improve E2 editor

### ISSUE THREAD

**Issue by KemGus** [wiremod/wire#2446]
1. High resolution for font (something what starfall has)
2. Any possibility of having warnings displayed as a list in the future, or at least have the ability to scroll through them somehow?
3. Add a way to just press on persist/input/trigger etc. and it will open a small menu where you can just put however amount of stuff in there
![image](https://user-images.githubusercontent.com/42640259/194769419-5a3f8a91-b19f-4ac9-871f-ff49a53bd779.png)

**Comment by Vurv78** [comment]
1. I never noticed a difference in font between this editor and starfall's fork, maybe I'm just blind

2. First step for warnings will just be to have them underline yellow, same as how editors like vscode do.
I could maybe have the validation bar expand into a larger menu with errors and warnings

3. Not sure what you mean by this?

**Comment by KemGus** [comment]
1. Just the quality overall. It feels like resolution of letters is low
2. I've seen a pr, so no more valid
3. So for example to make code look cleaner and instead of having this
@persist 1 2 3 4 5 6 7 8 9 10 11 12 13 14 
it would hide it and make it like a table that you open and you can see all of them.

**Comment by Divran** [comment]
having to open a separate menu to write code would just be worse

**Comment by KemGus** [comment]
or maybe it would just hide it and open

**Comment by CheezusChrust** [comment]
> 1. I never noticed a difference in font between this editor and starfall's fork, maybe I'm just blind

Looks like the font used in Starfall's editor is anti aliased while E2s isn't.
![image](https://user-images.githubusercontent.com/21130637/196056905-3b20c33d-7ef9-4887-a8e4-f8ad7d086739.png)
![image](https://user-images.githubusercontent.com/21130637/196056928-c2f6fa26-4816-4402-9d0c-1a92591c66e3.png)

Could we get an option to enable anti aliasing?

**Comment by Divran** [comment]
![image](https://user-images.githubusercontent.com/1485728/196060516-10f19313-d569-4300-ac13-2550257cbccc.png)

**Comment by Vurv78** [comment]
Resolved by #2453 and #2455.

Not going to do the third one
