### ISSUE TITLE
wire socket errors when spawend 

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#2447]
Error creating 'gmod_wire_socket' (Make sure the file is AddCSLuaFile'd and there aren't any errors!) (x6) this happens when the socket is spawned and the socket is invisable

**Comment by Vurv78** [comment]
I don't believe this is possible, unless two things afaik:
1. You don't have wiremod content downloaded (are you permitting downloads on multiplayer?) although idk if this should cause a lua error
2. The serverside gmod_wire_socket init is erroring as the message says, which in that case, you need to post the logs/console from the server file to give us the error.
