### ISSUE TITLE
I came back to building after a few months, I updated wire and everything is broken.

### ISSUE THREAD

**Issue by LightCat91** [wiremod/wire#2463]
I don't know what was changed, but 90% of my chips are now unusable. 10 years of building down the drain. I get warnings on many of them, but all my previous experience in coding with e2 is useless, I have no idea how to fix those problems. Is there a full in dept guide on how to convert the old chips to work with the new way or am I on my own?

Or, is there a way to get a legacy version of wire before the major changes so I can build my own stuff in sp as I was used to?

**Comment by Divran** [comment]
None of your old e2s should be broken by any changes we've made so it must be a bug, but we can't help you if you don't tell us what's wrong

**Comment by Divran** [comment]
Well there was one change recently which will probably have affected compatibility with third party extensions so that's the most likely culprit afaik

**Comment by thegrb93** [comment]
Probably the vector/angle change that this is supposed to fix https://github.com/wiremod/wire/pull/2462

**Comment by LightCat91** [comment]
All the holos E2 are broken completly with elements out of place or not moving, calculating speed the old way doesn't work, all other chips have many yellow warnings, some are easy to resolve by just using the new fucntions, but some I have no idea how to fix. I would have to check and fix thousands of E2s and hundreds of dupes, one by one... 

Is there no way to get a legacy version of E2 before the major changes?

**Comment by thegrb93** [comment]
Try the workshop version of wire.

**Comment by Vurv78** [comment]
> Try the workshop version of wire.

Workshop version is [pretty close to the latest github commit](https://github.com/wiremod/wire/commit/7dc9f10a570096e7a04e0df1c8c863baa1a33f3c), don't think that'll do much.

>  all other chips have many yellow warnings, some are easy to resolve by just using the new fucntions, but some I have no idea how to fix.

They're warnings. You don't *have* to fix them. They just warn you if you are relying on something which may lead to incorrect/weird behavior, or if there's a better way to do something.

**Comment by Vurv78** [comment]
Try with the latest commit @LightCat91

It should fix vector/angle from old dupes

**Comment by LightCat91** [comment]
> Try with the latest commit @LightCat91
> 
> It should fix vector/angle from old dupes

I was already using the latest commit

**Comment by thegrb93** [comment]
He means as of today

**Comment by Vurv78** [comment]
Going to assume fixed. You can comment here if it still doesn't work with the latest changes and I'll reopen this.
