### ISSUE TITLE
E2: Problem with local Dead

### ISSUE THREAD

**Issue by StrawWagen** [wiremod/wire#2481]
**Describe the bug**
Creating a local variable called Dead stops all code beyond it from being ran

**To Reproduce**
E2 that causes the problem for me.
```
@name 
@inputs 
@outputs 
@persist 
@trigger 

print( "Hello world!" )
local Dead = "lol"
print( "Goodbye world!" )

```

**Expected behavior**
Code beyond Dead should run. but it doesn't for me.

**Screenshots**
![image](https://user-images.githubusercontent.com/64710817/201436694-4db42a65-3e1e-4ea0-8744-8fd60057be38.png)
![image](https://user-images.githubusercontent.com/64710817/201436714-74c9ffb8-fa2c-4364-b6a2-e73127beb42b.png)

**Comment by wrefgtzweve** [comment]
Can confirm that this happens with the given code, using wiremod workshop.
![image](https://user-images.githubusercontent.com/69946827/201436987-14e63314-cbc3-470d-9658-7288c31f23d4.png)

**Comment by StrawWagen** [comment]
LOL

**Comment by brandonsturgeon** [comment]
This works if `Dead` is a global - only happens if it's local

**Comment by bigdogmat** [comment]
https://github.com/wiremod/wire/blob/aa988258401fe4e26c219ce778834ab1c6b6a4c0/lua/entities/gmod_wire_expression2/base/compiler.lua#L414

The unreachable code warning uses the scopes table. `Dead` needs to be in a non variable name index (e.g. _Dead, dead, 1, etc)

**Comment by Vurv78** [comment]
This is not critical, just need to make "Dead" lowercase. Only thing that this did was kill your code, might as well treat it as exit() since it'd have the same effect
