### ISSUE TITLE
Stuck on loading extensions

### ISSUE THREAD

**Issue by StrawWagen** [wiremod/wire#2487]
**Describe the bug**
The editor gets stuck on loading extensions.
Only in local server sessions.
And only on startup.

**To Reproduce**
Restart game.
Start a local server session.
Open the editor.

**Expected behavior**
I expect the editor to not get stuck on loading extensions lol.

**Comment by Vurv78** [comment]
A lot of things can cause that. Can you check the server / client console for anything?
