### ISSUE TITLE
Massive Errors on Duplicate containing radios

### ISSUE THREAD

**Issue by Duck375** [wiremod/wire#2491]
**Describe the bug**
When pasting/removing a duplication which contains multiple radios, that communicate once per tick (using gates) produces massive lua stack traces

**To Reproduce**
0. Download duplication ([radio_chat.txt](https://github.com/wiremod/wire/files/10047936/radio_chat.txt))
1. Paste duplication
2. Remove it
3. Paste it again
4. See errors
5. Remove it again
6. See some more errors

**Expected behavior**
No errors at all

**Lua stack traces**
[Paste.txt](https://github.com/wiremod/wire/files/10047939/Paste.txt)
[Remove.txt](https://github.com/wiremod/wire/files/10047940/Remove.txt)

**Comment by thegrb93** [comment]
Looks like a radio is failing to unregister. Looking into it

**Comment by thegrb93** [comment]
I figured it out, looks like the base wire code is causing inputs to trigger on wire entities that are being removed for whatever reason.
