### ISSUE TITLE
E2-Feature. Automatic spawn e2 once player is on server

### ISSUE THREAD

**Issue by KemGus** [wiremod/wire#2493]
**What's a use for it:**
For example, I have my TTS on and instead of me messing with my folders and trying to find the e2 I need, it would just spawn it automatically ( kinda what pac3 does once player is on server)

Ik you gotta be mad about safety issues but what prevents player from spawning the e2 after 20 seconds later once he found the e2?

**Comment by thegrb93** [comment]
just make a console command binding to do this

**Comment by Vurv78** [comment]
Yeah this doesn't really fit with wiremod at all, it can't be too much effort to just get the E2 out and paste it.
