### ISSUE TITLE
E2 Events unable to remember variables set outside of them

### ISSUE THREAD

**Issue by unknao** [wiremod/wire#2496]
The new E2 Events seem to forget variables set outside of them as if they aren't persisted.

![image](https://user-images.githubusercontent.com/24782457/204126029-d1aea953-6437-41bc-8264-3ea85add954d.png)
This example only prints 1 once and then proceeds to only print 0 afterwards.

**Comment by Vurv78** [comment]
Yes, you still need to persist them. They don't have upvalues / aren't lambda functions. This same behavior would happen with functions.

I had this conversation on the discord with divran, I could just disable the code that makes non-`@persist` variables persist anyways, and this would work as if it did have upvalues.

**Comment by unknao** [comment]
When i was testing it it didn't make any difference if it was using @output or @persist for the variable.

**Comment by Vurv78** [comment]
Yes, It should be fixed now.
