### ISSUE TITLE
E2 event keyPressed triggers mouse wheel inputs twice

### ISSUE THREAD

**Issue by unknao** [wiremod/wire#2502]
The E2 event keyPressed triggers any mouse wheel input twice a good 90% of the time.

**Comment by Vurv78** [comment]
Yes, because it triggers on up and down, you'll need to pick one to check for. Maybe I should separate it into `keyPressed` and `keyReleased` to be more clear.

**Comment by unknao** [comment]
It triggers both up and down twice from a single scroll action.

**Comment by unknao** [comment]
After some testing it seems to be a problem that comes from the PlayerButtonDown and PlayerButtonUp hooks by default even though the pod controller uses the same hook and doesn't have this problem.

**Comment by Vurv78** [comment]
Ah, it's a completely undocumented hook afaik so I had no idea :p

Couldn't even find info on it in the sandbox gamemode, dunno where it comes from
