### ISSUE TITLE
[Suggestion] EGP

### ISSUE THREAD

**Issue by KemGus** [wiremod/wire#2518]
1. Overhaul EGP (PLEASE PLEASE PLEASE)
2. Add curved lines in EGP
3. Touchscreen 
4. Named IDs 
5. Custom screen size(not based on prop, actual EGP screen)

PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE

**Comment by CornerPin** [comment]
2. This is possible with `xwl:egpLineStrip`.
3. Possible with `xwl:egpCursor` and `e:keyPressed`/`e:keyAttack1`.
4. Possible with tables, but it sill would be nice if EGP functions could support string IDs.
5. Possible with `xwl:egpResolution`.

**Comment by Vurv78** [comment]
`1`. Use the ZGPU or Starfall if you want any actual proper clientside screen.
In a perfect world I could give it the [WebAudio](https://github.com/Vurv78/WebAudio) treatment and make it super efficient with net and use the unreliable channel so you could get even faster frames, but I don't think I'll be doing that.

`3`. There's a User output on the EGP, just use that and do your own math on the objects.
`4`. Maybe this could be done alongside fixing the egp limit being based on ids <300.
`5`. `egpResolution` exists?

**Comment by Divran** [comment]
what does 1. even mean
4. in addition to tables, also possible with just variables `@persist MyNamedID` and `MyNamedID = 1` and `X:egpBox(MyNamedID,...)`

**Comment by KemGus** [comment]
Thanks for pointing out my mistakes!
