### ISSUE TITLE
[Suggestion] Remove annoying feature in E2 editor

### ISSUE THREAD

**Issue by KemGus** [wiremod/wire#2521]
Description:
Whenever you click before the variable and click tab, instead of indenting it, it switched between a table of co-existing variables with the same names.

Screenshot:
![image](https://user-images.githubusercontent.com/42640259/209553410-e308350a-bafc-46ed-899c-f45bc9d6d49e.png)

What can be done:
Make tab only work for identation, because user can switch those tabs by using arrow keys

**Comment by Divran** [comment]
You can already change the keybind for activating autocomplete in the options menu, including mouse only (so you still get the pop-up but you have to click it to activate it)

**Comment by KemGus** [comment]
This helped:
![image](https://user-images.githubusercontent.com/42640259/209557972-75cc51f6-b5c4-40db-b08e-823b8c7cbe32.png)
