### ISSUE TITLE
Wiremod turrets lua error and not showing GUI. Found on 02/01/2023

### ISSUE THREAD

**Issue by KURBY2023** [wiremod/wire#2524]
Yeah I kinda did something it fixed it but idk (ONLY BUGGED ON PISTOL)
**Please note: This issue tracker is for bug reports**
If your issue isn't a bug report, or if you are unsure whether it's a bug, please go to our discord channel instead at <https://discord.gg/H8UKY3Y>
If you are confident your issue is a bug, please fill in as much information as you can below.

**Describe the bug**
The bug is a Lua error I get when trying to use the turret and prevents me from trying to wire it to anything.

**To Reproduce**
For me.
1. Go to turret in wire.
2. Spawn it.
3. Gmod says wiremod is making lua errors.
4. See error in the lua error tab.

**Expected behavior**
I expected it to work like the video but it wouldn't let me wire it to anything and never showed any GUI when I put my crosshair over it with the wiring tool.

**Screenshots**
![20230102133025_1](https://user-images.githubusercontent.com/121806885/210238275-25dee9ee-6f0f-421f-a1f6-89dda5e17667.jpg)
![20230102133155_1](https://user-images.githubusercontent.com/121806885/210238277-0b28727a-f3b0-4dc0-af9a-e2020ffc01b0.jpg)
![20230102132702_1](https://user-images.githubusercontent.com/121806885/210238278-6aa40104-1831-4e58-9cdb-382d3edc74a1.jpg)
![20230102132713_1](https://user-images.githubusercontent.com/121806885/210238281-d692206d-8083-4b88-b8f4-294b4562d099.jpg)

Lua error is in screenshots. Please tell me if you need me to do any other things as I'm REALLY interested in the turrets.

**Comment by Vurv78** [comment]
Nothing to do with those 23 other problems?

Try without any addons

**Comment by KURBY2023** [comment]
Yes.
And it was my VR mods.
![image](https://user-images.githubusercontent.com/121806885/212470113-a0dd1f73-4b5a-4c97-bfa8-55d3bbb105bf.png)
Oh, and the pistol was the only broken one.
