### ISSUE TITLE
Wire Hydraulic Controller Doesn't Dupe

### ISSUE THREAD

**Issue by shadowscion** [wiremod/wire#2528]
**Describe the bug**
When a wire hydraulic is created between two props, and then copied with advdupe2 (NOT area copy), depending on what you right clicked, either the two props get copied, or the controller get copied, but not all three. 

**To Reproduce**
1. Create a wire hydraulic constraint
2. Right click on one of the props with advdupe2 tool
3. Paste the result

**Expected behavior**
If you copied the props, the controller will not have been included, and there should be an error (Failed to create WireHydraulic Constraint).

**Comment by thegrb93** [comment]
Applies to any wire entity that does linking as well
