### ISSUE TITLE
Abusive bug: `gmod_wire_friendslist` spawning world ents

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/wire#2529]
```
lua/entities/gmod_wire_friendslist.lua:100: attempt to get length of local 'r' (a number value)
   1.  __len - [C]:-1
    2.  isInArray - lua/entities/gmod_wire_friendslist.lua:100
     3.  checkSingle - lua/entities/gmod_wire_friendslist.lua:121
      4.  UpdateOutputs - lua/entities/gmod_wire_friendslist.lua:211
       5.  Connected - lua/entities/gmod_wire_friendslist.lua:77
        6.  UpdateFriendslist - lua/entities/gmod_wire_friendslist.lua:63
         7.  Setup - lua/entities/gmod_wire_friendslist.lua:45
          8.  MakeWireEnt - lua/wire/server/wirelib.lua:1015
           9.  MakeEnt - lua/wire/tool_loader.lua:65
            10.  LeftClick_Make - lua/wire/tool_loader.lua:56
             11.  LeftClick - lua/wire/tool_loader.lua:37
              12.  unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:220
```

Somehow players are able to spawn `gmod_wire_friendslist` that error when they're spawned resulting in them being registered as world entities bypassing propprotection limits.

![image](https://user-images.githubusercontent.com/69946827/212434716-976ce63d-ae9f-48ee-bba6-47c18f617526.png)
![image](https://user-images.githubusercontent.com/69946827/212434738-2bc87ca3-e664-4b2f-ac5b-f3d06a6a1c5e.png)

When a player has no friends they'll return a number instead, friendslist does not account for this and instead errors and makes a world entity.

As can be seen here, isInArray does not account for it and errors, seems like isInArray might not work at all as `ply` is never passed https://github.com/wiremod/wire/blob/27d7e5536dfa54dd32fb4d50824e8e4a07f2ee0c/lua/entities/gmod_wire_friendslist.lua#L98
![image](https://user-images.githubusercontent.com/69946827/212434875-725f9648-4d54-44a8-b829-c256ea7fa6f7.png)

**Comment by Divran** [comment]
that should fix it, please test it on an actual server with actual cppi friends and let me know how it went

**Comment by wrefgtzweve** [comment]
Took a while to test sorry for that, works now. Thanks!
