### ISSUE TITLE
Seemingly random "attempt to index field 'context'"

### ISSUE THREAD

**Issue by brandonsturgeon** [wiremod/wire#2530]
```
L 01/14/2023 - 04:21:30: Lua Error:
[wire] addons/wire/lua/entities/gmod_wire_expression2/init.lua:281: attempt to index field 'context' (a nil value)
  1. unknown - addons/wire/lua/entities/gmod_wire_expression2/init.lua:281
```

This happens with random manually-spawned E2s?

I only see this error happening after https://github.com/wiremod/wire/commit/27d7e5536dfa54dd32fb4d50824e8e4a07f2ee0c
Maybe something in there tries to run Think before `self.context` is set up?

cc @Aws0mee because you already have context on this portion of the code 👍

**Comment by Aws0mee** [comment]
Hmm, I don't recall getting this in my testing. I'll take a look.

**Comment by Aws0mee** [comment]
I see now, I'm not sure why these errors happen exactly, but I see how to fix it.

**Comment by Aws0mee** [comment]
PR opened, thanks for pointing that out. @brandonsturgeon
