### ISSUE TITLE
Wire Hydraulic Controller - TriggerInput varible leak

### ISSUE THREAD

**Issue by klen-list** [wiremod/wire#2534]
`ENT:TriggerInput` cause varible `_` leak into global table as number
https://github.com/wiremod/wire/blob/3888c5931b4a5a10f24544268c7e826e45e52480/lua/entities/gmod_wire_hydraulic.lua#L120
https://github.com/wiremod/wire/blob/3888c5931b4a5a10f24544268c7e826e45e52480/lua/entities/gmod_wire_hydraulic.lua#L128

**Comment by klen-list** [comment]
This cause other addon erroring
![image](https://user-images.githubusercontent.com/49125075/215577319-bdc13460-6784-4541-a50f-1df5b97486f1.png)
`includes/modules/hook.lua:239: attempt to index local 'gm' (a number value)`

**Comment by thegrb93** [comment]
I think that addon should be using 'nil' instead or something similar? No idea why it would use global '_'.
