### ISSUE TITLE
Setname function not working on props

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#2541]
So i tried making a code and that in itself works but using E:setname() (and E is defined at and input as E:entity but it doesnt wanna work loke that unless its the e2 itself doing it. When can this get fixed?

**Comment by thegrb93** [comment]
setname is to set the E2's name I think

**Comment by deathking61** [comment]
There needs to be one for props and things like that it could be useful.

**Comment by Divran** [comment]
setname can set the name of the e2 entity itself, or other wiremod entities. This changes one of the labels that show up in the tooltip when you aim at the entity. Props don't even have tooltips in the first place so even if it could target props it wouldn't do anything, and adding a tooltip to every single prop would be extremely annoying. Your screen would just be filled with tooltips everywhere you looked.

**Comment by thegrb93** [comment]
My guess is they want it for the ents.FindByName function or for source engine i/o stuff. Having access to that would probably not be a good idea.

**Comment by deathking61** [comment]
I understand it i do im just saying if you wanted to use it for some things
thats all lol
