### ISSUE TITLE
E2Lib issues

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#2543]
[wire-master] addons/wire-master/lua/wire/stools/expression2.lua:718: attempt to index global 'E2Lib' (a nil value)
  1. Expression2Upload - addons/wire-master/lua/wire/stools/expression2.lua:718
   2. func - addons/wire-master/lua/wire/stools/expression2.lua:748
    3. unknown - lua/includes/extensions/net.lua:33

**Comment by deathking61** [comment]
when i try to spawn ANY e2 in singleplayer this issue pops up and its been going on for sometime (new wiremod )

**Comment by Vurv78** [comment]
Feel free to elaborate. This is impossible without an addon conflict or something seriously wrong with your install, so.
