### ISSUE TITLE
runOnChat(1) function not working 

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#2547]
it bugs out despite it being on the server and enabled! (server owner says wire is up to date) 

**To Reproduce**
1. Go to a server with wiremod (no idea if its all of the servers or just some) 
2. Click on expression2 
3. try to use runonchat()
4. See error: Warning (1/1): Use of deprecated function: runOnChat(number): 'use the chat event instead'

**Expected behavior**
supposed to be able to use chat to do commands 
instead it bugs out.

**Comment by Divran** [comment]
A warning is not an error, it doesn't stop you from using it

**Comment by Vurv78** [comment]
are people just incapable of reading
