### ISSUE TITLE
creating holos with the updates wiremod addon isnt working fully

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#2548]
so using something like this: 

  #Key Buttons

  holoCreate(hash("2"),E:toWorld(vec(0.5,0,0)*Size),MODEL_SCALE*Size,E:toWorld(ang(0,0,0)),BUTTON_COLOR,MODEL)
 

mind you the # was because i have them commented out anyways the new wiremod is freaking out with whatever you guys have decided to "update" 

tried to upload the picture and your site wont allow it. so here is a link: https://ibb.co/d4QGM1s

**Comment by Vurv78** [comment]
A picture does not help at all. Please send a code snippet in the future. 

The hologram code that would cause something like this has not been changed in years. Feel free to post the code but assuming this is a user error.

**Comment by deathking61** [comment]
We got it working without the issues. Thank you for the reply
