### ISSUE TITLE
wirelink:egpPos(n,v2) works incorrectly when used on egpLine()

### ISSUE THREAD

**Issue by 4naki** [wiremod/wire#2553]
Basicly when one tries to use egpPos(number index, vector2 pos) on an egpLine, it moves the starting end of the line instead of the whole thing

Link your egp v3 hud to your e2
Put wirelink:egpLine(number index, vector2 pos1, vector2 pos2) in your if first statement
Next put wirelink:egpPos(number index, vector2 pos) under it
upload and exit

**Expected behavior**
Expected line to move to said position

**Screenshots**

Code screenshot
![code](https://user-images.githubusercontent.com/50541143/227005201-614b9a23-eeb6-44fe-9b9c-5fb546bdab2c.PNG)

Expected behavior screenshot
![expected behavior](https://user-images.githubusercontent.com/50541143/227005363-e7953c86-f3e5-4f9a-bd42-146585523656.PNG)

Result screenshot
![result](https://user-images.githubusercontent.com/50541143/227005460-d312d631-cea4-4ff7-8978-b06e5485577d.PNG)

**Comment by 4naki** [comment]
If this gets fixed, wirelink:egpPos(n,v2,v2) should be added for moving both ends separately

**Comment by Denneisk** [comment]
Fixed in #2646
