### ISSUE TITLE
Wire RT screens spamming errors

### ISSUE THREAD

**Issue by KekkyShmekky** [wiremod/wire#2561]
**Please note: This issue tracker is for bug reports**
If your issue isn't a bug report, or if you are unsure whether it's a bug, please go to our discord channel instead at <https://discord.gg/H8UKY3Y>
If you are confident your issue is a bug, please fill in as much information as you can below.

**Describe the bug**

```
[ERROR] lua/entities/gmod_wire_rt_screen.lua:234: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. DrawScreen - lua/entities/gmod_wire_rt_screen.lua:234
    3. unknown - lua/entities/gmod_wire_rt_screen.lua:306
```

**To Reproduce**
Spawn a Wire RT screen.

**Expected behavior**

Obviously for that error not to spam.

**Screenshots**
N/A

**Comment by Denneisk** [comment]
Can't reproduce. Most likely a version mismatch.
New:
https://github.com/wiremod/wire/blob/c0157596a58d63a40c2e8d8b91efa2e045824ef2/lua/entities/gmod_wire_rt_screen.lua#L234
https://github.com/wiremod/wire/blob/c0157596a58d63a40c2e8d8b91efa2e045824ef2/lua/entities/gmod_wire_rt_screen.lua#L306
Old:
https://github.com/wiremod/wire/blob/962a94edd63a6da17323ff725834eee1f4abcc3d/lua/entities/gmod_wire_rt_screen.lua#L234
https://github.com/wiremod/wire/blob/962a94edd63a6da17323ff725834eee1f4abcc3d/lua/entities/gmod_wire_rt_screen.lua#L306

**Comment by thegrb93** [comment]
Try updating

**Comment by Vurv78** [comment]
Closing since no response from author, can reopen if you can respond and reproduce this.
