### ISSUE TITLE
Adding a boolean type for wire IO

### ISSUE THREAD

**Issue by The17thDoctor** [wiremod/wire#2562]
**Describe the suggestion**
I think it would be great to have boolean IO type for wire entities. It would allow for strict behaviour on how ON/OFF states can be handled in many many entities.

No more having multiple behaviours dependent on how the owner of the entity codes the logic.
(e.g: Should 0.1 be considered ON ? ; Should -1 be considered ON ? ; etc.)

Booleans would give an actual answer to this, there's no way to not be sure, its ON or OFF.

**Comment by thegrb93** [comment]
It's 0=off anything-else=on. Not that complicated. Booleans would introduce the need for typechecking stuff.
