### ISSUE TITLE
Suppress Warnings

### ISSUE THREAD

**Issue by Denneisk** [wiremod/wire#2572]
## Description
A feature to suppress a single or multiple warnings. Allows projects to ignore intentional bad practice while still allowing warnings for other parts of code. Errors would still appear regardless of warning suppression.

## Possible Implementations
```golo
# In this context, #suppress is a command like #ifdef
#suppress
    runOnTick(1) # Will not cause a warning
#endsuppress
    runOnLast(1) # Will still warn
```
Alternatively,
```golo
#No warnings would be generated in this code
@persist A B
@suppress deprecated unused_global use_before_initialization 
runOnTick(1)
if(B){}
```

**Comment by Vurv78** [comment]
Second one would be a massive amount of work since you'd need to store all the warning types with ids to block those.

Only one I could agree with is if there was a single command to ignore a line, ala `@ts-ignore`. If you allow suppress blocks, people are just gonna wrap their entire chips with them..

**Comment by Denneisk** [comment]
You are not wrong but in the case of the following code, the warning should not occur. I'll concede when a `first()` event is implemented.
```golo
@persist A
if (clk())
{
    print(A) # Warning: Use of variable [A] before initialization
}
elseif (first())
{
    A = 0
    interval(100)
}
```

**Comment by Vurv78** [comment]
First event won't happen because.. that's just the top of the chip. I did address this in the PR, this is the only legitimate issue. And there's nothing you can really do about it.

Having first under the clks is a micro-optimization anyway, and makes the code flow hard to read
