### ISSUE TITLE
Turret there are no some settings in multiplayer 

### ISSUE THREAD

**Issue by Dambra4** [wiremod/wire#2592]
playing sandbox in singleplayer , in turret :   there is a parameter : bullets per shot, Tracer every x bullets.
But if i change to multiplayer (2 players, 4 players...)   They disappear

**Comment by thegrb93** [comment]
There's some multiplayer limits imposed. I think they should be removed and replaced with cvars.

https://github.com/wiremod/wire/blob/master/lua/wire/stools/turret.lua#L97-L102
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_turret.lua#L117-L119
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_turret.lua#L123-L125
