### ISSUE TITLE
Cvar to Toggle Overlay

### ISSUE THREAD

**Issue by Denneisk** [wiremod/wire#2613]
**Description:**
Add a cvar that enables/disables the overlay, enabled by default. Possibly have the overlay still appear when the toolgun/wire stool is out.

**Purpose:**
Allows users to not have to see the overlay pop up whenever they glance over a Wire entity, which can be a bit distracting if the user doesn't need to see it (i.e., not intending to modify the contraption).

**Comment by thegrb93** [comment]
Theres a gmod cvar that does this for all entities iirc.

**Comment by thegrb93** [comment]
I think the toggle for it is also in the context menu

**Comment by Denneisk** [comment]
> I think the toggle for it is also in the context menu

Tried a few of those toggles but none seemed to disable them.

**Comment by thegrb93** [comment]
Maybe the same check that gmod_base_entity uses needs to be added to wire.
