### ISSUE TITLE
Remove term "bytes" from memory

### ISSUE THREAD

**Issue by Denneisk** [wiremod/wire#2618]
Have references to the term "byte" replaced with a different terminology. It's misleading in almost every place it's used.

Possible alternatives:
- Numbers (N, KN)
- Words (W, KW)
- Doubles (D, KD)
- Values (V, KV)
- Block (B, KB)

True byte values can still be displayed, but they should be accurate, which, [according to Garry](https://wiki.facepunch.com/gmod/number), means they must be a multiple of 8.

**Comment by thegrb93** [comment]
number is the best term

**Comment by thegrb93** [comment]
'block' is a good one too.

**Comment by Denneisk** [comment]
Perhaps a poll could be done to see what users prefer most.

**Comment by Vurv78** [comment]
Superceded by #2636
