### ISSUE TITLE
EGP Hud method/function to determine which players have the hud open.

### ISSUE THREAD

**Issue by LoneCuriosity** [wiremod/wire#2620]
Hello I was recently messing with EGP huds and noticed there is no method like runonx for when a user connects or disconnects from a hud. My suggestion is to add such a runon method or event to be able to know when a new user connects or disconnects from a hud.

Sample functions/methods
- runonhud - runon method
- hudconnectclk - ran every time a player connects to the hud
- hudclkply - the player who connected to the hud or disconnected
- huddisconnectclk - ran every time a player disconnects to the hud
- hudplayers - returns an array with all the players that have the hud open

All the functions/methods above should be able to take in a wirelink instance to allow for multiple different huds to be checked.

**Comment by Denneisk** [comment]
Will cover this. Already had half of it done, just need to make an event for connecting. Probably a generic `egpHudConnect(EGP:wirelink, Player:entity, Connected:number)`.
