### ISSUE TITLE
Add native damage detecting events to E2

### ISSUE THREAD

**Issue by DecVes** [wiremod/wire#2623]
im requesting to add a damage event so if the e2 or a prop takes damage the damage event acts like a wire damage detector. im creating a big project and need something like this so it can be done (its a prop damage system but with no addons)
like damagecore

`#somehing like this`

`if(Prop:damage <= 45)`
`{`
`#do something`
`}`

`#or in my case`

`if(Prop:iswelded)`
`{`
 `     if(Prop:damaged  == 1)#you can changed damage to damaged or whatever you would like`
   `   {`
    `          #do something`
`      }`
`}`

`#if you do decide to add this please make it so it can be effected by explosions, bullets, physics props being thrown at it, etc`

**Comment by Vurv78** [comment]
```
event entityTakeDamage(Ent:entity, Dmg:damage) {}
```
or 
```
event entityDamage(Ent:entity, Dmg:damage) {}
```

?

And will need to create a `damage` type for CTakeDamageInfo.

**Comment by DecVes** [comment]
> ```
> event entityTakeDamage(Ent:entity, Dmg:damage) {}
> ```
> 
> or
> 
> ```
> event entityDamage(Ent:entity, Dmg:damage) {}
> ```
> 
> ?
> 
> And will need to create a `damage` type for CTakeDamageInfo.

how would i go about creating Ctakedamageinfo idk what that is

wdym and n

**Comment by Vurv78** [comment]
I'm just going over how someone should implement this if someone happens to get to it before I do
