### ISSUE TITLE
Internal error - lua/entities/gmod_wire_expression2/base/compiler.lua:606: attempt to index local 'rt' (a nil value)

### ISSUE THREAD

**Issue by Hetzer1913** [wiremod/wire#2664]
**Describe the bug**
Internal error - please report to https://github.com/wiremod/wire/issues
lua/entities/gmod_wire_expression2/base/compiler.lua:606: attempt to index local 'rt' (a nil value)

Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 316	"__index"		lua/entities/gmod_wire_expression2/core/e2lib.lua
	3: Line 606	"CallInstruction"		lua/entities/gmod_wire_expression2/base/compiler.lua
	4: Line 219	"EvaluateStatement"		lua/entities/gmod_wire_expression2/base/compiler.lua
	5: Line 229	"Evaluate"		lua/entities/gmod_wire_expression2/base/compiler.lua
	6: Line 661	"CallInstruction"		lua/entities/gmod_wire_expression2/base/compiler.lua
	7: Line 219	"EvaluateStatement"		lua/entities/gmod_wire_expression2/base/compiler.lua
	8: Line 423	"CallInstruction"		lua/entities/gmod_wire_expression2/base/compiler.lua
	9: Line 94	"nil"		lua/entities/gmod_wire_expression2/base/compiler.lua
	10: C function	"xpcall"
	11: Line 33	"Execute"		lua/entities/gmod_wire_expression2/base/compiler.lua
	12: Line 75	"wire_expression2_validate"		lua/entities/gmod_wire_expression2/cl_init.lua
	13: Line 1657	"Validate"		lua/wire/client/text_editor/wire_expression2_editor.lua
	14: Line 902	"OnMousePressed"		lua/wire/client/text_editor/wire_expression2_editor.lua
	15: Line 151	"nil"		lua/wire/client/text_editor/issue_viewer.lua

**To Reproduce**
if i make a mistake in my code, the debug bar goes red and says "Internal error, see console for more details" and then the above is spammed in console

**Expected behavior**
I expected to be told what i got wrong in my code

**Screenshots**
Not Required

**Comment by Vurv78** [comment]
You need to provide some code

**Comment by Hetzer1913** [comment]
> You need to provide some code to reproduce this

no i don't, i don't get feedback from the debug bar at the bottom, i just get this message every single time i get something wrong with the code. whenever the debugging bar goes red, it say "Internal error, see console for more details"

if you want to reproduce it, then simply make an mistake while writing code.

**Comment by Vurv78** [comment]
>no i don't, i don't get feedback from the debug bar at the bottom, i just get this message every single time i get something wrong with the code. whenever the debugging bar goes red, it say "Internal error, see console for more details"
>
> if you want to reproduce it, then simply make any mistake while writing code.

I'm sorry but your assumption that just E2 happens to be entirely broken and nobody reported it until now is wrong.

This is likely a server/addon conflict and you need to provide some code / extensions that are on the server to reproduce this.
