### ISSUE TITLE
E2 array:count() broken on non-sequential arrays

### ISSUE THREAD

**Issue by Denneisk** [wiremod/wire#2674]
`array:count()` will return an incorrect value for arrays that have non-sequential elements.

```php
print(array(100 = 100, 200 = 200):count()) # prints 0
```

**Expected behavior:**
Prints 2.

**Comment by Vurv78** [comment]
Believe sparse arrays are undefined behavior.

I'm personally against supporting them

**Comment by Vurv78** [comment]
Unless you want to make an rfc to completely change how arrays should be treated, I don't think this should happen.
Would make them much slower too
