### ISSUE TITLE
All wire screens erroring

### ISSUE THREAD

**Issue by Exotic0015** [wiremod/wire#2680]
**Describe the bug**
After the removal of ZASM all screens stopped working.

**To Reproduce**
Spawn any screen, for example EGP Screen, Digital Screen, Screen etc.

**Expected behavior**
Screen entity works normally.

**Screenshots**
![Screenshot_20230712_175314](https://github.com/wiremod/wire/assets/26276775/8f101090-86d6-4b90-8235-c509fc050e8c)

**Comment by Vurv78** [comment]
Fixed by https://github.com/wiremod/wire/commit/6e2aba39f4f583488c070bb6f073d219110c4cd6
