### ISSUE TITLE
using the wire tool

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#2682]
**Describe the bug**
spamming console with 

[wire-master] addons/wire-master/lua/weapons/gmod_tool/stools/wire_adv.lua:937: attempt to index local 'input' (a nil value)
  1. getName - addons/wire-master/lua/weapons/gmod_tool/stools/wire_adv.lua:937
   2. getWidthHeight - addons/wire-master/lua/weapons/gmod_tool/stools/wire_adv.lua:947
    3. DrawHUD - addons/wire-master/lua/weapons/gmod_tool/stools/wire_adv.lua:1131
     4. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua:54 (x30)

**To Reproduce**
just go into a game and then select wire it spams that error 

**Expected behavior**
expected no errors like this in console

**Screenshots**
![wireerror](https://github.com/wiremod/wire/assets/20668816/e643c02a-f2c2-4e19-87fb-ec6797768635)

**Comment by Vurv78** [comment]
Lot of his issues seem to be server specific / addon conflicts: https://github.com/wiremod/wire/issues?q=is%3Aissue+author%3Adeathking61+is%3Aclosed

**Comment by deathking61** [comment]
i think this is the workshop verson of wire.
