### ISSUE TITLE
using a variable as an index in table() causes a compile error.

### ISSUE THREAD

**Issue by hounddogie** [wiremod/wire#2696]
**Please note: This issue tracker is for bug reports**
If your issue isn't a bug report, or if you are unsure whether it's a bug, please go to our discord channel instead at <https://discord.gg/H8UKY3Y>
If you are confident your issue is a bug, please fill in as much information as you can below.

**Describe the bug**
when constructing a table, variables as the index will cause a compie error

**To Reproduce**

@name table sanity check 
@inputs 
@outputs 
@persist Tangle:table
@trigger 
Strang = "stri"
Tangle = table(Strang=69) #WTF 

![image](https://github.com/wiremod/wire/assets/85585283/080fb652-bf82-420a-ba57-5363c6f475c3)

**Expected behavior**
A compile error should not occur.

**Comment by Vurv78** [comment]
Reported to me previously and fixed in the new compiler PR, using this as a tracking issue to close.

(Also could move the parsing test to be a regression test)
