### ISSUE TITLE
Warning system does not consider preprocessing.

### ISSUE THREAD

**Issue by Hazeofdream** [wiremod/wire#2707]
![image](https://github.com/wiremod/wire/assets/74027566/72fa0f28-2aca-4b22-b05f-750b972c1af7)

PreProcessing has undefined functions listed as basically nonexistent, although this is recognized by the processor and therefore discarded, warning still takes note of this.

**Comment by Hazeofdream** [comment]
probably intentional, but having to wrap your entire event around a define instead of taking action based on a specific function is rather UNPLEASENT

**Comment by Vurv78** [comment]
The preprocessor does what it says. It just preprocesses to remove the unused branches of ifdefs. So there's no way for this to be possible. And I'm not entirely sure what you're trying to say since you haven't provided a specific warning that this is flagging.
