### ISSUE TITLE
Optimizer does not maintain scoping in case of if(1)

### ISSUE THREAD

**Issue by foul11** [wiremod/wire#2713]
```lua
local X = 1

if (1) {
    local X = X + 1
    print(X) -- printed '2'
}

print(X) -- printed '2'
```

```lua
local X = 1

if (X) {
    local X = X + 1
    print(X) -- printed '2'
}

print(X) -- printed '1'
```

**Comment by Vurv78** [comment]
Probably thanks to the optimizer, which is being removed in #2555, considering the bottom one works but the top doesn't.

**Comment by Vurv78** [comment]
Yeah this is already a test in the new compiler. So this is fixed by it.

https://github.com/wiremod/wire/blob/150e6c4e40fb0b6e038b9335e84e35f465ef9d8e/data/expression2/tests/runtime/base/scoping.txt#L3-L10
