### ISSUE TITLE
ZCPU, GPU etc are missing

### ISSUE THREAD

**Issue by Mer08** [wiremod/wire#2744]
**Please note: This issue tracker is for bug reports**
If your issue isn't a bug report, or if you are unsure whether it's a bug, please go to our discord channel instead at <https://discord.gg/H8UKY3Y>
If you are confident your issue is a bug, please fill in as much information as you can below.

**Describe the bug**
ZCPU and others are missing, they won't load from saves or appear under chips and gates

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Wire tab on tools
2. Click on Chips and gates

**Expected behaviour**
ZCPU and others should be visible there

**Screenshots**
![image](https://github.com/wiremod/wire/assets/79792352/48e5050b-c71f-4db5-beb2-aa4c075ab0cf)

**Comment by thegrb93** [comment]
It was moved to https://github.com/wiremod/wire-cpu due to security concerns.

**Comment by Mer08** [comment]
Wouldn't it break compatibility with other save files?

**Comment by Mer08** [comment]
Is it going to be reimplemented once the vulnerability is fixed?

**Comment by Hazeofdream** [comment]
> Is it going to be reimplemented once the vulnerability is fixed?

i doubt anyone is going to rewrite 3 components for the 5 people that make up the zcpu/cpu/gpu community

**Comment by Vurv78** [comment]
> Is it going to be reimplemented once the vulnerability is fixed?

I'm against this. It's a transpiled, large project that the original creator has long ago abandoned. It's just not safe to keep in this codebase nor is it productive to keep it with decade old bugs, and as @Hazeofdream says, barely anyone uses it. It's unfortunate but that's how abandonware goes

There's another chip in the works if you are just interested in a cpu
