### ISSUE TITLE
Wire-Screens inaccurate with decimal numbers when all settings are disabled

### ISSUE THREAD

**Issue by ArsiTheFox** [wiremod/wire#2760]
**Describe the bug**
WireMod screens showing inaccurate values when Text-Screens show normally

**To Reproduce**
1. Spawn Screen with all settings off except "Only one value" turn that on
2. Create Constant Value with a number with decimals. I used: 427.3716829
3. Spawn Constant Value
4. Wire Screen to Constant Value
5. See horribly inaccurate data on screen

**Expected behavior**
Screen should just output what was wired in when all format settings are off.
As u can see it displays perfectly on the Text-Screen when Wired to a "Number to String" gate

**Screenshots**
![image](https://github.com/wiremod/wire/assets/24835664/1024ad01-1226-46c3-b317-ea60e31e6fe9)

![image](https://github.com/wiremod/wire/assets/24835664/55e3909b-946b-431c-ac0a-dcb725b25c2e)
![image](https://github.com/wiremod/wire/assets/24835664/55f91b84-920b-452c-9d28-f4d3289f6f18)

**Comment by Denneisk** [comment]
This is just floating point imprecision because NWVars use floats instead of doubles. Could try sending a string representation of the number and having it tonumbered if we want double precision.

**Comment by ArsiTheFox** [comment]
Anything to have it sync better because with any decimal it fails especially a small number like 4.7 or 57.81 it spits out a bunch of gook

**Comment by thegrb93** [comment]
could split it into two floats, like a SetNWDouble, but Idk if I'd trust the two float to always sync at the same time

**Comment by Denneisk** [comment]
> could split it into two floats, like a SetNWDouble

How would this work?

**Comment by ArsiTheFox** [comment]
I was working on a feature for the Round Gate to add the functionality to set the amount of decimal places to round by and I found out it is useless until the screen inaccuracy is fixed in some way.
https://i.imgur.com/wSCd04b.png

**Comment by thegrb93** [comment]
@Denneisk Stringstream from starfall can do this
```lua
local ss = bit.stringstream()
ss:writeDouble(d)
ss:seek(1)
local f1, f2 = ss:readFloat(), ss:readFloat()
```

**Comment by thegrb93** [comment]
SetNWString would be the better solution though I think.

**Comment by ArsiTheFox** [comment]
If u do get this updated and working would u mind adding this to wire/lua/wire/gates/arithmetic.lua Line 145:
![Edited code of wire/lua/wire/gates/arithmetic.lua Line 145 to add decimal point functionality](https://i.imgur.com/wSCd04b.png)

It adds the functionability to insert a decimal place amount to the rounding and if nothing is put in it rounds it normally
I never made a Commit before soooo

**Comment by Denneisk** [comment]
You could PR that yourself if you wanted to.

**Comment by ArsiTheFox** [comment]
Sent out a Request

**Comment by ArsiTheFox** [comment]
Any updates on this issue?
