### ISSUE TITLE
Feature request: E2 Per player limits

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/wire#2762]
Currently E2 doesn't have per player limits like SF, this means that limiting E2's on larger servers is incredibly annoying as you either give people few chips or a bunch of low quota chips which both will break peoples builds. So currently i have to choose between low single chip limits which breaks a lot of badly coded public E2's which sadly a large amount of people use or i lower the chip count which breaks a lot of long term builders their stuff as they tend to use lots of low powered chips.

Here's how SF does it <https://github.com/thegrb93/StarfallEx/blob/ba765969401b4171ad22157b9a0f6ab69ac56dba/lua/starfall/instance.lua#L755>

**Comment by PekmeziKruh** [comment]
please add this bro

**Comment by Worldproto** [comment]
add this pls
