### ISSUE TITLE
E2 holo error spam

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/wire#2768]
```
[wire] cam.End underflow
  1. FinishClipping - addons/wire/lua/entities/gmod_wire_hologram.lua:106
   2. unknown - addons/wire/lua/entities/gmod_wire_hologram.lua:139 (x430)
```

E2 code to replicate it:
```
holoCreate(1)
holoClipEnabled(1,1,1)
```

Simply spawn the chip and it'll spam everyones console full with the error, the more holos the more error spam.
Has been happening for a few days now and it's really annoying, not exactly sure when it started.

**Comment by Vurv78** [comment]
Was just bad code in the first place, but there was no underflow error, so
