### ISSUE TITLE
Delta operator `$` behavior change w/ new compiler

### ISSUE THREAD

**Issue by Vurv78** [wiremod/wire#2784]
Old `$` updates **each assignment**
New `$` updates **each `$`**

This has broken some chips but also been seen as better behavior by some.

It wasn't intentional to change the behavior of delta, but after comparing the two implementations, I much prefer the new version.

## RFC

* Worth reverting for all chips? Or just non-strict?
* Worth "fixing" at all?
* Maybe even just deprecate the operator since it could cause major confusion just for slight convenience?

**Comment by CheezusChrust** [comment]
Give it back the old behavior, but deprecate it given that more often than not I see people confused about how it works (and IMO it leads to bad habits becoming dependent on it)
