### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by vrillz** [wiremod/wire#2800]
[Wiremod] lua/entities/gmod_wire_expression2/init.lua:595: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. Setup - lua/entities/gmod_wire_expression2/init.lua:595
    3. ApplyDupeInfo - lua/entities/gmod_wire_expression2/init.lua:653
     4. PostEntityPaste - lua/entities/base_wire_entity.lua:469
      5. oldPaste - lua/includes/modules/duplicator.lua:834
       6. Paste - lua/wire/server/wirelib.lua:1403
        7. LeftClick - gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator.lua:63
         8. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:226

happends when pasting a workshop dupe, that works fine on my local server. but not on my dedicated

**Comment by Vurv78** [comment]
This is from workshop version of wire, please update to github and let me know if it still happens.

**Comment by Vurv78** [comment]
Can reopen if provided with more info (at the very least provide the dupe...)
