### ISSUE TITLE
E2: Foreach behavior change with compiler rewrite

### ISSUE THREAD

**Issue by stepa2** [wiremod/wire#2803]
**Describe the bug**
`foreach` sometimes skips iterations.

**To Reproduce**
```
# Nothing changes when `array` is replaced with `table`
local List = array(1, 2, 3, "A", "B", "C", 4)

local Numbers = ""
foreach (K:number, V:number = List) { 
    Numbers += toString(V) + ","
}

# prints: Numbers=1,2,3,
# excepted: Numbers=1,2,3,4,
print("Numbers","=",Numbers)  

local Strings = ""
foreach (K:number, V:string = List) { 
    Strings += V + ","
}

# prints: Strings=
# excepted: Strings=A,B,C,
print("Strings","=",Strings)

# Also see what happens when you remove first three numbers from array.
```
```
local Table = table()
Table[123, table] = table("Something")

local String = ""

foreach(I:number, Tbl:table = Table) {
    String += Tbl[1, string]
}

# prints: String=
# excepted: String=Something
print("String=",String)
```

**Comment by Denneisk** [comment]
Foreach loops die when they run into a type mismatch. It's not errored either, it just does that. That should probably be an error or at least have the table filtered automatically. There's an E2 function that returns a copy that's filtered at least.

Second one is probably because the compiler optimizes it into `ipairs` instead of `pairs` which expects sequential arrays.

**Comment by Vurv78** [comment]
Problem with these things is that this behavior was never defined. Considering this was never brought to my attention probably the amount of people relying on behavior this is very minimal.

I personally don't agree with foreach doing this for essentially nonsequential / sparse arrays, which I've already said are undefined behavior.

As for the table issue, yeah that should be fixed as tables are meant to be used as lookup structures.

**Comment by Vurv78** [comment]
Table part fixed here https://github.com/wiremod/wire/commit/6f8480bd5254aafee70ae7675981d284df6cab2a

Not planning on changing the array behavior unless there's a really good reason to (giant chips that rely on it or significant amount of people)

**Comment by stepa2** [comment]
Why do you thing allowing correct iteration over heterogeneous arrays would reduce peformance?
