### ISSUE TITLE
`ray<Thing>Intersection()` returns bool if ray didn't hit <thing>, leading to errors

### ISSUE THREAD

**Issue by TypicWhisper** [wiremod/wire#2816]
**Describe the bug**
ray\<Thing\>Intersection() return their hitpos between the defined ray and the target. 
However, if the defined ray misses the target, they return a bool.

**To Reproduce**
1. Call ray\<Thing\>Intersection in a configuration above where the ray misses the target.
`A = raySphereIntersection(vec(0,0,0),vec(-1,0,0),vec(2,0,0),1)`
2. Use the return value as any argument.
`print(A)`
4. E2 subsequently errors when ran.

**Expected behavior**
In the context of E2, the most reasonable behavior in this case would be for the functions to return a zero , inf, or nan vector.

**Comment by Vurv78** [comment]
This is a wire extras issue, not wiremod
