### ISSUE TITLE
Vector2 issue

### ISSUE THREAD

**Issue by Hrecha** [wiremod/wire#2860]
https://github.com/wiremod/wire/blob/84f1f54065b51e8230a75b1e17bbaea0d2c68d7e/lua/entities/gmod_wire_expression2/core/vector2.lua#L658

code on E2:

MaxRanges[DataInd] = round(DataMaxRng/39.37, 1)

 will cause this:

sv: Expression 2 (CFCS v0.9.9 (HUD)): Internal error 'entities/gmod_wire_expression2/core/vector2.lua:658: attempt to index global 'self' (a nil value)' at line 464, char 13

I fix this problem, edited:
vector2.lua:658
self.GlobalScope.vclk[this] = true
change "self" to "state"
state.GlobalScope.vclk[this] = true

upper on 139 row, used "state" and in example how to use, showed from https://github.com/wiremod/wire/pull/2555
![image](https://github.com/wiremod/wire/assets/37973182/ef27fb53-2d60-4ae3-94b4-af0351de27f1)

**Comment by Vurv78** [comment]
May I ask why you're using vector4? Just curious. Because the plan was to deprecate it since it is essentially just an array.

**Comment by Hrecha** [comment]
in fact, this is not my code, someone's chip was written and it was convenient for him to use vector4 as an array
in the future, I will help him and write another code, but now he is faced with a problem and asked to see what is wrong, since he does not have much experience in programming, we tried to test what exactly is wrong, well, I concluded that the problem lies in the code of the "wire" itself

**Comment by Hrecha** [comment]
and so I myself often use it when creating holos, setting the color and transparency, rgba like

**Comment by Vurv78** [comment]
Yeah it would be deprecated and replaced with a proper `color` type.
