### ISSUE TITLE
selfaware core crashes under a change detection

### ISSUE THREAD

**Issue by Hazeofdream** [wiremod/wire#2876]
![image](https://github.com/wiremod/wire/assets/74027566/d1f9da2e-7d08-4df2-90b2-3eb29ba3b773)

The code can be replicated by using changed on an angle argument, not sure if this applies for any other kind of angle but It's odd behavior.

![image](https://github.com/wiremod/wire/assets/74027566/c38f72e5-ad46-4d6a-9d04-2d68b5abc077)

**Comment by Vurv78** [comment]
Ty
