### ISSUE TITLE
egpobject:getVertices() throws nil error

### ISSUE THREAD

**Issue by Noxyro** [wiremod/wire#2889]
See: [egpobjects.lua - egpobject:getVertices() - line 677 to 691](https://github.com/wiremod/wire/blame/d4fd71f9fdf57bfe45ffe70b606b467c98afa4fc/lua/entities/gmod_wire_expression2/core/egpobjects.lua#L677-L691)

Currently throws this error when trying to use on any egpobject without an actual "vertices" field:
`Internal error 'entities/gmod_wire_expression2/core/egpobjects.lua:684: attempt to index global 'v' (a nil value)' at line 34, char 13`

- **Probable cause:**
  - The `v` was accidentally used in reference to the `k, v` loop in the first if-statement.
- **Possible solution:**
  - Replace all `v` inside the elseif-statements with `this` instead.

**Comment by thegrb93** [comment]
You can implement your solution and PR it, it's a good practice. I'll do it if no one else does.

**Comment by Noxyro** [comment]
> You can implement your solution and PR it, it's a good practice. I'll do it if no one else does.

I would greatly appreciate it, if you could implement thix quick fix, as I currently don't have any dev tools set up on this computer.
Thank you!

**Comment by thegrb93** [comment]
fixed by https://github.com/wiremod/wire/commit/da9ef93c1ebc43dc14b2f530b27495795a2cc1c0
