### ISSUE TITLE
soundDuration cannot Detect TF2 Sounds Durations anymore.

### ISSUE THREAD

**Issue by nexbr** [wiremod/wire#291]
the function soundDuration are not detecting Team Fortress 2 Sound Duration anymore.

soundDuration("vo/scout_dominationdem04.wav") = 0

But with HL2 Sounds works OK.

**Comment by EvaneosKOWAR** [comment]
I've found that the soundDuration problem isn't due to a type of sound, but depend of the wiremod version installed on the server, 4 years later that problem still exist, and on 40% of the server i play soundDuration return 0 whatever sound you put on, could be if someone can check @Divran

**Comment by bigdogmat** [comment]
As said before, it directly returns what http://wiki.garrysmod.com/page/Global/SoundDuration gives us. That function has been known to be unreliable for years. There's nothing we can do.

**Comment by CaptainPRICE** [comment]
> There's nothing we can do.

Write a parser.
