### ISSUE TITLE
Expression 2: function predefinition is broken

### ISSUE THREAD

**Issue by stepa2** [wiremod/wire#2910]
Following code does not compile.
```
@strict
function b() { error("undef") }

function a() { b() }
function b() { a() }
```

No workarounds that keep type checking of argument and return value.

**Comment by Vurv78** [comment]
It shouldn't compile. Function overriding isn't a thing anymore on `@strict`. It's a hacky weird dynamic behavior. If you want it, use lambdas.

**Comment by Vurv78** [comment]
Closing as I never guaranteed backwards compatibility with `@strict`
