### ISSUE TITLE
Expression 2: VGUI Core doesn't seem to mount properly.

### ISSUE THREAD

**Issue by TRY0NIGHT** [wiremod/wire#2912]
Ever since the recent update, the VGUI Core written by Linus045 doesn't seem to mount properly to Expression 2. The addon mounts the Spawnmenu utilities fine, and doesn't seem to create any errors. However, none of the functions or directives seem to exist in the Expression 2 editor itself. 

Going to the Spawnmenu and in the utilities tab, I found the "E2 Vgui Core" folder and in that folder is the permissions tab. Everything seems to work fine there, as there are no errors or notifications when I fiddle with the settings. However, when I opened the Expression 2 editor with the wire tool, none of the utilities for e2 popped up. And when I opened up my AdvDupe2 to spawn a duplication that I had utilized VGUI core for, it gave me a bunch of expression code errors stating that the variables were unknown.

Here is the Github link to the addon:
https://github.com/Linus045/e2_vgui_core

Here are some images:

![image_2023-11-26_145450456](https://github.com/wiremod/wire/assets/54338434/cc82c3c7-5ca3-4460-9eb4-be19a8144547)

![image_2023-11-26_145629611](https://github.com/wiremod/wire/assets/54338434/581d7915-8f30-4db3-b373-7f8a15d797a2)

![image_2023-11-26_145655514](https://github.com/wiremod/wire/assets/54338434/c46dfef3-86b1-4973-a414-1141e4078651)

**Comment by Denneisk** [comment]
Do you get any errors on startup from the extension itself? It's likely the extension is erroring and not getting loaded.

**Comment by TRY0NIGHT** [comment]
Now that you mention it, I don't get any errors in console when I start up expression. However, when I start up expression 2 editor, there's a brief error text at the bottom saying something along the lines of something failing to compile, and then it just turns green and says "validation successful".

**Comment by Denneisk** [comment]
VGUI Core uses some loader to load all its submodules, which uses E2Lib's `extpp` to preprocess all those files. I don't know if this should be allowed, but VGUI is passing too little arguments to the updated preprocessor.

**Comment by TRY0NIGHT** [comment]
I downloaded the edited commit of VGUI core, however nothing much seemed to change... I've validated the game and even redownloaded it just to make sure. I'm not sure what could be causing the mounting issue

**Comment by TRY0NIGHT** [comment]
whoops. Didn't mean to do that. 

I've downloaded the edited version, but nothing much has seemed to change. I've validated and redownloaded it just to make sure. I don't know what could be causing the issue

**Comment by Vurv78** [comment]
They really shouldn't be relying on more internal e2 stuff like that so this is more of an issue for them. Since @Denneisk opened his PR over there I will close this.
