### ISSUE TITLE
#2895 

### ISSUE THREAD

**Issue by InfHorus** [wiremod/wire#2919]
sv: Expression 2 : Internal error 'entities/gmod_wire_expression2/core/vector.lua:489: attempt to call upvalue 'quadraticBezier' (a nil value)' at line 876, char 9

can you guys stop pushing shit updates without even testing? instead of improving e2s y'all doing garbage that doesn't even work.

fix your shit now

**Comment by Denneisk** [comment]
The August update has been out for 2 months now

**Comment by InfHorus** [comment]
you realize you broke an important function like bezier for dozens of servers that probably won't be updated again until weeks? if you don't know what you are doing, DO NOT do it.

**Comment by Vurv78** [comment]
This is volunteer work. Quit being a lazy cunt and send a PR if you want it fixed immediately. Otherwise just report issues respectfully.

**Comment by InfHorus** [comment]
> This is volunteer work. Quit being a lazy cunt and send a PR if you want it fixed immediately. Otherwise just report issues and raise your concerns respectfully.

for the love of God, stop volunteering, you guys have taken over E2 as if it were your own and you do whatever you want whenever you want without caring about the consequences.

**Comment by Vurv78** [comment]
> > This is volunteer work. Quit being a lazy cunt and send a PR if you want it fixed immediately. Otherwise just report issues and raise your concerns respectfully.
> 
> 
> 
> for the love of God, stop volunteering, you guys have taken over E2 as if it were your own and you do whatever you want whenever you want without caring about the consequences.

Your opinion is not relevant little guy. Go complain to your lazy ass server owners.

**Comment by bjcscat** [comment]
>you guys have taken over E2 as if it were your own and you do whatever you want
Ohh noooo, improvements nooo noo oh nooo! we must keep E2 as it was a decade ago!
