### ISSUE TITLE
Casualties caused by #2917

### ISSUE THREAD

**Issue by Fasteroid** [wiremod/wire#2926]
#2917 brought some unnecessary changes I think negatively impacted certain props.  I'm not saying none of the textures should have been compressed, but many props have been adversely affected:

![image](https://github.com/wiremod/wire/assets/29342750/17f3cc2c-7d68-4683-a0e7-7bf4f695587c)

The GPS, Target Finder, and CD props in particular were mangled pretty badly by this change.  Also among the casualties is my SD card model, which I put a LOT of work into texturing, and seeing it in this state is greatly upsetting.  

@thegrb93, please re-evaluate your decision to push this to master, I don't this PR was ready for that yet.

**Comment by Denneisk** [comment]
If it's any consolation, I believe this was automated, so it was probably just from a low sample size of images used for comparison.

**Comment by thegrb93** [comment]
What do you expect from compressing textures?

**Comment by Fasteroid** [comment]
I mean, I guess this, I just didn't expect we'd be compressing so hard everywhere.

**Comment by thegrb93** [comment]
Make a list of ones that look too shitty and we can revert

**Comment by thegrb93** [comment]
(using mat_texture_list in console while looking at the props is an easy way to do it)

**Comment by wrefgtzweve** [comment]
> Make a list of ones that look too shitty and we can revert

I've picked some and done this in https://github.com/wiremod/wire/pull/2928

**Comment by Fasteroid** [comment]
Apologies for overreacting, my sd card and wiremod base were adversely affected and I couldn't see past my own selfish tendencies.  Gonna close this for now as to be collaborative rather than "reverting and doing it my way"
