### ISSUE TITLE
E2 :wirelink() broken backwards-compat

### ISSUE THREAD

**Issue by Fasteroid** [wiremod/wire#2940]
Using :wirelink() on an entity that doesn't have one by default now returns an invalid wirelink.
Seems to have been broken by #2891 since `entity:wirelink()` no longer creates a wirelink.

Before: https://github.com/wiremod/wire/blob/4edf127222e5c584883739abdc3f4cef55f13117/lua/entities/gmod_wire_expression2/core/custom/wiring.lua#L108-L116

After: https://github.com/wiremod/wire/blob/95adeb437e8c1ac1f5ac13c83a23cd303d386ed8/lua/entities/gmod_wire_expression2/core/custom/wiring.lua#L108-L116

Probably easy to fix if this tiny change is reverted.

**Comment by Denneisk** [comment]
Thanks for reporting this.

**Comment by Fasteroid** [comment]
bruh
