### ISSUE TITLE
Really weird clutch behaviour when CHANGING friction value between unfrozen props

### ISSUE THREAD

**Issue by Mrleplayz** [wiremod/wire#2951]
Asked around discord too many times, nobody really responded with anything useful.

The clutch friction doesn't have constant application IF the friction is changed WHILE THE OBJECT IS ROTATING
Now, this is a problem since an unfrozen ACF vehicle still counts as the wheels sorta *moving*, so anytime i'd brake, it'd change the friction value while unfrozen/moving and not create a proper contraint.

This was NEVER an issue, and it only popped up in late September.

**To Reproduce**
1. create a clutch link of two props, one as a baseplate other as a suspended member
2. change the friction value WHILE the suspended memeber is rotating

**Expected behavior**
The clutch actually resists rotation as it did before September of this year (im not sure an update of gmod/wiremod caused it)
Note: video is in 24 fps, it is not stuttering, the wheel simply stops turning immediately upon release and the mouse jerks

https://github.com/wiremod/wire/assets/43085859/c78d09de-3372-46f0-b918-f3a2463a96a0

**Resulted behaviour**
The clutch takes time to engage and it does so only for a moment before letting go again
Weight of wheel 55, weight of base 1000

https://github.com/wiremod/wire/assets/43085859/eddf38a5-2c36-4ae2-8211-a632e631868e

**Comment by Mrleplayz** [comment]
As you see from this video, the friction is applied in "pulses"

https://github.com/wiremod/wire/assets/43085859/d8830bdc-0a15-4d90-99c0-6c14045144d7

**Comment by Vurv78** [comment]
Clutch hasn't changed behavior in years so I don't think it's that.

**Comment by Mrleplayz** [comment]
I think there were gmod updates around that time? Might've broken something

**Comment by thegrb93** [comment]
Hasn't the behavior always been jank? It's basically deleting the ballsocket joint and creating a new one every time the friction changes iirc.

**Comment by Mrleplayz** [comment]
See that's part of the issue, it had perfect functionality but no one ever used it.
Even now I can't see any alternative to them, they were smooth, they could hold ACF cars on hills with no issue, they were flexible.
Like you can't reproduce that kind of functionality with weld latches or ACF brakes

**Comment by thegrb93** [comment]
The clutch scripts haven't been touched in years so something else broke whatever you are finding is different.
