### ISSUE TITLE
E2 interval() no longer works inside conditional statements

### ISSUE THREAD

**Issue by DataSchmuck** [wiremod/wire#298]
I used to be able to do this:

if (Input) {
     interval(100)
     Do Stuff
}

and as long as Input was 1, the chip would run at interval(100)

However, after the june 03 commit fixing E2 timers and garbage leaks, the above code only runs the chip once, and doesn't repeat.

**Comment by expression2coder** [comment]
Perhaps add a persists D to it.

**Comment by expression2coder** [comment]
This bug seems to not effect people anymore.

**Comment by thegrb93** [comment]
We knew that 5 years ago.
