### ISSUE TITLE
EGP Parented Lines on HUD not rendering correctly

### ISSUE THREAD

**Issue by alexswad** [wiremod/wire#2981]
**Describe the bug**
Parented lines on EGP HUDs don't render correctly, after more testing I see the line pop on the middle of my screen before disappearing. It sometimes happen on screens randomly

**To Reproduce**
Run this code with an EGP screen and HUD and notice the difference
```js
@inputs EGP:wirelink

if (~EGP & EGP) {
    EGP:egpClear()
    EGP:egpCircle(3, vec2(200, 200), vec2(50, 50))
    EGP:egpColor(3, vec(255, 0, 0))
            
    EGP:egpLine(4, vec2(-20, 20), vec2(20, -20))
    EGP:egpSize(4, 5)
    EGP:egpParent(4, 3)
}
```

**Expected behavior**
Screenshot taken from Wiremod from 2022
![gmod_LoPBoY4dwZ](https://github.com/wiremod/wire/assets/23157413/29929cbd-d8c0-4c94-ad9c-4db0807354e5)

**Observed behavior**
Taken from most recent version
![gmod_Otu1BJ9XXR](https://github.com/wiremod/wire/assets/23157413/dd042341-86da-4d20-9830-22e78b52f93b)

![image](https://github.com/wiremod/wire/assets/23157413/a04e0f41-f4ff-4189-b5b9-433963044670)

**Comment by Denneisk** [comment]
Do you mind testing this and seeing if it still happens on the latest Github version? I just tested this again and it seems to work as expected.
