### ISSUE TITLE
Likely unneeded performance drop when having addon enabled

### ISSUE THREAD

**Issue by wolfestridershooter** [wiremod/wire#2987]
**Describe the bug:**
While trying to find what was causing me performance issues in Garry's Mod by using Addon hooks Lag Finder I found this:

```lua
Identifier  -----------------------------------------------  Impact      Executions     Mean t/f        Max time
 Event "PostDrawEffects", hook "RenderHalos"                 04.78%      2526           595.495us       2272.00us
  in "lua/wire/client/cl_wirelib.lua" (lines 244 to 248),
  found in Workshop addon « Wiremod »
```

Sure enough when I disabled Wiremod I gained FPS in an idle scenario. My guess is that this code renders the Halo effect that shows when you look at a wire entity, but if we have no wire entities on the map why are we running this? I don't know maybe I'm completely wrong and there is a good reason why it's being done.

**To Reproduce**
1. Start a new game
2. Do nothing
3. Lose FPS

**Expected behavior:**
To not lose FPS when not using Wire entities

**Comment by Vurv78** [comment]
https://github.com/wiremod/wire/pull/2576

@stepa2

**Comment by thegrb93** [comment]
detouring it won't produce lag... It's just calling https://github.com/Facepunch/garrysmod/blob/87aa68cb8da3d70e6e7265bc61ca222c55e3f8e5/garrysmod/lua/includes/modules/halo.lua#L147 which is historically known to be a very costly function

**Comment by Vurv78** [comment]
Detouring will absolutely produce lag.. especially since it runs hook.Run beforehand, and the hook library is not as fast as it could be

**Comment by thegrb93** [comment]
The script is just profiling hooks so yeah, it's identifying the wire hook which calls garry's hook, to be the culprit. This PR tried to improve its performance but didn't work https://github.com/Facepunch/garrysmod/pull/1590

It's not wire's problem that gmod's halo system is very costly.

**Comment by thegrb93** [comment]
I think there's a convar to disable halos btw.
