### ISSUE TITLE
Missing pattern checks

### ISSUE THREAD

**Issue by Vurv78** [wiremod/wire#2992]
Pattern complexity checks are missing in certain parts of code

1. Gates
2. E2 find library

Haven't looked much into it

**Comment by Fasteroid** [comment]
> Easy fix

You don't remember when e2 briefly had `:match` disabled specifically because of this, do you?  I don't think it's that easy to fix...

**Comment by Denneisk** [comment]
Could simply run `WireLib.CheckRegex` against every occurance, only I ran into a problem with E2 find library: the pattern is stored before it's used, and it's expected to be used against every entity's classname. Pausing the find operation in the middle would be bad UX, but you can't expect the longest entity's classname. Maybe just test it on definition against a dummy 32 character string? Could open up a branch to show you what I mean.

**Comment by thegrb93** [comment]
Yeah, running the check against a 32 length sounds fine for e2 find lib.
