### ISSUE TITLE
Lua standard thruster error

### ISSUE THREAD

**Issue by Astralcircle** [wiremod/wire#2993]
Tested in the game without addons and chromium. Wiremod was the newest from Github (Feb 8, 2024)

**Describe the bug**
Lua error when selecting Wiremod model in the GMOD DEFAULT thrusters menu

lua/vgui/propselect.lua:47: bad argument #1 to 'pairs' (table expected, got boolean)
    1. pairs - [C]:-1
        2. DoClick - lua/vgui/propselect.lua:47
            3. unknown - lua/vgui/dlabel.lua:237

**To Reproduce**
1. Go to 'Tools --> Thruster
2. Select model "models/fasteroid/computerfan.mdl" (Fan model from Wiremod)'
3. See error

**Expected behavior**
Fix lua error

**Screenshots**
![image](https://github.com/wiremod/wire/assets/142503363/32d9a8df-972b-47ec-9090-6c4f5a07acd5)
![image](https://github.com/wiremod/wire/assets/142503363/561cc745-f871-4e48-853e-c25bef004983)

**Comment by thegrb93** [comment]
this needs to be `value = value or {}` https://github.com/wiremod/wire/blob/master/lua/wire/sh_modelplug.lua#L6

**Comment by Fasteroid** [comment]
my fault
