### ISSUE TITLE
Wire Ballon Deployer game crash

### ISSUE THREAD

**Issue by Astralcircle** [wiremod/wire#2994]
**Describe the bug**
If you set the Ballon Deployer Force too high, the game will crash

**To Reproduce**
1. Go to 'Entities-->Wiremod'
2. Spawn 'Wire Ballon Deployer'
3. Set Force to 99999999999999999999999999999999999999999999999999999999999999999999999999999999999
4. Activate it

**Expected behavior**
Set the Force limit to approximately 1,000,000

**Video**
https://youtu.be/YeckL2h36wo (Maybe YouTube hasn't processed it yet)

**Comment by thegrb93** [comment]
You have sv_crazyphysics cvars turned off I think. There's millions of ways to crash the game if those are turned off.

**Comment by Astralcircle** [comment]
I just checked the convars on my server and all convars like sv_crazyphysics were enabled, but it still crashes my server

**Comment by thegrb93** [comment]
Give me an e2 to reproduce it then, I'm not counting all those 9s.

**Comment by Astralcircle** [comment]
In general, it is enough to enter a lot of nines, but here is the code


@name 
@inputs 
@outputs A
@persist 
@trigger 
@strict

A = 99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999

**Comment by Vurv78** [comment]
> In general, it is enough to enter a lot of nines, but here is the code
> 
> @name @inputs @outputs A @persist @trigger @strict
> 
> A = 99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999

That's just `_INF`. Should probably have a warning for number literals that are greater than what lua can actually store

**Comment by thegrb93** [comment]
Still didn't crash. I just get
```
Crazy origin, velocity on entity [73][gmod_balloon]
	Origin:           [-41.883915, -211.789429, nan]
	Angles:           [0.000000, 0.000000, 360.000000]
	Velocity:         [0.000000, 0.000000, nan]
	Angular Velocity: [0.000000, 0.000000, -0.000000]
Defusing!
Removing!
Crazy origin, velocity on entity [73][gmod_balloon]
	Origin:           [-41.793987, -211.789429, nan]
	Angles:           [0.000000, 0.000000, 360.000000]
	Velocity:         [0.000000, 0.000000, nan]
	Angular Velocity: [0.000000, 0.000000, -0.000000]
Defusing!
Removing!
```

**Comment by Astralcircle** [comment]
Perhaps it is so
