### ISSUE TITLE
Vehicle Controller engine sound bug

### ISSUE THREAD

**Issue by wolfestridershooter** [wiremod/wire#3002]
**Describe the bug:**
Engine sound will only play if I get in and out of the vehicle and will not rev up or down when the throttle is being controlled.

**To Reproduce**
Link the Vehicle Controller to a vehicle and link up inputs to the engine and throttle.

**Expected behavior:**
For the engine make sounds whenever turned on and to rev up and down depending on throttle input.

**Video:**
https://www.youtube.com/watch?v=RmntDkHixKE

**Comment by thegrb93** [comment]
The vehicle doesn't actually have a driver so that explains the missing sounds. This is just a source engine limitation and it won't fixable unless someone adds code in the vehicle controller to emulate the sounds, which I don't think anyone will since it's such a niche entity.
