### ISSUE TITLE
Several EGP elements dissapear permanently if not updated constantly

### ISSUE THREAD

**Issue by Ally-for-Hire** [wiremod/wire#3003]
**Please note: This issue tracker is for bug reports**
If your issue isn't a bug report, or if you are unsure whether it's a bug, please go to our discord channel instead at <https://discord.gg/H8UKY3Y>
If you are confident your issue is a bug, please fill in as much information as you can below.

**Describe the bug**
linestrips, polyoutlines, triangleoutlines, and lines when parented to a 3d tracker all delete themselves when you look away from them

**To Reproduce**
parent any of these elements to a 3d tracker, look more than 120 degrees away, and away indeed it goes

**Expected behavior**
they disappear permanently

**Screenshots**
just imagine a screenshot where first the triangle is there and then it isnt, took me like an hour and a half before i realized what was happening and just used a circle outline

**Comment by Denneisk** [comment]
Looked into it, it seems the vertices are being set to an impossible number from moving so far off the screen. Not sure how to remedy this best, maybe just clamp to a really high number.
