### ISSUE TITLE
Expression 2 bypass quota limit

### ISSUE THREAD

**Issue by Astralcircle** [wiremod/wire#3005]
**Describe the bug**
E2 code that can bypass the quota limit and easily crash any server. (Some not immediately, but sometimes instantly)

**To Reproduce**
Spawn E2 chip with that code:
interval(1)
if(first()){
    holoCreate(1)
    holoScale(1,vec(0,0,0))
}
while(perf()){
      holoPos(1,owner():pos())
}

**Expected behavior**
Fix this problem

**Demo and screenshots**
Demo: https://youtu.be/Cuao0rnue0w
Screnshoots:
![image](https://github.com/wiremod/wire/assets/142503363/8f315a93-cc24-4732-93e7-4d419b01d2ab)

**Comment by thegrb93** [comment]
@Vurv78

**Comment by Denneisk** [comment]
What version of Wiremod is this on? May be related to #2959

**Comment by Vurv78** [comment]
This doesn't do anything for me yeah. Update your wire.
