### ISSUE TITLE
Letters on Character LCD don't update unless CharAddress is addressing them

### ISSUE THREAD

**Issue by DerelictDrone** [wiremod/wire#3010]
When the memory of the Character LCD is written to, the character will only change/refresh when the CharAddress is set the same as the memory index

Additionally, changing CharAddress while the cursor is visible the cursor will be stuck opaque in that cell and another cursor will begin blinking in the new targeted cell. 

It would be nice if external writes would update the screen immediately, and if the cursor cleared automatically from a space when CharAddress moves

![image](https://github.com/wiremod/wire/assets/57756830/94648477-ec0f-4af0-8433-d3dec7aff187)

**Comment by thegrb93** [comment]
You have to trigger the clk. Some things trigger clk automatically, but you're expected to do it. Redrawing everytime a letter is written would be inefficient

**Comment by DerelictDrone** [comment]
> You have to trigger the clk. Some things trigger clk automatically, but you're expected to do it. Redrawing everytime a letter is written would be inefficient

I didn't see that clk and charaddress are available in memory, my bad
