### ISSUE TITLE
an addon on the workshop is conflicting with wiremod trails 

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#3015]
**Describe the bug**
when using https://steamcommunity.com/sharedfiles/filedetails/?id=2982704389&searchtext=improved+crossbow+bolt+ e2 trails stop working

**To Reproduce**
1. Go to the steam WS
2. look for improved crossbow bolt
3. subscribe to it 
4. go into game and try to use e2 trails on the crossbow bolt (so far they don't work unless you remove the addon

what i expected was to use the e2 trails without conflict.

**Comment by Vurv78** [comment]
Report it to them

**Comment by deathking61** [comment]
i have and they claimed to have updated the addon and now they have told me to tell you guys
