### ISSUE TITLE
`entity:aimBone()` does not return a valid bone

### ISSUE THREAD

**Issue by Denneisk** [wiremod/wire#3018]
**Description**
When using `entity:aimBone()`, the bone will be null despite looking at a proper ragdoll. Using `entity:bone(number)` on an entity does not cause this.

**To Reproduce**
1. Put this code on a chip
   ```ts
   @strict
   event keyPressed(_:entity, _:string, Down:number, KeyBind:string) {
       if(Down & KeyBind == "use") {
           print(owner():aimBone())
       }
   }
   ```
2. Press E on a ragdoll
3. Observe the print statement will say `(null)`

**Expected behavior**
The print statement should show something like `Entity [100][prop_ragdoll]:bone(1)`.

**Notes:**
In testing this, `entity:aimBone()` does return a valid bone, but in `isValidBone`, the bone gets invalidated wrongly. When performing `bone2entity[b]`, this returns `nil` even when an equivalent reference to the bone is in the table. Annoyingly, this only happens when using `aimBone`. This shouldn't happen since `getBone` uses a cached value which is guaranteed to be in `bone2index`, `bone2entity`, and `entity2bone`.

**Comment by Denneisk** [comment]
The same PhysObject can have different addresses, which apparently makes table lookups unreliable for them. Bone caching needs to be removed... I happened to have deleted a prototype uncached bone branch that I thought was outdated. Heh.

**Comment by Denneisk** [comment]
As it turns out, bones can simply remove themselves from tables. Is this a Lua feature? Hash collision? Cosmic radiation??

**Comment by thegrb93** [comment]
Possibly only if the table __mode is set to weak.

**Comment by Denneisk** [comment]
Yeah, but if you look at the source (even the diff in my PR) you'll see it's just a normal table.

**Comment by thegrb93** [comment]
Maybe whatever you're doing to try an print the bone isn't working
