### ISSUE TITLE
Weird behaviour with triggers

### ISSUE THREAD

**Issue by ghostserver10** [wiremod/wire#3037]
**Describe the bug**
I have a project that uses fairly comlex control system so I divided E2 chips by functions. I have a chip that calculates control forces and another that will apply those forces. To make sure that one chip trigger execution of another I make sure that control chip is executed first and then it flips output variable so that it should trigger force processing chip. Otherwise it seems that force processing chip will work with older outputs of control chip(older by one frame)

**To Reproduce**
Create a chip that calculates control signal using PID regulator. At the end of code type SyncOut = !SyncOut(which is in @outputs part) so it would trigger execution of another chip that process forces. Also have in @output force vector itself. 
Even though force processing chip has trigger only by SyncOut input it appears as if the chip gets triggered twice. As the stable control system becomes unstable
I am assuming that is just basic issue with trigger system but is there any way to make control system such that chip would use newest parameters for control without triggers?

**Expected behavior**
Expected behaviour is that it would work in a usual way. Maybe that is happening because my request is kinda impossible and you cant synchronise chips?

**Screenshots**

**Comment by thegrb93** [comment]
Don't know what you mean it triggers twice. I guess you are expecting it to only trigger if the input is 1? Input triggers will trigger on any change of the input, so 1 or 0 will trigger it.

**Comment by Denneisk** [comment]
You could disable triggers (`@trigger none`) and use a timer to regularly poll the inputs instead. Otherwise I think what you're looking for is just to check that `Input != 0` as thegrb93 suggested.

**Comment by Denneisk** [comment]
E2 chips can trigger multiple times per tick. Maybe that's what you're missing?

**Comment by Divran** [comment]
use `if (~InputName) {` to check if the current execution was caused by that input. this will filter out the multiple executions in a single tick thing

and by now there's probably an event for input triggers which could be used for that, which is probably better

**Comment by ghostserver10** [comment]
> use `if (~InputName) {` to check if the current execution was caused by that input. this will filter out the "multiple executions in a single tick" thing
> 
> and by now there's probably an event for input triggers which could be used for that, which is probably better

**Comment by ghostserver10** [comment]
Thank you guys
