### ISSUE TITLE
Client lua errors after objectcontrol update

### ISSUE THREAD

**Issue by Astralcircle** [wiremod/wire#3044]
**Describe the bug**
Lua error:
[wire-master] addons/wire-master/lua/entities/gmod_wire_egp/lib/egplib/objectcontrol.lua:113: attempt to index local 'name' (a nil value)
    1. NewObject - addons/wire-master/lua/entities/gmod_wire_egp/lib/egplib/objectcontrol.lua:113
        2. unknown - addons/wire-master/lua/entities/gmod_wire_egp/lib/objects/text.lua:2
            3. include - [C]:-1
                4. ObjectInherit - addons/wire-master/lua/entities/gmod_wire_egp/lib/egplib/objectcontrol.lua:143
                    5. unknown - addons/wire-master/lua/entities/gmod_wire_egp/lib/objects/textlayout.lua:2
                        6. include - [C]:-1
                            7. unknown - addons/wire-master/lua/entities/gmod_wire_egp/lib/egplib/objectcontrol.lua:156
                                8. include - [C]:-1
                                    9. unknown - addons/wire-master/lua/entities/gmod_wire_egp/lib/init.lua:40
                                        10. include - [C]:-1
                                            11. unknown - addons/wire-master/lua/entities/gmod_wire_egp/shared.lua:15
                                                12. include - [C]:-1
                                                    13. unknown - addons/wire-master/lua/entities/gmod_wire_egp/cl_init.lua:1

**To Reproduce**
1. Sometimes appears when entering the game

**Expected behavior**
Fix the error?

**Screenshots**
![image](https://github.com/wiremod/wire/assets/142503363/a0fd029b-e0ea-4c00-ad21-71a0deab2321)

**Comment by Denneisk** [comment]
Have you restarted the server/changed map? I only experienced this when the new version hot-reloads. Do you have any other versions of Wiremod installed?

**Comment by Astralcircle** [comment]
> Have you restarted the server/changed map? I only experienced this when the new version hot-reloads. Do you have any other versions of Wiremod installed?

Latest from Github

**Comment by Denneisk** [comment]
I just realized, your file is erroring on `objectcontrol.lua`, but this was renamed in the latest update to `objects.lua`. Are you sure there's no other versions of Wiremod?

**Comment by Astralcircle** [comment]
Well, of the other “wire” addons I only have Wire Extras and E2Power. But I don't think it has anything to do with it

**Comment by thegrb93** [comment]
objectcontrol.lua shouldn't exist, you probably copied the files or something without deleting the old install

**Comment by Astralcircle** [comment]
> objectcontrol.lua shouldn't exist, you probably copied the files or something without deleting the old install

Perhaps I should take a more responsible approach to updating addons. Thank you.

**Comment by thegrb93** [comment]
rsync is a good option if you're using ftp or something.
