### ISSUE TITLE
[SERVER SPECIFIC DISREGARD] Wire Textscreen FGColor and BGColor do not Update the Screen

### ISSUE THREAD

**Issue by snepderg** [wiremod/wire#3070]
**Please note: This issue tracker is for bug reports**
If your issue isn't a bug report, or if you are unsure whether it's a bug, please go to our discord channel instead at <https://discord.gg/H8UKY3Y>
If you are confident your issue is a bug, please fill in as much information as you can below.

**Describe the bug**
Wire Text Screen inputs for FGColor and BGColor are not updating the colour on the screen.

**To Reproduce**
1. Spawn a Wire Text Screen with some text.
2. Wire a Vector input to FGColor or BGColor with a different value than what is set in the tool.
3. Notice how the colour does not change.

**Expected behavior**
FGColor should update the text colour and BGColor should update the background colour.

**Screenshots**
(Notice that I spawned the text screen with the colour set to Red, and I'm trying to change it to Green).

(Debug and Screen)
![gmod_zU9q1lQnD4](https://github.com/wiremod/wire/assets/45838657/7687189f-ac09-4557-8e26-61caad3a9b17)

(Debug)
![gmod_7SCKm9Stga](https://github.com/wiremod/wire/assets/45838657/39ca5dbc-d375-40eb-be41-f50bd98d2555)

(Constant Value)
![gmod_dp2iyf57zC](https://github.com/wiremod/wire/assets/45838657/9fbaff0d-3d84-44a2-a1f9-fc609b83c80b)

**Comment by snepderg** [comment]
Not really sure why it displays RGB: 0, 255, 0 as 0, 0, 255 but maybe I don't know how Vectors work in Wire.

**Comment by Denneisk** [comment]
Every number is displayed to 1 decimal point. The value is displaying correctly in the debugger.

**Comment by snepderg** [comment]
Ahhh, ok yeah I didn't look closely enough.

**Comment by Denneisk** [comment]
I was only able to replicate this bug after

1. Placing a text screen
2. Setting its color using a constant value
3. Updating the text screen using the tool gun
4. Trying to update the constant value using the tool gun

With normal wiring and when the color changes, I don't see this effect.

**Comment by snepderg** [comment]
Huh, interesting. For me, the constant value won't set the colour at all. I was directed here as it was assumed a Wire issue and not a server-specific issue.
