### ISSUE TITLE
rangerWhitelist(1) - use new 'whitelist' trace property

### ISSUE THREAD

**Issue by Fasteroid** [wiremod/wire#3082]
When I added this back in https://github.com/wiremod/wire/pull/1985, there wasn't really a good way of implementing it, but now as of [garrysmod.main/x86-64#9e093b](https://commits.facepunch.com/482895), traces now have a `whitelist` property that's 1:1 with how this _should_ have been implemented in the beginning.  Now that it can be improved, it should be.

Tag this with "enhancement" or whatever, I'm just opening an issue so I get off my ass and fix it later.

**Comment by Fasteroid** [comment]
1 month already, do it dumbass!

**Comment by Fasteroid** [comment]
> 1 month already, do it dumbass!

okay okay fine, this weekend

**Comment by megascan** [comment]
okay okay today it is!

**Comment by TeeMeeFe** [comment]
today perhaps?
