### ISSUE TITLE
toAngle() change braking expressions

### ISSUE THREAD

**Issue by Fritz005** [wiremod/wire#3087]
#[
A couple of days ago toangle() was changed from vector2:toAngle() to toAngle(vector2)
I have dupes from July 25 2021 to March 14 2024 that uses toangle as vector2:toAngle()

This has broken everything that I have made with toangle() 
and when i try to run anything i have made with vector2:toAngle() i get the error

No such method: xv2:toangle() 

but this change only effects the vector2 version of toAngle() every other version has not been change

Angle = quaternion:toAngle()
Angle = vector:toAngle()
Angle = matrix4:toAngle()
Angle = matrix:toAngle()

are all still valid

toAngle(vector2) should be changed back to vector2:toAngle() to keep old dupes still working and
maintain consistency through every version of toAngle

**To Reproduce**
@outputs Ang
@strict

Ang = vec2(1):toAngle()

#this will cause No such method: xv2:toangle() 

**Expected behavior**

vec2(1):toAngle() should output 45

**Comment by thegrb93** [comment]
Looks like this commit caused it https://github.com/wiremod/wire/commit/1c5f5a0cb0ee83c704f9ebc8c1a615ded694dc44
