### ISSUE TITLE
Expression 2 Editor's look bug

### ISSUE THREAD

**Issue by PiotrWrobelAGH** [wiremod/wire#309]
Hello, today i have a problem with editor's look. I cant read what have i wrote, i dont know what to do.
![asd](https://f.cloud.github.com/assets/3217968/774905/c565ed72-e965-11e2-9764-e011d6b83c00.jpg)

In this screen You can see that (this is not my code). Help please

**Comment by lilggamegenuis** [comment]
I've recently encountered this same issue and changing the font doesn't seem to be changing the font, let alone fixing the spacing.

**Comment by lilggamegenuis** [comment]
Looking further into the issue, it seems that when ever the syntax color changes, it doesn't properly read the font widths or space causing them to be rendered on top of each other.
