### ISSUE TITLE
False warning when including a file with functions

### ISSUE THREAD

**Issue by deltamolfar** [wiremod/wire#3096]
**Describe the bug**
If you have a function inside of lib file, and then include it in other E2 **with @strict** - you will get a warning in editor, that 'included file have n warnings', where n == amount of functions inside of included file. But you may have no warnings at all in the included file itself even with strict mode.

**To Reproduce**
1. Create a lib file with at least one function.
2. Create general E2 with strict mode
3. Include lib file into strict mode E2
4. Press validate button on bottom of editor

**Expected behavior**
No warnings lol

**Screenshots**
![2024-07-15_16-18_1](https://github.com/user-attachments/assets/ab8cbb35-00b5-4e4c-8b96-4b593c5c67c0)
![2024-07-15_16-18](https://github.com/user-attachments/assets/9475e7f5-abfc-4efe-9acb-30ae1946e1bc)

Iirc, right before Vurv left - he told that this might originate from strict-mode nested function warnings, as the contents of included file counts as nested code.

**Comment by Vurv78** [comment]
Pretty easy fix. IIRC problem is include variables are stored in scope `[1]` rather than global scope `[0]` in the table.

**Comment by Vurv78** [comment]
```diff
- 		if self.strict and not self.scope:IsGlobalScope() then
+		if self.strict and not (self.scope:IsGlobalScope() or (self.include and self.scope:Depth() == 1)) then
```
