### ISSUE TITLE
Holograms fail to change model

### ISSUE THREAD

**Issue by unknao** [wiremod/wire#3103]
For some reason when i create holograms they somewhat consistently don't change model, it seems like wire_holograms_modelany doesn't affect it whatsoever.

Example code:
```@name 
@inputs 
@outputs 
@persist N
@strict

if(first()){
    N = 1   
    for(I = 0, 5){
        for(II = 0, 5){
            holoCreate(N, entity():toWorld(vec(I, II, 1) * 30))
            holoModel(N, "hq_sphere")
            N++
        }
    }
}
```
Result:
![image](https://github.com/user-attachments/assets/7c1979fc-779b-47fd-b703-0a3ce3e2a5d9)

**Comment by unknao** [comment]
This was tested on the github version of Wiremod on a 32 bit server running on Win11 by the way.

**Comment by unknao** [comment]
Still a problem after the July 2024 update.

**Comment by deltamolfar** [comment]
Just tested it on x86-64 gmod branch, latest github. Can't reproduce

**Comment by unknao** [comment]
After diving into the code i can conclude that this problem was entirely caused by me using the PlayerSpawnObject hook elsewhere, preventing it from setting the model via WireLib.CanModel().
