### ISSUE TITLE
the old way of using sound in e2 vs the new one

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#3153]
so doing something like this: 

@name reverse_beep
@inputs Gear
@outputs 
@persist 
@trigger 
@model models/bull/various/speaker.mdl
interval(120)

if(Gear==-1){
soundPlay(1,0,"@hl1/fvox/beep.wav")}

works but what i expected is the @ would make the sound act as if you where facing it and it wasnt left / right of you. but instead it now does nothing where as sounds even 3 updates back this worked fine. why has this changed? can we get this working again and if so how? been up all night trying to fix this within e2 but i can't and im tired of trying (4 hours of it) any ideas would be nice!

**Comment by thegrb93** [comment]
The @ flag isn't in the list of allowed flags in WireLib.SoundExists. Just need to add it https://github.com/wiremod/wire/blob/1335bfade25f8e48c6001b5fa7e388e67c9fee8c/lua/wire/server/wirelib.lua#L1548

Can also add # probably

**Comment by Denneisk** [comment]
Here's this for a full list: https://developer.valvesoftware.com/wiki/Soundscripts#Sound_characters
