### ISSUE TITLE
Camera Controller not working with this issue.

### ISSUE THREAD

**Issue by tjrtk95** [wiremod/wire#3154]
[wire-master] addons/wire-master/lua/entities/gmod_wire_cameracontroller.lua:477: bad argument #2 to '__mul' (number expected, got function)
    1. __mul - [C]:-1
        2. UpdateOutputs - addons/wire-master/lua/entities/gmod_wire_cameracontroller.lua:477
            3. unknown - addons/wire-master/lua/entities/gmod_wire_cameracontroller.lua:564

How can I fix this problem? Help me!

**Comment by deltamolfar** [comment]
How to reproduce this issue?
