### ISSUE TITLE
vON issue

### ISSUE THREAD

**Issue by Astralcircle** [wiremod/wire#3168]
```
[wire-master] addons/wire-master/lua/wire/von.lua:357: vON: Number definition does not contain a valid number!
1. error - [C]:-1
 2. unknown - addons/wire-master/lua/wire/von.lua:357
  3. d_findVariable - addons/wire-master/lua/wire/von.lua:93
   4. unknown - addons/wire-master/lua/wire/von.lua:295
    5. d_findVariable - addons/wire-master/lua/wire/von.lua:93
     6. unknown - addons/wire-master/lua/wire/von.lua:295
      7. d_findVariable - addons/wire-master/lua/wire/von.lua:93
       8. unknown - addons/wire-master/lua/wire/von.lua:284
        9. d_findVariable - addons/wire-master/lua/wire/von.lua:93
         10. deserialize - addons/wire-master/lua/wire/von.lua:295
          11. func - addons/wire-master/lua/entities/gmod_wire_egp/lib/egplib/transmitreceive.lua:706
           12. unknown - lua/includes/extensions/net.lua:38
```
My players started getting an error from vON, maybe it's related to #3141

**Comment by Denneisk** [comment]
Possibly coming from NaN errors. `tonumber(tostring(0/0))` returns nil.

**Comment by thegrb93** [comment]
`tonumber(tostring(0/0))` doesn't return nil though in the lua version I'm testing

**Comment by Denneisk** [comment]
> `tonumber(tostring(0/0))` doesn't return nil though in the lua version I'm testing, 5.1.4

That's odd. I'm getting nil on mainline 5.4.6 and in LuaJIT 2.1.0-beta3 (Gmod).

I also realized while testing that a solution needs to account for infinity. I think extending the decoder to expect `nan`, `inf`, and `-inf` would be sufficient. We can't leave ambiguity here in case someone *needs* to store these values in a von table for whatever reason.

**Comment by thegrb93** [comment]
Gmod bug I guess. Will need to patch von.
