### ISSUE TITLE
E2 tables forget themselves if not persisted while not in strict mode

### ISSUE THREAD

**Issue by unknao** [wiremod/wire#3225]
A weird discrepancy between strict and non-strict e2 modes, if strict is disabled and the table is not persisted then it will forget itself.
Example code:
```
@trigger none
#@strict

T = table(
    "1" = "one"
)

timer("nutimer", 1, 1, function(){
    printTable(T)   
})
```

**Comment by Denneisk** [comment]
Yes, that's a "feature" of strict. It goes for all global variables.
