### ISSUE TITLE
Make Wires a Constraint, for Duping purposes

### ISSUE THREAD

**Issue by Nebual** [wiremod/wire#339]
[AbigailBuccaneer proposes](https://github.com/wiremod/wire/issues/335#issuecomment-21439872) we consider attaching a constraint to wired entities, so they may be duped even if they are not otherwise constrained (eg. a button on a map wall, wired to an E2 chip welded to an EGP screen welded to a map wall, all 3 can be duped without needing to constrain the button to the other two) . 

Though some may argue that since its been how it is since wire was first created, it is a bit more intuitive that wired things should be duped together.

The following works:

```
function constraint.Wire( Ent1, Ent2 )
    if ( Ent1 == Ent2 ) then return end

    local Constraint = ents.Create("info_node")
    constraint.AddConstraintTable( Ent1, Constraint, Ent2 )

    Constraint:SetTable( {
        Type    = "Wire",
        Ent1    = Ent1,
        Ent2    = Ent2
    } ) 

    return Constraint
end
duplicator.RegisterConstraint( "Wire", constraint.Wire, "Ent1", "Ent2" )
```

In this rough draft, the "constraint entity" is just a lightweight info_node, which I haven't even properly spawned into the world. It is automatically deleted when either Ent1 or Ent2 is removed (the DeleteOnRemove is ran by constraint.AddConstraintTable). I'm unsure how much we'd want to change Wirelib to actually use this constraint (1 per wire?), or if we should just make one per pair of entities (disallowing multiple Wire constraints per pair) and then ignore it. This is successfully found by the various constraint.FindConstraint functions, as well as constraint.GetAllConstrainedEntities which Advdupe uses to detect what a "contraption" is. 

This would enable Garrydupe and Advdupe to properly handle cases [like this](http://www.youtube.com/watch?v=ADxp6-as1OU).

Is this something we want to do?

**Comment by Nebual** [comment]
@AbigailBuccaneer Did this ever go anywhere?

**Comment by AbigailBuccaneer** [comment]
Not yet, but I'd still like to make it happen!

**Comment by thegrb93** [comment]
The constraint create constraint function will only accept up to 6 entities and doesn't pass the EntityList to the factory function so this is impossible for basic duplicator.

**Comment by thegrb93** [comment]
That is, if the wire anchor points are attached to entities. I don't remember if that's the case, but if it is, you'd be limited to attaching anchors up to 6 entities.

**Comment by thegrb93** [comment]
Yeah, it does.

**Comment by thegrb93** [comment]
I don't see any code that allows dummy constraints though.
