### ISSUE TITLE
E2 hologram irremovable ghosts when e2 is removed / onRemove not being called?

### ISSUE THREAD

**Issue by sammyt291** [wiremod/wire#346]
Hey,
When dupe is undone or the e2 is removed/destroyed holograms it has created have a small chance of becoming irremovable ghosts, although the remove all holograms con cmd may remove them but as of yet i haven't tested it. still its an annoying bug that occurs on servers when no admins can clear them up. hope an easy fix can be found
-Sam

**Comment by FreeeFry** [comment]
This still seem to happen when using hologram indexes < **0** ( specifically in my test scenario it was reproducable by `holoCreate(-500)` ).

The already "stuck" holograms would also be re-used when recreated, so if you had hologram X with some scale, model ,etc. and then respawned it, it'd retain the same settings until changed, `wire_holograms_remove_all` fixes it some of the time but not always.

**Comment by Divran** [comment]
Negative indexes create shared holograms (meaning they are shared between all of your E2s). This of course means that they will not be deleted automatically once the E2 that created them is deleted, and that's intended behavior.

If these holograms stay even when you attempt to run holoDelete/holoDeleteAll on them, then that would be a bug. Also, I believe they should be deleted if they are parented and their parent is deleted.

**Comment by FreeeFry** [comment]
That explains it, I must've missed that, sorry.
