### ISSUE TITLE
Merge a whole bunch of entities

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#397]
There is a piece of paper on my desk that says the following:

```
adv_emarker / emarker
dynamic_button / button / lever
dhdd / hdd
explosive / simple_explosive
thruster / vector_thruster
```

Now everybody have a huge argument about why they're all so different and couldn't possibly be merged.

_(This should be put on hold until AdvDupe2 stops sucking so hard. Yeah, AdvDupe 2 authors, you heard me.)_

**Comment by AbigailBuccaneer** [comment]
It might be time to do something about this, now that #173 and #572 are both fixed.

**Comment by immibis** [comment]
dataplug / plug

**Comment by thegrb93** [comment]
This will break a lot of dupes
