### ISSUE TITLE
Thruster weight as part of thruster settings

### ISSUE THREAD

**Issue by Anticept** [wiremod/wire#421]
http://steamcommunity.com/workshop/filedetails/discussion/160250458/864976115789020004/

For now, let's put in a weight setting to address this problem (and change existing thruster weights using a shift click or something).

As for the physics behind it for @Nebual , I remember someone figured it out long ago, but I don't remember where it was posted (wiremod.com?). I think it had to do something with weight \* force applied and some other operand involving friction.

**Comment by thegrb93** [comment]
There's other tools more suited to controlling weight. They should be included in gmod, but they're not, but if you're advanced enough to be balancing your contraptions' weight then I think you would be using such a tool on all parts of your contraption, not just the thruster, so I think this option would be obsolete.
