### ISSUE TITLE
E2 editor brace-matching syntax highlighting fails when braces occur in comments

### ISSUE THREAD

**Issue by Mandera** [wiremod/wire#447]
``` PHP
if(1) {
    # }
}
```

If you select the first bracket, it will highlight the end-bracket in the comment, not the actual end-bracket.

~~It would also be nice to have a section-comment function, so you wouldn't have to put `if(0) { ... }` around your code you want to comment.
For example `#{ Commented code }#`~~

**Comment by bigdogmat** [comment]
I did some work on this here (https://github.com/wiremod/wire/commit/578fe8d7de898b1ccdb7071f17fd29999bd83006). Only difference is now comment brackets aren't matched, though I don't think they're really necessary.

Assuming I can't think of a better way to do this I'll clean up the old code and make a pr.
