### ISSUE TITLE
EGP: Parented elements ignoring egpDrawTopLeft(1)

### ISSUE THREAD

**Issue by MouldyTaco** [wiremod/wire#497]
Parented elements base their position off of the center of their parent, even when egpDrawTopLeft(1) is present.

![Screenshot](http://cloud-2.steampowered.com/ugc/705106665866710173/D10B7CC08659C491B3FEA4DD6514566D307071EE/)

**Comment by AbigailBuccaneer** [comment]
I guess if `egpDrawTopLeft` is now officially deprecated then this can be closed.

**Comment by Divran** [comment]
egpDrawTopLeft was deprecated the instant it was created. I just added it because 20+ people bitched that they wanted it because they were too lazy to do `-size/2`
