### ISSUE TITLE
EGP screens with custom models sometimes don't spawn with a sensible screen size/position

### ISSUE THREAD

**Issue by Jake2149** [wiremod/wire#524]
This issue only happens about half the time, and I'm not sure how to reproduce it. Usually the model will have a black overlay over it for the EGP, but sometimes it doesn't . This only affects custom models that are used with the `wire_egp_model` command. This is from a saved file, and it has fixed itself before. I believe it was fixed by restarting the game, but I'm not one hundred percent sure about that. I can also spawn a completely different dupe that also uses egp screens that have the same model, and they can also have the same problem, but the one I just tried had working screens, while the first dupe had broken ones. The first dupe also has a default egp screen on it that works.

**Comment by AbigailBuccaneer** [comment]
It's probably best to defer creating the screen until `util.IsModelLoaded(self:GetModel())` returns true. This should be a fairly simple change.

**Comment by Jake2149** [comment]
I forgot that I had opened this, but a friend and I figured out that if you join a server while there are egp screens spawned in it, the issue will be fixed for the egp models that were already there. The fix you just suggested would probably fix it.

**Comment by Jack37** [comment]
Something similar was fixed for #782 in dbfb23bbe05c2c55d6cc87070b14ab849faad45a recently. Try to reload the screen.

**Comment by Divran** [comment]
Not gonna read the whole issue, but judging by the title, I've already fixed this in issue #782, as Jack37 said.
