### ISSUE TITLE
Multi Laungage

### ISSUE THREAD

**Issue by aoisensi** [wiremod/wire#535]
Will you support Multi-Laungage?
Maybe, Japanese, German, Chinese...

**Comment by Info-Screen** [comment]
@AbigailBuccaneer if there is still interest in this, I could set up community based translation for you.

(Users translate strings and vote on other users translation. After some time translations are automatically pushed to the repository, and are automatically applied in Game to users in which pulled the commit)

**Comment by oldmud0** [comment]
We had been thinking of doing i18n for a while now, but what service/tool would we use?

**Comment by CaptainPRICE** [comment]
Garry's Mod uses crowdin ([source](https://crowdin.com/project/garrysmod)).

**Comment by Info-Screen** [comment]
As it seams that there's still some interest I'll create a fork, set up translation and than create a pull request.

**Comment by Info-Screen** [comment]
Ok things seem to work. 

I'd like to test it a bit, before I submit my pull request.
So everyone who is interested in translating: https://weblate.info-screen.me/engage/wiremod/

Current translation status: [![Translation status](https://weblate.info-screen.me/widgets/wiremod/-/multi-blue.svg)](https://weblate.info-screen.me/engage/wiremod/?utm_source=widget)

If you wan't me to add another language create an issue at my fork or leave a reply here

&nbsp;

Btw. could someone reopen this issue?

**Comment by its-suun** [comment]
https://github.com/wiremod/wire/issues/1234
