### ISSUE TITLE
CPU editor writing to different folder than listing

### ISSUE THREAD

**Issue by Xandaros** [wiremod/wire#541]
The CPU editor lists and reads files from "cpuchip", but writes the files to "CPUChip"

This is likely only a problem on Linux, since Windows ignores case.

I somehow got it to work but after reloading the map it stopped working again and I could not reproduce that behaviour again, but I don't think it is important.

(And this time I tested it in singleplayer...)

**Comment by X-Coder** [comment]
Is this related to the last patch you did @AbigailBuccaneer?

I was searching for hours why mostly zcpu was halting with error#2 all the time and the debugger goes crazy, even with helloworld.txt.

Then I have seen, as soon as I attach the debugger, I will get this error in console:
"Erroring opening file: CPUChip\cpuchip/examples/helloworld.txt."

It happens with all programs, even with build in helloworld.txt in example folder.
But I use a windows server, so upper/lowercase could not be the problem, you have any idea why I get the error?

**Comment by AbigailBuccaneer** [comment]
Interrupt 2 is end of execution. Was this halting just caused by #851 or is this a separate issue? (And if so, post code, of course.)

**Comment by X-Coder** [comment]
Yes Interrupt 2 is caused by pressing reset (#851), I figured it out late at night.
