### ISSUE TITLE
Potential memory leak or GC bug

### ISSUE THREAD

**Issue by briman0094** [wiremod/wire#542]
I have been working on a huge project using E2 (automated train system) and as the project has been progressing, I've noticed that I start getting lag spikes the longer the system runs.

Originally when I only had a couple chips (such as a linear motor controller and accelerometer), I didn't notice any lag during the time I was working. Now that I have probably 20+ chips (sound controllers, train logic controller, motor controller/acceleration monitor, EGP processor, etc) on the train, I start getting noticeable lag spikes after about 5 minutes of gameplay. The framerate will drop to 0 for a few milliseconds, and the spikes get longer the more I play

I wrote a quick STool to read the amount of memory used by Lua, and when it reaches about 45k is when the spikes become noticeable. If I reload the map or delete the chips it goes away. I haven't been able to find a good profiler so I can't do much further debugging myself, but I can update my project repository if anybody needs to profile the chips.

**Comment by AbigailBuccaneer** [comment]
I don't think anybody's planning on doing anything with this, and there's nothing to indicate that this is caused by Wiremod.
