### ISSUE TITLE
EGP & Hud indicators disapper from screen when away from them

### ISSUE THREAD

**Issue by VigiFyre** [wiremod/wire#548]
Indicators disappear from player screen when player spends some time away from them. Probably because client doesn't know about entity anymore.

(EDIT: This initially also contained an enhancement request, which has been moved to #785.)

**Comment by AbigailBuccaneer** [comment]
This deserves splitting up into two issues: a bug about entities disappearing when invisible, and an enhancement about sorting HUD indicators.

**Comment by thegrb93** [comment]
The solution is
```lua
self:AddEFlags( EFL_FORCE_CHECK_TRANSMIT )

function ENT:UpdateTransmitState()
	return TRANSMIT_ALWAYS
end
```
If anyone wants to implement it.
