### ISSUE TITLE
Revival of the wiremod wiki, forum, and server

### ISSUE THREAD

**Issue by DarkChowder** [wiremod/wire#562]
As far as I can tell, the wiremod server, and wiki are both dead, and neglected. The issue is also pretty bad on the fourms too, with only two active moderators left, but at least it is not completly abandoned. 

Here are the steps that could be taken:
1. Someone needs to get in contact with admins in control of the servers.
2. The admins need to pass on control to someone who will take care of the servers.
3. Recruitment must be started. This will light a flame of helpfulness if it's done right. As everyone who wants to become a mod, or admin, will attempt to help.
4. If an admin plans on retiring in the future, the admin must be replaced so this does not happen again.

This might be a sensitive issue but these issues are hurting the Wiremod community more then any bug could. As far as I can tell nobody that is actively working on Wiremod is an admin on any of the sites that are about Wiremod.

**Comment by AbigailBuccaneer** [comment]
Nobody can be bothered to make any real progress on this, and if they did then it'd be more appropriate under a new issue (eg. "Revive official Wiremod build server" and "Move documentation to GitHub wiki").
