### ISSUE TITLE
Adv Dupe 2 Hacking

### ISSUE THREAD

**Issue by DarkChowder** [wiremod/wire#572]
How do we hack Adv Dupe 2, and make it alias our outputs, and inputs?
I see from the pod controller that to hack in a class alias we can do this:
```Lua
hook.Add("Initialize", "AdvPod_rename", function()
	local tab = scripted_ents.GetStored("gmod_wire_pod").t -- Grab this ENT
	scripted_ents.Register(tab, "gmod_wire_adv_pod") -- Set "adv_pod" to be defined as this ENT
	tab.ClassName = "gmod_wire_pod" -- scripted_ents.Register changes this to your argument, lets change it back
end)
```

So I vote we make a lua file that is specifically for encapsulating the pains of duplicating.
We could either make a class that lets you register Aliases, or we could change the `CreateInputs`/`CreateOutputs` to take Aliases as easy as this:
```Lua
On={"On","Go","Fire"}
Reload={"R","Reload"}
InputList = {On,Reload}
WireLib.CreateInputs( self, InputList )
```
The `ClassAlias` class can be modified to hack AdvDupe2 as well. 

Does Adv Dupe 1 have this issue?

**Comment by AbigailBuccaneer** [comment]
AdvDupe2 not respecting class aliases has been fixed by wiremod/advdupe2@561f8d6b5656ea283f6de0727339e2eaf3bdee55. Input/output aliasing has been implemented by @Divran, see #173.
