### ISSUE TITLE
Switch E2 to a time based ops system

### ISSUE THREAD

**Issue by DarkChowder** [wiremod/wire#577]
The Op cost system is not accurate, and does not protect a server from E2.

Here are the current systems two biggest flaws:
- Operations do not have a constant cost.
- Memory is not being monitored.

Adding a time limit to E2, while keeping the current ops system, is a solution me, and Divran came up with while brain storming.

**Comment by dvdvideo1234** [comment]
If you keep keep doing 

--WarningLevel ;

Everyone know what will happen next xD, reaching  Level > 5 :)
