### ISSUE TITLE
Adv Duplicator 2 + Wiremod crash.

### ISSUE THREAD

**Issue by Ripmax** [wiremod/wire#595]
When spawning a contraption that uses wiremod with advanced duplicator 2, it causes a server crash.
Errors Produced:
```
Error, Could not find the output entity
```
This is all the information I have unfortunately.

**Comment by AbigailBuccaneer** [comment]
@Ripmax unless you have a dupe we can use to test this, there's nothing we can do. Feel free to reopen with more resources for us.
