### ISSUE TITLE
HL-ZASM UDH and CSCR Drivers not loading and compiling correctly

### ISSUE THREAD

**Issue by gwicks** [wiremod/wire#619]
Whenever a program written using these drivers is compiled, such as the example programs, the source file itself compiles correctly, but does nothing when connected to a Console Screen's MemBus. Upon investigation, it looks like it errors out when compiling one of the zcrt files, init.txt, It throws an error stating "Undefined label: main", commenting out the line fixes the error message, but obviously doesn't fix the issue. Maybe it's some sort of bug in the implementation of loading HL-ZASM programs?

**Comment by immibis** [comment]
You probably need "preserve edx;" as well.
