### ISSUE TITLE
Increment operator does not work on table entries

### ISSUE THREAD

**Issue by schilcote** [wiremod/wire#630]
The following:

```
EjectVotes[Sender:id(),normal]++
```

...confuses the parser, which gives the error "statements must be seperated by comma or whitespace".

Instead, the following must be used:

```
EjectVotes[Sender:id(),normal]=EjectVotes[Sender:id(),normal]+1
```
... which is ugly and long.

It'd be nice if we could use the increment operator on array/table entries, since they're long enough already by themselves, plus the parser error makes no sense.

**Comment by AbigailBuccaneer** [comment]
If anybody wants to look into this, it doesn't look too hard - change the grammar around `Parser:Expr15` (which parses table subscripts) to be able to parse `T[i, "type"]++` and generate a different instruction, and then either change `Compiler:InstrINC` or add a new instruction type to handle incrementing table fields.

However, nobody's showing any sign of wanting to work on this, so I'll close it for now.

**Comment by TomyLobo** [comment]
This hasn't had any activity in a year. I wouldn't discount the possibility that it prospective developers have simply never seen this.

**Comment by AbigailBuccaneer** [comment]
Well, if somebody wants to do this, they're perfectly welcome to reopen it.
