### ISSUE TITLE
egpCursor() on EGP HUD's should show actual cursor position

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#635]
Currently it returns the position of the cursor on the hud model.

Would be nice to have for making menus.

One can work around it by calculating the position from eyeTraceCursor(), but it would be nice to have a "intuitive" way.

And _maybe_ a way to make the cursor show up without having to use C or Tab.

**Comment by VINTproYKT** [comment]
Still not implemented? It is really needed!
