### ISSUE TITLE
Class Version/Conversion System

### ISSUE THREAD

**Issue by DarkChowder** [wiremod/wire#646]
I think each class in wiremod needs to start containing it's own version number, so when any major changes are made to it, it's possible to convert old versions from dupe files to new versions. With a versioning system in place, bigger changes could be made. A method of translating from old versions, to new versions is needed as well.

**Comment by AbigailBuccaneer** [comment]
I've been doing things which involve [moving away from ever manually having to do any dupe logic](https://github.com/wiremod/wire/commit/7692a9bc1ad9ef668e739065f38da267f7ad8ceb), which I feel is a nicer approach than explicit versioning.
