### ISSUE TITLE
Wiremod Sound Emitter Volume

### ISSUE THREAD

**Issue by xProlithium** [wiremod/wire#671]
This is a rather simple question, from a person who doesn't really understand why it's happening.

When using the Sound Emitter, the volume of the sound is extremely low. I have already gone into the sound browser and upped the volume but it is still extremely quiet. It is not my game volume because every other sound effect is fine.

Also, when I change the pitch of a sound, and send it to the sound emitter, it does not save the pitch either.

I put this as a question because I wasn't sure if it was a bug/issue or user error, do I'd rather be safe.

My question is, why would the volume be extremely low, and why doesn't the pitch setting save?

**Comment by Novanance** [comment]
You know you should really tell us others who dont get how to do that how
