### ISSUE TITLE
New Menu won't fit on my Monitor.

### ISSUE THREAD

**Issue by ConnorMcF** [wiremod/wire#672]
If we could at least have the old menu in a toggable option, that would be nice.
The current menu is cramped on my monitor. For example sound emitter says 'Sou...' 
And I use wiremod alot, if the server does not have wiremod I find another

**Comment by oldmud0** [comment]
Any way of just turning off the tree so that things don't just keep getting pushed over to the right on every branch? That way, everything is aligned on the same column, and no space to the left is wasted.
