### ISSUE TITLE
lua/entities/gmod_wire_gpulib_controller.lua:24: attempt to index field 'screen' (a boolean value)

### ISSUE THREAD

**Issue by Mista-Tea** [wiremod/wire#710]
I'm afraid I don't have many details to give concerning what causes this or how to replicate it. It was a serverside error:

```
[Wiremod] lua/entities/gmod_wire_gpulib_controller.lua:24: attempt to index field 'screen' (a boolean value)
  1. unknown - lua/entities/gmod_wire_gpulib_controller.lua:24
```

There were 3 other players on my server when this error started occurring on what looked like a Think hook and caused the server to horribly lag. Removing all entities had no effect, so this was an internal error that I pretty much couldn't do anything about without restarting the server.

**Comment by AbigailBuccaneer** [comment]
Caused by some other addon.

**Comment by TomyLobo** [comment]
> Is there any reason that the GPULib controller doesn't use MakeWireEnt?

Probably not
