### ISSUE TITLE
Wiremod elements (esp.target finder) react strangely to Striders

### ISSUE THREAD

**Issue by imaskari** [wiremod/wire#713]
I think this is as much an issue with garry's mod as with wire mod, but I can't pin it down, and I can't gather enough evidence to point towards it being solely garry's mod's fault (that and it's an irrelevant bug outside of the context of wiremod), so I'm posting here.

Target finder continues tracking striders even after they've been removed/undone/killed. Getting an entity list from the console reveals no NPCs present. This can cause maps to become "gunked up" with residual striders, making targeting more difficult.

Repro:

1. Place target finder set to only target NPCs. Observe no target.
2. Use `cl_showents` in console to show existing entities.
3. Spawn strider. Observe that there is now a target in the target finder
4. Use `cl_showents` in console to show existing entities. Take note of what entities have been added by spawning the strider.
5. Delete the strider, either by undoing the spawn, using the remove tool on it, or killing it. Observe that it still displays in the target finder.
6. Use `cl_showents` in console to show existing entities. Observe that the list of entities no longer includes those entities added when spawning the strider.

Other weird things I've noticed while trying to test this. I don't know if any of these will help pinpoint the problem, but I figured I should share them.

* The Entity › Model gate returns t̶h̶e̶ ̶*̶n̶u̶m̶b̶e̶r̶*̶ ̶0 when querying the model of a strider (through the target finder), e̶v̶e̶n̶ ̶t̶h̶o̶u̶g̶h̶ ̶i̶t̶ ̶i̶s̶ ̶s̶u̶p̶p̶o̶s̶e̶d̶ ̶t̶o̶ ̶o̶u̶t̶p̶u̶t̶ ̶a̶ ̶s̶t̶r̶i̶n̶g̶.̶ N̶o̶t̶e̶:̶ ̶i̶t̶ ̶d̶o̶e̶s̶ ̶n̶o̶t̶ ̶o̶u̶t̶p̶u̶t̶ ̶"̶"̶ ̶l̶i̶k̶e̶ ̶i̶t̶ ̶d̶o̶e̶s̶ ̶w̶h̶e̶n̶ ̶i̶t̶ ̶h̶a̶s̶ ̶n̶o̶ ̶t̶a̶r̶g̶e̶t̶,̶ ̶b̶u̶t̶ ̶t̶h̶e̶ ̶a̶c̶t̶u̶a̶l̶ ̶n̶u̶m̶e̶r̶i̶c̶a̶l̶ ̶n̶u̶m̶b̶e̶r̶ ̶"̶0̶"̶,̶ ̶t̶h̶i̶s̶ ̶c̶a̶n̶ ̶c̶a̶u̶s̶e̶ ̶s̶e̶r̶i̶o̶u̶s̶ ̶e̶r̶r̶o̶r̶s̶ ̶w̶h̶e̶n̶ ̶a̶t̶t̶e̶m̶p̶t̶i̶n̶g̶ ̶t̶o̶ ̶f̶e̶e̶d̶ ̶a̶ ̶s̶t̶r̶i̶n̶g̶ ̶f̶r̶o̶m̶ ̶a̶n̶ ̶e̶n̶t̶i̶t̶y̶ ̶m̶o̶d̶e̶l̶ ̶g̶a̶t̶e̶ ̶i̶n̶t̶o̶ ̶a̶n̶ ̶E̶2̶ ̶c̶h̶i̶p̶.̶ <EDIT: this is incorrect. The 0 is a string.
* The Entity › Health gate always returns 32, so long as the strider ever existed. I believe striders use a different health system to ensure they can only be killed with explosions (I think this is true of helecopters as well, but the helecopters don't leave a residue after they've been deleted, so I don't care as much)
* The Entity › Is On Ground gate always returns 0. This is true of some other NPC's as well, but those actually fly.

Strider bodies can be removed with the default remover gun, while other ragdolls cannot. Some NPC's break apart into giblets after they die which can also be removed, but the strider is unique in that it stays together.

I think all this just goes to show that for one reason or another, striders are fundamentally different from other NPC's. This is more garry's mod's, or even HL2's doing than yours, but the target finder treats striders the same as other NPC's and I'd speculate that constitutes at least some of the problem.

**Comment by AbigailBuccaneer** [comment]
Realistically, there's nothing we can do about this - if a bunch of core Garry's Mod functions like `ENT:GetModel()` don't work on the Strider, then it doesn't make much sense for Wiremod to work around this. Feel free to report this over at [Facepunch/garrysmod-issues](https://github.com/Facepunch/garrysmod-issues/).

**Comment by Divran** [comment]
@AbigailBuccaneer nah wiremod shouldn't try to work around the issue, but almost no gates or E2 functions should ever return "nil" because that's not a valid zero value for most types (except entities).
