### ISSUE TITLE
pod controller don't spawn.

### ISSUE THREAD

**Issue by kalexandre** [wiremod/wire#731]
when playing a multiplayer game the pod controller don't spwan. so all advanced duplication working with it like a drone or the drunk combine wont work. you can still spawn it manually but for the drunk combine exemple... it is hard to redefine all functions. and when you finally make it and save your work the pod controller dont spawn :/

it works fine in singleplayer tho.

(there is another problem with the drunk crow or the drunk raptor. when using them they turn invisible. this apeared since wiremod came back to steam after it got deleted. don't know if itis wiremod's fault tho.)

**Comment by AbigailBuccaneer** [comment]
If you're still having camera controller problems feel free to open another issue, but the duplication seems to work fine.
