### ISSUE TITLE
Cant spawn anything using wiremod toolgun!

### ISSUE THREAD

**Issue by CMicro** [wiremod/wire#732]
```
[ERROR] addons/wire-master/lua/entities/gmod_wire_hudindicator/cl_init.lua:53: attempt to call field 'MakeSortedKeys' (a nil value)
  1. v - addons/wire-master/lua/entities/gmod_wire_hudindicator/cl_init.lua:53
   2. unknown - lua/includes/modules/hook.lua:82
```
Im using the latest wire-master.zip
Please help me!

**Comment by AbigailBuccaneer** [comment]
As @Divran says, this is caused by something going seriously wrong, causing entire files from Wiremod not to run (that run fine for everybody else) or something modifying the `_G.table` and deleting our methods from it.

I'd recommend deleting your Garry's Mod directory and re-downloading it.
