### ISSUE TITLE
EGP Graphics Issue

### ISSUE THREAD

**Issue by Computer600** [wiremod/wire#735]
Hello all,
I was doing my daily E2 and EGP buisness. Then I seen some grey lines appear on my screen. I did some testing and found that it happened when ever the egp screens were getting rendered and stopped when I moved completely away from them.
I have tried this on 2 computers now with the same result. I've attached what I see when looking at the EGP screens. Also I've tried it in singleplayer and multiplayer, and have reinstalled gmod + addons completely.
![2014-11-08_00021](https://cloud.githubusercontent.com/assets/2004493/4965897/f2b1f616-679c-11e4-944a-fe5fa9d1a21f.jpg)

**Comment by Nebual** [comment]
Closing as unreproducable.
