### ISSUE TITLE
Function to share holos with a specific e2?

### ISSUE THREAD

**Issue by shadowscion** [wiremod/wire#737]
Maybe something like `holoShare(N, E)` or `holoShare(E)`. Similar to the global holograms (using a negative index allows you to control the holograms from any e2). Would this be possible and/or easy to implement? It would be very useful for cases where you don't want to have to keep respawning a lot of holograms just to edit a few lines of code (yes, global holograms work fine for this UNLESS you want multiple copies of the contraption out at once). Alternatively, would it be possible to enable propcore functions such as `setAng` and `setPos` to work on hologram entities?

**Comment by thegrb93** [comment]
All of the hologram modification functions would need to modified or duplicated to incorporate shared hologram indices. Not feasible imo.

**Comment by shadowscion** [comment]
@thegrb93 Object oriented functions like setPos,setAng,setScale,setModel would work just as well. I had at one point written them but I think I got stuck on setScale for some reason.

**Comment by TomyLobo** [comment]
how about a sudo feature?
sudo(OtherChip, UserDefinedFunction)

The UserDefinedFunction would run in the context of OtherChip, if it is your own chip.

**Comment by TomyLobo** [comment]
how about a sudo feature?
sudo(OtherChip, UserDefinedFunction)

The UserDefinedFunction would run in the context of OtherChip, if it is your own chip.

What do you think about this, @thegrb93 @Divran

**Comment by thegrb93** [comment]
That'd work, kind of overkill, but useful for many situations, however does e2 behave correctly when moving between e2 contexts? I don't know enough about the internals to make that kind of judgement.

@shadowscion well pr your progress and ppl can help or add suggestions

**Comment by TomyLobo** [comment]
probably just have to make the E2 context a stack instead of a simple variable

**Comment by thegrb93** [comment]
You'd have to make a PR and prove its safety. I'm not ever going to work on e2 internals so that's up to someone else, but I'll add/fix e2 functions.

This request just seems strange to e2 because most things are never shared between them, e.g. sounds, effects, etc, but if @shadowscion makes a PR for this, I'm sure it would be merged.

**Comment by thegrb93** [comment]
I am worried about the object oriented approach because you'd have to make sure the hologram object and entity object can never mix, but I think that's most likely not a problem for e2. Is kind of a problem for starfall though.
