### ISSUE TITLE
E2 Vanilla constraint extension is missing important things

### ISSUE THREAD

**Issue by shadowscion** [wiremod/wire#738]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/custom/constraintcore.lua

The axis functions don't include the vector argument for axis of rotation, this makes it pretty much useless. The elastic constraint was also left out altogether.

**Comment by AbigailBuccaneer** [comment]
See [lua/includes/modules/constraint.lua:777](https://github.com/garrynewman/garrysmod/blob/2618ad7ece3cdd47731585acc29aceab870f46ed/garrysmod/lua/includes/modules/constraint.lua#L777) - if you pass in a local axis, then it just uses that position local to Ent1 for WPos2. You can easily do the calculations yourself and do this entirely with the two local positions, so I wouldn't describe it as useless at all.

If somebody wants to add these, we'll gladly accept a pull request, but it seems unlikely to happen any time soon.
