### ISSUE TITLE
Clientside Cam Controller doesn't work for players not present when it was spawned

### ISSUE THREAD

**Issue by shadowscion** [wiremod/wire#741]
If a player was not nearby (in the same area portal) or on the server when the cam controller was first spawned, the cam controller will not work for them unless they are near it and it is updated with the tool. The same thing happens for anyone who has a client lag spike/freeze.

**Comment by shadowscion** [comment]
This bug has once again shown it's face. This was on the github version of wiremod.

Test E2:
```
if (first()) {
    Entity = entity()
    
    Camera["Parent", entity] = Entity
    Camera["Position", vector] = vec()
    Camera["Distance", number] = 100
}

interval(90)
Camera["Activated", number] = Vehicle:driver():isValid()
```
• Spawn and link/wire a pod, cam controller, and the e2 in a closed off (area portal) part of the map and have someone who wasn't there sit in the pod
• Cam has these checked: "Coordinates Local to Parent", "Clientside Movement", "Clientside Zooming", "Auto-unclip", "Draw Player", "Draw Parent"

**Comment by Divran** [comment]
I think I know what causes it this time. Could you test this for me real quick? Go to this line https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_cameracontroller.lua#L776
and change it to just `self.NeedsSync = true` (erase the if statement so that it always runs)

**Comment by Divran** [comment]
Well I'm going to add this label back here because I just tested it with a guy and we couldn't reproduce it.

**Comment by shadowscion** [comment]
Use the map _gm_carcon_ws_, at the spawn location you will notice two garages to the left and right. Have one person enter each of those.

**Comment by shinji144** [comment]
Do you mean two different area portals or just one?

**Comment by Divran** [comment]
Still works on that map

**Comment by shadowscion** [comment]
@shinji144 Two different area portals.

**Comment by Divran** [comment]
Yeah we tested it when one of us was in one area portal and the other spawned the cam controller in the other, still worked
