### ISSUE TITLE
Output bar Not Showing up?

### ISSUE THREAD

**Issue by SoulShark** [wiremod/wire#749]
I've Had this problem With Multiple computers and have had to deal with it every time. The last time i fixed this i WIPED my whole computer then wiremod decided to wake up. I have no Lua Or Script errors. Ive checked The Wiremod Files. Everything seems OK. Ive also checked for corruption in the files and the scan came up blank. i Do Not know If there is A Disable Key for This To hide The WireMod Output bar (To be Clear It's the bar The You Can See when you hover your wiring tool over a Wiremod Entity)

Please help ASAP!

**Comment by TheFreezebug** [comment]
I can second this, this bug recently started occuring for me.

I've attempted manually calling the draw hook for the tool on HUDPaint, but unfortunately there is no output.

**Comment by Divran** [comment]
According to garry, there's a convar called gmod_drawhelp which disables this. Make sure that convar is enabled. https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua#L49

**Comment by AbigailBuccaneer** [comment]
@Divran this has come up a fair few times, and I think we should either:

* Move the HUD drawing to somewhere other than the tool's `DrawHUD` method
* Display a warning if `gmod_drawhelp` is 0
* Make a garrysmod pull request so that it still calls `DrawHUD`, and so `gmod_drawhelp` actually does only control drawing the help.

I like the sound of the third option best, I think.

**Comment by Divran** [comment]
That's assuming gmod_drawhelp is the problem

**Comment by TheFreezebug** [comment]
@AbigailBuccaneer Thanks, that fixed it.

@Divran gmod_drawhelp is definitely the issue.

For your fourth recommendation, would you not be having to override multiple tools though? More tools than just adv wire use the DrawHUD function. Tools like regular wire, multi wire, the debugger, etc. They all use some form of DrawHUD.

**Comment by Divran** [comment]
>For your fourth recommendation, would you not be having to override multiple tools though? More tools than just adv wire use the DrawHUD function. Tools like regular wire, multi wire, the debugger, etc. They all use some form of DrawHUD.

Nah, because every single tool in all of wiremod (ironically, except for adv wire) uses the base wire tool object. So we just have to override it once and it affects all tools.

**Comment by TheFreezebug** [comment]
![2015-01-21_05-18-58](https://cloud.githubusercontent.com/assets/3169571/5834562/0ce8651e-a12d-11e4-9540-b61e2ca76f8f.png)

Fair enough I guess. An override would be great for users that break it (Like myself -cough-).

Thank you both for your help in resolving this issue!

**Comment by SoulShark** [comment]
Thank You Guys For The Support! I Thought I Was Alone! xD

**Comment by AbigailBuccaneer** [comment]
This has been fixed by garrynewman/garrysmod@680666b1ed62b77517d156f8b0ffc35ba34e920f.

**Comment by Divran** [comment]
neat
