### ISSUE TITLE
White boxes showing instead of arbitrary hologram models

### ISSUE THREAD

**Issue by MrMomox** [wiremod/wire#750]
E2 Doesn´t work right; If i use an E2 from any other server on my server, it will not work. If i use an E2 wich spawn models/props, there are only white boxes instead of props -.- There are other bugs too for example; I´ve got an "autoforce" E2 (Handling fix for cars) and if I use it, my car gets pulled to the ground :/ Can you help me (Sry for my bad english (im from Germany))

**Comment by AbigailBuccaneer** [comment]
White boxes was, as @Divran mentions, just a configuration issue. If you need help with the other issue you mentioned feel free to make a new issue about it (being sure to share the E2 source code).
