### ISSUE TITLE
Damage Detector gives errors when players leave

### ISSUE THREAD

**Issue by Shadotak** [wiremod/wire#752]
Hooking a damage detector up to the players() array from E2 will give errors when a player leaves. The damage detector doesn't unlink from player that left and anything that happens afterward will give a big list of errors.
The damage detector will be "broken" and can't be unlinked from the array. This doesn't seem to happen with anything but players(), as other arrays and entities will work fine.

**Comment by Divran** [comment]
I've figured out what causes this. Going to try to fix it now.
