### ISSUE TITLE
egpTextLayout deletes '#' symbol before some keywords

### ISSUE THREAD

**Issue by BoggLog** [wiremod/wire#753]
![egptextlayout_bug](https://cloud.githubusercontent.com/assets/10134635/5365874/5703ee46-8000-11e4-9d91-4ca45dcd2854.png)

Maybe it is not a bug, but then how can I get rid of it?
I am writing E2 editor in E2, and I usually use comments with these words, so I think it needs to be fixed.

Test: Spawn EGP screen, then spawn E2 with this code near it.

```PHP
@name EGPTextLayoutBUG
#[ BUG with EGPTextLayout deleting '#' before some, not documented, keywords ]#

#examples:

#single
#multiple
#select
#file

#here '#' stays

findByClass("gmod_wire_egp") findSortByDistance(entity():pos())
find():wirelink():egpTextLayout(1,getCode(),vec2(),vec2(512))
```

**Comment by AbigailBuccaneer** [comment]
Is there anything that can be done to bypass [`surface.DrawText`](http://wiki.garrysmod.com/page/surface/DrawText) translating lines? Will `##` or something do it?

**Comment by AbigailBuccaneer** [comment]
Ah, apparently just adding a space to the end of the line is sufficient to stop it being translated. ([relevant Facepunch thread](http://facepunch.com/showthread.php?t=1345164&p=43464483&viewfull=1#post43464483))

**Comment by Divran** [comment]
Yes, annoying feature etc etc but I don't see any need to fix this. If anyone wants to display this with egp and such, they can just add a space to the end themselves. This doesn't do any harm to egp at all, so why not keep it? Maybe someone wants to use this feature.

However, I do agree with ftpje in that thread. It shouldn't have been this way to begin with. I'm just saying it doesn't cause any problems for us in this case.

**Comment by AbigailBuccaneer** [comment]
Fair enough. Well, @BoggLog, there's your solution. :arrow_up:
