### ISSUE TITLE
Add brace collapsing to E2 editor

### ISSUE THREAD

**Issue by ghost** [wiremod/wire#754]
Functionality is same as hiding functions, etc., but realization must be simple, I think
1. "+" button after number for each line, containing '{' or #[
2. when pressed, remember current formatting (spaces, newlines) and crop them to just single spaces, making whole content one-line.
3. when clicked on that line, return formatting to edit and set button to '-'

That would definitely make a lot of people writing loooong e2's happy
- I know about #include, but, taking in consideration e2's limitations, it's only usable for small, maybe for average-size e2's. When u write 5000 lines and must always think about size limit (about 227KB), includes only hurts.
  ![init_end](https://cloud.githubusercontent.com/assets/10134635/5366543/bc97f96e-8005-11e4-8ca0-8cd23e0e00ed.png)

**Comment by thegrb93** [comment]
ExpAdv2 will have this feature soon. Maybe they will allow you to borrow code from it.

**Comment by Divran** [comment]
Can't simply copy paste code from a completely different editor. That's not how it works
