### ISSUE TITLE
Clutch Controller vs AdvDupe2

### ISSUE THREAD

**Issue by bladedpenguin** [wiremod/wire#755]
I've got an ACF tank,with the wheels advballsocket'd together, but using the ACF transmission brake seems to make the wheels freak out. I tried using a wire clutch, connecting each of 7 wheels to the base, which worked beautifully, but when I use the advdupe2 to save my tank, only a subset of the clutch links will survive when I paste the dupe. i go from two clutches with 7 links each to 5 on one side and 3 on the other. Every time I paste that dupe, it has the same pattern, 5 on one side and 3 on the other, but if I then copy it again and paste, the next iteration will have ie. 2 and 3 links.

**Comment by AbigailBuccaneer** [comment]
Unable to reproduce in a simple test case, plus this is likely a problem with AdvDupe2 rather than Wiremod.

**Comment by thegrb93** [comment]
I'll look in a minute
