### ISSUE TITLE
holoModelAny allows models which the server does not have

### ISSUE THREAD

**Issue by MattJeanes** [wiremod/wire#757]
This causes error spam such as:

```
Model missing: models/colgate_player.mdl
Model missing: models/derpyhooves_player.mdl
Model missing: models/colgate_player.mdl
Model missing: models/derpyhooves_player.mdl
```

Not sure if the spam is caused by them making it every tick though

I suggest util.IsValidModel checking, or maybe a console command for it?

**Comment by MattJeanes** [comment]
Just tested it. Works nicely thanks.

**Comment by Willymcmilly** [comment]
I think your problem is that you're a ponyfaggot and the game wants to deprive you of your brony shit.

**Comment by MattJeanes** [comment]
@Willymcmilly someone else on my server was trying to use these models, which as you can see are missing from the server. Go redirect your unnecessary hate at them thankyou.

**Comment by Willymcmilly** [comment]
Why did you mention me, I never commented on this.

**Comment by MattJeanes** [comment]
Are you actually serious?

![image](https://cloud.githubusercontent.com/assets/2363642/5790933/82d06050-9ea9-11e4-81fc-0eeb3ed1a3ec.png)

**Comment by AbigailBuccaneer** [comment]
Locking issue.
