### ISSUE TITLE
E2 Editor Layer issue

### ISSUE THREAD

**Issue by Codingale** [wiremod/wire#760]
So a while back, about 1 or two years ago I had this issue, hadn't paid it much attention nor wanted to go through the effort of fixing it until now when I need those tabs.

This happens somewhat randomly and a restart/rejoin normally fixes it. I can't begin to think where it's coming from.

![Image of remote updater layered wrong.](http://i.imgur.com/HnOne19.png)
![Image of credits layered wrong.](http://i.imgur.com/6e8t73X.png)

**Comment by AbigailBuccaneer** [comment]
Let's assume this doesn't happen any more. Feel free to reopen if it does.
