### ISSUE TITLE
New tool+e2func & entity: entity:makePaper() & Printer

### ISSUE THREAD

**Issue by BoggLog** [wiremod/wire#765]
This idea is coming from long time ago where I wanted to make printer thing which prints something on props using turret. But it hopelessly failed because of very poor (30) dots limit. This limit makes it only possible to do that on ground, where limit is much higher (probably 256, not sure).
Would be nice to have a tool to make printing on prop possible, using special Printer tool.
So, how it could possibly work:
1. you spawn some (flat) prop. (maybe special props)
2. "paperize" one side of it using either tool or e2func
3. spawn Printer ent (inputs Color:vector PixelSize:number Clk:number  outputs PaperPos:vector2)
4. moving Printer and triggering Clk input, you can now draw something pixel-by-pixel

**Comment by BoggLog** [comment]
@thegrb93 problem is the limit. You can't paint more than 30 points on prop, so you can only print like 3 chars and others will be cleaned.

**Comment by thegrb93** [comment]
What I meant was, use a digital screen. Then take a ranger and aim it onto the screen and calculate where to change the pixel and change it. Not hard to do at all if you know some simple linear algebra.

**Comment by thegrb93** [comment]
Here's a quick e2 that works. I used a 1x1 plate as the screen model and 512x512 as the resolution.
```
@inputs DigitalScreen:wirelink RangerPos:vector RangerEntity:entity

if(RangerEntity==DigitalScreen:entity())
{
    P = DigitalScreen:entity():toLocal(RangerPos)
    X = floor((P:y()+23)/46*512)
    Y = floor((P:x()+23)/46*512)
    if(X>=0 && X<512 && Y>=0 && Y<512)
    {
        Address = Y*512+X
        DigitalScreen[Address] = rgb2digi(1,255,0,0)
    }
}
```

**Comment by AbigailBuccaneer** [comment]
If anybody wants to submit a pull request for a fully fleshed-out entity that does this then we'll consider it - but it seems incredibly unlikely that anybody on the Wire Team will work on this.
