### ISSUE TITLE
Wiremod fails to load on Garry's Mod 'dev' beta

### ISSUE THREAD

**Issue by Mista-Tea** [wiremod/wire#766]
See https://github.com/wiremod/wire/blob/master/lua/autorun/wire_load.lua#L18-22

This check causes Wiremod to entirely break on the server when on the `Dev branch` of GMod because its VERSION is currently 14.

Removing the check entirely resolves the loading issue.

However, it appears as though `Expression 2` fails to load extensions after making the edit. Opening any E2 results in the "Loading extensions. Please try again in a few seconds..." message to be displayed indefinitely. Spawning any e2 has the same result.

Switching the server back to the main branch (of GMod) corrects the issue, so there may be more inherent issues than just the version check above.

**Comment by Grocel** [comment]
So far I have heard Kilburn is writing a Lua interface for TBoI:R or something, which is likely making him too busy for the GMod update.

About that version checking: The version isn't supposed to be that low, it's a bug which wasn't been reported jet apparently.
