### ISSUE TITLE
Wire Adv Includes?

### ISSUE THREAD

**Issue by GmodSC** [wiremod/wire#771]
Wire_Adv seems to require something in sandbox/base gamemode? If I were to per se, make a skeleton gamemode the tool won't allow me to use TOOL:LeftClick, TOOL:RightClick, nor TOOL:Reload. But does allow for the mouse wheel but that doesn't have its own function to play with.

I have ran a few prints through the file and it all runs but never runs the mouse functions stated above which makes the tool unusable. (Note: All other wire tools work fine. And I have the ability to mouse scroll through the input options on the adv tool.)

Any input? Obviously, garry is lazy and requires people to have functions that define what a mouse click would be...

**Comment by GmodSC** [comment]
Lol, been too busy.. Sort of forgot about the issue. :8ball: 
No errors, possibly it requires a function in the sandbox gamemode to return true? If a function isn't added it will just return false somewhere.

**Comment by Divran** [comment]
Just copy paste the base tool files from garry's sandbox gamemode, should work.

**Comment by AbigailBuccaneer** [comment]
Shouldn't [`DeriveGamemode("sandbox")`](http://wiki.garrysmod.com/page/Global/DeriveGamemode) be all that's needed? If your addon doesn't do that then we have no intention of supporting it; if it does do that and it's still not working feel free to reopen.

**Comment by Divran** [comment]
Not sure if that would work, @AbigailBuccaneer since the tool object might not be included if you derive from sandbox. I could be wrong.
