### ISSUE TITLE
WireAdv tool not showing inputs/outputs

### ISSUE THREAD

**Issue by EtheoBoxxman** [wiremod/wire#774]
When i join the server i frequent, i try to use the advanced wiring tool, but when i aim at indicators, buttons, etc, no UI shows up, and i cannot blindly wire anything if i even try, and legacy wiring works only half the time.

the problem: http://cloud-4.steampowered.com/ugc/538510267203377936/31A87A4053B5AC4B092AC6AEC27AF53414C9C904/
Screenshot of Q menu: http://cloud-4.steampowered.com/ugc/538510267203374359/94ECD88836DC78A3B7E5753B7B149278AE86A9D3/
Addons: http://imgur.com/YHbHUdm

**Comment by Orzlar** [comment]
If this is still an issue,

I had the same issue on my server, the issue for me was; gmod on linux now requires GLIB_2.15 and without it all sorts of issues arise, mainly with stuff that require networking.   anyhow if your dist is ubuntu 12.04+ or CentOS7+, simply ugrade,update ;  else go here http://wiki.garrysmod.com/page/Linux_Dedicated_Server_Hosting#/Troubleshooting and follow the 'GLIB_22.15' not found troubleshooting .
