### ISSUE TITLE
egpAngle on Text doesn't work on emitters

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#776]
Just makes the text vanish.

Code to reproduce:

     EGP:egpText(1,"Emitter",vec2(255))
     EGP:egpAngle(1,45)

Works just as expected on normal screen and HUD.

TextLayout does not seem to rotate at all, but at least doesn't vanish.

**Comment by Divran** [comment]
I asked a guy with way more knowledge than me about drawing and stuff and he said he had no idea, so uh.. someone else will have to fix it. Until someone like that comes around, I'll label this as can't fix because I can't fix it.

**Comment by AbigailBuccaneer** [comment]
@Divran is this then caused by Facepunch/garrysmod-issues#1663 ?

**Comment by Divran** [comment]
@AbigailBuccaneer yep that looks correct

**Comment by AbigailBuccaneer** [comment]
I guess we just wait for an upstream fix then.
