### ISSUE TITLE
Option to protect E2 code

### ISSUE THREAD

**Issue by BoggLog** [wiremod/wire#777]
I can't think of cases when anybody could want admins/owner or anybody else excluding, maybe, friends, to copy his e2 without any questions, requests, etc. Especially if he worked on it for months or even years... Yeah, there are some kind of ways to "protect", like adding "if(duped())...", "if(owner():steamID!="...")...", but they all are just too easy to overcome. Last month some of my e2s I was working on were copied for at least 4 times, and I don't wanna see them released by some thief poorly modified...
So, I am currently thinking of how can I protect my codes, and the best way I found is:
1. obfuscating e2 on client just before sending to server, 
2. including e2 code to protect from executing by another owner, encoded and hardly visible
3. making it impossible for owners/admins/anybody not allowed to read your code or dupe the e2

And I suggest adding (1) and (3) to wiremod (obfuscation can be optional in e2 settings). Also, think about adv.dupe. I think, owners and admins must be able to delete anything, but there must be no way to copy others stuff for them. And the harder it will be to overcome the better.

**Comment by Divran** [comment]
http://www.wiremod.com/forum/expression-2-discussion-help/33768-e2-anti-theft-options.html

**Comment by BoggLog** [comment]
@Divran Okay, I got that u don't have time/money for that and server-side protection must be done with prop protection addons. Well, but what about just adding simple option to clientside obfuscation? I mean it can just replace numbers with hex, variable names with random mess, delete comments and newlines. I believe that's not hard to add and it really helps at some rate. Don't u think so?
I can try to implement it myself, if you agree.

**Comment by Divran** [comment]
Obfuscation can easily be done locally. Just make a script that opens your files and replaces those things you just mentioned, and then saves the files again under a different name (so you have the original)

**Comment by Divran** [comment]
https://github.com/Divran/simple-e2-theft-protection
