### ISSUE TITLE
Issues with Angle Gates

### ISSUE THREAD

**Issue by Mattdaman354** [wiremod/wire#778]
Tinkering around with the standard wire gates, I realized the "Direction gate" under the "Angle" section does not have outputs that specifies angles (pitch, yaw, roll); instead it outputs vectors (forward, up, right). Sure it has a "homogeneous" input "A [Angles]," but my contraption that I plan to build requires a specified angle for it work that I intended it to. Wiremod team, please fix this.

**Comment by Divran** [comment]
is this what you're looking for? https://github.com/wiremod/wire/blob/master/lua/wire/gates/entity.lua#L561

**Comment by Mattdaman354** [comment]
Yes that is the gate that I recently used, but I can't retrieve the info on a particular angle. I can't "isolate" the angle "yaw" for example for the rest of the gates to process.

**Comment by Divran** [comment]
Here you go, it's called "decompose" https://github.com/wiremod/wire/blob/master/lua/wire/gates/angle.lua#L132

**Comment by Mattdaman354** [comment]
Actually, its "Compose" lol. Anyways, there is no bug that hinders me so thx Dirvan.

**Comment by Divran** [comment]
You said you wanted to "isolate the angle 'yaw'", that's what the decompose gate does. The compose gate is the exact opposite, to construct an angle object using pitch, yaw, and roll.
