### ISSUE TITLE
EGP custom model dupe bug

### ISSUE THREAD

**Issue by evil128** [wiremod/wire#782]
I noticed a while ago that if you set the egp model with "wire_egp_model" and save it as a dupe it wont spawn propperly. I only tested this with SProps plates. If you just copy them it works fine but if you spawn the screen, then use adv dupe 2 to save it, rejoin the server and load it it spawns the screen without the actual screen. Other people on the server do see the screen only the pasting person gets this bug and a simple rejoin fixes it. I tryed it on another player too and he had the same issue.

**Comment by Divran** [comment]
Try it with adv dupe 1. Also try getting EGP tool and hitting reload on the screen, and then click reload rendertarget.

**Comment by evil128** [comment]
Reload rendertarget does not work. Dont have adv dupe 1 installed on my server...

**Comment by Divran** [comment]
Host a listen server (just set number of players to above 0 when creating a local game from inside gmod). See if you get the same problem there with adv dupe 2. If you do, install adv dupe 1 there and test it. That way, you don't have to bother installing adv dupe 1 on your server.

Quick zip download: https://github.com/wiremod/advduplicator/archive/master.zip

**Comment by evil128** [comment]
mkay gimme 10 min will report when im done. thanks for the quick respont

**Comment by Divran** [comment]
I'm also testing it as we speak (in a listen server)

**Comment by evil128** [comment]
ok tested both adv dupe 1 and 2. its a different result then on my server but still not how its supposed to be: http://steamcommunity.com/sharedfiles/filedetails/?id=369168914

**Comment by evil128** [comment]
If I do it on my hosted server the screen is just empty.

**Comment by Divran** [comment]
Both adv dupes seem to corrupt it somehow. If I spawn a screen using egp tool first, and THEN spawn via adv dupe 1 or 2, it work fine.

**Comment by evil128** [comment]
Any idea what could be causing this?

**Comment by Divran** [comment]
Yeah I have absolutely no clue what causes this, but it can be fixed by spawning a screen with that model using the tool first, so just do that every time

**Comment by Divran** [comment]
Since I can't figure out what causes the problem, I can instead add a button that you can press every time it happens. Basically I'm making the "Reload RenderTarget" button in the EGP tool (when you click "R" on an egp screen) reload the position of the screen as well as the screen itself.

I'm also adding EGP to the `Wire tab -> options -> Fix RenderTargets` menu. This does the same thing as clicking "Reload RenderTarget" with EGP tool.

**Comment by Divran** [comment]
AHA I think I figured out what causes it! If I'm right, I won't have to add those things I just mentioned. I believe the GHOSTS of the duplicator tool are interfering with it. I will test it shortly.

**Comment by evil128** [comment]
cool good luck ^^
