### ISSUE TITLE
Camera Controller doesn't work properly

### ISSUE THREAD

**Issue by zakimano** [wiremod/wire#783]
Whenever I try to wire the CameraController, it gives me this error. (yep, this is with the pure `gmod_wire_cameracontroller.lua`) I double-checked everything, tried to get this working for days, and also spent hours trying to understand the lua code, and almost got it working, but it's still a mess. (If you want me to upload the "fixed" file, just ask.)
Or just tell me what the hell am I doing wrong. (For this error I only wired the CamController's Active to an E2 chip output, but that only contained a value of 1.)

(PS: Looked the problem up on google, didn't find anything, and I didn't see any active issues here w/ this problem. Pls help, I think this is an important part of wiremod.)

![2015-01-04_00002](https://cloud.githubusercontent.com/assets/10390117/5606580/83ff273c-9435-11e4-9fb2-0b1e626ef304.jpg)

It says this:
```
Wire error (Entity [90][gmod_wire_cameracontroller]):
addons/trunk/lua/entities/gmod_wire_cameracontroller.lua:399: bad argument #1 to 'WriteFloat' (number expected, got function)
stack traceback:
	[C]: in function 'WriteFloat'
	addons/trunk/lua/entities/gmod_wire_cameracontroller.lua:399: in function 'SendPositions'
	addons/trunk/lua/entities/gmod_wire_cameracontroller.lua:416: in function 'SyncSettings'
	addons/trunk/lua/entities/gmod_wire_cameracontroller.lua:664: in function 'EnableCam'
	addons/trunk/lua/entities/gmod_wire_cameracontroller.lua:773: in function <addons/trunk/lua/entities/gmod_wire_cameracontroller.lua:770>
	[C]: in function 'xpcall'
	addons/trunk/lua/wire/server/wirelib.lua:62: in function 'TriggerInput'
	addons/trunk/lua/wire/server/wirelib.lua:495: in function 'Wire_Link'
	addons/trunk/lua/wire/server/wirelib.lua:674: in function 'Link_End'
	addons/trunk/lua/weapons/gmod_tool/stools/wire_adv.lua:160: in function 'func'
	lua/includes/modules/net.lua:32: in function <lua/includes/modules/net.lua:17>
```

**Comment by Divran** [comment]
It seems the "Distance" variable on the cam controller is a function for some reason. It should be a number.

Write this in your console, while looking at the camera controller
`lua_run_cl PrintTable(debug.getinfo(LocalPlayer():GetEyeTraceNoCursor().Entity.Distance))`
this should tell us where this function is defined. Post the results here.

**Comment by zakimano** [comment]
So, first of all, I do have the latest wiremod version, as I said before, I've had this problem for days - so I've set up TortoiseSVN, got the latest Wire from here, and when that didn't work, jumped into the lua code myself. (it's not that far jump for me)

Well, I did what you've asked for;

Wire error (Entity [556][gmod_wire_cameracontroller]):
addons/trunk/lua/entities/gmod_wire_cameracontroller.lua:391: bad argument #1 to 'WriteFloat' (number expected, got function)
stack traceback:
	[C]: in function 'WriteFloat'
	addons/trunk/lua/entities/gmod_wire_cameracontroller.lua:391: in function 'SendPositions'
	addons/trunk/lua/entities/gmod_wire_cameracontroller.lua:412: in function 'SyncSettings'
	addons/trunk/lua/entities/gmod_wire_cameracontroller.lua:659: in function 'EnableCam'
	addons/trunk/lua/entities/gmod_wire_cameracontroller.lua:766: in function <addons/trunk/lua/entities/gmod_wire_cameracontroller.lua:763>
	[C]: in function 'xpcall'
	addons/trunk/lua/wire/server/wirelib.lua:62: in function 'TriggerInput'
	addons/trunk/lua/wire/server/wirelib.lua:492: in function 'Wire_Link'
	addons/trunk/lua/wire/server/wirelib.lua:671: in function 'Link_End'
	addons/trunk/lua/weapons/gmod_tool/stools/wire_adv.lua:160: in function 'func'
	lua/includes/modules/net.lua:32: in function <lua/includes/modules/net.lua:17>

] lua_run_cl PrintTable(debug.getinfo(LocalPlayer():GetEyeTraceNoCursor().Entity.Distance))
linedefined	=	156
currentline	=	-1
func	=	function: 0x3ea73028
isvararg	=	false
namewhat	=	
lastlinedefined	=	161
source	=	@lua/autorun/slvbase/shared/slvbase_sh_meta.lua
nups	=	0
what	=	Lua
nparams	=	2
short_src	=	lua/autorun/slvbase/shared/slvbase_sh_meta.lua

Tough I don't think this tells too much. But: in the lua code, at the line 391, ( dist ) is an interesting thing, if set to ( distance ) then the new error is almost the same saying:

Wire error (Entity [556][gmod_wire_cameracontroller]):
addons/trunk/lua/entities/gmod_wire_cameracontroller.lua:391: bad argument #1 to 'WriteFloat' (number expected, got nil)

the rest is the same. As far as I remember, if distance is defined as (at line 23) " local distance = 1 " instead of " local distance = 0 " then the error vanishes, and a new one appears.
Hope this helps with the problem. ^^

**Comment by Divran** [comment]
The problem is you have an addon called "slvbase" that is overwriting the "Distance" variable of other entities.

**Comment by zakimano** [comment]
Thanks, (last time I was a little bit tired) removing this was really simple, though I didn't even knew about the existence of that thing...

**Comment by PeltGun** [comment]
I get the same error.
So I hit the lua_run_cl PrintTable(debug.getinfo(LocalPlayer():GetEyeTraceNoCursor().Entity.Distance)) console
This is the result.

] lua_run_cl PrintTable(debug.getinfo(LocalPlayer():GetEyeTraceNoCursor().Entity.Distance))
currentline	=	-1
func	=	function: 0x5c7a6db0
isvararg	=	false
lastlinedefined	=	161
linedefined	=	156
namewhat	=	
nparams	=	2
nups	=	0
short_src	=	lua/autorun/slvbase/shared/slvbase_sh_meta.lua
source	=	@lua/autorun/slvbase/shared/slvbase_sh_meta.lua
what	=	Lua

[Wiremod] lua/entities/gmod_wire_cameracontroller.lua:482: bad argument #2 to '__mul' (number expected, got function)
  1. __mul - [C]:-1
   2. UpdateOutputs - lua/entities/gmod_wire_cameracontroller.lua:482
    3. unknown - lua/entities/gmod_wire_cameracontroller.lua:573


[Wiremod] lua/entities/gmod_wire_cameracontroller.lua:482: bad argument #2 to '__mul' (number expected, got function)
  1. __mul - [C]:-1
   2. UpdateOutputs - lua/entities/gmod_wire_cameracontroller.lua:482
    3. unknown - lua/entities/gmod_wire_cameracontroller.lua:573


[Wiremod] lua/entities/gmod_wire_cameracontroller.lua:482: bad argument #2 to '__mul' (number expected, got function)
  1. __mul - [C]:-1
   2. UpdateOutputs - lua/entities/gmod_wire_cameracontroller.lua:482
    3. unknown - lua/entities/gmod_wire_cameracontroller.lua:573


[Wiremod] lua/entities/gmod_wire_cameracontroller.lua:482: bad argument #2 to '__mul' (number expected, got function)
  1. __mul - [C]:-1
   2. UpdateOutputs - lua/entities/gmod_wire_cameracontroller.lua:482
    3. unknown - lua/entities/gmod_wire_cameracontroller.lua:573


[Wiremod] lua/entities/gmod_wire_cameracontroller.lua:385: bad argument #1 to 'WriteFloat' (number expected, got function)
  1. WriteFloat - [C]:-1
   2. SendPositions - lua/entities/gmod_wire_cameracontroller.lua:385
    3. SyncSettings - lua/entities/gmod_wire_cameracontroller.lua:407
     4. DisableCam - lua/entities/gmod_wire_cameracontroller.lua:616
      5. ClearEntities - lua/entities/gmod_wire_cameracontroller.lua:846
       6. unknown - lua/entities/gmod_wire_cameracontroller.lua:601

What is the solution? I can not use the cam controller because of this error

**Comment by Tyler13700** [comment]
What addon is causing this? I can't find any addon that would resemble, or initialize or has an author by the name of "slv". Only thing I can think of is Gbombs 5. Whats causing it?

**Comment by Tyler13700** [comment]
Alright after some google research, I found what SLV Base is, and I dont have it. Any idea what is causing this? I have a few addons when I start a singleplayer, but aren't in my addon list or addons folder.

**Comment by Divran** [comment]
dunno

try doing an in-file search with an editor like notepad++ or sublime text to check for "slv" (or similar) in all files in your gmod folder.

**Comment by CaptainPRICE** [comment]
According to Google, it is Silverfag's SLVBase addon (search for it in your addons and lua folders).

**Comment by Tyler13700** [comment]
I dont have this addon, And I completely searched my steam folder entirely, then my gmod.

**Comment by bigdogmat** [comment]
@Tyler13700 If you could, post whatever

`lua_run_cl PrintTable(debug.getinfo(LocalPlayer():GetEyeTraceNoCursor().Entity.Distance))`

prints out in console here

**Comment by Divran** [comment]
@bigdogmat doesn't it need to be run on the server

**Comment by MaxShadow09** [comment]
Sorry for bumping this issue, but I was having the same problem. After looking inside a few gma's, I found that the conflicting mod is Half Life Renaissance. Apparently, it includes the slvbase. So if anyone else is still having that problem, try unsubscribing that mod.

**Comment by oldmud0** [comment]
Can we make a big list of "ADDONS KNOWN TO BE INCOMPATIBLE WITH WIREMOD"? Although some authors are quick to make fixes, some don't care, but either way people keep pestering about it.

**Comment by Divran** [comment]
I was thinking about making a small thing in wiremod which detects when known conflicts are installed and notifies the user, but I've not gotten around to it because effort

**Comment by oldmud0** [comment]
There are a lot of places that could be overridden by other mods. Would this even be feasible?

**Comment by bigdogmat** [comment]
I think the key word is ` known conflicts`, we can easily check for ones we know about.

**Comment by MaxShadow09** [comment]
I don't think there are that many mods conflicting with wiremod. I have lots of addons and everything works fine, except for the slvbase thing. As far as I know, mods conflict when there are functions, variables or files with the same names, or when someone does stupid things like making a function named "Distance", but if you keep your stuff properly organized, that shouldn't happen. Anyway, a list of known conflicts would be cool, even better if it's notified inside the game. I've seen quite many people complaining about this error, and HL Rennaissance is quite popular (even tho is really outdated). Fixing the conflict should be quite easy, but I think nobody is working on that addon anymore.

**Comment by Divran** [comment]
Having a function named distance is fine as long as it's only on your entities. It breaks because slvbase tries to add this function to EVERYONE'S entities
