### ISSUE TITLE
Couldn't include file cl_e2derma.lua [cl & sv]

### ISSUE THREAD

**Issue by Doliman100** [wiremod/wire#784]
Error to the client and the server console:
Couldn't include file 'entities\gmod_wire_expreession2\core\custom\cl_e2derma.lua' (File not found) (@addons/e2power/lua/autorun/autoloade2p.lua (line 11))

**Comment by Doliman100** [comment]
Sorry, it's e2p

**Comment by AbigailBuccaneer** [comment]
As in, this e2power? http://www.wiremod.com/forum/wiremod-addons-coding/29465-e2power.html

If so, you may want to read that thread.

**Comment by Divran** [comment]
And besides the malware, there's the fact that a very large chunk of the things it adds already exist in wiremod.
