### ISSUE TITLE
Heavily refactor the text editor

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#786]
Currently, the text editor exists primarily as a [single 2500-line Lua file](https://github.com/wiremod/wire/blob/master/lua/wire/client/wire_expression2_editor.lua). I think something of that scope needs to be broken down into smaller parts:

* The text editor is currently specific to E2/CPU/GPU/SPU. It would be nice if this weren't hardcoded - so that other addons could hypothetically define their own languages, and more realistically just to make the code easier to maintain.
* The current source is monolithic, and implements the entire editor component and all the panels and buttons around it in one file. I think it'd be nicer to split it into a core editor component plus stuff around it. Once again, hypothetically this would allow other addons to embed a rich text editor widget in things, but more realistically is just for ease-of-maintenance.
* The core idea of "a text editor in Garry's Mod" isn't specific to Wiremod - would it be worth pulling out into its own repository? I can see the benefits of doing so but I suspect there'd be far too much resistance.

**Comment by Divran** [comment]
Gmod has a stupid as fuck file limit. Before we consider making more files, we should come up with some way making something that merges as many files as possible in order to bypass the file limit. Maybe all the tools could be one file, and all the files in the wire folder could be one file. And all entities could be one file.

**Comment by AbigailBuccaneer** [comment]
I don't think it'd require many text files - if it were split up into the core E2 widget and the editor window with all its options that wraps the widget, and the language modes were moved to other relevant files that already exist, that'd only be one more text file than there is now.

**Comment by AbigailBuccaneer** [comment]
Let's call this closed-ish by #802.
