### ISSUE TITLE
EGP Text rotating in wrong direction

### ISSUE THREAD

**Issue by Kawoosh** [wiremod/wire#792]
Text rorates in other direction than other objects.
Possible solution is to negate angle value at [lua/entities/gmod_wire_egp/lib/objects/text.lua:91    ](https://github.com/wiremod/wire/blob/03972803dd6f6087479c848dab7d015e5bce10f9/lua/entities/gmod_wire_egp/lib/objects/text.lua#L91):
```Lua
matAng.y = -self.angle
```

Screenshots before fix (top) and after (bottom). Text in center parented to shapes, top left rotated manually.
![egptexttest](https://cloud.githubusercontent.com/assets/8239679/5796872/f31e195c-9fc0-11e4-96c3-824a52c833d4.jpg)

**Comment by Divran** [comment]
They seem to be rotated the same way to me according to your pictures. I haven't tested it yet myself, though.
