### ISSUE TITLE
[E2] Soundplay (Failed to play sound)

### ISSUE THREAD

**Issue by edunad** [wiremod/wire#794]
soundPlay doesn't seem to be working correctly.
[E2] Failed to play sound: playonce/scripted_sequences/glados_reawakened_01.wav
[E2] Failed to play sound: items/ammo_pickup.wav

Code :
holoEntity(1):soundPlay(2,0,"playonce/scripted_sequences/glados_reawakened_01.wav")
holoEntity(1):soundPlay(1,0,"items/ammo_pickup.wav")

Bass isn't finding the files at all.

I would recommend using normal Emitsound or what ever it was used before, instead of sound.PlayFile

**Comment by thegrb93** [comment]
That's really weird. Other sound files play without a problem. I tested sounds from counter strike, tf2, hl2, and it seems there are some that don't want to play.

I'll open an issue ticket on garrysmod-issues, I guess meanwhile we can roll back the sound library rework since the BASS module isn't ready yet.

**Comment by thegrb93** [comment]
Yeah I'm getting 
```
-1	BASS_ERROR_UNKNOWN
```
So BASS is finding the file, it just can't play the file for whatever reason.

**Comment by thegrb93** [comment]
```
] lua_run_cl sound.PlayFile("sound/ambient/forest_day.wav", "", function(...) print(...) end)
IGModAudioChannel [sound/ambient/forest_day.wav]
] lua_run_cl sound.PlayFile("sound/ambient/forest_day.wav", "3d", function(...) print(...) end)
nil	-1	BASS_ERROR_UNKNOWN
```

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/1752

**Comment by Grocel** [comment]
As I wrote in the other report:
> The problem is that BASS doesn't like auto looping *.wav sounds, if you try non looping ones they will work fine. I think it has something to do with the cues inside them. If you open them with a wav editor, you will see them.

**Comment by edunad** [comment]
Are you sure about that? I mean "items/ammo_pickup.wav" isnt a looping sound

**Comment by thegrb93** [comment]
Tell him that in the other conversation, Idk if he's watching this one.

**Comment by Grocel** [comment]
Yeah I'm pretty sure. There could a another format issue too. BASS got an update several weeks ago. They changes something about WAV file playback, maybe they fixed it.
