### ISSUE TITLE
E2 parser.lua language grammar is outdated

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#796]
[entities/gmod_wire_expression2/base/parser.lua](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/base/parser.lua) specifies, at the top of the file, the complete grammar of the E2 language... or at least it used to. The language has since been updated with things like user-defined functions and scopes, and the grammar has not been kept up-to-date.

This makes it quite hard to get started with hacking away at the parser and compiler. Would somebody be able to update it please? (@Divran?)

**Comment by Divran** [comment]
D:

**Comment by TomyLobo** [comment]
while you're at it, write it in a language that is compatible with a parser generator that can generate lua

**Comment by Divran** [comment]
thanks tomylobo for giving me an excuse to say I can't do it and you should do it instead

**Comment by AbigailBuccaneer** [comment]
I'm actually working on top secret plans for an Expression³ language, but don't tell anybody...
(I was doing text editor stuff before I got distracted, I should finish that first!)

**Comment by TomyLobo** [comment]
@Divran, you're just lazy and/or stubborn, just like with git :)

**Comment by AbigailBuccaneer** [comment]
So I'm looking at it and the grammar has always been informal and incorrect. I'm updating it now.

**Comment by AbigailBuccaneer** [comment]
```Lua
function Parser:SwitchBlock() -- Shhh this is a secret. Do not tell anybody about this, Rusketh!
```

**Comment by Divran** [comment]
hahaha
