### ISSUE TITLE
File browser becomes blank and unusable when a search has no results

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#803]
The file browser (which is used on the left-hand-side of the E2 text editor, as well as on the C-menu page for the E2 tool) becomes entirely blank when searching for something with no results. Clearing the search box (with the cross, or manually and pressing enter) will no longer restore the list of all files, and subsequent searches don't work either.

**Comment by Divran** [comment]
I'm in a hurry now so if you could test it some more that'd be great
