### ISSUE TITLE
e2 file funcs malfunctioning?

### ISSUE THREAD

**Issue by shadowscion** [wiremod/wire#804]
This was in singleplayer/lan...

```
@persist FilePath:string
@trigger none

if (first()) {
    FilePath = "myfile.txt"
    fileLoad(FilePath)
    runOnFile(1)
}

if (fileClk()) {
    local File = fileRead()
    
    if (File != "") {
        print(File)
    } else {
        print("Empty...")
        fileWrite(FilePath, "someContents")
    }
}
```

It works properly the first time you spawn the script, but any subsequent spawns and it will not trigger fileClk until you reload expression2 (wire_expression2_reload). Once you reload expression2, if the file exists, it seems to trigger just fine.

**Comment by Divran** [comment]
Any errors in console?
