### ISSUE TITLE
Wire HDD Not reading stored data correctly

### ISSUE THREAD

**Issue by LordZZT** [wiremod/wire#808]
Long Story Short, I noticed that random bits of data started to vanish and get jumbled in the Flash HDD.
It wrote correctly but didn't read correctly.
Problem was the GetFloatTable function attempts to read the data in 24 char chunks, but ended up getting misaligned.
The reason for the misalignment is line 117:
text = string.sub(text,24,string.len(text))

Two things, First no need to specify the end length. The sub function assumes that if it is nil.
Second the misalignment is caused because that 24 should be a 25.
An easy test to find the misalignment is just throw in a print(value) in the middle of that loop.

In other news Why is it all stored in text? Really?! Text?!

**Comment by oldmud0** [comment]
It's a limitation; Lua doesn't support unicode.

**Comment by LordZZT** [comment]
Regarding the fact its in text? If so I don't believe that is an issue anymore.
That sort of thing I believe was addressed back in the big filesystem update.
Which BTW, all the file functions Should specify the DATA directory.
Ex: file.read('FileName.txt','DATA')

**Comment by LordZZT** [comment]
Did I win?

**Comment by thegrb93** [comment]
You win the "report a bug and make people not want to fix it" award.

**Comment by LordZZT** [comment]
Thank god. I was worried something would be done about it.

**Comment by thegrb93** [comment]
"Killing spree!"

The expression2 file library is much better anyway. Why not use that?
