### ISSUE TITLE
holoScaleUnits changed?

### ISSUE THREAD

**Issue by thegrb93** [wiremod/wire#809]
Is holoScaleUnits behaving like it should? My hq_torus and hq_hdome_thin holograms are scaled weird now.

**Comment by Nebual** [comment]
Hologram scaling hasn't been changed on Wiremod's end since Nov 12th 2014 (which I believe was making it more like how it was Pre-April 2014). We are TRYING to be consistent!

I don't see any Gmod update recently either, so unsure.

**Comment by thegrb93** [comment]
Damn, well I'm stumped. I'll try it in singleplayer and see it I get the same thing. They were working just last week.

**Comment by thegrb93** [comment]
So before I was using
```
holoCreate(47,Ball:pos(),vec(),ang(180,0,0),vec(255,0,0),"hq_hdome_thin")
holoScaleUnits(47,vec(10.44))
```
And it was working fine and they were nice and round, but now I have to do this.
```
holoCreate(47,Ball:pos(),vec(),ang(180,0,0),vec(255,0,0),"hq_hdome_thin")
holoScaleUnits(47,vec(10.441,10.441,10.441/2))
```
Seems the z-axis BoxMin/BoxMax got changed or something

**Comment by thegrb93** [comment]
Maybe It's because I updated my wire models without knowing or something. These new values make more sense I think.

**Comment by oldmud0** [comment]
Wasn't there an update that "broke" entity scaling many months ago?
