### ISSUE TITLE
E2 supports k operator anywhere regardless of previous statements

### ISSUE THREAD

**Issue by OTC-** [wiremod/wire#812]
You can place the k operator anywhere in the E2 and it is still processed regardless if you want a quaternion or not. Can be spammed multiple times on one line, still ignored by the parser

**Comment by Divran** [comment]
Post example code, unsure what you mean

**Comment by Crypt0p** [comment]
```
@name Hello Divran!
@inputs 
@outputs 
@persist 
@trigger 

k k     k k  k k k k k k  k k          k k          k k k k k k
k k     k k  k            k k          k k          k k k k k k
k k k k k k  k k k k k k  k k          k k          k k     k k
k k k k k k  k            k k          k k          k k     k k
k k     k k  k k k k k k  k k k k k k  k k k k k k  k k k k k k
k k     k k  k k k k k k  k k k k k k  k k k k k k  k k k k k k

                                                                              k k
k k k k k k	 k k k k k k  k k     k k  k k k k          k k      k k     k k  k k
k k k k k k	 k k k k k k  k k     k k  k k k k          k k      k k k   k k  k k
k k     k k	     k k      k k     k k  k k     k k  k k     k k  k k k k k k  k k
k k     k k	     k k      k k     k k  k k     k k  k k k k k k  k k   k k k  k k
k k k k k k	 k k k k k k     k k k     k k     k k  k k     k k  k k     k k  k k
k k k k k k	 k k k k k k     k k k     k k     k k  k k     k k  k k     k k  k k

                                                                              k k
                                                                              k k

```
![Preview](http://i.imgur.com/I5qkRtV.png)

**Comment by Divran** [comment]
hahah that's hilarious. I say we leave it in, like the skyrim space program

**Comment by AbigailBuccaneer** [comment]
@Divran it's just plain broken. I'm strongly against leaving this bug in.

**Comment by OTC-** [comment]
```
@name 
@inputs 
@outputs 
@persist A
@trigger 

A

A
A
A
A
A

A

A

A
A
A
A
A

A
A
A
A
A
A

A
A
A
A
A
```

Validates.

E2 does not seem to care if you simply drop variables in the code.

**Comment by AbigailBuccaneer** [comment]
Hmm. I assumed this was a bug with tokenization, not a property of the language. I forgot that you could just separate statements with a space, and that any expression (including variables, or in the first case quaternion literals) would be counted as a valid expression.

This is the kind of thing most compilers would output a warning about. I have grand far-off plans for an Expression³ language with a decent sensible compiler, but until then I think it'd be too much work to add support for warnings just to warn about this.

**Comment by oldmud0** [comment]
Don't think of it as warnings not being supported by E2, think of it as the validator being set to `-Werror` by default :trollface:

**Comment by thegrb93** [comment]
What is the k operator? I've never seen it before.

**Comment by AbigailBuccaneer** [comment]
@oldmud0, it's more like the validator being set to `-w` :)

@thegrb93 it's used for quaternion literals, eg. `3i + 4j + 5k`. But `k` can also be used on its own as a quaternion literal, and so it's an expression on its own, and so it's a statement on its own.
