### ISSUE TITLE
Expression2 persisting without @persist?

### ISSUE THREAD

**Issue by UKIkarus** [wiremod/wire#815]
Writing an E2 with code to increment a variable output by 1 everytime a button is pressed without `@persist` is persisting anyway? should it not reset to 0?

Have not used wire in a long time so forgive me if not an issue, but I'm pretty sure that in order for a value to persist you need `@persist`?

Example (Crude but gets the point across)

```
@name bla
@inputs Button
@outputs Out
runOnTick(1)
if(Button)
{Out++}
```

Pressing the button makes Out increment without resetting to 0? shouldn't I need `@persist` for this?

**Comment by Divran** [comment]
Nah, because it's an output. persist is when you want to preserve a variable's value without it having to be an input or an output.
