### ISSUE TITLE
ZCPU Editor doesn't highlight block comments

### ISSUE THREAD

**Issue by Hati-** [wiremod/wire#816]
Example code:
```
// This is a single-line comment

/* This is a single-line comment. Code gets highlighted inside block comments. */

/*
    This is
    a multi-line
    comment.


    Code gets highlighted inside block comments.
    
        mov ESI, text;
        mov EDI, 65536;
    main:
        cmp #ESI, 0;    je exit;    // Exit code if ESI points to a null char
        mov #EDI, #ESI; inc EDI;    // Write char to digital screen
        mov #EDI, 999;  inc EDI;    // Set color to white
        inc ESI;                    // Move to next char
        jmp main;
    exit: 
        int 2;                      // Send interrupt 2 (End of program execution)
    text:
        db "Hello world!", 0;
    
*/
```
Resulted highlighting:
![Resulted highlighting](http://a.pomf.se/oyynma.png)

*Note that the ZASM code is ignored by the compiler because it's tokenized as a comment.*

**Comment by AbigailBuccaneer** [comment]
Looks like this just hasn't been implemented.

E2 highlighter: [`function EDITOR:SyntaxColorLine(row)`](https://github.com/wiremod/wire/blob/5054669685c0e51d0ac6cf0715078bfa7a237ba4/lua/wire/client/texteditor.lua#L3467)
ZCPU highlighter: [`function EDITOR:CPUGPUSyntaxColorLine(row)`](https://github.com/wiremod/wire/blob/5054669685c0e51d0ac6cf0715078bfa7a237ba4/lua/wire/client/texteditor.lua#L3620)

**Comment by oldmud0** [comment]
That's funny, how block comments haven't been implemented for this long.
While we're at it, could somebody move those "Run" and "Reset" buttons a few pixels down?

**Comment by Hati-** [comment]
Block commenting have been implemented since 2011 with commit https://github.com/wiremod/wire/commit/c1ca649b1a3191c32347322db0594ee94ff3ae66#diff-33da2d8c3809b670a3007931b2875bb6R94.

There's a lot of CPUlib features that are undocumented, hidden in the compiler's code or not finished.
I've taken the time to read through some of the compiler's code just to understand its inner workings and to find these hidden features. CPUlib is like a big treasure chest with lots of sand in it.
