### ISSUE TITLE
ZCPU Editor's validator stops working once it finds an error

### ISSUE THREAD

**Issue by Hati-** [wiremod/wire#817]
Steps to reproduce:

1. Have an error in your code.
2. Validate your code and have it catch the error.
3. Fix or remove the part of your code that contains the error.
4. Attempt to re-validate your code.

Nothing happens when you attempt to re-validate your code, regardless if your code is valid or contains another error.

**Comment by WHO-ARE-WE** [comment]
I have this as well.

**Comment by Hati-** [comment]
I want to point out that this was an issue before E2 editor got updates.

**Comment by Divran** [comment]
@PhoenixBlack

**Comment by AbigailBuccaneer** [comment]
Thanks @Hati-, this is no longer my concern! ;)
