### ISSUE TITLE
ZGPU opcode DWRITE and DWRITEFMT causes Lua error when string pointer is a float

### ISSUE THREAD

**Issue by Hati-** [wiremod/wire#818]
ZGPU code with error:

```C
mov eax, text;
add eax, 0.1;       // Turn string pointer into a float by adding a decimal

dcolor white;
dwrite pos, eax;    // Same error occours when using DWRITEFMT
dexit;
color white;
string text, "Hello world";
vec2f pos;
```

Error repeatedly printed in console whenever ZGPU is in view and running:

```
[ERROR] addons/wire/lua/entities/gmod_wire_gpu/cl_gpuvm.lua:832: attempt to compare number with nil
  1. ReadString - addons/wire/lua/entities/gmod_wire_gpu/cl_gpuvm.lua:832
   2. unknown - ZVM:[0]:8
    3. Step - addons/wire/lua/wire/zvm/zvm_core.lua:619
     4. Run - addons/wire/lua/entities/gmod_wire_gpu/cl_init.lua:159
      5. RenderGPU - addons/wire/lua/entities/gmod_wire_gpu/cl_init.lua:246
       6. unknown - addons/wire/lua/entities/gmod_wire_gpu/cl_init.lua:351
```

This Lua error also causes drawing of entities to break, as shown below:
![Example image](http://a.pomf.se/fcfbib.png)

**Comment by AbigailBuccaneer** [comment]
Hmm. Either `ReadCell` should handle non-integer values (either by rounding them or by returning 0) or instructions should verify that the operands are integers and error if not.

**Comment by Hati-** [comment]
Issue not fixed. Drawing of entities still breaks, and a another error occurs:

	[ERROR] addons/wire/lua/entities/gmod_wire_gpu/cl_gpuvm.lua:67: attempt to concatenate local 'interruptParameter' (a nil value)
	  1. Interrupt - addons/wire/lua/entities/gmod_wire_gpu/cl_gpuvm.lua:67
	   2. ReadString - addons/wire/lua/entities/gmod_wire_gpu/cl_gpuvm.lua:836
	    3. unknown - ZVM:[0]:17
	     4. Step - addons/wire/lua/wire/zvm/zvm_core.lua:619
	      5. Run - addons/wire/lua/entities/gmod_wire_gpu/cl_init.lua:159
	       6. RenderGPU - addons/wire/lua/entities/gmod_wire_gpu/cl_init.lua:246
	        7. unknown - addons/wire/lua/entities/gmod_wire_gpu/cl_init.lua:351

**Comment by Hati-** [comment]
`dwritefmt` seems to be more broken. An extra byte is required between the formatted text and parameters and a valid string parameter stops the formatter. This was a problem before IIRC.

**Example:**
```
    dcolor white;
    dwritefmt pos, text;
    dexit;
    
    color white, 255, 255, 255;
    vec2f pos,   255, 255;
    
    string text, "Test: %f %f %s World!";
    alloc  1;                                // Extra byte
    float  var1 = 10;
    float  var2 = 13;
    string var3, "Hello";
```
Outputs `Test: 10 13` on screen
