### ISSUE TITLE
Add Bezier interpolation/curves

### ISSUE THREAD

**Issue by OTC-** [wiremod/wire#820]
```
    function vector2 bezierVector2(Start:vector2,Control:vector2,End:vector2,Fraction)
    {
        return vec2(
            (1-Fraction)^2 * Start:x() + 2 * (1-Fraction) * Fraction * Control:x() + Fraction^2 * End:x(),
            (1-Fraction)^2 * Start:y() + 2 * (1-Fraction) * Fraction * Control:y() + Fraction^2 * End:y()
        )
    }
    
    function vector bezierVector(Start:vector,Control:vector,End:vector,Fraction)
    {
        return vec(
            (1-Fraction)^2 * Start:x() + 2 * (1-Fraction) * Fraction * Control:x() + Fraction^2 * End:x(),
            (1-Fraction)^2 * Start:y() + 2 * (1-Fraction) * Fraction * Control:y() + Fraction^2 * End:y(),
            (1-Fraction)^2 * Start:z() + 2 * (1-Fraction) * Fraction * Control:z() + Fraction^2 * End:z()
        )
    }
```

I already have something like this made in E2 and it could greatly enhance the experience of people who use PropCore or Holos to create animations or contraptions if this was added.

Based on this:
https://stackoverflow.com/questions/5634460/quadratic-bezier-curve-calculate-point

Examples: 
![](http://i.imgur.com/9ubCeqR.png)

[Video of something I made previously](https://www.youtube.com/watch?v=A4OWHF_35kk)

![](http://i.imgur.com/5MbVOE4.jpg)

**Comment by Nebual** [comment]
Thank you for posting working code, almost as good as a pull request :D
