### ISSUE TITLE
[E2] 2 suggestions

### ISSUE THREAD

**Issue by arduinium** [wiremod/wire#823]
Hello,

1) I would like a function similar to "enableConstraintUndo", but for E2 spawned props.

2) When I make an E2 that require a pod, I have to spawn the pod manually, everything else is done automatically by the E2. It would be very nice if we could create pods from the E2 itself so I just spawn my E2 and poof, a working vehicle is created (or whatever requiring one ( or more ) seat ). A function such as createSeat( "model" ) or seatSpawn or whatever.. ;)

What do you think? I can attempt to code these myself.

**Comment by Nebual** [comment]
I have both of these locally actually, I'll look at cleaning up the code for pushing.

**Comment by arduinium** [comment]
Hey Nebual thank you, I haven't tested yet but looked the code: is it really needed to delete the props when the E2 is removed? I habitually remove the props in last() or whatever. Sometimes it's good to be able to keep the props even if the E2 is removed.

While we are at it, why not add a function like propDeleteAll(), which would delete all props spawned by this E2. This could make things easier in some cases, instead of storing all props in a table and then doing table:propDelete()

And what about the podCreate function ? :)

**Comment by Divran** [comment]
You can make your own propDeleteAll like this

```
@persist Props:array

runOnLast(1)

if (Button) {
    Props:pushEntity(propSpawn(whatever))
}

if (last()) {
    Props:propDelete()
}
```

**Comment by Nebual** [comment]
I figure, you should be able to cleanup everything by mashing undo, so either you have Undo entries for each prop, or you Undo the E2. You can work around it either way.

**Comment by arduinium** [comment]
Divran I know that but it would just make things easier if we had one function to delete all without having to store all props in a table or array. But is not really needed.

Nebual, yes I think you are right. If I want to keep the props I just delete the E2 with the Remover tool, else I use enablePropSpawnUndo(0) ;)

**Comment by arduinium** [comment]
Nice, thank you for propDeleteAll(), but, looking at the code, there is a bug: in case the props were spawned with enablePropSpawnUndo( 1 ), propDeleteAll() will not remove those props, because they aren't added in the self.data.propSpawns table.

**Comment by arduinium** [comment]
Just another thing I think it's worth mentioning. You never actually remove the props from the self.data.propSpawns and self.data.propSpawnsAll tables.

Now imagine that the E2 is spawning a prop, then remove it, then spawn another, remove it... etc. The amount of items in the table will increase, but will never decrease. At the end of the day, the table will be so big, that it could trigger an infinite loop protection!

You have to use another way than a table with numeric indexes. If you used table[toString(entity)] = 1 or something like that, you could easily (and quickly) remove items from the table when needed (i.e in the propDelete functions).

Also you will need to reset the tables (table = {}) in propDeleteAll().

**Comment by arduinium** [comment]
I'm rewriting a bit of prop.lua to fix the issues I described, also improving the seatSpawn thing. It will be ready soon and I will post a link here.

**Comment by arduinium** [comment]
Ok here it is:

Add this line in cl_prop.lua:
```language.Add("Undone_e2_spawned_seat", "Undone E2 Spawned Seat")```

Then here is my modified prop.lua: http://pastebin.com/8BPEPjJF

As you can see I simplified things, added all setSpawn functions (and increased the cost), also increased the cost of the array/table:propDelete() and propDeleteAll(). And of course I fixed the tables issues I described above.

Forgive me, I don't know how to make a patch... Will learn ;)
