### ISSUE TITLE
Non-ASCII characters aren't allowed in the E2 editor

### ISSUE THREAD

**Issue by strelokhalfer** [wiremod/wire#824]
Hello!
Can you add in E2 editor support of Unicode characters(like as cyrillic)?
I can add them in external editor(like as Notepad++), but why additional problems?
Regards and sorry for my bad English.

**Comment by thegrb93** [comment]
I think this is more of a Garrysmod problem than an e2 problem.

**Comment by Divran** [comment]
>I think this is more of a Garrysmod problem than an e2 problem.

If the editor renders the characters properly after entering them via notepad, then I don't see why it can't be fixed somehow

**Comment by strelokhalfer** [comment]
thegrb93, many things support non-ANSI characers.

**Comment by Divran** [comment]
I just checked. The problem is gmod's text boxes don't detect all keys correctly. While it is possible to work around, you have to use some ugly hacks to get it working.

**Comment by strelokhalfer** [comment]
Hmm...
That Issue from Gmod, not Wire?

**Comment by strelokhalfer** [comment]
in "function Editor:SetCode(code)"
I add "self:GetCurrentEditor().TextEntry:SetAllowNonAsciiCharacters(true)"
after "self:GetCurrentEditor():SetText(code)"

It work. Add unnecessary chars(because cyrillic two-byte), but work.

**Comment by strelokhalfer** [comment]
![iss](https://cloud.githubusercontent.com/assets/4334058/6174187/3f9e2f2e-b2fe-11e4-9ca9-c1a518299836.png)

**Comment by Divran** [comment]
also that

**Comment by strelokhalfer** [comment]
Probably it's bug of gmod.
I had same problem with JPEX Decompiler(they used old parser`s dll)

**Comment by Divran** [comment]
It's a problem with http://wiki.garrysmod.com/page/surface/GetTextSize

**Comment by AbigailBuccaneer** [comment]
The issue in this case is that the cursor position is in bytes, and the graphical cursor position is calculated directly from the cursor position.

Ideally we would also support moving through the string codepoint-by-codepoint with the arrow keys (or even grapheme-cluster-by-grapheme-cluster but let's not run before we can walk).

**Comment by oldmud0** [comment]
The Cyrillic characters use a fallback font that is not monospaced.
It's funny, because even Notepad++ has this problem: if I choose a font that is monospaced but does not have the characters of another codepage (like Japanese), then those unknown characters get rendered in the fallback font which throws off the text editor.
The solution does not seem so simple as it looks.

**Comment by AbigailBuccaneer** [comment]
@oldmud0 the solution, I think, would be to use `surface.GetTextSize` to calculate the width of all the text before the cursor. That way, if it falls back to monospace it doesn't matter, as the cursor will still be aligned.

**Comment by BoggLog** [comment]
Oh no, don't fix that, I've already implemented their bahavior inside e2 about 4 yrs ago(... xD

> moving through the string codepoint-by-codepoint with the arrow keys (or even grapheme-cluster-by-grapheme-cluster

So much ++++

**Comment by AbigailBuccaneer** [comment]
I played around with this last night. `surface.GetTextSize` does indeed work nicely for the cursor position. Hopefully this evening I'll have time to sit down and write some code to step through the string by codepoint.

**Comment by Divran** [comment]
Maybe you could use some `string.find` and whatnot to find the weird characters so you don't have to step through everything

**Comment by GitSparTV** [comment]
The problem has nothing with GetTextSize or something. string library works on ASCII (256 chars), to fix cursor and highlight problem texteditor should use utf8 library, one problem is there's not pre-made sub/find/etc.
The fix is not the easiest, but it's doable.

I can't promise to help, but I have a desire to help.

**Comment by GitSparTV** [comment]
Here's some PIL (4th gen) pages about Unicode
![clipboard](https://user-images.githubusercontent.com/5685050/69829730-48f67e80-1232-11ea-913a-04b54962c6f9.jpeg)
![clipboard1](https://user-images.githubusercontent.com/5685050/69829735-4b58d880-1232-11ea-9cec-146cfacc4a8c.jpeg)

**Comment by thegrb93** [comment]
We use 5.1 but luckily gmod has some utf functions.

**Comment by GitSparTV** [comment]
Yeah, the behavior of gmod utf8 is almost the same as in Lua 5.3
