### ISSUE TITLE
runOnTick stopped working

### ISSUE THREAD

**Issue by arduinium** [wiremod/wire#825]
I believe this is due to this: https://github.com/wiremod/wire/commit/67ee58ed22c00721bd6de229909697e90e5a61fe

Also same problem with getConstraints, the returned array starts at 0 when it should start at 1.

Use " array[ #array + 1 ] = ent " instead

**Comment by Divran** [comment]
No need to use `array[#array+1]` in that examle. Can simply do `local i = 1` instead of `local i = 0`
