### ISSUE TITLE
What about a new function entity:shadow( enable ) ?

### ISSUE THREAD

**Issue by arduinium** [wiremod/wire#826]
Sometimes I really need to disable the shadow on some props ;)

It's really simple, just need to call this function: http://wiki.garrysmod.com/page/Entity/DrawShadow

**Comment by Nebual** [comment]
I should probably just commit all my private extensions at this rate, but then we'd end up with terribly named functions like E:isRed() [returns true if a particular entity is an E2 that has errored] in the API. 

I'll at least add some of the more useful ones to propCore.

**Comment by arduinium** [comment]
Thanks
