### ISSUE TITLE
E2 Editor improvement

### ISSUE THREAD

**Issue by sammyt291** [wiremod/wire#828]
Hello,

Would it be possible to disable tab from switching between function suggestions in the e2 editor?
![image](https://cloud.githubusercontent.com/assets/5092626/6197914/6002663e-b3e6-11e4-844f-857b5e763561.png)

I feel this would help when manually indenting or during correction of indentation.

or if not disable it, add an opt-out check box in the editor's settings in the 'Expression 2' tab?

Best Regards,
Sam.

**Comment by oldmud0** [comment]
I recall that you can customize tab-completion style in the options menu, from Visual Studio-style to Eclipse-style.

**Comment by sammyt291** [comment]
Ah, you are indeed correct, Thank you very much!
