### ISSUE TITLE
Small issue in the E2 Helper

### ISSUE THREAD

**Issue by arduinium** [wiremod/wire#830]
Everytime I open the E2 Helper, it open with the "CPU/GPU" checkbox checked instead of the "E2" checkbox, and with text "E2" in the Return search field. It's annoying to always have to remove this text and re-check "E2".

So I've searched a little, and found in `wire_expression2_editor.lua` at line 1366: `E2Helper.UseCPU(nEditorType)` . Replacing this line with `E2Helper.UseE2()` fixed both problems.

I'm not sure if it's the right thing to do, but it appear to work anyway ;)

**Comment by Divran** [comment]
This looks like a problem for @AbigailBuccaneer because editor rewrite

**Comment by oldmud0** [comment]
#802
