### ISSUE TITLE
ZVM's VTRANSFORM opcode does nothing.

### ISSUE THREAD

**Issue by WHO-ARE-WE** [wiremod/wire#831]
Hey guys, I've been trying to rotate a vector in ZCPU using a vector and a rotation matrix with the `VTRANSFORM` opcode. It didn't work though, so I decided to look around the ZVM source code. Turns out, the contents of the `VTRANSFORM` opcode are commented away without any explanation. Can this be fixed?

Thanks!

**Comment by oldmud0** [comment]
Looks like VTRANSFORM was never a working opcode from the [very beginning](https://github.com/wiremod/wire/commit/a5b9ee512fca76df5c63c9c19e1a59b0adcbe18d).

**Comment by WHO-ARE-WE** [comment]
I see. Does anyone here have enough knowledge to finish the implementation? I'm not that familiar with Lua.

**Comment by AbigailBuccaneer** [comment]
Looks like it just needs patching up to use the `Dyn_Emit` JIT system.
