### ISSUE TITLE
E2 JSON Support

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#839]
Its a pretty widely adopted format and often used in API's, so interfacing with them would be much easier and save performace when one could use the builtin [util.JSONToTable()](http://wiki.garrysmod.com/page/util/JSONToTable) and [util.TableToJSON( )](http://wiki.garrysmod.com/page/util/TableToJSON), instead of reinventing the wheel.

**Comment by oldmud0** [comment]
What would be the purpose behind using this?

**Comment by adosikas** [comment]
Many Web APIs use it, for example the Google APIs and the Steam API.

There many are things you could do with that, like translate, search and fetch infos for a youtube video playing or just query infos on a player like ingame hours or achievments.

Sure there are other ways like using a different API or using the limited regex implementation, but directly reading it from a table would be much simpler.

**Comment by Divran** [comment]
There would be a little overhead, though, since E2 tables have some extra values stored to keep track of types and such. You'd have to convert from E2 tables to normal tables first etc

**Comment by Divran** [comment]
haha this is hilarious. Garry's mod's json function has a huge as fuck problem. It can't properly differentiate between numerical indexes and string indexes. So this means if you do this:
`util.TableToJSON( { [1] = 1, ["1"] = 2 } )`
then you'll end up with **only** this json: `{"1":1}``
However, E2's table syntax actually SOLVES THIS PROBLEM because it keeps track of string indexes and numerical indexes in different tables.

**Comment by Divran** [comment]
examples

```
] lua_run_cl t = util.TableToJSON( { [1] = 1337, ["1"] = 9001 } )
] lua_run_cl PrintTable(util.JSONToTable(t))
1    =    1337
```

```
local Str = jsonEncode( table(1=1337,"2"=9001) )
print(Str)
local T = jsonDecodeTable(Str)
printTable(T)

# result =>
{"ntypes":{"1":"n"},"size":2,"n":{"1":1337},"s":{"2":9001},"stypes":{"2":"n"}}	
1	=	1337
2	=	9001
```

**Comment by Divran** [comment]
Now the other problem is that I have to add another function to properly decode json tables not created by E2.

**Comment by Xandaros** [comment]
JSON only supports string indices, so this is not actually an implementation problem.

**Comment by Divran** [comment]
yep I realized that after I posted the things above

**Comment by immibis** [comment]
@Divran JavaScript supports array indices; JSON does not, because JSON isn't JavaScript.
