### ISSUE TITLE
Constant Value not hi-speed compatible

### ISSUE THREAD

**Issue by Hati-** [wiremod/wire#844]
The Constant Value is supposed be hi-speed compatible according the the Lua code. However, this functionality is broken, and a Lua error may occur when attempting to read the constant values using hi-speed methods.

<h4>References:</h4>
 -  [lua/entities/gmod_wire_value.lua:138](https://github.com/wiremod/wire/blob/897fc2ba497aa4de2522f8a1a57a776163de0e27/lua/entities/gmod_wire_value.lua#L138)
 - [lua/wire/cpulib.lua:783](https://github.com/wiremod/wire/blob/897fc2ba497aa4de2522f8a1a57a776163de0e27/lua/wire/cpulib.lua#L783)

Lua error generated by E2 code `ConstVal:readCell(0) + 1`:
```
sv: Expression 2 (generic): entities/gmod_wire_expression2/core/number.lua:145: attempt to perform arithmetic on a table value
```

**Comment by Divran** [comment]
will take a look tomorrow

**Comment by Hati-** [comment]
The sound emitter have limited hi-speed support and the oscilloscope doesn't even have a hi-speed interface (missing ReadCell and WriteCell functions.) It would be cool if these could get an upgrade too.

**Comment by Divran** [comment]
Technically, the constant value already supports hi-speed for E2 (using `Wlk[OutputName,OutputType]`), but not for other things.
Unfortunately, if you use the readCell function (or the `Wlk[N]` syntax) with a constant value (which I've now fixed, just need to upload it), you can only retrieve numbers. If you want to retrieve any other value type, you have to use the `Wlk[OutputName,OutputType]` syntax instead.
