### ISSUE TITLE
[ERROR] entities/gmod_wire_expression2/core/glon.lua:223: bad argument #1 to 'getupvalue'

### ISSUE THREAD

**Issue by Zaddion** [wiremod/wire#848]
I don't know too much about lua, but I thought I'd post this lua error here. I've had it for awhile but I just ignore it. I just updated to the latest github version of wiremod hoping it'd be fixed, but it still isn't. I get this error on my server.

[ERROR] entities/gmod_wire_expression2/core/glon.lua:223: bad argument #1 to 'getupvalue' (function expected, got nil)
  1. getupvalue - [C]:-1
   2. fn - entities/gmod_wire_expression2/core/glon.lua:223
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:183

**Comment by arduinium** [comment]
Do you use ULX Autopromote addon ? See this https://github.com/wiremod/wire/issues/585

**Comment by Zaddion** [comment]
Yeah, I do have that addon. Thanks for the help, I hope it fixes it! :)
