### ISSUE TITLE
ZCPU's reset-button clears the cpu's memory

### ISSUE THREAD

**Issue by X-Coder** [wiremod/wire#851]
If I hit the reset button while in debugging mode of zcpu, it doesn't reset the program, it removes it from cpu and clears it's memory. I connected a E2 chip to read out the first bits of CPU's memory to verify it.

This is not how the reset button should work I think.

**Comment by X-Coder** [comment]
Did some more testing tonight on a different server (metastruct). Had the same issues there. It does not only happen when using the reset button, but also on the reset input.

**Comment by X-Coder** [comment]
Sorry, the problem was, as usual, in front of the screen.

After looking through the reset-sourcecode in zvm_features.lua, I found out it happend because I used a cpu type without internal rom. The reset button restores the program from internal rom, without that there is nothing to restore.

**Comment by AbigailBuccaneer** [comment]
Cool, one less bug for me to fix.
