### ISSUE TITLE
E2 Extensions not working

### ISSUE THREAD

**Issue by bigdogmat** [wiremod/wire#853]
I have all the extensions from the wire-extras svn enabled but none of the functions work in the e2 editor, not sure if this is from the recent fix for enableing/disableing e2 extensions or if wire-extras needs to be updated. Also extensions like propcore from don't work aswell.

**Comment by Divran** [comment]
@arduinium

**Comment by arduinium** [comment]
Did you type "wire_expression2_reload" ?

**Comment by bigdogmat** [comment]
Thanks the reload fixed it

**Comment by arduinium** [comment]
;)

By the way I found another issue and made some improvements, I will post another pull request tomorrow.
