### ISSUE TITLE
Implement new GetSubMaterial,SetSubMaterial of updated GMOD in E2

### ISSUE THREAD

**Issue by Kawoosh** [wiremod/wire#859]
There are good feature in new Gmod update. Will be very useful in e2.
[lua/entities/gmod_wire_expression2/core/entity.lua:366](https://github.com/wiremod/wire/blob/d652c2a3cdbe6695162237f5262918c4015ba20c/lua/entities/gmod_wire_expression2/core/entity.lua#L366)
```Lua

e2function string entity:getSubMaterial(index)
	if not IsValid(this) then return "" end
	return this:GetSubMaterial(index) or ""
end

e2function void entity:setSubMaterial(index,string material)
	if not IsValid(this) then return end
	if not isOwner(self, this) then return end
	if string.lower(material) == "pp/copy" then return end
	this:SetSubMaterial(index,material)
end
```
![e2submattest](https://cloud.githubusercontent.com/assets/8239679/6555931/d398d014-c67a-11e4-9946-26bd1be5dbd9.jpg)

**Comment by Divran** [comment]
Is there a function to get the amount of sub materials the model supports?

**Comment by Kawoosh** [comment]
I can't find any way to do it.

**Comment by arduinium** [comment]
Count ent:GetMaterials()

**Comment by Kawoosh** [comment]
ent:GetMaterials seems to work. And this table can be useful in e2 coding too, not only count of it.
ent:GetSubMaterial works in same way like ent:GetMaterial, it returns only overriden material name.

**Comment by arduinium** [comment]
Yes I just noticed that.

So you could make your getSubMaterial returns the entry (minus one) of the GetMaterials table if GetSubMaterial returns an empty string

**Comment by Kawoosh** [comment]
It can be useful getSubMaterial return empty string if not overriden to detect when material was just changed. GetMaterials always return original materials list of model.

**Comment by Nebual** [comment]
Added by #860
