### ISSUE TITLE
Update workshop

### ISSUE THREAD

**Issue by oldmud0** [wiremod/wire#864]
The workshop branch is 129 commits behind master: that's 2 months worth of commits. We should push an update.

**Comment by Jack37** [comment]
I agree, it should be done as soon as possible, either with or without merging some of the pull requests.

As for the actual Workshop update, we don't need to update it every day so I don't think that manual uploading would be bad. If the auto updater doesn't work and the person who manages it is hard to reach, we should be able to use the shared Steam account (WireTeam) - if that's what it's used for, and do manual update each two weeks or so.

**Comment by Nebual** [comment]
I'd prefer to see the latest round of PR's stay on the master branch
another week or so in case any issues arise, such as the last comment in
#790, and then we'll do a merge.

Regarding the WireTeam account, there were concerns Steam may disable the
account if they observed "account sharing". I'll discuss further automation
options with the maintainer.

**Comment by Divran** [comment]
I've been trying to get in touch with faron for like a month

**Comment by oldmud0** [comment]
Well whenever we do, one of us is going to have to type up a *really* long changelog explaining how the changes affect server owners and players.

**Comment by Nebual** [comment]
The current changes: https://github.com/wiremod/wire/compare/b44103a...master
 (yes I double checked, b44103a is whats currently live on workshop): 

I usually write up the posted changelog based on summarizing that list. Apparently we missed the January workshop push update. Troublesome.

There's some complaints that the recent Gmod update broke Workshop Wiremod, specifically E2. I find this unlikely, since master branch seems fine and we haven't patched anything version specific, but nonetheless that probably makes updating a high priority.

**Comment by Divran** [comment]
>There's some complaints that the recent Gmod update broke Workshop Wiremod, specifically E2. I find this unlikely, since master branch seems fine and we haven't patched anything version specific, but nonetheless that probably makes updating a high priority.

https://github.com/wiremod/wire/commit/3f6ef023c22743f88407e72a51b4985e181dcfec
this is the commit that fixes E2. It's not in workshop yet

**Comment by dsgassassin** [comment]
If we can get it on the workshop ASAP that would probably be good - Seeing as its breaking quite a few servers whos owners dont have the time to repeatedly check github for the updates and instead just rely on the workshop to auto-update the major errors when they arise.

**Comment by immibis** [comment]
Could someone else just do it instead (uploading it as a new thing under their own account), or must there only be one version on the workshop?

**Comment by AbigailBuccaneer** [comment]
@immibis that's not an option, for a variety of reasons (some legal, some practical, and some about the negative impact that would have on wiremod long-term).

**Comment by AbigailBuccaneer** [comment]
@FaronFox where are you :(

**Comment by immibis** [comment]
What about getting in touch with Steam? (I wouldn't expect anything from
any large company's customer support, but it's probably worth trying)

**Comment by FaronFox** [comment]
Done, sorry for the delay. Been busy with job etc.

**Comment by Divran** [comment]
Uh thanks but could you give someone else access to the steam account so that this doesn't happen? Someone mentioned that valve might not like account sharing, though, so how can we tell them that we need to do this because their workshop sucks?

**Comment by AbigailBuccaneer** [comment]
Given that the workshop file has multiple creators, is it possible for other developers to manually create and upload a `.gma` file? Or does it have to be the user who initially added it to the workshop (presumably WireTeam)?

**Comment by FaronFox** [comment]
Fairly certain it has to be WireTeam, it shouldn't be an issue again though. At least not for awhile. My VM broke.
