### ISSUE TITLE
soundPlay stops working when a specific sound is played 'too much'

### ISSUE THREAD

**Issue by mitterdoo** [wiremod/wire#866]
after making some e2's that make use of the soundPlay function, even with using a totally unique string index value, they will sometimes stop playing. as far as i know, it's caused when a sound is played, and then shortly after, no matter what the index is, playing it again. sometimes the sound just doesn't play because the other is still playing.

this e2 code should play the bell1.wav sound every 100 milliseconds, but you only hear the sound once and none overlapping. sometimes they even cut off. after a bit they just stop playing.
```
if( first() )
{
    timer( "test", 100 )
}
if( clk( "test" ) )
{
    soundPlay( toString( realtime() ), 0, "buttons/bell1.wav" )
    timer( "test", 100 )
}
```

**Comment by Divran** [comment]
I noticed possibly the same issue unrelated to E2 when I was trying to add sounds in Lua to an entity I was creating. I think it may be caused by the latest gmod update

**Comment by thegrb93** [comment]
I have the new code for the bass library. I can open a new pr.

**Comment by thegrb93** [comment]
This is a limitation of the engine. an entity can only have so many CSoundPatch attached to it.
