### ISSUE TITLE
Concommand wire_expression2_extension_enable

### ISSUE THREAD

**Issue by SeaLife** [wiremod/wire#867]
```
[ERROR] addons/wire-master/lua/entities/gmod_wire_expression2/core/e2lib.lua:527: attempt to index upvalue 'extensions' (a nil value)
  1. unknown - addons/wire-master/lua/entities/gmod_wire_expression2/core/e2lib.lua:527

] wire_expression2_extension_enable wiring

[ERROR] addons/wire-master/lua/entities/gmod_wire_expression2/core/e2lib.lua:543: attempt to index upvalue 'extensions' (a nil value)
  1. unknown - addons/wire-master/lua/entities/gmod_wire_expression2/core/e2lib.lua:543
   2. unknown - lua/includes/modules/concommand.lua:54
```

**Comment by arduinium** [comment]
Can't reproduce. Please explain how you did exactly. Make sure you restarted your server after updating wiremod.

**Comment by SeaLife** [comment]
Im using it via rcon, but typing it in console will cause this error :)
Thank you

**Comment by arduinium** [comment]
So I found the cause. Apologies for not testing this on a true dedicated server... I'm fixing it but it's harder than I thought, I'm stuck trying to make the concommand autocomplete working client side. To @Divran etc, please do not update the workshop until this is fixed. Sorry again :(

**Comment by arduinium** [comment]
I think it's ready but I want to be sure so I test really carefully this time. I will make a pull request in about an hour, unless problems.
