### ISSUE TITLE
i cant even play gmod when i downlowed it BUG

### ISSUE THREAD

**Issue by snakerocks22** [wiremod/wire#872]

**Comment by awilliamson** [comment]
Best, bug report, ever... 10/10

**Comment by titanic4** [comment]
Give more info about the error you get. To ensure that is not caused the external compatibility problem, disable all addons, with exception of wiremod then start the map of your choice.

**Comment by AbigailBuccaneer** [comment]
Give us some actual details, or we can't help. Reopen the bug when you do so.

**Comment by oldmud0** [comment]
plz reinstal; ur gmod. den restart windoze.
