### ISSUE TITLE
Garry's Mod Crashes when trying to open Expression2 Files

### ISSUE THREAD

**Issue by Chippyy** [wiremod/wire#873]
Ever since the new GMod update, I keep on crashing when I try to open E2 files. Other people can open it, some people I know can't. I use a mac, but I'm not sure if that's the reason.

**Comment by arduinium** [comment]
Are you using the Github version or the workshop one?

**Comment by Chippyy** [comment]
I tried using github and workshop version, none worked.

**Comment by arduinium** [comment]
I have to ask because people these days... Did you disable/uninstall the workshop one before installing the Github one? It's needed because if you have both versions, it's the workshop one that is being loaded in Gmod.

**Comment by Chippyy** [comment]
yes.

**Comment by oldmud0** [comment]
Does the crash produce a .dmp file on your GarrysMod folder? We might be able to analyze it. In the meantime though, check your access permissions.

**Comment by Chippyy** [comment]
I can't find a .dmp file anywhere, and I only spent 10 minute in my gmod file looking for them. I'm pretty sure it's just I can't find them, because this is actually the first time I heard someone mention a .dmp file.

**Comment by thegrb93** [comment]
It's actually .mdmp

**Comment by CaptainPRICE** [comment]
> Ever since the new GMod update

That would be "Garry's fault".
@Chippyy Is it still crashing for you?
