### ISSUE TITLE
New garrysmods.org site, should I post wiremod?

### ISSUE THREAD

**Issue by Divran** [wiremod/wire#875]
Have a read here http://facepunch.com/showthread.php?t=1456612 or https://garrysmods.org

This site is the replacement for garrysmod.org. The really nice thing is that it supports specifying an external URL for downloads as well as uploading the addon as a zip file. What this means is that we can give it https://github.com/wiremod/wire/archive/master.zip this link and voila, auto updated wiremod, so we never have to touch the site again lol. Should I do it?

**Comment by Divran** [comment]
@Nebual @AbigailBuccaneer @TomyLobo @Jack37

**Comment by thegrb93** [comment]
Seems kind of pointless for a mod that gets updated regularly.

**Comment by Nebual** [comment]
I think it'd be a good idea to post us there, if people want to use that method they can. Obviously we'll continue recommending git/workshop, but users will be users.

**Comment by TomyLobo** [comment]
the top-level folder in that is "wire-master", which sucks a bit. can you get rid of that "-master" with a parameter maybe?

**Comment by Divran** [comment]
>the top-level folder in that .zip is "wire-master", which sucks a bit. can you get rid of that "-master" with a parameter maybe?

dunno

**Comment by natrim** [comment]
or rename wiremod to: Wire Master
XD

**Comment by AbigailBuccaneer** [comment]
> Garry has very kindly agreed to point the http://garrysmod.org domain at the site, despite his feeling that a site like this is no longer required (but acknowledges that a lot of people would disagree with that)!

Pros:

* It's easier to update than the Workshop. (You can upload from a URL, but I don't think it'll auto-update from that URL, so it wouldn't be completely painless - but we could hypothetically set up a webhook and start using the Release feature of GitHub to automate it.)
* It means others are less likely to upload it and then forget about it, and we don't have people using an outdated third-party version. (The forum thread explicitly encourages this after a delay: "PLEASE DO NOT UPLOAD ALL OF YOUR ADDONS THAT YOU DID NOT CREATE YOURSELF. Give the original author's time to upload their own work, and fill in the blanks after some time has passed".)

Cons:

* It's another distribution method to maintain
* Which means the potential for there being *three* different 'latest' versions in the wild
* It won't automatically update when people install it, unlike the workshop

All in all I would prefer we didn't, but if majority opinion is in favour then I'm okay with that. I think the lack of auto-updating is the biggest issue - with workshop, it doesn't matter how little you care about up-to-date addons, it'll take care of that for you - whereas garrysmod.org doesn't offer that.

I also like the fact that currently we're distributing it via channels we control (GitHub) and official channels (workshop). I don't see a compelling reason to ever use any third-party distribution channel, which we don't have control over and which doesn't have the official Team Garry Seal Of Approval.

**Comment by Divran** [comment]
>It's easier to update than the Workshop. (You can upload from a URL, but I don't think it'll auto-update from that URL, so it wouldn't be completely painless - but we could hypothetically set up a webhook and start using the Release feature of GitHub to automate it.)

When "uploading" from an URL, I was under the assumption that users who click the download link will simply be redirected to that URL instead of downloading it off of garrysmods.org
I'm pretty sure this is the case since the max upload size is 200 mb, and this URL feature was added to solve that problem without increasing the max upload size.
So this means we just have to give it the URL once, and since github's zip link never changes, it will auto update as long as the user redownloads it every time.

**Comment by AbigailBuccaneer** [comment]
Ah, I assumed it would download it from that URL and then serve it as normal (which circumvents uploading limits in web servers). If all it is is a redirect to our GitHub link, that's quite different - in that case I'm in favour of this, but I think the URL should point to the `workshop` branch, not the `master` branch.

Is there any way we can check if a version installed from the `workshop` branch isn't the latest, and display an error message? @Divran I know you have experience messing with the GitHub API from Garry's Mod.

**Comment by AbigailBuccaneer** [comment]
If we want to use `wire_version.txt` I think it'd make sense to start using proper versioned releases on the `workshop` branch - eg. it'd contain "2.4.3" or whatever instead of a branch and commit hash. It's fairly common for projects to have a commit saying something like "bumped the version number to 2.4.3 in preparation for release" every release.

**Comment by TomyLobo** [comment]
maven-release-plugin *g*

**Comment by AbigailBuccaneer** [comment]
Most of the popular addons on the website are old ones imported from the old garrysmod.org. The site isn't popular, and I don't want to have to deal with the hassle of another place to upload it.

**Comment by TomyLobo** [comment]
Plus the main venue for addons is the workshop now, so why post it anywhere else?
If people want to tinker, they should clone the git repo, not download a dated version from some page

**Comment by AbigailBuccaneer** [comment]
@TomyLobo The new garrysmod.org was made when the Workshop hadn't entirely taken off, and so it hadn't established itself as the main venue for addons. There were worries that garrysmod.org would be as popular as it used to be (where we often did have people installing from there). Fortunately that hasn't happened so we're all good :)

**Comment by oldmud0** [comment]
I think it's also a place for addons with incompatible licenses or explicit content.

**Comment by TomyLobo** [comment]
i.e. not a place where we really want to be :)
