### ISSUE TITLE
wirelink:writeArray always null-terminates

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#879]
While the E2Helper states:
"Writes an array's elements into a piece of memory. Strings and sub-tables (angles, vectors, matrices) are written as pointers to the actual data. Strings are written null-terminated"
even arrays containing just numbers are written null-terminated.

This is quite annoing if you try to use it to draw onto a digitalscreen. since it will always add a black pixel after the array unless you "backup" that pixel and restore it after writing the array.

Example Code (on a 512x512 screen):

```
Screen[1048574]=0 #Clear
Screen[1048569]=3 #Color Mode
Screen[1048572]=512 #Y Res
Screen[1048573]=512 #X Res
Screen[1048575]=1 #Apply changes
function drawCircle(X,Y,Size){
    Color=rgb2digi(randvec(0,255),3)
    for(YO=0, Size,1){
        Width=round(2*sqrt(Size^2-YO^2))
        #Efficent method of making a array containing "Width"-times the wanted color
        Array=array(Color)
        for(I=floor(log2(Width)-1),0,-1){
            Array=Array:add(Array)
            if(Width&&2^I){
                Array:pushNumber(Color)
            }
        }
        Screen:writeArray(max(X-Width/2,0)+512*clamp(Y-YO,0,512),Array)
        Screen:writeArray(max(X-Width/2,0)+512*clamp(Y+YO,0,512),Array)
    }
}
drawCircle(200,200,10)
drawCircle(200,200,5)
```

![Screenshot](http://i.imgur.com/zYg1LDr.png)

**Comment by Divran** [comment]
looks fine to me https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/wirelink.lua#L62-L92

**Comment by adosikas** [comment]
Yeah i checked the code, after i noticed the black pixel.
It would make sense to have it there if there were no dedicated writeString() method, or readArray() had no size parameter (which might have been the case before), but at the moment i don't really see the point in it.

The && is intended btw, that alorithm is a adaptation of [this](http://en.wikipedia.org/wiki/Exponentiation_by_squaring), so it finishes filling the array in log_2(n) instead of n, which is significantly faster when trying to fill arrays past a certain size (for 100 it is not 100 iterations, but just 6, 100_10=1100100_2). Each iteration duplicate the array, if the bit is 1 at the I-th position also add one value. 1=>2->3=>6=>12=>24->25=>50=>100

**Comment by TomyLobo** [comment]
iirc, I wrote writeArray back then. The reason for the trailing null byte was to accomodate Wire CPU, I think.
Since people may or may not depend on the trailing null byte, you should make another method which doesnt place a trailing null byte.

The wiki is down right now so I can't check whether the null byte behaviour is documented.

**Comment by adosikas** [comment]
From the wiki (same as E2Helper):
>Writes an array's elements into a piece of memory. Strings and sub-tables (angles, vectors, matrices) are written as pointers to the actual data. Strings are written null-terminated. 

Any update on this?

**Comment by TomyLobo** [comment]
so, if there is no 0 byte at the end of the string, how do you know where the string ends?

**Comment by adosikas** [comment]
Its not about the strings being null-terminated, that is perfectly fine.
What my issue here is that arrays (and tables i presume) also null-terminate (as indicated by the black pixel in the screen), and that that behavior is, (in constrast to strings) not documented.
And while null-terminating is obviously usefull for strings, it's not really necessary for arrays, since one can always manually append a 0.

**Comment by Damianu** [comment]
bump,this problem is annoying..
