### ISSUE TITLE
Wire Nailer not working on GMod Linux Dedicated Server

### ISSUE THREAD

**Issue by Yuri6037** [wiremod/wire#880]
Hello all,

So I tried everything I could, including removing all addons that can interface with Wiremod. But nothing works. The Wiremod itself works great. However everytime you try to nail two props together, it does nothing. In singleplayer that works like it needs to.

I'm using the Workshop version. Please don't ask me to upload the github version to the linux server, cause my bandwidth will upload wiremod in one or two days due to the fact you have too much heavy models for my upload rate...

Note : It's a paid hoster, not a free one. All addons works, just Wiremod Nailer is broken.

**Comment by Yuri6037** [comment]
Ok wait my connection seams to be realy quick this evening it will maybe be able to upload the github version on the Linux server...

**Comment by Yuri6037** [comment]
Fixed it. For anyone who needs fix, put Nadmod prop protection, then put the last wiremod github version !

**Comment by Nebual** [comment]
The Workshop version was actually updated a week ago, so your problem was
likely just your old prop protection not being CPPI compliant. Glad to hear
mine still works.
