### ISSUE TITLE
Wire Nailer not working with Nadmod Prop Protection

### ISSUE THREAD

**Issue by Yuri6037** [wiremod/wire#883]
Hello all,

So I'm now using the Github version of WireMod. It works well, but the nailer won't work if Nadmod prop protection is activated.

I tried UPS (Ulysses Prop Share) too, but it creates Lua Errors when you try to Nail. I know there some others prop protection scripts, however they aren't working very well on my server : 
- Simple prop protection works, but impossible to take world props as SuperAdmin so can't use it.
- Falco's prop protection doesn't work at all, for it I'm a user not SuperAdmin !!
- Nadmod prop protection and UPS are the only scripts that are working like they should, but visibly with the last Wiremod update they aren't working well...

Do you know a fix ? I tried to edit Nadmod prop protection but I can't find any code that would cancel the Nailer action...

**Comment by Divran** [comment]
The problem appears to be
`if not hook.Run( "CanTool", self:GetOwner(), trace, "nailer" ) then return false end`

This should be comparing `== false`

**Comment by Yuri6037** [comment]
Ok but please make it quickly, I know development is a long process, but please do as much quick as you can.

My server rests shutdown due to this issue !

**Comment by Yuri6037** [comment]
So much thanks you solved the problem.

**Comment by AbigailBuccaneer** [comment]
Sorry!
