### ISSUE TITLE
Falco's Prop Protection Wire Forcer

### ISSUE THREAD

**Issue by Yuri6037** [wiremod/wire#884]
Hello all,

Again a problem...
So a friend told me to put Falco's Prop Protection instead of Nadmod prop protection. However with Falco's prop protection, WireMod Forcer does no longer force anything !!!

So actualy I run back to UPS (Ulysses prop share) that seams to be working fine, but I'd like you to see what you can do for Falco's Prop Protection...

**Comment by Yuri6037** [comment]
This line in the Think hook of gm_wire_forcer.lua in entities should be : 
if (gamemode.Call("GravGunPunt", self:GetPlayer(), trace.Entity) == false) then return end
instead of : 
if not gamemode.Call( "GravGunPunt", self:GetPlayer(), trace.Entity ) then return end

**Comment by Divran** [comment]
Falco's prop protection hacks many wire entities to disable them. You have to go into FPP's settings to enable them.

**Comment by Yuri6037** [comment]
So why when I change to ==false FPP does no longer break wiremod ?

**Comment by TomyLobo** [comment]
@Yuri6037 are there any side-effects?

**Comment by Divran** [comment]
It's correct because the GravGunPunt hook returns true in the gamemode (which is the last hook to run).

**Comment by zDarKLordZ** [comment]
I have the same problem, it's urgent please!

**Comment by Divran** [comment]
>Falco's prop protection disables many wire entities on purpose. You have to go into FPP's settings to enable them.

I already answered this question over 2 years ago.
