### ISSUE TITLE
Weird trigger behaviour with arrays (E2)

### ISSUE THREAD

**Issue by nirahiel** [wiremod/wire#886]
Put this in an E2 chip

``` Perl
@name 
@inputs Create Push ArrayIn:array
@outputs ArrayOut:array
@persist 
@trigger 

if (inputClk())
{
    if (~Create & Create)
    {
        print("Trigger on Create")
        ArrayOut = array()
    }

    if (~Push & Push)
    {
        print("Trigger on Push")
        ArrayOut:pushNumber(random())
    }

    if (~ArrayIn)
    {
        print("Trigger on ArrayIn")
    }
}
```

Place it with 2 buttons, wire the chip to the buttons, and connect the chip's ArrayIn with it's own ArrayOut.
Play with the buttons, observe results.
In my case, when the array changes once, the trigger is run FOUR times.
Example output after pressing create once, and push twice : 

```
Trigger on Create   
Trigger on ArrayIn  
Trigger on ArrayIn  
Trigger on ArrayIn  
Trigger on ArrayIn  
Trigger on Push 
Trigger on ArrayIn  
Trigger on ArrayIn  
Trigger on ArrayIn  
Trigger on ArrayIn  
Trigger on Push 
Trigger on ArrayIn  
Trigger on ArrayIn  
Trigger on ArrayIn  
Trigger on ArrayIn
```

**Comment by Divran** [comment]
Why would you wire an input to an entity's own output? It doesn't really matter how broken that is because you'd never do it. Try it with two different E2s instead.

**Comment by nirahiel** [comment]
Ok i'll do it just to prove you my point

**Comment by Divran** [comment]
>also, i can see some cases where I'd wire something to itself.

Ok, when

**Comment by nirahiel** [comment]
Okay, after some tests (and using the github version instead of the workshop one), it seems to not fire the gate more than once on array trigger with 2 different gates. (Still exists with the same gate)
Also, for when I'm wiring an entity output to the input of the same entity, recurrent neural network ;)

**Comment by Divran** [comment]
>recurrent neural network
wat

**Comment by nirahiel** [comment]
Ok then, quick question about this, depending on the answer i might mark it as closed.
What happens if I create an input and output of the same name. Is it something I can do, or something I should avoid at all cost ?

**Comment by Divran** [comment]
>What happens if I create an input and output of the same name. Is it something I can do, or something I should avoid at all cost ?

I'm not sure. I'd test it but I don't have access to a computer with gmod installed for another hour.

>EDIT : Also, sometimes I might create a chip that could use some data from somewhere, or itself, but not always, so instead of designing the chip to use data from itself on certain conditions (and make the code more complicated) i could wire it to itself, to use the benefits of the trigger system.

I have also done that, but I just use the `->` operator (which returns 1 if the input is wired, and 0 if it isn't). You're right in that it makes it a tiny bit more complicated, though. (although not much - you could, for example, simply use timers to trigger the same part of the code that the changing input would have)

**Comment by nirahiel** [comment]
I think that when the chip is initialized the output immediately takes the
value of the input with the same name and isn't updated after that, even on
triggers or stuff. The problem comes when you want to assign data. If the
input is named eg Value, doing a Thing = Value * 5 uses the input one.
Where Value = Thing sets the output value. That way you can't read from an
output value. Problems are when you use stuff like func(Value). Does it use
the input or output in this case ?
Anyway about the chip sending array data to itself, I could vonEncode the
array since strings should not cause this kind of problems.
If you can tell me where in the code I could find this stuff, I could try
and fix it myself though. Also quick question, I wonder if there is a way
to have an E2 with an input array and when it's triggered see which index
of the array changed (new row, changed row, deleted row) along with the old
value if any ?

**Comment by Divran** [comment]
>The problem comes when you want to assign data. If the
input is named eg Value, doing a Thing = Value * 5 uses the input one.
Where Value = Thing sets the output value. That way you can't read from an
output value. Problems are when you use stuff like func(Value). Does it use
the input or output in this case ?

This sounds reasonable. I assume `func(Value)` would use the input as well.

>Anyway about the chip sending array data to itself, I could vonEncode the
array since strings should not cause this kind of problems.

That's extremely inefficient, though. Another solution is to not use inputs or outputs at all, and instead use datasignals.

>If you can tell me where in the code I could find this stuff, I could try
and fix it myself though.

https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/table.lua#L1132-L1161
This function goes through the arrays and tables that have been flagged for change and triggers them (vclk) as necessary.
You can find the code that flags them inside every function that modifies arrays or tables.

>Also quick question, I wonder if there is a way
to have an E2 with an input array and when it's triggered see which index
of the array changed (new row, changed row, deleted row) along with the old
value if any ?

Anything is possible. Question is, is it worth the time to make such a niche feature?

**Comment by Divran** [comment]
If having an input and an output of the same name doesn't work the way you want it, you can always use `ioSetOutput(Name,Value)` and `ioGetInput*(Name)` to force the E2 to get the correct one
