### ISSUE TITLE
Increase OPS for some basic functions

### ISSUE THREAD

**Issue by monkstick** [wiremod/wire#887]
I feel that some of the basic functions like holo / entity parenting, setpos, setang and HoloCreate need an OPS boost to avoid newer players from making really bad decisions when coding and causing a lot of un-needed strain on servers, just because there's no real punishment for doing it.

If we raise the OPS of some of these functions so you cannot parent or create 10 holos per tick, I feel players will learn better and more optimized ways to create there chips, plus servers and server owners will have to deal with a lot less un-needed lag, just because some players can't code correctly.

What are your thoughts on this?

**Comment by RaptorEatingDuck** [comment]
I agree with this wigga.

**Comment by monkstick** [comment]
Or, even better;

Can we ditch the OPS system and use the SysTime() as a chips actual usage?  Making a Holo for 33 ticks a second, is only 26 ops, yet it is 76μs.

Doing A = "Hello" + "World" uses 20 ops, but only 9μs.

**Comment by Akarias** [comment]
I agree with the replacement of the OPS system, it does not feel accurate at all; SysTime on the other hand...

**Comment by RaptorEatingDuck** [comment]
Does make sense if its better to know about how much μs a chip uses

**Comment by Stachura5** [comment]
I agree

**Comment by CaptainStumpy** [comment]
I agree.

**Comment by ApplesGmod** [comment]
I agree

**Comment by RaptorEatingDuck** [comment]
Wow didnt know so many people would agree

**Comment by Iska45** [comment]
Agreed

**Comment by AbigailBuccaneer** [comment]
@Stachura5 @CaptainStumpy @ApplesGmod and @Iska45 all registered today - they're either sockpuppet accounts, or friends that you got to sign up specifically to agree. Please don't just spam with 'I agree', it's not helpful.

**Comment by AbigailBuccaneer** [comment]
A time-based system would be very hard to make reliable - if the server stalls because some other process is doing work, then everybody's E2s would fall over. If we could get how much time they're using as a fraction of how much time the server is using, then that'd be more useful.

It would definitely have benefits, though, and it would cleanly solve the problem of "the op numbers are just picked nearly at random".

**Comment by monkstick** [comment]
Yeah they are some of my server clients.  I was actually hoping for more of a discussion and for them to also explain why, instead of just "I agree.", sorry about that.

What about if the server hangs (Easy to detect) then make a buffer.  If the server hangs for a couple of seconds, then the server has a bigger problem to deal with than some e2's going over quota.

**Comment by Theonemanny** [comment]
If the idea is a stretch for devs to commit and they are not sure. Why not have two OPS modes. Normal and strict. Very simple the strict one would be as monkstick said and normal would be as it is now. It would solve the problem for anyone who experiences lots of crashing, lag and general laziness when it comes to people doing it an inefficient way. But also leave an option for people who want a more relaxed e2 enviroment for themselves to mess around in.

**Comment by thegrb93** [comment]
This is what I use for my server

```
timer.Create("CheckE2Cpu", .5, 0, function()
    for k, v in pairs(ents.FindByClass("gmod_wire_expression2")) do
		if v.context then
			if v.context.timebench > .003 then
				v.TOOMUCHCPU = (v.TOOMUCHCPU or 0) + 1
				if v.TOOMUCHCPU == 5 then
					v:Error("Expression 2 (" .. v.name .. "): cpu quota exceeded", "cpu quota exceeded")
					v:PCallHook('destruct')
					v.context.timebench = 0
				end
			else
				v.TOOMUCHCPU = 0
			end
		end
    end
end)
```

**Comment by Nebual** [comment]
Detecting hanging is an interesting feat; on a 66 tick server, there's 15ms
between each frame. In that time, there are source level calculations
(physics), network processing, SENT think hooks, etc that all must
complete, and then it sleeps any remaining time until the next 15ms
interval. So if the above takes up say, 10ms, then there's 5ms 'left over'
for E2 processing. If they take more than this time, players will start to
notice jerkiness in physics, and the server FPS will drop. Obviously
servers will take more or less than 10ms depending on many factors,
including number of non-sleeping physics objects, or if it's a 100/33 tick
server, and there can be many E2s running at once. This makes determining a
threshold difficult.

thegrp93's solution would probably work for some servers, but it isn't a
great one size fits all approach, and it would be far less
consistent/predictable than the ops system. I wouldn't be opposed to adding
something like it, multiplied against tickrate, as an option.

Really someone should probably try benchmarking a ton of functions against
their cputime, and reevaluate their ops count. Doing so programmatically
might be an interesting challenge...

Wouldn't work for propCreate and holoCreate, but those are already rate
limited.

**Comment by Stachura5** [comment]
@AbigailBuccaneer do you have a problem with that? @monkstick is a friend of mine and I thought that this is a good idea so I said that I agree with it

**Comment by oldmud0** [comment]
Detecting hanging is trying to solve the halting problem.

**Comment by thegrb93** [comment]
Starfall has a nice cpu quota system. Might try looking at that.

**Comment by thegrb93** [comment]
https://github.com/INPStarfall/Starfall/blob/develop/lua/starfall/instance.lua#L31

**Comment by monkstick** [comment]
If it would be a massive headache to pull off, I don't mind adopting @thegrb93 's meathod plus re-evaluating some of the more common functions.  Things like holoCreate, parenting and other propCore functions are massively under estimated with there ops count IMO.

**Comment by Divran** [comment]
>I feel that some of the basic functions like holo / entity parenting, setpos, setang and HoloCreate need an OPS boost to avoid newer players from making really bad decisions when coding and causing a lot of un-needed strain on servers, just because there's no real punishment for doing it.

holo parenting does not need an ops boost. It's a pretty cheap operation. holoPos/setPos + holoAng/setAng might need an increase though, and definitely holoCreate.

**Comment by monkstick** [comment]
Whilst we're on the subject of re-evaluating ops, one of my clients told me that if you make a huge array and sort it on tick / perf, it will cripple a server.  I'll ask him for the exact code later on today, but perhaps we could make a list of functions which should definitely be re-considered.

**Comment by immibis** [comment]
@oldmud0 No, it's not. The halting problem is to determine whether a given program will *ever* halt; for E2, all you need to know is whether it will halt within a certain number of microseconds. That's easy to find out - just run it for that long, and check whether it's still going!

**Comment by Divran** [comment]
@TomyLobo let me know that this issue was unresolved.

In my opinion, we shouldn't replace the OPS system with any kind of time check in E2, simply because it's not worth the effort. Starfall works differently, so it can use the default lua `debug.sethook` to check performance, but I'm not sure if E2 can do that. In any case, the OPS system works fine. It just needs some adjusting for a few functions.
