### ISSUE TITLE
Use key hardcoded to E in one place in wire_keyboard

### ISSUE THREAD

**Issue by TomyLobo** [wiremod/wire#893]
``` lua
        if self.IgnoreFirstKey then -- Don't start listening to keys until Use is released
            if not self.ply.keystate[KEY_E] then self.IgnoreFirstKey = nil end
```

If someone doesnt have "use" on "E", that key is going to be affected instead.
I would suggest delaying PlayerAttach until after -use has been run and removing everything related to self.IgnoreFirstKey.

Just putting this here so it's not forgotten.

~~I have a ton of code cleanup lying around which accumulated while making #892.
Please don't mess with this until I push that.~~

**Comment by Ruuttu** [comment]
Just mentioning the "leave" key for the wired keyboard can be customized separately.

**Comment by TomyLobo** [comment]
The "leave" key is unaffected by this problem though. that one is consistently treated as variable.
