### ISSUE TITLE
egpCircleOutline looks somewhat ugly with linewidth > 1

### ISSUE THREAD

**Issue by DaedalusGame** [wiremod/wire#895]
This may be a cantfix/wontfix candidate because
- The fix I propose is much slower than what you currently have
- It's probably not that big of a deal anyway

The issue is that egpCircleOutline seems to draw rectangles (lines with linewidth >1) on the circumference of the circle, which on higher linewidths will cause the outline to look jagged and discontinued.

The file I'm looking at is lua/entities/gmod_wire_egp/lib/objects/circleoutline.lua

Normally when drawing a circle you draw a fan of triangles with two endpoints of each triangle on the circumference on the circle, when drawing a circle outline with variable linewidth you'd instead draw a fan of trapezoids with h = linewidth around the outside of the circle. This can be done in e2, but it would use up n = fidelity egp objects from the buffer of 300 (by default, I believe?) objects, so preferrably it should probably be part of the lib. In theory, if your line drawing function already draws a rectangle, which is 2 triangles, you should end up with little to no increase in processing time, unless there's high overhead involved with successive calls to the drawpolygon function.

**Comment by Divran** [comment]
The line drawing thing draws a rectangle using a DrawRect function. If we were to make the circle outline draw triangles, we couldn't use the DrawRect function anymore and we'd have to do it manually by spamming DrawPoly. Not sure about the overhead involved in doing that

**Comment by AbigailBuccaneer** [comment]
As has been noted before (#763), the `DrawPolygon` function doesn't support concave polygons, and so we can assume it's not doing anything fancy and expensive under the hood that `DrawRect` doesn't do. There'd be a tiny bit more work involved as there's more Lua data to process on the C++ side, but that should be a fairly trivial amount.

In fact, given that DrawPolygon draws as a triangle fan from a given vertex, we could potentially use that to halve the number of `Draw*` calls we make (as each `DrawPolygon` could be a fan from one of the inner vertices, and cover the two adjacent edges.

**Comment by adosikas** [comment]
This could be fixed by overlapping the ends of the line segments slightly.
![grafik](https://user-images.githubusercontent.com/3721366/55676258-b6cfed80-58d1-11e9-948a-f09421e607f9.png)

Pseudocode:
```
local HalfBeta = acos( Dir1:dot(Dir2) )/2
local AddDist = Width * tan(HalfBeta)
Line1End = Line1End + Dir1*AddDist
Line2Start = Line2Start - Dir2*AddDist
```
That principle works for all angles<=90 degrees. I guess it would make sense to offload that into a generic function to use for all outlines as well as lineStrip.  
For angles>90 degrees (ie polyOutline) the old behavior could be kept.
