### ISSUE TITLE
E2 Function jsonDecode calls the wrong function

### ISSUE THREAD

**Issue by FNCxPro** [wiremod/wire#898]
If I were to make a JSON response that looks like:
```
{
    "depthone":{
        "value": 1
    }
}
```

and use the E2 function: `jsonDecode` it will halt the E2, display a notification, and print this to the console. `sv: Expression 2 (Weather): entities/gmod_wire_expression2/core/serialization.lua:485: attempt to call global 'jsonDecodeTableExternal_recurse' (a nil value)`

I believe you could fix this by changing Line 485 in entities/gmod_wire_expression2/core/serialization.lua(`v = jsonDecodeTableExternal_recurse( self, val, copied_tables )`) to `v = jsonDecode_recurse( self, val, copied_tables )` which will call itself again instead of calling the wrong function which was removed.

**Comment by Divran** [comment]
Huh, that's odd. I did test it before I merged it. Dunno how this could've gotten through. I'll fix it when I get home.

**Comment by FNCxPro** [comment]
@Divran After making the change in my issue post, it is fixed.
I'm just telling you that so your life is much easier.

**Comment by TomyLobo** [comment]
these are strange function names... they both sound like internal functions

**Comment by Divran** [comment]
they are

**Comment by TomyLobo** [comment]
yeah, internal to wiremod... we are not using an external parser?

**Comment by Divran** [comment]
It's using garry's parser, but it has to convert the results to and from E2 table syntax
