### ISSUE TITLE
Missing console commands

### ISSUE THREAD

**Issue by Mornedil** [wiremod/wire#901]
I have tried both the SVN and the workshop edition, yet I am still missing only certain console commands.

Examples of missing commands:
wire_holograms_modelany
sbox_maxwire_turrets (and almost all other sbox limits)

However, I have most of the console commands. like:
sbox_maxwire_gate_...
wire_holograms_block_client

.. and a ton more commands.

So is this a bug? It's very strange that some commands are missing, while others are there.

**Comment by TomyLobo** [comment]
old unanswered issue here

@Mornedil If you still think these commands are missing, enter them into the search box at the top of this page and see if they're mentioned in the source.
For the sbox_maxwire things, I think their names are concatenated from pieces though, so you won't find them either way.

**Comment by TomyLobo** [comment]
@Divran old unanswered issue here

@Mornedil If you still think these commands are missing, enter them into the search box at the top of this page and see if they're mentioned in the source.
For the sbox_maxwire things, I think their names are concatenated from pieces though, so you won't find them either way.

**Comment by Divran** [comment]
Make sure you're not hitting gmod's retarded lua file limit

**Comment by oldmud0** [comment]
I think this is issue is dead. We don't even know if we can still repro it.

**Comment by thegrb93** [comment]
I can't reproduce it.

**Comment by Mornedil** [comment]
I didn't explain it well enough.. hold on

**Comment by thegrb93** [comment]
I have wire commands in my server.cfg and haven't noticed any problems, but that isn't to say there isn't a problem. I'll try it if I get the time.

**Comment by Divran** [comment]
>So, I think the actual bug (if it's even a bug) was that the server.cfg somehow tried to execute the commands before wiremod initialized them on the server.
I never managed to fix it, but I found a workaround by creating a lua file which executed the sbox_maxwire commands shortly after the server started up, and that worked.

Ah yes, I remember now. This is the problem (others have had it) and the solution for it, good thing you found it already.

**Comment by TomyLobo** [comment]
So isn't there a config file that gets executed later?
Do they persist if you set them in the server console?
If so, where does Garry store them?
Can't you edit that file instead? (assuming it's not some silly sqlite database)

**Comment by GalaxyOfWaffles** [comment]
This also happens for effects extension.

**Comment by AbigailBuccaneer** [comment]
There's not really anything we can do to create these convars before we do, and they're created with `FCVAR_ARCHIVE` so their values should be stored fine. You can set them in a Lua file that runs on `InitPostEntity`.
