### ISSUE TITLE
entity:steamFriends() broken.

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#905]
Looks completely random when on a server for some time, some of my friends are in there, some not. Other people i don't know are in, sometimes multiple times, even Entity [0][worldspawn] is.

Code i used:

     printTable(owner():steamFriends())

Relevant code: https://github.com/wiremod/wire/blob/66b6a050da0368d41f44266693593a1e1c9d143c/lua/entities/gmod_wire_expression2/core/player.lua#L379
and https://github.com/wiremod/wire/blob/7fce83eb1199e5b7147e123f0bf9827214eb9e7e/lua/entities/gmod_wire_expression2/core/cl_player.lua#L8

**Comment by Divran** [comment]
Sorry for the super late reply, but this appears to be gmod's fault... if so, not much we can do. I've not tested it though.

**Comment by TomyLobo** [comment]
uhm, are you uploading the friend list to the server by default?

**Comment by immibis** [comment]
@TomyLobo It looks like it's only the subset of friends who are currently playing on the same server. Note that a nefarious server owner can get that information from Lua anyway, without having to go through E2.

**Comment by brandonsturgeon** [comment]
Curious, why would you want to get steam friends that aren't on the server through E2 anyways?
