### ISSUE TITLE
interval / other timers broken

### ISSUE THREAD

**Issue by DaRustyrail** [wiremod/wire#906]
I did some testing with the new gmod update and it seems that timers (or atleast interval, i didn't test other timers) are broken, basicly what happens is: when the chip is placed it updates once, as usual. and after that it only gets updated by triggers, it ignores the interval.

**Comment by gogasan24ru** [comment]
timer also not working
```lua
if(clk("i")){
    timer("i",1000)
    print("test")
}else{timer("i",1000)}
```
but this working:
```lua
@persist I
if(clk("i"+I)){
    I++
    timer("i"+I,1000)
    print("test "+I)
}else{timer("i0",1000)}
```

**Comment by Divran** [comment]
teamgarry's fault. I have worked around the problem with a quick hack

**Comment by oldmud0** [comment]
Timers!

**Comment by oldmud0** [comment]
And of course, never forget to push to workshop.
