### ISSUE TITLE
[BUG] Expression 2 Broken

### ISSUE THREAD

**Issue by PeEzZ96** [wiremod/wire#909]
Wire Expression 2 is broken on server, i can create and upload, but e2 stop working after 1 sec.

**Comment by TomyLobo** [comment]
The apocalypse!!!!1111

In seriousness, if you want stuff fixed, be more specific.
The version you're using would help and which script you're trying to upload.

**Comment by PeEzZ96** [comment]
anything script, e2 stop after finished the upload

E2 code:
[code]
@name PeEzZ's Prop Aim To Owner Aim

interval(1)

if(first())
{
    entity():isWeldedTo():propFreeze(1)
}

entity():isWeldedTo():setAng( ( entity():isWeldedTo():pos() - owner():aimPos() ):toAngle() - ang(90, 0, 0))
[/code]

**Comment by TomyLobo** [comment]
1 out of 4 - try harder

**Comment by PeEzZ96** [comment]
i Using the workshop version of wiremod.

**Comment by GalacticPaperclip** [comment]
The new Gmod update broke some stuff or something, even on the Github version. To fix an E2, replace the word "interval" with "runOnTick"

**Comment by TomyLobo** [comment]
Note that they're not the same though. ``runOnTick(<any non-zero number>)`` makes it run every tick, whereas ``interval(N)`` makes it run every every N milliseconds.
What @GalacticPaperclip works well in your situation, but in general, it does not.

**Comment by Divran** [comment]
@GalacticPaperclip untrue - it was fixed on the github version of wiremod just a few hours after the problem was found.
