### ISSUE TITLE
Fix that auto-Workshop script

### ISSUE THREAD

**Issue by oldmud0** [wiremod/wire#910]
We make 50 commits and then push it to workshop after a month. Then people start reporting that X is broken. Then we fix it and don't publish it to workshop again.

That auto-publishing script/webhook seriously needs to be fixed so that we don't have to depend on Faron.

**Comment by TomyLobo** [comment]
Problem is, he keep tight control over the means of production.
The way I understood it, no one but him can publish wiremod.
I might be wrong though, don't quote me on it.

**Comment by oldmud0** [comment]
They've been working on it now
