### ISSUE TITLE
addons/wiremod/entities/gmod_wire_expression2/init.lua:478:bad arguement #1 blabalabla... what should i do?

### ISSUE THREAD

**Issue by 1242161** [wiremod/wire#915]
problem is about init.lua:478..
when i try to spawn many hologram e2 with adv dupe 2, my dedicate server going down and left the log : addons/wiremod/entities/gmod_wire_expression2/init.lua:478:bad arguement #1 blabalabla

**Comment by TomyLobo** [comment]
That typo in "argument" tells me that you're paraphrasing it.
Can you copypaste the error instead of paraphrasing it?

**Comment by AbigailBuccaneer** [comment]
`self.dupevars` is nil when `self:ApplyDupeInfo` is called - but it's always set by `MakeWireExpression2`.

Presumably this is/was an issue with advdupe2, but I can't reproduce it.
