### ISSUE TITLE
egpMaterialFromScreen doesn't seem to be working

### ISSUE THREAD

**Issue by ZRonMoirZ** [wiremod/wire#917]
I couldn't get egpMaterialFromScreen working, it will just spam the console with ''--- Missing Vgui material GPURT' however I could get GpuLibSwitcher working.

EDIT: Only works on emitter and hud my bad.

**Comment by TomyLobo** [comment]
So... does that mean it works again?
Or was it never broken?
Or did you just stop caring?

**Comment by ZRonMoirZ** [comment]
It was always working, it just doesn't say that it only works on emitter/hud which made think it was not working at the time.

**Comment by Divran** [comment]
It used to work on screens as well, as long as you spam refreshed it (for example by parenting an invisible object to the cursor, which force refreshes every frame).
