### ISSUE TITLE
Target Finder Error

### ISSUE THREAD

**Issue by XxWestKillzXx** [wiremod/wire#918]
Sorry if this is a duplicate.

When people crash or leave with a target finder it spews errors into the server console about it not being able to find a buddy list.
```
[ERROR] addons/wire/lua/entities/gmod_wire_target_finder.lua:224: bad argument #1 to 'pairs' (table expected, got number)
1. pairs - [C]:-1
2. CheckTheBuddyList - addons/wire/lua/entities/gmod_wire_target_finder.lua:224
3. unknown - addons/wire/lua/entities/gmod_wire_target_finder.lua:243
```

**Comment by oldmud0** [comment]
I think this has something to do with the "Check Prop Protection Buddy List" setting. Does that *still* say "experimental"? It's been a couple years since it's been like that, better just remove it altogether.
