### ISSUE TITLE
Wires between entities will use up more resources the longer they get

### ISSUE THREAD

**Issue by Jake2149** [wiremod/wire#921]
Wasn't really sure how to title this one, but it's a pretty bad issue that can crash almost anyone. It isn't all that bad between entities from wiremod itself, but other mods that support wiring seem to have it pretty badly. Here's a video of this issue https://www.youtube.com/watch?v=5SYk-HVAoAg. If I were to attach those entities on the small plate to the car, the issue is fixed. I'm not really sure why it happens, but it causes Garry's Mod to use excessive amounts of memory until it crashes.

**Comment by Divran** [comment]
This doesn't make sense because wires are just numbers. There's nothing in the code at all that cares about distance.

**Comment by Jake2149** [comment]
The wire rope itself is what I'm referring to. Even at 0 width it seems to render a shadow.

**Comment by Divran** [comment]
iirc if at 0 width it doesn't even create a wire rope effect at all

**Comment by Jake2149** [comment]
Not sure why it happens then, but I've been able to replicate it doing that several times now. I can make another video of it since in that one I didn't actually know what was causing it.

**Comment by Divran** [comment]
Yeah ok it seems to create a beam even if the width is 0. I'll have to fix that

**Comment by Jake2149** [comment]
Even though it's not really easy to do with wiremod itself, I could see someone wiring stuff to ACF entities with a width more than 0, and moving it a large distance just to try and crash people. I don't really see anyone trying to do that, but is there any actual reason for wires taking up resources for shadow rendering?

**Comment by Divran** [comment]
pretty sure they don't need shadows, but I don't know how to disable those

**Comment by thegrb93** [comment]
Found that rangers and forcers also cast shadows if "Don't show beam" is checked.

**Comment by Jake2149** [comment]
Yeah this is sadly still an issue after that fix you added.

**Comment by Divran** [comment]
if anyone knows how to disable shadows for beams let me know

**Comment by thegrb93** [comment]
I think you have to draw the beam outside of the entity's draw hook. I'll test and see.

**Comment by thegrb93** [comment]
Yeah that fixes it. I don't know which hook to use though. I tried PreDrawOpaqueRenderables and PostDrawOpaqueRenderables and models always seem to draw over the beam.

**Comment by thegrb93** [comment]
Maybe the RenderScene hook. I'll try that.

**Comment by thegrb93** [comment]
This can be closed. After going through the render code, I see that beams aren't drawn at all if their width is 0.
