### ISSUE TITLE
Array:count returning incorrect number?

### ISSUE THREAD

**Issue by bigdogmat** [wiremod/wire#922]
Array:count doesn't count indexes less than 1, I don't know if this is intended behavior or?

**Comment by Divran** [comment]
It's intended behavior because arrays in E2 are direct ports of Lua arrays, and that's how it works in Lua.

**Comment by bigdogmat** [comment]
Ok then I guess I'll have to make a function to count them, thanks.

**Comment by Divran** [comment]
or I believe you can use tables instead

**Comment by bigdogmat** [comment]
I'm using this in a file system and saving an array takes up a bit less space than a table. Also I didn't really need count to work like I had hoped because it was either use count or check if the first two values in the array are assigned

**Comment by TomyLobo** [comment]
you could use an offset for your array
MyArray[I+2]
