### ISSUE TITLE
E2 editor going off screen

### ISSUE THREAD

**Issue by bigdogmat** [wiremod/wire#924]
If in windowed mode it seems I can pull the editor off screen 
![ss 2015-07-18 at 08 03 24](https://cloud.githubusercontent.com/assets/7156309/8764010/32f61908-2d88-11e5-86e2-d9469a6e5c51.png)

Not much of an issue, just annoying if I want the editor to cover my whole screen

**Comment by thegrb93** [comment]
Wire devs can't improve that. Gmod gui can't go outside the main window.

**Comment by bigdogmat** [comment]
I mean if I want the editor to cover my gmod window, when expanding the editor window you can make it bigger than your screen. It's not clamped to your current gmod screen res

**Comment by Divran** [comment]
yeah that's not possible, like @thegrb93 already said

**Comment by bigdogmat** [comment]
I'm not too sure you understand what I mean here. If you look in the screen shot you can see the close button and pretty much the whole top of the editor is out of the screen. When expanding the editor the size doesn't get clamped to your current screen res, so if I keep expanding the editor I wouldn't be able to close it at all. Not an issue in fullscreen because you can't pull your mouse outside of the gmod window. Not sure if it can be fixed I'm just pointing it out.

**Comment by Divran** [comment]
ok I see what you mean now

**Comment by thegrb93** [comment]
I feel like this should be a garrysmod issue rather than a wiremod issue.

**Comment by Divran** [comment]
Nah if it is what I think it is then it's a wiremod issue

**Comment by oldmud0** [comment]
You could add a custom resize hook to keep the window within boundaries.

**Comment by oldmud0** [comment]
Or that works too
