### ISSUE TITLE
Add function type for use in searching and calling functions.

### ISSUE THREAD

**Issue by Measurity** [wiremod/wire#926]
**Edit after discussion (renamed title):**
I've changed the title to represent what seems to be the way to go: Creating a delegate type for looking up functions in E2 and calling them afterwards. For backwards compatibility, strfuncs need to stay.

_Features required for approval (so far)_
- Function type
- \- Points to any one function or nothing (nofunction(), like noentity()).
- \- Can be retrieved at runtime through getFunction(name, [args]).
- \- Can be called using "getFunction("name", Args):call(Args)".
- \- Possibly: Can get name, return type, extension type and parameters from (as array of types in order).

If features should be different. Would like to hear so.

**Original post:**
The main reason for this feature is that you cannot safely check if a function can be called or not. Not sure if the E2 can easily implement eval(). Otherwise maybe something like a try-catch when E2 throws an error. So that you can handle it and continue. Without respawning the E2.

Syntax propose:

``` lua
if (first()) {
    function entity:sayPM(Message:string) {
        concmd("say /pm " + This:name() + " " + Message)
    }
}

......
......
......

if (chatClk(owner()) {
    Targets = findPlayersByName(...)

    local Command = lastSaid(owner())
    eval(Command)
    # Possibly:
    # local Players = evalArray("players()")
    # local OwnerName = evalString("owner():name()")
    if (!lastEval()) {
        # Fallback plan.
    }
}
```

Example chat: "# sayPM(Targets, "I'm your dynamic calling")"

Having this feature will allow users to create command-like utilities without getting an error message when calling an undefined function with "str"().

**Comment by thegrb93** [comment]
string function error handling should be better yeah, but I don't think an exception handling is the correct way since e2 was made to be safe from errors. Maybe instead of erroring the chip, an attempt to call an invalid function string should set a global error value/string which can be retrieved and reset with lastError(). Like how C programs work.

**Comment by Divran** [comment]
Or you can define your functions with tables as arguments when you don't know the types or how many it will receive.

**Comment by awilliamson** [comment]
You only want 'eval' as a steal from a dynamic language ( JS / Lua ). What you actually want is to create a parser. I see no reason for the use of eval. If you can provide a secondary use case that cannot be solved by using a parser, I will concede the point.

**Comment by Divran** [comment]
what @awilliamson means is basically what I said: either you use a table for dynamic types, or you could use a string and some very simple parsing to retrieve the values from the string (like we usually do with chat commands)

**Comment by Measuring** [comment]
@Divran @awilliamson 
Thanks for your thoughts. Using a table as parameter is a good idea I can currently do. Thought it would be a nice addition if there was a nice way to call strfuncs without throwing errors. And without redefining all functions in a table. Some kind of self-awareness would help a lot of redundancy.

**Comment by thegrb93** [comment]
A functionExists(str) would be great.

**Comment by Measuring** [comment]
Yes, though it would be nice if you could do it the same as you call it:
```lua
if (functionExists(Command, Arg1, Arg2)) {
    Command(Arg1, Arg2)
}
```

**Comment by oldmud0** [comment]
`eval`? no

**Comment by thegrb93** [comment]
Nobody said eval exists on C or any language, but it does exist as pcall in lua. I mentioned that lastError() is how many C apis handle errors, but edited it out because that was irrelevant.

**Comment by awilliamson** [comment]
@oldmud0 I don't see how anonymous functions would solve the issue at hand?

@Measuring I've yet to see you raise a valid point against using a parser. Your parser is responsible for interpreting your 'commands' eg "tp radon divran", and relaying the args to whatever function ( or in a case where tp is undefined, erroring ). Then it will pass args to the defined function, which will then be responsible for validity checks? Obviously I don't know the specifics of E2's UDFs, but the implementation should be trivial. If you make the parser correctly, you shouldn't be attempting to call invalid functions.

**Comment by thegrb93** [comment]
Its redundant to have to make your own check that a function exists when e2 should have it built in.

**Comment by Divran** [comment]
Right now you can add all valid functions to a table and check that

```
@persist ValidActions:table
if (first()) {
    function doSomething( Args:table ) {
        #whatever
    }

    ValidActions = table(
        "doSomething" = 1
        #more stuff
    )

    function functionExists( Str:string ) {return ValidActions[Str,number]}
}
```

**Comment by thegrb93** [comment]
We know. Just seemed like something that should be built in.

**Comment by Measuring** [comment]
@awilliamson @Divran I have no valid points against using a parser. I've done the part I can with a parser. The problem I have is that users CANNOT make any mistakes in what they type. Because it'll try to call that function. Unless I first check if the given function call is valid through a table of "valid-functions". Would be nice to have it build in. So utilities like this can be easily extended by adding a function or an '#include "lib"'

**Comment by adosikas** [comment]
The workaround i used it dumping the whole funtion list to vonEncoded table, with function name as key and a array of matching e2helper parameter and return types as value, which i then #include in the main e2 (else it lags the syntax highlighter badly).
Makes the E2 take awefully long to upload, has to be updated whenever you switch server(due to changed extensions) or a when new functions get added, but works.

See #652

**Comment by Measuring** [comment]
@adosikas I appreciate that solution to check for functions that exist. But dumping the function list in a vonEncoded table would still require you to type everything out I assume?

I know I could go out of the way and just redefine functions as text in a table. Though it seems like E2 can do much easier and better than me if it was added. Without having possible issues like "whoops, forgot to change my table".

**Comment by Measuring** [comment]
@adosikas I removed my original post. Think I misinterpreted your post. You said "dumping the functions to a vonEncoded table with lua". Is this something you purpose as a solution for E2? Or for me as a user? As I understand it: You write lua to parse the E2 code to only take the function information and write that back to a vonEncoded table. Then load this table in your E2 chip with an include?

That's a smart but really exhaustive method to get it to work imo.

**Comment by adosikas** [comment]
As a solution for you, as i made a similar request which was denied.

And no, i don't parse the E2 code, i convert the E2Helper.Descriptions table into a lookup table (using clientside lua), and have a E2 that does FunctionTable=vonDecodeTable("<vonEncoded Table here>") and provides a function that checks the table if a function with said name (and parameters) exist.
That whole procedure is a one-off thing that you can forget about, until the e2 function list changes (wiremod updates adds functions, or server enables/disables extensions), which should not be to often.

When that is done you can just #include that file, and use the function to check whenever you need.
Of course you will still have to add your own (user defined) functions to the FunctionTable, if you plan on using those alongside the given ones.

**Comment by Divran** [comment]
fyi that lua code there is horrendously unoptimized (thanks to garry). You have to be careful when using any functions in gmod that start with an uppercase letter, because they're often old as fuck and were made back when garry didn't know how to code. Two examples in your code is table.Count, which loops through the entire table, and table.GetKeys which also loops through the entire table. So in that piece of code you're looping through E2Helper.Descriptions 4 times, even though it looks like you're only looping once. 5 times if you count von.serialize. And that table isn't exactly small. (but we can't really say it's your fault - these functions garry added just makes it easy to make bad code)

**Comment by TomyLobo** [comment]
1. There are no errors that dont halt execution immediately, so a lastFuncError function is useless
2. If you want to introduce an eval, make it return a user-defined function
3. You dont need functionExists(), you have #ifdef and you want to introduce an eval, right?
4. @thegrb93 pcall is not in any way equivalent to eval
5. If you introduce error handling, make it pcall-like, not with a silly lastError function.

**Comment by TomyLobo** [comment]
PCallResult = pcall(Function, ...)
PCallResult:message()
PCallResult:returnValue()[1,type]

I just notice that would throw type safety out the window... meh

**Comment by thegrb93** [comment]
@TomyLobo He changed his proposed syntax since my comment.

I doubt a pcall system can smoothly be integrated into e2.

**Comment by Divran** [comment]
@TomyLobo `#ifdef` doesn't work on user defined functions because `#ifdef` is a preprocessor command and UDFs don't exist until after the E2 is parsed.

**Comment by Measuring** [comment]
Yes, I eventually went with lastFuncError(). Because it was the easiest thing to implement and doesn't have a huge impact. Besides, it's something a rookie can do without breaking a lot :).

**Comment by TomyLobo** [comment]
@thegrb93 yes there are, but can you name any that don't? also, we can implement e2 pcall with lua pcall :)

@Divran the eval gets the UDFs from the main script and you just put #ifdef there to return different things based on the result.
Also, if UDFs are not sourced from other scripts, why the heck would you even need this feature?
You already know which functions you defined...

@Measuring "easy to implement" shouldnt be a criterion for what gets in

**Comment by Divran** [comment]
@TomyLobo these guy want this feature to avoid having to add all their UDFs to a table to check if it exists, like we already explained like 5 times

Myself I don't see the need for this and I am fine with adding the functions to a table if necessary.

**Comment by Measuring** [comment]
@Divran Alright. But if I do get around working on it. How would you guys like it to be? Or is this out of the question?

**Comment by thegrb93** [comment]
@TomyLobo Nevermind I misread your double negative statement. "There are no errors that dont"

**Comment by thegrb93** [comment]
There's nothing wrong with lastFuncError(). I would prefer a functionExists() though.

**Comment by TomyLobo** [comment]
@thegrb93 both are kinda broken designs. functionExists is less broken, though.
A delegate would be the proper way to do this.

@Divran do we have automatic type conversion in E2? String->Function, for instance?

**Comment by Divran** [comment]
@TomyLobo we only have automatic type conversion in some cases, for example number->string when concatenating. I wouldn't really call callable strings a type conversion

**Comment by oldmud0** [comment]
I can't believe I said the word lambda instead of delegate

**Comment by TomyLobo** [comment]
Actually, wouldn't a delegate for E:owner() include a reference to E? :)
It's actually more of a function pointer.
Let's just call the type "Function" with abbreviation "f" if that's still available.

**Comment by Measuring** [comment]
@TomyLobo Well, a function pointer is really basic. So I thought that delegates would make it more extensible. Like this answer: http://stackoverflow.com/a/8097290/1277156 "function objects".  Containing information about the function. Like arguments, return type. Instead of only being able to call it.

**Comment by TomyLobo** [comment]
Let's call it function object then.
That seems the least "huh?"-inducing :)

**Comment by oldmud0** [comment]
Would the behavior be like JavaScript?

**Comment by TomyLobo** [comment]
nope, not possible, since we have overloading

For the function search syntax, I propose the #ifdef syntax:
function("entity:setAlpha(number)"):call(MyEntity, MyNumber)

**Comment by thegrb93** [comment]
We have #ifdef now I believe

**Comment by shadowscion** [comment]
This is still one of the biggest issues for releasing public scripts. We have #ifdef, but would a @required tag at the top for specific extensions (at least those included in wiremod) be possible? 

Something like...

```@required propcore```

**Comment by Vurv78** [comment]
> This is still one of the biggest issues for releasing public scripts. We have #ifdef, but would a @required tag at the top for specific extensions (at least those included in wiremod) be possible?
> Something like...
> @required propcore

Just saw this, I mean you can do this now with compile time preprocessor errors so it's more obvious.
```golo
#ifndef propSpawn(string, vector, angle, number)
    #error This chip does not work without propcore enabled.
#endif
```
