### ISSUE TITLE
vonDecodeTable does not appear to be working correctly

### ISSUE THREAD

**Issue by o7c** [wiremod/wire#927]
local S = vonDecodeTable("~\"statusv\":n1;\"codev\":\"ZYZ5Yv\"")
    print(S:count()) # results in 0
    printTable(S) # no result

    ] lua_run_cl PrintTable(von.deserialize("~\"statusv\":n1;\"codev\":\"ZYZ5Yv\""))
    code	=	ZYZ5Y
    status	=	1

note console output for lua_run_cl PrintTable will be invisible for some reason, copy and paste it to see the result

**Comment by Divran** [comment]
wire doesn't use the latest version of von. Make sure you use WireLib.von.serialize/deserialize to compare with

**Comment by OpenToClose** [comment]
] lua_run_cl print(WireLib.von.serialize({ status = 1, code = "ZYZ5Y"}))
~"statusv":n1;"codev":"ZYZ5Yv"

**Comment by Divran** [comment]
ah right, that's because E2 expects it to be an encoded E2 table, which looks like this
`{n={},ntypes={},s={},stypes={},size=0}`
so in your case you want to do this
`vonEncode(table("status" = 1,"code" = "ZYZ5Y"))`
which will give you a von string of the above example with those values filled in, and then you can go from there

**Comment by OpenToClose** [comment]
Problem with this is that I'm not doing the vonEncode from an E2, I'm sending it from a different Lua enviroment by HTTP, what table format must I use in order to send E2 compatible tables?

**Comment by Divran** [comment]
Well you could just use json instead. Latest version of Wire has added json to E2.

Or you could format your table to look like the one in my previous comment

**Comment by OpenToClose** [comment]
Does wiremod have a converter at the moment or will I need to write my own?

**Comment by Divran** [comment]
If you want to use von, you will need to write your own. It should be really easy though, if all you're sending is strings and numbers.

If you use json, you don't need a converter.

**Comment by OpenToClose** [comment]
local function getTableSize(T)
        local count = 0
        for _ in pairs(T) do count = count + 1 end
        return count
    end

    local function getWireType(var)
        if type(var) == "number" then 
            return "n"
        elseif type(var) == "string" then 
            return "s"
        end
    end

    local function tableToWireTable(t)
        local DEFAULT = {n={},ntypes={},s={},stypes={},size=0}

        
        for k,v in pairs(t) do
            if type(k) == "number" then
                DEFAULT.s[k] = v
                DEFAULT.stypes[k] = getWireType(v)
            elseif type(k) == "string" then
                DEFAULT.s[k] = v
                DEFAULT.stypes[k] = getWireType(v)
            end
        end
        
        DEFAULT.size = getTableSize(t)
        return DEFAULT
    end

Perfect, this should ready a convert a Lua table into a wire compatible lua table.
I may add the ability to use tables in the future

**Comment by Divran** [comment]
Why loop through the table a second time in `getTableSize` when you can just do `count=count+1` in the loop inside the `tableToWireTable` function

**Comment by OpenToClose** [comment]
Thank you, while I was at it I added support for nested tables

    local function wireGetType(var)
        if type(var) == "number" then 
            return "n"
        elseif type(var) == "string" then 
            return "s"
        elseif type(var) == "table" then
            return "t"
        end
    end

    local function wireTableFromTable(t)
        local DEFAULT = {n={},ntypes={},s={},stypes={},size=0}
        local count = 0
        
        for k,v in pairs(t) do
             count = count + 1
        
            -- Check if the value is a table and if it is convert it
            local value = v
            if (type(v) == "table") then 
                value = wireTableFromTable(v) 
            end
            
            if type(k) == "number" then
                DEFAULT.n[k]      = value
                DEFAULT.ntypes[k] = wireGetType(v)
            elseif type(k) == "string" then
                DEFAULT.s[k]      = value
                DEFAULT.stypes[k] = wireGetType(v)
            end
        end
        
        DEFAULT.size = count
        return DEFAULT
    end
