### ISSUE TITLE
Add a hook call to signify Wire has fully loaded

### ISSUE THREAD

**Issue by Mista-Tea** [wiremod/wire#930]
This is a feature request unless there is currently a method to detect when Wire has been fully loaded.

It can be beneficial for external addons to know when Wire has completely finished loading. For example, the PlayerSay hook used by Expression 2 exposes all chat to clients, meaning private conversations can be snooped on. Currently there is no way to accurately know when the PlayerSay hook is added by E2. With this hook, an external addon would know exactly when it can override the hook. Developers wouldn't need to edit core files to modify functionality like this.

I believe it should be as easy as adding something like ```hook.Run( "OnWireLoaded" )``` at the end near https://github.com/wiremod/wire/blob/master/lua/autorun/wire_load.lua#L132. Letting it be called on the client could be helpful as well, instead of just surrounding it in ```if SERVER then```.

Let me know your thoughts. The example I gave is very specific, but having this hook could be beneficial on a wider basis, and it's such a small and simple addition.

**Comment by thegrb93** [comment]
Use registerCallback(event, callback) with event "postinit"

**Comment by Divran** [comment]
@Mista-Tea you can simply use a regular "Initialize" hook, which I believe should run after all addons have loaded. If not, I'm sure there's already some alternative hooks in gmod which do that (InitPostEntity perhaps)

@thegrb93 that hook and that hook system is for E2 only. postinit is called whenever an E2 is spawned. It has nothing to do with when wiremod is loaded.

**Comment by Mista-Tea** [comment]
@Divran, good point. ```Initialize``` will have to do for now. Thanks for looking into this :)
