### ISSUE TITLE
Attempt to index field 'BaseClass' (a nil value)

### ISSUE THREAD

**Issue by Bryantdl7** [wiremod/wire#933]
This just started flooding my console. 
[ERROR] addons/wire-extras/lua/entities/gmod_wire_rfid_reader_beam/cl_init.lua:7: attempt to index field 'BaseClass' (a nil value)
  1. unknown - addons/wire-extras/lua/entities/gmod_wire_rfid_reader_beam/cl_init.lua:7

**Comment by Divran** [comment]
it would appear the rfid reader is ded

**Comment by AbigailBuccaneer** [comment]
Should be reported at https://github.com/wiremod/wire-extras.
