### ISSUE TITLE
E2 doesn't allow method-style functions on numbers

### ISSUE THREAD

**Issue by airidas338** [wiremod/wire#934]
Example:
function void number:testFunction() { }

Enable numbers as function object types, so we could create functions similar to these n:teamDeaths(), teamName() which is implemented in E2. (No, i don't want to add number as parameter, this way it looks better, nearly can simulate object based scripting)

**Comment by Divran** [comment]
hm, try `normal:test()` ?

**Comment by bigdogmat** [comment]
Returns the same error

**Comment by TomyLobo** [comment]
It's pretty simple actually:
1. What's the error?
2. Are we throwing it?
3. Is Garry throwing it?
4. Is Lua throwing it?
5. If 2., was there a reason for introducing that error?
6. Is that a good reason?
7. Does that reason still apply?

**Comment by TomyLobo** [comment]
Maybe E2 needs user-defined types, so he can have a Team type :)

**Comment by Divran** [comment]
Currently the easiest way to fake objects is to use tables and then create functions on the table type.

**Comment by oldmud0** [comment]
Agreed, we should get some user-defined types.

But Divran is already directing people to things that are "better" than E2 so why bother.

**Comment by Divran** [comment]
@oldmud0 development for E2 has been pretty stale for years

**Comment by bigdogmat** [comment]
Any update on this issue?

**Comment by Divran** [comment]
That's weird. I don't see any reason to have that.

**Comment by bigdogmat** [comment]
Neither did I, maybe caused an old bug? If it did I'd think it's been fixed by now as I wasn't able to produce any errors using numbers as objects.

**Comment by TomyLobo** [comment]
In this case, I'd say remove it and see if people complain :)
You can try doing shenanigans with all the different kinds of number literals to see if they cause problems.

**Comment by Divran** [comment]
Apparently Syranide did this, just saying

**Comment by bigdogmat** [comment]
So should we just comment out the line just incase something happens? I mean unless someone can contact Syranide and ask why it was added, we don't have much to go off of. And should I create a pull request for this or would it be easier for someone to commit it directly in?

**Comment by syranide** [comment]
The only thing that makes sense to me is that it was added to give a useful error message. My thinking probably being that it doesn't really make sense to have methods on numbers, they're "too primitive" in a sense and the only operations that really makes sense are already operators. Anything that operates on numbers are better provided as functions.

Anyway, do as you please :) because I can't imagine it being there for any other reason that wouldn't be immediately obvious (like not parsing).

**Comment by Divran** [comment]
>My thinking probably being that it doesn't really make sense to have methods on numbers, they're "too primitive" in a sense and the only operations that really makes sense are already operators

This is E2, we don't give a fuck

**Comment by TomyLobo** [comment]
PHP has classes with polymorphism... let's at least add user-defined types. together with method-style they feel like non-polymorphic classes
Shorthand would be automatically assigned from a pool of x00..x99, so we have 100 user-defined classes :)
