### ISSUE TITLE
"repeat" can freeze server and allocate all memory

### ISSUE THREAD

**Issue by Draiget** [wiremod/wire#937]
"repeat" can freeze server for a long time, and if you put string to array with adding one char (like dot) - server will allocate all available memory (for x86 architecture of srcds - 3gb).

Example: *hidden*

**Comment by Divran** [comment]
Yes, we know. There's no way to fix it, other than deleting those functions.

**Comment by Draiget** [comment]
Rubat refused to limit\fix those functions...

**Comment by Divran** [comment]
banhammer is the best solution. Just log E2 spawns so you can see who spawned what and check your logs just before the crash

**Comment by TomyLobo** [comment]
I know it's not a solution, but there's still no 64 bit srcds?
how quaint

**Comment by Draiget** [comment]
For windows, definitely not.

**Comment by oldmud0** [comment]
Why are there no memory caps for e2s?

**Comment by Divran** [comment]
Because it's *really* hard to implement

**Comment by oldmud0** [comment]
Can't we give each data structure "memory points" and make a recursive method to get the number of memory points an object is worth?

**Comment by Divran** [comment]
And then what is a good max string size? You can easily crash a server with as little as 10 000 characters. It's better to not fuck legit users in the ass by making E2 have a max ram usage of like 1000 bytes. But seriously though, I've never seen anyone crash a server this way. Not once.

**Comment by Draiget** [comment]
Without clamping, this function freeze server for 1-4 minutes (drops tickrate to 2) from one chip spawn. Even without this function, simple while with growing string can make *huge* lags, it sucks.
