### ISSUE TITLE
Allow EGP Hud to remember who was connected.

### ISSUE THREAD

**Issue by RonnieMoir** [wiremod/wire#940]
I'm pretty sure this doesn't exist already and I know it can kinda be done with E:egpHudSetPlayer(E) from nexus core but its would be much nicer to have an option for the client to remember which players huds he was connected to so that if he was to rejoin he would be automatically reconnected to that hud.

**Comment by thegrb93** [comment]
I imagine some players may leave because they get a troll hud and can't figure out how to remove it. This would make it impossible for them to reset it.

**Comment by TomyLobo** [comment]
Maybe restrict it to the owner?
