### ISSUE TITLE
CamControler bug

### ISSUE THREAD

**Issue by Yuri6037** [wiremod/wire#955]
After going to a certain distance from the point the player is sitting down, the WireCamControler stops to update position and client parent entity is no longer rendered. Is there any way you can fix that ?

**Comment by AbigailBuccaneer** [comment]
@Divran this sounds like a bug with PVSs?

**Comment by Yuri6037** [comment]
Note : I've tested that and reproduced that on TSCM Sandbox Build server, Person (server owner) said that he is using the latest WireMod, so I conclude that it's linked to yoru addon.

I can try to see if I can reproduce in singleplayer/fix the issue.

**Comment by Divran** [comment]
I've had several issues with the player leaving the visleaf (or whatever it's called in source), but I thought I'd fixed them all using a special hook: https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_cameracontroller.lua#L561-L568

**Comment by Yuri6037** [comment]
After some research using TSCM's Starfall, I can conclude the problem is linked to entity remove client side ! After going to a certain distance entities you can't see are being removed client side but not server side causing Wire Cam Controler to fail updating position.
To verify that I used print(entity) on an entity that is far away from player. I got a valid entity server side but when print(entity) client side by sending it's index (EntIndex) I see Null Entity.

Is this linked to Source Engine itself or is it TSCM ? I believe it's TSCM Anti lag or something like that.

**Comment by Divran** [comment]
If it is TSCM Anti lag then it's up to the server owner to fix it. The anti-lag should remove entities that are a certain distance away from the player's PVS, not from the player entity, since there are many ways that the player's PVS could be moved (not just via cam controller).

**Comment by Yuri6037** [comment]
Thanks Drivan, please don't close this, I posted something on TSCM forums in the hope Person see the problem.

If you want to follow here is the link : http://teamscm.co.uk/showthread.php?tid=1309

**Comment by Divran** [comment]
Of course. Let me know if it turned out to be Wire's fault after all, although I don't think it is.

**Comment by Divran** [comment]
@AbigailBuccaneer okay but we just said not to close it <.<

**Comment by AbigailBuccaneer** [comment]
It can easily be reopened if needed, and all the evidence points to it being something other than us.
