### ISSUE TITLE
E2: Table/Array:remove* not working

### ISSUE THREAD

**Issue by bigdogmat** [wiremod/wire#958]
I was told it wouldn't work on unordered arrays because arrays in e2 are a direct port of glua arrays though shouldn't it work on unordered tables?

**Comment by thegrb93** [comment]
unordered table is the same as an unordered array in lua.

**Comment by bigdogmat** [comment]
So their's no way to remove a value from a table/array unless it's ordered?

**Comment by thegrb93** [comment]
They way you do it with lua is to set the key to nil.
```
> mytbl = {[100] = "hi", hello = "hello"}
> mytbl[100] = nil
```

**Comment by bigdogmat** [comment]
Yea but I'm talking about within e2

**Comment by thegrb93** [comment]
No idea. Have to wait for someone better with e2 to answer.

**Comment by thegrb93** [comment]
table:remove should work actually. This is the code for it.
```
-- Remove a variable at a number index
e2function void table:remove( number index )
	if (#this.n == 0) then return end
	if (!this.n[index]) then return end
	table.remove( this.n, index )
	table.remove( this.ntypes, index )
	this.size = this.size - 1
	self.GlobalScope.vclk[this] = true
end

-- Remove a variable at a string index
e2function void table:remove( string index )
	if (IsEmpty(this.s)) then return end
	if (!this.s[index]) then return end
	this.s[index] = nil
	this.stypes[index] = nil
	this.size = this.size - 1
	self.GlobalScope.vclk[this] = true
end
```
Note the this.s[index] = nil, However the version for numbers doesn't set the key to nil, so in that case it wouldn't work.

**Comment by thegrb93** [comment]
So either avoid using unordered numbers, or wait for a fix to be made.

**Comment by bigdogmat** [comment]
Well I was using keys as values to override old entries, as I didn't want to loop through the table again. So I'll guess I wait. On another note shouldn't array:remove work? Or is it the same bug?

**Comment by thegrb93** [comment]
Yeah it's the same. table.remove won't remove any number keys that aren't in the ordered number set.

**Comment by thegrb93** [comment]
I think the solution might be to check if a number is outside the ordered number set. I guess if number is <1 or >#array then set the key to nil.

**Comment by thegrb93** [comment]
Try replacing line 281-287 in array.lua with this
```
__e2setcost(15)
e2function void array:remove( index )
	if index < 1 or index > #this then
		this[ index ] = nil
	else
		table_remove( this, index )
	end
	self.GlobalScope.vclk[this] = true
end
```

And see if the array:remove(unorderedindex) works.

**Comment by bigdogmat** [comment]
It works. So now all remove* functions need to be fixed.

**Comment by TomyLobo** [comment]
Maybe you should mention why it was closed.
Divran added ``unset`` methods which effectively do what @bigdogmat said the remove functions should do for the unordered parts of a table.
