### ISSUE TITLE
holoDelete prevents spawning of holos with same ID

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#961]
if(first()){
        holoCreate(1)
        timer("run",1000)
    }
    else{
        holoDelete(1)
        holoCreate(1,entity():pos(),vec(2))
        print(holoScale(1))
    }

Expected result: small holo gets replaces with a bigger one, prints 2,2,2
Actual result: small holo gets deleted, other holo doesn't spawn at all, still prints 2,2,2

Is it indented behavior that holoDelete gets executed after all other commands (as it deletes the holo AFTER the scale has been changed)?

**Comment by Divran** [comment]
`holoDelete()` calls the `ent:Remove()` function immediately. If it takes 1 tick to delete it, then that's garry's fault. But this is irrelevant because there's literally no situation where you would delete a hologram and then immediately create a new one.

**Comment by adosikas** [comment]
I see, i encountered it while making a system to dynamically allocate holoids, and and part of the code freed up a id (deleting the holo) while another part occupied it directly after.

I assume you repurpose the same entity when overwriting a holo with holoCreate? Is there a way you can disable that when that entity was/is beeing removed?

**Comment by Divran** [comment]
No, and why would you want to? You'd just be wasting server resources

**Comment by Nebual** [comment]
I believe the root of this problem may be some mixture of Garry's recent happy fun change so that 
```
E:Remove()
E:IsValid() // returns true for the remainder of this tick, then false afterwards
```
and/or E:CallOnRemove(s, function) doesn't run until the end of the tick. Manually running SetIndex(self, index, nil) inside holoDelete may thus solve your problem. I'll try to take a look soon.


I'm not quite sure why you'd want a brand new hologram as opposed to reusing an old existing one (which is indeed what we do if you 'overwrite' a holo with holoCreate), so my immediate advice would be to restructure your allocation code to skip the delete step if you plan on creating anyway.

**Comment by TomyLobo** [comment]
oh god, this breaks so much stuff
can't garry make transparent changes for once?
Like, mark the entity as invalid until it is actually invalidated

**Comment by Divran** [comment]
So I assume we can close this issue, then

**Comment by oldmud0** [comment]
`can't fix` or `won't fix`?

**Comment by Divran** [comment]
because there's no reason to delete a hologram and then immediately create it. Either don't call `holoDelete`, and only call `holoCreate`, or simply modify the existing hologram.

**Comment by TomyLobo** [comment]
I don't think so, @Divran 
If you modify an existing holo, it might transition from the old state to the new one, possibly resulting in temporary ugliness.
Also, you'd have to clear all the properties you potentially set at all points in your program when putting the holo back in the pool.

**Comment by Divran** [comment]
>If you modify an existing holo, it might transition from the old state to
the new one, possibly resulting in temporary ugliness.

Only if you modify it slowly over multiple ticks. If you call all the
functions you want in the same tick then there won't be any temporary
ugliness (except for the scale, which must be synced to the client by net
messages, so those might arrive at a different time than other changes such
as color and material, but the difference is normally too small to see).

>Also, you'd have to clear all the properties you potentially set at all
points in your program when putting the holo back in the pool.

yes, you would. But deleting and creating an entity is way more hard on the
server than modifying it, so this behavior isn't going to change.
Also, this
https://github.com/wiremod/wire/blob/d8524642c12c53900dcd549575a85f177b00d348/lua/entities/gmod_wire_expression2/core/hologram.lua#L314
is a commit from 2009, so holoCreate has been like this (aka where it
doesn't create a new hologram when called - it reuses the existing one)
literally forever.

**Comment by TomyLobo** [comment]
I didn't mean it makes the server slow.
I meant it makes your code ugly.
