### ISSUE TITLE
Allow EGP functions to take an array of indices as an argument

### ISSUE THREAD

**Issue by brandonsturgeon** [wiremod/wire#967]
For example, I'd like to be able to do `EGP:egpColor(array(1,3,5,7,9), vec(255))` instead of having to do

```
foreach(K, V:number = array(1,3,5,7,9))
{
    EGP:egpColor(V, vec(255))
}
```
or whatever. 

Allowing us to pass an array of indices would save a lot of time and Ops. Especially with EGPs that have a lot of objects on them.

I tested and got this working on my server by adding this block of code
```
e2function void wirelink:egpColor( array indices, vector color )
	if (!EGP:IsAllowed( self, this )) then return end
	for k, index in pairs(indices) do
		local bool, k, v = EGP:HasObject( this, index )
		if (bool) then
			if (EGP:EditObject( v, { r = color[1], g = color[2], b = color[3] } )) then EGP:DoAction( this, self, "SendObject", v ) Update(self,this) end
		end
	end
end
```

To `lua/entities/gmod_wire_expression2/core/egpfunctions.lua:620`

I didn't want to make a pull request because you guys will know continuity and command structure better than me. (For example, still call it egpColor or would you call it egpColorMulti or something?)

If this were implemented, the same block of code would have to be repeated for each EGP command, too. And honestly, could it be done for Holograms too, maybe?

Also, if you just tell me how you guys would like it, I'd be more than happy to shoot a PR and save you some work.

**Comment by TomyLobo** [comment]
This needs to be implemented in a carefully designed way.
Otherwise we end up duplicating code a lot.
And duplicating code means duplicating bugs means you fix a bug in one place but forget the other place.

**Comment by Pharap** [comment]
function array:forEach(func)
        foreach k, v in self do func(k, v) end
    end
    
    (1,2,3,4,5,6):forEach(function(k,v) EGP:egpColor(v, vec(255) end)

Like that?

**Comment by Pharap** [comment]
I don't see what's so hard about writing

    local indices = array(1,3,5,7,9)
    foreach k,v in indices do EGP:egpColor(v, vec(255)) end

You could always just make a helper function like so:

    local forV = function(arr, fun, ...)
        foreach _, v in arr do fun(v, ...) end
    end

Which you use as thus:

    forV(array(1,3,5,7,9),  EGP:egpColor, vec(255))

**Comment by bigdogmat** [comment]
I can't tell if you're talking about using that code in E2 or changing the lua function for said function as both syntaxes would be incorrect.

**Comment by Pharap** [comment]
I've been doing Lua and C# all day, I forgot that E2s use a slightly different language. Which equally means I forgot it's the only one where functions aren't first class values (I think).

The only issue I see with what I wrote was the `;` on the bottom line should be a `.`. Otherwise it's all perfectly legal Lua as far as I can see.

**Comment by bigdogmat** [comment]
That didn't answer whether you were writing in Lua or E2... I'm gonna guess from your last line you mean Lua and if so you can't create arrays like that, you didn't use an iterator for your loops, vec isn't a valid type ( it should be a table with 3 args ) and EGP:egpColor isn't a valid function as it's a converted when the file is loaded for E2.

Back onto topic I guess this could be useful though idk, it'd make code look a bit cleaner though you could do the same with a UDF in E2 like so.

```
function wirelink:egpColor( Indices:array, Color:vector )
{
    foreach( K, V:number = Indices )
    {
        This:egpColor( V, Color)
    }
}
```

**Comment by Divran** [comment]
Yeah this could just be done in E2

**Comment by bigdogmat** [comment]
I'd say it could unless @TomyLobo still wants to clean up the EGP code to have less code duplication.

**Comment by Divran** [comment]
technically that's a different issue

**Comment by bigdogmat** [comment]
Yea I know, was just pointing out.

**Comment by TomyLobo** [comment]
@AbigailBuccaneer @Divran since you two closed the issue, you make another one with the cleanup :)
