### ISSUE TITLE
Remove dependencies on beam vars

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#969]
As has been discussed in #946 beam vars are a big bandwidth eater, as they use usermessages with an unstructued key-value format.

As of #966 being merged, the only thing still using them is wire paths, which are pretty ubiquitous. It'd be nice to replace them with their own separate system which uses the fact that path data is very structured to reduce the bandwidth of them.

**Comment by AbigailBuccaneer** [comment]
My initial progress on this is in 20de2ce309646dbb2f87842eac5bee88243c5919.

**Comment by CaptainPRICE** [comment]
Why does [`lua/wire/beam_netvars.lua`](https://github.com/wiremod/wire/blob/master/lua/wire/beam_netvars.lua) file still exist?
I have just run a throughout reference checks, static analysis, and runtime tests on both clientside and serverside, so I can confirm this code is no longer used nor needed. Trash it?
