### ISSUE TITLE
SPU Folder structure

### ISSUE THREAD

**Issue by suunrider** [wiremod/wire#973]
The folders "gpuchip" and "cpuchip" in /data contain the folder "e2shared", but it's useless for CPU and GPU.
Also the SPU examples should be in an examples folder.

**Comment by Divran** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/cl_files.lua#L13-L19 they're not useless for gpu/cpu

**Comment by suunrider** [comment]
Oh^^ Well then an e2shared folder is missing in spuchip :P
