### ISSUE TITLE
Moving Documentation to Github Wiki

### ISSUE THREAD

**Issue by its-suun** [wiremod/wire#980]
As it in #562 says, wiremod wiki is dead. I try to port it on Github Wiki at the moment.
My current progress is on my fork: https://github.com/suunrider/wire/wiki/
I don't use any script to make it, so it can takes up some time.
If you have any suggestions for improvements then tell me please.

**Comment by Divran** [comment]
The "how to install wire" section should suggest using github directly, since workshop sucks dick

**Comment by suunrider** [comment]
I didn't look in the content yet, i care only about design yet

**Comment by oldmud0** [comment]
FYI, the git repo for the wire wiki is at `https://github.com/wiremod/wire/wire.wiki.git` so you can actually pull changes.

**Comment by AbigailBuccaneer** [comment]
I think we should get on this, the Wiremod Wiki is pretty nasty and it'd be nice to have something we can make pull requests too and have it more integrated with the code.

**Comment by suunrider** [comment]
Still working on it

**Comment by suunrider** [comment]
Made a little script to build the wiki from a lua table (https://github.com/suunrider/wiremod_wiki/tree/master).That allows to easily change links, design and also it makes it possible to generate the expression 2 extensions documentation automatically.
I also have some other ideas for the wiki:
- "View Sourcecode" button
- Tutorials directly in wiki and not in forums

**Comment by oldmud0** [comment]
"View source" button..? Are you planning to use GitHub Pages or the built-in wiki feature?

**Comment by suunrider** [comment]
The "View Source" button would be just a link to a line of a file (on github). I never worked with Github pages, so im using the wiki in the repo.

**Comment by oldmud0** [comment]
Don't worry, pushing directly to the repo wiki is the easy part.

**Comment by suunrider** [comment]
### Progress
`[######--------------------------------------------]`

Not much yet, but now I have a little bit more time now.

**Comment by suunrider** [comment]
Implemented memory layout tables and the `View Code` button.

Beacon Sensor: [![View Code](http://suunrider.bplaced.net/wiki/View_Code.png)] (https://github.com/wiremod/wire/tree/master/lua/entities/gmod_wire_sensor.lua)
# Console Screen


## Memory layout


**Address**         |  **Meaning**
--------------------|---------------------
`0,2,4,6 ... 2018  `| Characters
`1,3,5,7 ... 2019  `| Color of the character in the previous address (format: LBBBFFF. To make the character flash L should be not zero; BBB is the background color in RGB format. FFF is the foreground color in RGB format).
`2020              `| Reserved
`2021              `| Reserved
`2022              `| Screen ratio (read only)
`2023              `| Hardware scale
`2024              `| Rotation (0° = 0; 90° = 1; 180° = 2; 270° = 3)
`2025              `| Brightness (white)
`2026              `| Brightness (blue)
`2027              `| Brightness (green)
`2028              `| Brightness (red)
`2029              `| Vertical scale (always 1)
`2030              `| Horizontal scale (always 1)
`2031              `| Low shift (column)
`2032              `| High shift (column)
`2033              `| Low shift (row)
`2034              `| High shift (row)
`2035              `| Reserved
`2036              `| Brightness (additive)
`2037              `| Shift horizontal
`2038              `| Shift vertically
`2039              `| Clear row
`2040              `| Clear column
`2041              `| Clear screen
`2042              `| Background color (when the background color of a character is 000, this will be used as background color).
`2043              `| Cursor blink rate (default: 0.5)
`2044              `| Cursor size (in percentage; 1 is the character height)
`2045              `| Cursor address
`2046              `| Cursor clk (default: 0)
`2047              `| Clk (default: 1)

**Comment by CaptainPRICE** [comment]
Seems like you deleted your wire/wiki repo?
Any updates? What happened?

P.S. I have this on my todo list, too ([repo](https://github.com/CaptainPRICE/wire/wiki))..

**Comment by oldmud0** [comment]
rip

**Comment by TomyLobo** [comment]
Looks like that didnt get restored from the backup

@Anticept can you contact support?

**Comment by its-suun** [comment]
wiki never got finished and i removed myself, sorry, but its much

**Comment by oldmud0** [comment]
No matter, we will develop mediawiki to markdown parser, right everyone?

**Comment by CaptainPRICE** [comment]
Indeed. It would be better to make something [like Microsoft have](https://docs.microsoft.com/en-us/dotnet/core/api/index). Modern documentation service.
(I have "a look of" it inside my head.) Take a look at [this page](https://docs.microsoft.com/en-us/dotnet/core/api/index) for example.
On the left-hand side there are namespaces, that's where I would put Wire tools (such as `Expression 2`, `CPU`, `GPU`, `SPU`, `Console Screen`, `Digital Screen` and so forth...) with search field (and filters on advanced search page) right on top of the list.
If you would navigate to `Expression 2`, it would take you to a new page ([example](https://docs.microsoft.com/en-us/dotnet/core/api/system), take any namespace page on API reference) with relevant information about the component (E2 in this case), so it would display extensions and their description, while on the left-hand side of that page, you would see extensions with constants on top. And if you would click on extension from that list, it would navigate to a page like [this](https://docs.microsoft.com/en-us/dotnet/core/api/system.console#System_Console) which would display all functions that are registered for particular extension. For example, take a look at [this](https://docs.microsoft.com/en-us/dotnet/core/api/system.console#System_Console_WriteLine_System_String_), it would point you to it.
And even with White/Dark theme switch, looks damn great...
  
We can get almost all data about E2's functions (at least the most important info) through `wire_expression2_funcs` table (which is used by in-game Helper, that's pretty much how I made up [Static-Reflector library](https://github.com/CaptainPRICE/Wire-Data-New/tree/master/Wire-Data/expression2/e2shared/lib/static-reflector/src)). I can post some screenshots of this.. But, I am not sure if I would be allowed to publish it..

**Comment by oldmud0** [comment]
Let's not overkill

**Comment by Anticept** [comment]
@TomyLobo support ticket submitted

**Comment by Anticept** [comment]
@TomyLobo What wiki are we talking about? If this was a wiki in a fork, then that's on the forker.

**Comment by TomyLobo** [comment]
@Anticept yeah, oops, i only saw the 404 and "Welcome to the wire wiki!"
