### ISSUE TITLE
Screen Tool Error

### ISSUE THREAD

**Issue by suunrider** [wiremod/wire#981]
Steps to reproduce:  

1. Place a screen with two values and a constant with Value 1 as a number
2. Wire the two inputs of the screen to the constant value
3. Set Value 1 of the constant value to any string
4. Update constant value

Then you get this error:
```
addons/wiremod/lua/entities/gmod_wire_screen.lua:88: attempt to perform arithmetic on local 'value' (a string value)
stack traceback:
	addons/wiremod/lua/entities/gmod_wire_screen.lua:88: in function 'DrawNumber'
	addons/wiremod/lua/entities/gmod_wire_screen.lua:110: in function <addons/wiremod/lua/entities/gmod_wire_screen.lua:101>
	[C]: in function 'xpcall'
	addons/wiremod/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	addons/wiremod/lua/entities/gmod_wire_screen.lua:101: in function <addons/wiremod/lua/entities/gmod_wire_screen.lua:98>
```

**Comment by Divran** [comment]
Ideally, whenever an entity's outputs change, anything wired to it should be unwired if it's no longer the same type.
