### ISSUE TITLE
--- Missing Vgui material texturemissing

### ISSUE THREAD

**Issue by MidNightGamingMNG** [wiremod/wire#984]
Hi there!

Okay, so, I recently installed Wire onto my server and everything was working fine until this error came up. It seems whenever I disable Wire for my server, it fixes it but whenever it is enabled, I get this error message in my client console: --- Missing Vgui material texturemissing

What is this and how can I fix it?
Thank you!

**Comment by AbigailBuccaneer** [comment]
This is nothing to worry about, and is expected (if a bit messy).

The `surface.GetTextureID` API is very lacking - we can ask it for an ID but not check if that ID is valid. So at some point, the code checks:

```Lua
if CogTexture == surface.GetTextureID("texturemissing") then CogTexture = nil end
```

The idea being that `"texturemissing"` is an *intentionally* missing texture, and so we'd hope it'd have the same ID as any other missing texture, so we can check if `CogTexture` is a missing texture.

There's probably a better way to do this; I don't know who wrote this code. (Maybe `surface.GetTextureID` returns some constant that we can just hardcode, or maybe we could just use `surface.GetTextureSize` to check.)

I'll leave this open but as a cleanup task rather than a bug.

**Comment by MidNightGamingMNG** [comment]
Oh, yeah, I also forgot to mention, and is crucial, Whenever someone tries to connect to the server with that... error, thing... it will just say "Sending Client Info" over and over again. Once, I waited 10 minutes but I still didn't spawn in my server.

Sorry for leaving this crucial information out...

**Comment by AbigailBuccaneer** [comment]
That sounds like a completely unrelated bug. You can confirm by commenting out `"texturemissing"` line.

**Comment by MidNightGamingMNG** [comment]
Hmm. If it's completely unrelated, then how come whenever I remove Wire, it fixes the server and people can join again but whenever Wire is added to the server, it does that glitch again.

I've also contacted the host of my server and they say that it's a Wire problem as they've looked into the server files also. What could be causing this?

**Comment by bigdogmat** [comment]
I've never had a problem with wire causing issues on a server and/or other servers I've gone on, you may want to reinstall wire and makes sure all files are validated. As for your host I'm not to sure how they would know, as the most info you can get would come from server console so I'm not to sure how they'd know that's your issue.

Also are you using the workshop version or git version?

**Comment by MidNightGamingMNG** [comment]
I am using the version that the server provides me, right now. But previously, I tried workshop and git versions but they also caused the same problem.

**Comment by AbigailBuccaneer** [comment]
> Hmm. If it's completely unrelated, then how come whenever I remove Wire, it fixes the server and people can join again but whenever Wire is added to the server, it does that glitch again.

I'm not saying it's not Wire's fault, merely that the `--- Missing vgui material texturemissing` issue isn't causing you to fail to connect.

**Comment by MidNightGamingMNG** [comment]
Well... If it's not that... Then I have no clue what Wire is doing to cause the problem. I COULD try and reinstall it (Git and workshop, not together) and see what happens from there?

**Comment by oldmud0** [comment]
You should make a new issue for whatever trouble you're having.

**Comment by MidNightGamingMNG** [comment]
Alrighty then. I'll close this issue and create a new one, since I know now that Missing Vgui isn't the problem. Before I make a new issue though, I'm going to reinstall both versions (git and workshop) and if none work, then I'll start a new issue. If it works, you won't be seeing any more issues from me for a while.
