### ISSUE TITLE
Can't get on my server

### ISSUE THREAD

**Issue by MidNightGamingMNG** [wiremod/wire#985]
Hi there.

Previously, I made an issue with the Missing VGui stuff. It turns out, that wasn't the problem. I have a new problem now with a new error in the console. I downloaded the Git version of wire first which lead to the same, Missing VGui glitch but when I tried the workshop version, what I got in the console (of my Garry's Mod client) is this:

```
[ERROR] addons/wire-master/lua/wire/stools/hdd.lua:9: attempt to call field 'setToolMenuIcon' (a nil value)
  1. unknown - addons/wire-master/lua/wire/stools/hdd.lua:9
   2. include - [C]:-1
    3. LoadTools - lua/wire/tool_loader.lua:6
     4. unknown - lua/wire/tool_loader.lua:573
      5. include - [C]:-1
       6. unknown - lua/weapons/gmod_tool/stools/wire.lua:6
        7. include - [C]:-1
         8. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/stool.lua:142
          9. include - [C]:-1
           10. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:363
            11. include - [C]:-1
             12. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua:10
```
It then repeated itself over and over again. What exactly is this and how can it be fixed?

Kind Regards,
MidNightGamingMNG

**Comment by Divran** [comment]
This is caused by you having an old version of this file
https://github.com/wiremod/wire/blob/master/lua/wire/tool_loader.lua#L422-L426

**Comment by MidNightGamingMNG** [comment]
Well... I've tried the Git version, that won't work and when I tried the workshop version, that came up. I don't know what's happening.

I know you said it's an old version but I mean, the other one (Git) won't work so workshop's the only one I gotta go with here.

**Comment by Divran** [comment]
Make sure you don't have two copies of wire installed at the same time

On Wed, Oct 7, 2015 at 10:05 AM, MidNightGamingMNG <notifications@github.com

**Comment by MidNightGamingMNG** [comment]
I don't. I have made sure of it too.

**Comment by MidNightGamingMNG** [comment]
Hello? I really need help with this...

**Comment by AbigailBuccaneer** [comment]
@MidNightGamingMNG run the server with nothing *except* the latest Git `master` version of Wiremod installed. See what happens.

**Comment by MidNightGamingMNG** [comment]
Sure, I shall try this and come back with the results.

**Comment by MidNightGamingMNG** [comment]
Okay... I tried running the server with nothing but the latest Git master version but it still came up with the same results. It did spurt something new into the console though that I haven't seen before. This is what it shows:

Connecting to 119.252.189.27:27410...
Connected to 119.252.189.27:27410

Sandbox
Map: gm_construct
Players: 1 / 25
Build: 6148
Server Number: 1

MNG's Fun Time

sandbox
gm_construct
25
76561198051971393
Attemped to precache unknown particle system "generic_smoke"!
Requesting 13 lua files from the server
ConVarRef wire_expression2_file_max_size doesn't point to an existing ConVar
ConVarRef wire_expression2_quotatick doesn't point to an existing ConVar
ConVarRef wire_expression2_quotahard doesn't point to an existing ConVar
ConVarRef wire_expression2_quotasoft doesn't point to an existing ConVar
ConVarRef wire_expression2_unlimited doesn't point to an existing ConVar
ConVarRef gmod_physiterations doesn't point to an existing ConVar
PREP OK
Warning: WorldTwoTextureBlend found on a non-displacement surface (material: gm_construct/flatgrass). This wastes perf for no benefit.
clientside lua startup!
Requesting texture value from var "$dummyvar" which is not a texture value (material: NULL material)
--- Missing Vgui material 

It came up with the normal server information but then it came up with the Wire_expression2 things.
Could this be the reason why all of this is happening?

**Comment by bigdogmat** [comment]
Only thing that'd cause that is if you're setting expression2 settings in the cfg file, as they don't exist until wire is loaded.

**Comment by MidNightGamingMNG** [comment]
If it isn't something I should worry about, what is causing the problem? I still have no clue!

**Comment by bigdogmat** [comment]
As I stated in the first sentence of my last post it happens when gmod ties to set a convar from a cfg file before the convar is created. In this case you're trying to set e2 convars from the cfg file, but those convars don't exist until wire has loaded.

This doesn't effect anything except those covars won't be set.

**Comment by MidNightGamingMNG** [comment]
I got that but I would like to know what's causing such a major problem on the server that no one can join.

**Comment by bigdogmat** [comment]
Only thing I can guess is their's something wrong with your server, as I've never had any issue with wiremod doing this, and out of everyone I know who has had wiremod installed they have never had the issue either.

If we don't have any kind of error to go off of any kind or something of the sort, then I don't think their's much we can help you with. You say it's an issue when you install wiremod, but even then it could just  be gmod not working with addons.

Unless someone else here can think of anything that'd cause this issue then the only thing I can say is make a bug report for gmod or post on facepunch about it.
