### ISSUE TITLE
E2: gmatch not working?

### ISSUE THREAD

**Issue by bigdogmat** [wiremod/wire#986]
For some reason patterns don't work in gmatch, even using a gmod wiki example 

```
"my awesome stuff 12":gmatch("( %a )")
```
Will return nothing, though it seems non-pattern searches like 
```
"my awesome stuff 12":gmatch("a")
```
Work fine, I think it's the helper function but I'd have no idea what's wrong with it.

On another note why does match return an array when the lua function only returns the matched text?

**Comment by Divran** [comment]
that's because your pattern `( %a )` matches nothing in your string

**Comment by bigdogmat** [comment]
Ah thanks for letting me know, I'll start using some pattern tutorials. As for match returning a table, I knew that gmatch returned varargs but I didn't know match did, so thanks for letting me know about that as well
