### ISSUE TITLE
Expression 2 editor settings not saving

### ISSUE THREAD

**Issue by Cre8or** [wiremod/wire#987]
A small request, but it's been on my mind for too long...

Whenever the editor is initialised, both the editor's position and size parameters are reset to default values. This not only happens whenever a map is loaded, but also after using
`wire_expression2_reloadeditor`
despite having set the values for the settings using
`wire_expression2_editor_size "1360_850"`
`wire_expression2_editor_pos "280_115"`

It's probably a simple fix, but as someone who spends most of their time in the E2 editor, it particularily bothers me that these two settings don't persist.

Perhaps marking these convars as archive might solve the issue, and if not, it can most likely be done by retrieving the convars whenever the editor is opened.

**Comment by Divran** [comment]
I just tested it, it works fine for me

**Comment by bigdogmat** [comment]
I'm having this issue as well, went into game, set editor size, checked convar and it was set to the correct size, reloaded game, it reset.

**Comment by Divran** [comment]
The file where these convars are saved are probably set to read only for you

**Comment by bigdogmat** [comment]
I don't even have a client.cfg folder, I have a client.vdf

**Comment by Cre8or** [comment]
I have `client.vdf` and `gmod_cvars_cl.txt`, both have the commands in them, though with differing values. Could you perhaps explain which one of them is the important one, as I'm guessing one of them overrides the other?

Alternatively, can I not simply force the game to use my settings by inserting the commands in `autoexec.cfg`, or will that also be overwritten by something else?

Lastly, none of my files are set to read-only mode, so I'm fairly sure that isn't what's causing it.

**Comment by Divran** [comment]
Unless valve changed it, it should be in client.cfg. Try making a file
named client.cfg

**Comment by Cre8or** [comment]
I tried adding a client.cfg with the following lines in it:

**Comment by bigdogmat** [comment]
The function is set to save across sessions, so issue shouldn't be wires fault.

**Comment by Cre8or** [comment]
From an analytical point of view, I'm observing that the editor uses the default values whenever it boots up for the first time. This implies that it ignores all and any traditional config files - whether it reads them, or whether it successfully retrieves the values and then simply ignores them is a different thing.

A good starting point would be to debug the functions related to the editor's startup, in order to see whether it successfully read the config files or not. From then on it should be a tad easier to pinpoint the issue.

**Comment by bigdogmat** [comment]
It's one function [CreateClientConVar](http://wiki.garrysmod.com/page/Global/CreateClientConVar), and within that function there's a argument for wether to save or not across sessions, it's set to true.

It's either the way the editor is saving the info as I put in my last comment ( highly unlikely), or it's a gmod issue.

**Comment by Cre8or** [comment]
Can you point me to the file where this is located? I'd like to have a go at debugging the convars.

**Comment by bigdogmat** [comment]
I already told you how, using the CreateClientConVar, which creates the convar and gets the value of it if client has already set it. And I know it sets the convar to the correct value, but it doesn't save them in the client file, which is a gmod issue.

If you must see the 2 lines of code that do this,
https://github.com/wiremod/wire/blob/master/lua/wire/client/wire_expression2_editor.lua#L189-L218

**Comment by Cre8or** [comment]
Actually, the problem is this: https://github.com/wiremod/wire/blob/master/lua/wire/client/wire_expression2_editor.lua#L212

When checking whether the position + size exceeds the window, ScrH() is being compared with **x** + h when it should be **y** + h. This is what's causing my window to shrink back to default values.

Another bug is that people using "-1_-1" for the position are forced to use default values, because the condition has `x < 0 or y < 0 or` in it. This is not necessary, since you can already limit the values of x and y to never go lower than -1 at lines 202 and 203.

Here are my fixes, and they work splendidly:


```
Lines 202-203:
	x = tonumber(x)
	y = tonumber(y)
```
```
Line 211:
	if x + w > ScrW() or y + h > ScrH() then
```

Also, as a final note, I'd like to point out that you're using ScrW() / ScrH() aswell as surface.ScreenWidth() / surface.ScreenHeight(). I'm not sure of the reason behind this, but perhaps you could normalise the code so as to only use one set of functions.

**Comment by Divran** [comment]
You're right, that's a mistake in the code.

-1_-1 is only used once, when you use the editor for the first time, unless you enter it manually. But if you do, it's changed to not -1, -1 before the exceeds window check.

I'll fix the check now
