### ISSUE TITLE
GPULib 32-screen limit

### ISSUE THREAD

**Issue by immibis** [wiremod/wire#997]
Reference: https://github.com/wiremod/wire/blob/master/lua/wire/gpulib.lua#L69 and the GetRT function.

Currently, GPULib never create more than 32 render-targets. This used to be because of a limitation of Garry's Mod - [every render-target needed a script file](https://github.com/wiremod/wire/commit/dc4842e47352019e2a9f8fefbba43228b364f1a5), so there had to be some hard-coded limit.

The current code creates rendertargets as needed (with `GetRenderTarget`), and only uses 32 as a maximum limit. Is there any reason not to make this configurable, or unlimited?

One argument for the limit is that it makes it possible to know if something is leaking rendertargets, since eventually the limit will be reached. If that's desirable then a (client-side) configurable limit would be better than unlimited.

**Comment by TomyLobo** [comment]
ok if you testedit and it works now, change it and make a PR

**Comment by oldmud0** [comment]
A configurable limit should be added with a default of 128.

**Comment by Divran** [comment]
128 sounds like too many. I think default 32 is fine. I've never seen a server hit the limit with 32.

**Comment by TomyLobo** [comment]
That limit should be client-configurable

**Comment by AbigailBuccaneer** [comment]
A client-configurable limit would be excellent but will need a lot of thought put into it (eg. if you decrease the limit while it's at the limit it should dynamically destroy rendertargets, and the choice of which to destroy is maybe not obvious).

**Comment by TomyLobo** [comment]
It would destroy the higher indices, of course :P

**Comment by thegrb93** [comment]
Each RT is 1MB of VRAM. 64 of them might be fine.
