### ISSUE TITLE
"Data Transferer" is misspelled

### ISSUE THREAD

**Issue by immibis** [wiremod/wire#999]
"Transfe**rr**er" should have two r's (3 including the last one). (It still looks weird, though)

**Comment by suunrider** [comment]
Someone should fix this

**Comment by oldmud0** [comment]
Nice... `gmod_wire_data_transferer` is misspelled. If it's renamed, then dupes that use the old name break.

**Comment by suunrider** [comment]
Better break backwards compatibility than having this embarrassing mistake.

**Comment by Divran** [comment]
@suunrider lolno nobody gives a fuck about this spelling mistake

Also we can just alias it and it'll work fine

**Comment by AbigailBuccaneer** [comment]
Petition to change the name to "That which transfers data"

**Comment by immibis** [comment]
Or "That witch transfers data", keeping with tradition. :P

**Comment by TomyLobo** [comment]
We're in [good company] (https://en.wikipedia.org/wiki/HTTP_referer).

**Comment by oldmud0** [comment]
hahahaha ok let's keep this misspelling then

**Comment by AbigailBuccaneer** [comment]
![image](https://user-images.githubusercontent.com/908758/35700438-e4306082-078a-11e8-8873-fea837b4e0e1.png)

From everything I can see, they're both equally acceptable, but `transferer` is more common. Apparently the rules for whether the final consonant gets doubled depends on whether the final syllable is stressed or not, and the whether people say 'TRANSfer' or 'transFER' seems to be a regional thing, so I'm happy to accept the internet's majority rule here.
